{100}{}{Eu não consigo acreditar nas coisas que você fez.}
{101}{}{Eu não me importo. Eu estou ferido. Me cure.}
{102}{}{Hngh!}
{103}{}{Não. Eu fiz um voto de não machucar a vida, mas eu não
 ajudarei você.}
{104}{}{A falta de inteligencia não é desculpa para o que você tem
 feito. Vai embora, eu não falarei mais com você.}
{105}{}{Ah minha nossa, você esta seriamente ferido. Aqui, deixe-me ajudar você.}
{106}{}{Bem-vindo de volta, }
{107}{}{. Como
 vai a busca?}
{108}{}{Esta indo ok.}
{109}{}{Eu preciso de ajuda.}
{110}{}{Lol?}
{111}{}{Ah. Sim. Aqui, eu achei estes. Tente eles quando você precisar de um
 boost.}
{112}{}{Bom, mantenha o bom trabalho. É deixe-me saber se você
 precisar de alguma coisa.}
{113}{}{O que eu posso fazer por você?}
{114}{}{Eu preciso de cura.}
{115}{}{Eu preciso de algumas drogas.}
{116}{}{Eu preciso de mais alguns stimpaks.}
{117}{}{Doh!}
{118}{}{Duh!}
{119}{}{Eu não estou autorizado a dar nenhum a você. Lamento.}
{120}{}{Obrigado, de qualquer maneira.}
{121}{}{Eu tenho uma necessidade urgente delas. Sem as drogas a seguranca
 da Vault esta em jogo.}
{122}{}{Lamento, eu não posso da-las a você.}
{123}{}{Bem, já que você poe desse modo. Mas não diga a ninguém que
 eu deixei você ter estas. Elas são extremamente viciantes e
 perigosas de usar.}
{124}{}{Obrigado.}
{125}{}{Os stimpaks estão sendo racionados. Você e bem-vindo para o que
 nos tivermos no conteiner medico na parede. Leve tantos quantos você
 precisar, mas use eles aos poucos. Demorara um tempo antes que nos
 possamos conseguir mais um pouco pra você.}
{126}{}{Hmm. Vamos ver se você esta ferido.}
{127}{}{Você parece ok pra mim. Volte se você precisar de um pouco de cura.}
{128}{}{Você parece ferido. Aqui, deixe-me ajudar você.}
{129}{}{Se você precisar de cura volte aqui pra mim ou use
 alguns dos stimpaks que nos temos. Você pode pegar mais
 stimpaks da parede.}
{130}{}{Deite-se aqui e nós começaremos o processo de cura.}
{131}{}{Você esta completamente curado. Tome conta de si próprio
 no futuro, mas volte se você precisar de mais cura.}
{132}{}{Os scanners medicos detectaram um pouco de envenenamento mortal por
 radiação. Você gostaria que nos tentassemos um cura? Levara um tempo.}
{133}{}{Os scanners medicos detectaram um pouco de envenenamento serio por
 radiação. Você gostaria que nos tentassemos um cura? Levara um tempo.}
{134}{}{Os scanners medicos detectaram um pouco de envenenamento maior por
 radiação. Você gostaria que nos tentassemos um cura? Levara um tempo.}
{135}{}{Os scanners medicos detectaram um pouco de envenenamento leve por
 radiação. Você gostaria que nos tentassemos um cura? Levara um tempo.}
{136}{}{Você vê o medico da Vault-13.}
{137}{}{Certo, bom, vamos dar uma olhada então. Fique parado por um instante.}
{138}{}{Não.}
{139}{}{Certo, faca.}
{140}{}{Quanto tempo?}
{141}{}{Quanto vai demorar e quanta radiação você consegue
 remover?}
{142}{}{Não.}
{143}{}{Sim.}
{144}{}{É seu corpo.}
{145}{}{Levara }
{146}{}{ minutos. Você quer
 começar o processo?}
{147}{}{Não.}
{148}{}{Sim.}
{149}{}{Levara }
{150}{}{ minutos. Sera capaz de
 remover por volta de }
{151}{}{ por cento. Você quer
 começar o processo?}
{152}{}{Não.}
{153}{}{Sim.}
{154}{}{Isto vai ser realmente, realmente doloroso.}
{155}{}{Certo, isto não deve machucar de modo algum.}
{156}{}{Certo, você deve estar se sentindo muito melhor. Seja cuidadoso
 lá fora.}
{157}{}{Eu ouvi sobre o que você fez, salvando a Vault. Obrigado a você.}
{158}{}{[Mais]}
{159}{}{O medico se recusa a falar com você.}
{160}{}{Por favor não faca isso.}
{161}{}{Fui envenenado!}
{162}{}{Estou muito irradiado, me ajude! Minha pele está derretendo!}
{163}{}{De nada. Tchau!}
{164}{}{[Continuar]}
{165}{}{Vai levar menos de }
{166}{}{uma hora.}
{167}{}{ eu vou conseguir te curar completamente da sua doença por radiação, que é }
{168}{}{ horas. Eu vou conseguir te curar completamente da sua doença por radiação, que é }
{169}{}{ e meia}
{170}{}{ O RadAway funcionaria um pouco mais rápido, mas não temos nenhum de sobra. Vamos começar?}
{171}{}{Hmph.}
{172}{}{Procurando mais uma dose? Em que tipo de encrenca você tem se metido? Eu não deveria fazer isso, mas toma, pega estes. Mas chega pra você, e tome cuidado.}
{1000}{}{Médico}
{1001}{}{Cura}
{1100}{}{Eu estou aqui o tempo todo, para oferecer assistencia e cura.}
{1101}{}{Eu posso curar você se você esta ferido.}
{2000}{}{Hã, preciso remover uma protuberância. Meu sexto dedo do pé.}
{2001}{}{Um sexto dedo?! Interessante. Muito interessante... }
{2002}{}{Bom, posso tentar. Sem garantias, claro, já que você ficou em contato com a radiação externa bem mais tempo do que prevíamos... pode ser que ele cresça de novo.}
{2003}{}{Então ele DE FATO cresceu de novo!}
{2010}{}{Não me importo. Quero ele fora antes que vire um novo eu.}
{2020}{}{Deixa pra lá, então. Eu tinha outras perguntas...}
{2030}{}{Esquece, então. Talvez eu volte.}
{3000}{}{Certo, então. Deite-se aqui, e vamos começar a operação agora mesmo.}
{3001}{}{Aquele seu amiguinho já deve ter ido embora agora. Espero. É difícil espremer todo aquele pus mutante da medula óssea. Enfim, aqui está.}
{3010}{}{Que bom que isso foi resolvido, então. Escuta, tinha outra coisa que eu precisava...}
{3020}{}{É bom mesmo ele não crescer de novo dessa vez. Estou falando sério.}
{3030}{}{Muito obrigado. Posso voltar.}
