{100}{}{Você vê o Smitty.}
{101}{}{Você vê um grande homem musculoso.}
{102}{}{Bom dia. O que eu posso fazer por você?}
{103}{}{O que você quer?}
{104}{}{Eu posso perguntar seu nome?}
{105}{}{Eu preciso que você conserte estas partes pra mim, para que eu possa consertar suas fazendas hidroponicas.}
{106}{}{Eu gostaria de comprar algo.}
{107}{}{Eu posso fazer algumas perguntas pra você?}
{108}{}{Nada, obrigado. Vejo você por ai.}
{109}{}{Uhhh . . .}
{110}{}{Eu recomendaria que você verificasse a loja do Tine, bem a um dos lados do portao. Eu realmente
 não vendo qualquer coisa aqui; eu troco com o Tine ou com os mercadores do Hub por mercadorias.}
{111}{}{Por que? Todos apenas me chamam de 'Smitty'.
 Provavelmente porque eu sou o ferreiro local.}
{112}{}{Pergunte.}
{113}{}{Aonde você conseguiu todo o equipamento da sua loja?}
{114}{}{Você faz tudo de que aqui?}
{115}{}{Você consegue fazer armas e balas?}
{116}{}{Nada mais, obrigado.}
{117}{}{Eu lamento, eu não acho que eu possa ajudar você. Tente o Zimmerman.}
{118}{}{Com certeza.}
{119}{}{Por que? qualquer ferreiro competente consegue fazer seu proprio anvil!
 claro, eu realmente apenas aprendi o oficio na pratica, mas eu fiz a maioria
 das minhas proprias ferramentas.}
{120}{}{Na maior parte eu faco e reparo ferramentas e implements aqui. Eu
 tambem conserto coisas pros mercadores do Hub. Com a ajuda de Miles,
 o quimico, eu recarrego balas de tempos em tempos.}
{121}{}{Bem, construir armas e fazer cartuchos exige maquinaria, e eu simplesmente
 não tenho as ferramentas pra isso. Mas com a ajuda de Miles, o quimico, eu posso
 recarregar os velhos        já que eu posso lancar balas.}
{122}{}{Sim, eu consigo consertar isto. Me de algum tempo.}
{123}{}{Aqui esta você. [Smitty da a você as partes consertadas.]}
{124}{}{Eu já consertei as partes. Você precisa da-las ao Miles agora.}
{125}{}{Obrigado por consertar as fazendas. Se você achar um rifle de plasma, traga-o
 de volta aqui. Eu conheco alguns truques que eu posso fazer com os injetores.}
{126}{}{Bem, eu tenho um bem aqui.}
{127}{}{Então você achou um rifle de plasma?}
{128}{}{Me de ele e eu darei uma olhada nele. [Smitty toma o rifle de plasma de
 você, puxa as ferramentas dele, e comeca a tinker com ele.]}
{129}{}{Ai, eu acho que isso e tudo. [Smitty da de volta pra você seu rifle de plasma.]
 Tente isso pelo tamanho.}
{130}{}{Como eu disse antes, se você obter um rifle de plasma e traze-lo de
 volta aqui, eu posso melhora-lo um pouco pra você.}
{131}{}{Bom ver você de novo. Espero que você esta indo bem.}
{1000}{}{Ah, caramba, é você! Fiquei te vendo descer a estrada com aquela moto. Não acontece com tanta frequência hoje em dia. Normalmente são só as carroças de brahmin... }
{1010}{}{[Mais]}
{1100}{}{Se você um dia achar a moto pequena demais, é só me procurar, ouviu? Tenho um sidecar velho parado num armazém não muito longe daqui. Os catadores podem buscar e eu conserto ele pra você!}
{1110}{}{Quanto isso me custaria?}
{1120}{}{Obrigado pela oferta. Vou ter isso em mente.}
{1200}{}{Vai levar um dia, e algumas pessoas precisam ser pagas... Eu diria que umas 1.000 tampinhas devem cobrir.}
{1201}{}{ ... Pensando bem, você livrou a gente dos Regulators. Então fazemos assim, vou chamar uns favores. O que você acha?}
{1210}{}{Aqui está o dinheiro. Mãos à obra!}
{1220}{}{Talvez outra hora.}
{1230}{}{Obrigado, Smitty!}
{1300}{}{Parece que você não está com as tampinhas. Me procure quando estiver abastecido.}
{1301}{}{Ótimo! Vou levar a moto pra minha oficina. [Smitty pega suas chaves.] }
{1310}{}{[Wait]}
{1400}{}{Essa moto está zerada! [Smitty te devolve as chaves.] Tomei a liberdade de modificar umas coisinhas aqui e ali. Nada muito chique, só um para-lama novo, como você pode ver, e consertei aquele velocímetro quebrado. Agora cuide bem dela!}
{1500}{}{Não esqueça. Vou estar aqui!}
{1510}{}{Você consegue melhorar minha motocicleta?}
