{100}{}{Você vê: Phrax dos Crypts.}
{101}{}{Essa geladeira não é sua propriedade. Eu sugiro fortemente não tocar nela.}
{102}{}{Por que não?}
{103}{}{Você vai me obrigar?}
{104}{}{Não, vou chamar meus companheiros Crypts e a gente vai te fazer sentir dor.}
{105}{}{Oh.}
{106}{}{Pertence aos Crypts. Não é sua.}
{107}{}{Eu só quero uma bebida.}
{108}{}{Ah, tá.}
{109}{}{Não tem bebida nenhuma nessa geladeira. Fique longe dela.}
{110}{}{Você não deveria mexer com coisas que não são suas. E essa definitivamente não é sua. Jogada burra.}
{111}{}{Você pode ser um Crypt, mas esta sala não é pra você. Não mexa em nada.}
{112}{}{Você veio ao lugar errado na hora errada.}
{113}{}{Esta sala não é pra você. Não toque em nada, ou vai se ver comigo.}
{114}{}{[DONE]}
{115}{}{[MAIS]}
{116}{}{O Phil tem mais coragem que qualquer Tolo!}
{117}{}{BABUÍNOS ROXOS!}
{118}{}{Os Brahmin têm mais juízo que um Tolo.}
{119}{}{Os Tolos são tão fracos que até o Lex consegue surrar todos eles.}
