{100}{}{Ah não.}
{101}{}{Você engatilhou uma faixa de laser detonando algum tipo de mecanismo de defesa.
 Você leva um ponto de dano.}
{102}{}{Você engatilhou uma faixa de laser detonando algum tipo de mecanismo de defesa.
 Você leva }
{103}{}{ pontos de dano.}
{104}{}{Você tropeçou num fio de laser, acionando algum tipo de mecanismo de defesa.}
{105}{}{ tropeçou num fio de laser, acionando algum tipo de mecanismo de defesa.}
