{100}{}{Você vê: Skizzer.}
{101}{}{Você vê um homem.}
{102}{}{Colega Crypt, você tá indo bem.}
{103}{}{Você um Tolo idiota.}
{104}{}{Bem-vindo a Scrapheap. Mantenha as mãos pra você mesmo.}
{105}{}{Tá.}
{106}{}{Você se comporta, e o Rock não vai ter que pegar no seu pé.}
{107}{}{Tá.}
{108}{}{[pronto]}
{109}{}{Ele se recusa a falar com você.}
{110}{}{Você vai ser enterrado, Tolo!}
{111}{}{Vou chutar uns traseiros pra valer! Estou pronto pra guerraaaa!}
{112}{}{Crypts mandam! E Tolos babam!}
{113}{}{Nós somos os portadores da morte!}
