{1000}{}{}
{1001}{}{}
{1002}{}{Recuar!}
{1003}{}{Recuar!}
{1004}{}{Eu não vou morrer por isto!}
{1005}{}{Isso é o bastante pra mim}
{1006}{}{}
{1007}{}{Você cometeu um grande erro!}
{1008}{}{Nós não gostamos do seu tipo por aqui!}
{1009}{}{Eu não gosto do seu tipo}
{1010}{}{}
{1011}{}{}
{1012}{}{}
{1013}{}{}
{1014}{}{Agora você morre!}
{1015}{}{}
{1016}{}{}
{1017}{}{Você vai morrer}
{1018}{}{Vamos ver quão forte você é...}
{1019}{}{Miserável}
{1020}{}{Ataque!}
{1021}{}{}
{1022}{}{}
{1023}{}{Eu estive fazendo isto por anos, miserável}
{1024}{}{Você não é bom/boa o bastante}
{1025}{}{Esse foi seu ultimo erro}
{1026}{}{Amador}
{1027}{}{}
{1028}{}{Ai! Seu/Sua filho da...}
{1029}{}{Eu vou matar você por isso}
{1030}{}{}
{1031}{}{Ai, meu braço}
{1032}{}{Maldição, meu braço esta destruido!}
{1033}{}{Meu braço!}
{1034}{}{Ai, meu braço}
{1035}{}{Maldição, meu braço esta destruido!}
{1036}{}{Meu braço!}
{1037}{}{Ooph!}
{1038}{}{Ai}
{1039}{}{Gasp!}
{1040}{}{Minhas costelas!}
{1041}{}{Ai, minha perna}
{1042}{}{Você vai pagar por isso!}
{1043}{}{Meu joelho!}
{1044}{}{Ai, minha perna}
{1045}{}{Você vai pagar por isso!}
{1046}{}{Meu joelho!}
{1047}{}{Eu não consigo ver!}
{1048}{}{Meu olho!}
{1049}{}{}
{1050}{}{Uuuuuu, minha virilha!}
{1051}{}{}
{1052}{}{}
{1053}{}{Urp!}
{1054}{}{Oof!}
{1055}{}{Isso doi}
{1100}{}{Reforços!}
{1101}{}{}
{1102}{}{Medico!}
{1103}{}{Recuar! Recuar!}
{1104}{}{Recuar! Recuar!}
{1105}{}{Você pode ter vencido a batalha...}
{1106}{}{}
{1107}{}{}
{1108}{}{Eu vou ensinar a você algumas maneiras}
{1109}{}{Você e historia!}
{1110}{}{Atacar!}
{1111}{}{Vamos enterrar este perdedor!}
{1112}{}{Tome isto!}
{1113}{}{Agora eu tenho você!}
{1114}{}{Agora você morre!}
{1115}{}{Você gosta disto?}
{1116}{}{}
{1117}{}{Não deveria começar o que você não pode terminar}
{1118}{}{Melhor você rezar para os deuses!}
{1119}{}{}
{1120}{}{}
{1121}{}{Vejo você no Inferno}
{1122}{}{}
{1123}{}{Isso e o melhor que você pode fazer?}
{1124}{}{Vamos perdedor. Me de uma luta!}
{1125}{}{Tente mirar da próxima vez}
{1126}{}{Civil}
{1127}{}{}
{1128}{}{}
{1129}{}{Minha cara!}
{1130}{}{Você quebrou meu nariz!}
{1131}{}{Você quebrou meu braço!}
{1132}{}{Um braço destruido não vai me parar!}
{1133}{}{}
{1134}{}{Você quebrou meu braço!}
{1135}{}{Um braço destruido não vai me parar!}
{1136}{}{}
{1137}{}{Hmph! Isso não machucou nada}
{1138}{}{Uck!}
{1139}{}{Você vai se arrepender disso!}
{1140}{}{Uph! Você pagara por isso}
{1141}{}{Ai, minha perna}
{1142}{}{Você pagara por isso!}
{1143}{}{Esse tipo de ferida não me parara!}
{1144}{}{Ai, minha perna}
{1145}{}{Esse tipo de ferida não me parara!}
{1146}{}{Você me pagara!}
{1147}{}{Eu estou cego!}
{1148}{}{Meus olhos estão queimando!}
{1149}{}{Eu não consigo ver!}
{1150}{}{Uuu, minha virilha!}
{1151}{}{Ack!}
{1152}{}{Oof!}
{1153}{}{Eu...não...consigo...respirar...}
{1154}{}{Eu...não...consigo...respirar...}
{1155}{}{Seu/Sua miseravel...}
{1200}{}{Tenho que sair daqui!}
{1201}{}{Eu voltarei...}
{1202}{}{Você não vai me matar hoje!}
{1203}{}{Mais tarde miserável!}
{1204}{}{Você não me viu pela ultima vez!}
{1205}{}{Você pagara por isto - mais tarde!}
{1206}{}{Você e historia!}
{1207}{}{Carne fresca...}
{1208}{}{Eu vou dançar no seu tumulo}
{1209}{}{Atenção Todo Mundo! É pratica de tiro ao alvo!}
{1210}{}{}
{1211}{}{Eu vou apreciar isto...}
{1212}{}{}
{1213}{}{Não se incomode de gritar por misericordia...}
{1214}{}{Esta é a melhor parte...}
{1215}{}{}
{1216}{}{Vou alimentar os cachorros com você}
{1217}{}{Não deveria começar o que você não pode terminar}
{1218}{}{Espero que você não morra muito rápido}
{1219}{}{Só um de nos está saindo fora}
{1220}{}{Morra!}
{1221}{}{Eu como miseraveis como você no café da manhã}
{1222}{}{Eu vou alimentar minha iguana de estimação com você}
{1223}{}{A ultima coisa que você verá é minha face com um sorriso largo}
{1224}{}{Este é meu trabalho favorito}
{1225}{}{Você é uma piada}
{1226}{}{Isso é o melhor que você pode fazer?}
{1227}{}{}
{1228}{}{}
{1229}{}{Muito lento!}
{1230}{}{Perdedor}
{1231}{}{Não na cara!}
{1232}{}{Ai!}
{1233}{}{Você quebrou meu nariz!}
{1234}{}{Ai, meu braço}
{1235}{}{Você quebrou meu braço!}
{1236}{}{Um braço destruido não vai me parar!}
{1237}{}{Ai, meu braço}
{1238}{}{Você quebrou meu braço!}
{1239}{}{Um braço destruido não vai me parar!}
{1240}{}{Ai, minhas costelas!}
{1241}{}{Esse foi seu único tiro livre}
{1242}{}{Eu vou fazer você pagar por isso}
{1243}{}{Minha perna!}
{1244}{}{Você vai pagar por isso!}
{1245}{}{Argh!}
{1246}{}{Minha perna!}
{1247}{}{}
{1248}{}{Argh!}
{1249}{}{Argh! Meus olhos!}
{1250}{}{Meu olho! Você pagara por isso!}
{1251}{}{}
{1252}{}{Uuuuuu, minha virilha!}
{1253}{}{Uuu! Eu vou aprender esse movimento...}
{1254}{}{Urp!}
{1255}{}{Urp!}
{1256}{}{Urp!}
{1257}{}{Ai! Eu vou matar você por isso!}
{1300}{}{Você ouviu alguém chamar meu nome?}
{1301}{}{}
{1302}{}{Socorro!}
{1303}{}{Aaaaahhhh!}
{1304}{}{Fujam!}
{1305}{}{}
{1306}{}{Eu vou fazer você parecer um pretzel rachado}
{1307}{}{Olhe! Seu sapato esta desamarrado!}
{1308}{}{Espere até eu pegar você...}
{1309}{}{}
{1310}{}{Eu vou dar a você uma pancada tal}
{1311}{}{}
{1312}{}{Tome isto!}
{1313}{}{Eu tenho você agora!}
{1314}{}{Eu tenho você agora!}
{1315}{}{Você gosta disto?}
{1316}{}{Coma isto}
{1317}{}{Esta será uma experiência transformadora de vida}
{1318}{}{Eu não vou me arrepender disto, vou?}
{1319}{}{}
{1320}{}{}
{1321}{}{}
{1322}{}{Há, não me acertou!}
{1323}{}{Nhá, nhá!}
{1324}{}{Há!}
{1325}{}{Nhá, nhá!}
{1326}{}{Que foguete!}
{1327}{}{Não consegue me tocar}
{1328}{}{Cuidado com o cabelo!}
{1329}{}{Meu denfe! Eu pefdi um denfte!}
{1330}{}{Meus denfes! Meus denfes!}
{1331}{}{Ai, meu braço}
{1332}{}{Ai!}
{1333}{}{Ai, pare com isso!}
{1334}{}{Ai, meu braço}
{1335}{}{Ai!}
{1336}{}{Ai, pare com isso!}
{1337}{}{Eu não quero ser um canhoto!}
{1338}{}{Uph!}
{1339}{}{Isso não foi muito legal}
{1340}{}{Você pode se arrepender de fazer isso, Eu certamente me arrependi}
{1341}{}{Eu acho que eu vou desmaiar}
{1342}{}{O que pensa que eu sou, um saco de pancada?}
{1343}{}{Você não é muito legal}
{1344}{}{Ai, minha perna}
{1345}{}{Ai! Não faca isso!}
{1346}{}{!}
{1347}{}{Ai, minha perna}
{1348}{}{Ai! Você e mau!}
{1349}{}{}
{1350}{}{Por que esta tão escuro?}
{1351}{}{Onde todo mundo foi?}
{1352}{}{Ouch, minha retina!}
{1353}{}{Uuuuuu, minha virilha!}
{1354}{}{Minha virilha é a virilha de fogo!}
{1355}{}{Minha virilha é a virilha de fogo!}
{1356}{}{Eu...não...consigo...respirar...}
{1357}{}{}
{1358}{}{A dor, a dor...}
{1400}{}{Fora daqui!}
{1401}{}{Tchau!}
{1402}{}{Aaaaahhhh!}
{1403}{}{}
{1404}{}{}
{1405}{}{Vejo você por ai}
{1406}{}{}
{1407}{}{Você e historia!}
{1408}{}{A hora de brincar acabou}
{1409}{}{Alguém esta morrendo}
{1410}{}{Negocie comigo}
{1411}{}{}
{1412}{}{Tome isto!}
{1413}{}{Morra!}
{1414}{}{Perdedor}
{1415}{}{Miseravel}
{1416}{}{}
{1417}{}{Espero que isto doa}
{1418}{}{}
{1419}{}{}
{1420}{}{Eu enterrarei você}
{1421}{}{Você esta morto}
{1422}{}{Não me acertou!}
{1423}{}{Não estou impressionado}
{1424}{}{}
{1425}{}{Você e lento}
{1426}{}{Você e inutil}
{1427}{}{}
{1428}{}{Isso doi}
{1429}{}{Meus olhos!}
{1430}{}{Ai! Meu nariz...}
{1431}{}{Ai!}
{1432}{}{Ai! Meu braço!}
{1433}{}{Ai! Você quebrou ele!}
{1434}{}{Ai!}
{1435}{}{Ai! Meu braço!}
{1436}{}{Ai! Você quebrou ele!}
{1437}{}{Ai!}
{1438}{}{Ouch!}
{1439}{}{Ooph!}
{1440}{}{Gasp!}
{1441}{}{Oof!}
{1442}{}{Ugh!}
{1443}{}{Ai!}
{1444}{}{Ai! Meu joelho!}
{1445}{}{Ai! Minha perna!}
{1446}{}{Ai!}
{1447}{}{Ai! Meu joelho!}
{1448}{}{Ai! Minha perna!}
{1449}{}{Eu estou cego!}
{1450}{}{Eu não consigo ver!}
{1451}{}{Meu olho!}
{1452}{}{Minha virilha!}
{1453}{}{Aieee!}
{1454}{}{Maldicao, isso doi}
{1455}{}{Ooof!}
{1456}{}{Urp!}
{1457}{}{Eu...não...consigo...respirar...}
{1500}{}{Eu estou fora daqui!}
{1501}{}{Eu fui!}
{1502}{}{}
{1503}{}{Talvez isto não era uma ideia tão boa}
{1504}{}{Um cara poderia se machucar aqui!}
{1505}{}{}
{1506}{}{Hora de aumentar a velha contagem de corpos}
{1507}{}{O trabalho de um guarda nunca esta terminado}
{1508}{}{}
{1509}{}{De novo não. A munição e tão cara!}
{1510}{}{Melhor eles não me prenderem com os deveres do enterro}
{1511}{}{Quem você pensa que você e?}
{1512}{}{Agora aqui esta um profissional trabalhando}
{1513}{}{Você não deveria ter se levantado esta manha}
{1514}{}{Você vai tirar uma soneca no po!}
{1515}{}{}
{1516}{}{É agora eu deito você pra descansar...}
{1517}{}{}
{1518}{}{É a sobrevivencia do mais apto, e você esta fora de forma}
{1519}{}{}
{1520}{}{Finja de morto!}
{1521}{}{Eu vou ser a ultima coisa que você verá!}
{1522}{}{Eu não sou assim fácil}
{1523}{}{Aw! Você não me acertou?}
{1524}{}{Continue tentando e um dia você acertara!}
{1525}{}{}
{1526}{}{Quer que fique parado pra você?}
{1527}{}{}
{1528}{}{Ai!}
{1529}{}{Minha cabeca esta zumbindo!}
{1530}{}{Ai! Minha orelha!}
{1531}{}{Ai, meu braço}
{1532}{}{Você quebrou meu braço!}
{1533}{}{Ai... você e muito desarmante...}
{1534}{}{Ai, meu braço}
{1535}{}{Você quebrou meu braço!}
{1536}{}{Ai... você e muito desarmante...}
{1537}{}{Você deve pensar que você e muito bom/boa}
{1538}{}{Ugh!}
{1539}{}{Oof!}
{1540}{}{Quer vir e tentar isso de novo?}
{1541}{}{Quando você crescer, eu aposto que você quer ser tão bom quanto eu}
{1542}{}{Pelo menos isso não foi tão feio quanto sua cara!}
{1543}{}{Ouch!  Maldito seja!}
{1544}{}{Ai!}
{1545}{}{Apenas um arranhao ...e alguns ossos quebrados}
{1546}{}{Não precisava desse joelho mesmo}
{1547}{}{Ack!}
{1548}{}{Apenas um arranhao ...e alguns ossos quebrados}
{1549}{}{Não precisava desse joelho mesmo}
{1550}{}{Eu estou cego!}
{1551}{}{Agora eu não tenho que ver sua cara feia}
{1552}{}{Agora eu não tenho que ver sua cara feia}
{1553}{}{Minha virilha! Minha virilha!}
{1554}{}{Você esta tornando isto realmente pessoal}
{1555}{}{}
{1556}{}{La se vai minha vida sexual!}
{1557}{}{Ah, a dor!}
{1558}{}{Ai! Agora isso e o que eu chamo doloroso!}
{1600}{}{Ei, eu poderia morrer aqui!}
{1601}{}{Talvez isto não era uma boa ideia}
{1602}{}{Eu desisto!}
{1603}{}{Socorro!}
{1604}{}{Aaaaahhhh!}
{1605}{}{Deixe-me sair daqui!}
{1606}{}{Finalmente, um pouco de ação de verdade!}
{1607}{}{Você não deveria mexer comigo!}
{1608}{}{Agora eu posso provar a mim mesmo em batalha!}
{1609}{}{Isto esta... certo?}
{1610}{}{}
{1611}{}{Isto pode ser divertido!}
{1612}{}{Tome isto!}
{1613}{}{Agora eu tenho você!}
{1614}{}{Tome isto!}
{1615}{}{Você gosta disto?}
{1616}{}{Morra, sua aberracao saqueadora!}
{1617}{}{Sua aberracao mutante!}
{1618}{}{Atacar!}
{1619}{}{}
{1620}{}{}
{1621}{}{}
{1622}{}{Há, não me acertou!}
{1623}{}{Você não me acertou!}
{1624}{}{Movimento esperto, huh?}
{1625}{}{Isso e o melhor que você pode fazer?}
{1626}{}{Ei! Isso poderia ter machucado!}
{1627}{}{}
{1628}{}{Ai!}
{1629}{}{Minha cara! O que você fez?}
{1630}{}{Aggghhh! Minha cara! Não! Não!}
{1631}{}{Ai, meu braço}
{1632}{}{Meu braço, o que você fez com ele?}
{1633}{}{Aggghhh!}
{1634}{}{Ai, meu braço}
{1635}{}{Meu braço, o que você fez com ele?}
{1636}{}{Aggghhh!}
{1637}{}{Ai!}
{1638}{}{}
{1639}{}{Ferida! Ferida! Ferida!}
{1640}{}{Eu não tenho certeza se eu gosto disto...}
{1641}{}{Vá com calma comigo, eu sou apenas um iniciante}
{1642}{}{Oof!}
{1643}{}{Ack!}
{1644}{}{Ouch! Isso doi!}
{1645}{}{Ai, minha perna}
{1646}{}{Minha perna, o que você fez com ela?}
{1647}{}{Aggghhh!}
{1648}{}{Ai, minha perna}
{1649}{}{Minha perna!}
{1650}{}{Aggghhh!}
{1651}{}{Eu não consigo ver!}
{1652}{}{Meus olhos!}
{1653}{}{Me ajudem!}
{1654}{}{Ai! Minha virilha!}
{1655}{}{Uuuuuu, seu/sua pequeno sujo...}
{1656}{}{Urp!}
{1657}{}{Essas são minha entranhas?}
{1658}{}{Eu...não...consigo...respirar...}
{1659}{}{Maldicao, isso doi!}
{1700}{}{Eu não vou morrer por isto!}
{1701}{}{O trabalho não vale isto!}
{1702}{}{Eu vou sumir!}
{1703}{}{La se vai minha rep...}
{1704}{}{Eu não tenho queixas contra você}
{1705}{}{Me ponha longe deste estúpido}
{1706}{}{Outro hooligan não!}
{1707}{}{Você acabou de cruzar a linha!}
{1708}{}{Você não vai embora com isso aqui!}
{1709}{}{Não no meu turno!}
{1710}{}{Eu vou desgracar você!}
{1711}{}{}
{1712}{}{Isto e o que eu faco com causadores de problemas!}
{1713}{}{Desliguem as luzes...}
{1714}{}{Isto ensinara você a não causar problemas}
{1715}{}{Eu vou abrir você!}
{1716}{}{}
{1717}{}{Vamos ver o quao forte você é.}
{1718}{}{Pensa que você e algum tipo de pessoa famosa, huh?}
{1719}{}{Não deveria começar o que você não pode terminar}
{1720}{}{Você esperava sair bem com isto?}
{1721}{}{Eu como prostitutas como você no cafe da manha}
{1722}{}{Você torna meu trabalho fácil}
{1723}{}{Sem finesse, amigo}
{1724}{}{Cara, você não tem musculo!}
{1725}{}{Isso e o melhor que você pode fazer?}
{1726}{}{Você não esperava me tocar, esperava?}
{1727}{}{Vamos, veado. Me de uma luta!}
{1728}{}{Você quebrou meu nariz!}
{1729}{}{Ai! Maldito seja!}
{1730}{}{Maldicao! Isso doi!}
{1731}{}{Ai, meu braço}
{1732}{}{Eu vou congelar você por isso!}
{1733}{}{Isso foi um erro}
{1734}{}{Ai, meu braço}
{1735}{}{Eu vou matar você por isso!}
{1736}{}{Isso foi um erro}
{1737}{}{Outra perna destruida não!}
{1738}{}{Ai!}
{1739}{}{Isso foi um erro}
{1740}{}{Ai! Você tentando me derrubar?}
{1741}{}{Ai!}
{1742}{}{Isso doi...}
{1743}{}{Eu não consigo ver!}
{1744}{}{Ouch!}
{1745}{}{Eu não preciso ver você pra estrangular você!}
{1746}{}{Uuuu! Nas bolas!}
{1747}{}{Uuuu! Nas bolas!}
{1748}{}{Uuuu! Nas bolas!}
{1749}{}{Ack! Minhas joias!}
{1750}{}{Ack! Minhas joias!}
{1751}{}{Urp!}
{1800}{}{Misericordia!}
{1801}{}{Alguém me ajude!}
{1802}{}{Por favor pare!}
{1803}{}{Socorro!}
{1804}{}{Aaaaahhhh!}
{1805}{}{Misericordia!}
{1806}{}{Hmm, uh, pare!}
{1807}{}{Eu não gosto do seu tipo...}
{1808}{}{Eu realmente esperava que não chegasse a isto...}
{1809}{}{Eu creio que eu tenho que defender a mim mesmo}
{1810}{}{Eu creio que eu tenho que defender a mim mesmo}
{1811}{}{Eu realmente esperava que não chegasse a isto...}
{1812}{}{Tome isto!}
{1813}{}{Você não deveria ter comecado isto!}
{1814}{}{Você pediu por isto!}
{1815}{}{Você gosta disto?}
{1816}{}{}
{1817}{}{Seu/Sua bruto!}
{1818}{}{Eu não quero fazer isto!}
{1819}{}{}
{1820}{}{Eu não queria esta luta, mas...}
{1821}{}{Seu/Sua malcriado!}
{1822}{}{}
{1823}{}{Você não me acertou!}
{1824}{}{Uau, isso poderia ter machucado!}
{1825}{}{Whew! Eu ainda estou vivo!}
{1826}{}{Ei! Isso poderia ter machucado!}
{1827}{}{Whew! Eu ainda estou vivo!}
{1828}{}{Minha cara! Minha cara!}
{1829}{}{Ai! Isso doi!}
{1830}{}{}
{1831}{}{Ai, meu braço}
{1832}{}{Ai!}
{1833}{}{Você quebrou meu braço!}
{1834}{}{Ai, meu braço}
{1835}{}{Wahhhh!}
{1836}{}{Meu Deus! Meu braço!}
{1837}{}{Ai! Isso realmente doi!}
{1838}{}{Eu acho que eu vou desmaiar}
{1839}{}{Ouch!}
{1840}{}{}
{1841}{}{Isso doi!}
{1842}{}{So me deixe em paz!}
{1843}{}{Ohhh, dor!}
{1844}{}{Ai, minha perna}
{1845}{}{Meu joelho!}
{1846}{}{Ai!}
{1847}{}{Ai, minha perna}
{1848}{}{Meu joelho!}
{1849}{}{Aaaarrrrggghhh!}
{1850}{}{Eu estou cego! Ah Deus, Eu estou cego!}
{1851}{}{Minha cara! Meus olhos! Arrrrgh!}
{1852}{}{Meus olhos!}
{1853}{}{Ooooooooo, minha virilha! Ooooooo...}
{1854}{}{Oww...Ela queima!}
{1855}{}{Urp!}
{1856}{}{Ooorp! aoooww...}
{1857}{}{Eu...não...consigo...respirar...}
{1858}{}{A dor, a dor...}
{1900}{}{Eu estou levando-o na fuga}
{1901}{}{Eu voltarei!}
{1902}{}{Mais tarde miseravel!}
{1903}{}{Isso foi divertido, mas eu fui!}
{1904}{}{Você pagara por isto - mais tarde!}
{1905}{}{Vamos fazer isto de novo em breve!}
{1906}{}{Eu vou prender suas orelhas de volta!}
{1907}{}{Carne fresca!}
{1908}{}{Você fez o meu dia!}
{1909}{}{Você vai ser minha puto!}
{1910}{}{Eu vou prender suas orelhas de volta!}
{1911}{}{Eu vou me vingar!}
{1912}{}{}
{1913}{}{}
{1914}{}{Por favor não implore. A morte deve ser digna.}
{1915}{}{Eu espero que você não morra muito rapido}
{1916}{}{Tem quaisquer palavras finais?}
{1917}{}{Tome isto!}
{1918}{}{Morra! Morra! Morra! Morra! Morra!}
{1919}{}{Morra!}
{1920}{}{Vamos abrir você um pouco...}
{1921}{}{Você e comida de cachorro, amigo.}
{1922}{}{Você nem ao menos me acertou}
{1923}{}{}
{1924}{}{Vamos, miseravel. Me de uma luta!}
{1925}{}{Isso e o melhor que você pode fazer?}
{1926}{}{Isto vai ser mais fácil do que eu pensei}
{1927}{}{Isto vai ser mais fácil do que eu pensei}
{1928}{}{Essa será uma cicatriz legal!}
{1929}{}{Eu estou comecando a ficar chateado}
{1930}{}{Faca isso de novo, porco}
{1931}{}{Você me acertou!}
{1932}{}{}
{1933}{}{Você quebrou meu braço, mas eu quebrarei seu pescoco}
{1934}{}{}
{1935}{}{É apenas um arranhao...}
{1936}{}{Você quebrou meu braço, então eu vou quebrar seu pescoco}
{1937}{}{}
{1938}{}{Oof! Eu vou estrangular você por isso...}
{1939}{}{Oof!}
{1940}{}{Oof!}
{1941}{}{Eu amo o som de costelas rachando!}
{1942}{}{}
{1943}{}{Arg!}
{1944}{}{Eu amo o som de ossos triturando}
{1945}{}{}
{1946}{}{Você quebrou minha perna, mas eu quebrarei seu pescoco}
{1947}{}{Eu amo o som de ossos triturando}
{1948}{}{}
{1949}{}{Você quebrou minha perna, mas eu quebrarei seu pescoco}
{1950}{}{Ei, Eu estou cego}
{1951}{}{Eu não consigo ver. Isso tornara isto justo}
{1952}{}{Meus olhos, puto!}
{1953}{}{Oof, minha virilha!}
{1954}{}{Esse foi um movimento corajoso}
{1955}{}{}
{1956}{}{}
{1957}{}{Então esse e o modo que você quer jogar}
{1958}{}{Ack!}
{2000}{}{Ataque alguém mais, por favor!}
{2001}{}{Tenha misericordia!}
{2002}{}{Alguém me ajude!}
{2003}{}{Por favor pare!}
{2004}{}{}
{2005}{}{Eu não vou morrer por isto!}
{2006}{}{Espere até eu pegar você...}
{2007}{}{}
{2008}{}{Ei você!}
{2009}{}{Você não é bem-vindo aqui}
{2010}{}{Ninguem vai tomar este lugar...}
{2011}{}{Quem você pensa que você e?}
{2012}{}{}
{2013}{}{}
{2014}{}{Isto e o que nos fazemos com os vermes!}
{2015}{}{Sua aberracao mutante!}
{2016}{}{}
{2017}{}{Vou alimentar os cachorros com você}
{2018}{}{Isto você aprendera!}
{2019}{}{Certo. Você pediu por isto.}
{2020}{}{Seu/Sua animal!}
{2021}{}{}
{2022}{}{}
{2023}{}{Eu já vi Brahmin mais espertos do que você}
{2024}{}{Whew!}
{2025}{}{Eu não sou coisa fácil}
{2026}{}{Gracas aos deuses}
{2027}{}{Você não me acertou!}
{2028}{}{Maldicao, isso arde!}
{2029}{}{Aggghhh!}
{2030}{}{Uuu!}
{2031}{}{Aggghhh! Meu braço}
{2032}{}{Meu braço!}
{2033}{}{Ai!}
{2034}{}{Aggghhh! Meu braço}
{2035}{}{Meu braço!}
{2036}{}{Ai!}
{2037}{}{Ai!}
{2038}{}{Isso foi bastante doloroso...}
{2039}{}{Argh!}
{2040}{}{Ouch!}
{2041}{}{}
{2042}{}{Oof!}
{2043}{}{Ai!}
{2044}{}{Aggghhh! Minha perna}
{2045}{}{Minha perna!}
{2046}{}{Minha perna!}
{2047}{}{Aggghhh! Minha perna}
{2048}{}{Minha perna!}
{2049}{}{Ai!}
{2050}{}{Aggghhh! Eu estou cego!}
{2051}{}{Maldito seja até o inferno!}
{2052}{}{Meu olho!}
{2053}{}{ouch}
{2054}{}{Oooooooooo!}
{2055}{}{Eu...não...consigo...respirar...}
{2056}{}{}
{2057}{}{A dor, a dor...}
{2058}{}{Maldicao!}
{2100}{}{Eu fui!}
{2101}{}{Misericordia! Misericordia!}
{2102}{}{Por favor pare!}
{2103}{}{Socorro!}
{2104}{}{}
{2105}{}{Eu tenho de parar com a confusão}
{2106}{}{}
{2107}{}{}
{2108}{}{Eu realmente não quero fazer isto}
{2109}{}{Eu vou ter que socar você}
{2110}{}{Eu realmente não quero fazer isto}
{2111}{}{Espero que eu não me machuque}
{2112}{}{}
{2113}{}{Você pediu por isto!}
{2114}{}{Eu não estou com disposicao para uma luta, mas...}
{2115}{}{}
{2116}{}{Por que você comecou isto?}
{2117}{}{Eu não quero fazer isto!}
{2118}{}{Não tome isto como pessoal...}
{2119}{}{Espero que eu não machuque você muito gravemente}
{2120}{}{Você percebe que você comecou isto?}
{2121}{}{}
{2122}{}{Whew!}
{2123}{}{Você realmente não tem que fazer isto}
{2124}{}{Ei! Isso poderia ter machucado!}
{2125}{}{Nós não deveriamos estar lutando}
{2126}{}{Violencia não resolvera o problema de verdade}
{2127}{}{Seu coração não esta nisto}
{2128}{}{Não na cara!}
{2129}{}{Ah, minha cabeca!}
{2130}{}{Ai! Minha orelha!}
{2131}{}{Ai, meu braço}
{2132}{}{Ouch!}
{2133}{}{Você quebrou meu braço!}
{2134}{}{Ai, meu braço}
{2135}{}{Ugh!}
{2136}{}{Você quebrou meu braço!}
{2137}{}{Ai, minha perna}
{2138}{}{Meu joelho!}
{2139}{}{Ai! Minha perna esta destruida!}
{2140}{}{Ai, minha perna}
{2141}{}{Meu joelho!}
{2142}{}{Ai! Minha perna esta destruida!}
{2143}{}{Eu estou cego!}
{2144}{}{Eu tenho lagrimas de sangue!}
{2145}{}{Isso doi...}
{2146}{}{Uuuuuu, minha virilha!}
{2147}{}{}
{2148}{}{}
{2149}{}{Eu...não...consigo...respirar...}
{2150}{}{Minhas joias!}
{2151}{}{Uuuu! Eu preciso deitar...}
{2200}{}{Corra!}
{2201}{}{Você não me matara!}
{2202}{}{Eu voltarei!}
{2203}{}{Meus amigos pegarao você por mim!}
{2204}{}{Você pagara por isto -- mais tarde!}
{2205}{}{Nós somo os Escolhidos! Você morre mais tarde!}
{2206}{}{Sua morte chega!}
{2207}{}{Seu tempo esta acabado!}
{2208}{}{Armas humanas não podem me prejudicar!}
{2209}{}{Você sofrera, sofrera muito!}
{2210}{}{Eu esmago cranios nos meus dedos!}
{2211}{}{Nós somos o futuro e nós rimos de você!}
{2212}{}{Este e o fim!}
{2213}{}{Ninguem salva você agora!}
{2214}{}{Agora você morre!}
{2215}{}{Agora você morrera uma Morte Ardente!}
{2216}{}{Você entra no Inferno hoje!}
{2217}{}{Eu zombo conforme eu mato}
{2218}{}{Seu sangue e meu vinho!}
{2219}{}{Agora você morre!}
{2220}{}{Assim e como você morre!}
{2221}{}{Sofra, humano!}
{2222}{}{Por que você luta?}
{2223}{}{Isso e o melhor que os humanos podem fazer?}
{2224}{}{Você não tem força!}
{2225}{}{Você me faz rir muito!}
{2226}{}{Isso foi um ataque?}
{2227}{}{Você não é nada!}
{2228}{}{Ahhhgh! Minha cara!}
{2229}{}{Minha cara! Você sofrera!}
{2230}{}{Ahhhgh! Eu vou rasgar você em pedacos!}
{2231}{}{Ahhhgh!}
{2232}{}{Você chama isso de dor? Eu zombo!}
{2233}{}{Ahhhgh! Eu quebro seu pescoco por isso!}
{2234}{}{Ahhhgh!}
{2235}{}{Você chama isso de dor? Eu zombo!}
{2236}{}{Ahhhgh! Eu quebro seu pescoco por isso!}
{2237}{}{Argh!}
{2238}{}{Grrrr!}
{2239}{}{Esse foi um erro - da sua parte!}
{2240}{}{Argh!}
{2241}{}{Grrrr!}
{2242}{}{Hahahaha! Você chama isso de dor!}
{2243}{}{Arrr!}
{2244}{}{Ahhhgh! Minha perna}
{2245}{}{Você chama isso de dor? Eu zombo!}
{2246}{}{Ahhhgh! Eu quebro você como um raminho!}
{2247}{}{Ahhhgh! Minha perna}
{2248}{}{ Você chama isso de dor? Eu zombo}
{2249}{}{Ahhhgh! Eu quebrarei seu pescoco por isso!}
{2250}{}{Ahhhgh! Humano miseravel! Eu estou cego!}
{2251}{}{Ahhhgh! Dor! O que você fez!}
{2252}{}{Ahhhgh! Eu torturarei você por muitos dias!}
{2253}{}{Essa é a fraqueza humana!}
{2254}{}{Você não pode me machucar lá!}
{2255}{}{Você e humano estúpido!}
{2256}{}{Por que você me ataca lá?}
{2257}{}{Sua morte será dolorosa, humano!}
{2258}{}{Morte para você por isso...}
{2300}{}{Recuar! Recuar!}
{2301}{}{O Mestre destruira você por isto!}
{2302}{}{Isto não acabou!}
{2303}{}{A vinganca do Mestre atingira você!}
{2304}{}{Você pagara por isto - mais tarde!}
{2305}{}{Eu banquetearei com seu coração outro dia!}
{2306}{}{Sua morte e iminente}
{2307}{}{Você enraiveceu seus chefes, agora pague o preço!}
{2308}{}{Eu vi para os meus inimigos, empunhando a Chama Sagrada!}
{2309}{}{Aqueles que se opoem a Unidade devem ser varridos!}
{2310}{}{Morte aos inimigos do Mestre!}
{2311}{}{Nós somos o futuro e você e historia!}
{2312}{}{Este e o fim!}
{2313}{}{Nem homem ou deus pode salvar você agora!}
{2314}{}{Bem vindo ao seu tumulo!}
{2315}{}{Este e o toque do Mestre!}
{2316}{}{Você entrara no Inferno este dia!}
{2317}{}{Você morrera na minha mao}
{2318}{}{Em nome do Mestre, morra!}
{2319}{}{Agora desce o golpe da morte!}
{2320}{}{Eu queimarei você com a Chama Sagrada!}
{2321}{}{Sofra, humano!}
{2322}{}{Lamentavel! Por que você ainda assim luta?}
{2323}{}{Isto e o melhor que a humanidade tem a oferecer?}
{2324}{}{Seu ataque e tão fraco quanto seu espirito!}
{2325}{}{Esse foi seu ultimo erro}
{2326}{}{O Mestre me protege de seus inimigos!}
{2327}{}{Você não pode ferir os Escolhidos}
{2328}{}{Você sofrera por isso!}
{2329}{}{Você sofrera por isso!}
{2330}{}{Ahhhgh! Eu rasgarei você em pedacos!}
{2331}{}{Ahhhgh! Meu braço}
{2332}{}{Ahhhgh! Eu não sou derrotado tão facilmente!}
{2333}{}{Ahhhgh! Eu quebrarei todos os seus ossos por isso}
{2334}{}{Ahhhgh! Meu braço}
{2335}{}{Ahhhgh! Eu não sou derrotado tão facilmente!}
{2336}{}{Ahhhgh! Você se arrependera disso}
{2337}{}{Argh!}
{2338}{}{Duf!}
{2339}{}{Mestre!}
{2340}{}{Você me humilhou...}
{2341}{}{Argh!}
{2342}{}{Grrr!}
{2343}{}{Ahhhgh! Minha perna}
{2344}{}{Ahhhgh! Eu não sou derrotado tão facilmente!}
{2345}{}{Ahhhgh! Eu quebrarei você por isso!}
{2346}{}{Ahhhgh! Minha perna}
{2347}{}{Ahhhgh! Eu não sou derrotado tão facilmente!}
{2348}{}{Ahhhgh! Eu esmagarei você por isso!}
{2349}{}{Ahhhgh! Humano miseravel! Você me cegou!}
{2350}{}{Ahhhgh! A dor! O que você fez!}
{2351}{}{Ahhhgh! Você ganhou dias de agonia por isso!}
{2352}{}{Eu não compartilho essa fraqueza com você, humano!}
{2353}{}{Meus quadris são mais fortes do que o seu, humano!}
{2354}{}{Que tatica patetica, humano!}
{2355}{}{O Mestre me protege, humano!}
{2356}{}{Sua morte fica mais dolorosa, humano!}
{2357}{}{Oof! Talvez eu devesse testar seus pontos fracos}
{2400}{}{Mestre! Por que você me abandonou!}
{2401}{}{O Mestre me vingara!}
{2402}{}{Mestre, me perdoe, mas eu devo fugir!}
{2403}{}{Você não teme a retribuição?}
{2404}{}{Chama Sagrada, me proteja!}
{2405}{}{Me ajude Mestre, me ajude!}
{2406}{}{Os inimigos do Mestre devem queimar na Chama Sagrada!}
{2407}{}{Os inimigos do Mestre devem morrer!}
{2408}{}{A unidade prevalecera!}
{2409}{}{O sangue das Crianças será vingado!}
{2410}{}{A paz deve ser alimentada com o sangue dos inimigos!}
{2411}{}{Me de a Unidade, ou me de a Morte!}
{2412}{}{Não corra, nos somos seus amigos}
{2413}{}{Morra em nome do Mestre!}
{2414}{}{Contemplem a chama sagrada!}
{2415}{}{Beije o fogo, toque o tumulo!}
{2416}{}{Unidade!}
{2417}{}{Ninguem pode parar a causa da paz!}
{2418}{}{Você não parara a Unidade!}
{2419}{}{Pela Unidade!}
{2420}{}{Mestre, me abencoe!}
{2421}{}{Queime no Fogo Sagrado!}
{2422}{}{O Mestre me protege!}
{2423}{}{Louvem o Mestre, você não pode me fazer mal!}
{2424}{}{Obrigado a você, Mestre!}
{2425}{}{A misericordia do Mestre e incrivel!}
{2426}{}{Eu sou protegido pela Chama Sagrada!}
{2427}{}{Você não pode fazer mal as Crianças}
{2428}{}{Agghhh! O que me acertou?}
{2429}{}{Mestre! Proteja-me!}
{2430}{}{Oof!}
{2431}{}{Meu braço!}
{2432}{}{O Mestre curara minha feridas...}
{2433}{}{Mestre! O que eles fizeram a mim!}
{2434}{}{Ai, meu braço}
{2435}{}{O Mestre curara minha feridas...}
{2436}{}{Mestre! O que eles fizeram a mim!}
{2437}{}{Oof!}
{2438}{}{Ack!}
{2439}{}{Mestre, me proteja!}
{2440}{}{Mestre, me vingue!}
{2441}{}{Gulp!}
{2442}{}{Ai, minha perna}
{2443}{}{Você quebrou minha perna!}
{2444}{}{Mestre! O que eles fizeram a mim!}
{2445}{}{Minha perna!}
{2446}{}{Você quebrou minha perna!}
{2447}{}{Mestre! O que eles fizeram a mim!}
{2448}{}{Mestre, Eu estou cego!}
{2449}{}{Mestre, meus olhos, eles queimam!}
{2450}{}{Mestre, Eu não consigo ver!}
{2451}{}{Uuuuuu, minha virilha!}
{2452}{}{Mestre!}
{2453}{}{Mestre, me proteja da dor!}
{2454}{}{Eu...não...consigo...respirar...}
{2455}{}{Mestre, nossos inimigos são crueis!}
{2456}{}{Mestre, nossos inimigos são crueis!}
{2500}{}{Por que você me abandonou!}
{2501}{}{Eu serei vingado!}
{2502}{}{Perdoe-me, mas eu devo fugir!}
{2503}{}{Você não teme a retribuição?}
{2504}{}{Chama Sagrada, me proteja!}
{2505}{}{Chama Sagrada, guie a minha fuga!}
{2506}{}{Nossos inimigos devem queimar na Chama Sagrada!}
{2507}{}{Nossos inimigos devem morrer!}
{2508}{}{A Unidade prevalecera!}
{2509}{}{O sangue das Crianças será vingado!}
{2510}{}{A paz deve ser alimentada com o sangue dos inimigos!}
{2511}{}{}
{2512}{}{Morra!}
{2513}{}{Morra em nome da Chama!}
{2514}{}{Contemplem a Chama Sagrada!}
{2515}{}{Em nome da Paz, morra!}
{2516}{}{Unidade!}
{2517}{}{Ninguem pode parar a causa da paz!}
{2518}{}{Pagao!}
{2519}{}{Não corra, nos somos seus amigos!}
{2520}{}{Mestre, me abencoe!}
{2521}{}{Queime no Fogo Sagrado, barbaro!}
{2522}{}{O Mestre me protege!}
{2523}{}{Louvem a Chama Sagrada, você não pode me fazer!}
{2524}{}{Seu deus e falso!}
{2525}{}{Seu mal derrota a si próprio!}
{2526}{}{Eu sou protegido pela Chama Sagrada!}
{2527}{}{Você não pode fazer mal as Crianças}
{2528}{}{Agghhh! O que me acertou?}
{2529}{}{Mestre! Proteja-me!}
{2530}{}{Ai!}
{2531}{}{Ai, meu braço}
{2532}{}{Você quebrou meu braço!}
{2533}{}{O que você fez a mim!}
{2534}{}{Ai, meu braço}
{2535}{}{Você quebrou meu braço!}
{2536}{}{Seu/Sua pecador!}
{2537}{}{Ouch!  Isso doi!}
{2538}{}{!*&^@#!}
{2539}{}{Ah, oh, isso doi!}
{2540}{}{Ouch!}
{2541}{}{Ooph!}
{2542}{}{Oof!}
{2543}{}{Ai, minha perna}
{2544}{}{Você quebrou minha perna!}
{2545}{}{O que você fez?}
{2546}{}{Ai, minha perna}
{2547}{}{Você quebrou minha perna!}
{2548}{}{^%@!!}
{2549}{}{Eu não consigo ver!}
{2550}{}{Meus olhos!}
{2551}{}{Eu fui cegado pelos meus pecados!}
{2552}{}{Uuuuuu, minha virilha!}
{2553}{}{Uuuuuu, você e o mau verdadeiro!!}
{2554}{}{Chama Sagrada, proteja minha semente!}
{2555}{}{Eu...não...consigo...respirar...}
{2556}{}{Eu...não...consigo...respirar...}
{2557}{}{Nossos inimigos são crueis!}
{2600}{}{A Igreja pegara você!}
{2601}{}{A Igreja pode tomar conta de si mesma!}
{2602}{}{Socorro!}
{2603}{}{}
{2604}{}{Algum outro patsy pode brigar com você}
{2605}{}{Eu não vou morrer por isto!}
{2606}{}{}
{2607}{}{Vamos enterrar este arruaceiro!}
{2608}{}{Hora de morrer!}
{2609}{}{Você não é permitido aqui!}
{2610}{}{Hora de tirar o lixo pra fora...}
{2611}{}{Você pagara pelos seus "pecados"...}
{2612}{}{Tome isto!}
{2613}{}{Seu/Sua louco!}
{2614}{}{Agora, você morre!}
{2615}{}{Vamos, seu/sua oportunista, vamos lutar!}
{2616}{}{Eu vou chicotear você}
{2617}{}{Eu vou chicotear você}
{2618}{}{Hora de morrer...}
{2619}{}{Hora de morrer...}
{2620}{}{Beije minha chama sagrada, amigo!}
{2621}{}{Beije minha chama sagrada, amigo!}
{2622}{}{Há, não me acertou!}
{2623}{}{Que estúpido!}
{2624}{}{Há, você não me acertou!}
{2625}{}{Você e até mesmo um perdedor maior do que os zumbis!}
{2626}{}{Alguém já ensinou a você como mirar?}
{2627}{}{Você e até mesmo um perdedor maior do que os zumbis!}
{2628}{}{Ugh!}
{2629}{}{Oof!}
{2630}{}{Maldicao! Isso doi!}
{2631}{}{Ai, meu braço}
{2632}{}{Você vai pagar por essa!}
{2633}{}{Eu quebrarei ambos os bracos por isso!}
{2634}{}{Ai, meu braço}
{2635}{}{Você vai pagar por essa!}
{2636}{}{Eu quebrarei ambos os bracos por isso!}
{2637}{}{Ai, minha perna}
{2638}{}{Você vai pagar por essa!}
{2639}{}{Seu/Sua ^&!$%@! Eu vou pegar você!}
{2640}{}{Ai, minha perna}
{2641}{}{Você vai pagar por essa!}
{2642}{}{Ai!}
{2643}{}{Eu vou por você em apuros por isso!}
{2644}{}{Meu olho! Você pagara por isso!}
{2645}{}{Esse foi um tiro verdadeiramente barato!}
{2646}{}{Ah, você me pegou deslealmente!}
{2647}{}{Maldicao, isso doi!}
{2648}{}{!%@$ #^%!@# ^#$%@^#!!!}
{2649}{}{Ah, maldicao!}
{2650}{}{}
{2651}{}{}
{2700}{}{Esta batalha e desnecessaria}
{2701}{}{Eu serei vingado!}
{2702}{}{Seu triunfo será de duração curta!}
{2703}{}{Você não derrotara a Unidade}
{2704}{}{Meus servos me protegerao!}
{2705}{}{Esperanca! Eu devo ter esperança!}
{2706}{}{Seus pecados agora serao punidos}
{2707}{}{Meus inimigos devem morrer! Morra!}
{2708}{}{A Unidade prevalecera! Prevaleca!}
{2709}{}{Não será permitido a você destruir nosso mundo}
{2710}{}{O futuro deve ser preservado! Preservado!}
{2711}{}{Me de a Unidade, ou me de a Morte! Morte!}
{2712}{}{Morra!}
{2713}{}{Você será totalmente destruido}
{2714}{}{Você selou a sua destruição}
{2715}{}{Você pagara pelo que você fez! Fez!}
{2716}{}{Unidade!}
{2717}{}{Ninguem pode parar a causa da paz! Paz!}
{2718}{}{Nada espera você alem do fogo. Fogo!}
{2719}{}{Deixe este ser seu epitafio}
{2720}{}{Você não é nada. Nada!}
{2721}{}{Este e o fim da sua existência}
{2722}{}{Seus esforcas são inuteis! Inuteis!}
{2723}{}{Você não pode prevalecer contra mim!}
{2724}{}{Você errou de novo}
{2725}{}{Seu mal derrota a si próprio!}
{2726}{}{Você não sobrevivera}
{2727}{}{Sua performance e inadequada}
{2728}{}{Ferida na cabeca}
{2729}{}{Essa dor foi desagradavel}
{2730}{}{Isso não me incapacitara}
{2731}{}{Você acha que você por me ferir ai?}
{2732}{}{Ferida menor, humano, menor}
{2733}{}{Essa dor foi levemente desagradavel}
{2734}{}{Nenhum dano nos circuitos/organicos que não possa ser reparados depois}
{2735}{}{Você morre! Morra!}
{2736}{}{Sistemas atingidos, compensando}
{2737}{}{Sistemas atingidos, registrando dano menor}
{2738}{}{Sistemas atingidos, sistemas atingidos, sistemas atingidos}
{2800}{}{Tenho que sair daqui!}
{2801}{}{Eu voltarei...}
{2802}{}{Você não vai me matar hoje!}
{2803}{}{Mais tarde, normalzinho!}
{2804}{}{Você ainda não ouviu sobre mim pela ultima vez!}
{2805}{}{Você pagara por isto - mais tarde!}
{2806}{}{Você e historia!}
{2807}{}{Carne fresca...}
{2808}{}{Ah, o jantar chegou.}
{2809}{}{Cerebros...}
{2810}{}{Eu vou escavar seu tumulo...}
{2811}{}{Espero que eu possa manter sua cabeca intacta...}
{2812}{}{Seu numero aumentou!}
{2813}{}{Não se incomode de gritar por misericordia...}
{2814}{}{Eu vou apreciar isto}
{2815}{}{Uuuu, isso deve doer!}
{2816}{}{}
{2817}{}{Eu vou comer seu figado!}
{2818}{}{Espero que você não morra muito rapido}
{2819}{}{Hora do jantar!}
{2820}{}{Morra!}
{2821}{}{Eu como miseraveis como você no cafe da manha, e almoco}
{2822}{}{Você não pode me ferir!}
{2823}{}{}
{2824}{}{Você não me acertou, normalzinho!}
{2825}{}{Você não me acertou, normalzinho!}
{2826}{}{Você não pode matar o que você não consegue acertar!}
{2827}{}{Muito lento!}
{2828}{}{Ah, minha linda face}
{2829}{}{Ai! Minha cabeca!}
{2830}{}{Oof!}
{2831}{}{Minha mao!}
{2832}{}{Ai!}
{2833}{}{Ai!!}
{2834}{}{Ai, meu braço}
{2835}{}{Você quebrou meu braço!}
{2836}{}{Você vai se arrepender disso!}
{2837}{}{(Grunt!)}
{2839}{}{Ah bosta!}
{2840}{}{Grrr!}
{2841}{}{Você vai se arrepender disso!}
{2842}{}{Você deveria parar enquanto você ainda esta na frente!}
{2843}{}{}
{2844}{}{}
{2845}{}{Ai, minha perna}
{2846}{}{Você vai pagar por isso!}
{2847}{}{Argh! Você quebra minha perna, eu quebro seu pescoco!}
{2848}{}{Minha perna!}
{2849}{}{}
{2850}{}{}
{2851}{}{Maldito sangue nos meus olhos!}
{2852}{}{Meu olho! Você pagara por isso!}
{2853}{}{Bastardo!}
{2854}{}{Uuuuuu, minha virilha!}
{2855}{}{Uuu! Eu vou aprender esse movimento...}
{2856}{}{Suino desumano!}
{2857}{}{AAAAAAAAAAAACCCKKKKKK!}
{2858}{}{Urp!}
{2859}{}{Oof! Eu vou matar você por isso!}
{2900}{}{Recuar! Recuar!}
{2901}{}{Você não vai me matar hoje!}
{2902}{}{Isto não acabou!}
{2903}{}{Meus amigos pegarao você por mim!}
{2904}{}{Você pagara por isto - mais tarde!}
{2905}{}{Eu banquetearei com seu coração outro dia!}
{2906}{}{Eu matarei você, humano!}
{2907}{}{Ninguem nos desafia e vive!}
{2908}{}{Suas armas lamentaveis não me farao mal!}
{2909}{}{Outra vitima vem brincar conosco!}
{2910}{}{Eu lancarei você fora da sua miseria}
{2911}{}{}
{2912}{}{}
{2913}{}{}
{2914}{}{Agora você morre!}
{2915}{}{Assim e como nos manejamos os tolos!}
{2916}{}{Eu apreciarei isto...}
{2917}{}{}
{2918}{}{Seus deuses abandonaram você!}
{2919}{}{Eu quero ouvir seus gritos!}
{2920}{}{É assim e como você morre!}
{2921}{}{Sofra, humano!}
{2922}{}{Lamentavel! Por que você ainda assim luta?}
{2923}{}{Isto e o melhor que a humanidade tem a oferecer?}
{2924}{}{Seu ataque e tão fraco quanto seu espirito!}
{2925}{}{Esse foi seu ultimo erro}
{2926}{}{Tolo! É você me derrotaria?}
{2927}{}{Patetico!}
{2928}{}{Ahhhgh! Minha cara!}
{2929}{}{Minha cara! Você sofrera por isso!}
{2930}{}{Ahhhgh! Eu rasgarei você em pedacos!}
{2931}{}{Ahhhgh! Meu braço}
{2932}{}{Ahhhgh! Eu não sou derrotado tão facilmente!}
{2933}{}{Ahhhgh! Eu quebrarei seu pescoco por isso!}
{2934}{}{Ahhhgh! Meu braço}
{2935}{}{Ahhhgh! Eu não sou derrotado tão facilmente!}
{2936}{}{Ahhhgh! Eu quebrarei seu pescoco por isso!}
{2937}{}{Necropolis sofrera por causa de você}
{2938}{}{Oof!}
{2939}{}{Arg!}
{2940}{}{(Sorrisos)}
{2941}{}{Isso não machucou!}
{2942}{}{Você pode fazer melhor que isso}
{2943}{}{Até mesmo estes ghouls são mais fortes do que você!}
{2944}{}{}
{2945}{}{}
{2946}{}{Haha! Que tentativa fraca... (geme)}
{2947}{}{Ahhhgh! Minha perna}
{2948}{}{Ahhhgh! Eu não sou derrotado tão facilmente!}
{2949}{}{Ahhhgh! Eu quebrarei seu pescoco por isso!}
{2950}{}{Ahhhgh! Minha perna}
{2951}{}{Ahhhgh! Eu não sou derrotado tão facilmente!}
{2952}{}{Ahhhgh! Eu quebrarei seu pescoco por isso!}
{2953}{}{Ahhhgh! Humano miseravel! Você me cegou!}
{2954}{}{Ahhhgh! A dor! O que você fez!}
{2955}{}{Ahhhgh! Você ganhou dias de agonia por isso!}
{2956}{}{Eu não compartilho essa fraqueza com você, humano!}
{2957}{}{Meus quadris são mais fortes do que o seu, humano!}
{2958}{}{Que tatica patetica, humano!}
{2959}{}{Esse não é meu local vulneravel, humano!}
{2960}{}{Sua morte fica mais dolorosa, humano!}
{2961}{}{Talvez eu devesse testar seus pontos fracos}
{3000}{}{Fujam! Fujam!}
{3001}{}{Recuar!}
{3002}{}{Reagrupar!}
{3003}{}{Recuar!}
{3004}{}{Retirar!}
{3005}{}{Aaaaghhh!}
{3006}{}{Matem este tolo!}
{3007}{}{Carne fresca...}
{3008}{}{Saquear!}
{3009}{}{Este e meu!}
{3010}{}{Capturem-no!}
{3011}{}{}
{3012}{}{Aprecie os ultimos segundos de sua vida}
{3013}{}{Sangue! Sangue! Sangue!}
{3014}{}{Seu coração e meu!}
{3015}{}{RAAAAAAARRRR!!}
{3016}{}{Suas armas serao meus trofeus!}
{3017}{}{Morte!}
{3018}{}{Você e meu para matar!}
{3019}{}{Seus ossos branquearao nas terras devastadas!}
{3020}{}{Sangue e trevas!}
{3021}{}{}
{3022}{}{Perfurem o bastardo entrangulador!}
{3023}{}{Esforco desperdicado!}
{3024}{}{Você falhou!}
{3025}{}{Meu sangue e mais forte do que o seu!}
{3026}{}{Eu vivo!!}
{3027}{}{Seu corpo e fraco e lamentavel!}
{3028}{}{Aaaagghh! Minha cara!}
{3029}{}{#@$^!! %%$^&!!?!}
{3030}{}{Você quebrou meu nariz!}
{3031}{}{Ai, meu braço}
{3032}{}{Você quebrou meu braço!}
{3033}{}{Você morrera por isso!}
{3034}{}{Ai, meu braço}
{3035}{}{Você quebrou meu braço!}
{3036}{}{Você morrera por isso!}
{3037}{}{}
{3038}{}{Você chama isso de dor!?}
{3039}{}{Ouch!}
{3040}{}{Oof!}
{3041}{}{Maldicao! Isso doi!}
{3042}{}{Venha aqui, e deixe-me fazer isso por você!}
{3043}{}{Você vai pagar! Eu juro!}
{3044}{}{Gasp!}
{3045}{}{}
{3046}{}{Eegah! Essa mordeu a raiz!}
{3047}{}{Ai, minha perna}
{3048}{}{Você morrera por isso!}
{3049}{}{Argh! Você quebra minha perna, eu quebro seu pescoco!}
{3050}{}{Ai, minha perna}
{3051}{}{Você morrera por isso!}
{3052}{}{Argh!!}
{3053}{}{Argh! Eu rasgarei você em pedacos!}
{3054}{}{Meu olho!}
{3055}{}{Meu olho! Você morrera lentamente por isso!}
{3056}{}{Uuuuuu, minha virilha!}
{3057}{}{Uuu! Você... sofrera...}
{3058}{}{Uuu! Eu... matarei...}
{3059}{}{Uuu! Eu mutilarei você...}
{3060}{}{Urp!}
{3061}{}{Eu matarei você por isso!}
{3100}{}{Khans! Me cubram!}
{3101}{}{Recuar!}
{3102}{}{Reagrupar!}
{3103}{}{Recuar!}
{3104}{}{Retirar!}
{3105}{}{Aaaaghhh!}
{3106}{}{Deixe o desafio começar!}
{3107}{}{Carne fresca...}
{3108}{}{Saquear!}
{3109}{}{Este e meu!}
{3110}{}{Khans, ataquem!}
{3111}{}{}
{3112}{}{Khans, matem!}
{3113}{}{Sangue! Sangue! Sangue!}
{3114}{}{Eu sou supremo!}
{3115}{}{RAAAAAAARRRR!!}
{3116}{}{Khans são invenciveis!}
{3117}{}{Sem retirada! Sem rendicao!}
{3118}{}{Você e meu para matar!}
{3119}{}{Seus ossos branquearao nos desertos!}
{3120}{}{Sangue e trevas!}
{3121}{}{Khans são os fortes!}
{3122}{}{}
{3123}{}{Eu não posso ser tocado!}
{3124}{}{Eu sou indestrutivel!}
{3125}{}{Meu sangue e mais forte do que o seu!}
{3126}{}{RAAAAAAAAARRRR!!}
{3127}{}{Você não é digno de combate comigo!}
{3128}{}{Um golpe valoroso!}
{3129}{}{Esse foi seu ultimo ataque!}
{3130}{}{Meu nariz!}
{3131}{}{Eu posso bater em você com um braço!}
{3132}{}{Você quebrou meu braço! Agora a luta e justa!}
{3133}{}{Esse foi seu golpe final!}
{3134}{}{Eu posso bater em você com um braço!}
{3135}{}{Você quebrou meu braço! Agora a luta e justa!}
{3136}{}{Esse foi seu golpe final!}
{3137}{}{Sua morte será lendaria por isso!}
{3138}{}{Eu banquetearei com seus olhos por isso!}
{3139}{}{Bosta!}
{3140}{}{Oof!}
{3141}{}{Ouch!}
{3142}{}{}
{3143}{}{Gasp!}
{3144}{}{Minhas costelas doem. Em breve eu removerei as suas! É justo}
{3145}{}{}
{3146}{}{Gemido}
{3147}{}{Eu não preciso ficar de pe pra matar você!}
{3148}{}{Você morrera por isso!}
{3149}{}{}
{3150}{}{Eu não preciso ficar de pe pra matar você!}
{3151}{}{Você morrera por isso!}
{3152}{}{}
{3153}{}{Argh! Eu rasgarei você em pedacos!}
{3154}{}{Meu olho! Eu trocarei minha visao pela sua morte!}
{3155}{}{Meu olho! Você morrera lentamente por isso!}
{3156}{}{Uuuuuu, minha virilha!}
{3157}{}{Uuu! Você... sofrera...}
{3158}{}{Uuu! Eu... matarei...}
{3159}{}{Uuu! Eu mutilarei você...}
{3160}{}{Urp!}
{3161}{}{Você não roubara minha masculinidade!}
{3200}{}{Não pense que isto esta acabado!}
{3201}{}{Eu preciso de ajuda aqui!}
{3202}{}{Alguém me ajude!}
{3203}{}{Nós ainda traremos a justica até você!}
{3204}{}{Algum dia, você tera o que esta vindo pra você!}
{3205}{}{ Eu não vou morrer por isto!}
{3206}{}{}
{3207}{}{}
{3208}{}{}
{3209}{}{Nós não precisamos do seu tipo por aqui!}
{3210}{}{Ninguem vai tomar este lugar...}
{3211}{}{Shady Sands não precisa dos tipos de você!}
{3212}{}{}
{3213}{}{Eu vou por a grande ferida em você?}
{3214}{}{Isto e o que nos fazemos com os vermes!}
{3215}{}{}
{3216}{}{Assim e como nos manejamos um problema em Shady Sands.}
{3217}{}{Você aprendera isto!}
{3218}{}{Eu usarei seu corpo como fertilizante.}
{3219}{}{Certo. Você pediu por isto.}
{3220}{}{Seu/Sua animal!}
{3221}{}{Você se arrependera de vir aqui!}
{3222}{}{Você não é tão bom quanto você pensa }
{3223}{}{}
{3224}{}{Você e mais burro do que um rato-toupeira}
{3225}{}{Shady Sands não derruba e morre por ninguém}
{3226}{}{}
{3227}{}{Esse foi seu ultimo erro}
{3228}{}{Maldicao!}
{3229}{}{Aggghhh!}
{3230}{}{Minha cara! Minha cara!}
{3231}{}{Aggghhh! Meu braço}
{3232}{}{Meu braço!}
{3233}{}{O maldito braço esta inaproveitavel agora...}
{3234}{}{Aggghhh! Meu braço}
{3235}{}{Meu braço!}
{3236}{}{O maldito braço esta inaproveitavel agora...}
{3237}{}{Ouch!}
{3238}{}{Doh!}
{3239}{}{}
{3240}{}{Que você possa morrer de sede, sozinho e com frio...}
{3241}{}{Gasp!}
{3242}{}{}
{3243}{}{Por favor não...}
{3244}{}{}
{3245}{}{Karma ruim me atingir desse modo}
{3246}{}{Gack!}
{3247}{}{Aggghhh! Minha perna}
{3248}{}{Minha perna!}
{3249}{}{Maldicao, minha perna esta inaproveitavel...}
{3250}{}{Aggghhh! Minha perna}
{3251}{}{Minha perna!}
{3252}{}{Maldicao, minha perna esta inaproveitavel...}
{3253}{}{Aggghhh! Eu estou cego!}
{3254}{}{Maldicao! Tudo esta escuro!}
{3255}{}{Meu olho! Você pagara por isso!}
{3256}{}{Uuuuuu, minha virilha!}
{3257}{}{Ooooooooooffffff!}
{3258}{}{Eu...não...consigo...respirar...}
{3259}{}{!}
{3260}{}{A dor, a dor...}
{3261}{}{Maldicao, isso doi!}
{3300}{}{Eu fui}
{3301}{}{}
{3302}{}{Aaaaahhhh!}
{3303}{}{Mais tarde. Talvez.}
{3304}{}{}
{3305}{}{Vejo você por ai}
{3306}{}{}
{3307}{}{O que é desta vez?}
{3308}{}{Eu lidarei com isto...}
{3309}{}{Não outra interrupcao!}
{3310}{}{Se não são os Radscorpions, são eles os malditos saqueadores...}
{3311}{}{}
{3312}{}{}
{3313}{}{Morra!}
{3314}{}{Perdedor}
{3315}{}{Miseravel}
{3316}{}{}
{3317}{}{Seu numero aumentou!}
{3318}{}{Você realmente espiolhou aqui}
{3319}{}{Aqui esta um presente de Shady Sands}
{3320}{}{Você não vai chatear este lugar de novo}
{3321}{}{Fique pronto para empurrar as margaridas pra cima}
{3322}{}{Não estou impressionado}
{3323}{}{Amador}
{3324}{}{Patetico}
{3325}{}{Você e lento}
{3326}{}{Você e inutil}
{3327}{}{Não desista do seu trabalho de dia}
{3328}{}{Isso doi}
{3329}{}{Meus olhos!}
{3330}{}{Ai! Destruiu meu nariz...}
{3331}{}{Ai!}
{3332}{}{Ai! Meu braço!}
{3333}{}{Ai! Você quebrou ele!}
{3334}{}{Ai!}
{3335}{}{Ai! Meu braço!}
{3336}{}{Ai! Você quebrou ele!}
{3337}{}{Maldicao it! Isso doi!}
{3338}{}{Ouch!}
{3339}{}{Ai!}
{3340}{}{}
{3341}{}{(Segurando as costelas) Ouch!}
{3342}{}{Vamos! Sem luta na cidade!}
{3343}{}{Gasp!}
{3344}{}{Ai! Eu estou desapontado com vocês, forasteiros...}
{3345}{}{Oof!}
{3346}{}{Isso doi!}
{3347}{}{Ai!}
{3348}{}{Ai! Minha perna!}
{3349}{}{Ai! Minha perna!}
{3350}{}{Ai!}
{3351}{}{Ai! Minha perna!}
{3352}{}{Ai! Minha perna!}
{3353}{}{Eu estou cego!}
{3354}{}{Eu não consigo ver!}
{3355}{}{Tao escuro}
{3356}{}{Uuuuuu, minha virilha!}
{3357}{}{Aieee!}
{3358}{}{Maldicao, isso doi}
{3359}{}{Ooof!}
{3360}{}{Urp!}
{3361}{}{Eu...não...consigo...respirar...}
{3400}{}{}
{3401}{}{}
{3402}{}{Eu preciso de um doutor}
{3403}{}{Mais tarde. Talvez.}
{3404}{}{Melhor eu ficar fora do caminho}
{3405}{}{Vejo você por ai}
{3406}{}{Amigo, você cometeu um grande erro}
{3407}{}{O que é desta vez?}
{3408}{}{Eu lidarei com isto...}
{3409}{}{Não outra interrupcao!}
{3410}{}{Se não são radscorpions, são criadores de problemas...}
{3411}{}{}
{3412}{}{}
{3413}{}{}
{3414}{}{Scab}
{3415}{}{Miseravel}
{3416}{}{Isto e o que nos fazemos com criadores de problemas}
{3417}{}{Espero que isto machuque}
{3418}{}{Você realmente ferrou aqui}
{3419}{}{Aqui esta um presente de Shady Sands}
{3420}{}{Você não vai chatear este lugar de novo}
{3421}{}{Eu não vou deixar você sair fora disto}
{3422}{}{Não estou impressionado}
{3423}{}{Não deveria lutar a menos que você saiba o que você esta fazendo}
{3424}{}{Patetico}
{3425}{}{Você e lento}
{3426}{}{}
{3427}{}{}
{3428}{}{}
{3429}{}{Meu cranio!}
{3430}{}{Ai! Maldito nariz quebrado...}
{3431}{}{Ai!}
{3432}{}{Ai! Meu braço!}
{3433}{}{Ai! Você quebrou ele!}
{3434}{}{Ai!}
{3435}{}{Ai! Meu braço!}
{3436}{}{Ai! Você quebrou ele!}
{3437}{}{Ai!}
{3438}{}{Por Dharma! Isso doi!}
{3439}{}{Aqueles que comecam a criar problema o acharao...}
{3440}{}{Oof!}
{3441}{}{Oof! Eu punirei você por isso...}
{3442}{}{Ai! Isso doi!}
{3443}{}{Ouch! Isso foi muito desagradavel}
{3444}{}{Ai! Por que você faz isto?}
{3445}{}{Arg! Eu devo controlar minhas emoções...}
{3446}{}{Ack! Você e semelhante a bosta de radscorpion!}
{3447}{}{Ai!}
{3448}{}{Ai! Minha perna!}
{3449}{}{Ai! Minha perna!}
{3450}{}{Ai!}
{3451}{}{Ai! Minha perna!}
{3452}{}{Ai! Minha perna!}
{3453}{}{Meus olhos!}
{3454}{}{Agghh! Então e assim que você quer jogar...}
{3455}{}{Agghh! Pequeno sujo filho da...}
{3456}{}{Uuuuuu, minha virilha!}
{3457}{}{Aieee!}
{3458}{}{[whimper]}
{3459}{}{Ooof!}
{3460}{}{Uuuuuu! Eu não senti isso! Ai!}
{3461}{}{Uuuuuu! Isso doi. Devo estar ficando velho.}
{3500}{}{Talvez eu darei um pequeno intervalo.}
{3501}{}{Eu voltarei!}
{3502}{}{Mais tarde, miseravel!}
{3503}{}{}
{3504}{}{}
{3505}{}{Vamos fazer isso de novo em breve!}
{3506}{}{Me enfrente ou me ame...}
{3507}{}{Carne fresca!}
{3508}{}{!}
{3509}{}{}
{3510}{}{Os Rippers vao rachar você em pedacos!}
{3511}{}{Vamos dancar!}
{3512}{}{Eu vou esculpir você como uma iguana-no-espeto!}
{3513}{}{}
{3514}{}{Por favor não morra ainda. Eu quero que você sofra}
{3515}{}{}
{3516}{}{Uma porcao de morte, saindo agora mesmo!}
{3517}{}{Você ficara tão bonito quando você estiver morto}
{3518}{}{Morra! Morra! Morra! Morra! Morra!}
{3519}{}{Sua dor é minha alegria!}
{3520}{}{Vamos abrir você um pouco...}
{3521}{}{É eu pensei que não haveria carnificina hoje...}
{3522}{}{}
{3523}{}{Eu estou TÃO assustado!}
{3524}{}{Vamos garoto viado, me de uma luta!}
{3525}{}{Isso e o melhor que você pode fazer?}
{3526}{}{Você não é nada comparado a mim!}
{3527}{}{Isto vai ser mais fácil do que eu pensei}
{3528}{}{Essa será uma cicatriz bacana!}
{3529}{}{Você tentando me impressionar?}
{3530}{}{Faca isso de novo, docura.}
{3531}{}{Eu amo o som de ossos esmagando}
{3532}{}{Uuu, você esta ficando serio!}
{3533}{}{Eu gosto brutal, querido}
{3534}{}{Eu amo o som de ossos esmagando}
{3535}{}{Uuu, você esta ficando serio!}
{3536}{}{Eu gosto brutal, querido}
{3537}{}{Eu amo quando você e bruto...}
{3538}{}{Me de outro tapinha de amor...}
{3539}{}{Ouch! Ah, o amor doi, baby!}
{3540}{}{Oof!}
{3541}{}{Doh!}
{3542}{}{Argh! Isto significa que esta acabado?}
{3543}{}{Gasp!}
{3544}{}{Me acerte de novo, por favor...}
{3545}{}{Eu tenho que arremessar da proxima vez}
{3546}{}{Ah, a dor, a dor...}
{3547}{}{Eu amo o som de ossos esmagando}
{3548}{}{Uuu, você esta ficando serio!}
{3549}{}{}
{3550}{}{Eu amo o som de ossos esmagando}
{3551}{}{}
{3552}{}{Eu gosto!}
{3553}{}{Ei, Eu estou cego. Que investida!}
{3554}{}{Eu não consigo ver. Eu creio que eu apenas terei que farejar o seu medo!}
{3555}{}{Meus olhos! Cara, eu gosto do modo como você luta}
{3556}{}{Uuuuuu, minha virilha!}
{3557}{}{Esse foi um movimento corajoso}
{3558}{}{Uuuu! Isso é uma proposta, baby?}
{3559}{}{}
{3560}{}{Então esse e o modo que você quer jogar}
{3561}{}{Uuuuu, movimento bacana, amigo}
{3600}{}{}
{3601}{}{}
{3602}{}{}
{3603}{}{Você não venceu!}
{3604}{}{Recuar!}
{3605}{}{Eu não preciso disto...}
{3606}{}{Atacar!}
{3607}{}{Eu vou apreciar enterrar você em uma tumulo raso!}
{3608}{}{}
{3609}{}{Alguém esta morrendo}
{3610}{}{Matem o intruso!}
{3611}{}{}
{3612}{}{}
{3613}{}{Morra!}
{3614}{}{Skank!}
{3615}{}{Isto e por que eles nos chamam de Blades}
{3616}{}{}
{3617}{}{Espero que isto machuque}
{3618}{}{Vou apreciar isto}
{3619}{}{Sua cabeca vai pra minha colecao!}
{3620}{}{Eu enterrarei você}
{3621}{}{Seu dia esta pra ficar ruim de verdade}
{3622}{}{Eu sou mais virtuoso do que Deus!}
{3623}{}{Não estou impressionado}
{3624}{}{Mostre-me algumas bolas!}
{3625}{}{}
{3626}{}{Sua Mamae dormiu com os Rippers!}
{3627}{}{Você esta tentando acertar as moscas, bobo?}
{3628}{}{}
{3629}{}{ack!!}
{3630}{}{Ai! Destruiu meu nariz...}
{3631}{}{Ai!}
{3632}{}{Ai! Meu braço!}
{3633}{}{Ai! Você quebrou ele!}
{3634}{}{Ai!}
{3635}{}{Ai! Meu braço!}
{3636}{}{Ai! Você quebrou ele!}
{3637}{}{Ai!}
{3638}{}{Ah, merda!}
{3639}{}{Ouch! Esse foi um erro ruim...}
{3640}{}{Ai! Eu mostrarei a você...}
{3641}{}{Gasp!}
{3642}{}{Não consigo respirar...}
{3643}{}{}
{3644}{}{Oof!}
{3645}{}{You skag! Isso doi!}
{3646}{}{}
{3647}{}{Ai!}
{3648}{}{Ai! Minha perna!}
{3649}{}{Ai! Minha perna!}
{3650}{}{Ai!}
{3651}{}{Ai! Minha perna!}
{3652}{}{Ai! Minha perna!}
{3653}{}{Eu estou cego!}
{3654}{}{Eu não consigo ver!}
{3655}{}{Meus olhos! Seu/Sua filho de um Ripper...}
{3656}{}{Uuuuuu, minha virilha!}
{3657}{}{Aieee!}
{3658}{}{Maldicao, isso doi}
{3659}{}{Ooof!}
{3660}{}{Eu matarei você por essa, miseravel}
{3661}{}{Eu...não...consigo...respirar...}
{3700}{}{Eu realmente gostaria de assistir o levantar do sol amanha}
{3701}{}{Talvez isto não era uma boa ideia}
{3702}{}{}
{3703}{}{}
{3704}{}{Eu não vou morrer por isto!}
{3705}{}{Eu não posso acreditar no que eles estão carregando...}
{3706}{}{Tentando to muscle em nosso negocio, huh?}
{3707}{}{Alguém acabou de cometer um grande erro!}
{3708}{}{}
{3709}{}{Quem você pensa que você e?}
{3710}{}{Hora de demonstrar um pouco da mercadoria}
{3711}{}{Espere até eu pegar você...}
{3712}{}{}
{3713}{}{}
{3714}{}{}
{3715}{}{Você gosta disto?}
{3716}{}{Eu vou derrubar você como um vicio ruim}
{3717}{}{Que tal isto como poder de fogo?}
{3718}{}{Vamos ver quao forte você é.}
{3719}{}{Lutar é minha vida}
{3720}{}{}
{3721}{}{Talvez você aprendera um pouco de respeito}
{3722}{}{Você não esperava me tocar, esperava?}
{3723}{}{Eu estive fazendo isto por anos, miseravel}
{3724}{}{Você não esperava isso, esperava?}
{3725}{}{Esse foi seu ultimo erro}
{3726}{}{Amador}
{3727}{}{Isto não é como atirar em ratos-toupeira, amigo.}
{3728}{}{Ai! Seu/Sua filho da...}
{3729}{}{Eu vou matar você por isso}
{3730}{}{Eu arrancarei sua cabeca fora!}
{3731}{}{Ai, meu braço}
{3732}{}{Maldicao. Meu braço esta destruido!}
{3733}{}{Meu braço!}
{3734}{}{Ai, meu braço}
{3735}{}{Maldicao. Meu braço esta destruido!}
{3736}{}{Meu braço!}
{3737}{}{Eu já vi empregados junior fazerem melhor do que isso...}
{3738}{}{Ouch!}
{3739}{}{Eu devo me lembrar de dar de volta para você essa dor algum dia}
{3740}{}{Oof!}
{3741}{}{}
{3742}{}{Maldicao!}
{3743}{}{Seu babaca!}
{3744}{}{}
{3745}{}{Gasp!}
{3746}{}{Ouch!}
{3747}{}{Ai, minha perna}
{3748}{}{}
{3749}{}{Meu joelho!}
{3750}{}{Ai, minha perna}
{3751}{}{Você vai pagar por isso, em spades!}
{3752}{}{Meu joelho!}
{3753}{}{Eu não consigo ver!}
{3754}{}{Meu olho! Você pagara por isso!}
{3755}{}{Aaieeee! Eu estou cego!}
{3756}{}{Uuuuuu, minha virilha!}
{3757}{}{Então esse e o modo como você quer jogar}
{3758}{}{}
{3759}{}{Urp!}
{3760}{}{}
{3761}{}{A dor, a dor...}
{3800}{}{Eu preciso de reforcos!}
{3801}{}{Alguém me ajude!}
{3802}{}{Reagrupar!}
{3803}{}{Recuar! Recuar!}
{3804}{}{Recuar! Recuar!}
{3805}{}{Nós precisamos achar uma posição melhor!}
{3806}{}{Nós temos um alvo!}
{3807}{}{Nós estamos sob ataque!}
{3808}{}{Soem um alerta! Eu segurarei eles!}
{3809}{}{Nós temos um problema. Eu lidarei com ele.}
{3810}{}{Alvo localizado, movendo para interceptar!}
{3811}{}{Entrando em combate com o alvo!}
{3812}{}{Gangland miseravel!}
{3813}{}{Eu vou por você fora do seu sofrimento}
{3814}{}{Você não é melhor do que um animal!}
{3815}{}{Melhor você ficar abaixado desta vez}
{3816}{}{Você nunca aborrecera ninguém de novo}
{3817}{}{Nenhuma misericordia para miseraveis!}
{3818}{}{Melhor você rezar para os deuses!}
{3819}{}{}
{3820}{}{Eu estou soltando o martelo em você}
{3821}{}{Vejo você no Inferno}
{3822}{}{Seu ataque fede pior do que o seu bafo, verme!}
{3823}{}{Vamos perdedor. Apenas finja de morto pra mim}
{3824}{}{}
{3825}{}{Você esta jogando o jogo errado, scumbag!}
{3826}{}{Qual e o problema, miseravel?}
{3827}{}{Eu não mato assim fácil.}
{3828}{}{Aggghh! Tiro sortudo!}
{3829}{}{Minha cara!}
{3830}{}{Você quebrou meu nariz!}
{3831}{}{Aggghh! Tiro sortudo!}
{3832}{}{Um braço destruido não vai me parar!}
{3833}{}{}
{3834}{}{Aggghh! Tiro sortudo!}
{3835}{}{Um braço destruido não vai me parar!}
{3836}{}{Eu não gosto do som disso}
{3837}{}{Aggghh! Tiro sortudo!}
{3838}{}{}
{3839}{}{Você não vai me incapacitar, amigo.}
{3840}{}{Aggghh! Tiro sortudo!}
{3841}{}{}
{3842}{}{Você não vai me incapacitar, amigo.}
{3843}{}{Eu estou cego!}
{3844}{}{Meus olhos estão queimando!}
{3845}{}{Eu não consigo ver!}
{3846}{}{Uuuuuu, minha virilha!}
{3847}{}{Sim, miseraveis sempre miram na virilha}
{3848}{}{Maldicao, isso doi!}
{3849}{}{Eu...não...consigo...respirar...}
{3850}{}{Uuuuuu. Seu sadico filho da...}
{3851}{}{Seu/Sua miseravel...}
{3900}{}{Eu preciso de reforcos!}
{3901}{}{Alguém me ajude!}
{3902}{}{}
{3903}{}{Recuar! Recuar!}
{3904}{}{Recuar! Recuar!}
{3905}{}{Socorro!}
{3906}{}{Por Adytown!}
{3907}{}{Nós estamos sob ataque!}
{3908}{}{Eu preciso de reforco!}
{3909}{}{Atacar!}
{3910}{}{Nós não precisamos do seu tipo por aqui!}
{3911}{}{Para as armas! Para as armas!}
{3912}{}{Isto e para Adytown!}
{3913}{}{Isto e o que nos fazemos com animais!}
{3914}{}{Bem vindo ao Inferno, miseravel}
{3915}{}{Melhor você ficar abaixado desta vez}
{3916}{}{Você nunca aborrecera ninguém de novo}
{3917}{}{Nenhuma misericordia para miseraveis!}
{3918}{}{Melhor você rezar para os deuses!}
{3919}{}{}
{3920}{}{Você acabou de comprar uma casa a sete palmos abaixo}
{3921}{}{Espero que você apreciou sua vida, ela esta pra passar diante dos seus olhos}
{3922}{}{Você é um desperdicio de munição}
{3923}{}{}
{3924}{}{}
{3925}{}{Agora é a minha vez}
{3926}{}{Surpreso, miseravel?}
{3927}{}{Nós não somos faceis de matar}
{3928}{}{Aggghh! Bem na cara.}
{3929}{}{Minha cara!}
{3930}{}{Você quebrou meu nariz!}
{3931}{}{Aggghh! Meu braço}
{3932}{}{Ai! Isso doi!}
{3933}{}{Maldicao. Eu posso estar ferido gravemente}
{3934}{}{Aggghh! Meu braço}
{3935}{}{Ai! Isso doi!}
{3936}{}{Maldicao. Eu posso estar ferido gravemente}
{3937}{}{Ouch!}
{3938}{}{Oof! Isso doi!}
{3939}{}{Oof! É... difícil... respirar...}
{3940}{}{Eu fui atingido! Medico!}
{3941}{}{Eu ficarei ok, e só uma ferida menor}
{3942}{}{Argh!}
{3943}{}{Ouch! Maldicao!}
{3944}{}{Ai! Eu pegarei você}
{3945}{}{}
{3946}{}{}
{3947}{}{Aggghh! Tiro sortudo!}
{3948}{}{Maldicao, bem no joelho...}
{3949}{}{Eu não estou caindo, miseravel. Ai.}
{3950}{}{Aggghh! Tiro sortudo!}
{3951}{}{Maldicao, bem no joelho...}
{3952}{}{Eu não estou caindo, miseravel. Ai.}
{3953}{}{Eu fui cegado! Alguém me ajude!}
{3954}{}{Maldicao, bem nos olhos!}
{3955}{}{Eu não consigo ver!}
{3956}{}{Uuuuuu, minha virilha!}
{3957}{}{Sim, miseraveis sempre miram na virilha}
{3958}{}{Maldicao, isso doi!}
{3959}{}{Eu...não...consigo...respirar...}
{3960}{}{Uuuuuu. Seu sadico filho da...}
{3961}{}{Seu/Sua miseravel...}
{4000}{}{Alguém pode me cobrir!}
{4001}{}{Alguém me ajude!}
{4002}{}{Medico!}
{4003}{}{Recuar! Recuar!}
{4004}{}{Recuar! Recuar!}
{4005}{}{Socorro!}
{4006}{}{Isto parece problema.}
{4007}{}{Nós estamos sob ataque!}
{4008}{}{Nós temos problemas!}
{4009}{}{Mais uma vez na discordia!}
{4010}{}{Eu morrerei antes que eu deixe você me empurrar por ai!}
{4011}{}{Você esta mexendo com as pessoas erradas}
{4012}{}{Você deveria ter corrido quando você teve a chance}
{4013}{}{Hora de acabar com isto}
{4014}{}{}
{4015}{}{}
{4016}{}{Outra cadaver para minha consciencia...}
{4017}{}{Eu vou por você no seu lugar para o bem desta vez}
{4018}{}{Melhor você rezar para os deuses!}
{4019}{}{}
{4020}{}{}
{4021}{}{Você não saira fora disto}
{4022}{}{Você não vai vencer esta luta}
{4023}{}{}
{4024}{}{Você não pode vencer...}
{4025}{}{Agora é a minha vez}
{4026}{}{Você não sacou? Você não vencera!}
{4027}{}{Nós não somos faceis de matar}
{4028}{}{Aggghh! Bem na cara.}
{4029}{}{Minha cara!}
{4030}{}{Você quebrou meu nariz!}
{4031}{}{Aggghh! Meu braço}
{4032}{}{Ai! Isso doi!}
{4033}{}{Maldicao. Eu posso estar ferido gravemente}
{4034}{}{Aggghh! Meu braço}
{4035}{}{Ai! Isso doi!}
{4036}{}{Maldicao. Eu posso estar ferido gravemente}
{4037}{}{Ai! Esse foi doloroso}
{4038}{}{}
{4039}{}{Oof! Você tem que fazer melhor do que isso}
{4040}{}{Ouch! Você acha que você pode me tirar da minha causa assim facilmente!?}
{4041}{}{Ouch!}
{4042}{}{Argh!}
{4043}{}{Oof!}
{4044}{}{Gasp!}
{4045}{}{}
{4047}{}{Aggghh! Minha perna!}
{4048}{}{Maldicao, bem no joelho...}
{4049}{}{Aggghh! Mal posso ficar de pe...}
{4050}{}{Aggghh! Minha perna!}
{4051}{}{Maldicao, bem no joelho...}
{4052}{}{Aggghh! Mal posso ficar de pe...}
{4053}{}{Eu fui cegado! Alguém me ajude!}
{4054}{}{}
{4055}{}{Eu não consigo ver!}
{4056}{}{Uuuuuu, minha virilha!}
{4057}{}{}
{4058}{}{Maldicao!}
{4059}{}{Eu...não...consigo...respirar...}
{4060}{}{}
{4061}{}{Seu/Sua miseravel!}
{4100}{}{}
{4101}{}{Alguém ajude!}
{4102}{}{}
{4103}{}{Recuar! Recuar!}
{4104}{}{Recuar! Recuar!}
{4105}{}{Socorro!}
{4106}{}{}
{4107}{}{Eu acho que nos temos um problema}
{4108}{}{Vamos ver se eu posso remover isto rapidamente}
{4109}{}{Melhor tomar conta deles aqui}
{4110}{}{Esse parece um poder de fogo serio}
{4111}{}{Você esta mexendo com as pessoas erradas}
{4112}{}{Você deveria ter corrido quando você teve a chance}
{4113}{}{Hora de acabar com isto}
{4114}{}{}
{4115}{}{Você não será ameca apos isto}
{4116}{}{}
{4117}{}{}
{4118}{}{}
{4119}{}{Um verme a menos na Boneyard}
{4120}{}{}
{4121}{}{Você não vai sair fora disto}
{4122}{}{Você não vai vencer}
{4123}{}{}
{4124}{}{}
{4125}{}{Agora é a minha vez}
{4126}{}{Você não pode vencer!}
{4127}{}{}
{4128}{}{Aggghh!}
{4129}{}{}
{4130}{}{Minha cara!}
{4131}{}{Aggghh! Meu braço}
{4132}{}{Bem, esse membro e muito inutil...}
{4133}{}{Maldicao. Eu posso estar ferido gravemente}
{4134}{}{Aggghh! Meu braço}
{4135}{}{Bem, esse membro e muito inutil...}
{4136}{}{Maldicao. Eu posso estar ferido gravemente}
{4137}{}{Aaugh! Vou avisar o resto sobre você(s)}
{4138}{}{Oof! Tenho que viver, tenho que viver...}
{4139}{}{}
{4140}{}{Oof!}
{4141}{}{Bah!}
{4142}{}{Ack!}
{4143}{}{Ai!}
{4144}{}{}
{4145}{}{}
{4146}{}{}
{4147}{}{Aggghh! Minha perna!}
{4148}{}{Maldicao, bem no joelho...}
{4149}{}{Aggghh! Mal posso ficar de pe...}
{4150}{}{Aggghh! Minha perna!}
{4151}{}{Maldicao, bem no joelho...}
{4152}{}{Aggghh! Mal posso ficar de pe...}
{4153}{}{Eu estou cego! Talvez se eu enxugar o sangue...}
{4154}{}{Maldicao, bem nos olhos!}
{4155}{}{Eu não consigo ver!}
{4156}{}{}
{4157}{}{Eegah!}
{4158}{}{}
{4159}{}{Eu...não...consigo...respirar...}
{4160}{}{}
{4161}{}{}
{4200}{}{}
{4201}{}{Sem cobertura o bastante e eu estou ferido gravemente!}
{4202}{}{}
{4203}{}{}
{4204}{}{Recuar! Recuar!}
{4205}{}{Alguém me cubra!}
{4206}{}{}
{4207}{}{}
{4208}{}{Defendam a colonia!}
{4209}{}{}
{4210}{}{Intrusos!}
{4211}{}{Você acabou de assinar sua sentenca de morte}
{4212}{}{}
{4213}{}{}
{4214}{}{}
{4215}{}{Você não será uma ameaca apos isto...}
{4216}{}{Isto vai doer}
{4217}{}{Eu vou por você no seu lugar...}
{4218}{}{}
{4219}{}{Um verme a menos na Boneyard}
{4220}{}{}
{4221}{}{Você não vai sair fora disto}
{4222}{}{Você não vai vencer esta luta}
{4223}{}{}
{4224}{}{}
{4225}{}{Agora é a minha vez}
{4226}{}{Você acabou de cometer um grande erro}
{4227}{}{}
{4228}{}{Maldicao!}
{4229}{}{}
{4230}{}{Eu acho que meu nariz esta destruido}
{4231}{}{Meu braço!}
{4232}{}{}
{4233}{}{Eu posso estar ferido gravemente...}
{4234}{}{Meu braço!}
{4235}{}{Bem, esse membro e muito inutil...}
{4236}{}{Maldicao! Eu posso estar ferido gravemente...}
{4237}{}{}
{4238}{}{}
{4239}{}{}
{4240}{}{Oof!}
{4241}{}{Bah!}
{4242}{}{Ack!}
{4243}{}{Ai!}
{4244}{}{Oof! Isso pode ter me machucado}
{4245}{}{Maldicao, isso doi!}
{4246}{}{}
{4247}{}{Minha perna!}
{4248}{}{Maldicao, bem no joelho...}
{4249}{}{Aggghh! Mal posso ficar de pe...}
{4250}{}{Minha perna!}
{4251}{}{Maldicao, bem no joelho...}
{4252}{}{Aggghh! Mal posso ficar de pe...}
{4253}{}{Eu estou cego!}
{4254}{}{Maldicao, bem nos olhos!}
{4255}{}{Eu não consigo ver!}
{4256}{}{Urgh! Minhas joias!}
{4257}{}{}
{4258}{}{Isso doi como o Inferno!}
{4259}{}{Eu...não...consigo...respirar...}
{4260}{}{}
{4261}{}{}
{4300}{}{Tenho que achar uma posição melhor...}
{4301}{}{Sem cobertura o bastante e eu estou ferido gravemente...}
{4302}{}{Isto não acabou!}
{4303}{}{Melhor reagrupar....}
{4304}{}{Recuar!}
{4305}{}{Força bruta não vencera esta luta}
{4306}{}{Eu manejarei isto}
{4307}{}{Isto não vai ser bonito!}
{4308}{}{Defendam a colonia!}
{4309}{}{Nós não podemos deixar esta escoria parar nossa missao!}
{4310}{}{}
{4311}{}{}
{4312}{}{Eu não tomo alegria nisto}
{4313}{}{Hora de acabar com isto}
{4314}{}{}
{4315}{}{Você não deveria ter vindo aqui}
{4316}{}{Isto vai doer}
{4317}{}{Eu não deixarei você destruir o que nos construimos}
{4318}{}{}
{4319}{}{Eu lamento que eu tenha que fazer isto}
{4320}{}{Maldito seja por me fazer a fazer isto!}
{4321}{}{Eu tenho pena de você}
{4322}{}{Eu não posso deixar você vencer}
{4323}{}{Você e tão desajeitado quanto você e violento}
{4324}{}{Nós sabemos como tomar conta de nos mesmos}
{4325}{}{Agora é a minha vez}
{4326}{}{Esse e seu ultimo erro}
{4327}{}{}
{4328}{}{Maldicao. Isso arde}
{4329}{}{O osso da mandibula esta rachado. Não posso deixa-lo me parar.}
{4330}{}{Eu acho que meu nariz esta destruido}
{4331}{}{Meu braço!}
{4332}{}{O membro esta inaproveitavel. Tenho que continuar indo}
{4333}{}{Maldicao! Eu posso estar ferido gravemente}
{4334}{}{Meu braço!}
{4335}{}{O membro e inaproveitavel. Tenho que continuar indo}
{4336}{}{Maldicao! Eu posso estar ferido gravemente}
{4337}{}{}
{4338}{}{Oof!}
{4339}{}{}
{4340}{}{}
{4341}{}{Gasp!}
{4342}{}{Ack!}
{4343}{}{Ai!}
{4344}{}{Oof! Você pode me derrotar, mas a causa vivera}
{4345}{}{Argh!}
{4346}{}{}
{4347}{}{Minha perna!}
{4348}{}{Maldicao, bem no joelho...}
{4349}{}{}
{4350}{}{Minha perna!}
{4351}{}{Maldicao, bem no joelho...}
{4352}{}{A perna se foi, mas eu ainda posso lutar!}
{4353}{}{Eu estou cego! Não posso deixar me parar...}
{4354}{}{Eu estou cego!}
{4355}{}{Eu não consigo ver!}
{4356}{}{AAUGH!!}
{4357}{}{}
{4358}{}{Oof!}
{4359}{}{}
{4360}{}{Eegah!}
{4361}{}{}
{4400}{}{Você vai morrer em breve!}
{4401}{}{Eu voltarei!}
{4402}{}{Mais tarde miseravel!}
{4403}{}{}
{4404}{}{Eu estou poupando você para depois!}
{4405}{}{}
{4406}{}{Eu vou arrancar sua cabeca!}
{4407}{}{Carne fresca!}
{4408}{}{}
{4409}{}{}
{4410}{}{Eu comerei você, um pedaço de cada vez!}
{4411}{}{}
{4412}{}{Eu vou esculpir você como uma iguana-no-espeto!}
{4413}{}{}
{4414}{}{Não morra ainda - Eu quero que você sofra.}
{4415}{}{Você ofendeu o Rei da Boneyard!}
{4416}{}{}
{4417}{}{Você ficara tão bonito quando você estiver morto}
{4418}{}{Morra! Morra! Morra! Morra! Morra!}
{4419}{}{}
{4420}{}{Você vai alimentar as minhocas esta noite.}
{4421}{}{Eu esfolarei você vivo!}
{4422}{}{}
{4423}{}{Vamos! Bring it on, scag!}
{4424}{}{Vamos miseravel. Me de uma luta!}
{4425}{}{Isso e o melhor que você pode fazer?}
{4426}{}{Você não é nada!}
{4427}{}{Eu não posso ser morto!}
{4428}{}{}
{4429}{}{}
{4430}{}{Ack!}
{4431}{}{Eu amo o som de ossos esmagando}
{4432}{}{}
{4433}{}{Eu gosto rough, bim!}
{4434}{}{Meu braço!}
{4435}{}{}
{4436}{}{Bastardo! Meu braço!}
{4437}{}{Meu peito!}
{4438}{}{Argh! Esse foi seu ultimo erro}
{4439}{}{}
{4440}{}{Gasp!}
{4441}{}{Bah!}
{4442}{}{Ack! Isso vai deixar um hematoma}
{4443}{}{Ai!}
{4444}{}{Tolo!}
{4445}{}{Nós podemos trocar golpes o dia todo}
{4446}{}{}
{4447}{}{Eu amo o som de ossos esmagando}
{4448}{}{}
{4449}{}{}
{4450}{}{Minha perna!}
{4451}{}{}
{4452}{}{Maldito seja!}
{4453}{}{}
{4454}{}{Eu apenas terei que cheirar seu medo!}
{4455}{}{Meus olhos! Cara, eu gosto do modo como você luta}
{4456}{}{Ack! Minha virilha!}
{4457}{}{}
{4458}{}{Uuuu! Isso é uma proposta, baby?}
{4459}{}{}
{4460}{}{Então esse e o modo que você quer jogar}
{4461}{}{}
{4500}{}{Eu estou fora daqui!}
{4501}{}{}
{4502}{}{}
{4503}{}{Você não venceu!}
{4504}{}{}
{4505}{}{Vejo você por ai}
{4506}{}{Atacar!}
{4507}{}{Você e historia!}
{4508}{}{Você esta mexendo com a gangue errada!}
{4509}{}{Ninguem muscles in on our turf!}
{4510}{}{}
{4511}{}{}
{4512}{}{Eu sou seu Mestre!}
{4513}{}{Morra!}
{4514}{}{Scab}
{4515}{}{Isto e por que eles nos chamam de Blades}
{4516}{}{Eu vou escrever seu epitafio}
{4517}{}{Espero que isto machuque}
{4518}{}{}
{4519}{}{}
{4520}{}{Eu enterrarei você}
{4521}{}{Você esta morto}
{4522}{}{Eu sou mais virtuoso do que Deus!}
{4523}{}{}
{4524}{}{Mostre-me algumas bolas!}
{4525}{}{Você e tão fraco quanto um Ripper!}
{4526}{}{}
{4527}{}{Você não é um Blade!}
{4528}{}{}
{4529}{}{Meus olhos!}
{4530}{}{Ai! Destruiu meu nariz!}
{4531}{}{Ai!}
{4532}{}{Ai! Meu braço!}
{4533}{}{Ai! Você quebrou ele!}
{4534}{}{Ai!}
{4535}{}{Ai! Meu braço!}
{4536}{}{Ai! Você quebrou ele!}
{4537}{}{Ai!}
{4538}{}{Ai! Meu peito!}
{4539}{}{Oof! Minhas costelas!}
{4540}{}{Grunt}
{4541}{}{Eu zombo da minha dor!}
{4542}{}{Gasp!}
{4543}{}{Isso e o quao forte você bate?}
{4544}{}{}
{4545}{}{Oof!}
{4546}{}{}
{4547}{}{Ai!}
{4548}{}{Ai! Minha perna!}
{4549}{}{Ai! Minha perna!}
{4550}{}{Ai!}
{4551}{}{Ai! Minha perna!}
{4552}{}{Ai! Minha perna!}
{4553}{}{Eu estou cego!}
{4554}{}{Eu não consigo ver!}
{4555}{}{Meus olhos! Filho de um Ripper...}
{4556}{}{Uuuuuu, minha virilha!}
{4557}{}{Aieee!}
{4558}{}{Maldicao, isso doi}
{4559}{}{Ooof!}
{4560}{}{Eu vou rasgar você em pedacos}
{4561}{}{Eu...não...consigo...respirar...}
{4600}{}{}
{4601}{}{}
{4602}{}{É apenas uma prorrogacao, miseravel!}
{4603}{}{Você não venceu!}
{4604}{}{Não ria! Eu vou mijar no seu tumulo}
{4605}{}{Vejo você por ai}
{4606}{}{}
{4607}{}{}
{4608}{}{Você esta mexendo com a gangue errada!}
{4609}{}{}
{4610}{}{}
{4611}{}{Morra!}
{4612}{}{}
{4613}{}{Morra!}
{4614}{}{}
{4615}{}{Quao grande você quer a cicatriz?}
{4616}{}{}
{4617}{}{Espero que isto machuque}
{4618}{}{}
{4619}{}{}
{4620}{}{Eu enterrarei você}
{4621}{}{Você esta morto}
{4622}{}{Eu sou seu Mestre!}
{4623}{}{}
{4624}{}{Mostre-me algumas bolas!}
{4625}{}{Eu possuo você!}
{4626}{}{}
{4627}{}{}
{4628}{}{Isso doi}
{4629}{}{Meus olhos!}
{4630}{}{Ai! Meu nariz...}
{4631}{}{Ai!}
{4632}{}{Ai! Meu braço!}
{4633}{}{Ai! Você quebrou ele!}
{4634}{}{Ai!}
{4635}{}{Ai! Meu braço!}
{4636}{}{Ai! Você quebrou ele!}
{4637}{}{Ai!}
{4638}{}{Ai! Meu peito!}
{4639}{}{Oof! Minhas costelas!}
{4640}{}{Grunt}
{4641}{}{Há! Eu zombo da dor!}
{4642}{}{Gasp!}
{4643}{}{}
{4644}{}{}
{4645}{}{Oof!}
{4646}{}{Ah, sim, isso me acordou!}
{4647}{}{Ai!}
{4648}{}{Ai! Minha perna!}
{4649}{}{Ai! Minha perna!}
{4650}{}{Ai!}
{4651}{}{Ai! Minha perna!}
{4652}{}{Ai! Minha perna!}
{4653}{}{Eu estou cego!}
{4654}{}{Eu não consigo ver!}
{4655}{}{Meus olhos! Filho de um Ripper...}
{4656}{}{Uuuuuu, minha virilha!}
{4657}{}{Aieee!}
{4658}{}{Maldicao, isso doi}
{4659}{}{Ooof!}
{4660}{}{Eu vou rasgar você em pedacos}
{4661}{}{Eu...não...consigo...respirar...}
{4700}{}{}
{4701}{}{Talvez isto não era uma boa ideia}
{4702}{}{}
{4703}{}{}
{4704}{}{Eu não vou morrer por isto!}
{4705}{}{Eu não posso acreditar no que eles estão carregando...}
{4706}{}{}
{4707}{}{Alguém acabou de cometer um grande erro!}
{4708}{}{}
{4709}{}{Quem você pensa que você e?}
{4710}{}{Hora de demonstrar a mercadoria}
{4711}{}{}
{4712}{}{}
{4713}{}{Pratica de tiro ao alvo!}
{4714}{}{}
{4715}{}{Você gosta disto?}
{4716}{}{}
{4717}{}{Que tal isto como poder de fogo?}
{4718}{}{Vamos ver como você maneja isto...}
{4719}{}{}
{4720}{}{}
{4721}{}{}
{4722}{}{}
{4723}{}{}
{4724}{}{Você não esperava isso, esperava?}
{4725}{}{Esse foi seu ultimo erro}
{4726}{}{Amador}
{4727}{}{Seus movimentos são fracos!}
{4728}{}{Ai! Seu/Sua filho da...}
{4729}{}{Eu vou matar você por isso}
{4730}{}{Eu arrancarei sua cabeca fora!}
{4731}{}{Ai, meu braço}
{4732}{}{Maldicao. Meu braço esta destruido!}
{4733}{}{Meu braço!}
{4734}{}{Ai, meu braço}
{4735}{}{Maldicao. Meu braço esta destruido!}
{4736}{}{Meu braço!}
{4737}{}{Ai!}
{4738}{}{Ai! Meu peito!}
{4739}{}{Oof! Minhas costelas!}
{4740}{}{}
{4741}{}{}
{4742}{}{}
{4743}{}{}
{4744}{}{Isso poderia requerer atenção medica... }
{4745}{}{}
{4746}{}{Oof!}
{4747}{}{Ai, minha perna}
{4748}{}{Você pagara por isso!}
{4749}{}{Meu joelho!}
{4750}{}{Ai, minha perna}
{4751}{}{Você pagara por isso!}
{4752}{}{Meu joelho!}
{4753}{}{Eu não consigo ver!}
{4754}{}{Meu olho! Você pagara por isso!}
{4755}{}{}
{4756}{}{Uuuuuu, minha virilha!}
{4757}{}{Então esse e o modo como você quer jogar}
{4758}{}{}
{4759}{}{Urp!}
{4760}{}{}
{4761}{}{Suino!}
{4800}{}{Eu preciso de reforcos!}
{4801}{}{Alguém me ajude!}
{4802}{}{Medico!}
{4803}{}{Recuar! Recuar!}
{4804}{}{Recuar! Recuar!}
{4805}{}{Reagrupar!}
{4806}{}{Eu tomarei conta disto}
{4807}{}{Nós estamos sob ataque!}
{4808}{}{}
{4809}{}{Atacar!}
{4810}{}{}
{4811}{}{Para as armas! Para as armas!}
{4812}{}{Isto e para Adytown!}
{4813}{}{Isto e o que nos fazemos com animais!}
{4814}{}{Bem vindo ao Inferno, miseravel}
{4815}{}{Aprecie os ultimos segundos de sua vida...}
{4816}{}{Você nunca aborrecera ninguém de novo}
{4817}{}{}
{4818}{}{Você não deveria ter comecado isto}
{4819}{}{}
{4820}{}{}
{4821}{}{Você esta acabado, miseravel!}
{4822}{}{}
{4823}{}{Você esta mirando ao acaso, miseravel}
{4824}{}{}
{4825}{}{}
{4826}{}{Você estava brincando com essa, certo?}
{4827}{}{Eu não sou fácil de matar...}
{4828}{}{Maldicao! Bem na cara.}
{4829}{}{Minha cara!}
{4830}{}{Meu nariz!}
{4831}{}{Maldicao! Meu braço}
{4832}{}{Ai! Isso doi!}
{4833}{}{Maldicao. Eu posso estar ferido gravemente}
{4834}{}{Maldicao! Meu braço}
{4835}{}{Ai! Isso doi!}
{4836}{}{Maldicao. Eu posso estar ferido gravemente}
{4837}{}{Ai!}
{4838}{}{Ai! Bem no peito!}
{4839}{}{Oof! Me pegou nas costelas!}
{4840}{}{Oof!}
{4841}{}{}
{4842}{}{Oof! Bem nos intestinos!}
{4843}{}{Argh!}
{4844}{}{Ouch!}
{4845}{}{Oof!}
{4846}{}{Eu... preciso... de... ar...}
{4847}{}{Tiro sortudo!}
{4848}{}{Maldicao, bem no joelho...}
{4849}{}{Eu não estou caindo, miseravel.}
{4850}{}{Tiro sortudo!}
{4851}{}{Maldicao, bem no joelho...}
{4852}{}{Eu não estou caindo, miseravel.}
{4853}{}{Maldicao, Isto não é bom...}
{4854}{}{Maldicao, bem nos olhos!}
{4855}{}{Eu não consigo ver!}
{4856}{}{Uuuuuu, minha virilha!}
{4857}{}{}
{4858}{}{Maldicao, isso doi!}
{4859}{}{Eu...não...consigo...respirar...}
{4860}{}{Seu sadico filho da...}
{4861}{}{Seu/Sua miseravel...}
{4900}{}{Tenho que sair daqui!}
{4901}{}{}
{4902}{}{Misericordia! Misericordia!}
{4903}{}{}
{4904}{}{}
{4905}{}{}
{4906}{}{Por que estas coisas acontecem comigo?!}
{4907}{}{Onde esta meu reforco?}
{4908}{}{Eu poderia usar alguma ajuda aqui!}
{4909}{}{}
{4910}{}{}
{4911}{}{}
{4912}{}{Não leve isto pro lado pessoal}
{4913}{}{}
{4914}{}{}
{4915}{}{}
{4916}{}{Eu creio que eu tenho que machucar você}
{4917}{}{Por favor desca}
{4918}{}{Por favor não me mate por isto}
{4919}{}{}
{4920}{}{Eu acho que eu vou vomitar}
{4921}{}{}
{4922}{}{Eu estou vivo! Eu estou vivo!}
{4923}{}{}
{4924}{}{Você precisa mirar um pouco mais para a direita}
{4925}{}{}
{4926}{}{Este não é seu dia.}
{4927}{}{}
{4928}{}{Não na cara!}
{4929}{}{Ai! Minha cabeca!}
{4930}{}{Você quebrou meu nariz!}
{4931}{}{Ai, meu braço}
{4932}{}{Você quebrou meu braço!}
{4933}{}{Isso era realmente necessario?}
{4934}{}{Ai, meu braço}
{4935}{}{Você quebrou meu braço!}
{4936}{}{Isso era realmente necessario?}
{4937}{}{Oof!}
{4938}{}{Ai! Isso me doi! Muito!}
{4939}{}{}
{4940}{}{Gasp! Não me acerte!}
{4941}{}{Ack! Isso doi!}
{4942}{}{Argh! Por favor pare!}
{4943}{}{Ouch!}
{4944}{}{Oof!}
{4945}{}{Oof!}
{4946}{}{Oof! Gasp! Argh! Ai! Ferida!}
{4947}{}{Ai, minha perna}
{4948}{}{Ei, isso doi!}
{4949}{}{}
{4950}{}{Ai, minha perna}
{4951}{}{Ei, isso doi!}
{4952}{}{Isso era realmente necessario?}
{4953}{}{Argh! Minha retina!}
{4954}{}{Meu olho! Ah meu deus, Eu estou cego!}
{4955}{}{Por que a vida e tão cruel!}
{4956}{}{Uuuuuu, minha virilha!}
{4957}{}{Uuu! Isso doi!}
{4958}{}{Isso foi muito inamistoso.}
{4959}{}{}
{4960}{}{Urp!}
{4961}{}{}
{5000}{}{Eu estou fora daqui!}
{5001}{}{}
{5002}{}{Aaaaahhhh!}
{5003}{}{}
{5004}{}{}
{5005}{}{Vejo você por ai}
{5006}{}{}
{5007}{}{}
{5008}{}{Uma licao precisa ser ensinada a alguém}
{5009}{}{Alguém esta morrendo}
{5010}{}{}
{5011}{}{}
{5012}{}{}
{5013}{}{Morra!}
{5014}{}{Morte e fogo!}
{5015}{}{Miseravel}
{5016}{}{Fogo do atomo!}
{5017}{}{}
{5018}{}{Nunca deveria ter mexido conosco}
{5019}{}{Para o Glow com você!}
{5020}{}{Eu vou selar sua tumba}
{5021}{}{Você esta morto!}
{5022}{}{}
{5023}{}{Não estou impressionado}
{5024}{}{}
{5025}{}{Eu estou construindo sua tumba}
{5026}{}{Você não vai me enterrar!}
{5027}{}{O que você esperava?}
{5028}{}{}
{5029}{}{Meus olhos!}
{5030}{}{Ai!}
{5031}{}{Ai!}
{5032}{}{Ai! Meu braço!}
{5033}{}{Ai! Você quebrou ele!}
{5034}{}{Ai!}
{5035}{}{Ai! Meu braço!}
{5036}{}{}
{5037}{}{Ai!}
{5038}{}{Oof!}
{5039}{}{Ouch!}
{5040}{}{Gack!}
{5041}{}{Argh!}
{5042}{}{Grrr!}
{5043}{}{}
{5044}{}{Eu comerei seu figado por isso!}
{5045}{}{}
{5046}{}{Oof!}
{5047}{}{Ai!}
{5048}{}{Ai! Minha perna!}
{5049}{}{Ai! Minha perna!}
{5050}{}{Ai!}
{5051}{}{Ai! Minha perna!}
{5052}{}{Ai! Minha perna!}
{5053}{}{Eu estou cego!}
{5054}{}{Eu não consigo ver!}
{5055}{}{Meu olho!}
{5056}{}{Uuuuuu, minha virilha!}
{5057}{}{Uuu! Isso doi!}
{5058}{}{Isso foi muito inamistoso.}
{5059}{}{}
{5060}{}{Urp!}
{5061}{}{}
{5100}{}{Recuar!}
{5101}{}{Retirar!}
{5102}{}{Reagrupar!}
{5103}{}{Isto não acabou!}
{5104}{}{Eu retornarei!}
{5105}{}{Nós voltaremos!}
{5106}{}{}
{5107}{}{}
{5108}{}{Peguem o intruso!}
{5109}{}{Morte para o humano!}
{5110}{}{}
{5111}{}{}
{5112}{}{Para o Glow com você!}
{5113}{}{}
{5114}{}{Humano sujo!}
{5115}{}{}
{5116}{}{}
{5117}{}{Morte e fogo!}
{5118}{}{Você queimara!}
{5119}{}{}
{5120}{}{Você caira e nunca se levantara de novo!}
{5121}{}{Eu vou selar sua tumba}
{5122}{}{Não acertou}
{5123}{}{Ninguem sela minha tumba!}
{5124}{}{Você não é lutador}
{5125}{}{}
{5126}{}{Você não vencera, humano}
{5127}{}{}
{5128}{}{Isso doi}
{5129}{}{Meus olhos!}
{5130}{}{Aghh!}
{5131}{}{Aghh!}
{5132}{}{Ai! Meu braço!}
{5133}{}{Ai! Você quebrou ele!}
{5134}{}{Aghh!}
{5135}{}{Ai! Meu braço!}
{5136}{}{Ai! Você quebrou ele!}
{5137}{}{Ai!}
{5138}{}{Oof!}
{5139}{}{Ouch!}
{5140}{}{Gack!}
{5141}{}{Argh!}
{5142}{}{Grrr!}
{5143}{}{Ufa! Vocês vermes são todos iguais}
{5144}{}{Eu comerei seu figado por isso!}
{5145}{}{}
{5146}{}{Oof!}
{5147}{}{Aghh!}
{5148}{}{Ai! Minha perna!}
{5149}{}{Ai! Minha perna!}
{5150}{}{Aghh!}
{5151}{}{Ai! Minha perna!}
{5152}{}{Ai! Minha perna!}
{5153}{}{Amaldicoo você com fogo!}
{5154}{}{Eu não consigo ver!}
{5155}{}{Meu olho!}
{5156}{}{Uuuuuu, minha virilha!}
{5157}{}{Ooof!}
{5158}{}{Eu apagarei seu tumulo!}
{5159}{}{}
{5160}{}{Urp!}
{5161}{}{}
{5200}{}{Corra!}
{5201}{}{Você não me matara!}
{5202}{}{Eu voltarei!}
{5203}{}{Meus amigos pegarao você pra mim!}
{5204}{}{Você paga por isto -- mais tarde!}
{5205}{}{Nós somo os Escolhidos! Você morre mais tarde!}
{5206}{}{Sua morte chega!}
{5207}{}{Aqueles que aborrecem os Escolhidos, não aborrecem ninguém de novo!}
{5208}{}{Armas humanas não podem me prejudicar!}
{5209}{}{Você sofrera, sofrera muito!}
{5210}{}{}
{5211}{}{Quem é estúpido o bastante para nos enraivecer?}
{5212}{}{}
{5213}{}{Ninguem salva você agora!}
{5214}{}{}
{5215}{}{Agora você morre morte ardente!}
{5216}{}{Morra Humano Tolo!}
{5217}{}{Agora você morre uma morte gritando}
{5218}{}{}
{5219}{}{Agora eu esmago você}
{5220}{}{Você não consegue enfrentar os Escolhidos!}
{5221}{}{Sofra, humano!}
{5222}{}{Por que você luta?}
{5223}{}{Isso e o melhor que os humanos pode fazem!}
{5224}{}{Você não tem poder!}
{5225}{}{Você me faz rir bastante!}
{5226}{}{Isso foi um ataque?}
{5227}{}{Nós somos os Escolhidos!}
{5228}{}{Ahhhgh! Minha cara!}
{5229}{}{Minha cara! Você sofrera!}
{5230}{}{Ahhhgh! Eu vou rasgar você em pedacos!}
{5231}{}{Ahhhgh!}
{5232}{}{}
{5233}{}{Ahhhgh! Eu quebro seu pescoco por isso!}
{5234}{}{Ahhhgh!}
{5235}{}{}
{5236}{}{Ahhhgh! Eu quebro seu pescoco por isso!}
{5237}{}{Oof!}
{5238}{}{Grrr!}
{5239}{}{Eu mato você por isso!}
{5240}{}{Você não me machucar quando você morto!}
{5241}{}{Eu zombo do seu ataque fraco!}
{5242}{}{Grrr!}
{5243}{}{Ah!}
{5244}{}{Eu vou mergulhar você!}
{5245}{}{Grrr! Você me enraivece}
{5246}{}{Agh!}
{5247}{}{Ahhhgh! Minha perna}
{5248}{}{}
{5249}{}{Ahhhgh! Eu quebro seu pescoco por isso!}
{5250}{}{Ahhhgh! Minha perna}
{5251}{}{}
{5252}{}{Ahhhgh! Eu quebrarei seu pescoco por isso!}
{5253}{}{Ahhhgh! Humano miseravel! Eu estou cego!}
{5254}{}{Ahhhgh! Dor! O que você fez!}
{5255}{}{Ahhhgh! Eu torturarei você por muitos dias!}
{5256}{}{Essa é a fraqueza humana!}
{5257}{}{}
{5258}{}{Você e estúpido, humano!}
{5259}{}{Por que você me ataca lá?}
{5260}{}{Eu machucarei você por muitas horas}
{5261}{}{}
{5300}{}{Corra!}
{5301}{}{Você não me matara!}
{5302}{}{Devo escapar}
{5303}{}{}
{5304}{}{Você paga por isto -- mais tarde!}
{5305}{}{Você morre mais tarde!}
{5306}{}{Quem ousa aborrecer os Escolhidos?}
{5307}{}{Você me deixa zangado!}
{5308}{}{Armas humanas não podem me prejudicar!}
{5309}{}{}
{5310}{}{Nenhuma misericordia para os inimigos!}
{5311}{}{Quando eu luto, eu mato!}
{5312}{}{}
{5313}{}{Ninguem salva você agora!}
{5314}{}{Agora você morre!}
{5315}{}{Deixe-me ver sua dor!}
{5316}{}{Eu quebro seu corpo!}
{5317}{}{}
{5318}{}{}
{5319}{}{Agora você morre}
{5320}{}{Eu machucar você muito}
{5321}{}{Sofra!}
{5322}{}{Você e fraco!}
{5323}{}{Vocês são fracos...}
{5324}{}{Você não tem força!}
{5325}{}{}
{5326}{}{Isso foi um ataque?}
{5327}{}{Vocês são inuteis}
{5328}{}{Ahhhgh! Minha cara!}
{5329}{}{Minha cara! Você sofrera!}
{5330}{}{Ahhhgh! Eu vou rasgar você em pedacos!}
{5331}{}{Ahhhgh!}
{5332}{}{Ai! Você quase machucar os Escolhidos!}
{5333}{}{Ahhhgh! Eu quebro seu pescoco por isso!}
{5334}{}{Ahhhgh!}
{5335}{}{}
{5336}{}{Ahhhgh! Eu quebro seu pescoco por isso!}
{5337}{}{Eu retornarei esta dor para você!}
{5338}{}{Oof!}
{5339}{}{Ouch!}
{5340}{}{Hmm, você poderia ser problema}
{5341}{}{Grrr! Eu aguardo ansiosamente pela sua morte}
{5342}{}{Grrr!}
{5343}{}{Você pode me machucar mas você não pode vencer!}
{5344}{}{Grrr!}
{5345}{}{Ai! Essa não foi boa ideia me machucar}
{5346}{}{}
{5347}{}{Ahhhgh! Minha perna}
{5348}{}{}
{5349}{}{Ahhhgh! Eu quebro seu pescoco por isso!}
{5350}{}{Ahhhgh! Minha perna}
{5351}{}{Você quase machucar os Escolhidos!}
{5352}{}{Ahhhgh! Eu quebrarei seu pescoco por isso!}
{5353}{}{Ahhhgh! Eu estou cego!}
{5354}{}{Ahhhgh! Dor! O que você fez a mim?}
{5355}{}{Ahhhgh! Os olhos queimam como o fogo do Glow!}
{5356}{}{Essa é a fraqueza humana!}
{5357}{}{}
{5358}{}{}
{5359}{}{Por que você me ataca lá?}
{5360}{}{Sua morte será dolorosa, humano!}
{5361}{}{}
{5400}{}{Corra!}
{5401}{}{Você não me matara!}
{5402}{}{Eu voltarei!}
{5403}{}{}
{5404}{}{Você paga por isto -- mais tarde!}
{5405}{}{Você morre mais tarde!}
{5406}{}{Sua morte chega!}
{5407}{}{}
{5408}{}{Armas humanas não podem me prejudicar!}
{5409}{}{Você sofrera, sofrera muito!}
{5410}{}{Eu vejo inimigos para destruir!}
{5411}{}{Quem é estúpido o bastante para nos enraivecer?}
{5412}{}{}
{5413}{}{Ninguem salva você agora!}
{5414}{}{Nós somos seus Mestres!}
{5415}{}{Agora você morre uma morte ardente!}
{5416}{}{Morra Humano Tolo!}
{5417}{}{Agora você morre uma morte gritando}
{5418}{}{}
{5419}{}{Agora eu esmago você}
{5420}{}{}
{5421}{}{Sofra, humano!}
{5422}{}{Por que você luta?}
{5423}{}{Isso e o melhor que os humanos podem fazer?}
{5424}{}{Você não tem força!}
{5425}{}{}
{5426}{}{}
{5427}{}{Nós somos os Escolhidos!}
{5428}{}{Ahhhgh! Minha cara!}
{5429}{}{Minha cara! Você sofrera!}
{5430}{}{Ahhhgh! Eu vou rasgar você em pedacos!}
{5431}{}{Ahhhgh!}
{5432}{}{Você chama isso de dor? Eu zombo!}
{5433}{}{Ahhhgh! Eu quebro seu pescoco por isso!}
{5434}{}{Ahhhgh!}
{5435}{}{Você chama isso de dor? Eu zombo!}
{5436}{}{Ahhhgh! Eu quebro seu pescoco por isso!}
{5437}{}{Não há dor que possa me machucar!}
{5438}{}{Oof! Eu mato você}
{5439}{}{Eu odeio seu tipo!}
{5440}{}{}
{5441}{}{Argh!}
{5442}{}{Grrr!}
{5443}{}{Ai! Eu tomarei conta de você eu mesmo!}
{5444}{}{}
{5445}{}{Grrr!}
{5446}{}{Oof!}
{5447}{}{Ahhhgh! Minha perna}
{5448}{}{Você chama isso de dor? Eu zombo!}
{5449}{}{Ahhhgh! Eu quebro seu pescoco por isso!}
{5450}{}{Ahhhgh! Minha perna}
{5451}{}{Você chama isso de dor? Eu zombo!}
{5452}{}{Ahhhgh! Eu quebrarei seu pescoco por isso!}
{5453}{}{Ahhhgh! Humano miseravel! Eu estou cego!}
{5454}{}{Ahhhgh! Dor! O que você fez!}
{5455}{}{Ahhhgh! Eu torturarei você por muitos dias!}
{5456}{}{}
{5457}{}{}
{5458}{}{Você e humano estúpido!}
{5459}{}{Por que você me ataca lá?}
{5460}{}{Eu machucarei você por muitas horas}
{5461}{}{}
{5500}{}{Corra!}
{5501}{}{Você não me matara!}
{5502}{}{Eu voltarei!}
{5503}{}{Isto não esta acabado!}
{5504}{}{Sua vitoria será de duração muito curta, humano!}
{5505}{}{Nós somos os Escolhidos! Você morrera mais tarde!}
{5506}{}{De um passo a frente, pois a Morte anda conosco!}
{5507}{}{}
{5508}{}{Armas humanas não podem nos fazer mal!}
{5509}{}{Você sofrera!}
{5510}{}{Ninguem se opora a nos!}
{5511}{}{}
{5512}{}{}
{5513}{}{Ninguem pode salvar você}
{5514}{}{Nós somos seus Mestres!}
{5515}{}{Agora você morrera uma Morte Ardente!}
{5516}{}{Morra Humano Tolo!}
{5517}{}{Agora você morre uma morte engracada}
{5518}{}{Seu sangue e meu vinho!}
{5519}{}{Agora eu esmago você}
{5520}{}{Você não consegue enfrentar os Escolhidos!}
{5521}{}{Sofra, humano!}
{5522}{}{Por que você luta tão lamentavelmente?}
{5523}{}{}
{5524}{}{Você chama esta tolice cambaleante uma luta?}
{5525}{}{Seu ataque só me faz rir}
{5526}{}{}
{5527}{}{}
{5528}{}{Ahhhgh! Minha cara!}
{5529}{}{Minha cara! Você sofrera!}
{5530}{}{Ahhhgh! Eu vou rasgar você em pedacos!}
{5531}{}{Ahhhgh!}
{5532}{}{Você chama isso de dor? Eu zombo!}
{5533}{}{Ahhhgh! Eu quebro seu pescoco por isso!}
{5534}{}{Ahhhgh!}
{5535}{}{}
{5536}{}{Ahhhgh! Eu quebro seu pescoco por isso!}
{5537}{}{Você não pode me derrotar!}
{5538}{}{Eu matarei você por isso!}
{5539}{}{Sua morte será lendaria!}
{5540}{}{Agora eu estou zangado!}
{5541}{}{Oof!}
{5542}{}{Grrr!}
{5543}{}{Oof! Você não pode sobreviver}
{5544}{}{}
{5545}{}{Você não tem ideia de com o que você esta lidando, humano}
{5546}{}{Eu lavarei minha frente com seu sangue!}
{5547}{}{Ahhhgh! Minha perna}
{5548}{}{}
{5549}{}{Ahhhgh! Eu quebro seu pescoco por isso!}
{5550}{}{Ahhhgh! Minha perna}
{5551}{}{}
{5552}{}{Ahhhgh! Eu quebrarei seu pescoco por isso!}
{5553}{}{Ahhhgh! Humano miseravel! Eu estou cego!}
{5554}{}{Ahhhgh! Mas eu não preciso de olhos para matar você.}
{5555}{}{Ahhhgh! Eu torturarei você por muitos dias!}
{5556}{}{Essa é a fraqueza humana!}
{5557}{}{}
{5558}{}{Você e humano estúpido!}
{5559}{}{Por que você me ataca lá?}
{5560}{}{Eu machucarei você por muitas horas}
{5561}{}{Essa foi a afronta final!}
{5600}{}{Eu estou fora daqui!}
{5601}{}{Tenha misericordia!}
{5602}{}{Por favor pare!}
{5603}{}{Socorro!}
{5604}{}{Aaaaahhhh!}
{5605}{}{Fujam!}
{5606}{}{}
{5607}{}{Você não esta nos dando muita escolha!}
{5608}{}{Quem você pensa que você e?}
{5609}{}{Ninguem vai tomar este lugar...}
{5610}{}{Nós poderiamos ter feito um acordo}
{5611}{}{Esse foi um movimento ruim, meu amigo}
{5612}{}{Não deveria começar o que você não pode terminar}
{5613}{}{Você pediu por isto!}
{5614}{}{}
{5615}{}{Eu sei como lidar com suinos!}
{5616}{}{Você pagara pelo que você fez!}
{5617}{}{Seu numero aumentou!}
{5618}{}{}
{5619}{}{}
{5620}{}{Hora de contar suas perdas}
{5621}{}{}
{5622}{}{Whew!}
{5623}{}{Você não vale vinte pratas}
{5624}{}{Você não é muito bom nisto}
{5625}{}{You're just a cut rate miseravel}
{5626}{}{Você deveria apenas sair fora!}
{5627}{}{}
{5628}{}{Não na cara!}
{5629}{}{}
{5630}{}{Ai! Minha orelha!}
{5631}{}{Ai, meu braço}
{5632}{}{Maldito seja!}
{5633}{}{Você quebrou meu braço!}
{5634}{}{Ai, meu braço}
{5635}{}{Maldito seja!}
{5636}{}{Você quebrou meu braço!}
{5637}{}{Ai!}
{5638}{}{Oof!}
{5639}{}{Ouch!}
{5640}{}{Gack!}
{5641}{}{Argh!}
{5642}{}{}
{5643}{}{Eu deveria ter feito um acordo!}
{5644}{}{Oof! Eu imagino quanto eu conseguirei pelo seu cadaver}
{5645}{}{Ai!}
{5646}{}{Oof!}
{5647}{}{Ai, minha perna}
{5648}{}{Meu joelho!}
{5649}{}{Ai! Minha perna esta destruida!}
{5650}{}{Ai, minha perna}
{5651}{}{Meu joelho!}
{5652}{}{Ai! Minha perna esta destruida!}
{5653}{}{Eu estou cego!}
{5654}{}{Ugggh. Minha cara! Meus olhos!}
{5655}{}{Meus olhos! Maldito seja até o Inferno...}
{5656}{}{Uuuuuu, minha virilha!}
{5657}{}{Uuuuuu, esse foi um golpe barato, miseravel.}
{5658}{}{Urp!}
{5659}{}{Eu...não...consigo...respirar...}
{5660}{}{}
{5661}{}{A dor, a dor...}
{5700}{}{Eu tenho que sair daqui!}
{5701}{}{Corra! Corra!}
{5702}{}{Alguém me ajude!}
{5703}{}{Nós todos vamos morrer!}
{5704}{}{Algum dia, você recebera o que esta vindo para você!}
{5705}{}{ Eu não vou morrer por isto!}
{5706}{}{É muito tarde pra correr}
{5707}{}{Quem deixou você no Hub?}
{5708}{}{Ei você!}
{5709}{}{Nós não precisamos do seu tipo por aqui!}
{5710}{}{Ninguem vai tomar este lugar...}
{5711}{}{Quem você pensa que você e?}
{5712}{}{Tome isto!}
{5713}{}{Você gosta disto?}
{5714}{}{Isto e o que nos fazemos com os vermes!}
{5715}{}{Isto e para você!}
{5716}{}{Tchau!}
{5717}{}{}
{5718}{}{Escoria criadora de problemas!}
{5719}{}{}
{5720}{}{Seu/Sua animal!}
{5721}{}{Você se arrependera de por o pe no Hub!}
{5722}{}{Você não é tão bom/boa quanto você pensa }
{5723}{}{}
{5724}{}{Você e apenas um facinora comum}
{5725}{}{}
{5726}{}{Eu não vou ser sua vitima}
{5727}{}{Esse foi seu ultimo erro}
{5728}{}{}
{5729}{}{Aggghhh!}
{5730}{}{Minha cara! Minha cara!}
{5731}{}{Aggghhh! Meu braço}
{5732}{}{Meu braço!}
{5733}{}{O maldito braço esta inaproveitavel agora...}
{5734}{}{Aggghhh! Meu braço}
{5735}{}{Meu braço!}
{5736}{}{O maldito braço esta inaproveitavel agora...}
{5737}{}{Ai!}
{5738}{}{Oof!}
{5739}{}{Ouch!}
{5740}{}{Gack!}
{5741}{}{Argh!}
{5742}{}{Grrr!}
{5743}{}{!}
{5744}{}{}
{5745}{}{Ouch!}
{5746}{}{Oof!}
{5747}{}{Aggghhh! Minha perna}
{5748}{}{Minha perna!}
{5749}{}{Maldicao, minha perna esta inaproveitavel...}
{5750}{}{Aggghhh! Minha perna}
{5751}{}{Minha perna!}
{5752}{}{Maldicao, minha perna esta inaproveitavel...}
{5753}{}{Aggghhh! Eu estou cego!}
{5754}{}{Maldicao! Tudo esta queimando...}
{5755}{}{Meu olho! Você pagara por isso!}
{5756}{}{Uuuuuu, minha virilha!}
{5757}{}{Oooooooooo!}
{5758}{}{Eu...não...consigo...respirar...}
{5759}{}{}
{5760}{}{A dor, a dor...}
{5761}{}{Maldicao, isso doi!}
{5800}{}{}
{5801}{}{Corra! Corra!}
{5802}{}{Eu estou saindo daqui!}
{5803}{}{Eu sou muito jovem pra morrer!}
{5804}{}{Nas sombras!}
{5805}{}{Esta luta não esta indo do meu modo...}
{5806}{}{Vamos pregar este patife!}
{5807}{}{Que comece o massacre!}
{5808}{}{Ei você!}
{5809}{}{Eu não gosto da sua atitude...}
{5810}{}{Ninguem vai tomar este lugar...}
{5811}{}{Quem você pensa que você e?}
{5812}{}{}
{5813}{}{Você gosta disto?}
{5814}{}{Isto e o que nos fazemos com os vermes!}
{5815}{}{Eu vou empaturrar você para uma soneca no po!}
{5816}{}{Seu/Sua patife insolente!}
{5817}{}{Você é um chato de verdade}
{5818}{}{Você me enoja!}
{5819}{}{Morte or gloria!}
{5820}{}{Você vai fazer uma bagunca terrível}
{5821}{}{Você se arrependera de por o pe no Hub!}
{5822}{}{Eu vou me baixar quando eu enfrentar você}
{5823}{}{}
{5824}{}{Você e apenas um facinora comum}
{5825}{}{}
{5826}{}{Você realmente não deveria ter se incomodado}
{5827}{}{Esse foi seu ultimo erro}
{5828}{}{Maldicao, isso arde!}
{5829}{}{Aggghhh!}
{5830}{}{Minha cara! Minha linda cara!}
{5831}{}{Aggghhh! Meu braço}
{5832}{}{Meu braço!}
{5833}{}{O maldito braço esta inaproveitavel agora...}
{5834}{}{Aggghhh! Meu braço}
{5835}{}{Meu braço!}
{5836}{}{O maldito braço esta inaproveitavel agora...}
{5837}{}{}
{5838}{}{Oof!}
{5839}{}{Ouch!}
{5840}{}{Oof! Minhas costelas doem}
{5841}{}{Bosta! Isso doi!}
{5842}{}{Ouch! Maldito seja!}
{5843}{}{Argh!}
{5844}{}{}
{5845}{}{}
{5846}{}{Oof!}
{5847}{}{Aggghhh! Minha perna}
{5848}{}{Minha perna!}
{5849}{}{Maldicao, minha perna esta inaproveitavel...}
{5850}{}{Aggghhh! Minha perna}
{5851}{}{Minha perna!}
{5852}{}{Maldicao, minha perna esta inaproveitavel...}
{5853}{}{Aggghhh! Eu estou cego!}
{5854}{}{Maldicao! Tudo esta queimando...}
{5855}{}{O que você fez a mim!}
{5856}{}{Uuuuuu, minha virilha!}
{5857}{}{Você não é nada alem de um facinora comum!}
{5858}{}{}
{5859}{}{}
{5860}{}{}
{5861}{}{Maldicao, isso doi!}
{5900}{}{Eu estou fora daqui!}
{5901}{}{Tchau!}
{5902}{}{Aaaaahhhh!}
{5903}{}{Mais tarde. Talvez.}
{5904}{}{}
{5905}{}{Vejo você por ai}
{5906}{}{}
{5907}{}{Defendam nossos lares!}
{5908}{}{Uma licao deve ser ensinada a alguém}
{5909}{}{Alguém esta morrendo}
{5910}{}{}
{5911}{}{Ninguem mexe com o Hub!}
{5912}{}{Tome isto!}
{5913}{}{Morra e fique morto!}
{5914}{}{Finja de morto!}
{5915}{}{Miseravel}
{5916}{}{Seu nojento!}
{5917}{}{Espero que isto machuque}
{5918}{}{Nunca deveria ter mexido conosco}
{5919}{}{Para o Glow com você!}
{5920}{}{Vá pro Inferno!}
{5921}{}{Você esta morto}
{5922}{}{Não acertou!}
{5923}{}{Não estou impressionado}
{5924}{}{}
{5925}{}{Eu não sou assim fácil}
{5926}{}{Ninguem vai me humilhar!}
{5927}{}{O que você esperava?}
{5928}{}{Isso doi}
{5929}{}{Uuu, meu cranio dolorido!}
{5930}{}{Ai!}
{5931}{}{Ai!}
{5932}{}{Ai! Meu braço!}
{5933}{}{Ai! Meu cotovelo!}
{5934}{}{Ai!}
{5935}{}{Ai! Meu braço!}
{5936}{}{Ai! Meu cotovelo!}
{5937}{}{Ai! Meu peito!}
{5938}{}{Oof!}
{5939}{}{Ouch!}
{5940}{}{}
{5941}{}{}
{5942}{}{Ouch! Maldito seja!}
{5943}{}{Argh!}
{5944}{}{Ai!}
{5945}{}{}
{5946}{}{Oof!}
{5947}{}{Ai!}
{5948}{}{Ai! Minha perna!}
{5949}{}{Ai! Minha perna!}
{5950}{}{Ai!}
{5951}{}{Ai! Minha perna!}
{5952}{}{Ai! Minha perna!}
{5953}{}{Eu estou cego!}
{5954}{}{Eu não consigo ver!}
{5955}{}{Meu olho!}
{5956}{}{Uuuuuu, minha virilha!}
{5957}{}{Uuu! Isso doi!}
{5958}{}{}
{5959}{}{}
{5960}{}{Urp!}
{5961}{}{}
{6000}{}{Ataque alguém mais, por favor!}
{6001}{}{Tenha misericordia!}
{6002}{}{Alguém me ajude!}
{6003}{}{Por favor pare!}
{6004}{}{Talvez isto não era uma boa ideia}
{6005}{}{Eu não vou morrer por isto!}
{6006}{}{Espere até eu pegar você...}
{6007}{}{}
{6008}{}{Ei você!}
{6009}{}{Nós não precisamos do seu tipo por aqui!}
{6010}{}{}
{6011}{}{Eu vou desmontar você como um relogio barato}
{6012}{}{Tome isto!}
{6013}{}{Você gosta disto?}
{6014}{}{Morra!}
{6015}{}{Sua aberracao mutante!}
{6016}{}{Eu como miseraveis como você no cafe da manha}
{6017}{}{Vou alimentar os cachorros com você}
{6018}{}{}
{6019}{}{Certo. Você pediu por isto.}
{6020}{}{}
{6021}{}{}
{6022}{}{Você não é tão bom/boa quanto você pensa }
{6023}{}{Isso e o melhor que você pode fazer?}
{6024}{}{}
{6025}{}{}
{6026}{}{}
{6027}{}{Lamentavel}
{6028}{}{Maldicao!}
{6029}{}{Meu cranio dolorido}
{6030}{}{Minha cara! Minha cara!}
{6031}{}{Aggghhh! Meu braço}
{6032}{}{Meu braço!}
{6033}{}{Ah cara, isso doi!}
{6034}{}{Aggghhh! Meu braço}
{6035}{}{Meu braço!}
{6036}{}{}
{6037}{}{}
{6038}{}{Oof!}
{6039}{}{Ouch!}
{6040}{}{Oof! Minhas costelas doem}
{6041}{}{Ugh! Isso doi!}
{6042}{}{Maldicao! Eu cuspo em você!}
{6043}{}{Argh!}
{6044}{}{Ah, minhas costelas!}
{6045}{}{Ai!!!}
{6046}{}{Oof!}
{6047}{}{Aggghhh! Minha perna}
{6048}{}{Minha perna!}
{6049}{}{La se vai meu joelho}
{6050}{}{Aggghhh! Minha perna}
{6051}{}{Minha perna!}
{6052}{}{La se vai meu joelho}
{6053}{}{Aggghhh! Eu estou cego!}
{6054}{}{Meus olhos! Meus olhos!}
{6055}{}{Meu olho! Você pagara por isso!}
{6056}{}{Uuuuuu, minha virilha!}
{6057}{}{Oooooooooo!}
{6058}{}{Eu...não...consigo...respirar...}
{6059}{}{}
{6060}{}{A dor, a dor...}
{6061}{}{Maldicao, isso doi!}
{6100}{}{Eu estou fora daqui!}
{6101}{}{Talvez isto não era uma boa ideia}
{6102}{}{Ataque alguém mais, ok?}
{6103}{}{Yikes!}
{6104}{}{Eu não vou morrer por isto!}
{6105}{}{Isso e demais para mim}
{6106}{}{Ei você!}
{6107}{}{Eu vou ensinar a você algumas maneiras}
{6108}{}{Nós não precisamos do seu tipo por aqui!}
{6109}{}{Você precisa aprender um pouco de respeito!}
{6110}{}{Hora de ganhar meu pagamento...}
{6111}{}{Espere até eu pegar você...}
{6112}{}{}
{6113}{}{}
{6114}{}{}
{6115}{}{Você gosta disto?}
{6116}{}{}
{6117}{}{}
{6118}{}{Vamos ver o quao forte você é.}
{6119}{}{Miseravel}
{6120}{}{}
{6121}{}{Eu vou por você no seu lugar para o bem}
{6122}{}{Sua mamae ensinou a você esse movimento?}
{6123}{}{}
{6124}{}{Você não é bom/boa o bastante}
{6125}{}{Esse foi seu ultimo erro}
{6126}{}{Amador}
{6127}{}{Você aprende a lutar em bares?}
{6128}{}{Ai! Seu/Sua filho da...}
{6129}{}{Você quebrou meu nariz!}
{6130}{}{Eu arrancarei sua cabeca fora!}
{6131}{}{Ai, meu braço}
{6132}{}{Você acabou de cometer o maior erro da sua vida}
{6133}{}{Meu braço!}
{6134}{}{Ai, meu braço}
{6135}{}{Você acabou de cometer o maior erro da sua vida}
{6136}{}{Meu braço!}
{6137}{}{Urp!}
{6138}{}{Oof!}
{6139}{}{Ouch!}
{6140}{}{}
{6141}{}{Ugh! Isso doi!}
{6142}{}{Ouch!}
{6143}{}{Argh!}
{6144}{}{Ah, Eu acho que você quebrou uma costela!}
{6145}{}{Ai!!! Meu baco!}
{6146}{}{Oof!}
{6147}{}{Ai, minha perna}
{6148}{}{Eu não preciso ficar de pe para matar você!}
{6149}{}{Meu joelho!}
{6150}{}{Ai, minha perna}
{6151}{}{Eu não preciso ficar de pe para matar você!}
{6152}{}{Meu joelho!}
{6153}{}{Eu não consigo ver!}
{6154}{}{Esta luta esta ficando pior a cada segundo}
{6155}{}{Esse foi um tiro barato de verdade!}
{6156}{}{Uuuuuu, minha virilha!}
{6157}{}{Eu sentirei isso de manha}
{6158}{}{}
{6159}{}{Urp!}
{6160}{}{}
{6161}{}{}
{6200}{}{Nós nos encontraremos de novo. Aposte nisso}
{6201}{}{Você me deve uma revanche. Depois}
{6202}{}{Você venceu este round mas o jogo ainda não acabou}
{6203}{}{Eu superarei você mais tarde}
{6204}{}{Se você sabe o que é bom pra você, você saira da cidade}
{6205}{}{Isto não esta acabado, amigo.}
{6206}{}{}
{6207}{}{Eu vou ensinar a você algumas maneiras}
{6208}{}{}
{6209}{}{Você precisa aprender um pouco de respeito!}
{6210}{}{}
{6211}{}{}
{6212}{}{}
{6213}{}{}
{6214}{}{}
{6215}{}{Você gosta disto?}
{6216}{}{}
{6217}{}{}
{6218}{}{Vamos ver o quao forte você é.}
{6219}{}{Miseravel}
{6220}{}{}
{6221}{}{Eu vou chutar seu traseiro para fora da cidade}
{6222}{}{Você esta fora da sua liga}
{6223}{}{}
{6224}{}{Você não é bom/boa o bastante}
{6225}{}{Você deveria sair enquanto você ainda esta inteiro}
{6226}{}{Amador}
{6227}{}{}
{6228}{}{Ai! Seu/Sua filho da...}
{6229}{}{}
{6230}{}{Eu arrancarei sua cabeca fora!}
{6231}{}{Ai, meu braço}
{6232}{}{Você esta comecando a me deixar puto}
{6233}{}{Meu braço!}
{6234}{}{Ai, meu braço}
{6235}{}{Você esta comecando a me deixar puto}
{6236}{}{Meu braço!}
{6237}{}{Ahh!}
{6238}{}{Oof!}
{6239}{}{Ouch!}
{6240}{}{Oof! Indo nos meus rins, huh?}
{6241}{}{}
{6242}{}{}
{6243}{}{}
{6244}{}{Ah, minhas costelas!}
{6245}{}{}
{6246}{}{}
{6247}{}{Ai, minha perna}
{6248}{}{Tiro bacana. Espere até que seja minha vez}
{6249}{}{Meu joelho!}
{6250}{}{Ai, minha perna}
{6251}{}{Tiro bacana. Espere até que seja minha vez}
{6252}{}{Meu joelho!}
{6253}{}{Eu não consigo ver!}
{6254}{}{Esta luta esta ficando pior a cada segundo}
{6255}{}{}
{6256}{}{Aaaaaugh!!!}
{6257}{}{}
{6258}{}{Ei, mantenha-a acima do cinto}
{6259}{}{Urp!}
{6260}{}{}
{6261}{}{}
{6300}{}{Tenho que sair daqui!}
{6301}{}{Eu voltarei...}
{6302}{}{Você vai pagar pelo que você fez!}
{6303}{}{Mais tarde miseravel!}
{6304}{}{Você ainda não ouviu sobre mim pela ultima vez!}
{6305}{}{Você pagara por isto - mais tarde!}
{6306}{}{}
{6307}{}{Carne fresca...}
{6308}{}{Eu vou dancar no seu tumulo}
{6309}{}{}
{6310}{}{É hora de matar!}
{6311}{}{}
{6312}{}{}
{6313}{}{Sinta-se livre para gritar}
{6314}{}{Vou apreciar isto.}
{6315}{}{}
{6316}{}{Vou alimentar os cachorros com você}
{6317}{}{Ninguem vai tirar Junktown de nos}
{6318}{}{}
{6319}{}{Eu vou obter um bonus por isso}
{6320}{}{Morra!}
{6321}{}{Eu como miseraveis como você no cafe da manha}
{6322}{}{}
{6323}{}{Isso e o melhor que você pode fazer?}
{6324}{}{}
{6325}{}{Tente mirar da proxima vez...}
{6326}{}{}
{6327}{}{Perdedor}
{6328}{}{Não na cara!}
{6329}{}{Ah, minha cabeca doi}
{6330}{}{Você quebrou meu nariz!}
{6331}{}{Ai, meu braço}
{6332}{}{Você quebrou meu braço!}
{6333}{}{}
{6334}{}{Ai, meu braço}
{6335}{}{Você quebrou meu braço!}
{6336}{}{}
{6337}{}{Ouch! Isso doi}
{6338}{}{Oof!}
{6339}{}{Ouch!}
{6340}{}{}
{6341}{}{Ugh! Isso doi!}
{6342}{}{}
{6343}{}{Oof!}
{6344}{}{Eu vou chutar você nas costelas por isso}
{6345}{}{Ah!}
{6346}{}{Oof!}
{6347}{}{Ai, minha perna}
{6348}{}{Você vai pagar por isso!}
{6349}{}{Ah, meu joelho!}
{6350}{}{Ai, minha perna}
{6351}{}{}
{6352}{}{Ah, meu joelho}
{6353}{}{Argh!}
{6354}{}{Meus olhos.... Não meus olhos...}
{6355}{}{Esse foi um tiro verdadeiramente barato!}
{6356}{}{Uuuuuu, minha virilha!}
{6357}{}{}
{6358}{}{}
{6359}{}{}
{6360}{}{Urp!}
{6361}{}{Ai! Eu vou matar você por isso!}
{6400}{}{Tenho que sair daqui!}
{6401}{}{Eu voltarei...}
{6402}{}{Socorro!}
{6403}{}{Fujam!}
{6404}{}{Você ainda não ouviu sobre mim pela ultima vez!}
{6405}{}{}
{6406}{}{}
{6407}{}{Carne fresca...}
{6408}{}{Bem-vindo a Junktown. Lugar bacana para o seu tumulo!}
{6409}{}{Skulz! Ataquem!}
{6410}{}{É hora de matar!}
{6411}{}{}
{6412}{}{Vamos pôr seu crânio na nossa coleção}
{6413}{}{Sinta-se livre para gritar}
{6414}{}{Vou apreciar isto.}
{6415}{}{}
{6416}{}{Vou alimentar os cachorros com você}
{6417}{}{Ninguem vai tirar Junktown de nos}
{6418}{}{Espero que você não morra muito rapido}
{6419}{}{}
{6420}{}{Morra!}
{6421}{}{}
{6422}{}{}
{6423}{}{Eu sou muito bom/boa para morrer!}
{6424}{}{}
{6425}{}{Tente mirar, scag!}
{6426}{}{}
{6427}{}{Hah!}
{6428}{}{Não na cara!}
{6429}{}{Cara, isto e pior do que uma ressaca}
{6430}{}{Você quebrou meu nariz!}
{6431}{}{Ai, meu braço}
{6432}{}{Você quebrou meu braço!}
{6433}{}{Meu braço! Meu braço!}
{6434}{}{Ai, meu braço}
{6435}{}{Você quebrou meu braço!}
{6436}{}{Meu braço! Meu braço!}
{6437}{}{Cara! Isso realmente doi!}
{6438}{}{Oof! Você vai se arrepender disso}
{6439}{}{Gasp}
{6440}{}{Gasp! Preciso... de... ar...}
{6441}{}{Eu vou cuspir no seu cadaver, you skag!}
{6442}{}{Maldicao!}
{6443}{}{Oof!}
{6444}{}{Esse foi um tiro barato!}
{6445}{}{Oof!}
{6446}{}{Ouch!}
{6447}{}{Ai, minha perna}
{6448}{}{Ninguem vai me tornar em um gimp!}
{6449}{}{Ah, meu joelho!}
{6450}{}{Ai, minha perna}
{6451}{}{Ninguem vai me tornar em um gimp!}
{6452}{}{Ah, meu joelho}
{6453}{}{Argh! Meus olhos!}
{6454}{}{Meus olhos.... Não meus olhos...}
{6455}{}{}
{6456}{}{Uuuuuu, minha virilha!}
{6457}{}{}
{6458}{}{}
{6459}{}{}
{6460}{}{Urp!}
{6461}{}{Ai! Eu vou matar você por isso!}
{6500}{}{Tenho que sair daqui!}
{6501}{}{Eu voltarei...}
{6502}{}{Socorro!}
{6503}{}{Fujam!}
{6504}{}{Você ainda não ouviu sobre mim pela ultima vez!}
{6505}{}{Você vai ter o troco, eu prometo!}
{6506}{}{Esta acabado, miseravel! Você ser historia!}
{6507}{}{Você nunca deveria ter se oposto a mim, miseravel}
{6508}{}{Você esta precisando de uma nova atitude, miseravel.}
{6509}{}{Ninguem se opoe a Gizmo mais do que uma vez}
{6510}{}{Você vai estar morto e enterrado}
{6511}{}{Você estar me deixando realmente infeliz}
{6512}{}{Eu vou adicionar suas rotulas a minha colecao}
{6513}{}{Isto e o que faco com miseraveis e perdedores}
{6514}{}{Eu vou apreciar isto.}
{6515}{}{Uuuu, isso deve doer!}
{6516}{}{Você mexeu com o homem errado}
{6517}{}{Ninguem vai tirar Junktown de mim}
{6518}{}{Espero que você não morra muito rapido}
{6519}{}{Eu vou rasgar você membro por membro!}
{6520}{}{Você estar morto!}
{6521}{}{Experimente isto pelo tamanho!}
{6522}{}{Isso e patetico de verdade}
{6523}{}{Você precisa de melhores chems de combate}
{6524}{}{Você e até mesmo um perdedor maior do que o Killian}
{6525}{}{}
{6526}{}{Esse foi seu ultimo tiro!}
{6527}{}{}
{6528}{}{}
{6529}{}{Como ousa você fazer isto comigo!}
{6530}{}{Você quebrou meu nariz!}
{6531}{}{Seu/sua beijador de radscorpions...}
{6532}{}{Você quebrou meu braço!}
{6533}{}{Meu braço! Meu braço!}
{6534}{}{Seu/sua beijador de radscorpions...}
{6535}{}{Você quebrou meu braço!}
{6536}{}{Meu braço! Meu braço!}
{6537}{}{}
{6538}{}{}
{6539}{}{Oof!}
{6540}{}{Oof! Minhas costelas...}
{6541}{}{!}
{6542}{}{Ai!}
{6543}{}{Argh!}
{6544}{}{Ninguem faz isso comigo, ninguém!}
{6545}{}{Ai!!!}
{6546}{}{Oof!}
{6547}{}{Ai, minha perna}
{6548}{}{Eu mal... posso... ficar de pe...}
{6549}{}{Ah, meu joelho!}
{6550}{}{Ai, minha perna}
{6551}{}{Eu mal... posso... ficar de pe...}
{6552}{}{Ah, meu joelho}
{6553}{}{Uggh! Naooo!}
{6554}{}{Meus olhos.... Não meus olhos...}
{6555}{}{}
{6556}{}{Uuuuuu, minha virilha!}
{6557}{}{Uuu! Nada mal, miseravel}
{6558}{}{Uuu! Você estar escavando seu tumulo, miseravel}
{6559}{}{Uuu! Você estar mais morto do que um albino no Glow}
{6560}{}{Urp!}
{6561}{}{Ai! Eu vou matar você por isso!}
{6600}{}{Eu estou fora daqui!}
{6601}{}{Tenha misericordia!}
{6602}{}{Por favor pare!}
{6603}{}{Socorro!}
{6604}{}{Aaaaahhhh!}
{6605}{}{}
{6606}{}{Ei!}
{6607}{}{}
{6608}{}{Quem você pensa que você e?}
{6609}{}{Ninguem vai tomar este lugar...}
{6610}{}{Você esta me forcando a ser inamistosa de verdade.}
{6611}{}{Seu/Sua filho da...}
{6612}{}{}
{6613}{}{Você pediu por isto!}
{6614}{}{}
{6615}{}{}
{6616}{}{Por que você comecou isto?}
{6617}{}{Morra, seu/sua filho da...}
{6618}{}{Não tome isto como pessoal...}
{6619}{}{Você merece cada pedaço disto!}
{6620}{}{Você percebe que você comecou isto?}
{6621}{}{}
{6622}{}{Whew!}
{6623}{}{Você realmente não tem que fazer isto}
{6624}{}{Você é uma desculpa lamentavel para um lutador}
{6625}{}{Você me lembra de alguém que eu costumava namorar}
{6626}{}{Você não consegue lidar comigo}
{6627}{}{}
{6628}{}{Minha cara!}
{6629}{}{Ah, minha cabeca doi}
{6630}{}{Você esta baguncando minha frente!}
{6631}{}{Ai, meu braço}
{6632}{}{Você esta tentando me aleijar!}
{6633}{}{Meu braço!}
{6634}{}{Ai, meu braço}
{6635}{}{Você esta tentando me aleijar!}
{6636}{}{Você quebrou meu braço!}
{6637}{}{Ai!}
{6638}{}{!}
{6639}{}{Ai! Isso doi!}
{6640}{}{}
{6641}{}{Não acerte uma dama ai!}
{6642}{}{Ai!!}
{6643}{}{Ouch!}
{6644}{}{Ai! Seu/Sua pequeno pedaço de ...}
{6645}{}{&*$#@!}
{6646}{}{#$#@! Seu/Sua vermezinho!}
{6647}{}{Minha perna!!!}
{6648}{}{Meu joelho!}
{6649}{}{Ai! Minha perna esta destruida!}
{6650}{}{Ai, minha perna}
{6651}{}{Meu joelho!}
{6652}{}{}
{6653}{}{Minha cara! Minha cara!}
{6654}{}{Meus... olhos... MEUS OLHOS!}
{6655}{}{Seu/Sua bastardo! Eu matarei você!}
{6656}{}{Você deve estar acostumado a enfrentar homens}
{6657}{}{}
{6658}{}{Seu pedaço de lixo do deserto!}
{6659}{}{Esse e meu espaco pessoal!}
{6660}{}{Sua gosma!}
{6661}{}{Seu/Sua animal!}
{6700}{}{Eu preciso de reforcos!}
{6701}{}{Alguém me ajude!}
{6702}{}{}
{6703}{}{Recuar!}
{6704}{}{Recuar!}
{6705}{}{Da proxima vez!}
{6706}{}{Eu estou indo!}
{6707}{}{}
{6708}{}{}
{6709}{}{Você não deveria ter comecado isto}
{6710}{}{Eu espero que os Paladinos estejam observando}
{6711}{}{}
{6712}{}{}
{6713}{}{}
{6714}{}{Agora você morre!}
{6715}{}{Você gosta disto?}
{6716}{}{Mexa com o melhor, morra como o resto}
{6717}{}{Não deveria começar o que você não pode terminar}
{6718}{}{}
{6719}{}{Vamos ver o quanto você gosta disto!}
{6720}{}{}
{6721}{}{Vejo você no Inferno}
{6722}{}{Enfrente os fatos. Você e outclassed.}
{6723}{}{Isso e o melhor que você pode fazer?}
{6724}{}{Perdedor! Me de uma luta!}
{6725}{}{}
{6726}{}{Nós somos os Mestres do Combate!}
{6727}{}{Você não pode tocar a Brotherhood}
{6728}{}{Eu pegarei você por isso}
{6729}{}{Ai!}
{6730}{}{Você quebrou meu nariz!}
{6731}{}{Você quebrou meu braço!}
{6732}{}{Um braço destruido não vai me parar!}
{6733}{}{}
{6734}{}{Você quebrou meu braço!}
{6735}{}{Um braço destruido não vai me parar!}
{6736}{}{}
{6737}{}{Você destruiu uma costela!}
{6738}{}{Oof!}
{6739}{}{Ouch!}
{6740}{}{Oof! Então e assim como se sente com dor...}
{6741}{}{Ai! Meu treinamento não me preparou pra isto!}
{6742}{}{Oof! A Brotherhood me vingara se eu morrer!}
{6743}{}{Ouch!}
{6744}{}{}
{6745}{}{Ah! Minhas costelas doloridas! Eu pegarei você por isso}
{6746}{}{Oof!}
{6747}{}{Ai, minha perna}
{6748}{}{Você vai pagar big time por isso!}
{6749}{}{Você não vai me incapacitar. Ai...}
{6750}{}{Ai, minha perna}
{6751}{}{Você vai pagar big time por isso!}
{6752}{}{Você não vai me incapacitar.}
{6753}{}{Eu estou cego!}
{6754}{}{Meus olhos estão queimando!}
{6755}{}{Eu não consigo ver!}
{6756}{}{Uuuuuu, minha virilha!}
{6757}{}{}
{6758}{}{A dor...}
{6759}{}{Eu...não...consigo...respirar...}
{6760}{}{Eu pegarei você por isso!}
{6761}{}{Seu/Sua miseravel...}
{6800}{}{Eu preciso de reforcos!}
{6801}{}{Eu estou fora desta luta}
{6802}{}{Retirar}
{6803}{}{Recuar!}
{6804}{}{Recuar!}
{6805}{}{Eu não posso ficar mais nisto}
{6806}{}{}
{6807}{}{}
{6808}{}{Espere um segundo...}
{6809}{}{Você não deveria ter comecado isto}
{6810}{}{}
{6811}{}{Eu vou entrar!}
{6812}{}{Tome isto!}
{6813}{}{Agora eu tenho você!}
{6814}{}{Agora você morre!}
{6815}{}{Você gosta disto?}
{6816}{}{Eu sei como lidar com os tipos de vocês}
{6817}{}{Isto deve tirar a luta de você}
{6818}{}{}
{6819}{}{Deixe-nos ver o quanto você gosta disto!}
{6820}{}{}
{6821}{}{}
{6822}{}{O fato é. Você e outclassed}
{6823}{}{Isto e o seu melhor?}
{6824}{}{Seu/Sua estúpido pequeno tolo}
{6825}{}{Isso foi patetico}
{6826}{}{Você me insulta com sua incompetencia}
{6827}{}{Você não consegue tocar a Brotherhood}
{6828}{}{Ah!}
{6829}{}{Ai!}
{6830}{}{Uuu, meu nariz!}
{6831}{}{Isso soa como uma fratura exposta}
{6832}{}{Uuu, meu braço}
{6833}{}{Meu braço acabou de ficar dormente}
{6834}{}{Isso soa como uma fratura exposta}
{6835}{}{Uuu, meu braço}
{6836}{}{Meu braço acabou de ficar dormente}
{6837}{}{}
{6838}{}{Oof!}
{6839}{}{}
{6840}{}{Oof! Dor...minha velha amiga}
{6841}{}{}
{6842}{}{Oof! A Brotherhood vingara minha morte!}
{6843}{}{Ouch!}
{6844}{}{}
{6845}{}{Ah! Minhas costelas doloridas! Eu pegarei você por isso}
{6846}{}{Oof!}
{6847}{}{Ai, minha perna}
{6848}{}{Uuu, meu joelho!}
{6849}{}{Ai}
{6850}{}{Ai, minha perna}
{6851}{}{Uuu, meu joelho}
{6852}{}{Ai...}
{6853}{}{Eu estou cego!}
{6854}{}{Eu fui cegado! Eu preciso de ajuda aqui!}
{6855}{}{Meus olhos!}
{6856}{}{Uuuuuu, minha virilha!}
{6857}{}{Uuuuuu, tirou o vento fora de mim}
{6858}{}{Uuuuuu, isso doi...}
{6859}{}{Eu...não...consigo...respirar...}
{6860}{}{Eu estou ferido aqui! Eu preciso de ajuda!}
{6861}{}{Isso doi...}
{6900}{}{Eu preciso de reforcos!}
{6901}{}{Eu estou fora desta luta}
{6902}{}{Retirar}
{6903}{}{Recuar!}
{6904}{}{Recuar!}
{6905}{}{Eu não posso ficar mais nisto}
{6906}{}{Eu estou indo!}
{6907}{}{Este e meu!}
{6908}{}{}
{6909}{}{Mais uma vez na discordia}
{6910}{}{}
{6911}{}{Eu estou dentro!}
{6912}{}{Hora de acabar com isto}
{6913}{}{Agora eu tenho você!}
{6914}{}{Agora você morre!}
{6915}{}{Esta acabado!}
{6916}{}{Cai no chão!}
{6917}{}{Isto deve tirar a luta fora de você}
{6918}{}{}
{6919}{}{Vamos ver do que você e feito}
{6920}{}{Eu estou apenas aquecendo}
{6921}{}{Aqui vem o trovao}
{6922}{}{Suas técnicas são fracas}
{6923}{}{Isso e o melhor que você pode fazer?}
{6924}{}{Seu/Sua pequeno estúpido tolo}
{6925}{}{Isso foi patetico}
{6926}{}{Você me insulta com sua incompetencia}
{6927}{}{Você não é lutador}
{6928}{}{Ah!}
{6929}{}{Ai!}
{6930}{}{Uuu}
{6931}{}{Isso soa como uma fratura exposta}
{6932}{}{Ai!}
{6933}{}{Meu braço acabou de ficar dormente}
{6934}{}{Isso soa como uma fratura exposta}
{6935}{}{Ai!}
{6936}{}{Meu braço acabou de ficar dormente}
{6937}{}{Ai! Eu estou preparado para o seu tipo!}
{6938}{}{Oof!}
{6939}{}{Ouch!}
{6940}{}{Oof! Eu tive piores}
{6941}{}{Ai! Faca o seu pior, Eu estou pronto!}
{6942}{}{A Brotherhood me vingara se eu morrer!}
{6943}{}{Ouch!}
{6944}{}{Argh!}
{6945}{}{}
{6946}{}{Oof!}
{6947}{}{Ai, minha perna}
{6948}{}{}
{6949}{}{Ai}
{6950}{}{Ai, minha perna}
{6951}{}{}
{6952}{}{Ai...}
{6953}{}{Aggghh!}
{6954}{}{Eu fui cegado! Eu preciso de ajuda aqui!}
{6955}{}{Meus olhos!}
{6956}{}{Uuuuuu, minha virilha!}
{6957}{}{Uuuuuu, tirou o vento fora de mim}
{6958}{}{Uuuuuu, isso doi...}
{6959}{}{Eu...não...consigo...respirar...}
{6960}{}{Vamos manter isto justo}
{6961}{}{Isso doi...}
{7000}{}{Dunquerque! Dunquerque! Vou recuar!}
{7001}{}{Eu estou fora desta luta}
{7002}{}{Retirar}
{7003}{}{Eu viverei para lutar outro dia}
{7004}{}{Eu não posso fazer qualquer bem aqui}
{7005}{}{}
{7006}{}{Eu estou indo!}
{7007}{}{Este e meu!}
{7008}{}{Isto deve ser rapido}
{7009}{}{Mais uma vez na discordia}
{7010}{}{Deixe-nos neutralizar este criador de problemas}
{7011}{}{Eu estou dentro!}
{7012}{}{Aprecie estes ultimos poucos segundos}
{7013}{}{Vou te mandar pra vala!}
{7014}{}{Assim e que é feito}
{7015}{}{Esta acabado!}
{7016}{}{Fogo inimigo!}
{7017}{}{Eu aprecio o exercicio, mas é hora de terminar isto}
{7018}{}{}
{7019}{}{Vamos ver do que você e feito}
{7020}{}{Chega de brincar}
{7021}{}{Eu quase me sinto pesaroso por você}
{7022}{}{Você é um tolo fraco!}
{7023}{}{Isso foi o seu melhor?}
{7024}{}{Você esta levando esta luta a serio?}
{7025}{}{Mantenha seus olhos no alvo, seu/sua idiota!}
{7026}{}{Esse será seu ultimo erro}
{7027}{}{Você deveria ter ficado em casa}
{7028}{}{Hmm, isso doi!}
{7029}{}{Uh!}
{7030}{}{Uuu}
{7031}{}{Isso soa como uma fratura exposta}
{7032}{}{Hmm, me pegou no antebraco}
{7033}{}{Meu braço acabou de ficar dormente}
{7034}{}{Isso soa como uma fratura exposta}
{7035}{}{Hmm, me pegou no antebraco}
{7036}{}{Meu braço acabou de ficar dormente}
{7037}{}{Ai! Seu/Sua Cao/Cadela!}
{7038}{}{Oof!}
{7039}{}{Ouch!}
{7040}{}{Oof! Eu tive piores feitas em mim pela minha mae}
{7041}{}{Ai! Seu/sua malcriado!}
{7042}{}{Oof! A Brotherhood me vingara se eu morrer!}
{7043}{}{I will master my dor as I will master you!}
{7044}{}{Sim...Dor, minha velha amiga}
{7045}{}{}
{7046}{}{É só uma ferida na carne!}
{7047}{}{Hmm, uma ferida na perna}
{7048}{}{Minha perna esta comecando a curvar!}
{7049}{}{Ai}
{7050}{}{Hmm, uma ferida na perna}
{7051}{}{Minha perna esta comecando a curvar}
{7052}{}{Ai...}
{7053}{}{Aggghh!}
{7054}{}{Minha visao se foi!}
{7055}{}{Meus olhos!}
{7056}{}{Uuuuuu, minha virilha!}
{7057}{}{Eu estou realmente comecando a não gostar deste miseravel}
{7058}{}{Eu já me senti melhor}
{7059}{}{Então, este miseravel gosta de descer escadas}
{7060}{}{Time to take this miseravel apart}
{7061}{}{Não outro artista de tiro barato}
{7100}{}{Me cubram!}
{7101}{}{Do not mistake this por covardia, patife.}
{7102}{}{Esta não é a minha hora!}
{7103}{}{Eu darei a você esta luta, patife.}
{7104}{}{Não pense que isto esta acabado.}
{7105}{}{}
{7106}{}{Eu estou indo.}
{7107}{}{Eu devo fazer tudo eu mesmo?}
{7108}{}{Isto deve ser rapido}
{7109}{}{Talvez isto será um desafio}
{7110}{}{Alguém acabou de cometer um grande erro}
{7111}{}{Alguém quer nos aborrecer? Quem é este imbecil?}
{7112}{}{Tudo muito fácil}
{7113}{}{Pronto, mirar, fogo...}
{7114}{}{Assim e que é feito}
{7115}{}{Esta acabado!}
{7116}{}{Incoming!}
{7117}{}{Eu aprecio o exercicio, mas é hora de terminar isto}
{7118}{}{Hora de acabar com suas ilusoes}
{7119}{}{Esta é uma dura licao para alguém tão jovem}
{7120}{}{Chega de brincar}
{7121}{}{Um presente dos Elders, criança.}
{7122}{}{Eu podia ver isso vindo}
{7123}{}{Me levou vinte anos para aprender como esquivar assim}
{7124}{}{Você tem talento, mas seu treinamento e patetico}
{7125}{}{Não há substituto para a experiência}
{7126}{}{Agora... é minha vez}
{7127}{}{Você deveria ter ficado em casa}
{7128}{}{Hmm, isso doi!}
{7129}{}{Uh!}
{7130}{}{Uuu, não foi um acerto ruim}
{7131}{}{}
{7132}{}{Hmm, me pegou no antebraco}
{7133}{}{Meu braço acabou de ficar dormente. Não foi a primeira vez}
{7134}{}{}
{7135}{}{Hmm, me pegou no antebraco}
{7136}{}{Meu braço acabou de ficar dormente. Não foi a primeira vez}
{7137}{}{Eu não sentirei dor!}
{7138}{}{Eu vivo!}
{7139}{}{Eu vivo! Eu sinto dor mas eu vivo!}
{7140}{}{Ai! Você cometeu um erro grave de tatica}
{7141}{}{Oof! A Brotherhood prevalecera!}
{7142}{}{Oof! A Brotherhood me vingara se eu morrer!}
{7143}{}{Oof!}
{7144}{}{Gasp!}
{7145}{}{Isso doi!}
{7146}{}{Você sentira a ira da Brotherhood por isso!}
{7147}{}{Hmm, uma ferida na perna}
{7148}{}{Minha perna esta comecando a curvar!}
{7149}{}{Isso não foi agradavel}
{7150}{}{Hmm, uma ferida na perna}
{7151}{}{Minha perna esta comecando a curvar}
{7152}{}{Isso não foi agradavel}
{7153}{}{Devo ficar calmo. Eu sei onde mirar}
{7154}{}{Atingido nos olhos. Isto não é bom.}
{7155}{}{Meus olhos!}
{7156}{}{Uuuuuu, minha virilha!}
{7157}{}{}
{7158}{}{Este garoto esta tentando me irritar}
{7159}{}{}
{7160}{}{Hora de despedaçar esse idiota}
{7161}{}{Não outro artista de tiro barato}
{7200}{}{Vou recuar!}
{7201}{}{Eu estou fora desta luta}
{7202}{}{Retirar!}
{7203}{}{Eu lutarei outro dia}
{7204}{}{Eu não posso fazer qualquer bem aqui}
{7205}{}{}
{7206}{}{Eu estou indo!}
{7207}{}{Este e meu!}
{7208}{}{Eu vou tomar conta deste patife.}
{7209}{}{Deixe-me apresentar você a dor}
{7210}{}{Pequeno bastardo insolente}
{7211}{}{Eu estou dentro!}
{7212}{}{Aprecie estes ultimos poucos segundos}
{7213}{}{Eu estou cansado de você}
{7214}{}{Assim e que é feito}
{7215}{}{Esta acabado!}
{7216}{}{Assim e que um profissional o faz}
{7217}{}{Você esta realmente comecando a me perturbar}
{7218}{}{}
{7219}{}{Você esta pedindo pra ser slagged, garoto}
{7220}{}{Chega de brincar}
{7221}{}{Eu quase me sinto pesaroso por você}
{7222}{}{Suas técnicas não são nada}
{7223}{}{Pare de desperdicar meu tempo garoto}
{7224}{}{Você esta levando esta luta a serio?}
{7225}{}{Você não esteve fazendo isto por muito tempo, esteve?}
{7226}{}{Tolo Fraco}
{7227}{}{Você deveria ter ficado em casa}
{7228}{}{Hmm, isso doi!}
{7229}{}{Uh!}
{7230}{}{Uuu}
{7231}{}{}
{7232}{}{Hmm, me pegou no antebraco}
{7233}{}{Meu braço acabou de ficar dormente}
{7234}{}{}
{7235}{}{Hmm, me pegou no antebraco}
{7236}{}{Meu braço acabou de ficar dormente}
{7237}{}{Eu não sentirei dor!}
{7238}{}{Oof! Cao/Cadela Insolente!}
{7239}{}{Oof! Patife insolente! Sinta minha ira!}
{7240}{}{Ai! Você cometeu um erro grave de tatica}
{7241}{}{Ouch!}
{7242}{}{Oof! A Brotherhood vingara minha morte}
{7243}{}{Oof!}
{7244}{}{A dor me deixa saber que eu estou vivo}
{7245}{}{Isso doi!}
{7246}{}{}
{7247}{}{Uma ferida na perna não me impedira de matar você}
{7248}{}{Minha perna esta comecando a curvar!}
{7249}{}{Ai}
{7250}{}{Uma ferida na perna não me impedira de matar você}
{7251}{}{Minha perna esta comecando a curvar}
{7252}{}{Ai...}
{7253}{}{Aggghh!}
{7254}{}{Seu/Sua bastardo!}
{7255}{}{Meus olhos!}
{7256}{}{Garato, pessoas que fazem jogos comigo acabam mortos!}
{7257}{}{}
{7258}{}{Eu já me senti melhor}
{7259}{}{}
{7260}{}{Hora de despedaçar esse idiota}
{7261}{}{Eu esperaria isso de alguém como você}
{7300}{}{Isto foi comico, mas eu devo ir.}
{7301}{}{Esta batalha e sem significado. Tchau, tolo!}
{7302}{}{Eu não desperdicarei mais tempo com você}
{7303}{}{Eu tenho coisas melhores pra fazer do que sujar minhas mãos com você!}
{7304}{}{Eu deixarei os Nightkin lidarem com você}
{7305}{}{Tchau, tolo. Você não sobrevivera para me encontrar de novo}
{7306}{}{Foi há muito tempo desde quando eu apreciei sangue quente nos meus dedos!}
{7307}{}{Eu verei você morto pelo que você fez!}
{7308}{}{Quando eu tiver terminado, você será comida para os ratos toupeira!}
{7309}{}{Não outra interrupcao!}
{7310}{}{Sua insolencia não será tolerada!}
{7311}{}{Você passou alem do reino do perdao}
{7312}{}{Tome isto!}
{7313}{}{Eu unjo você com a chama sagrada!}
{7314}{}{Assim e como eu lido com animais}
{7315}{}{Seu pequeno selvagem inominavel!}
{7316}{}{Eu ouvirei você gritar!}
{7317}{}{Este e só o comeco da sua agonia!}
{7318}{}{Eu sou Morpheus, e eu empunho um cajado preto!}
{7319}{}{Você queimara!}
{7320}{}{Eu sou Morpheus, mestre da Morte!}
{7321}{}{Eu lanco você fora e encerro sua vida}
{7322}{}{Eu estou singularmente não impressionado}
{7323}{}{Eu não passei dez anos nos Rippers por nada!}
{7324}{}{Patetico}
{7325}{}{Eu tive lutas melhores com putas}
{7326}{}{Você sempre foi incompetente ou este e um desenvolvimento recente?}
{7327}{}{Blasfemador, falha, tolo. Em breve nos adicionaremos cadaver a sua lista de realizações}
{7328}{}{Agggh!}
{7329}{}{Meus olhos!}
{7330}{}{Tiro sortudo!}
{7331}{}{Ai!}
{7332}{}{Ai! Meu braço!}
{7333}{}{Ai! Amaldico-o sua sorte!}
{7334}{}{Ai!}
{7335}{}{Ai! Meu braço!}
{7336}{}{Ai! Amaldico-o sua sorte!}
{7337}{}{Maldita seja sua sorte!}
{7338}{}{Ai! Eu não me renderei!}
{7339}{}{Você é uma verdadeira dor no traseiro!}
{7340}{}{Você esta amaldicoando a si próprio aos olhos do Mestre}
{7341}{}{Ai!}
{7342}{}{Ouch!}
{7343}{}{Oof!}
{7344}{}{Gasp!}
{7345}{}{Ah, isso doi!}
{7346}{}{My minions causarao a você seria dor por isso!}
{7347}{}{Ai!}
{7348}{}{Ai! Minha perna!}
{7349}{}{Ai! Minha perna!}
{7350}{}{Ai!}
{7351}{}{Ai! Minha perna!}
{7352}{}{Ai! Minha perna!}
{7353}{}{Meus olhos! Seu/Sua suino sujo!}
{7354}{}{Eu verei você rasgado membro por membro!}
{7355}{}{Agghh! Pequeno sujo filho da...}
{7356}{}{Uuuuuu, minha virilha!}
{7357}{}{Aieee!}
{7358}{}{Eu verei você sofrer!}
{7359}{}{Ooof!}
{7360}{}{Sua morte será especialmente dolorosa agora!}
{7361}{}{Como ousa você atacar os loins de Morpheus!}
{7400}{}{Crianca, você foi punida o bastante. Pra fora com você}
{7401}{}{Você não deveria resistir a mim criança. Nós trabalharemos nisso.}
{7402}{}{Eu não desperdicarei mais tempo com você}
{7403}{}{Eu tenho coisas melhores pra fazer do que sujar minhas mãos com você!}
{7404}{}{Eu deixarei os Nightkin lidarem com você}
{7405}{}{Eu punirei você de novo mais tarde}
{7406}{}{Você ganhou punicao}
{7407}{}{Você deve receber disciplina}
{7408}{}{Hold still. Isto vai doer.}
{7409}{}{Você deve aprender maneiras, criança.}
{7410}{}{Juventude hoje. Sem disciplina. Sem maneiras. Eu instruirei você.}
{7411}{}{Você ganhou grande dor, criança.}
{7412}{}{Sinta meu acoite e seja limpo!}
{7413}{}{Eu unjo você com a chama sagrada!}
{7414}{}{Você é uma criatura perversa! Admita!}
{7415}{}{Você merece punicao! Admita!}
{7416}{}{Grite, criança! Na dor há redencao!}
{7417}{}{Eu não tomo alegria na dor, criança.}
{7418}{}{Confesse seu pecado! Confesse seu pecado!}
{7419}{}{Você e vil e profano. Admita!}
{7420}{}{Sua resistência só adiciona aos seus pecados. Sumeta-se!}
{7421}{}{Submeta-se a autoridade divina e você será curado!}
{7422}{}{Suas ações só refletem uma mente doente e pervertida}
{7423}{}{Sua resistência me enoja, mas eu devo resistir}
{7424}{}{Eu temo que você esta alem da minha habilidade de redimir.}
{7425}{}{Não há fim para o seu perfidio, criança?}
{7426}{}{Embora você me ataque, eu ainda amo você}
{7427}{}{Blasfemador, falha, tolo. Arrependa-se!}
{7428}{}{Eu suporto seus golpes com paciencia, criança.}
{7429}{}{Você não me fara mal, pois minha causa e sagrada}
{7430}{}{Eu resistirei}
{7431}{}{O Mestre e meu escudo. Eu não sinto dor.}
{7432}{}{Eu sou protegido pelos Holies, criança.}
{7433}{}{A Chama Sagrada me socorre. Seus golpes não são nada.}
{7434}{}{O Mestre e meu escudo. Eu não sinto dor.}
{7435}{}{Eu sou protegido pelos Holies, criança.}
{7436}{}{A Chama Sagrada me socorre. Seus golpes não são nada.}
{7437}{}{Apos a dor, há perdao, criança.}
{7438}{}{Eu entendo a dor.  Você entende?}
{7439}{}{Eu posso sentir seus golpes, mas a dor não me importa}
{7440}{}{Faca isso de novo, eu gosto do seu toque}
{7441}{}{O Mestre me da a vontade para sobreviver}
{7442}{}{Gasp! Você não é nada alem de um criança}
{7443}{}{Meu corpo não é nada alem de um casco}
{7444}{}{Você não pode parar a Unidade}
{7445}{}{Eu sinto sua dor, criança}
{7446}{}{Não tente isso de novo!}
{7447}{}{Apos a dor, há perdao, criança.}
{7448}{}{O Mestre e minhas pernas e bracos, criança.}
{7449}{}{Cada fraqueza do corpo torna minhas almas mais fortes, criança.}
{7450}{}{Apos a dor, há perdao, criança.}
{7451}{}{O Mestre e minhas pernas e bracos, criança.}
{7452}{}{Cada fraqueza do corpo faz minhas almas mais fortes, criança.}
{7453}{}{Apos a dor, há perdao, criança.}
{7454}{}{Nenhum sacrifico e muito grande para o Mestre, criança.}
{7455}{}{Cada fraqueza do corpo torna minhas almas mais fortes, criança.}
{7456}{}{Embora minha carne e fraca, meu espirito e forte!}
{7457}{}{A dor e um artefato de uma mente fraca. Eu resistirei}
{7458}{}{Meu sofrimento me fortalece}
{7459}{}{Ooof!}
{7460}{}{Até mesmo na batalha, você revela uma natureza decadente}
{7461}{}{Seus pecados serao multiplicados em você tenfold, criança!}
{7500}{}{Seus atos maus receberao punicao em tempo devido!}
{7501}{}{As marcas das Crianças esta em você agora!}
{7502}{}{Eu verei você de novo!}
{7503}{}{Eu verei seu cadaver!}
{7504}{}{Nós nos encontraremos outra hora}
{7505}{}{Isto não acabou!}
{7506}{}{Blasfemadores devem ser punidos!}
{7507}{}{Morte em nome da Chama Sagrada!}
{7508}{}{Como ousa você interromper nosso grande trabalho!}
{7509}{}{Você deve aprender maneiras, criança}
{7510}{}{Crianças, destruam o intruso!}
{7511}{}{Você ganhou grande dor, criança}
{7512}{}{Esta e sua punicao!}
{7513}{}{Blasfemador!}
{7514}{}{Sofram as Crianças!}
{7515}{}{Em nome da Chama Sagrada, Morra!}
{7516}{}{É agora vem a noite}
{7517}{}{Conheca o pedaço do tumulo, criança!}
{7518}{}{Agora desce o golpe da morte!}
{7519}{}{Você desecra a Chama Sagrada!}
{7520}{}{Sofra, tolo!}
{7521}{}{So no fim você entende!}
{7522}{}{Suas ações só refletem uma mente doente e pervertida}
{7523}{}{Você não pode me fazer mal, criança.}
{7524}{}{Eu temo que você esta alem da minha habilidade de redimir}
{7525}{}{Não há fim para sua perfidia, criança?}
{7526}{}{A Chama Sagrada me protege!}
{7527}{}{Minha força esta alem da sua compreensao}
{7528}{}{Sua pequena fera maligna!}
{7529}{}{Você morrera por isto!}
{7530}{}{Ai!}
{7531}{}{O Mestre e meu escudo. Eu não sinto dor}
{7532}{}{A morte achara você em breve!}
{7533}{}{Ai!}
{7534}{}{O Mestre e meu escudo. Eu não sinto dor}
{7535}{}{A morte achara você em breve!}
{7536}{}{Ai!}
{7537}{}{Pecador!}
{7538}{}{Ai!}
{7539}{}{Você esta derramando o sangue de uma mulher santa!}
{7540}{}{Oof! Você não pode ter sucesso}
{7541}{}{Ai! Eu punirei você por seus pecados}
{7542}{}{Ai! Você desgraca a si próprio}
{7543}{}{Ah!}
{7544}{}{Meu Mestre me protege de suas fracas tentativas}
{7545}{}{Ai!}
{7546}{}{Oof!}
{7547}{}{O Mestre e meu escudo. Eu não sinto dor}
{7548}{}{Meu sangue e um sacrificio para a piedade}
{7549}{}{Ai!}
{7550}{}{Apos a dor, há perdao, criança}
{7551}{}{Meu sangue e um sacrificio para a piedade}
{7552}{}{Ai!}
{7553}{}{Meus olhos!}
{7554}{}{Aggh! Seu demonio!}
{7555}{}{Meus olhos estão em chamas!}
{7556}{}{Você é uma abominacao!}
{7557}{}{Você toma prazer em vitorias baratas!}
{7558}{}{Meu sofrimento me fortalece}
{7559}{}{Ooof!}
{7560}{}{Até mesmo na batalha, você revela uma natureza decadente}
{7561}{}{Seus pecados serao multiplicados em você tenfold, criança!}
{7600}{}{Isto não vale meu tempo}
{7601}{}{Eu não tenho tempo para morrer!}
{7602}{}{Você vai pagar pelo que você fez!}
{7603}{}{}
{7604}{}{Você não me viu pela ultima vez!}
{7605}{}{Eu estou vivendo para lutar outro dia!}
{7606}{}{Você e historia!}
{7607}{}{Você mexeu com as pessoas erradas!}
{7608}{}{Eu vou dancar no seu tumulo}
{7609}{}{Você comprou pra si próprio um lar a sete palmos abaixo!}
{7610}{}{Quando eu acabar com você, os ratos limparao você!}
{7611}{}{Sua vida não significa nada pra mim}
{7612}{}{Hora de alimentar as minhocas!}
{7613}{}{Você esta pra ficar bem feio}
{7614}{}{}
{7615}{}{Seu numero aumentou!}
{7616}{}{Dois segundos mais e você encontrara seu criador}
{7617}{}{Eu vou derrubar você como um vicio ruim!}
{7618}{}{}
{7619}{}{Eu vou obter um bonus por isso}
{7620}{}{Morra!}
{7621}{}{Eu vou chutar seu traseiro até o tumulo}
{7622}{}{Isso foi um tiro de aviso ou você e apenas suck?}
{7623}{}{Deixe-me advinhar, você estava pretendendo errar?}
{7624}{}{}
{7625}{}{Então e assim que você erra o alvo! Obrigado por me mostrar.}
{7626}{}{Eu já fui machucado mais por um bom cuss!}
{7627}{}{Perdedor}
{7628}{}{}
{7629}{}{Ah, minha cabeca doi}
{7630}{}{Você quebrou meu nariz!}
{7631}{}{Ai, meu braço}
{7632}{}{Você quebrou meu braço!}
{7633}{}{Eu não precisava disso}
{7634}{}{Ai, meu braço}
{7635}{}{Você quebrou meu braço!}
{7636}{}{Meu braço bom!}
{7637}{}{Oof!}
{7638}{}{Isso doi!}
{7639}{}{Continue, tente isso de novo!}
{7640}{}{Oof!}
{7641}{}{Gasp!}
{7642}{}{Ai, bugger all!}
{7643}{}{Ah, ufa!}
{7644}{}{Ouch!}
{7645}{}{Ouch! Isso doi!}
{7646}{}{Ei! Eu não estava preparado pra isso!}
{7647}{}{Ai, minha perna}
{7648}{}{Você vai pagar big time por isso!}
{7649}{}{Ah, meu joelho!}
{7650}{}{Ai, minha perna}
{7651}{}{Você vai pagar big time por isso!}
{7652}{}{Ah, meu joelho}
{7653}{}{Argh! Minha retina!}
{7654}{}{Meus olhos.... Não meus olhos...}
{7655}{}{Esse foi um tiro verdadeiramente barato!}
{7656}{}{Uuuuuu, minha virilha!}
{7657}{}{Uuu! Eu vou aprender esse movimento...}
{7658}{}{Eu sentirei isso de manha}
{7659}{}{Eu odeio tiros no crotch}
{7660}{}{Urp!}
{7661}{}{Ai! Eu vou matar você por isso!}
{7700}{}{}
{7701}{}{Talvez isto não era uma boa ideia}
{7702}{}{Eu acho que eu posso estar outgunned}
{7703}{}{}
{7704}{}{Eu não vou morrer por isto!}
{7705}{}{Isso e demais para mim}
{7706}{}{Ei você!}
{7707}{}{Alguém tem grandes problemas}
{7708}{}{Nós não precisamos do seu tipo por aqui!}
{7709}{}{Quem você pensa que você e?}
{7710}{}{}
{7711}{}{Policia do Hub!}
{7712}{}{Tome isto!}
{7713}{}{Agora eu tenho você!}
{7714}{}{Desca e fique abaixado}
{7715}{}{Você gosta disto?}
{7716}{}{}
{7717}{}{Que seja}
{7718}{}{Você acha que você e problema? Pense de novo}
{7719}{}{Miseravel}
{7720}{}{Vou te levar preso!}
{7721}{}{Talvez você aprendera um pouco de respeito}
{7722}{}{Você não esperava me tocar, esperava?}
{7723}{}{Eu sou um profissional treinado}
{7724}{}{Você não é bom/boa o bastante}
{7725}{}{Esse foi seu ultimo erro}
{7726}{}{Amador}
{7727}{}{Você aprende a lutar em bares?}
{7728}{}{Ai! Seu/Sua filho da...}
{7729}{}{Eu vou matar você por isso}
{7730}{}{Eu arrancarei sua cabeca fora!}
{7731}{}{Ai, meu braço}
{7732}{}{Maldicao. Meu braço esta destruido!}
{7733}{}{Meu braço!}
{7734}{}{Ai, meu braço}
{7735}{}{Maldicao. Meu braço esta destruido!}
{7736}{}{Meu braço!}
{7737}{}{Você vai cumprir algum tempo por isso!}
{7738}{}{É contra a lei atingir um oficial!}
{7739}{}{Ouch!}
{7740}{}{Oof!}
{7741}{}{Basta! Eu já tive o bastante de você!}
{7742}{}{Gonna put you away por isso}
{7743}{}{Me acerte ai de novo e nós não teremos que ver um juiz}
{7744}{}{Faca isso de novo por seu proprio peril}
{7745}{}{Oof! Desista!}
{7746}{}{}
{7747}{}{Ai, minha perna}
{7748}{}{Você vai pagar big time por isso!}
{7749}{}{Meu joelho!}
{7750}{}{Ai, minha perna}
{7751}{}{Você vai pagar big time por isso!}
{7752}{}{Meu joelho!}
{7753}{}{Eu não consigo ver!}
{7754}{}{Meu olho! Você pagara por isso!}
{7755}{}{Eu estou cego!! Eu preciso de reforco}
{7756}{}{Uuuuuu, minha virilha!}
{7757}{}{Eu sentirei isso de manha}
{7758}{}{Seu/Sua miseravel!}
{7759}{}{Urp!}
{7760}{}{Agora você esta tornando pessoal!}
{7761}{}{Maldicao, isso doi}
{7800}{}{Isto não esta acabado. De forma alguma!}
{7801}{}{Eu voltarei...}
{7802}{}{Você esta morto. Você me ouviu? Morto!}
{7803}{}{Eu ainda verei você morto!}
{7804}{}{Você ainda não ouviu sobre mim pela ultima vez!}
{7805}{}{Você vai ter o troco, eu prometo!}
{7806}{}{Esta acabado, miseravel! Você e historia!}
{7807}{}{Você nunca deveria ter se oposto a mim, miseravel}
{7808}{}{Você precisa de uma nova atitude, miseravel}
{7809}{}{Você é um erro que eu tenho que corrigir}
{7810}{}{Você esta no trem expresso para o Inferno, miseravel}
{7811}{}{Basta! Alguém vai morrer}
{7812}{}{Tome isto!}
{7813}{}{Isto e o que eu faco com miseraveis e perdedores}
{7814}{}{Eu vou apreciar isto}
{7815}{}{Isto vai doer!}
{7816}{}{Você mexeu com o homem errado}
{7817}{}{Ninguem vai tirar o Hub de mim}
{7818}{}{Espero que você não morra muito rapido}
{7819}{}{Ninguem mexe com o Decker!}
{7820}{}{Morra!}
{7821}{}{Tente isto pelo tamanho!}
{7822}{}{Isso e patetico de verdade}
{7823}{}{Você mordeu mais do que pode mastigar!}
{7824}{}{Eu ainda consigo manejar a mim mesmo em uma luta}
{7825}{}{Você não consegue ter o trabalho feito}
{7826}{}{Esse foi seu ultimo tiro!}
{7827}{}{Perdedor}
{7828}{}{Meu cranio dolorido!}
{7829}{}{Como ousa você fazer isto a mim!}
{7830}{}{Você quebrou meu nariz!}
{7831}{}{Seu/Sua sujo beijador de radscorpions...}
{7832}{}{Você quebrou meu braço!}
{7833}{}{Meu braço! Meu braço!}
{7834}{}{Seu/Sua sujo beijador de radscorpions...}
{7835}{}{Você quebrou meu braço!}
{7836}{}{Meu braço! Meu braço!}
{7837}{}{You're an underhanded SOB, você sabia disso?}
{7838}{}{Oof! Minhas costelas vao doer por dias!}
{7839}{}{Ai! O que pensa que eu sou? Um saco de pancada?}
{7840}{}{Oof!}
{7841}{}{Ai!}
{7842}{}{Não mexa comigo assim, I won't take it}
{7843}{}{Oof! Você teve sua chance de negociar, and you blew it!}
{7844}{}{Ai! Isso foi muito desagradavel}
{7845}{}{Oof! Eu vou me lembrar disso...}
{7846}{}{Gasp! Eu... sem... ar...}
{7847}{}{Ai, minha perna}
{7848}{}{Uuu.... Seu/Sua miseravel!}
{7849}{}{Ah, meu joelho!}
{7850}{}{Ai, minha perna}
{7851}{}{Uuu.... Seu/Sua miseravel!}
{7852}{}{Ah, meu joelho}
{7853}{}{Sangue. Todo este sangue...}
{7854}{}{Meus olhos.... Não meus olhos...}
{7855}{}{Esse foi um tiro verdadeiramente barato!}
{7856}{}{Uuuuuu, minha virilha!}
{7857}{}{Uuu! Nada mal, miseravel}
{7858}{}{Uuu! Você esta escavando seu tumulo, miseravel}
{7859}{}{Uuu! Eu vou enterrar você vivo no Glow!}
{7860}{}{Urp!}
{7861}{}{Ai! Eu vou matar você por isso!}
{7900}{}{Isto não esta acabado. De forma alguma!}
{7901}{}{Eu voltarei...}
{7902}{}{Você esta morto. Você me ouviu? Morto!}
{7903}{}{Eu ainda verei você morto!}
{7904}{}{Você ainda não ouviu sobre mim pela ultima vez!}
{7905}{}{Você vai ter o troco, eu prometo!}
{7906}{}{Eu sou muito bom em consertar problemas}
{7907}{}{Você nunca deveria ter se oposto ao Sr. Decker}
{7908}{}{Eu vou mudar sua atitude}
{7909}{}{Sr. Decker não gosta de você}
{7910}{}{Você esta no trem expresso para o Inferno}
{7911}{}{Basta! Alguém vai morrer}
{7912}{}{Tome isto!}
{7913}{}{Decker pensa que você precisa aprender respeito}
{7914}{}{Esta é uma mensagem do Decker}
{7915}{}{Isto vai doer!}
{7916}{}{Você mexeu com o homem errado}
{7917}{}{Decker diz ola.}
{7918}{}{É muito tarde para desculpas}
{7919}{}{Ninguem mexe com o Decker!}
{7920}{}{Morra!}
{7921}{}{Tente isto pelo tamanho!}
{7922}{}{Isso e patetico de verdade}
{7923}{}{Você mordeu mais do que pode mastigar!}
{7924}{}{Eu não acho que você possa acertar o alvo}
{7925}{}{Você não consegue ter o trabalho feito}
{7926}{}{Esse foi seu ultimo erro}
{7927}{}{Você esta tendo um dia ruim. Stick around. Ele fica pior.}
{7928}{}{Meu cranio dolorido!}
{7929}{}{Uuuu...}
{7930}{}{Você quebrou meu nariz!}
{7931}{}{Uuuu...}
{7932}{}{Você quebrou meu braço!}
{7933}{}{Meu braço!}
{7934}{}{Uuuu...}
{7935}{}{Você quebrou meu braço!}
{7936}{}{Meu braço!}
{7937}{}{Oof! Nenhum miseravel como você vai me derrubar...}
{7938}{}{Oof! Minhas costelas!}
{7939}{}{Ai! Whatta some kinda smuzzle or something?}
{7940}{}{Há! Eu tive hematomas maiores quand malhava!}
{7941}{}{Oof! Vocês miseraveis são todos parecidos...}
{7942}{}{Gulp! Tenho... que... respirar...}
{7943}{}{Ouch!}
{7944}{}{Ai! Piss off you brat!}
{7945}{}{Ah, bosta...}
{7946}{}{Argh! Eu acho que você rachou uma costela!}
{7947}{}{Ai, minha perna}
{7948}{}{Uuuu....}
{7949}{}{Ah, meu joelho!}
{7950}{}{Ai, minha perna}
{7951}{}{Uuuu....}
{7952}{}{Ah, meu joelho}
{7953}{}{Sangue. Todo este sangue...}
{7954}{}{Meus olhos....}
{7955}{}{Esse foi um tiro verdadeiramente barato!}
{7956}{}{Uuuuuu, minha virilha!}
{7957}{}{Uuu! Eu vou retornar o favor}
{7958}{}{Uuu! Você esta escavando seu tumulo}
{7959}{}{Uuu! Eu aposto que você pensa que é engracado}
{7960}{}{Urp!}
{7961}{}{Ai! Eu não acho que eu gosto de você}
{8000}{}{Meu papai vai matar você! Espere até que ele chegue aqui!}
{8001}{}{Mamae!!!}
{8002}{}{Alguém me ajude!}
{8003}{}{Socorro!}
{8004}{}{Aaaaahhhh!}
{8005}{}{Waaaaahhhh!!}
{8006}{}{Ei você!}
{8007}{}{Eu odeio você! Eu odeio você!}
{8008}{}{}
{8009}{}{Você é um mutante deformado!}
{8010}{}{Alguém precisa rasgar você!}
{8011}{}{Eu vou matar você!}
{8012}{}{Cabeca de radscorpion!}
{8013}{}{Eu vou matar você!}
{8014}{}{Mutante perdedor!}
{8015}{}{Bebe Perdedor do Glow! Bebe Perdedor do Glow!}
{8016}{}{Morra, feio!}
{8017}{}{Sua Mamae era um rato-toupeira!}
{8018}{}{Worm ridden Bebe do Glow!}
{8019}{}{Eu vou fazer você feio!}
{8020}{}{Eu odeio você!}
{8021}{}{Amante de radscorpion! Você dorme com radscorpions!}
{8022}{}{Sua Mamae era um Bebe do Glow!}
{8023}{}{Você não pode me tocar, cerebro de radscorpion!}
{8024}{}{Você não consegue nem mesmo derrotar uma criança}
{8025}{}{Perdedor!}
{8026}{}{Não me acertou, cerebro de radiação!}
{8027}{}{Qual e o problema, Bebe do Glow?}
{8028}{}{Minha cara!}
{8029}{}{Uuuu, isso doi...}
{8030}{}{Ai! Minha orelha!}
{8031}{}{Ai, meu braço}
{8032}{}{Uuuu, isso doi...}
{8033}{}{Você quebrou meu braço! Papai!}
{8034}{}{Ai, meu braço}
{8035}{}{Uuuu, isso doi}
{8036}{}{Você quebrou meu braço! Papai!}
{8037}{}{Ai!}
{8038}{}{Ai! Mamaezinha, o homem/mulher mau/ma esta me machucando!}
{8039}{}{Ouch! Isso foi ruim!}
{8040}{}{Ai! Se eu fosse maior, eu derrotaria você!}
{8041}{}{Ferida! Ferida! Ferida! Mamaezinha!}
{8042}{}{Ai! Meu papai e maior do que o seu papai!}
{8043}{}{Uuuu, Eu... vou... chorar! Brahhhhh!}
{8044}{}{Ouch!}
{8045}{}{Ai!}
{8046}{}{Ai! Ai! Você e mau!}
{8047}{}{Ai, minha perna}
{8048}{}{Meu joelho!}
{8049}{}{Você quebrou minha perna! Papai!}
{8050}{}{Ai, minha perna}
{8051}{}{Meu joelho!}
{8052}{}{Você quebrou minha perna! Papai!}
{8053}{}{Aaaaaahhhh!!!}
{8054}{}{Onde todo mundo foi?}
{8055}{}{Esta tudo escuro...}
{8056}{}{Uuuuuu, minha virilha!}
{8057}{}{Ai! Seu/Sua Bebe do Glow sujo fedido!}
{8058}{}{Urp!}
{8059}{}{Eu...não...consigo...respirar...}
{8060}{}{Uuuuu...}
{8061}{}{A dor, a dor...}
{8100}{}{Opcao para recuar iniciada}
{8101}{}{Plano tatico: recuar}
{8102}{}{Efetivo de combate minimo. Aconselhado recuar}
{8103}{}{Analise tatica completa. Recomendado recuar.}
{8104}{}{Baixando programa de fuga}
{8105}{}{Sequencia para recuar iniciada}
{8106}{}{Alvo alcancado!}
{8107}{}{Eliminar! Eliminar!}
{8108}{}{O(A) humanoide não deve escapar}
{8109}{}{Eliminar o intruso}
{8110}{}{Sequencia de combate iniciada}
{8111}{}{Fazendo upload do programa de combate}
{8112}{}{Sequencia de combate iniciada}
{8113}{}{Atacando alvo}
{8114}{}{Iniciando sequencia de ataque}
{8115}{}{O(A) intruso deve ser destruido}
{8116}{}{Selecao de opções taticas completada}
{8117}{}{Comecando ataque}
{8118}{}{O alvo deve ser destruido}
{8119}{}{Sequencia de eliminacao do inimigo iniciada}
{8120}{}{Alvo deve ser eliminado}
{8121}{}{Selecao ofensiva completada}
{8122}{}{Analise. Sucesso do programa defensivo}
{8123}{}{Analise. Ofensa do alvo negligivel.}
{8124}{}{O ataque do alvo falhou. Calculando a resposta}
{8125}{}{A unidade não foi prejudicada pelo ataque}
{8126}{}{Recalculando as habilidades ofensivas do alvo}
{8127}{}{Analise. O alvo errou na selecao tatica. Unidade não danificada}
{8128}{}{Aviso, Mal funcionamento da CPU!}
{8129}{}{Aviso! Dano da CPU! Processamento impaired!}
{8130}{}{Aviso! CPU danificada! Redirecionando o sistema critico!}
{8131}{}{Dano no manipulador registrado}
{8132}{}{Unidade atingida no manipulador esquerdo. Dano}
{8133}{}{Manipulador atingido registrado. Tentando compensar}
{8134}{}{Dano no manipulador registrado}
{8135}{}{Unidade atingida no manipulador direito. Avaliacao do dano}
{8136}{}{Manipulador atingido registrado. Tentando compensar}
{8137}{}{Frame atingido. Corrigindo por causa do dano}
{8138}{}{Frame atingido. Reparos internos iniciados}
{8139}{}{Estrutura principal sob ataque}
{8140}{}{Armadura penetrada}
{8141}{}{Estrutura principal sob ataque. Corrigindo}
{8142}{}{Esta unidade sob ataque}
{8143}{}{Tentando manobra de combate}
{8144}{}{Brzzt!}
{8145}{}{Dano menor}
{8146}{}{Brzzt!}
{8147}{}{Dano no motivador registrado}
{8148}{}{Unidade atingida no motivador direito. Avaliacao do dano}
{8149}{}{Motivador atingido registrado. Tentando}
{8150}{}{Dano no motivador registrado}
{8151}{}{Unidade atingida no motivador esquerdo. Avaliacao do dano}
{8152}{}{Motivador atingido registrado. Tentando compensar}
{8153}{}{Sensor atingido! Sensor atingido!}
{8154}{}{Sensores impaired! Sensores impaired!}
{8155}{}{Mal funcionamento do sistema de sensores, tentando trespassar}
{8156}{}{Mal funcionamento do regulador registrado!}
{8157}{}{Dano no Regulador! Regulacao impaired!}
{8158}{}{Regulador danificado! Redirecionando o sistema critico!}
{8200}{}{Eu não vou morrer por isto!}
{8201}{}{O trabalho não vale isto!}
{8202}{}{Alguém mais pegue eles!}
{8203}{}{La se vai minha reputação...}
{8204}{}{Yikes!}
{8205}{}{Eu não vou lutar contra isso!}
{8206}{}{Não outro cabeca de osso!}
{8207}{}{Você acabou de cruzar a linha!}
{8208}{}{Você não vai embora com isso aqui!}
{8209}{}{Não no meu turno!}
{8210}{}{Ninguem faz isso no meu lugar!}
{8211}{}{Ei você!}
{8212}{}{Isto e o que eu faco com causadores de problemas!}
{8213}{}{Desliguem as luzes...}
{8214}{}{Isto ensinara você a não causar problemas}
{8215}{}{Seu numero aumentou!}
{8216}{}{Você vai perder}
{8217}{}{Vamos ver quao forte você é.}
{8218}{}{Miseravel}
{8219}{}{Você lamenta agora?}
{8220}{}{Você esperava sair bem com isto?}
{8221}{}{Eu como miseraveis como você no cafe da manha}
{8222}{}{Você esta dando tiros de aviso ou você e apenas ruim!}
{8223}{}{Você não é apenas um miseravel, você e um miseravel incompetente!}
{8224}{}{Cara, você e ruim!}
{8225}{}{Isso e o melhor que você pode fazer?}
{8226}{}{Você não esperava to tag me, esperava?}
{8227}{}{Você sempre foi uma falha ou isto é uma coisa recente?}
{8228}{}{Você quebrou meu nariz!}
{8229}{}{Eu não precisava daquela orelha mesmo}
{8230}{}{Maldicao! Isso doi!}
{8231}{}{Ai, meu braço}
{8232}{}{Você pode me incapacitar mas eu ainda chutarei sua bunda}
{8233}{}{Isso foi um erro}
{8234}{}{Ai, meu braço}
{8235}{}{Você pode me incapacitar mas eu ainda chutarei sua bunda}
{8236}{}{Isso foi um erro}
{8237}{}{Ai!}
{8238}{}{Isso foi um erro}
{8239}{}{Oof!}
{8240}{}{Ai! Certo, isso basta!}
{8241}{}{Ai! Agora eu estou furioso}
{8242}{}{Oof!}
{8243}{}{Argh!}
{8244}{}{Ouch!}
{8245}{}{Ai! Eu vou pegar esta espingarda e enfia-lá...}
{8246}{}{Gulp!}
{8247}{}{Outra perna destruida não! Ah bem...}
{8248}{}{Você pode me incapacitar mas eu ainda chutarei sua bunda}
{8249}{}{Isso foi um erro}
{8250}{}{Outra perna destruida não! Ah bem...}
{8251}{}{Você pode me incapacitar mas eu ainda chutarei sua bunda}
{8252}{}{Isso foi um erro}
{8253}{}{Eu não consigo ver! Você esta comecando a me encher!}
{8254}{}{Eu não preciso ver você para matar você!}
{8255}{}{Ai! Tiro de sorte...}
{8256}{}{Uuuuuu, minha virilha!}
{8257}{}{Agora você esta tornando pessoal!}
{8258}{}{A virilha. O ultimo refugio de um vilao}
{8259}{}{Eu sou uma mulher, you twit.}
{8260}{}{Você esta mexendo com a mulher errada}
{8261}{}{Urp!}
{8300}{}{Squeak!}
{8301}{}{Squeak!!}
{8302}{}{Squeak!}
{8303}{}{squeak}
{8400}{}{Hora de sair daqui!}
{8401}{}{Arrgh!}
{8402}{}{Recuar!}
{8403}{}{Isto vai machucar muito você é a mim nada, de modo algum.}
{8404}{}{Eu vou chutar seu traseiro.}
{8405}{}{Eu tentarei e farei isto rapido.}
{8406}{}{Vamos ver se você aprecia isto.}
{8407}{}{Tome isto.}
{8408}{}{Te peguei!}
{8409}{}{Seu/Sua perdedor!}
{8410}{}{Tente com mais vontade!}
{8411}{}{Maldito seja, Seu/Sua pecador!}
{8412}{}{Você quebrou meu nariz!}
{8413}{}{Agh! Você quebrou meu braço!}
{8414}{}{Meu braço esta destruido!}
{8415}{}{Agh! Você quebrou meu braço!}
{8416}{}{Meu braço esta destruido!}
{8417}{}{Oof!}
{8418}{}{Argh!}
{8419}{}{Você pagara por isso . . .}
{8420}{}{Vamos, tente isso de novo!}
{8421}{}{Ai! Você quebrou minha perna!}
{8422}{}{Uh! Meu joelho!}
{8423}{}{Ai! Você quebrou minha perna!}
{8424}{}{Uh! Meu joelho!}
{8425}{}{Aah! Eu não posso ver!}
{8426}{}{Você me cegou, seu/sua cuzao(ona)!}
{8427}{}{Oooohhh . . .}
{8500}{}{Hora de uma retirada tatica.}
{8501}{}{Eu tornarei isto breve.}
{8502}{}{Mudando.}
{8503}{}{Coma isto.}
{8504}{}{Tenha um bom dia.}
{8505}{}{Tenho algo pra você.}
{8506}{}{Não exatamente.}
{8507}{}{Perto, mas isso não foi um nuke.}
{8508}{}{Ai. Bom tiro.}
{8509}{}{Ugh.}
{8510}{}{Perdi outro pedaço da minha orelha . . .}
{8511}{}{Maldito seja, lá se vai outro dente . . .}
{8512}{}{Ugh.}
{8513}{}{Não precisava daquele braço mesmo.}
{8514}{}{Ai.}
{8515}{}{Maldicao, essa é a minha mao que atira.}
{8516}{}{Ai.}
{8517}{}{Maldicao, outra costela destruida.}
{8518}{}{Se você quer me matar, tente a cabeca.}
{8519}{}{Você pode me retardar, mas eu ainda pegarei você.}
{8520}{}{Eu já tive uma perna quebrada antes.}
{8521}{}{Você pode me retardar, mas eu ainda pegarei você.}
{8522}{}{Eu já tive uma perna quebrada antes.}
{8523}{}{Agora, isso e lutar sujo.}
{8524}{}{Se eu ficar cego, eu vou machucar você antes de eu matar você.}
{8525}{}{Ugh! Pare!}
{8526}{}{Ah, minhas bolas . . .}
{8527}{}{Agora ISSO doi.}
{8600}{}{Tenho que fugir}
{8601}{}{Eu estou fora desta luta}
{8602}{}{O que aconteceu com você}
{8603}{}{Alguém me ajude!}
{8604}{}{Isto e bem longe do meu league!}
{8605}{}{Meu deus, não!}
{8606}{}{Traidor!}
{8607}{}{Eu não posso acreditar que você fez isso!}
{8608}{}{A superficie deve deixar as pessoas insanas!}
{8609}{}{Você ficou insano!}
{8610}{}{Defendam a Vault!}
{8611}{}{Eu pensei que você era meu amigo!}
{8612}{}{Você nunca deveria ter voltado}
{8613}{}{É pensar que nos costumavamos ser amigos!}
{8614}{}{Eu gostaria que você nunca tivesse ido a superficie}
{8615}{}{Ola, velho amigo}
{8616}{}{Eu estou pondo você pra fora de sua miseria}
{8617}{}{Eu estou pondo você pra fora da minha miseria}
{8618}{}{Isto não me da prazer}
{8619}{}{Seu/Sua pequeno rato de caverna raivoso!}
{8620}{}{Eu tenho que por você pra fora}
{8621}{}{Você e apenas um bully e um sneak}
{8622}{}{Eu podia ver isso vindo}
{8623}{}{Você lutava melhor quando nos eramos crianças}
{8624}{}{Sua mira não melhorou}
{8625}{}{Você ainda da um passo pra tras toda vez que você tenta esse movimento}
{8626}{}{Você nunca poderia me derrotar}
{8627}{}{Como eles escolheram você pra sair na superficie?}
{8628}{}{Ah, meu cranio dolorido!}
{8629}{}{Uh}
{8630}{}{Uuu}
{8631}{}{Meu braço!}
{8632}{}{Ai! Eu ouvi algo rachar...}
{8633}{}{Meu braço acabou de ficar dormente}
{8634}{}{Meu braço!}
{8635}{}{Ai! Eu ouvi algo rachar...}
{8636}{}{Meu braço acabou de ficar dormente}
{8637}{}{Ai!}
{8638}{}{Oof! É nos costumavamos ser amigos...}
{8639}{}{Oof!}
{8640}{}{Ai! Certo, isso basta!}
{8641}{}{Ai! Agora eu estou furioso}
{8642}{}{Oof!}
{8643}{}{Argh!}
{8644}{}{Ouch!}
{8645}{}{Você ainda acerta como uma bicha}
{8646}{}{Gulp!}
{8647}{}{Ai!}
{8648}{}{Minha perna esta comecando a curvar}
{8649}{}{ow, meu joelho}
{8650}{}{Ei, eu ainda preciso dessa perna!}
{8651}{}{Minha perna esta comecando a curvar}
{8652}{}{Ouch, meu joelho}
{8653}{}{Aggghhh!}
{8654}{}{Seu/Sua pequeno bastardo!}
{8655}{}{Meus olhos!}
{8656}{}{Você sempre gostou de golpes baixos...}
{8657}{}{Você nunca muda, não e?}
{8658}{}{Eu já me senti melhor...}
{8659}{}{Uuu, minha virilha!}
{8660}{}{Você sempre foi o lutador mais sujo na Vault}
{8661}{}{Seu/Sua pequeno rato de caverna sujo!}
{8700}{}{Certo, você pode te-lá!}
{8701}{}{A puta e sua!}
{8702}{}{A Tandi e sua. Me deixe em paz!}
{8703}{}{Certo, você pode te-lá!}
{8704}{}{A Tandi e sua. Me deixe em paz!}
{8705}{}{A puta e sua!}
{8706}{}{Deixe a luta de honra começar!}
{8707}{}{}
{8708}{}{}
{8709}{}{Este e meu!}
{8710}{}{Khans, ataquem!}
{8711}{}{}
{8712}{}{}
{8713}{}{}
{8714}{}{Eu sou supremo!}
{8715}{}{RAAAAAAARRRR!!}
{8716}{}{}
{8717}{}{}
{8718}{}{Você e meu para matar!}
{8719}{}{}
{8720}{}{}
{8721}{}{}
{8722}{}{}
{8723}{}{}
{8724}{}{}
{8725}{}{Minha honra e mais forte do que a sua!}
{8726}{}{}
{8727}{}{Você não é de valor de combate comigo!}
{8728}{}{Um golpe valoroso!}
{8729}{}{}
{8730}{}{}
{8731}{}{}
{8732}{}{Você quebrou meu braço! Agora a luta e justa!}
{8733}{}{}
{8734}{}{}
{8735}{}{Você quebrou meu braço! Agora a luta e justa!}
{8736}{}{}
{8737}{}{}
{8738}{}{}
{8739}{}{}
{8740}{}{Oof!}
{8741}{}{Ouch!}
{8742}{}{}
{8743}{}{}
{8744}{}{}
{8745}{}{}
{8746}{}{Argh! Isso doi!}
{8747}{}{}
{8748}{}{Esse foi um golpe barato!}
{8749}{}{}
{8750}{}{}
{8751}{}{Esse foi um golpe barato!}
{8752}{}{}
{8753}{}{}
{8754}{}{}
{8755}{}{Isso não foi honravel!}
{8756}{}{Uuuuuu, minha virilha!}
{8757}{}{}
{8758}{}{}
{8759}{}{}
{8760}{}{Urp!}
{8761}{}{Você não roubara minha masculinidade!}
{8800}{}{Ai! Seu filho da...}
{8801}{}{Você quebrou meu nariz!}
{8802}{}{Vou arrancar sua cabeça!}
{8803}{}{Você acertou minha porra do crânio!}
{8804}{}{Tem que se esforçar mais que isso, mas não muito mais.}
{8805}{}{Ai, isso vai te custar caro.}
{8806}{}{Ah, olha só os passarinhos bonitinhos.}
{8807}{}{Isso doeu.}
{8808}{}{Você estragou meu rostinho bonito.}
{8809}{}{Isso vai deixar cicatriz.}
{8810}{}{Ai, meu braço.}
{8811}{}{Você acabou de cometer o maior erro da sua vida.}
{8812}{}{Meu braço!}
{8813}{}{Rá, eu sou destro.}
{8814}{}{Só preciso de um braço pra te matar.}
{8815}{}{Nem precisava desses dedos mesmo.}
{8816}{}{Só preciso de um dedo pra você, amigão.}
{8817}{}{Droga, isso vai atrapalhar meu golpe.}
{8818}{}{Ainda posso te tirar do mapa.}
{8819}{}{Droga, partiu meu braço bem no meio.}
{8820}{}{Ai, meu braço.}
{8821}{}{Você acabou de cometer o maior erro da sua vida.}
{8822}{}{Meu braço!}
{8823}{}{Consigo te vencer com a mão esquerda.}
{8824}{}{Rá, eu sou canhoto mesmo.}
{8825}{}{Tentando me desarmar, é?}
{8826}{}{Isso não vai me deter.}
{8827}{}{Ainda tenho a outra mão pra usar contra você.}
{8828}{}{Droga, isso doeu.}
{8829}{}{Mmm, isso vai deixar marca.}
{8830}{}{Urp!}
{8831}{}{Oof!}
{8832}{}{Ouch!}
{8833}{}{É, isso trincou umas costelas, com certeza.}
{8834}{}{Ugh! Isso doeu!}
{8835}{}{Ouch!}
{8836}{}{Argh!}
{8837}{}{Ah, acho que você quebrou uma costela!}
{8838}{}{Ai!!! Meu baço!}
{8839}{}{É, isso só me esquentou.}
{8840}{}{Agora você me deixou puto.}
{8841}{}{Não gostei nada disso.}
{8842}{}{Droga, você estourou meu maldito pulmão.}
{8843}{}{Só um verme como você miraria na barriga.}
{8844}{}{Vou trocar esses órgãos que você furou por alguns dos seus.}
{8845}{}{Droga, você é melhor do que parece, imagino que tenha que ser.}
{8846}{}{Isso não foi nada legal. Vou ter que te ensinar boas maneiras.}
{8847}{}{Tiro de sorte dessa vez.}
{8848}{}{Espero que ache tão engraçado quando eu fizer isso com você.}
{8849}{}{Devo estar ficando velho. Isso doeu mesmo.}
{8850}{}{Você vai ter que fazer bem melhor que isso.}
{8851}{}{Tudo ainda funciona bem o bastante pra te liquidar.}
{8852}{}{Passou raspando do meu pulmão, acho.}
{8853}{}{Eu tenho mesmo muito sangue, bom, tinha, pelo menos.}
{8854}{}{Caramba, isso dói!}
{8855}{}{Porra! Seu desgraçado!}
{8856}{}{Ninguém me acerta assim e vive pra contar.}
{8857}{}{Assim que eu recuperar o fôlego (cof, cof) vou atrás de você.}
{8858}{}{Você rasgou alguma coisa dentro de mim.}
{8859}{}{Você não sabe no que se meteu.}
{8860}{}{Ai, minha perna.}
{8861}{}{Não preciso ficar de pé pra te matar!}
{8862}{}{Meu joelho!}
{8863}{}{Meu tendão de aquiles!}
{8864}{}{Aaiiiieeee!!}
{8865}{}{Lá se vai meu gingado.}
{8866}{}{Vou te ensinar a arrancar meus dedos do pé.}
{8867}{}{Quebrar minha perna? Vou te despedaçar!}
{8868}{}{Cadê um torniquete quando a gente precisa.}
{8869}{}{Porra, minha perna dói.}
{8870}{}{Ai, minha perna.}
{8871}{}{Não preciso ficar de pé pra te matar!}
{8872}{}{Meu joelho!}
{8873}{}{Isso vai me deixar mancando por um tempo.}
{8874}{}{Vem cá, não me faça mancar atrás de você.}
{8875}{}{Quase arrancou minha perna fora.}
{8876}{}{Isso vai me atrasar a temporada inteira.}
{8877}{}{Isso me tira de campo com certeza.}
{8878}{}{Eu tenho outra perna.}
{8879}{}{Rá-rá, essa era minha perna de mentira mesmo.}
{8880}{}{Não consigo enxergar!}
{8881}{}{Essa luta piora a cada segundo.}
{8882}{}{Isso foi golpe baixo!}
{8883}{}{Estou cego, porra!}
{8884}{}{Seu babaca, você me cegou!}
{8885}{}{Só por isso, vou estourar seus olhos feito uvas maduras.}
{8886}{}{Você arrancou minha porra do olho!}
{8887}{}{Merda, meu olho tá pendurado pelo nervo óptico aqui.}
{8888}{}{Ainda consigo ouvir onde você está.}
{8889}{}{Não encoste nunca mais na porra dos meus olhos!}
{8890}{}{Oooooo, minha virilha!}
{8891}{}{Vou sentir isso de manhã.}
{8892}{}{Covarde de merda!}
{8893}{}{Urp!}
{8894}{}{Isso não vai te ajudar em nada.}
{8895}{}{Era de se esperar que tentasse isso.}
{8896}{}{Se divertindo, é?}
{8897}{}{Vou arrancar os seus e te obrigar a comê-los.}
{8898}{}{Acho que preciso me sentar um pouco.}
{8899}{}{Tem que se esforçar mais, minha coquilha aparou quase tudo.}
