{0}{}{Rajada}
{1}{}{Fugir}
{2}{}{Pref. de Arma}
{3}{}{Distância}
{4}{}{Atacar Quem}
{5}{}{Uso de Drogas}
{10}{}{Pronto}
{11}{}{Cancelar}
{99}{}{Não Aplicável.}
{100}{}{Sempre!}
{101}{}{Às vezes, não se preocupe em me acertar}
{102}{}{Tenha certeza de não me acertar}
{103}{}{Tenha cuidado para não me acertar}
{104}{}{Tenha certeza absoluta de não me acertar}
{200}{}{Covarde total}
{201}{}{Seu dedo dói}
{202}{}{Você está sangrando um pouco}
{203}{}{Não se sentindo bem}
{204}{}{Você precisa de um torniquete}
{205}{}{Nunca!}
{300}{}{Nenhuma}
{301}{}{Corpo-a-corpo}
{302}{}{Corpo-a-corpo e depois à distância}
{303}{}{À distância e depois corpo-a-corpo}
{304}{}{À distância}
{305}{}{Desarmado}
{400}{}{Fique perto de mim}
{401}{}{Ataquem!}
{402}{}{Atire de longe no inimigo}
{403}{}{Por conta própria}
{404}{}{Fique onde está}
{500}{}{Quem estiver me atacando}
{501}{}{O mais forte}
{502}{}{O mais fraco}
{503}{}{Quem você quiser}
{504}{}{Quem estiver mais perto}
{600}{}{Estou limpo}
{601}{}{Stimpaks quando ferido um pouco}
{602}{}{Stimpaks quando ferido muito}
{603}{}{Qualquer droga de vez em quando}
{604}{}{Qualquer droga a qualquer hora}
