{0}{}{FO}
{1}{}{PE}
{2}{}{RE}
{3}{}{CA}
{4}{}{IN}
{5}{}{AG}
{6}{}{SO}
{7}{}{Pts de Vida}
{8}{}{Classe Arm.}
{9}{}{  Normal}
{10}{}{  Laser}
{11}{}{  Fogo}
{12}{}{  Plasma}
{13}{}{  Explosão}
{14}{}{Sem item}
{15}{}{Dano:}
{16}{}{Alc:}
{17}{}{Mun:}
{18}{}{(Não usado)}
{19}{}{Você não tem pontos de ação o bastante pra usar o inventario.}
{20}{}{Peso Total:}
{21}{}{MOVER ITENS}
{22}{}{TUDO}
{23}{}{DEFINIR TIMER}
{24}{}{Desarmado:}
{25}{}{Você não pode pegar aquilo. Você esta na sua capacidade máxima de peso.}
{26}{}{Não há espaço restante para aquele item.}
{27}{}{OK, essa é uma boa negociação.}
{28}{}{Não, sua oferta não é boa o bastante.}
{29}{}{Você ganha %d pontos de experiência por usar sua técnica de roubar com sucesso.}
