{101}{}{Perspicaz}
{102}{}{Ataques Corpo a Corpo Aprimorados}
{103}{}{Dano Corpo a Corpo Aprimorado}
{104}{}{Movimento Extra}
{105}{}{Dano à Distância Aprimorado}
{106}{}{Cadência de Tiro Aprimorada}
{107}{}{Iniciativa Aprimorada}
{108}{}{Cura Rápida}
{109}{}{Mais Críticos}
{110}{}{Visão Noturna}
{111}{}{Presença}
{112}{}{Resistente a Radiação}
{113}{}{Robustez}
{114}{}{Costas Fortes}
{115}{}{Atirador de Elite}
{116}{}{Corrida Furtiva}
{117}{}{Sobrevivente}
{118}{}{Mestre Mercador}
{119}{}{Instruído}
{120}{}{Curandeiro}
{121}{}{Caçador de Fortuna}
{122}{}{Críticos Aprimorados}
{123}{}{Empatia}
{124}{}{Slayer}
{125}{}{Sniper}
{126}{}{Morte Furtiva}
{127}{}{Garoto Ágil}
{128}{}{Mente Blindada}
{129}{}{Portador de Vida}
{130}{}{Evasivo}
{131}{}{Snakeater}
{132}{}{Sr. Conserta-Tudo}
{133}{}{Médico}
{134}{}{Ladrão Mestre}
{135}{}{Orador}
{136}{}{Heave Ho!}
{137}{}{Inimigo Amistoso}
{138}{}{Mãos Leves}
{139}{}{Fantasma}
{140}{}{Carismático}
{141}{}{Catador}
{142}{}{Explorador}
{143}{}{Filho das Flores}
{144}{}{Desbravador}
{145}{}{Amigos dos Animais}
{146}{}{Batedor}
{147}{}{Mysterious Stranger}
{148}{}{Ranger}
{149}{}{Bolsos Rápidos}
{150}{}{Boa Lábia}
{151}{}{Aprendizado Rápido}
{152}{}{Tag!}
{153}{}{Mutação!}
{154}{}{Vicio em Nuka-Cola}
{155}{}{Vicio em Buffout}
{156}{}{Vicio em Mentats}
{157}{}{Vicio em Psycho}
{158}{}{Vicio em Radaway}
{159}{}{Arma de Longo Alcance}
{160}{}{Arma Precisa}
{161}{}{Arma Penetrante}
{162}{}{Arma que Revida}
{163}{}{Armadura Fortalecida}
{164}{}{Armadura de Combate}
{165}{}{Arma: Alcance de Mira}
{166}{}{Arma: Recarga Rápida}
{167}{}{Arma: Mira Noturna}
{168}{}{Arma: Incendiária}
{169}{}{Armadura Avançada I}
{170}{}{Armadura Avançada II}
{171}{}{Vício em Jet}
{172}{}{Vício em Tragic}
{173}{}{Armadura: Carisma}
{174}{}{Esfolar Gecko}
{175}{}{Armadura Dérmica de Impacto}
{176}{}{Aprim. Dérmico de Assalto}
{177}{}{Implantes de Armadura Phoenix}
{178}{}{Aprimoramento de Assalto Phoenix}
{179}{}{Vacinas de Vault City}
{180}{}{Descarga de Adrenalina}
{181}{}{Natureza Cautelosa}
{182}{}{Compreensão}
{183}{}{Perito em Demolição}
{184}{}{Apostador}
{185}{}{Ganhar Força}
{186}{}{Ganhar Percepção}
{187}{}{Ganhar Resistência}
{188}{}{Ganhar Carisma}
{189}{}{Ganhar Inteligência}
{190}{}{Ganhar Agilidade}
{191}{}{Ganhar Sorte}
{192}{}{Inofensivo}
{193}{}{Aqui e Agora}
{194}{}{Esquiva Corpo-a-Corpo}
{195}{}{Mestre do Kama Sutra}
{196}{}{Farol de Karma}
{197}{}{Passo Leve}
{198}{}{Anatomia Viva}
{199}{}{Personalidade Magnética}
{200}{}{Orador}
{201}{}{Você provavelmente vai notar mais detalhes sobre as pessoas. Atento dará mais informações detalhadas sobre elas quando você realizar um Examinar.}
{202}{}{Você aprendeu as artes secretas do leste ou você apenas soca mais rapido. Em qualquer caso, seus ataques corpo a corpo custam menos 1 PA para realizar.}
{203}{}{Experiencia em combate desarmado deu a você a vantagem no que diz respeito ao dano. Você causa +2 pontos de dano com ataques corpo a corpo e para cada nível deste benefício.}
{204}{}{Pra cada nível do Bonus da Movimentação você obtem 2 PAs livres pra cada turno que só podem ser usados pra movimentação. Em outras palavras, você pode se mover em 2 hexagonos livres pra cada nível deste benefício.}
{205}{}{Seu treinamento em armas de fogo e outras armas de alcance tornou você mais mortal em combate a distancia. Pra cada nível deste benefício, você faz +2 pontos de dano com armas de alcance.}
{206}{}{Este benefício permite a você puxar o gatilho um pouco mais rapido e ainda permanecer tão preciso quanto antes. Cada ataque de arma de alcance custa menos 1 PA para executar.}
{207}{}{É mais provável que você se mova antes dos seus oponentes em combate já que sua sequencia e +2 para cada nível deste Beneficio.}
{208}{}{Com cada nível deste benefício você obtera um bonus de +1 para sua Taxa de Cura. Portanto, você cura mais rapido.}
{209}{}{É mais provável que você faça acertos criticos em combate se você tem este benefício. Cada nível de mais criticos dara a você uma chance de +5% de fazer um acerto critico. Isto é uma coisa boa.}
{210}{}{Com o benefício da visao noturna, você consegue ver melhor no escuro. Cada nível deste benefício reduzira o nível da escuridão total em 10%.}
{211}{}{Você comanda a atenção apenas caminhando em uma sala. A reação inicial de outra pessoa é melhorada em 10% para cada nível deste benefício.}
{212}{}{Você é mais capaz de evitar a radiação e os efeitos ruins que a radiação causa. Cada nível deste benefício melhorara sua resistência a radiação em 10%.}
{213}{}{Quando você é resistente, você toma menos dano. Cada nível deste benefício adicionara +10% a sua resistência ao dano em geral.}
{214}{}{Também conhecido como Mula. Você consegue carregar 50 quilos adicionais de equipamento para cada nível deste benefício.}
{215}{}{O talento de acertar coisas a distancias mais longas. Você tem um bonus de +2 pra cada nível deste benefício para a PE pro propósito de determinar modificadores de alcance. É mais fácil do que nunca matar a longo alcance!}
{216}{}{Com este benefício você agora tem a habilidade de mover-se rapidamente e ainda permanecer quieto. Você pode andar furtivamente e correr ao mesmo tempo. Sem este benefício você automaticamente pararia de andar furtivamente se você corresse.}
{217}{}{Você é um mestre do ar livre. Este benefício confere a habilidade de sobreviver em ambientes hostis. Você obtem um bonus de 20% para homem ao ar livre pro propósito de sobrevivencia pra cada nível deste benefício.}
{218}{}{Você dominou a fundo um aspecto da negociação - a habilidade de comprar mercadorias de longe mais baratas do que uma pessoa normal. Com este benefício você obtem um desconto de 25% quando comprar itens de uma loja ou outro comerciante.}
{219}{}{Cada nível de educado adicionara +2 pontos de técnica quando você ganhar um novo nível de experiência. Este benefício funciona melhor quando comprado cedo na sua aventura.}
{1101}{}{Você tem mais chance de notar detalhes sobre as pessoas. O Atento dará informações mais detalhadas sobre elas quando você Examinar.}
{1102}{}{Você aprendeu as artes secretas do Oriente, ou só soca mais rápido. De qualquer forma, seus ataques Corpo-a-Corpo custam 1 PA a menos.}
{1103}{}{A experiência no combate desarmado te deu vantagem no dano. Você causa +2 pontos de dano com ataques desarmados e corpo-a-corpo por nível desta Vantagem.}
{1104}{}{Para cada nível de Movimento Bônus, você ganha 2 PAs livres por turno que só podem ser usados para movimentação. Ou seja, você move 2 hexágonos grátis por turno por nível desta Vantagem.}
{1105}{}{Seu treino com armas de fogo e outras armas de alcance te tornou mais mortal no combate à distância. Para cada nível desta Vantagem, você causa +2 pontos de dano com armas de alcance.}
{1106}{}{Esta Vantagem permite puxar o gatilho um pouco mais rápido, mantendo a mesma precisão de antes. Cada ataque com arma de alcance custa 1 PA a menos.}
{1107}{}{Você tem mais chance de agir antes dos oponentes no combate, já que sua Sequência é +2 para cada nível desta Vantagem.}
{1108}{}{A cada nível desta Vantagem, você ganha +1 na sua Taxa de Cura. Assim você se cura mais rápido.}
{1109}{}{Você tem mais chance de causar Acertos Críticos no combate com esta Vantagem. Cada nível de Mais Críticos te dá +5% de chance de causar um crítico. Isso é uma coisa boa.}
{1110}{}{Com a Vantagem Visão Noturna, você enxerga melhor no escuro. Cada nível desta Vantagem reduz o nível geral de escuridão em 10%.}
{1111}{}{Você chama atenção só de entrar numa sala. A reação inicial de outra pessoa melhora em 10% para cada nível desta Vantagem.}
{1112}{}{Você evita melhor a radiação e os efeitos ruins que ela causa. Cada nível desta Vantagem melhora sua Resistência a Radiação em 10%.}
{1113}{}{Quando você é durão, sofre menos dano. Cada nível desta Vantagem adiciona +10% à sua resistência geral ao dano.}
{1114}{}{Também conhecido como Mula. Você pode carregar 50 lbs. a mais de equipamento para cada nível desta Vantagem.}
{1115}{}{O talento de acertar coisas a distâncias maiores. Você ganha +2 de bônus, para cada nível desta Vantagem, na Percepção para efeito dos modificadores de distância. Ficou mais fácil que nunca matar a longa distância!}
{1116}{}{Com esta Vantagem, você agora consegue se mover rápido e ainda ficar quieto. Você pode Esgueirar e correr ao mesmo tempo. Sem esta Vantagem, você pararia de Esgueirar automaticamente ao correr.}
{1117}{}{Você é um mestre da vida ao ar livre. Esta Vantagem confere a habilidade de sobreviver em ambientes hostis. Você ganha +20% de bônus em Homem ao Ar Livre para fins de sobrevivência, para cada nível desta Vantagem.}
{1118}{}{Você dominou um aspecto da negociação - a habilidade de comprar bens bem mais baratos que uma pessoa normal. Com esta Vantagem, você ganha 25% de desconto ao comprar itens de uma loja ou outro comerciante.}
{1119}{}{Cada nível de Instruído adiciona +2 pontos de perícia quando você sobe de nível. Esta Vantagem funciona melhor se comprada cedo na sua aventura.}
{1120}{}{A cura de corpos fica mais fácil para você com esta Vantagem. Cada nível cura de 4 a 10 pontos de dano adicionais ao usar as perícias Primeiros Socorros ou Doutor.}
{1121}{}{Você tem o talento de achar dinheiro. Você encontrará dinheiro adicional em encontros aleatórios no deserto.}
{1122}{}{Os acertos críticos que você causa em combate são mais devastadores. Você ganha 20% de bônus na tabela de acertos críticos, quase garantindo que mais dano será causado. Isso não afeta a chance de causar um crítico.}
{1123}{}{Você estudou outros seres humanos, ganhando o conhecimento interno da reação emocional deles a você. Você verá o nível de reação da pessoa com quem fala, durante uma conversa aprofundada.}
{1124}{}{O Matador caminha pela terra! No combate Corpo-a-Corpo, todos os seus acertos são elevados a acertos críticos - causando destruição e caos.}
{1125}{}{Você dominou a arma de fogo como fonte de dor. Com esta Vantagem, qualquer acerto bem-sucedido em combate com arma de alcance vira um crítico se você também passar num teste de Sorte.}
{1126}{}{Ao Esgueirar, se você atingir uma criatura pelas costas, causará o dobro de dano com um ataque Corpo-a-Corpo. Morte Silenciosa é esse tipo de Vantagem.}
{1127}{}{Cada nível de Garoto de Ação (coloque Garota, se quiser) te dá um PA adicional para gastar a cada turno de combate. Você pode usar esses PAs genéricos em qualquer tarefa.}
{1128}{}{Bloqueio Mental é a habilidade de ignorar qualquer interferência mental externa. Você deve ter aprendido esse talento com um guru de passagem, ou numa noite muito longa num bar.}
{1129}{}{A cada nível desta Vantagem, você ganha 4 Pontos de Vida adicionais. Pode não parecer muito, mas todo pouquinho ajuda.}
{1130}{}{Você tem menos chance de ser atingido em combate com esta Vantagem. Cada nível adiciona +5% à sua Classe de Armadura, além do bônus de CA de qualquer armadura vestida.}
{1131}{}{Nham! Tem gosto de frango. Você ganhou imunidade a veneno, resultando em +25% na sua Resistência a Veneno.}
{1132}{}{Esta Vantagem te dá um bônus único de +20% nas perícias Reparo e Ciência. Uma viradinha de estudo na noite nunca fez mal a ninguém, especialmente a você.}
{1133}{}{A Vantagem Médico te dá um bônus único de +20% nas perícias Primeiros Socorros e Doutor. Perícias de cura são uma coisa boa.}
{1134}{}{Desculpe, por razões técnicas, esta vantagem está desativada.}
{1135}{}{Desculpe, por razões técnicas, esta vantagem está desativada.}
{1136}{}{Cada nível da Vantagem Força no Arremesso! dá às suas armas de arremesso +2 de Força, apenas para fins de determinar o alcance.}
{1137}{}{Personagens que fazem parte da sua equipe ficam destacados em verde no combate em vez de vermelho, se você tiver esta Vantagem. Personagens destacados em vermelho ainda podem não ser hostis a você.}
{1138}{}{Você é bem mais habilidoso em Roubar que o ladrão comum. Você pode Roubar como os melhores, pois com esta Vantagem você ignora os modificadores de tamanho e direção ao roubar de uma pessoa.}
{1139}{}{Quando o sol se põe, ou quando você está numa área mal iluminada, você se move como um Fantasma com esta Vantagem. Sua perícia Furtivo aumenta +20% em condições de escuridão.}
{1140}{}{Sua reputação é sempre positiva para as pessoas. Sem esta Vantagem, uma grande reputação negativa teria um efeito ruim sobre pessoas de bom coração. Funciona com boa reputação e pessoas más também.}
{1141}{}{Você encontra mais munição que o sobrevivente pós-holocausto comum. Esta Vantagem dobra a quantidade de munição encontrada em encontros aleatórios.}
{1142}{}{A marca do Explorador é buscar lugares novos e interessantes. Com esta Vantagem, você tem mais chance de encontrar lugares ou povos especiais.}
{1143}{}{Com esta Vantagem, você tem bem menos chance de desejar drogas (50% menos, na verdade) e sofre metade do tempo de abstinência de uma pessoa normal.}
{1144}{}{O Desbravador acha melhor a rota mais curta. Com esta Vantagem, seu tempo de viagem no Mapa-Múndi é reduzido em 25% para cada nível.}
{1145}{}{Os animais não atacarão um dos seus amigos, a menos que o animal seja ameaçado ou atacado primeiro. O que exatamente é um animal neste mundo é assunto para debate.}
{1146}{}{Você melhorou sua capacidade de enxergar locais distantes, aumentando o tamanho das explorações no Mapa-Múndi em um quadrado em cada direção.}
{1147}{}{Com esta Vantagem, você chamou a atenção de um Estranho Misterioso, que aparecerá para te ajudar de tempos em tempos. Se seu aliado for perdido em combate, não espere que ele ou ela seja substituído.}
{1148}{}{Você evita melhor a atenção indesejada ao viajar pelo ermo. Sua chance de um encontro aleatório hostil é reduzida por cada nível desta Vantagem.}
{1149}{}{Você aprendeu a guardar melhor seu equipamento junto ao corpo. Com cada nível desta Vantagem, o custo em PA para acessar o Inventário em combate é reduzido em um.}
{1150}{}{Um Bom de Papo aprendeu a aumentar suas opções no diálogo, sem entender do que está falando. Cada nível desta Vantagem aumenta sua IN em um, apenas para fins de diálogo.}
{1151}{}{Você é de fato um Aprendiz Veloz com esta Vantagem, pois cada nível te dá +5% de bônus adicional sempre que você ganha pontos de experiência. Melhor comprada em nível baixo.}
{1152}{}{Suas perícias melhoraram a ponto de você poder escolher uma perícia Marcada adicional, aumentando essa perícia em +20% imediatamente e 2% por ponto de perícia gasto.}
{1153}{}{A radiação do ermo te mudou! Uma das suas Características sofreu mutação em outra coisa...}
{1154}{}{Você deseja outra Nuka-Cola.}
{1155}{}{Você está com tremores.}
{1156}{}{Você se sente grogue.}
{1157}{}{Você se sente tonto.}
{1158}{}{Você se sente enjoado.}
{1159}{}{Arma: Longo Alcance}
{1160}{}{Arma: Precisa}
{1161}{}{Arma: Perfurante}
{1162}{}{Arma: Empurrão}
{1163}{}{Armadura Motorizada}
{1164}{}{Armadura de Combate}
{1165}{}{Arma: Alcance de Mira}
{1166}{}{Arma: Recarga Rápida}
{1167}{}{Arma: Mira Noturna}
{1168}{}{Arma: Incendiária}
{1169}{}{Armadura Avançada I}
{1170}{}{Armadura Avançada II}
{1171}{}{Tudo está se movendo tão devagar... você precisa de mais Jet, AGORA!}
{1172}{}{Você sente um desejo ardente de abrir outra caixa de cartas Tragic.}
{1173}{}{Armadura: Carisma}
{1174}{}{Você tem o conhecimento de como esfolar geckos corretamente para obter os couros.}
{1175}{}{Você tem proteção inerente contra ataques físicos.}
{1176}{}{Você tem proteção inerente extra contra ataques físicos.}
{1177}{}{Você tem proteção inerente contra ataques de energia.}
{1178}{}{Você tem proteção inerente extra contra ataques de energia.}
{1179}{}{Você ganhou +10% de resistência tanto a veneno quanto a radiação.}
{1180}{}{Com esta Vantagem, você ganha +1 de Força quando cai abaixo de 1/2 dos seus pontos de vida máximos.}
{1181}{}{Você fica mais alerta ao ar livre e os inimigos têm menos chance de te surpreender. Com esta Vantagem, você ganha +3 de percepção em encontros aleatórios ao determinar o posicionamento.}
{1182}{}{Você presta muito mais atenção aos pequenos detalhes ao ler. Você ganha 50% mais pontos de perícia ao ler livros.}
{1183}{}{Você é um perito na fina arte de manusear explosivos. Eles sempre detonam na hora certa, além de causar dano extra.}
{1184}{}{Você aposta como os melhores. Você ganha +20% na sua perícia de jogatina.}
{1185}{}{Com esta Vantagem você ganha +1 de Força.}
{1186}{}{Com esta Vantagem você ganha +1 de Percepção.}
{1187}{}{Com esta Vantagem você ganha +1 de Resistência.}
{1188}{}{Com esta Vantagem você ganha +1 de Carisma.}
{1189}{}{Com esta Vantagem você ganha +1 de Inteligência.}
{1190}{}{Com esta Vantagem você ganha +1 de Agilidade.}
{1191}{}{Com esta Vantagem você ganha +1 de Sorte.}
{1192}{}{Seu jeito inocente facilita um pouco roubar das pessoas. Você ganha 20% na sua perícia Roubar.}
{1193}{}{Com esta Vantagem você ganha imediatamente um nível de experiência.}
{1194}{}{Se ambos os espaços de item estiverem vazios, cada ponto de ação não usado te dá +2 em vez de +1 na classe de armadura no fim do seu turno, mais 1/12 da sua perícia desarmado.}
{1195}{}{Quando o assunto é dar prazer sexual, você escreveu o livro.}
{1196}{}{Seu Karma brilha duas vezes mais forte. Bom ou ruim, seu Karma é dobrado para qualquer tipo de reação ou modificador.}
{1197}{}{Você é ágil, sortudo e sempre cuidadoso. Esta vantagem reduz pela metade suas chances de acionar uma armadilha.}
{1198}{}{Você entende melhor as criaturas vivas e seus pontos fortes e fracos. Você ganha um bônus único de +10% em Doutor e causa +5 de dano por ataque a criaturas vivas.}
{1199}{}{Você ganha 1 espaço extra no seu limite de companheiros, mas não esqueça que mais de 5 é sempre multidão.}
{1200}{}{Ser um Orador significa que você tem um bônus único de +20% nas perícias Discurso e Negociação. Da boca das crianças e tudo mais.}
{1201}{}{Você é eficiente em organizar seu inventário em geral. Isso facilita bastante carregar aquele extra que você sempre precisou.}
{1202}{}{Você causa dano extra com armas incendiárias, e os inimigos sempre parecem morrer da forma mais dolorosa e flamejante.}
{1203}{}{Você é rápido em se recuperar de uma queda.}
{1204}{}{Desculpe, por razões técnicas, esta vantagem está desativada.}
{1205}{}{Você tem bem menos chance de ser derrubado em combate.}
{1206}{}{Um Mestre Ladrão tem um bônus único de +10% nas perícias Furtivo, Gazua, Roubar e Armadilhas. Roube dos ricos e dê para você.}
{1207}{}{Você pode empunhar armas bem maiores do que o normalmente permitido. Você ganha +3 de força para fins de testes de Força ao tentar empunhar armas.}
{1208}{}{Você recebeu o treinamento médico de Vault City.}
{1209}{}{Seus pontos de vida foram um pouco melhorados por embriaguez repetida.}
{1210}{}{Seus pontos de vida foram um pouco mais melhorados por embriaguez repetida.}
{1211}{}{Seus pontos de vida foram levemente reduzidos por embriaguez repetida.}
{1212}{}{Seus pontos de vida foram levemente reduzidos por embriaguez repetida.}
{1213}{}{Seus pontos de vida foram um pouco melhorados pelo uso repetido do autodoc.}
{1214}{}{Seus pontos de vida foram um pouco mais melhorados pelo uso repetido do autodoc.}
{1215}{}{Seus pontos de vida foram levemente reduzidos pelo uso repetido do autodoc.}
{1216}{}{Seus pontos de vida foram levemente reduzidos pelo uso repetido do autodoc.}
{1217}{}{Você sabe enrolar conversa como os melhores.}
{1218}{}{Arma: Nocaute Aprimorado}
{1219}{}{A coisa boa é que todos ao seu redor têm mais falhas críticas em combate. A coisa ruim é que você também!}
{220}{}{A cura dos corpos vem mais fácil até você com este benefício. Cada nível adicionara de 2-5 mais pontos de dano curados quando usar as técnicas Primeiros Socorros ou Doutor.}
{221}{}{Você tem o talento de achar dinheiro. Você achara dinheiro adicional em encontros aleatórios no deserto.}
{222}{}{Os acertos criticos que você faz em combate são mais devastadores. Você ganha um bonus de 20% na tabela de acertos criticos, quase garantindo que mais dano será feito. Isto não afeta a chance de causar um acerto critico.}
{223}{}{Você estudou outros seres humanos, dando a você conhecimento interior da reação emocional deles a você. Você verá o nível da reação da pessoa com quem você esta falando quando envolvido em uma profunda conversacão.}
{224}{}{O assassino caminha pela terra!  Em combate corpo a corpo, todos os seus golpes são elevados para golpes criticos - causando destruição e confusão.}
{225}{}{Você dominou a fundo a arma de fogo como uma fonte de dor. Com este benefício, qualquer acerto bem sucedido em combate com uma arma de alcance será elevado para um acerto critico se você tambem fizer uma jogada de sorte.}
{226}{}{Enquanto furtivo, se você acertar um animal nas costas, você causara o dobro do dano usando um ataque corpo a corpo. Morte silenciosa é esse tipo de benefício.}
{227}{}{Cada nível do garoto ação (insira garota se você desejar) dara a você um PA adicional para gastar em cada turno de combate. Você pode usar estes PAs genericos em qualquer tarefa.}
{228}{}{Bloqueio mental é a habilidade de ignorar qualquer interferência mental exterior. Você deve ter aprendido este talento de um guru que passava ou de uma noite realmente tardia em um bar.}
{229}{}{Com cada nível deste benefício, você ganha 4 pontos de dano adicionais. Isto pode não parece muito, mas cada pouquinho ajuda.}
{230}{}{É menos provável que você seja atingido em combate se você tem este benefício. Cada nível adicionara +5% a sua classe de armadura alem do bonus para a CA de qualquer armadura usada.}
{231}{}{Yum!  O gosto parece de frango. Você ganhou uma imunidade a veneno, resultando em +25% a sua Resistência a Veneno.}
{232}{}{Este benefício dara a você um bonus único de +20% para as técnicas de reparo e ciência. Um pouco de estudo tarde da noite nunca machucou ninguém, especialmente você.}
{233}{}{O benefício medico dara a você um bonus único de +20% para as técnicas de primeiros socorros e doutor. Tecnicas de cura são uma coisa boa.}
{234}{}{Um ladrão mestre tem um bonus único de +10% para as técnicas furtivo, gazua, roubar e armadilha. Roube dos ricos e de para você.}
{235}{}{Ser um orador significa que você tem um bonus único de 20% para as técnicas de discurso e negociação. Da boca das gatas e tudo isso.}
{236}{}{Cada nível do benefício Arremesso! dara as suas armas de arremesso um +2 de porca adicional para o propósito de determinar só o alcance.}
{237}{}{Personagens que são parte do seu time são destacados em verde no combate em vez de vermelho, se você tem este benefício. Personagens destacados em vermelho podem ainda ser não-hostis em relacao a você.}
{238}{}{Você é muito mais adepto em roubar do que o trapaceiro normal. Você pode roubar com o melhor deles, porque com este benefício, você ignora os modificadores de tamanho e enfrentamento quando rouba de uma pessoa.}
{239}{}{Quando o sol desce ou você esta em uma area pobremente iluminada, você se move como um fantasma com este benefício. Sua técnica furtiva é melhorada em 20% durante as condições de escuridão.}
{240}{}{Sua reputação é sempre positiva para as pessoas. Sem este benefício, uma grande reputação negativa teria um efeito ruim nas pessoas de boa natureza. Funciona com uma boa reputação e pessoas ruins tambem.}
{241}{}{Você consegue achar mais munição do que o sobrevivente pos-holocausto normal. Este benefício dobrara a quantia de munição achada em encontros aleatórios.}
{242}{}{A marca do explorador e procurar locais novos e interessantes. Com este benefício, você tem uma chance maior de achar lugares ou pessoas especiais.}
{243}{}{Com este benefício, é muito menos provável que você fique viciado em chems (50% menos provável, realmente), e você sofre pela metade do tempo da retirada de uma pessoa normal.}
{244}{}{O descobridor de caminhos é mais capaz de achar a rota mais curta. Com este benefício, seu tempo de viagem no mapa mundi e reduzido em 25% para cada nível.}
{245}{}{Animais não atacarão um de seus amigos, a menos que o animal seja ameacado ou atacado primeiro. Exatamente o que um animal é neste mundo esta aberto a debate.}
{246}{}{Você melhorou sua habilidade de ver locais distantes, aumentando o tamanho das explorações no mapa mundi por um quadrado em cada direção.}
{247}{}{Com este benefício, você ganhou a atenção de um estranho misterioso, que aparecerá pra ajudar você de tempo em tempo. Se seu aliado é morto em combate, não espere que ele ou ela seja substituido.}
{248}{}{Você e mais capaz de evitar atenção não desejada enquanto viaja atraves da terra devastada. Sua chance de um encontro hostil aleatorio e reduzida para cada nível deste benefício.}
{249}{}{Você aprendeu a armazenar melhor seu equipamento na sua pessoa. Com cada nível deste benefício, o custo dos PA para acessar o inventario e reduzido em um.}
{250}{}{Um habil conversador aprendeu a aumentar suas opções no dialogo, sem entender do que eles estão falando. Cada nível deste benefício aumentara sua IN em um, só para o propósito de dialogo.}
{251}{}{Você é de fato um aprendiz veloz com este benefício, como cada nível dara a você um bonus de 5% adicional sempre que você ganha pontos de experiência. Melhor comprada num nível inicial.}
{252}{}{Suas técnicas melhoraram ao ponto onde você pode escolher uma técnica de identificação, aumentando essa técnica em +20% imediatamente e 2% por ponto de técnica gasto.}
{253}{}{A radiação da terra devastada mudou você!  Um dos seus traços se transformou em algo mais...}
{254}{}{Você almeja outra Nuka-Cola.}
{255}{}{Você tem as tremedeiras.}
{256}{}{Você se sente grogue.}
{257}{}{Você se sente de cabeca leve.}
{258}{}{Você se sente nauseado.}
{259}{}{Arma de Longo Alcance}
{260}{}{Arma Precisa}
{261}{}{Arma Penetrante}
{262}{}{Arma que Revida}
{263}{}{Armadura Fortalecida}
{264}{}{Armadura de Combate}
