{100}{}{Foguete}
{200}{}{Bola de Plasma}
{300}{}{Explosão}
{400}{}{Sangue}
{500}{}{Hex no-trans}
{501}{}{}
{600}{}{faca}
{700}{}{lança}
{800}{}{Explosão de PEM}
{900}{}{Rajada de Laser}
{1000}{}{Rajada de Plasma}
{1100}{}{Explosão}
{1200}{}{Bloqueador de Rolamento}
{1300}{}{Raio de Eletricidade}
{1400}{}{Explosão}
{1500}{}{Explosão}
{1600}{}{Grade de Saida}
{1700}{}{Grade de Saida}
{1800}{}{Grade de Saida}
{1900}{}{Grade de Saida}
{2000}{}{Grade de Saida}
{2100}{}{Grade de Saida}
{2200}{}{Grade de Saida}
{2300}{}{Grade de Saida}
{2400}{}{Sinal Luminoso}
{2500}{}{Granada}
{2600}{}{Rocha}
{2700}{}{Explosão}
{2800}{}{Explosão}
{2900}{}{Explosão}
{3000}{}{Coquetel Molotov}
{3100}{}{Grade de Saida}
{3200}{}{Grade de Saida}
{3300}{}{Grade de Saida}
{3400}{}{Grade de Saida}
{3500}{}{Grade de Saida}
{3600}{}{Grade de Saida}
{3700}{}{Grade de Saida}
{3800}{}{Grade de Saida}
{3900}{}{Grade de Saida}
{4000}{}{Grade de Saida}
{4100}{}{Grade de Saida}
{4200}{}{Grade de Saida}
{4300}{}{Grade de Saida}
{4400}{}{Grade de Saida}
{4500}{}{Grade de Saida}
{4600}{}{Grade de Saida}
{4700}{}{Foguete de Robô}
{4701}{}{}
{4800}{}{Ka-Pow!}
{4801}{}{}
{4900}{}{Espinho de Planta}
{4901}{}{}
{5000}{}{Bola de Plasma Dupla}
{5100}{}{chão}
