{100}{}{Armadura de Couro}
{101}{}{Seu traje basico todo de couro. Finamente feita do couro curtido do brahmin.}
{200}{}{Armadura de Metal}
{201}{}{Placas de metal polidas, asperamente formando um traje de armadura.}
{300}{}{Armadura Fortalecida}
{301}{}{Um traje de armadura de tecnologia avancada auto-contida. Movida por um reator de micro-fusao, com combustivel o bastante para durar cem anos.}
{400}{}{Faca}
{401}{}{Uma arma de cortar e esfaquear com lamina afiada. Minimo de FORCA: 2.}
{500}{}{Clava}
{501}{}{Um bastao militar ou policial. Madeira pesada. Minimo de FORCA: 3.}
{600}{}{Marreta}
{601}{}{Um grande martelo com grande cabo. Muito popular com a turma muscular. Minimo de FORCA: 6.}
{700}{}{Lanca}
{701}{}{Uma arma longa com ponta em forma de lamina. O cabo e de madeira é a ponta e trabalhada em aco. Minimo de FORCA: 4.}
{800}{}{Pistola 10mm}
{801}{}{Uma pistola Colt 6520 10mm auto-carregante. Cada puxada do gatilho recarregara a arma de fogo até que o carregador esteja vazio. Tiro único apenas, usando a poderosa capsula de 10mm. Minimo de FORCA: 3.}
{900}{}{SMG 10mm}
{901}{}{Sub-metralhadora H&K MP9(Variante da 10mm). Uma SMG de tamanho medio, capaz de tiro único e modo rajada. Minimo de FORCA: 4.}
{1000}{}{Rifle de Caca}
{1001}{}{Um rifle semi-automatico Colt Rangemaster de calibre .223. Tiro único apenas. Minimo de FORCA: 5.}
{1100}{}{Flamejador}
{1101}{}{Um lança-chama Flambe modelo 450, variacao do varmiter. Dispara um curto spray de liquido extremamente quente e inflamavel. Requer combustivel especializado para funcionar apropriadamente. Minimo de FORCA: 6.}
{1200}{}{Minigun}
{1201}{}{Uma minigun Rockwell CZ53 Personal. Uma arma em cadeia com multi-canos disparando munição de 5mm a aproximadamente 60,000 RPM. Minimo de FORCA: 7.}
{1300}{}{Lancador de Foguetes}
{1301}{}{Um lancador de foguetes Rockwell BigBazooka. Com o gatilho de 3 lb. deluxe. Dispara PA ou Foguetes Explosivos. Minimo de FORCA: 6.}
{1400}{}{Foguete Explosivo}
{1401}{}{Um foguete com uma grande ogiva explosiva.}
{1500}{}{Rifle de Plasma}
{1501}{}{Um Rifle de Plasma Winchester Modelo P94. Uma arma de energia de grade industrial, disparando raios de plasma super aquecidos por um barril super condutor. Movido por Celulas de Micro Fusao. Minimo de FORCA: 6.}
{1600}{}{Pistola Laser}
{1601}{}{Uma Pistola Laser Wattz 1000. Modelo civil, então a voltagem e menor do que as versoes policiais ou militares. Usa pequenas celulas de energia. Minimo de FORCA: 3.}
{1700}{}{Armadura de Combate}
{1701}{}{Armadura de alta tecnologia feita de polimeros defensivos avancados.}
{1800}{}{Desert Eagle .44}
{1801}{}{Uma antiga pistola magnum Desert Eagle .44. Interesse nos filmes do final do seculo 20 tornaram esta uma das mais populares armas de mao de todos os tempos. Minimo de FORCA: 4.}
{1900}{}{Rocha}
{1901}{}{É uma rocha. O modelo Granito-Inc. é uma versao melhorada. Minimo de FORCA: 1.}
{2000}{}{Pe de Cabra}
{2001}{}{Um pedaço de metal muito solido e pesado, especialmente designado para exercer a ação de alavanca. Ou ferir cabecas. Minimo de FORCA: 5.}
{2100}{}{Soco Ingles}
{2101}{}{Punho de soco ingles endurecido que é realmente feito de aco. Eles protegem sua mao e fazem mais dano em combate desarmado. Minimo de FORCA: 1.}
{2200}{}{Pistola 14mm}
{2201}{}{Uma Pistola Automatica Sig-Sauer 14mm. Grande, arma de mao de tiro único. Excelente craftmanship. Minimo de FORCA: 4.}
{2300}{}{Rifle de Ataque}
{2301}{}{Um Rifle de Ataque AK-112 5mm. Um velho modelo militar, fora de uso por volta do tempo da guerra. Pode disparar tiro único ou rajada, usando as capsulas de alta velocidade de 5mm. Minimo de FORCA: 5.}
{2400}{}{Pistola de Plasma}
{2401}{}{Pistola de Plasma Glock 86. Desenhada pela Gaston Glock AI. Dispara um pequeno raio de plasma super aquecido. Movida por uma pequena celula de energia. Minimo de FORCA: 4.}
{2500}{}{Granada (Fragmentacao)}
{2501}{}{Uma granada de fragmentacao generica. Contem uma pequena quantia de altos explosivos, o recipiente em si formando a maioria dos fragmentos de dano. Explode no contato. Minimo de FORCA: 3.}
{2600}{}{Granada (Plasma)}
{2601}{}{Uma unidade de entrega de plasma selada magneticamente com explosivos detonantes. Cria uma explosao de plasma super aquecido no contato. Minimo de FORCA: 4.}
{2700}{}{Granada (Pulso)}
{2701}{}{Uma granada de pulso eletro-magnetico, gerando um intenso campo magnetico na detonacao. Não afeta criaturas biologicas. Funde-se com o contato. Minimo de FORCA: 4.}
{2800}{}{Laser Gatling}
{2801}{}{Uma Laser Gatling H&K L30. Designada especificamente para uso militar, estas estavam no estagio prototipo no comeco da guerra. Multiplos canos permitem disparos mais longos antes de super aquecer. Movida por Celulas de Micro Fusao. Minimo de FORCA: 6.}
{2900}{}{10mm JHP}
{2901}{}{Municao. Calibre: 10mm, pontos-de-cavidade revestidos}
{3000}{}{10mm AP}
{3001}{}{Municao. Calibre: 10mm, penetrante de armadura.}
{3100}{}{Magnum JHP .44}
{3101}{}{Uma caixa de munição, calibre da magnum .44, pontos-de-cavidade.}
{3200}{}{Combustivel de Lança-Chamas}
{3201}{}{Um cilindro contendo um combustivel liquido extremamente inflamavel para lança-chamas.}
{3300}{}{14mm PA}
{3301}{}{Municao de grande calibre. 14mm penetrante de armadura.}
{3400}{}{.223 FMJ}
{3401}{}{Uma caixa de munição, calibre .223, Revestimento Completo de Metal.}
{3500}{}{5mm JHP}
{3501}{}{Uma caixa de munição de peso leve, pequena. Calibre: 5mm, ponto-de-cavidade revestido.}
{3600}{}{5mm AP}
{3601}{}{Uma caixa de munição de pequeno calibre. 5mm, penetrante de armadura.}
{3700}{}{Foguete PA}
{3701}{}{Um casco de foguete, com um explosivo mais pequeno, mas designada para penetrar o revestimento da armadura.}
{3800}{}{Pequena Celula de Energia}
{3801}{}{Uma pequena, auto-contida unidade de armazenamento de energia.}
{3900}{}{Celula de Micro Fusao}
{3901}{}{Uma unidade de producao de energia de tamanho medio. Usina de fusao auto-contida.}
{4000}{}{Stimpak}
{4001}{}{Um chem de cura. Quando injetado, o chem fornece cura imediata de pequenos ferimentos.}
{4100}{}{Tampinhas de Garrafa}
{4101}{}{Este saco segura suas tampinhas de garrafa.}
{4200}{}{Geladeira}
{4201}{}{Um refrigerador. Sem o liquido refrigerador.}
{4300}{}{Bau de Gelo}
{4301}{}{Um bau de gelo em estilo-antigo. As dobradicas estão em boa condicao de funcionamento.}
{4400}{}{Bau de Gelo}
{4401}{}{Um bau de gelo em estilo-antigo. As dobradicas estão em boa condicao de funcionamento.}
{4500}{}{Faca de Arremesso}
{4501}{}{Uma faca, balanceada especificamente para arremesso. Feita de titanio e afiada com laser. Minimo de FORCA: 3.}
{4600}{}{Saco}
{4601}{}{Um saco de tamanho medio. Feito de pelos de brahmin trancados.}
{4700}{}{Kit de Primeiros Socorros}
{4701}{}{Um pequeno kit recipiente de equipamento medico basico. Bandagens, gaze para enrolar, spray, anti-septico e mais.}
{4800}{}{RadAway}
{4801}{}{Uma solucao quimica que se liga com as particulas da radiação e transpoe elas atraves do seu sistema. Leva tempo pra funcionar.}
{4900}{}{Antidoto}
{4901}{}{Um garrafa contendo um antidoto feito em casa para veneno. Um liquido leitoso com pedacos flutuantes de carne de radscorpion.}
{5000}{}{Item Reservado}
{5001}{}{Este e um item reservado. NÃO USE.}
{5100}{}{Dinamite}
{5101}{}{Um explosivo forte, consistindo de nitroglicerina misturada com a substancia absorvente kiselguhr. Inclui um timer.}
{5200}{}{Contador Geiger}
{5201}{}{Um Contador Geiger da Wattz Electronics modelo C-Radz. Detecta a presença e força dos campos da radiação.}
{5300}{}{Mentats}
{5301}{}{Uma caixa de pilulas chem alteradoras da mente. Aumenta as funções relacionadas a memória e acelera outros processos mentais. Altamente viciante.}
{5400}{}{Garoto Disfarce}
{5401}{}{Um dispositivo RobCo Garoto Disfarce 3001 dispositovo de disfarce pessoal. Gera um campo modulante que transmite a luz refletida de um lado de um objeto para o outro.}
{5500}{}{Chip de Água}
{5501}{}{Um chip do sistema de computadores de controle da purificacao da água. Parece surpreendentemente com o chip que sua Vault precisa.}
{5600}{}{Dog tags}
{5601}{}{Um conjunto de Dog tags militares. O nome Darkwater esta legivel mas não muito mais esta.}
{5700}{}{Microfone Miniatura}
{5701}{}{Um microfone miniatura e dispositivo de transmissao.}
{5800}{}{Fita}
{5801}{}{Uma fita holodisco da Wattz Electronics. Esta fita em particular parece estar em condicao muito pobre.}
{5900}{}{Sensor de Movimento}
{5901}{}{Um sensor de movimento da Wattz Electronics modelo C-U. Detecta o movimento de material biologico a uma distancia de metros usando um dispositivo de radar ajustado.}
{6000}{}{Estante para Livros}
{6001}{}{Uma estante para livros de madeira}
{6100}{}{Estante para Livros}
{6101}{}{Uma estante para livros de madeira}
{6200}{}{Estante para Livros}
{6201}{}{Uma estante para livros de madeira}
{6300}{}{Estante para Livros}
{6301}{}{Uma estante para livros de madeira}
{6400}{}{Estante para Livros}
{6401}{}{Uma estante para livros de madeira}
{6500}{}{Estante para Livros}
{6501}{}{Uma estante para livros de madeira}
{6600}{}{Escrivaninha}
{6601}{}{Uma escrivaninha de madeira.}
{6700}{}{Escrivaninha}
{6701}{}{Uma escrivaninha de madeira.}
{6800}{}{Penteadeira}
{6801}{}{Uma penteadeira de madeira.}
{6900}{}{Penteadeira}
{6901}{}{Uma penteadeira de madeira.}
{7000}{}{Penteadeira}
{7001}{}{Uma penteadeira de madeira.}
{7100}{}{Fruta}
{7101}{}{Um estranho pedaço de fruta. Sem conservantes e nenhum colorimento adicional na comida adicionados.}
{7200}{}{Pasta}
{7201}{}{Uma pasta, com um rotulo Made-in-the-USA. Couro. Condicao boa, mas a tranca da combinação esta quebrada.}
{7300}{}{Grande Livro da Ciencia}
{7301}{}{Um conjunto de livros, contendo informação sobre diferentes campos cientificos.}
{7400}{}{Jaqueta de Couro}
{7401}{}{Uma jaqueta de couro pesada e preta.}
{7500}{}{Ferramenta}
{7501}{}{Um super conjunto de ferramentas, contendo varias ferramentas uteis.}
{7600}{}{Eletronicos Deans}
{7601}{}{Um livro de estudo no campo dos eletronicos. Uma nota na capa diz que é para o "jovem eletricista emergente em todo mundo!"}
{7700}{}{Gazua Eletronica}
{7701}{}{Uma gazua eletronica da Wattz Electronics Micromanipulator FingerStuff. Para derrotar trancas eletronicas e dispositivos de seguranca.}
{7800}{}{Pintura Desfocada}
{7801}{}{Uma imagem de um cantor. Obviamente muito antiga. A imagem tem uma camada de feltro que ainda esta em boa condicao.}
{7900}{}{Sinal Luminoso}
{7901}{}{Um sinal luminoso. Cria luz por um curto periodo de tempo. O papel esta um pouco usado, mas de outro modo esta em boa condicao. Torca o topo para ativa-lo.}
{8000}{}{Livro de Primeiros Socorros}
{8001}{}{Um livro de estudo sobre os conceitos e uso pratico das técnicas de primeiros socorros.}
{8100}{}{Iguana-no-espeto}
{8101}{}{Uma iguana cozinhada, assada na sua propria pele.}
{8200}{}{Chave}
{8201}{}{Uma chave. Uma chave abrira um tranca particular.}
{8300}{}{Conjunto de Chaves}
{8301}{}{Multiplas chaves.}
{8400}{}{Gazuas}
{8401}{}{Um conjunto de ferramentas de serralheiro. Inclui todos os pições necessarios e chaves de tensao para abrir trancas de fechaduras e pinos convencionais.}
{8500}{}{Explosivos Plasticos}
{8501}{}{Um chunk de Cordex, uma marca milita de explosivos plasticos. Altamente estaveis, muito destrutivos. Inclui um timer.}
{8600}{}{Manual do Escoteiro}
{8601}{}{Um livro sobre os metodos e ideais do escotismo. Informacao muito pratica a respeito da vida fora de casa.}
{8700}{}{Buffout}
{8701}{}{Esteroides altamente avancados. Enquanto em efeito, eles aumentam a força e os reflexos. Muito viciante.}
{8800}{}{Relogio de Pulso}
{8801}{}{Um relogio de pulso caro. Não funciona realmente, mas ainda parece bacana.}
{8900}{}{Motor}
{8901}{}{Um motor eletrico de 40-hps.}
{9000}{}{Mochila}
{9001}{}{Uma mochila bascio, com correias para carregar opcionais.}
{9100}{}{Sacola do Doutor}
{9101}{}{Esta sacola preta contem instrumentos e chems usados pelos doutores na aplicação do seu oficio.}
{9200}{}{Cauda de Escorpiao}
{9201}{}{A cauda cortada de um radscorpion.}
{9300}{}{Sacola}
{9301}{}{Uma sacola de tamanho medio. Feita de pelos de brahmin tracados.}
{9400}{}{Espingarda}
{9401}{}{Uma espingarda Winchester Widowmaker de cano duplo calibre 12. Cano curto, com cabo de mogno. Minimo de FORCA: 4.}
{9500}{}{Capsulas de Espingarda Calibre 12}
{9501}{}{Municao de espingarda. Nesta munição em particular esta marcado: "capsulas de calibre 12, não para o uso de crianças com idade inferior a 3."}
{9600}{}{Chave de Passe Vermelha}
{9601}{}{Uma chave de seguranca eletronica, codificada com a cor vermelha.}
{9700}{}{Chave de Passe Azul}
{9701}{}{Uma chave de seguranca eletronica, codificada com a cor azul.}
{9800}{}{Lixo}
{9801}{}{Uma pilha de partes de lixo. Um pouco de tudo.}
{9900}{}{Medalhao de Ouro}
{9901}{}{Um valioso medalhao de ouro.}
{10000}{}{Rádio}
{10001}{}{Um radio comunicador modelo 2043B, das pessoas boas da Wattz Electronics. De confianca, maltratado pelo tempo e camuflado. Com a interface opcional RS-121.}
{10100}{}{Isqueiro}
{10101}{}{Um isqueiro prata com butano, em boa condicao.}
{10200}{}{Armas e Balas}
{10201}{}{Um pasquim sobre armas. Uma revista devotada ao uso pratico de armas de fogo é a analise ocasional tendenciosa.}
{10300}{}{Iguana-no-espeto}
{10301}{}{Um pouco de carne chamuscada e vegetais num espeto para cozimento.}
{10400}{}{Gravador de Fita}
{10401}{}{Um gravador de fita Toque-Para-Mim da Wattz Electronics. Toca e grava as fitas padrao de 30 minutos de alta densidade Grave-Uma-Vez.}
{10500}{}{Chave}
{10501}{}{Uma chave especial de algum tipo.}
{10600}{}{Nuka-Cola}
{10601}{}{Uma garrafa de Nuka-Cola, a bebida leve saborosa do mundo pos-nuclear. Quente e sem gas.}
{10700}{}{Ossos}
{10701}{}{Uma colecao de ossos estranhos.}
{10800}{}{Ossos}
{10801}{}{Uma colecao de ossos estranhos.}
{10900}{}{Rad-X}
{10901}{}{Chems anti-radiação para serem tomados antes da exposicao. Não há efeitos colaterais conhecidos.}
{11000}{}{Psycho}
{11001}{}{Um sistema de entrega único com quimicos estranhos e desconhecidos de origem provavelmente militar. É esperado que aumente o potencial de combate de um soldado.}
{11100}{}{Magnum FMJ .44}
{11101}{}{Uma caixa de munição, .44 calibre da magnum, revestimento completo de metal.}
{11200}{}{Urna}
{11201}{}{Uma bela urna dourada com o nome "Harriet" inscrito na frente e cinzas dentro.}
{11300}{}{Mantos}
{11301}{}{Mantos das Crianças da Catedral.}
{11400}{}{Mao do Tangler}
{11401}{}{Um manipulador cibernetico, no contorno e forma de uma mao. Estragado devido a natureza malfeita do processo de remoção.}
{11500}{}{Super Marreta}
{11501}{}{Uma super marreta, fabricada pela Brotherhood of Steel usando as melhores tecnologias para armas disponiveis. Inclui um dispositivo de armazenagem de energia cinetica para aumentar o ricochete. Minimo de FORCA: 5.}
{11600}{}{Ripper}
{11601}{}{Um vibroblade Ripper(tm). Movida por uma pequena celula de energia, a espada em cadeias rasga e corta o seu alvo. Minimo de FORCA: 4.}
{11700}{}{Flor}
{11701}{}{Uma linda flor.}
{11800}{}{Rifle Laser}
{11801}{}{Um Rifle Laser Wattz 2000. Usa celulas de micro fusao para lasers mais poderosos e um cano extendido para alcance adicional. Minimo de FORCA: 6.}
{11900}{}{Colar}
{11901}{}{Um colar de aparencia cara feito de prata, ouro e diamantes comprimidos.}
{12000}{}{Alien Blaster}
{12001}{}{Uma estranha arma de origem obviamente alienigena. Todavia, parece que consegue suportar pequenas celulas de energia. Minimo de FORCA: 2.}
{12100}{}{bola de 9mm}
{12101}{}{Uma colecao de antigas capsulas de 9x19mm. Graxa espessa para preserva-las do ambiente. Balas padrao.}
{12200}{}{Mauser 9mm}
{12201}{}{Uma Mauser M/96, em 9x19mm Parabellum. Em condicao excelente. Extremamente precisa. Minimo de FORCA: 3.}
{12300}{}{Anulador Psiquico}
{12301}{}{Um dispositivo estranho, construido de uma tecnologia estranha.}
{12400}{}{Cerveja}
{12401}{}{Algum tipo de cerveja feita em casa.}
{12500}{}{Bebida}
{12501}{}{Um licor antigo, da era pre-Guerra.}
{12600}{}{Frasco de Água}
{12601}{}{Um recipiente para a contencao e preservacao de água ou outros liquidos.}
{12700}{}{Corda}
{12701}{}{Uma linha grossa, forte. Aproximadamente 45 pés de comprimento.}
{12800}{}{Armario de Pe de Cama}
{12801}{}{Seu armario de pe de cama basico. Guarda coisas, fica no pe da cama, pode ser trancado.}
{12900}{}{Armario de Pe de Cama}
{12901}{}{Seu armario de pe de cama basico. Guarda coisas, fica no pe da cama, pode ser trancado.}
{13000}{}{Armario de Pe de Cama}
{13001}{}{Seu armario de pe de cama basico. Guarda coisas, fica no pe da cama, pode ser trancado.}
{13100}{}{Armario de Pe de Cama}
{13101}{}{Seu armario de pe de cama basico. Guarda coisas, fica no pe da cama, pode ser trancado.}
{13200}{}{Armario}
{13201}{}{Um recipiente para armazenagem.}
{13300}{}{Armario}
{13301}{}{Um recipiente para armazenagem.}
{13400}{}{Armario}
{13401}{}{Um recipiente para armazenagem.}
{13500}{}{Armario}
{13501}{}{Um recipiente para armazenagem.}
{13600}{}{Armario}
{13601}{}{Um recipiente para armazenagem.}
{13700}{}{Armario}
{13701}{}{Um recipiente para armazenagem.}
{13800}{}{Armario}
{13801}{}{Um recipiente para armazenagem.}
{13900}{}{Armario}
{13901}{}{Um recipiente para armazenagem.}
{14000}{}{Cartao de Acesso}
{14001}{}{Um cartao de acesso da seguranca. Ainda em condicao de funcionamento.}
{14100}{}{Emblema COC}
{14101}{}{Um emblema na forma do simbolo das Crianças da Catedral. Em um lado você nota batidas e marcas de dente, quase lembrando você de uma chave.}
{14200}{}{Emblema COC}
{14201}{}{Um emblema na forma do simbolo das Crianças da Catedral. Em um lado você nota batidas e marcas de dente, quase lembrando você de uma chave.}
{14300}{}{Rifle de Sniper}
{14301}{}{Um Rifle de Sniper DKS-501. Excelente arma de projetil de longo alcance. Originalmente .308, este rifle esta modificado para o mais comum calibre .223. Minimo de FORCA: 5.}
{14400}{}{Super Stimpak}
{14401}{}{Um chem de cura avancado. Muito poderoso. Superstims causarao uma pequena quantia de dano apos um periodo de tempo devido a poderosa natureza dos quimicos usados.}
{14500}{}{Estante para Livros}
{14501}{}{Uma estante para livros de madeira}
{14600}{}{Estante para Livros}
{14601}{}{Uma estante para livros de madeira}
{14700}{}{Estante para Livros}
{14701}{}{Uma estante para livros de madeira}
{14800}{}{Estante para Livros}
{14801}{}{Uma estante para livros de madeira}
{14900}{}{Estante para Livros}
{14901}{}{Uma estante para livros de madeira}
{15000}{}{Estante para Livros}
{15001}{}{Uma estante para livros de madeira}
{15100}{}{Estantes}
{15101}{}{Um conjunto de estantes de madeira.}
{15200}{}{Estantes}
{15201}{}{Um conjunto de estantes de madeira.}
{15300}{}{Estantes}
{15301}{}{Um conjunto de estantes de madeira.}
{15400}{}{Estantes}
{15401}{}{Um conjunto de estantes de madeira.}
{15500}{}{Estantes}
{15501}{}{Um conjunto de estantes de madeira.}
{15600}{}{Estantes}
{15601}{}{Um conjunto de estantes de madeira.}
{15700}{}{Banca de Trabalho}
{15701}{}{Um banca de trabalho. Sim, sua velha, ordinaria banca de trabalho padrao. Também parece bacana assentado lá.}
{15800}{}{Quadro de Ferramentas}
{15801}{}{Este quadro segura uma variedade de ferramentas acima da banca de trabalho popular.}
{15900}{}{Coquetel Molotov}
{15901}{}{Uma granada inflamavel feita em casa. Minimo de FORCA: 3.}
{16000}{}{Aguilhao de Rebanho}
{16001}{}{Um aguilhao de rebanho modelo Melhor Amigo do Fazendeiro da Wattz Electronics. Usa pequenas celulas de energia para a força. Minimo de FORCA: 4.}
{16100}{}{Arma Red Ryder BB}
{16101}{}{Uma arma Red Ryder BB. A classica. Minimo de FORCA: 3.}
{16200}{}{Arma Red Ryder LE BB}
{16201}{}{Uma versao da edicao limitada da arma Red Ryder BB. Uma verdadeira classica. Minimo de FORCA: 3.}
{16300}{}{BB's}
{16301}{}{Um pacote de BBs de antes da guerra. Em excelente condicao. Aço inoxidavel.}
{16400}{}{Fita da Brotherhood}
{16401}{}{Um holodisco a respeito da Brotherhood of Steel.}
{16500}{}{Barraca da Iguana}
{16501}{}{O lar dos Pedacos da Iguana do Bob. O que não há para amar a respeito de iguana fresca e assada?}
{16600}{}{Mesa}
{16601}{}{Uma mesa generica. Mantem as coisas fora do chao.}
{16700}{}{Mesa}
{16701}{}{Uma mesa generica. Mantem as coisas fora do chao.}
{16800}{}{Coisas}
{16801}{}{Estes são itens mistos, tambem conhecidos como "coisas".}
{16900}{}{Coisas}
{16901}{}{Estes são itens mistos, tambem conhecidos como "coisas".}
{17000}{}{Coisas}
{17001}{}{Estes são itens mistos, tambem conhecidos como "coisas".}
{17100}{}{Coisas}
{17101}{}{Estes são itens mistos, tambem conhecidos como "coisas".}
{17200}{}{Coisas}
{17201}{}{Estes são itens mistos, tambem conhecidos como "coisas".}
{17300}{}{Coisas}
{17301}{}{Estes são itens mistos, tambem conhecidos como "coisas".}
{17400}{}{Coisas}
{17401}{}{Estes são itens mistos, tambem conhecidos como "coisas".}
{17500}{}{Coisas}
{17501}{}{Estes são itens mistos, tambem conhecidos como "coisas".}
{17600}{}{Coisas}
{17601}{}{Estes são itens mistos, tambem conhecidos como "coisas".}
{17700}{}{Coisas}
{17701}{}{Estes são itens mistos, tambem conhecidos como "coisas".}
{17800}{}{Coisas}
{17801}{}{Estes são itens mistos, tambem conhecidos como "coisas".}
{17900}{}{Coisas}
{17901}{}{Estes são itens mistos, tambem conhecidos como "coisas".}
{18000}{}{Caixote}
{18001}{}{Um caixote de madeira preenchido com coisas genericas.}
{18100}{}{Escrivaninha}
{18101}{}{Uma escrivaninha generica. Viu uma escrivaninha, você viu todas elas.}
{18200}{}{Escrivaninha}
{18201}{}{Uma escrivaninha generica.}
{18300}{}{Escrivaninha}
{18301}{}{Uma escrivaninha generica.}
{18400}{}{Escrivaninha}
{18401}{}{Uma escrivaninha generica.}
{18500}{}{Escrivaninha}
{18501}{}{Uma escrivaninha generica.}
{18600}{}{Escrivaninha}
{18601}{}{Uma escrivaninha generica.}
{18700}{}{Escrivaninha}
{18701}{}{Uma escrivaninha generica.}
{18800}{}{Armario}
{18801}{}{Um armario.}
{18900}{}{Armario}
{18901}{}{Um armario.}
{19000}{}{Disco do VEF}
{19001}{}{Uma holofita contendo informação medica. Pode ser usada para inserir informação no seu PIPBoy.}
{19100}{}{Disco da Segurança}
{19101}{}{Uma holofita com a escrita "Registro da Segurança" no rotulo. Você pode usa-lá para transferir os dados que ela contem para o seu PIPBoy.}
{19200}{}{Disco do Experimento Alfa}
{19201}{}{O rotulo nesta holofita diz: "Registro do Experimento Alfa"}
{19300}{}{Disco do Experimento Delta}
{19301}{}{O rotulo nesta holofita diz: "Registro do Experimento Delta"}
{19400}{}{Disco do Experimento da Vree}
{19401}{}{Esta holofita foi atualizada com evidencia medica da Vree da Irmandade do Aço. Ela pode usada para transferir os dados para o seu PIPBoy.}
{19500}{}{Codigo de Honra da Brotherhood}
{19501}{}{Um holofita com um simbolo aspero da Brotherhood of Steel inscrito nela. Use a fita para transferir os dados para o seu PIPBoy.}
{19600}{}{Transmissoes Mutantes}
{19601}{}{Esta holofita parece que foi designada para gravar dados de audio de um radio. Use a fita para transferir a informação para o seu PIPBoy.}
{19700}{}{Caixa}
{19800}{}{Caixa}
{19900}{}{Caixa}
{20000}{}{Caixa}
{20100}{}{Caixa}
{20200}{}{Caixa}
{20300}{}{Caixa}
{20400}{}{Caixa}
{20500}{}{Sinal Luminoso}
{20501}{}{Um sinal luminoso. Cria luz por um curto periodo de tempo. O papel esta um pouco gasto, mas de outro modo esta em boa condicao. Ele esta aceso.}
{20600}{}{Dinamite}
{20601}{}{Um explosivo forte, consistindo de nitroglicerina misturado com a substancia absorvente kiselguhr. Inclui um timer, o qual esta ticking.}
{20700}{}{Contador Geiger}
{20701}{}{Um Contador Geiger da Wattz Electronics modelo C-Radz. Detecta a presença e força dos campos da radiação. Esta ligado.}
{20800}{}{Sensor de Movimento}
{20801}{}{Um sensor de movimento da Wattz Electronics modelo C-U. Detecta a movimentação de material biologico a um distancia de metros usando um dispositivo rader ajustado. Esta ligado.}
{20900}{}{Explosivos Plasticos}
{20901}{}{Um chunk de Cordex, uma marca militar de explosivos plasticos. Altamente estaveis, muito destrutivos. Inclui um timer, o qual esta ticking.}
{21000}{}{Garoto Disfarce}
{21001}{}{Um dispositivo RobCo Garoto Disfarce 3001 dispositivo de disfarce pessoal. Gera um campo modulante que transmite a luz refletida de um lado de um objeto para o outro.}
{21100}{}{Ossos}
{21101}{}{Você vê o Ed. Ed esta morto.}
{21200}{}{Tandi}
{21201}{}{Você esta permutando pela libertacao da Tandi.}
{21300}{}{Restos do Gizmo}
{21301}{}{Gizmo, chefe do crime formal de Junktown esta morto. É bastante fedido tambem.}
{21400}{}{Escrivaninha}
{21401}{}{Uma escrivaninha. Apos observacao adicional, você decide que ainda é uma escrivaninha.}
{21500}{}{Historia da Brotherhood}
{21501}{}{Uma holofita contendo informação relacionada a Brotherhood of Steel. Pode ser usada para inserir informação no seu PIPBoy 2000.}
{21600}{}{Historia do Maxson}
{21700}{}{Jornal do Maxson}
{21800}{}{Cura Leve}
{21801}{}{Permute por esta opção se você quer cura leve.}
{21900}{}{Cura Media}
{21901}{}{Permute por esta opção se você quer cura media.}
{22000}{}{Cura Pesada}
{22001}{}{Permute por esta opção se você quer muitos cuidados e cura pesada.}
{22100}{}{Cartao de Segurança}
{22101}{}{Um cartao com um nível de seguranca codificado dentro dos seus eletronicos muito simples.}
{22200}{}{Interruptor de Campo}
{22201}{}{Um dispositivo de trasmissao eletronica com um botao de ativacao muito simples e grande. Parece que foi feito recentemente e desenhado para mãos muito grandes.}
{22300}{}{Chave de Passe Amarela}
{22301}{}{Uma chave de seguranca eletronica, codificada com a cor amarela.}
{22400}{}{Estatueta Pequena}
{22401}{}{Você pensa que esta poderia ser uma escultura do "Pip Boy" mas você não consegue ter certeza.}
{22500}{}{Você Não Tem Ideia}
{22501}{}{Conforme inspecao adicional, você ainda não tem ideia do que isto é.}
{22600}{}{Caixa de Noodles}
{22601}{}{Você não tem ideia do que "Espaguete Instantaneo" significa.}
{22700}{}{Pequena Caixa Empoeirada de Algum Tipo}
{22701}{}{Um jantar congelado. Você não tem certeza, mas é definitivamente não comestivel. Você não esta bem certo se alguma vez foi.}
{22800}{}{Manual Tecnico}
{22801}{}{Um manual técnica de reparo da Power Armor T-51b.}
{22900}{}{Pequeno Pedaco de Maquinaria}
{22901}{}{Você vê um Motivador Sistolico. Esta pedaço incomum de maquinaria e muito pequeno.}
{23000}{}{Registros da Vault}
{23001}{}{Um compendio de eventos e gravações importantes de um sistema de computadores da Vault. Possivelmente estragado.}
{23100}{}{Codigo de Segurança da Base Militar}
{23101}{}{Uma fita Holodisc da Wattz Electronics. Esta em particular parece estar em péssimo estado.}
{23200}{}{Power Armor Fortalecida}
{23201}{}{Um traje de Power Armor T-51b. O processo de fortalecimento melhorou a capacidade defensiva deste sistema de armadura de alta tecnologia.}
{23300}{}{Rifle de Plasma Turbo}
{23301}{}{Um rifle de plasma modificado Winchester P94. A camara do raio de plasma foi anexada para acelerar o processo de formacao do raio. Minimo de FORCA: 6.}
{23400}{}{Soco Ingle com Pontas}
{23401}{}{Uma versao melhorada do classico. O soco ingles com pontas faz mais dano, cortando na carne do seu/sua oponente em combate desarmado. Minimo de FORCA: 1.}
{23500}{}{Punho de Força}
{23501}{}{Um Punho de Força "Big Frigger" da BeatCo. Considerada por muitos ser a arma suprema a usar em combate desarmado. Movida por pequenas celulas de energia. Minimo de FORCA: 1.}
{23600}{}{Faca de Combate}
{23601}{}{Uma faca de combate de alta qualidade, a Stallona e da SharpWit, Inc. O gume desta lamina e afiado com garantia de uma decada de uso!  Minimo de FORCA: 2.}
{23700}{}{Jornais de Quimica}
{23701}{}{Uma pilha aleatoria de literatura a respeito do campo da Quimica. Os papeis sobre Quimica Molecular são particularmente interessantes.}
{23800}{}{Transmissao dos Regulores}
{23801}{}{Uma gravacao em holofita de uma transmissao de audio.}
{23900}{}{Armadura da Brotherhood}
{23901}{}{Uma versao superior da Armadura de Combate. A Brotherhood of Steel fez muitos melhoramentos sobre a versao padrao.}
{24000}{}{Armadura Tesla}
{24001}{}{Esta armadura brilhante fornece protecao superior contra ataques de energia. As tres varinhas com espirais de atracao Tesla dispersam uma grande porcentagem dos ataques direcionados de energia.}
{24100}{}{Pistola .223}
{24101}{}{Um rifle .223 modificado e cortado para um pistola. Esta é uma arma de fogo de um tipo único, obviamente feita com amor e técnica. Minimo de FORCA: 5.}
{24200}{}{Espingarda de Combate}
{24201}{}{Uma espingarda de combate calibre 12 Winchester City-Killer, variante com a cartucheira atras do gatilho. Em excelente condicao, ela tem a modificacao seladora ambiental DesertWarfare para confiabilidade extra. Minimo de FORCA: 5.}
{24300}{}{Vaso}
{24301}{}{Um vaso de barro finamente trabalhado.}
{24400}{}{Vaso}
{24401}{}{Um vaso de barro finamente trabalhado.}
{24500}{}{Baú}
{24501}{}{Um baú de madeira.}
{24600}{}{Prateleira}
{24601}{}{Uma prateleira de madeira com itens diversos.}
{24700}{}{Prateleira}
{24701}{}{Uma prateleira de madeira com itens diversos.}
{24800}{}{Vaso}
{24801}{}{Um vaso de barro finamente trabalhado.}
{24900}{}{Vaso}
{24901}{}{Um vaso de barro finamente trabalhado.}
{25000}{}{Ossos}
{25001}{}{Uma pilha de ossos humanos.}
{25100}{}{Ossos da Anna}
{25101}{}{Estes ossos parecem inquietos.}
{25200}{}{Medalhão de Ouro da Anna}
{25201}{}{Este medalhão dourado, bem gasto, se abre revelando uma foto encantadora.}
{25300}{}{Controlador de Célula de Combustível}
{25301}{}{Este chip controla o fluxo de energia para os motores elétricos de um carro. Muitos motoristas queimavam este chip rapidamente com acelerações bruscas e frequentes. Ainda é uma peça valiosa - se ao menos você tivesse um carro para instalá-la.}
{25400}{}{Regulador de Célula de Combustível}
{25401}{}{Alguns donos de carro instalavam este regulador, que dobra a autonomia do carro entre cargas, mas a maioria dos motoristas não se importava com o quanto o carro consumia; afinal, energia é barata e abundante, então por que se preocupar?}
{25500}{}{Zip Gun}
{25501}{}{Uma pistola laser caseira. Força mín.: 3.}
{25600}{}{10mm Mauser}
{25601}{}{Uma Mauser M/96, convertida para o poderoso calibre 10mm. Em excelente estado. Extremamente precisa. Força mín.: 4.}
{25700}{}{Relógio de Ouro do Cornelius}
{25701}{}{Este é um antigo instrumento de medir tempo conhecido como relógio de bolso. O tempo se esgotou para esta lembrança há muitos e muitos anos.}
{25800}{}{Peça Hidrelétrica}
{25801}{}{Este é um Regulador de Magnetosfera Hidrelétrico.}
{25900}{}{Jet}
{25901}{}{Jet é uma poderosa metanfetamina que estimula o sistema nervoso central. O êxtase inicial raramente dura mais que alguns minutos, mas nesse tempo o usuário é tomado por uma onda de energia e força.}
{26000}{}{Antídoto de Jet}
{26001}{}{Este antídoto cura o vício em Jet.}
{26100}{}{Espingarda de Chumbinho do Jonny}
{26101}{}{Uma espingarda de chumbinho Red Ryder com o nome 'Jonny' arranhado na coronha. Força mín.: 3.}
{26200}{}{Botas de Borracha}
{26201}{}{Um velho par de botas de borracha resistentes para trabalho. Parecem duráveis o bastante para segurar a lama, ao menos por um tempo.}
{26300}{}{Mensagem do Slag}
{26301}{}{Esta é uma mensagem do líder dos Slags para os moradores de Modoc.}
{26400}{}{Item Legal do Smith}
{26401}{}{LONG DESCRIPTION HERE.}
{26500}{}{Jaqueta de Couro de Combate}
{26501}{}{Esta jaqueta de couro bem acolchoada é incomum por ter duas mangas. Você com certeza vai fazer sucesso na moda onde quer que arrume confusão.}
{26600}{}{Rádio do Vic}
{26601}{}{Este rádio portátil não funciona, mas parece estar em boas condições. Algumas peças dele poderiam ser aproveitadas em outros rádios.}
{26700}{}{Cantil do Vic}
{26701}{}{Esta relíquia do Vault provavelmente guardava algum sacramento sagrado. O número sagrado 13 está estampado na lateral deste precioso elo com o passado, e o esperançoso futuro, do seu povo.}
{26800}{}{Espingarda de Assalto}
{26801}{}{Uma Arma de Assalto Militar H&K, uma das muitas armas importadas em solo americano. Foi a arma favorita de unidades de pacificação militar pelo mundo, embora seu custo tenha impedido que substituísse os projetos do próprio Exército dos EUA. Força mín.: 6.}
{26900}{}{Peças de Robô}
{26901}{}{Uma pilha de peças de robô danificadas.}
{27000}{}{Lança-Foguetes Robô}
{27001}{}{Usado apenas por robôs equipados com foguetes.}
{27100}{}{Flor de Broc}
{27101}{}{A flor abundante que forma a base do pó de cura.}
{27200}{}{Raiz de Xander}
{27201}{}{A raiz rara que dá propriedades curativas ao pó de cura.}
{27300}{}{Pó de Cura}
{27301}{}{Uma magia de cura muito poderosa - embora traga uma sensação de sono à sua cabeça.}
{27400}{}{Munição de Foguete Robô}
{27401}{}{Usado apenas por robôs equipados com foguetes.}
{27500}{}{Troféu de Reconhecimento}
{27501}{}{Um troféu de ouro maciço com a inscrição "Para: Dave, De: DC's, Por: Ser uma Pessoa Especial."}
{27600}{}{Pele de Gecko}
{27601}{}{Este é o couro seco e curtido de um Gecko.}
{27700}{}{Pele de Gecko Dourado}
{27701}{}{Este é o couro seco e curtido de um Gecko Dourado.}
{27800}{}{Pederneira}
{27801}{}{Uma pedra usada para afiar armas.}
{27900}{}{Interface Neural}
{27901}{}{Parece ser um conjunto de eletrodos embutidos numa unidade de cabeça com um plugue de interface de computador padrão.}
{28000}{}{Lança Afiada}
{28001}{}{Uma arma de haste com ponta afiada. O cabo é de madeira e a ponta é de aço afiado. Força mín.: 4.}
{28100}{}{Olho do Dixon}
{28101}{}{Um pequeno pote contendo um olho humano suspenso em algum tipo de líquido. O rótulo diz Cabo Dixon.}
{28200}{}{Olho do Clifton}
{28201}{}{Um pequeno pote contendo um olho humano suspenso em algum tipo de líquido. O rótulo diz General Clifton.}
{28300}{}{Tommy Gun}
{28301}{}{Esta arma de aparência antiga parece ser uma submetralhadora fabricada à imagem da Thompson M1928, a arma preferida dos gângsteres do início do século 20. Você se pergunta por quê. Força mín.: 6.}
{28400}{}{Carne Seca}
{28401}{}{Estes pedaços de carne de fera, defumados e secos, continuam mastigáveis e até nutritivos por anos, e anos, e anos....}
{28500}{}{Membros de Radscorpion}
{28501}{}{Estas garras de Radscorpion foram esvaziadas e têm uma alça com uma fivela quebrada na ponta.}
{28600}{}{Lenha}
{28601}{}{Uma pilha de lenha e gravetos.}
{28700}{}{Rifle de Caça com Mira}
{28701}{}{Nada melhor do que ver aquela cara de surpresa no seu alvo. A mira Loophole x20 deste rifle de caça torna isso mais fácil do que nunca. Preciso do primeiro ao último tiro, não importa que tipo de caça você esteja perseguindo. Força mín.: 5.}
{28800}{}{Célula de Combustível do Carro}
{28801}{}{Uma célula de combustível de carro.}
{28900}{}{Pá}
{28901}{}{Esta é uma pá para cavar valas e coisas do tipo.}
{29000}{}{Arma Corpo-a-Corpo Robô 1}
{29001}{}{Para o Robô Olho Flutuante. Causa Dano Elétrico.}
{29100}{}{Arma Corpo-a-Corpo Robô 2}
{29101}{}{Para o Robô Olho Flutuante. Causa Dano Elétrico.}
{29200}{}{Luvas de Boxe}
{29201}{}{Um par de luvas de boxe com leve cheiro de suor. Parecem ter sido muito usadas: muitas manchas antigas de sangue ainda permanecem.}
{29300}{}{Luvas de Boxe Reforçadas}
{29301}{}{Alguém "acidentalmente" enfiou placas de metal nestas luvas de boxe. Tecnicamente poderia ser considerado trapaça, mas você prefere pensar nisso como uma chance a mais de causar um dano de quebrar ossos.}
{29400}{}{Holodisco do Vault 13}
{29401}{}{Um holodisco que supostamente contém a localização do Vault 13.}
{29500}{}{Cheezy Poofs}
{29501}{}{Uma caixa de salgadinhos sabor queijo. São extremamente bons.}
{29600}{}{Carabina 10mm}
{29601}{}{A Heckler & Koch MP10 foi projetada para substituir a envelhecida MP9, com base na experiência das Guerras dos Recursos. Feita para aguentar o ambiente hostil dos desertos árabes. Força mín.: 4.}
{29700}{}{Barra de Metal}
{29701}{}{É uma longa barra de metal. O que você esperava? Força mín.: 5.}
{29800}{}{Chave de Trapper Town}
{29801}{}{Uma chave comum.}
{29900}{}{Rifle de Cano}
{29901}{}{Este é um rifle de tiro único feito à mão. Força mín.: 5.}
{30000}{}{Zip Gun}
{30001}{}{Uma pistola de tiro único feita à mão. Força mín.: 4.}
{30100}{}{Prancheta}
{30101}{}{Esta é uma prancheta com o relatório do sistema de refrigeração.}
{30200}{}{Holodisco do Gecko}
{30201}{}{O rótulo desta holofita diz: "Dados Econômicos de Gecko". É difícil interpretar a maioria dos gráficos, tabelas e fórmulas técnicas aqui, mas a maior parte da informação parece destacar as vantagens de uma aliança entre Vault City e Gecko.}
{30300}{}{Holodisco do Reator}
{30301}{}{O rótulo desta holofita diz: "Dados de Desempenho do Reator de Gecko". Este disco contém uma sequência de números que não significam nada para você. Com certeza há muita informação aqui e deve ser importante para alguém, de algum modo.}
{30400}{}{Baralho de Cartas "Tragic"}
{30401}{}{Este é um baralho de um jogo de cartas colecionáveis. Parece que poderia ser um hobby caro se você se viciasse.}
{30500}{}{Cartão-Chave Amarelo do Reator}
{30501}{}{Uma chave de segurança eletrônica, com código de cor amarelo.}
{30600}{}{Cartão-Chave Vermelho do Reator}
{30601}{}{Uma chave de segurança eletrônica, com código de cor vermelho.}
{30700}{}{Transformador de Plasma}
{30701}{}{Este é um Transformador de Plasma de Três Estágios.}
{30800}{}{Super Kit de Ferramentas}
{30801}{}{Um impressionante conjunto de ferramentas feito pela "Snap-Off".}
{30900}{}{Talismã}
{30901}{}{Um talismã usado pelos seguidores do Cérebro.}
{31000}{}{Cerveja Gamma Gulp}
{31001}{}{Uma garrafa de cerveja Gamma Gulp. Brilha no escuro!}
{31100}{}{Rum Roentgen}
{31101}{}{Uma garrafa de rum Roentgen. Brilha no escuro!}
{31200}{}{Formulário de Requisição de Peças}
{31201}{}{Este é um formulário de Requisição de Peças.}
{31300}{}{Revólver .44 Magnum}
{31301}{}{Sendo esta a pistola mais poderosa do mundo, capaz de arrancar sua cabeça fora, você tem que se perguntar uma coisa. Estou com sorte? E então, está, seu moleque? Força mín.: 5.}
{31400}{}{Camisinha (Pacote Azul)}
{31401}{}{Esta é uma camisinha da marca Jimmy Hats, uma marca muito confiável. Esta é texturizada para o prazer dela.}
{31500}{}{Camisinha (Pacote Verde)}
{31501}{}{Esta é uma camisinha da marca Jimmy Hats, uma marca muito confiável. Esta contém corante verde fosforescente nº 2 e está lambuzada de lubrificante espermicida para proteção extra.}
{31600}{}{Camisinha (Pacote Vermelho)}
{31601}{}{Esta é uma camisinha da marca Jimmy Hats, uma marca muito confiável. Esta contém corante vermelho fosforescente nº 5 e tem um delicioso sabor de rocambole de canela... ou pelo menos foi o que você ouviu.}
{31700}{}{Estojo de Cosméticos}
{31701}{}{Este é um autêntico estojo de cosméticos da marca Mary May.}
{31800}{}{Seringa Vazia}
{31801}{}{Esta é uma seringa vazia.}
{31900}{}{Canivete}
{31901}{}{A lâmina desta pequena faca é presa por uma mola. Quando um botão no cabo é pressionado, a lâmina salta com um satisfatório som de "Sssssshk". Força mín.: 1.}
{32000}{}{Vara Afiada}
{32001}{}{Uma vara de madeira afiada numa das pontas. Força mín.: 4.}
{32100}{}{Cérebro Cibernético}
{32101}{}{Um cérebro humano que foi aprimorado com o acréscimo de conexões eletrônicas e robóticas.}
{32200}{}{Cérebro Humano}
{32201}{}{Um cérebro humano comum. Normalmente são encontrados em crânios humanos. Eca.}
{32300}{}{Cérebro de Chimpanzé}
{32301}{}{Um cérebro de macaco. É macio e mole.}
{32400}{}{Cérebro Anormal}
{32401}{}{Muito possivelmente um cérebro humano. A cor não parece muito certa e o hemisfério esquerdo do cérebro desabou sobre si mesmo.}
{32500}{}{Dados}
{32501}{}{Um par comum de dados de aposta.}
{32600}{}{Dados Viciados}
{32601}{}{Um par de dados viciados. Não fique exibindo isso pelo cassino.}
{32700}{}{Ovo de Páscoa}
{32701}{}{Este é um ovo de galinha cozido pintado com corantes coloridos.}
{32800}{}{Magic 8-Ball}
{32801}{}{Esta esfera preta é algum estranho dispositivo precognitivo... uma pequena janela no topo parece ser capaz de prever o futuro! A humanidade pré-guerra devia ser genial para inventar tamanha maravilha!}
{32900}{}{Soro Mutagênico}
{32901}{}{Uma estranha mistura orgânica que talvez possa reverter o Fator de Mutação em humanos.}
{33000}{}{Verti-Bird Caído}
{33001}{}{Estes são destroços de um verti-bird. Parece ter caído aqui meses atrás.}
{33100}{}{Cat's Paw Issue #5}
{33101}{}{Esta é a difícil de achar Edição 5 da revista Cat's Paw. Fotos à parte, esta edição tem um artigo maravilhoso sobre armas de energia.}
{33200}{}{.45 SMG}
{33201}{}{Esta submetralhadora MAC-27 barata foi projetada para uso pela retaguarda do Exército e por forças policiais no Canadá ocupado. Robusta e confiável. Força mín.: 4.}
{33300}{}{Comprimidos para o Coração}
{33301}{}{Estes comprimidos são usados por pessoas com problemas cardíacos.}
{33400}{}{Veneno}
{33401}{}{Uma agulha hipodérmica cheia de veneno poderoso.}
{33500}{}{Maleta do Moore}
{33501}{}{Thomas Moore pediu que você levasse esta maleta de couro de brahmin à família Bishop em Nova Reno. Está bem trancada e você não consegue abri-la.}
{33600}{}{Maleta do Moore}
{33601}{}{Thomas Moore pediu que você levasse esta maleta de couro de brahmin à família Bishop em Nova Reno. Está bem trancada e você não consegue abri-la.}
{33700}{}{Holodisco da Lynette}
{33701}{}{Este é o holodisco que você recebeu da Lynette.}
{33800}{}{Holodisco do Westin}
{33801}{}{Este é o holodisco que você recebeu do Westin.}
{33900}{}{Holodisco Espião da NCR}
{33901}{}{Este holodisco contém relatórios de horários das caravanas da NCR e informações de segurança. É endereçado a Darion e assinado "F". Com essa informação, fica fácil ver como os saqueadores escaparam da captura.}
{34000}{}{Papéis do Doutor}
{34001}{}{Um conjunto de plantas muito detalhadas de uma Unidade Canina Cibernética de Guarda. Com isto e as instalações certas, uma pessoa talvez consiga construir um robô-cão.}
{34100}{}{Passe Presidencial}
{34101}{}{O portador deste documento tem Nível de Segurança A-Prime, conforme autorizado pela autoridade do Presidente da Nova República da Califórnia. Está assinado pela Presidente Tandi.}
{34200}{}{Broche dos Rangers}
{34201}{}{Este broche diz que você é um Ranger oficial da Nova Califórnia. Olha - tem até uma roda de código e tudo!}
{34300}{}{Mapa dos Rangers}
{34301}{}{Um mapa da área ao redor - não vai te ajudar muito - mas há nomes-código nele para os esconderijos dos Rangers ao norte.}
{34400}{}{Sepultura}
{34500}{}{Sepultura}
{34600}{}{Sepultura}
{34700}{}{Sepultura}
{34800}{}{Power Armor Avançada}
{34801}{}{Esta armadura motorizada é composta de ligas metálicas leves, reforçadas com peças de cerâmica em pontos-chave. Os servomotores de assistência ao movimento também parecem ser modelos de alta qualidade.}
{34900}{}{Arm. Motoriz. Avançada MKII}
{34901}{}{Esta Power Armor parece ser composta inteiramente de compósitos cerâmicos leves, em vez da combinação usual de placas de metal e cerâmica. Parece que deve oferecer proteção ainda maior que a Power Armor Avançada padrão.}
{35000}{}{Bozar}
{35001}{}{O sonho de um texano, a DKS-802 é o ápice da arte do atirador de elite. Embora seja um tanto exigente e propensa a emperrar, a precisão da grande arma compensa de sobra suas necessidades extras de manutenção. Força mín.: 8.}
{35100}{}{Rifle de Assalto Avançado}
{35101}{}{A sucessora da AK-112, a AK-198 é um modelo militar moderno importado em quantidades limitadas para uso pelas Forças Especiais do Exército dos EUA. Capaz de disparar em modo único e automático. Força mín.: 5.}
{35200}{}{Rifle de Assalto EC}
{35201}{}{Um velho rifle de assalto europeu, o G66 foi importado em números limitados por survivalistas e milícias, após a dissolução da Comunidade Europeia. Força mín.: 5.}
{35300}{}{XL70E3}
{35301}{}{Esta era uma arma experimental na época da guerra. Fabricada, principalmente, de polímeros de alta resistência, a arma é quase indestrutível. É leve, dispara rápido, é precisa e pode ser desmontada sem o uso de ferramentas. Força mín.: 5.}
{35400}{}{Espingarda Antimotim}
{35401}{}{Um passo acima da City-Killer original, a City-Sweeper foi projetada especificamente para conter motins e cobaias de laboratório. Aceita cartuchos de espingarda calibre 12 padrão. Força mín.: 5.}
{35500}{}{Metralhadora Leve}
{35501}{}{Uma velha arma automática de esquadrão, retirada das unidades da Guarda Nacional depois que a chegada das miniguns portáteis e projetos superiores a tornou obsoleta. Força mín.: 6.}
{35600}{}{Módulo de Voz do Computador}
{35601}{}{Uma placa de circuito com várias peças não identificáveis, um microfone e uma inscrição que diz "Módulo de Reconhecimento de Voz da Vault-Tec".}
{35700}{}{.45 Caliber}
{35701}{}{Munição. Calibre .45.}
{35800}{}{2mm EC}
{35801}{}{Ammunition.}
{35900}{}{4.7mm Caseless}
{35901}{}{Munição. Calibre: 4.7mm, sem estojo.}
{36000}{}{9mm}
{36001}{}{Munição. Calibre: 9mm.}
{36100}{}{HN Needler Cartridge}
{36101}{}{Munição. Este cartucho parece ser munição para a Pistola HN Needler. Cada 'bala' é uma pequena seringa projetada para injetar seu conteúdo no alvo ao impacto.}
{36200}{}{HN AP Needler Cartridge}
{36201}{}{Munição. Este cartucho parece ser munição perfurante para a Pistola HN Needler. As pontas hipodérmicas são feitas de uma liga estranha e são incrivelmente afiadas.}
{36300}{}{7.62mm}
{36301}{}{Munição. Calibre: 7.62mm.}
{36400}{}{Motivador de Robô}
{36401}{}{Este é o mecanismo de acionamento de um robô.}
{36500}{}{Espinho de Planta}
{36501}{}{Um espinho-semente orgânico que as plantas carnívoras cospem em potenciais alimentos ou portadores de sementes.}
{36600}{}{G.E.C.K.}
{36601}{}{O Kit de Criação do Jardim do Éden. Esta unidade é equipamento padrão de todos os vaults da Vault-Tec. Um GECK é o recurso para reconstruir a civilização após a bomba. É só adicionar água e mexer.}
{36700}{}{Caixa de Munição}
{36800}{}{Caixa de Munição}
{36900}{}{Caixa de Munição}
{37000}{}{Caixa de Munição}
{37100}{}{Garra}
{37101}{}{Garra}
{37200}{}{Garra}
{37201}{}{Garra}
{37300}{}{Cartão-Chave do Vault 15}
{37301}{}{Uma chave de segurança eletrônica, com código de cor vermelho.}
{37400}{}{Sepultura}
{37500}{}{Sepultura}
{37600}{}{Sepultura}
{37700}{}{Peças de Computador do Vault 15}
{37701}{}{Peças de computador diversas com várias funções. O sonho de um nerd de informática.}
{37800}{}{Biscoito}
{37801}{}{Um biscoito com gotas de chocolate. Nham!}
{37900}{}{Armadura de Couro Mark II}
{37901}{}{Uma versão aprimorada da armadura de couro básica, com camadas extras de proteção. Finamente confeccionada em couro curtido de brahmin.}
{38000}{}{Armadura de Metal Mark II}
{38001}{}{Placas de metal polidas, finamente trabalhadas numa armadura.}
{38100}{}{Armadura de Combate Mark II}
{38101}{}{Armadura de alta tecnologia, feita de polímeros defensivos avançados.}
{38200}{}{Combustível de Lança-Chamas MKII}
{38201}{}{Este combustível de lança-chamas usa uma mistura avançada de super-queima.}
{38300}{}{Estilete}
{38301}{}{Esta faca caseira é tão perigosa quanto fácil de esconder. Sua presença não pode ser detectada por outros. Força mín.: 1.}
{38400}{}{Chave Inglesa}
{38401}{}{Uma chave inglesa comum, usada por mecânicos. Força mín.: 3.}
{38500}{}{Espingarda Serrada}
{38501}{}{Os últimos centímetros do cano e da coronha desta espingarda foram serrados. Agora, a ampla dispersão dos tiros deste canhão de mão de cano curto o torna perfeito para controle de multidões a curta distância. Força mín.: 4.}
{38600}{}{Taco de Beisebol}
{38601}{}{Este taco de beisebol de madeira maciça, genuinamente americano, manda qualquer coisa para fora do estádio. Força mín.: 4.}
{38700}{}{Metralhadora Pesada}
{38701}{}{Um velho projeto de arma automática de esquadrão, esta arma nunca entrou em produção em massa nem em serviço regular. Força mín.: 7.}
{38800}{}{Pistola de Dardos}
{38801}{}{Você suspeita que esta pistola de dardos Bringham já foi usada para estudos científicos de campo. Ela usa como munição pequenos dardos hipodérmicos de plástico rígido. Força mín.: 3.}
{38900}{}{Avenger Minigun}
{38901}{}{A Rockwell projetou a Avenger como substituta da sua envelhecida Minigun Pessoal CZ53. Os aprimoramentos da Avenger incluem refrigeração melhorada por aletas em gel e canos cromados. Isso lhe dá maior alcance e letalidade. Força mín.: 7.}
{39000}{}{Escaldador Solar}
{39001}{}{Sem os raios do sol para carregar os capacitores desta arma, ela não acende nem um fósforo. Porém, em plena luz do dia, as células fotoelétricas experimentais que alimentam a Scorcher permitem transformar quase qualquer coisa numa criatura crocante. Força mín.: 3.}
{39100}{}{Rifle de Assalto EC Mk II}
{39101}{}{Uma versão avançada do G66, este rifle europeu importado foi usado por forças que combatiam ameaças internas. Um projeto compacto e poderoso, considerado exigente demais para o front chinês. Força mín.: 6.}
{39200}{}{Rifle Gauss M72}
{39201}{}{O rifle M72 é de projeto alemão. Ele usa um campo eletromagnético para lançar projéteis a velocidades tremendas... e perfurar quase qualquer obstáculo. Seu alcance, precisão e poder de parada são quase incomparáveis. Força mín.: 6.}
{39300}{}{Phazer}
{39301}{}{Esta misteriosa arma de alta tecnologia parece ter algum tipo de gerador de energia dentro. Se não estivesse danificada, esta arma poderia ser a arma definitiva contra qualquer inimigo. O módulo de energia reserva consiste numa pequena célula de energia substituível. Força mín.: 3.}
{39400}{}{Pistola Gauss PPK12}
{39401}{}{Elogiada por seu alcance e poder de parada, a Pistola Gauss PPK12 é de projeto alemão. A pistola usa um campo eletromagnético para lançar projéteis a velocidades tremendas e atravessar quase qualquer armadura. Força mín.: 4.}
{39500}{}{Minigun Vindicator}
{39501}{}{A empresa alemã Rheinmetal AG criou a minigun definitiva. A Vindicator dispara mais de 90.000 projéteis sem estojo por minuto pelos seus seis canos de polímero de carbono. Como o auge da habilidade de engenharia teutônica, é a arma de mão definitiva. Força mín.: 7.}
{39600}{}{Pistola de Pulso YK32}
{39601}{}{A YK32 é uma arma de pulso elétrico desenvolvida pelo Consórcio de Energia de Yuma Flats. Embora poderosa, a YK32 nunca foi considerada uma arma prática por causa do uso ineficiente de energia e do design volumoso. Força mín.: 3.}
{39700}{}{Rifle de Pulso YK42B}
{39701}{}{A YK42B é uma arma de pulso elétrico desenvolvida pelo Consórcio de Energia de Yuma Flats. É considerada uma arma muito superior à pistola YK32, tendo maior capacidade de carga e alcance. Força mín.: 3.}
{39800}{}{.44 Magnum (Recarga Rápida)}
{39801}{}{Um Revólver .44 Magnum com carregador rápido. Força mín.: 5.}
{39900}{}{Super Aguilhão de Gado}
{39901}{}{Um aguilhão de gado modelo Melhor Amigo do Fazendeiro, da Wattz Electronics. Este modelo foi aprimorado para aumentar a descarga elétrica. Força mín.: 4.}
{40000}{}{Lança-Chamas Aprimorado}
{40001}{}{Um lança-chamas modelo Flambe 450, variação exterminadora. Dispara um curto jato de líquido inflamável extremamente quente. Requer combustível especializado para funcionar direito. Este modelo foi modificado para disparar uma mistura mais quente, que causa maior combustibilidade. Força mín.: 6.}
{40100}{}{Rifle Laser (Cap. Est.)}
{40101}{}{Este rifle laser Wattz 2000 teve seu sistema de recarga aprimorado e um chip especial de reciclagem instalado, que reduz o consumo da micro célula de fusão em 50%. Força mín.: 6.}
{40200}{}{Pistola Magneto-Laser}
{40201}{}{Esta pistola laser Wattz 1000 foi aprimorada com um sistema de mira por campo magnético que concentra a emissão do laser, dando a esta pistola poder de penetração extra. Força mín.: 3.}
{40300}{}{Rifle de Assalto Avan. (VN)}
{40301}{}{A sucessora da AK-112, a AK-198 é um modelo militar moderno importado em quantidades limitadas para uso pelas Forças Especiais do Exército dos EUA. Capaz de disparar em modo único e automático. Esta arma foi equipada com uma unidade de visão noturna para maior precisão à noite. Força mín.: 5.}
{40400}{}{Desert Eagle (Pente Ampl.)}
{40401}{}{Uma antiga pistola Desert Eagle, em .44 magnum. O interesse por filmes do fim do século 20 fez desta uma das pistolas mais populares de todos os tempos. Esta foi equipada com um pente ampliado para diversão mais longa! Força mín.: 4.}
{40500}{}{Rifle de Assalto (Pente Ampl.)}
{40501}{}{Este Rifle de Assalto tem um pente de munição estendido, de tamanho militar. A capacidade ampliada do pente o torna mais divertido do que nunca para atirar a esmo. Força mín.: 5.}
{40600}{}{Pistola de Plasma (Cap. Est.)}
{40601}{}{Esta Pistola de Plasma Glock 86 teve sua câmara de contenção magnética realinhada para reduzir o consumo da célula de energia. Sua eficiência dobrou, permitindo mais tiros antes que a bateria se esgote. Força mín.: 4.}
{40700}{}{Mega Punho de Força}
{40701}{}{Um Punho de Força "Big Frigger" da BeatCo. Considerado por muitos a arma definitiva para combate desarmado. Este tem servos de força aprimorados para maior potência. Alimentado por pequenas células de energia. Força mín.: 1.}
{40800}{}{Kit de Primeiros Socorros de Campo}
{40801}{}{Um pequeno kit contendo equipamento médico básico de emergência. Ataduras, faixas, spray antisséptico e mais.}
{40900}{}{Bolsa de Paramédico}
{40901}{}{Esta bolsa contém instrumentos e químicos usados por paramédicos em campo. As ferramentas são projetadas especificamente para casos de trauma grave e emergências.}
{41000}{}{Kit de Gazuas Ampliado}
{41001}{}{Um conjunto de ferramentas de chaveiro. Inclui todas as gazuas e tensores necessários para abrir fechaduras de pino e tambor convencionais. Este conjunto também inclui algumas ferramentas especiais para mecanismos de travamento mais difíceis.}
{41100}{}{Gazua Eletrônica MKII}
{41101}{}{Esta é a gazua eletrônica FingerStuff Micromanipuladora da Wattz Electronics, de segunda geração. Serve para vencer fechaduras eletrônicas e dispositivos de segurança. Esta versão Mark II inclui software atualizado e ferramentas de interface.}
{41200}{}{Lata de Óleo}
{41201}{}{Você vê uma lata de Armor-Go. Um lubrificante polimérico de última geração para armaduras motorizadas.}
{41300}{}{Lança de Choque}
{41301}{}{Uma arma de haste eletrificada. O cabo é de metal e a ponta foi aprimorada com algum tipo de teiser de alta potência. Força mín.: 4.}
{41400}{}{Chave do Barraco do Vault 15}
{41401}{}{Uma chave comum.}
{41500}{}{Óculos}
{41501}{}{Um par de óculos para correção da visão.}
{41600}{}{Cartucho de Jet Vazio}
{41601}{}{Este cartucho de Jet vazio foi encontrado no quarto de Richard Wright. Ainda tem vestígios de Jet dentro.}
{41700}{}{Tanque de Oxigênio}
{41701}{}{Este é o tanque de oxigênio do aparelho respiratório do Salvatore.}
{41800}{}{Tanque de Veneno}
{41801}{}{Este tanque parece suspeitamente com um tanque de oxigênio, mas há um pequeno símbolo de caveira e ossos cruzados gravado no fundo. Se você não tivesse examinado de perto, não teria visto o símbolo.}
{41900}{}{Peças de Mina}
{41901}{}{Você vê um pacote de peças claramente rotuladas "Purificador de Ar GX-9". Usando suas incríveis habilidades dedutivas, você conclui que provavelmente são peças de um purificador de ar quebrado.}
{42000}{}{Vale da Mina Morningstar}
{42001}{}{Esta é uma pequena ficha provavelmente usada para pagar os Trabalhadores da Mina Morningstar.}
{42100}{}{Granada de Mão Sagrada}
{42101}{}{Uma relíquia sagrada de poder divino.}
{42200}{}{Chip de Escavadeira}
{42201}{}{Este chip parece ser de algum tipo de grande máquina industrial. Sob a sujeira e a poeira, parece estar surpreendentemente em bom estado.}
{42300}{}{Pepita de Ouro}
{42301}{}{Uma pepita de ouro.}
{42400}{}{Pedaço de Monumento}
{42401}{}{Este é um pedaço do irritadiço monumento de pedra que você achou no deserto. Embora muitos da sua vila sem dúvida o considerassem uma relíquia sagrada, de alguma forma você suspeita que foi enganado.}
{42500}{}{Cabeça de Pedra}
{42501}{}{Um enorme monumento de pedra.}
{42600}{}{Minério de Urânio}
{42601}{}{Um pedaço de Minério de Urânio, não refinado.}
{42700}{}{Sopro de Fogo}
{42800}{}{Suprimentos Médicos}
{42801}{}{Uma caixa de suprimentos médicos variados. Nada que eu possa aproveitar, porém.}
{42900}{}{Dente de Ouro}
{42901}{}{Este dente de ouro costumava pertencer ao Jules, mas agora é seu.}
{43000}{}{Projétil de Obuseiro}
{43001}{}{Um projétil de Obuseiro de 75mm. O invólucro está quase todo corroído, mas você consegue distinguir estas letras: EXP. 25-9-98.}
{43100}{}{Caixa do Ramirez, Fechada}
{43101}{}{Esta é a caixa que você recebeu do Big Jesus Mordino para entregar ao Ramirez nos Estábulos.}
{43200}{}{Caixa do Ramirez, Aberta}
{43201}{}{Esta é a caixa que você recebeu do Big Jesus Mordino para entregar ao Ramirez nos Estábulos. Está aberta e você removeu o Jet que estava dentro.}
{43300}{}{Óculos Espelhados}
{43301}{}{Este é um par de óculos escuros espelhados, elegantes e de aparência mortal. Só de tê-los no inventário você já se sente descolado.}
{43400}{}{Carroça}
{43401}{}{Uma carroça de caravana feita dos destroços de um automóvel antigo.}
{43500}{}{Carroça}
{43501}{}{Uma carroça de caravana feita dos destroços de um automóvel antigo.}
{43600}{}{Baralho}
{43601}{}{Um baralho comum de cartas de jogar.}
{43700}{}{Baralho Marcado}
{43701}{}{Toda carta deste baralho é uma dama de copas. Deve render jogos bem chatos.}
{43800}{}{Chave do Templo}
{43801}{}{Uma chave para a porta do Templo de Arroyo.}
{43900}{}{Fiapo de Bolso}
{43901}{}{Um fiapo que você achou num bolso.}
{44000}{}{Gel Biomédico}
{44001}{}{Um pote de Gel Biológico usado na área biomédica.}
{44100}{}{Plaquetas do Blondie}
{44101}{}{Estas Dog tags têm o nome do dono arranhado e o nome "Blondie" rabiscado no verso. Abaixo do nome está o número "11".}
{44200}{}{Plaquetas do Angel-Eyes}
{44201}{}{Estas Dog tags listam o dono como "Angel-Eyes". Abaixo do nome está o número "16".}
{44300}{}{Plaquetas do Tuco}
{44301}{}{Estas Dog tags fedorentas listam o dono como "Tuco Benedicto Pacifico Juan Maria Ramirez", seguido do número "27".}
{44400}{}{Mapa dos Saqueadores}
{44401}{}{Este é um mapa amassado do Norte da Califórnia pré-guerra. Reno e as rotas de caravana ao redor estão marcadas em vermelho, e há um "X" vermelho bem a leste de Reno com "Saqueadores" rabiscado embaixo.}
{44500}{}{Distintivo do Xerife}
{44501}{}{Um distintivo usado pelo Xerife de uma cidade.}
{44600}{}{Plantas do Vertibird}
{44601}{}{Um conjunto de plantas para construir Vertibirds.}
{44700}{}{Holodisco do Bishop}
{44701}{}{Este holodisco contém informações incriminadoras sobre o acordo secreto do Bishop com a NCR. Aparentemente, Bishop contratou mercenários para atacar Vault City na esperança de que Vault City recorresse à NCR por ajuda militar. Este holodisco é só de áudio e não tem dados de texto. Vault City pode se interessar por isso.}
{44800}{}{Livro-Caixa}
{44801}{}{Este livro-caixa lista uma série de pagamentos mensais feitos ao bando de mercenários pela Família Bishop de Nova Reno. Os pagamentos dependem muito de quanta "pressão" os mercenários põem sobre Vault City. Vault City pode se interessar por isso.}
{44900}{}{Espingarda de Combate (Pente Ampl.)}
{44901}{}{Uma espingarda de combate Winchester City-Killer calibre 12, variante bullpup. Em excelente estado. Tem um pente circular para rajadas prolongadas. Força mín.: 5.}
{45000}{}{Papel Rasgado 1}
{45001}{}{Você vê um pedaço de papel com algo escrito. Parece fazer parte de algum tipo de código. Infelizmente, o código está incompleto. Se ao menos você achasse as três partes. Você consegue ler o seguinte: 1. Senha de Física KSLJ, 2. Senha de Química TIU, 3. Senha de Biologia INTL}
{45100}{}{Papel Rasgado 2}
{45101}{}{Você vê um pedaço de papel com algo escrito. Parece fazer parte de algum tipo de código. Infelizmente, o código está incompleto. Se ao menos você achasse as três partes. Você consegue ler o seguinte: KJ: Ken-Lee-9, ASPO- Lo-S, VR- Dnky-Pnch-}
{45200}{}{Papel Rasgado 3}
{45201}{}{Você vê um pedaço de papel com algo escrito. Parece fazer parte de algum tipo de código. Infelizmente, o código está incompleto. Se ao menos você achasse as três partes. Você consegue ler o seguinte: 7313, hi-S12908, 98790}
{45300}{}{Papel de Senha}
{45301}{}{Estas são três partes de uma única página que, quando montadas, revelam três senhas. O texto diz: 1. Senha de Física KSLJKJ: Ken-Lee-97313, 2. Senha de Química TIUASPO- Lo-Shi-S12908, 3. Senha de Biologia INTLVR- Dnky-Pnch-98790}
{45400}{}{Interruptor de Explosivo}
{45401}{}{Este interruptor de alavanca é o componente final de um dispositivo explosivo.}
{45500}{}{Porta-Malas do Carro}
{45501}{}{O porta-malas é um ótimo lugar para guardar suas coisas.}
{45600}{}{Chave da Cela}
{45601}{}{Esta chave serve na Porta da Cela em Broken Hills.}
{45700}{}{Relatório de Campo Hubologista}
{45701}{}{Um relatório de escritório de campo sobre a campanha de recrutamento na Verdadeira Fé.}
{45800}{}{Holodisco M.B. 5}
{45801}{}{O rótulo diz: Mensagem ao CHQ - Confidencial.}
{45900}{}{Holodisco M.B. 1}
{45901}{}{O rótulo diz: Registro de transmissão de rádio checkpoint 1.}
{46000}{}{Holodisco M.B. 2}
{46001}{}{O rótulo diz: Registro de transmissão de rádio checkpoint 2.}
{46100}{}{Holodisco M.B. 3}
{46101}{}{O rótulo diz: Registro de transmissão de rádio checkpoint 3.}
{46200}{}{Holodisco M.B. 4}
{46201}{}{O rótulo diz: Registro de transmissão de rádio equipe de pesquisa.}
{46300}{}{Holodisco de Evacuação}
{46301}{}{O rótulo diz: Aviso de evacuação da base.}
{46400}{}{Holodisco de Experimento}
{46401}{}{O rótulo diz: Registro de pesquisa.}
{46500}{}{Holodisco Médico}
{46501}{}{O rótulo diz: Registro médico.}
{46600}{}{Papel de Senha}
{46601}{}{Uma folha de papel dobrada com a palavra "TCHAIKOVSKY" escrita.}
{46700}{}{Recipiente do Jesse}
{46701}{}{}
{46800}{}{Refeição do Smitty}
{46801}{}{É algum tipo de salada e um sanduíche feito do que você acha ser carne de Brahmin coberta por um molho grosso e amarelo-escuro. Também há um estranho legume verde em conserva ao lado.}
{46900}{}{Cachaça Barata}
{46901}{}{Um licor muito forte, ou fluido de limpeza, você decide.}
{47000}{}{Mordaça}
{47001}{}{Um duvidoso dispositivo sexual. Se você precisa perguntar, é porque não quer saber.}
{47100}{}{"A Flor de Lavanda"}
{47101}{}{Parece ser algum tipo de romance escrito por Dorothy Rixon. A capa tem uma mulher deitada numa cama cercada por uma centena de flores.}
{47200}{}{Holodisco Hubologista}
{47201}{}{Este holodisco está rotulado "Hubologia: A Verdade Por Trás das Mentiras". Parece funcionar com o seu PIP-Boy.}
{47300}{}{Dedo do Pé Mutante}
{47301}{}{Você vê seu sexto dedo do pé. É uma pequena parte mutante de você mesmo. Por algum motivo, você sente uma terrível sensação de perda ao olhar o minúsculo dedo amputado.}
{47400}{}{Margaridas}
{47401}{}{Um vaso de margaridas. Não são lindas?}
{47500}{}{Unused}
{47501}{}{Unused}
{47600}{}{Carta do Iluminado}
{47601}{}{Um relatório endereçado ao AHS-9 em São Francisco. É uma leitura muito enfadonha - tabelas de ajustes opressivos, relatórios de despesas e outras bobagens que não valem o seu tempo.}
{47700}{}{Holodisco de Transmissão}
{47701}{}{O rótulo diz: "Rede de Notícias Galaxy".}
{47800}{}{Holodisco da Missão Sierra}
{47801}{}{O rótulo diz: "Declaração de Missão".}
{47900}{}{Peças do NavCom}
{47901}{}{Estas são peças de computador que parecem se encaixar no interior de uma máquina. O fato de dizerem "Poseidon Oil" e "Computador de Navegação" leva você a crer que se encaixam num Computador de Navegação da Poseidon Oil.}
{48000}{}{Bônus +1 Agilidade}
{48100}{}{Bônus +1 Inteligência}
{48200}{}{Bônus +1 Força}
{48300}{}{Guia do Fallout}
{48301}{}{Bom, ISTO teria sido ótimo de se ter no começo do maldito jogo.}
{48400}{}{Orelha do Jogador}
{48401}{}{Esta é a sua orelha. O Masticator a arrancou com uma mordida durante a luta e cuspiu no seu corpo desacordado. Se você está lendo isto, provavelmente significa que vai recarregar o jogo em breve. Claro, é possível que este item tenha algum valor especial.}
{48500}{}{Orelha do Masticator}
{48501}{}{Esta é a orelha do Masticator. Você a arrancou com uma mordida depois de espancá-lo até desmaiar. Parabéns por vencê-lo. Ele é um dos NPCs mais durões do jogo, especialmente quando você não tem armas nem armadura.}
{48600}{}{Minério de Urânio Refinado}
{48601}{}{Um pedaço de Minério de Urânio. Este minério parece ter sido processado de alguma forma. Parece mais pesado.}
{48700}{}{Bilhete do Francis}
{48701}{}{"Zaius, Marcus não está fazendo nada quanto àquele odioso Jacob e seus malditos conspiradores. Primeiro eles desativam o purificador de ar... e depois o quê? Achei os túneis das reuniões secretas deles. Imagino que um corpo ou dois lá embaixo possam incriminar o Jacob. Se quiser entrar nessa, me avise. E queime o maldito bilhete desta vez!" -Assinado, Francis.}
{48800}{}{Motivador K-9}
{48801}{}{Este é o mecanismo de acionamento de um robô da série K-9.}
{48900}{}{Arma Especial de Boxeador}
{49000}{}{Holodisco da História da NCR}
{49001}{}{O rótulo diz: "História da NCR."}
{49100}{}{Boneco do Sr. Nixon}
{49101}{}{Você vê um pequeno boneco com um grande nariz vermelho. Por algum motivo, você não confia neste brinquedo infantil aparentemente inocente.}
{49200}{}{Chaveiro do Petroleiro}
{49201}{}{Uma chave de acesso codificada que dá acesso a áreas de alta segurança.}
{49300}{}{Holodisco dos Ensinamentos}
{49301}{}{O rótulo diz: "Ensinamentos Hubologistas".}
{49400}{}{Vale da Mina Kokoweef}
{49401}{}{Esta é uma pequena ficha provavelmente usada para pagar os Trabalhadores da Mina Kokoweef.}
{49500}{}{Chave de Acesso Presidencial}
{49501}{}{Esta chave de acesso tem o que parece ser o selo presidencial. Parece ser usada para obter acesso de nível Presidencial a computadores.}
{49600}{}{Luvas de Boxe}
{49601}{}{Um par de luvas de boxe com leve cheiro de suor. Parecem ter sido muito usadas: muitas manchas antigas de sangue ainda permanecem.}
{49700}{}{Luvas de Boxe Reforçadas}
{49701}{}{Alguém "acidentalmente" enfiou placas de metal nestas luvas de boxe. Tecnicamente poderia ser considerado trapaça, mas você prefere pensar nisso como uma chance a mais de causar um dano de quebrar ossos.}
{49800}{}{Canhão de Plasma Duplo}
{49801}{}{Usar somente para a criatura Torreta de Arma.}
{49900}{}{Aprimorador Linguístico do Pip-Boy}
{49901}{}{Este aprimorador linguístico do Pip-Boy consiste num holodisco de armazenamento, um cabo de microfilamento, um capacete e um sensor óptico posicionado sobre o olho direito do usuário. Ao ser usado, um flash óptico transmite um dicionário inteiro à memória do usuário, melhorando permanentemente suas habilidades de fala.}
{50000}{}{Adv. Assault Rifle (HPFA)}
{50001}{}{A sucessora da AK-112, a AK-198 é um modelo militar moderno importado em quantidades limitadas para uso pelas Forças Especiais do Exército dos EUA. Capaz de disparar em modo único e automático. Esta variante é Automática de Alta Potência, na qual a rajada usa um pente inteiro. Força mín.: 5.}
{50100}{}{Cofre de Parede}
{50200}{}{Cofre de Chão}
{50300}{}{Módulo de Memória Azul}
{50301}{}{Um módulo de memória de computador somente leitura contendo informação médica. Este módulo detalha aprimoramentos de carisma.}
{50400}{}{Módulo de Memória Verde}
{50401}{}{Um módulo de memória de computador somente leitura contendo informação médica. Este módulo detalha aprimoramentos de percepção.}
{50500}{}{Módulo de Memória Vermelho}
{50501}{}{Um módulo de memória de computador somente leitura contendo informação médica. Este módulo detalha aprimoramentos de força.}
{50600}{}{Módulo de Memória Amarelo}
{50601}{}{Um módulo de memória de computador somente leitura contendo informação médica. Este módulo detalha aprimoramentos de inteligência.}
{50700}{}{Corpo em Decomposição}
{50701}{}{Este é o corpo parcialmente decomposto de uma criatura humanoide.}
{50800}{}{Boneca de Borracha}
{50801}{}{Uma boneca inflável de borracha. Este modelo se chama "Tandi".}
{50900}{}{Boneca de Borracha Danificada}
{50901}{}{Esta boneca inflável de borracha tem uma costura rasgada. Obviamente foi bastante usada.}
{51000}{}{Mesa de Sinuca}
{51100}{}{Mesa de Sinuca}
{51200}{}{Mesa de Sinuca}
{51300}{}{Mesa de Sinuca}
{51400}{}{Mesa de Sinuca}
{51500}{}{Mesa de Sinuca}
{51600}{}{Aprimorador Médico do Pip-Boy}
{51601}{}{Este aprimorador médico do Pip-Boy consiste num holodisco de armazenamento, um cabo de microfilamento, um capacete e um sensor óptico posicionado sobre o olho esquerdo do usuário. Ao ser usado, um flash óptico transmite um dicionário de habilidades e conhecimento médico à memória do usuário, melhorando permanentemente sua perícia de doutor.}
{51700}{}{"Pequeno Jesus"}
{51701}{}{Esta lâmina de aparência maligna já pertenceu ao Lil' Jesus Mordino. Tem inúmeros entalhes e cortes pela superfície, mas o fio é afiadíssimo. No cabo está gravado "Little Jesus".}
{51800}{}{Minigun Duplo}
{51801}{}{Usar somente para a criatura Canhão Automático.}
{51900}{}{Tampinhas de Garrafa}
{51901}{}{Estas são tampinhas de garrafa sem valor. Você ouviu dizer que um dia foram usadas como dinheiro, mas suspeita que seja só história.}
{52000}{}{Minigun Duplo Pesado}
{52001}{}{Usar somente para a criatura Canhão Automático.}
{52100}{}{Caixa de Esmolas}
{52101}{}{Uma pequena caixa usada para arrecadar dinheiro para os pobres.}
{52200}{}{Lâmina Wakizashi}
{52201}{}{Uma faca curta finamente trabalhada. A ponta parece ser projetada para perfurar armaduras.}
{52300}{}{Mapa de Levantamento}
{52301}{}{Parece um mapa de levantamento geológico da região da Baía.}
{52400}{}{Túnicas do Deserto}
{52401}{}{Esta peça de roupa fedorenta e imunda deve ser feita de algum tecido especial para ter aguentado os ambientes hostis do ermo profundo.}
{52500}{}{Seringa}
{52501}{}{Um instrumento de injeção médica de algum tipo. Parece de altíssima tecnologia. Você não sabe com o que está preenchido, mas parece restar apenas uma dose.}
{52600}{}{Camisa Vermelha Morto}
{52601}{}{Este cara tem um estranho uniforme vermelho que você nunca viu. Parece que morreu de desidratação.}
{52700}{}{Camisa Vermelha Morto}
{52701}{}{Este cara tem um estranho uniforme vermelho que você nunca viu. Parece que morreu de desidratação.}
{52800}{}{Camisa Vermelha Morto}
{52801}{}{Este cara tem um estranho uniforme vermelho que você nunca viu. Parece que morreu de desidratação.}
{52900}{}{Máquina de Mineração}
{53000}{}{Faca do Chefe Final}
{53100}{}{Arma de Plasma do Chefe Final}
{53200}{}{Baú da Motocicleta}
{53201}{}{O porta-malas é um ótimo lugar para guardar suas poucas coisas.}
{53300}{}{Sidecar}
{53301}{}{O sidecar permite outro passageiro. Além disso, é um ótimo lugar para guardar suas poucas coisas.}
{53400}{}{Chave da Motocicleta}
{53401}{}{Esta chave pertence a uma motocicleta Chrysalis.}
{53500}{}{Peças da Bomba}
{53501}{}{Bomba de hidropressurização, fio de bobina eletrofibroso, selo magnético de vácuo, régua de energia, adaptadores de três pinos para três pinos... e tanto de peças.}
{53600}{}{Traje do Vault}
{53601}{}{Um traje de vault comum. O número 13 está impresso nas costas.}
{53700}{}{Desidratação Fraca}
{53701}{}{NÃO USAR}
{53800}{}{Desidratação Forte}
{53801}{}{NÃO USAR}
{53900}{}{Pele de Gecko de Fogo}
{53901}{}{Este é o couro seco e curtido de um gecko de fogo. Está muito queimado e, por isso, tem pouco valor.}
