{100}{}{Barril de Metal em Chamas}
{101}{}{O barril contém papel em chamas e outros lixos inflamáveis.}
{200}{}{Porta de Madeira}
{201}{}{Uma porta, feita de madeira.}
{300}{}{Mesa de Madeira}
{301}{}{Uma mesa, feita de madeira.}
{400}{}{Mesa de Madeira}
{401}{}{Uma mesa, feita de madeira.}
{500}{}{Barril de Metal}
{501}{}{Um velho barril, feito de aço.}
{600}{}{Barril de Metal}
{601}{}{Um velho barril, feito de aço.}
{700}{}{Pilha de Pneus}
{701}{}{Uma pilha de antigos pneus de borracha. Eles vulcanizaram e endureceram, provavelmente devido ao calor.}
{800}{}{Porta de Segurança}
{801}{}{Esta porta parece muito segura. Ela fornece proteção dos elementos do mundo lá fora e de criaturas perigosas.}
{900}{}{Computador}
{901}{}{Um terminal de computador da Vault, plugado no computador principal da Vault.}
{1000}{}{Coluna}
{1001}{}{Uma coluna de suporte, fornecendo alívio do stress para o complexo inteiro.}
{1100}{}{Computador}
{1101}{}{Um terminal de computador da Vault, plugado no computador principal da Vault.}
{1200}{}{Computador}
{1201}{}{Um terminal de computador da Vault, plugado no computador principal da Vault.}
{1300}{}{Monitor}
{1301}{}{Um monitor de exibição de tela verde, mostrando vários bits de dados. Alguns bytes ocasionalmente se mostram.}
{1400}{}{Monitor}
{1401}{}{Um monitor de exibição de tela verde, mostrando vários bits de dados.}
{1500}{}{Holo-Gerador}
{1501}{}{Um tocador de fitas de entretenimento em grande escala. Nenhum filme novo foi feito em 80 anos.}
{1600}{}{Telas}
{1601}{}{Uma série de 3 monitores de exibição, mostrando vários bits de dados.}
{1700}{}{Telas}
{1701}{}{Um conjunto de 3 monitores de exibição, mostrando vários bits de dados da Vault.}
{1800}{}{Porta}
{1801}{}{Ainda é uma porta após examinação mais próxima.}
{1900}{}{Porta}
{1901}{}{Ainda é uma porta após examinação mais próxima.}
{2000}{}{Passagem}
{2001}{}{Uma passagem de ar, suprindo ar processado e limpo para o complexo inteiro da vault.}
{2100}{}{Passagem}
{2101}{}{Uma passagem de ar, suprindo ar processado e limpo para o complexo inteiro da vault.}
{2200}{}{Porta da Vault 13}
{2201}{}{Uma porta pesada, construída para sobreviver a todos os tipos de dano e trauma.}
{2300}{}{Porta da Vault 13}
{2301}{}{Uma porta pesada, construída para sobreviver a todos os tipos de dano e trauma.}
{2400}{}{Pedestal}
{2401}{}{Uma vida hidráulica, designada para ajudar a fornecer suporte, força e linhas de comunicação para a plataforma do Supervisor.}
{2500}{}{Monitor}
{2501}{}{Se você já viu um monitor, você viu todos eles.}
{2600}{}{Monitor}
{2601}{}{Um monitor de computador, exibindo vários bits de dados.}
{2700}{}{Barra de Ferro}
{2701}{}{Barra de ferro padrão da Vault-Tec, fornecendo uma base para o pedestal do Supervisor.}
{2800}{}{Canos}
{2801}{}{Alguns canos. Após examinação mais próxima, eles ainda são canos.}
{2900}{}{Passagem}
{2901}{}{Sistema de ventilação padrão da Vault-Tec.}
{3000}{}{Coluna}
{3001}{}{Um sistema de suporte de colunas padrão da Vault-Tec.}
{3100}{}{Coluna}
{3101}{}{Um sistema de suporte de colunas padrão da Vault-Tec.}
{3200}{}{Passagem}
{3201}{}{Sistema de ventilação padrão da Vault-Tec.}
{3300}{}{Passagem}
{3301}{}{Sistema de ventilação padrão da Vault-Tec.}
{3400}{}{Cama}
{3401}{}{Uma cama, ela parece bastante confortável conforme em que você tem estado dormindo.}
{3500}{}{Cama}
{3501}{}{Uma cama padrão. Parece confortável.}
{3600}{}{Cama}
{3601}{}{Uma cama padrão. Parece confortável.}
{3700}{}{Cama}
{3701}{}{Uma cama padrão. Parece confortável.}
{3800}{}{Elevador da Vault}
{3801}{}{Este é um elevador. Ele sobe e desce os níveis no complexo da Vault.}
{3900}{}{Cadeira}
{3901}{}{É uma cadeira. Muito ruim que você não tenha tempo para sentar e relaxar}
{4000}{}{Cadeira}
{4001}{}{É uma cadeira. Muito ruim que você não tenha tempo para sentar e relaxar}
{4100}{}{Cadeira}
{4101}{}{É uma cadeira. Muito ruim que você não tenha tempo para sentar e relaxar}
{4200}{}{Cadeira}
{4201}{}{É uma cadeira. Muito ruim que você não tenha tempo para sentar e relaxar}
{4300}{}{Monitor}
{4301}{}{Um monitor de computador, exibindo vários bits de dados.}
{4400}{}{Monitor}
{4401}{}{Um monitor de computador, exibindo vários bits de dados.}
{4500}{}{Monitor}
{4501}{}{Um monitor de computador, exibindo vários bits de dados.}
{4600}{}{Monitor}
{4601}{}{Um monitor de computador, exibindo vários bits de dados.}
{4700}{}{Monitor}
{4701}{}{Um monitor de computador, exibindo vários bits de dados.}
{4800}{}{Monitor}
{4801}{}{Um monitor de computador, exibindo vários bits de dados.}
{4900}{}{Marcador no Mapa da Grade de Saída}
{4901}{}{Marcador no Mapa da Grade de Saída}
{5000}{}{Unidade de Processamento de Ar}
{5001}{}{Uma UPA limpa o ar velho para fornecer o novo ar para o complexo, Esta está quebrada.}
{5100}{}{Cadeira}
{5101}{}{É uma cadeira. Muito ruim que você não tenha tempo para sentar e relaxar}
{5200}{}{Cadeira}
{5201}{}{É uma cadeira. Muito ruim que você não tenha tempo para sentar e relaxar}
{5300}{}{Cadeira}
{5301}{}{É uma cadeira. Muito ruim que você não tenha tempo para sentar e relaxar}
{5400}{}{Cadeira}
{5401}{}{É uma cadeira. Muito ruim que você não tenha tempo para sentar e relaxar}
{5500}{}{UEV}
{5501}{}{Esta Unidade de Exibição de Vídeos tem uma variedade de monitores de computador e outras telas.  Ela parece muito, muito ocupada.}
{5600}{}{UEV}
{5601}{}{Esta Unidade de Exibição de Vídeos tem uma variedade de monitores de computador e outras telas.  Ela parece muito, muito ocupada.}
{5700}{}{Cadeira}
{5701}{}{É uma cadeira. Ela parece muito confortável.}
{5800}{}{Cadeira}
{5801}{}{É uma cadeira. Ela parece muito confortável.}
{5900}{}{Cadeira}
{5901}{}{É uma cadeira. Ela parece muito confortável.}
{6000}{}{Cadeira}
{6001}{}{É uma cadeira. Ela parece muito confortável.}
{6100}{}{Mesa}
{6101}{}{É uma mesa. Antes das mesas, as pessoas tinham que manter suas coisas no chão.}
{6200}{}{Mesa}
{6201}{}{É definitivamente uma mesa..}
{6300}{}{Arbusto Rolante}
{6301}{}{É uma . Claro, você nunca viu uma viva de verdade antes. Melhor você manter um olho perto dela.}
{6400}{}{Cacto}
{6401}{}{Você não vê nada especial a respeito deste cacto.}
{6500}{}{Cacto}
{6501}{}{Você não vê nada importante a respeito deste cacto.}
{6600}{}{Árvore}
{6601}{}{Uma árvore morta. Nada cresce bem aqui.}
{6700}{}{Hex do Bloqueio Secreto}
{6701}{}{Se você consegue ver isto, culpe o designer técnico.}
{6800}{}{Escadas da Vault}
{6801}{}{Um conjunto de escadas.}
{6900}{}{Estalagmite}
{6901}{}{Uma extensão natural do chão da rocha.}
{7000}{}{Estalagmite}
{7001}{}{Uma extensão natural do chão da rocha.}
{7100}{}{Mancha de Sangue}
{7101}{}{Não há nada fora do ordinário com esta mancha de sangue. Exceto, claro, que alguém ou alguma coisa morreu aqui.}
{7200}{}{Coluna da Rocha}
{7201}{}{Esta coluna grossa de rocha se estende do chão até o teto.}
{7300}{}{Coluna da Rocha}
{7301}{}{Esta coluna fina de rocha se estende do chão até o teto.}
{7400}{}{Rochas}
{7401}{}{Você estuda as rochas por um tempo, mas elas nunca se movem.}
{7500}{}{Rochas}
{7501}{}{Você mantém um olho perto destas rochas, no caso de que elas se movam pra atacar você.}
{7600}{}{Chão da Parede do Carro}
{7601}{}{REMOVIDO}
{7700}{}{Teto da Parede do Carro}
{7701}{}{REMOVIDO}
{7800}{}{Rochas}
{7801}{}{Uma grande pilha de rochas. Elas parecem comuns a esta região.}
{7900}{}{Rochas}
{7901}{}{Uma pequena pilha de rochas.}
{8000}{}{Rochas}
{8001}{}{Uma pequena pilha de rochas.}
{8100}{}{Rochas}
{8101}{}{Uma grande pilha de rochas.}
{8200}{}{Ossos}
{8201}{}{Uma grande pilha de ossos de animais alvejados. Pelo menos, você pensa que todos os ossos são de animais...}
{8300}{}{Ossos}
{8301}{}{Uma grande pilha de ossos de animais alvejados. Pelo menos, você pensa que todos os ossos são de animais...}
{8400}{}{Ossos}
{8401}{}{Uma pilha muito grande de ossos alvejados. Você não consegue determinar a espécie do critters morto.}
{8500}{}{Ossos}
{8501}{}{Você acha que estes poderiam ser ossos de canguru com chifres, mas você não consegue ter certeza. Eles estão muitos   para fazer uma determinação final.}
{8600}{}{Ossos}
{8601}{}{Você vê os ossos de uma grande vaca de duas cabeças.}
{8700}{}{Portão}
{8701}{}{Um portão de madeira. Ele abre, e fecha, e abre, e fecha, é..}
{8800}{}{Baú de Gelo de Metal}
{8801}{}{REMOVIDO}
{8900}{}{Baú de Gelo de Metal}
{8901}{}{REMOVIDO}
{9000}{}{Rochas}
{9001}{}{Uma pilha muito grande de rochas. Elas parecem perigosas apenas assentadas ali.}
{9100}{}{Rochas}
{9101}{}{Uma grande pilha de rochas. Se você olhar atentamente, você consegue ver as faces de pequenos homens velhos nas pedras.}
{9200}{}{Rochas}
{9201}{}{Rochas, rochas, rochas! Em todo lugar que você olha, rochas!}
{9300}{}{Rochas}
{9301}{}{Uma pequena pilha de rochas..}
{9400}{}{Bar}
{9401}{}{Esta versão moderna de um alcohol still poderia generosamente ser chamada de uma micro-brewery.}
{9500}{}{Cadeira}
{9501}{}{Uma cadeira velha apodrecendo feita de um antigo assento de carro.}
{9600}{}{Cadeira}
{9601}{}{Uma velha cadeira fedida que costumava ser um assento de carro. The springs have lost their spring.}
{9700}{}{Cadeira}
{9701}{}{Uma velha cadeira fedida apodrecendo assentada nos tijolos por suporte. Parece bastante desconfortável.}
{9800}{}{Sofá}
{9801}{}{Uma velha cadeira fedida apodrecendo assentada nos tijolos por suporte. Parece bastante desconfortável.}
{9900}{}{Sofá}
{9901}{}{Um dispositivo para sentar de aparência muito desconfortável, as vezes conhecido como sofá.}
{10000}{}{Sofá}
{10001}{}{Um dispositivo para sentar de aparência muito desconfortável, as vezes conhecido como um sofá.}
{10100}{}{Pneu}
{10101}{}{Um velho pneu de borracha assentado no meio de algumas ervas-daninhas.}
{10200}{}{Arbusto}
{10201}{}{Algum tipo de erva-daninha do deserto.}
{10300}{}{Arbusto}
{10301}{}{Algum tipo de erva-daninha do deserto.}
{10400}{}{Arbusto}
{10401}{}{Algum tipo de erva-daninha do deserto.}
{10500}{}{Arbusto}
{10501}{}{Algum tipo de erva-daninha do deserto.}
{10600}{}{Lixo}
{10601}{}{É uma porta de carro enferrujada leaning num barril de metal enferrujado. A whole lot of rust is going on.}
{10700}{}{Lixo}
{10701}{}{Um toalete, meio enterrado na areia. A vida é uma mijadora, então você morre.}
{10800}{}{Ervas-daninhas}
{10801}{}{Algum tipo de arbusto do deserto. Se estava crescendo no passado recente, agora não está.}
{10900}{}{Lixo}
{10901}{}{Um pneu de carro, enterrado na areia. Alguns pequenos pedaços de madeira estão empilhado em volta dele.}
{11000}{}{Rochas}
{11001}{}{Com examinação mais próxima, você acha que estas poderiam ser realmente pedaços de madeira petrificada.}
{11100}{}{Pó}
{11101}{}{Uma pequena pilha de pó, com uma erva-daninha morta saindo dela.}
{11200}{}{Pó}
{11201}{}{Uma pequena pilha de pó.}
{11300}{}{Pó}
{11301}{}{Uma pequena pilha de pó.}
{11400}{}{Pó}
{11401}{}{Uma pequena pilha de pó.}
{11500}{}{Erva-Daninha}
{11501}{}{Uma pequena pilha de pó, com uma erva-daninha seca saindo dela.}
{11600}{}{Lixo}
{11601}{}{Um pedaço retorcido de metal enferrujado.}
{11700}{}{Lixo}
{11701}{}{Alguns pedaços quebrados de madeira.}
{11800}{}{Lixo}
{11801}{}{Uma pequena pilha de lixo ao acaso.}
{11900}{}{Pó}
{11901}{}{Uma pequena pilha de pó.}
{12000}{}{Pó}
{12001}{}{Uma pequena pilha de pó.}
{12100}{}{Pó}
{12101}{}{Uma pequena pilha de pó.}
{12200}{}{Pó}
{12201}{}{Uma pequena pilha de pó.}
{12300}{}{Pó}
{12301}{}{Uma pequena pilha de pó.}
{12400}{}{Pó}
{12401}{}{Uma pequena pilha de pó.}
{12500}{}{Erva-Daninha}
{12501}{}{Uma genérica erva-daninha do deserto.}
{12600}{}{Erva-Daninha}
{12601}{}{Uma genérica erva-daninha do deserto.}
{12700}{}{Erva-Daninha}
{12701}{}{Uma genérica erva-daninha do deserto.}
{12800}{}{Hex Bloqueante (SemLuz)}
{12900}{}{Parede}
{13000}{}{Parede}
{13100}{}{Parede}
{13200}{}{Parede}
{13300}{}{Parede}
{13400}{}{Parede}
{13500}{}{Dreno}
{13501}{}{Há algum tipo de cheiro rank, nojento vindo deste dreno de esgoto. Após alguns momentos não cheira tão mau.}
{13600}{}{Dreno}
{13601}{}{Você mal consegue perceber alguns movimentos atrás da grade cobrindo este dreno. Você consegue ver pequenos olhos vermelhos olhando de volta pra você. Olhos de rato.}
{13700}{}{Dreno}
{13701}{}{Sons de água gorgolejando vem deste dreno. Assim vem um fedor realmente vil.}
{13800}{}{Dreno}
{13801}{}{Sons de água gorgolejando vem além deste dreno. Assim vem um fedor realmente vil.}
{13900}{}{Escada da Mão}
{13901}{}{É uma escada velha, bastante frágil. Parece que mal suportará seu peso.}
{14000}{}{Buraco do Esgoto}
{14001}{}{Parece um buraco de acesso para o sistema de esgoto.}
{14100}{}{Fonte de Luz}
{14200}{}{Porta}
{14201}{}{Esta parece uma porta padrão de Vault que foi danificada, talvez queimada. Contudo, ainda está funcional.}
{14300}{}{Porta}
{14301}{}{Esta parece uma porta padrão de Vault que foi danificada, talvez queimada. Contudo, ainda está funcional.}
{14400}{}{Tampa}
{14401}{}{Um pesada tampa man-hole. Parece que está em boa forma e que foi recentemente movida.}
{14500}{}{Buraco}
{14501}{}{Um grande buraco foi explodido através desta porta.}
{14600}{}{Buraco}
{14601}{}{Um grande buraco foi explodido através desta porta.}
{14700}{}{Vidro a Prova de Balas}
{14701}{}{Vidro completamente inquebrável. Nem mesmo tente.}
{14800}{}{Vidro a Prova de Balas}
{14801}{}{Vidro completamente inquebrável. Nem mesmo tente.}
{14900}{}{Vidro a Prova de Balas}
{14901}{}{Vidro completamente inquebrável. Nem mesmo tente.}
{15000}{}{Vidro a Prova de Balas}
{15001}{}{Vidro completamente inquebrável. Nem mesmo tente.}
{15100}{}{Porta}
{15101}{}{Esta porta é um pedaço de construção de alta tecnologia. Ela abre dilatando conforme gira os três pedaços que constituem a porta.}
{15200}{}{Porta}
{15201}{}{Esta porta é um pedaço de construção de alta tecnologia. Ela abre dilatando conforme gira os três pedaços que constituem a porta.}
{15300}{}{Porta}
{15301}{}{Esta porta está decorada com o símbolo da Brotherhood of Steel.}
{15400}{}{Porta}
{15401}{}{Esta porta está decorada com o símbolo da Brotherhood of Steel.}
{15500}{}{Elevador}
{15501}{}{Este é o interior de um elevador da Brotherhood. It is squeaky clean!}
{15600}{}{Elevador}
{15601}{}{Este é o interior de um elevador da Brotherhood. It is squeaky clean!}
{15700}{}{Marcador}
{15701}{}{Este é o símbolo da Brotherhood of Steel. Este marcador diz a terra devastada que esta é a área deles, e pra sair imediatamente.}
{15800}{}{Monitor}
{15801}{}{Você vê um monitor de computador. Ele é feito da tecnologia da Brotherhood.}
{15900}{}{Monitor}
{15901}{}{Você vê um monitor de computador. Ele é feito da tecnologia da Brotherhood.}
{16000}{}{Computador}
{16001}{}{Este é um banco de dados da memória do computador. É obviamente tecnologia da Brotherhood.}
{16100}{}{Computador}
{16101}{}{Este é um banco de dados da memória do computador. É obviamente tecnologia da Brotherhood.}
{16200}{}{Computador}
{16201}{}{Um computador de alta tecnologia, usando modernos dispositivos de armazenagem          em vez dos antiquados carroçaões de ponto.}
{16300}{}{Computador}
{16301}{}{Um computador de alta tecnologia, usando modernos dispositivos de armazenagem          em vez dos antiquados carroçaões de ponto.}
{16400}{}{Monitor}
{16401}{}{Você vê um monitor de computador. Ele é feito da tecnologia da Brotherhood.}
{16500}{}{Monitor}
{16501}{}{Você vê um monitor de computador. Ele é feito da tecnologia da Brotherhood.}
{16600}{}{Fio}
{16601}{}{Algum tipo de instalação elétrica de computador.}
{16700}{}{Fio}
{16701}{}{Algum tipo de instalação elétrica de computador.}
{16800}{}{Fio}
{16801}{}{Algum tipo de instalação elétrica de computador.}
{16900}{}{Coluna}
{16901}{}{Uma coluna de suporte.}
{17000}{}{Coluna}
{17001}{}{Uma coluna de suporte.}
{17100}{}{Computador na Porta de Entrada}
{17101}{}{Este computador controla a grande porta da vault. Você tem que inserir um código de acesso específico para funcionar.}
{17200}{}{Sinal do Cassino}
{17201}{}{Parece um anúncio para o Cassino do Gizmo.}
{17300}{}{Porta Exterior da Vault 13}
{17301}{}{Esta grande porta é a ligação entre a vault e o mundo lá fora.}
{17400}{}{Porta Exterior da Vault 13}
{17401}{}{Esta grande porta é a ligação entre a vault e o mundo lá fora.}
{17500}{}{Sinal do Cassino}
{17501}{}{Esta parte do sinal contém um motor elétrico que está lentamente girando o sinal de neon anexado.}
{17600}{}{Seta pra Baixo}
{17700}{}{Seta pra Cima}
{17800}{}{Caixote}
{17900}{}{Caixote}
{18000}{}{Caixote}
{18100}{}{Topo do Elevador}
{18101}{}{Você está olhando para uma porção do elevador.}
{18200}{}{Console do Computador}
{18201}{}{Este é um terminal dumb, plugado por cabo a um grande computador. É tecnologia da Brotherhood.}
{18300}{}{Console do Computador}
{18301}{}{Este é um terminal dumb, plugado por cabo a um grande computador. É tecnologia da Brotherhood.}
{18400}{}{Emblema}
{18401}{}{O símbolo da Brotherhood. As engrenagens representam o conhecimento de engenharia deles, a espada é a vontade deles em defender a si próprios e as asas são a elevadora esperança.}
{18500}{}{Emblema}
{18501}{}{O símbolo da Brotherhood. As engrenagens representam o conhecimento de engenharia deles, a espada é a vontade deles em defender a si próprios e as asas são a elevadora esperança.}
{18600}{}{Sinal do Nível 'Um'}
{18601}{}{Você acha que isto poderia significar que você está no nível um da Brotherhood.}
{18700}{}{Sinal do Nível 'Dois'}
{18701}{}{Você está no nível dois da Brotherhood.}
{18800}{}{Sinal do Nível 'Três'}
{18801}{}{Isto deve significar que você está no nível três da Brotherhood.}
{18900}{}{Sinal do Nível 'Quatro'}
{18901}{}{Você deve estar no nível quatro da Brotherhood.}
{19000}{}{Cama Beliche}
{19001}{}{Uma cama beliche estilo militar. Parece muito desconfortável. Também parece que você poderia sacudir um quarto destes lençóis.}
{19100}{}{Cama Beliche}
{19101}{}{Uma cama beliche estilo militar. Parece muito desconfortável. Também parece que você poderia sacudir um quarto destes lençóis.}
{19200}{}{Cama Beliche}
{19201}{}{Uma cama beliche estilo militar. Parece muito desconfortável. Também parece que você poderia sacudir um quarto destes lençóis.}
{19300}{}{Caixote}
{19400}{}{Máquina de Nuka-Cola}
{19401}{}{O anúncio no lado desta máquina promove a soda popular deles.}
{19500}{}{Parede}
{19600}{}{Alçapão}
{19601}{}{Parece um alçapão perfeitamente bom.}
{19700}{}{Bueiro}
{19701}{}{A escada neste bueiro leva para a escuridão abaixo. Ohhh, assustador.}
{19800}{}{Altar}
{19801}{}{Este é um altar.}
{19900}{}{Púlpito}
{19901}{}{As pessoas ficam atrás disto e falam, Parece que tem um pequeno lugar para manter um discurso preparado.}
{20000}{}{Banco de Igreja}
{20001}{}{Isto parece com o que você esperaria. Nada especial a respeito deste banco de igreja.}
{20100}{}{Poste com Direções}
{20101}{}{O sinal neste poste parece um pouco enferrujado.}
{20200}{}{Poste com Direções}
{20201}{}{O sinal neste poste parece um pouco enferrujado.}
{20300}{}{Poste com Direções}
{20301}{}{O sinal neste poste parece um pouco enferrujado.}
{20400}{}{Poste com Direções}
{20401}{}{O sinal neste poste parece um pouco enferrujado.}
{20500}{}{Poste com Direções}
{20501}{}{O sinal neste poste parece um pouco enferrujado.}
{20600}{}{Colchão Velho}
{20601}{}{Um colchão velho e surrado. Você acha que vê algum tipo de bichinho parecido com inseto infestando-o.}
{20700}{}{Colchão Velho}
{20701}{}{Mesmo se você fosse dormir sozinho nesta coisa, você não estaria dormindo só.}
{20800}{}{Cama}
{20801}{}{Uma cama improvisada. O material foi tirado de alguma outra fonte.}
{20900}{}{Cama}
{20901}{}{Uma cama improvisada. O material foi tirado de alguma outra fonte.}
{21000}{}{Cama}
{21001}{}{Esta cama já viu dias melhores (e provavelmente noites também.)}
{21100}{}{Cama}
{21101}{}{Com examinação mais próxima, você determina que os lençóis não foram trocados há muito, muito longo tempo.}
{21200}{}{Cama}
{21201}{}{Há algumas manchas de origem duvidosa neste dispositivo para dormir bem gasto.}
{21300}{}{Cama}
{21301}{}{Esta cama viu muito uso. Algo deve ter rastejado entre os colchões e morrido também.}
{21400}{}{Estante para Livros}
{21500}{}{Estante para Livros}
{21600}{}{Estante para Livros}
{21700}{}{Estante para Livros}
{21800}{}{Estante para Livros}
{21900}{}{Estante para Livros}
{22000}{}{Caixas}
{22001}{}{Estas caixas de madeiras estão se despedaçando com o tempo.}
{22100}{}{Caixas}
{22101}{}{Você não acha detalhes dignos de mencionar sobre estas caixas de madeira.}
{22200}{}{Caixas}
{22201}{}{Você tem muito tempo nas suas mãos para estar olhando atentamente para este lixo apodrecido.}
{22300}{}{Caixas}
{22301}{}{Estas caixas de madeiras estão se despedaçando com o tempo.}
{22400}{}{Carro}
{22401}{}{Este automóvel está em terrível forma. Você não consegue pensar num modo de restaurá-lo.}
{22500}{}{Carro}
{22501}{}{Este pedaço enferrujado de metal para sucata não pode ser restaurado.}
{22600}{}{Carro}
{22601}{}{Você determina que este veículo nunca andará de novo. Realmente.}
{22700}{}{Carro}
{22701}{}{Não há modo de que este junkyard wannabe andará de novo.}
{22800}{}{Carro}
{22801}{}{Se o Mecânico do Ano de repente aparecesse próximo a você, ambos não conseguiriam consertar este lixo enferrujado.}
{22900}{}{Cadeira}
{22901}{}{Uma cadeira confortável.}
{23000}{}{Cadeira}
{23001}{}{Esta cadeira parece ter visto anos melhores.}
{23100}{}{Cadeira}
{23101}{}{Esta cadeira está moldy e gross. Conforme você pode advinhar, ela fede também.}
{23200}{}{Cadeira}
{23201}{}{Esta cadeira está despedaçando. Rapidamente.}
{23300}{}{Cadeira}
{23301}{}{Se alguém pagasse a você muitas tampinhas e você pudesse usar britches de aço, você poderia considerar sentar nesta cadeira.}
{23400}{}{Cadeira}
{23401}{}{Esta parece uma cadeira velha de escritório, ainda em muito boa forma após todos estes anos.}
{23500}{}{Cadeira}
{23501}{}{Esta é uma cadeira velha de escritório. Ela poderia até mesmo suportar o peso de uma pessoa.}
{23600}{}{Cadeira}
{23601}{}{Esta cadeira de escritório viu dias melhores. É lixo agora.}
{23700}{}{Cadeira}
{23701}{}{Esta parece uma cadeira que você veria nun escritório de um necrotério - morta.}
{23800}{}{Escrivaninha}
{23900}{}{Escrivaninha}
{24000}{}{Penteadeira}
{24100}{}{Penteadeira}
{24200}{}{Penteadeira}
{24300}{}{Hidrante}
{24301}{}{Este é um hidrante. Sem os sprinklers de teto da Vault, você poderia precisar de um destes para apagar os fogos.}
{24400}{}{Poste de Luz}
{24401}{}{Este poste de luz parece que ainda está em condição de funcionamento. Imagine isso, algo que funcione aqui.}
{24500}{}{Poste de Luz}
{24501}{}{Este poste de luz nunca funcionará de novo.}
{24600}{}{Poste de Luz}
{24601}{}{Este é um poste de luz que funciona. A noite, ele lança uma luz pálida, gentil que lembra você de absolutamente nada.}
{24700}{}{Poste de Luz}
{24701}{}{Este é um poste de luz quebrado. Não pode ser consertado.}
{24800}{}{Poste de Luz}
{24801}{}{Esta instalação de luz está operacional.}
{24900}{}{Poste de Luz}
{24901}{}{A luz neste poste de luz está despedaçada além de reparo.}
{25000}{}{Poste de Luz}
{25001}{}{Este é um poste de luz funcional.}
{25100}{}{Portão}
{25101}{}{A tranca neste portão foi jammed shut e as barras parecem muito fortes.}
{25200}{}{Lixo}
{25201}{}{Definitivamente lixo inútil, nenhuma dúvida a respeito.}
{25300}{}{Lixo}
{25301}{}{Definitivamente lixo inútil, nenhuma dúvida a respeito.}
{25400}{}{Lixo}
{25401}{}{Definitivamente lixo inútil, nenhuma dúvida a respeito.}
{25500}{}{Lixo}
{25501}{}{Definitivamente lixo inútil, nenhuma dúvida a respeito.}
{25600}{}{Lixo}
{25601}{}{Definitivamente lixo inútil, nenhuma dúvida a respeito.}
{25700}{}{Caixa de Correio}
{25701}{}{A caixa de correio está vazia. Você tem a sensação de que tem estado desse modo por algum tempo.}
{25800}{}{Porta}
{25801}{}{Uma porta de madeira lindamente esculpida, em boa condição.}
{25900}{}{Porta}
{25901}{}{Uma porta de madeira lindamente esculpida, em boa condição.}
{26000}{}{Porta}
{26001}{}{Uma porta de madeira lindamente esculpida, em boa condição.}
{26100}{}{Porta}
{26101}{}{Uma porta de madeira lindamente esculpida, em boa condição.}
{26200}{}{Banco de Igreja}
{26201}{}{Este banco de igreja de madeira está lentamente se despedaçando.}
{26300}{}{Banco de Igreja}
{26301}{}{Este banco de igreja foi negligenciado e está mostrando sinais de     .}
{26400}{}{Banco de Igreja}
{26401}{}{A banco de igreja de madeira que sucumbiu aos efeitos da idade e abuso.}
{26500}{}{Máquina de Jornais}
{26501}{}{A máquina de jornais está vazia.}
{26600}{}{Máquina de Jornais}
{26601}{}{A máquina de jornais está vazia.}
{26700}{}{Máquina de Jornais}
{26701}{}{A máquina de jornais está vazia.}
{26800}{}{Máquina de Jornais}
{26801}{}{A máquina de jornais está vazia.}
{26900}{}{Máquina de Jornais}
{26901}{}{A máquina de jornais está vazia.}
{27000}{}{Máquina de Jornais}
{27001}{}{A máquina de jornais está vazia. Parece que uma vez manteve revistas para adultos.}
{27100}{}{Lixo}
{27101}{}{Um colchão em condição terrível. Mesmo os ratos não dormirão nela.}
{27200}{}{Lixo}
{27201}{}{Um colchão gêmeo que viu muitos dias melhores do que este.}
{27300}{}{Lixo}
{27301}{}{Um pilha de madeira apodrecida e weathered. Não vale o seu peso em, bem, nada.}
{27400}{}{Lixo}
{27401}{}{Uma pilha de madeira, com alguns pregos inúteis enferrujados embutidos no fundo.}
{27500}{}{Caixas}
{27501}{}{Uma pilha de velhas caixas de papelão. Você não consegue acreditar que elas sobreviveram por este tempo.}
{27600}{}{Caixas}
{27601}{}{Uma pilha de velhas, caixas de papelão.}
{27700}{}{Lixo}
{27701}{}{Algum lixo que você poderia pensar ter sido um colchão antes que fosse destruído pelo ambiente.}
{27800}{}{Rochas}
{27900}{}{Rochas}
{28000}{}{Rochas}
{28100}{}{Escombros}
{28101}{}{Uma pequena pilha de pedras de entulho e rochas. Cuidado onde pisa!}
{28200}{}{Pia}
{28201}{}{Uma pia de porcelana que há muito perdeu a habilidade de funcionar.}
{28300}{}{Pia}
{28301}{}{Uma pia de porcelana quebrada. Há uma pequena poça de água marrom na bacia, com um rato morto flutuante.}
{28400}{}{Pia}
{28401}{}{Esta pia não está funcional. Você pode dizer isto da grande rachadura no meio.}
{28500}{}{Pia}
{28501}{}{Uma pia de porcelana quebrada. Há uma pequena poça de água marrom na bacia, com um rato morto flutuante.}
{28600}{}{Stop Sinal}
{28601}{}{Um sinal vermelho com a palavra PARE escrita em grande letras.}
{28700}{}{Stop Sinal}
{28701}{}{Um sinal vermelho com a palavra PARE escrita em grande letras. O grande buraco de bala foi adicionado após a fabricação.}
{28800}{}{Semáforo}
{28801}{}{Este é um antigo dispositivo de controle de tráfego de automóveis.}
{28900}{}{Semáforo}
{28901}{}{Este é um antigo dispositivo de controle de tráfego de automóveis.}
{29000}{}{Semáforo}
{29001}{}{Este é um antigo dispositivo de controle de tráfego de automóveis.}
{29100}{}{Luz de Rua}
{29101}{}{Esta luz de rua fornece iluminação após a noite cair ou em áreas escurecidas.}
{29200}{}{Luz de Rua}
{29201}{}{Esta luz de rua fornece iluminação após a noite cair ou em áreas escurecidas.}
{29300}{}{Luz de Rua}
{29301}{}{Esta luz de rua fornece iluminação após a noite cair ou em áreas escurecidas.}
{29400}{}{Luz de Rua}
{29401}{}{Esta luz de rua fornece iluminação após a noite cair ou em áreas escurecidas.}
{29500}{}{Luz de Rua}
{29501}{}{Esta luz de rua poderia fornecer iluminação em áreas escurecidas, se não estivesse completamente quebrada.}
{29600}{}{Luz de Rua}
{29601}{}{Esta luz de rua poderia fornecer iluminação em áreas escurecidas, se não estivesse completamente quebrada.}
{29700}{}{Luz de Rua}
{29701}{}{Esta luz de rua poderia fornecer iluminação em áreas escurecidas, se não estivesse completamente quebrada.}
{29800}{}{Poste com Direções}
{29801}{}{Este sinal deveria marcar qual a rua em que está, mas as letras desvaneceram na obscuridade.}
{29900}{}{Poste com Direções}
{29901}{}{Este sinal deveria marcar qual a rua em que está, mas as letras desvaneceram na obscuridade.}
{30000}{}{Mesa}
{30001}{}{Uma mesa de madeira, em condição boa a mediana.}
{30100}{}{Mesa}
{30101}{}{Uma mesa de madeira, em condição boa a mediana.}
{30200}{}{Mesa}
{30201}{}{Uma mesa de madeira, em condição mediana a pobre.}
{30300}{}{Mesa}
{30301}{}{Uma mesa de madeira, com superfície de plástico, que tem estado quebrada por um tempo.}
{30400}{}{Mesa}
{30401}{}{Uma mesa de madeira, pintada com uma côr verde de vômito, que está além do reparo.}
{30500}{}{Mesa}
{30501}{}{Esta parece uma velha mesa de café, baixa perto do chão para aqueles mutantes realmente baixos.}
{30600}{}{Mesa}
{30601}{}{Esta parece uma velha mesa de café, baixa perto do chão para aqueles mutantes realmente baixos.}
{30700}{}{Vaso Sanitário}
{30701}{}{As bordas afiadas em volta do assento fazem deste um lugar muito desconfortável para sentar.}
{30800}{}{Vaso Sanitário}
{30801}{}{Este vaso sanitário está quebrado.}
{30900}{}{Vaso Sanitário}
{30901}{}{Yuck! Quem quer que usou este por último não deu descarga!}
{31000}{}{Vaso Sanitário}
{31001}{}{Este vaso sanitário está quebrado e definitivamente não usável se você é uma mulher.}
{31100}{}{Lixo}
{31101}{}{Alguns canos destruídos meio-enterrados no pó. Nada importante para ver aqui. Mova-se.}
{31200}{}{Lixo}
{31201}{}{Alguns pedaços de vidros quebrados e outros pedaços arruinados de lixo.}
{31300}{}{Lixo}
{31301}{}{Alguns pedaços de vidros quebrados e outros pedaços arruinados de lixo.}
{31400}{}{Lixo}
{31401}{}{Um cano que foi partido no meio. Parece que enferrujou até que caiu sob o seu próprio peso.}
{31500}{}{Lata de Lixo}
{31501}{}{Uma lata de lixo. Você mal consegue ler o rótulo: Mantenha as ruas da sua cidade limpas!}
{31600}{}{Árvore}
{31601}{}{É uma árvore morta.}
{31700}{}{Árvore}
{31701}{}{Um toco. Nada realmente excitante. De fato, esta poderia ser a coisa menos excitante em que você botou os olhos.}
{31800}{}{Árvore}
{31801}{}{É uma árvore morta.}
{31900}{}{Árvore}
{32000}{}{Árvore}
{32100}{}{Árvore}
{32200}{}{Caminhão}
{32300}{}{Caminhão}
{32301}{}{Os restos arruinados de caminhão a diesel. Este pedaço de metal nunca se moverá de novo.}
{32400}{}{Caminhão}
{32401}{}{Este caminhão a diesel está além de ajuda. Bem além de ajuda.}
{32500}{}{Banheira}
{32501}{}{Esta banheira está quebrada e rachada.}
{32600}{}{Banheira}
{32601}{}{Com examinação mais próxima, você percebe que você não estará tomando o seu banho nesta banheira depois de tudo.}
{32700}{}{Mictório}
{32701}{}{É apenas um mictório.}
{32800}{}{Mictório}
{32801}{}{É apenas um mictório.}
{32900}{}{Mictório}
{32901}{}{É apenas um mictório. Nada especial.}
{33000}{}{Mictório}
{33001}{}{É apenas um mictório. Nada especial.}
{33100}{}{Tanque de Água}
{33101}{}{Um grande tanque que guarda líquidos. Neste caso, você acredita que foi designado para armazenar água.}
{33200}{}{Porta}
{33201}{}{Uma porta de madeira. Nada extremamente interessante sobre ela.}
{33300}{}{Porta}
{33301}{}{Uma porta de madeira. Ela fornece uma entrada e saída deste prédio.}
{33400}{}{Lâmpada da Parede}
{33401}{}{Esta lâmpada parece que está em boa condição de funcionamento.}
{33500}{}{Lâmpada da Parede}
{33501}{}{Uma lâmpada quebrada. Não é surpreendente que não funcione.}
{33600}{}{Lâmpada da Parede}
{33601}{}{Esta lâmpada parece que está em boa condição de funcionamento.}
{33700}{}{Lâmpada da Parede}
{33701}{}{Uma lâmpada quebrada. Não é surpreendente que não funcione.}
{33800}{}{Lâmpada da Parede}
{33801}{}{Esta lâmpada parece que está em boa condição de funcionamento.}
{33900}{}{Lâmpada da Parede}
{33901}{}{Uma lâmpada quebrada. Não é surpreendente que não funcione.}
{34000}{}{Lâmpada da Parede}
{34001}{}{Esta lâmpada parece que está em boa condição de funcionamento.}
{34100}{}{Lâmpada da Parede}
{34101}{}{Uma lâmpada quebrada. Não é surpreendente que não funcione.}
{34200}{}{Sinal para Dar a Preferência}
{34201}{}{Este era um sinal para controlar o fluxo do tráfego.}
{34300}{}{Sinal para Dar a Preferência}
{34301}{}{O sinal está desbotado, mas você consegue perceber a palavra YIELD (DAR A PREFERÊNCIA).}
{34400}{}{Hex Bloqueante Auto Invisível}
{34401}{}{Se você consegue ver isto, culpe o designer técnico.}
{34500}{}{Chão}
{34600}{}{Porta}
{34601}{}{Uma porta ornada de madeira. É obviamente feita da boa arte do artífice.}
{34700}{}{Banco de Igreja}
{34701}{}{Este assento é suportado por grande tijolos de concreto. Isso não é importante, mas você é aquele que olhou.}
{34800}{}{Escada}
{34801}{}{Esta escada leva para cima.}
{34900}{}{Escada}
{34901}{}{Esta escada leva para cima.}
{35000}{}{Escada}
{35001}{}{Esta escada leva para cima.}
{35100}{}{Escada}
{35101}{}{Esta escada leva para cima.}
{35200}{}{Escada}
{35201}{}{Esta escada leva para cima.}
{35300}{}{Escada}
{35301}{}{Esta escada leva para cima.}
{35400}{}{Escada}
{35401}{}{Esta escada leva para cima.}
{35500}{}{Escada}
{35501}{}{Esta escada leva para cima.}
{35600}{}{Escada}
{35601}{}{Esta escada leva pra baixo.}
{35700}{}{Parede}
{35701}{}{Você está olhando para o lado de fora da Catedral.}
{35800}{}{Parede}
{35801}{}{Você está olhando para o lado de fora da Catedral.}
{35900}{}{Parede}
{35901}{}{Você está olhando para o lado de fora da Catedral.}
{36000}{}{Parede}
{36001}{}{Você está olhando para o lado de fora da Catedral.}
{36100}{}{Cortina}
{36101}{}{Esta cortina parece que foi criada por meios primitivos mas ainda é muito funcional.}
{36200}{}{Cortina}
{36201}{}{Esta cortina parece que foi criada por meios primitivos mas ainda é muito funcional.}
{36300}{}{Tigela}
{36301}{}{Uma lindamente esculpida tigela de madeira. Esta parece que foi designada para esmagar e separar grãos.}
{36400}{}{Tigela}
{36401}{}{Uma lindamente esculpida tigela de madeira.}
{36500}{}{Pote}
{36501}{}{Um lindamente esculpido pote.}
{36600}{}{Planta}
{36601}{}{Parece um repolho que sofreu mutação para você. Parece estar se desenvolvendo bem no tempo quente.}
{36700}{}{Planta}
{36701}{}{Parece um repolho que sofreu mutação para você. Parece estar se desenvolvendo bem no tempo quente.}
{36800}{}{Carroça}
{36801}{}{Uma grosseira, mas efetiva, carroça agricultural.}
{36900}{}{Planta}
{36901}{}{Um pé de milho que sofreu mutação para você. Parece estar se desenvolvendo bem sob estas condições.}
{37000}{}{Planta}
{37001}{}{Um pé de milho que sofreu mutação para você. Parece estar se desenvolvendo bem sob estas condições.}
{37100}{}{Planta}
{37101}{}{Um pé de milho que sofreu mutação para você. Parece estar se desenvolvendo bem sob estas condições.}
{37200}{}{Pote}
{37201}{}{Um lindamente esculpido pote de argila.}
{37300}{}{Ancinho}
{37301}{}{Este ancinho é de propriedades dos seus donos. Você não consegue nem mesmo conceber um uso para ele.}
{37400}{}{Ancinho}
{37401}{}{Este ancinho é de propriedades dos seus donos. Você não consegue nem mesmo conceber um uso para ele.}
{37500}{}{Ancinho}
{37501}{}{Este ancinho é de propriedades dos seus donos. Você não consegue nem mesmo conceber um uso para ele.}
{37600}{}{Tapete}
{37601}{}{Um tapete simples. O(A) tecelão(ã) foi obviamente muito talentoso.}
{37700}{}{Tapete}
{37701}{}{Um tapete simples. O(A) tecelão(ã) foi obviamente muito talentoso.}
{37800}{}{Tapete}
{37801}{}{Um tapete simples. O(A) tecelão(ã) foi obviamente muito talentoso.}
{37900}{}{Pá}
{37901}{}{Esta pá é da propriedade de seus donos. Você não consegue nem mesmo conceber um uso para ela.}
{38000}{}{Pá}
{38001}{}{Esta pá é da propriedade de seus donos. Você não consegue nem mesmo conceber um uso para ela.}
{38100}{}{Pá}
{38101}{}{Esta pá é da propriedade de seus donos. Você não consegue nem mesmo conceber um uso para ela.}
{38200}{}{Vaso}
{38201}{}{Um vaso de barro muito bonito.}
{38300}{}{Poço}
{38301}{}{Tanto quanto você tente, você não consegue pensar de um jeito de mover este poço para a vault.}
{38400}{}{Mastro}
{38401}{}{Este mastro ajuda a suportar o yurt.}
{38500}{}{Mastro}
{38501}{}{Este mastro ajuda a suportar o yurt.}
{38600}{}{Mastro}
{38601}{}{Este mastro ajuda a suportar o yurt.}
{38700}{}{Mastro}
{38701}{}{Este mastro ajuda a suportar o yurt.}
{38800}{}{Mastro}
{38801}{}{Este mastro ajuda a suportar o yurt.}
{38900}{}{Mastro}
{38901}{}{Este mastro ajuda a suportar o yurt.}
{39000}{}{Porta da Vault}
{39001}{}{Esta porta de vault é agora apenas um pedaço pesado de metal para sucata.}
{39100}{}{Parede}
{39101}{}{O mecanismo para abrir e fechar a porta pesada da vault foi danificado além do reparo.}
{39200}{}{Escora}
{39201}{}{Esta escora ajuda a suportar a parede defensiva.}
{39300}{}{Escora}
{39301}{}{Esta escora ajuda a suportar a parede defensiva.}
{39400}{}{Escora}
{39401}{}{Esta escora ajuda a suportar a parede defensiva.}
{39500}{}{Escora}
{39501}{}{Esta escora ajuda a suportar a parede defensiva.}
{39600}{}{Barril de Metal}
{39601}{}{Um barril de metal enferrujado. Está vazio.}
{39700}{}{Barril de Metal}
{39701}{}{Este barril está provavelmente vazio por causa do som oco.}
{39800}{}{Barris de Metal}
{39801}{}{Estes barris estão provavelmente vazios por causa do som oco deles.}
{39900}{}{Barris de Metal}
{39901}{}{Estes barris estão provavelmente vazios por causa do som oco deles.}
{40000}{}{Cúpula}
{40001}{}{Você acha um pequeno rótulo que diz: "Propriedade da Área-51. Retorne se achado."}
{40100}{}{Caixote}
{40101}{}{Um caixote de madeira. Não parece estar ruim de forma.}
{40200}{}{Caixote}
{40201}{}{Um simples caixote de madeira. Em condição razoavelmente boa.}
{40300}{}{Caixote}
{40301}{}{Este simples caixote de madeira caiu sob o seu próprio peso.}
{40400}{}{Escrivaninha}
{40401}{}{Uma escrivaninha simples com um computador.}
{40500}{}{Escrivaninha}
{40501}{}{Uma escrivaninha simples com um computador.}
{40600}{}{Porta}
{40601}{}{Uma porta de madeira, em forma razoável.}
{40700}{}{Desmoronamento}
{40701}{}{Uma grande quantidade de rocha, de longe mais do que poderia ser movida facilmente.}
{40800}{}{Carro}
{40801}{}{Este carro submergido não pode ser reparado.}
{40900}{}{Carro}
{40901}{}{Este carro está um pouco molhado e não pode ser reparado.}
{41000}{}{Carro}
{41001}{}{Este carro foi mal estacionado. Infelizmente, ele está além do reparo.}
{41100}{}{Lixo}
{41101}{}{Este lixo foi arruinado pela água do mar contaminada.}
{41200}{}{Lixo}
{41201}{}{Este lixo foi quase washed away.}
{41300}{}{Lixo}
{41301}{}{Uma seleção por escolha de lixo inútil.}
{41400}{}{Canos}
{41401}{}{Estes canos costumavam transferir combustível de um tanque no subsolo para a garagem. Eles não foram usados em muito tempo.}
{41500}{}{Cano}
{41501}{}{Estes canos costumavam transferir combustível de um tanque no subsolo para a garagem. Eles não foram usados em muito tempo.}
{41600}{}{Canos}
{41601}{}{Estes canos costumavam transferir combustível de um tanque no subsolo para a garagem. Eles não foram usados em muito tempo.}
{41700}{}{Poço do Elevador}
{41701}{}{Parte de um sistema de elevator.}
{41800}{}{Poço do Elevador}
{41801}{}{Um poço de elevador que stretches deep into the ground. Foi danificado.}
{41900}{}{Elevador}
{41901}{}{Um elevador. Use-o para subir e descer entre os níveis.}
{42000}{}{Poço do Elevador}
{42001}{}{Um poço de elevador que stretches deep into the ground. Foi danificado.}
{42100}{}{Porta do Elevador}
{42101}{}{Esta porta leva ao carro do elevador. Se você quer usar o elevador, você deve primeiro abrir esta porta.}
{42200}{}{Cano}
{42201}{}{Um cano de metal. Detalhes adicionais não são importantes.}
{42300}{}{Pó}
{42400}{}{Caixa}
{42500}{}{Caixa}
{42600}{}{Caixa}
{42700}{}{Caixa}
{42800}{}{Rochas}
{42801}{}{Uma pilha de rochas. Não muito interessante.}
{42900}{}{Rochas}
{42901}{}{Uma pilha de rochas. Não muito interessante.}
{43000}{}{Rochas}
{43001}{}{Uma pequena pilha de rochas. Nem ao mínimo interessante para você.}
{43100}{}{Rochas}
{43101}{}{Uma pilha muito pequena de rochas.}
{43200}{}{Rochas}
{43201}{}{Uma pilha muito pequena de rochas.}
{43300}{}{Rochas}
{43301}{}{Uma pilha muito pequena de rochas.}
{43400}{}{Rochas}
{43401}{}{Uma pilha muito pequena de rochas.}
{43500}{}{Rochas}
{43501}{}{Uma pilha muito pequena de rochas.}
{43600}{}{Porta da Vault}
{43601}{}{Esta porta de vault é muito similar a aquela da Vault-13. O mecanismo da porta foi desativado.}
{43700}{}{Porta}
{43701}{}{Uma lindamente construída porta de madeira, reforçada com adornos de metal ornados de um design quase hipnótico.}
{43800}{}{Porta}
{43801}{}{Uma lindamente construída porta de madeira, reforçada com adornos de metal ornados de um design quase hipnótico.}
{43900}{}{Tanques}
{43901}{}{Um complexo de algum tipo. Você não tem certeza, mas você consegue ver grandes tanques de uma gosma esverdeada que parece vagamente importante.}
{44000}{}{Tanques}
{44001}{}{Um complexo de algum tipo. Você não tem certeza, mas você consegue ver grandes tanques de uma gosma esverdeada que parece vagamente importante.}
{44100}{}{Tanques}
{44101}{}{Um complexo de algum tipo. Você não tem certeza, mas você consegue ver grandes tanques de uma gosma esverdeada que parece vagamente importante.}
{44200}{}{Tanques}
{44201}{}{Um complexo de algum tipo. Você não tem certeza, mas você consegue ver grandes tanques de uma gosma esverdeada que parece vagamente importante.}
{44300}{}{Tanques}
{44301}{}{Um complexo de algum tipo. Você não tem certeza, mas você consegue ver grandes tanques de uma gosma esverdeada que parece vagamente importante.}
{44400}{}{Tanques}
{44401}{}{Um complexo de algum tipo. Você não tem certeza, mas você consegue ver grandes tanques de uma gosma esverdeada que parece vagamente importante.}
{44500}{}{Tanques}
{44501}{}{Um complexo de algum tipo. Você não tem certeza, mas você consegue ver grandes tanques de uma gosma esverdeada que parece vagamente importante.}
{44600}{}{Tanques}
{44601}{}{Um complexo de algum tipo. Você não tem certeza, mas você consegue ver grandes tanques de uma gosma esverdeada que parece vagamente importante.}
{44700}{}{Parede}
{44800}{}{Porta}
{44801}{}{Uma porta de segurança. Looks heavily armored.}
{44900}{}{Ogiva Nuclear}
{45000}{}{Poço}
{45001}{}{Tanto quanto você tente, você não consegue pensar de um jeito de mover este poço para a vault.}
{45100}{}{Mesa de Dados}
{45101}{}{Esta é uma mesa de jogo.}
{45200}{}{Mesa de Dados}
{45201}{}{Esta é uma mesa de jogo.}
{45300}{}{Mesa de Dados}
{45301}{}{Esta é uma mesa de jogo.}
{45400}{}{Mesa de Dados}
{45401}{}{Esta é uma mesa de jogo.}
{45500}{}{Mesa de Dados}
{45501}{}{Esta é uma mesa de jogo.}
{45600}{}{Mesa de Dados}
{45601}{}{Esta é uma mesa de jogo.}
{45700}{}{Mesa de Dados}
{45701}{}{Esta é uma mesa de jogo.}
{45800}{}{Mesa de Dados}
{45801}{}{Esta é uma mesa de jogo.}
{45900}{}{Mesa de Dados}
{45901}{}{Esta é uma mesa de jogo.}
{46000}{}{Mesa de Dados}
{46001}{}{Esta é uma mesa de jogo.}
{46100}{}{Rocha}
{46101}{}{Uma rocha pequena, completamente desinteressante no contexto desta estória.}
{46200}{}{Rocha}
{46300}{}{Rocha}
{46400}{}{Rocha}
{46500}{}{Máquina de Slots}
{46501}{}{Esta é uma máquina de jogo.}
{46600}{}{Máquina de Slots}
{46601}{}{Esta é uma máquina de jogo.}
{46700}{}{Vão da Porta}
{46800}{}{Elevador}
{46900}{}{Elevador}
{47000}{}{Porta do Elevador}
{47100}{}{Janela}
{47101}{}{Em vez de vidro, esta janela está usando papel de cêra.}
{47200}{}{Janela}
{47201}{}{Em vez de vidro, esta janela está usando papel de cêra.}
{47300}{}{Janela}
{47301}{}{Em vez de vidro, esta janela está usando papel de cêra.}
{47400}{}{Janela}
{47401}{}{Em vez de vidro, esta janela está usando papel de cêra.}
{47500}{}{Porta}
{47501}{}{Esta grande porta que rola de metal foi emperrada por dentro.}
{47600}{}{Porta}
{47601}{}{Esta grande porta que rola de metal foi emperrada por dentro.}
{47700}{}{Porta}
{47701}{}{Esta grande porta que rola de metal foi emperrada por dentro. Ela diz APENAS CARREGAMENTO.}
{47800}{}{Porta}
{47801}{}{Esta grande porta que rola de metal foi emperrada por dentro.}
{47900}{}{Porta}
{47901}{}{Esta grande porta que rola de metal foi emperrada por dentro.}
{48000}{}{Porta}
{48001}{}{Esta grande porta que rola de metal foi emperrada por dentro. Ela diz APENAS CARREGAMENTO.}
{48100}{}{Porta}
{48101}{}{Esta porta parece suspeitosamente como a porta que você acharia em um depósito.}
{48200}{}{Porta}
{48201}{}{Esta porta parece suspeitosamente como a porta que você acharia em um depósito.}
{48300}{}{Cata-Vento}
{48301}{}{Este simples weather vane ajuda o povo de Shady Sands a estudar o tempo.}
{48400}{}{Altar}
{48401}{}{Um altar simples feito de madeira pintada.}
{48500}{}{Pódio}
{48501}{}{Este pódio é normal, exceto pelo símbolo das Crianças da Catedral esculpido na frente dele.}
{48600}{}{Altar}
{48700}{}{Monitor}
{48701}{}{Um grande monitor, preto e branco apenas. A recepção é muito boa por estar dentro da catedral sem uma antena.}
{48800}{}{Monitor}
{48801}{}{Um grande monitor, preto e branco apenas. A figura de manto está recitando dogma religioso a um passo fervoroso.}
{48900}{}{Campo de Força}
{48901}{}{Este é um poderoso campo de energia.}
{49000}{}{Campo de Força}
{49001}{}{Este é um poderoso campo de energia.}
{49100}{}{Campo de Força}
{49101}{}{Este é um poderoso campo de energia.}
{49200}{}{Campo de Força}
{49201}{}{Este é um poderoso campo de energia.}
{49300}{}{Mesa}
{49301}{}{Uma razoavelmente ordinária mesa de madeira.}
{49400}{}{Mesa}
{49401}{}{Uma razoavelmente ordinária mesa de madeira.}
{49500}{}{Mesa}
{49501}{}{Uma razoavelmente ordinária mesa de madeira.}
{49600}{}{Mesa}
{49601}{}{Uma razoavelmente ordinária mesa de madeira.}
{49700}{}{Mesa}
{49701}{}{Uma razoavelmente ordinária mesa de madeira.}
{49800}{}{Mesa}
{49801}{}{Uma razoavelmente ordinária mesa de madeira.}
{49900}{}{Estante}
{50000}{}{Estante}
{50100}{}{Estante}
{50200}{}{Estante}
{50300}{}{Estante}
{50400}{}{Estante}
{50500}{}{Altar}
{50501}{}{Um altar simples feito de madeira pintada.}
{50600}{}{Altar}
{50601}{}{Um altar simples feito de madeira pintada.}
{50700}{}{Altar}
{50701}{}{Um altar simples feito de madeira pintada.}
{50800}{}{Altar}
{50801}{}{Um altar simples feito de madeira pintada.}
{50900}{}{Escombros}
{50901}{}{Uma seção desmoronada do telhado formou esta pilha de escombros. Sua corda leva de volta a superfície.}
{51000}{}{Estante para Livros}
{51100}{}{Estante para Livros}
{51200}{}{Estante para Livros}
{51300}{}{Estante para Livros}
{51400}{}{Estante para Livros}
{51500}{}{Estante para Livros}
{51600}{}{Mesa}
{51601}{}{Esta grande mesa parece importante. Talvez eles mantiveram reuniões aqui?}
{51700}{}{Mesa}
{51701}{}{Esta grande mesa parece importante. Talvez eles mantiveram reuniões aqui?}
{51800}{}{Mesa}
{51801}{}{Esta grande mesa parece importante. Talvez eles mantiveram reuniões aqui?}
{51900}{}{Mesa}
{51901}{}{Esta grande mesa parece importante. Talvez eles mantiveram reuniões aqui?}
{52000}{}{Mesa}
{52001}{}{Esta grande mesa parece importante. Talvez eles mantiveram reuniões aqui?}
{52100}{}{Mesa}
{52101}{}{Esta grande mesa parece importante. Talvez eles mantiveram reuniões aqui?}
{52200}{}{Altar}
{52201}{}{Um altar desenhado e usado pela Brotherhood of Steel. O símbolo deles é mostrado descaradamente.}
{52300}{}{Altar}
{52301}{}{Um altar desenhado e usado pela Brotherhood of Steel. O símbolo deles é mostrado descaradamente.}
{52400}{}{Altar}
{52401}{}{Um altar desenhado e usado pela Brotherhood of Steel. O símbolo deles é mostrado descaradamente.}
{52500}{}{Banco de Igreja}
{52501}{}{Um lindamente fashioned e de aparência desconfortável e poderoso, banco de igreja.}
{52600}{}{Pódio}
{52601}{}{Um pódio de madeira bacana. Há uma tela de tele-prompter construída nele, de frente para o orador.}
{52700}{}{Vagão}
{52701}{}{Um vagão da caravana convertido dos restos destroçados de um antigo automóvel.}
{52800}{}{Vagão}
{52801}{}{Um vagão da caravana convertido dos restos destroçados de um antigo automóvel.}
{52900}{}{Vagão}
{52901}{}{Um vagão da caravana convertido dos restos destroçados de um antigo automóvel.}
{53000}{}{Vagão}
{53001}{}{Um vagão da caravana convertido dos restos destroçados de um antigo automóvel.}
{53100}{}{Vagão}
{53101}{}{Um vagão da caravana convertido dos restos destroçados de um antigo automóvel.}
{53200}{}{Vagão}
{53201}{}{Um vagão da caravana convertido dos restos destroçados de um antigo automóvel.}
{53300}{}{Esteira}
{53301}{}{Uma esteira de treinamento.}
{53400}{}{Esteira}
{53401}{}{Uma esteira de treinamento.}
{53500}{}{Esteira}
{53501}{}{Uma esteira de treinamento.}
{53600}{}{Esteira}
{53601}{}{Uma esteira de treinamento.}
{53700}{}{Saco de Pancada}
{53701}{}{Este é um saco de pancada StrongMan(tm).}
{53800}{}{Piso da Escada}
{53801}{}{Uma máquina de exercícios.}
{53900}{}{Piso da Escada}
{54000}{}{Esteira}
{54001}{}{Uma máquina de exercícios.}
{54100}{}{Esteira}
{54101}{}{Uma máquina de exercícios.}
{54200}{}{Supino}
{54201}{}{Uma máquina de exercícios.}
{54300}{}{Supino}
{54301}{}{Uma máquina de exercícios.}
{54400}{}{Ponte}
{54401}{}{Uma ponta de madeira construída as pressas que permite o acesso sobre o fosso de gosma brilhante verde.}
{54500}{}{Ponte}
{54501}{}{Uma ponta de madeira construída as pressas que permite o acesso sobre o fosso de gosma brilhante verde.}
{54600}{}{Mesa da Roleta}
{54601}{}{Esta é uma mesa de jogo.}
{54700}{}{Mesa da Roleta}
{54701}{}{Esta é uma mesa de jogo.}
{54800}{}{Mesa da Roleta}
{54801}{}{Esta é uma mesa de jogo.}
{54900}{}{Mesa da Roleta}
{54901}{}{Esta é uma mesa de jogo.}
{55000}{}{Mesa da Roleta}
{55001}{}{Esta é uma mesa de jogo.}
{55100}{}{Barril}
{55101}{}{Este barril de metal vazio tem o símbolo trefoil nuclear pintado no lado da tinta amarela brilhante.}
{55200}{}{Barril}
{55201}{}{Este barril contém um pouco de gosma brilhante verde. O símbolo trefoil nuclear dá uma pista do que a gosma poderia ser.}
{55300}{}{Computador}
{55301}{}{Um computador de aparência muito moderna.}
{55400}{}{Computador}
{55401}{}{Um computador de aparência muito moderna.}
{55500}{}{Tanque de Suspensão}
{55501}{}{Algum tipo de aparato médicou ou experimental, parece como se pudesse conter um corpo humano ou de tamanho maior.}
{55600}{}{Tanque de Suspensão Quebrado}
{55601}{}{Um pedaço quebrado de equipamento. Está além do reparo.}
{55700}{}{Mainframe}
{55701}{}{Um grande super computador. Provavelmente o computador de aparência mais rápida que você já viu.}
{55800}{}{Plataforma de Suporte}
{55801}{}{Esta plataforma suporta o grande super computador sobre os tanques de resfriamento.}
{55900}{}{Não use}
{56000}{}{Não use}
{56100}{}{Cama}
{56101}{}{Uma cama beliche estilo militar. Parece muito desconfortável. Também parece que você poderia sacudir um quarto destes lençóis.}
{56200}{}{Cama}
{56201}{}{Uma cama beliche estilo militar. Parece muito desconfortável. Também parece que você poderia sacudir um quarto destes lençóis.}
{56300}{}{Cama}
{56301}{}{Uma cama beliche estilo militar. Parece muito desconfortável. Também parece que você poderia sacudir um quarto destes lençóis.}
{56400}{}{Fio}
{56401}{}{Parece com um cabo serial de algum tipo.}
{56500}{}{Fio}
{56501}{}{Parece com um cabo serial de algum tipo.}
{56600}{}{Sinal}
{56601}{}{O sinal diz BAR. Isso deveria ser bastante auto-evidente.}
{56700}{}{Viga}
{56701}{}{Este beam forte está estacionado sobre o buraco da cratera.}
{56800}{}{Viga}
{56801}{}{Há uma corda seguramente anexada ao beam. Parece que você pode descer a cratera agora.}
{56900}{}{Estantes}
{56901}{}{Você vê algumas estantes de metal muito vazias.}
{57000}{}{Estantes}
{57001}{}{Você vê algumas estantes de metal muito vazias.}
{57100}{}{Estantes}
{57101}{}{Você vê algumas estantes de metal muito vazias.}
{57200}{}{Estantes}
{57201}{}{Você vê algumas estantes de metal muito vazias.}
{57300}{}{Arbusto}
{57301}{}{Uma erva-daninha do deserto de algum tipo. Não importante para esta estória.}
{57400}{}{Arbusto}
{57401}{}{Uma erva-daninha do deserto de algum tipo.}
{57500}{}{Arbusto}
{57501}{}{Uma erva-daninha do deserto de algum tipo.}
{57600}{}{Chão}
{57601}{}{Uma vista bacana das Boneyards deste nível da torre. Você tem uma sensação boa de quão alto no céu você está.}
{57700}{}{Chão}
{57701}{}{Uma vista bacana das Boneyards deste nível da torre.}
{57800}{}{Parede}
{57801}{}{Uma boa visão do lado de fora da Catedral.}
{57900}{}{Parede}
{57901}{}{Uma boa visão do lado de fora da Catedral.}
{58000}{}{Parede}
{58001}{}{Uma boa visão do lado de fora da Catedral.}
{58100}{}{Porta}
{58101}{}{Uma porta que parece perfeitamente em casa numa cela.}
{58200}{}{Sinal}
{58201}{}{Este sinal diz que esta loja é chamada Darkwater's.}
{58300}{}{Escada da Mão}
{58301}{}{Esta escada de mão leva para a escuridão abaixo.}
{58400}{}{Escada da Mão}
{58401}{}{Esta escada de mão leva para a escuridão abaixo.}
{58500}{}{Maquinaria}
{58501}{}{Parece uma velha máquina de impressão ou manufacturing doohikey.}
{58600}{}{Maquinaria}
{58601}{}{Parece uma velha máquina de impressão ou manufacturing doohikey.}
{58700}{}{Maquinaria}
{58701}{}{Parece uma velha máquina de impressão ou manufacturing doohikey.}
{58800}{}{Maquinaria}
{58801}{}{Parece uma velha máquina de impressão ou manufacturing doohikey.}
{58900}{}{Maquinaria}
{58901}{}{Parece uma velha máquina de impressão ou manufacturing doohikey.}
{59000}{}{Maquinaria}
{59001}{}{Parece uma velha máquina de impressão ou manufacturing doohikey.}
{59100}{}{Mesa}
{59101}{}{Esta mesa de metal parece em condição boa. Há um dreno no centro dela.}
{59200}{}{Mesa}
{59201}{}{Esta mesa de metal parece em condição boa. Há um dreno no centro dela.}
{59300}{}{Mesa}
{59301}{}{A mesa de metal está coberta por algum tipo de bio-massa.}
{59400}{}{Mesa}
{59401}{}{A mesa de metal está coberta por algum tipo de bio-massa.}
{59500}{}{Mesa}
{59501}{}{A mesa de metal está coberta por algum tipo de bio-massa.}
{59600}{}{Quadro de Boletins}
{59601}{}{Notas para emprego estão stapled no quadro. Parece bem usado.}
{59700}{}{Guarita}
{59701}{}{Este guard shack tem aproximadamente 100 anos de idade, mas ainda em excelente condição.}
{59800}{}{Sinal}
{59801}{}{Este sinal diz: Armazém.}
{59900}{}{Sinal}
{59901}{}{Este sinal diz: Armazém.}
{60000}{}{Sinal}
{60001}{}{Este sinal diz: Mercado}
{60100}{}{Poça de Lôdo}
{60101}{}{Parece muito não saudável. Você poderia querer usar trunks de nadar com armadura antes de dar um mergulho.}
{60200}{}{Poça de Lôdo}
{60201}{}{Parece muito não saudável. Você poderia querer usar trunks de nadar com armadura antes de dar um mergulho.}
{60300}{}{Poça de Lôdo}
{60301}{}{Parece muito não saudável. Você poderia querer usar trunks de nadar com armadura antes de dar um mergulho.}
{60400}{}{Mesa}
{60401}{}{Uma mesa de metal de aparência bacana.}
{60500}{}{Mesa}
{60501}{}{Uma mesa de metal de aparência bacana.}
{60600}{}{Mesa}
{60601}{}{Uma mesa de metal de aparência bacana.}
{60700}{}{Mesa}
{60701}{}{Uma mesa de metal de aparência bacana.}
{60800}{}{Mesa}
{60801}{}{Este mesa de metal não foi tratada bem. A ferrugem é muito pervasiva.}
{60900}{}{Mesa}
{60901}{}{Uma mesa de metal de boa aparência, exceto pela ferrugem.}
{61000}{}{Mesa}
{61001}{}{Uma mesa de metal de boa aparência, exceto pela ferrugem.}
{61100}{}{Mesa}
{61101}{}{Uma mesa de metal de boa aparência, exceto pela ferrugem.}
{61200}{}{Poço de Fogo}
{61201}{}{O fogo está queimando.}
{61300}{}{Espelho}
{61301}{}{Você olha pra si próprio por um tempo.}
{61400}{}{Espelho}
{61401}{}{Você olha fixamente para a sua imagem no espelho por um temp.}
{61500}{}{Pia}
{61501}{}{Uma pia completamente funcional. Bacana e limpa também.}
{61600}{}{Vaso Sanitário}
{61601}{}{Este vaso sanitário está muito limpo. Ele funciona também.}
{61700}{}{Mictório}
{61701}{}{Este mictório está funcional.}
{61800}{}{Vaso Sanitário}
{61801}{}{Se você tivesse um fetish por vasos sanitários, então este seria um bom vaso sanitário.}
{61900}{}{Pia}
{61901}{}{Esta pia está em condição perfeita.}
{62000}{}{Mictório}
{62001}{}{Este urinal está em condição perfeita.}
{62100}{}{Chuveiro}
{62101}{}{Um chuveiro estilo militar. Não é pra ser usado por pessoas modestas.}
{62200}{}{Chuveiro}
{62201}{}{Um chuveiro estilo militar. Não é pra ser usado por pessoas modestas.}
{62300}{}{Chuveiro}
{62301}{}{Um chuveiro estilo militar. Não é pra ser usado por pessoas modestas.}
{62400}{}{Chuveiro}
{62401}{}{Um chuveiro estilo militar. Não é pra ser usado por pessoas modestas.}
{62500}{}{Chuveiro}
{62501}{}{Um chuveiro estilo militar. Não é pra ser usado por pessoas modestas.}
{62600}{}{Chuveiro}
{62601}{}{Um chuveiro estilo militar. Não é pra ser usado por pessoas modestas.}
{62700}{}{Cama}
{62701}{}{Uma cama de aparência muito confortável.}
{62800}{}{Cama}
{62801}{}{Uma cama de aparência muito confortável.}
{62900}{}{Cama}
{62901}{}{Uma cama beliche estruturalmente melhorada.}
{63000}{}{Cama}
{63001}{}{Uma cama beliche estruturalmente melhorada.}
{63100}{}{Cama}
{63101}{}{Uma cama beliche estruturalmente melhorada.}
{63200}{}{Terminal}
{63300}{}{Terminal}
{63400}{}{Bandeira}
{63401}{}{Esta bandeira é o símbolo das Crianças da Catedral.}
{63500}{}{Bandeira}
{63501}{}{Esta bandeira é o símbolo das Crianças da Catedral.}
{63600}{}{Bandeira}
{63601}{}{Esta bandeira é o símbolo das Crianças da Catedral.}
{63700}{}{Computador}
{63701}{}{Um grande computador.}
{63800}{}{Computador}
{63801}{}{Um grande computador.}
{63900}{}{Computador}
{63901}{}{Um grande computador.}
{64000}{}{Terminal}
{64001}{}{O terminal para um grande computador.}
{64100}{}{Corpo Morto}
{64101}{}{Parece como se esta pessoa morreu muito dolorosamente.}
{64200}{}{Corpo Morto}
{64201}{}{Parece como se esta pessoa morreu muito dolorosamente.}
{64300}{}{Corpo Morto}
{64301}{}{Parece como se esta pessoa morreu muito dolorosamente.}
{64400}{}{Corpo Morto}
{64401}{}{Parece como se esta pessoa morreu muito dolorosamente.}
{64500}{}{Porta}
{64501}{}{Este barred door works well as the door to a jail cell.}
{64600}{}{Terminal}
{64700}{}{Terminal}
{64800}{}{Empilhadeira}
{64801}{}{A empilhadeira está inoperante.}
{64900}{}{Empilhadeira}
{64901}{}{A empilhadeira está inoperante.}
{65000}{}{Equipamento}
{65100}{}{Mesa Médica}
{65101}{}{Esta mesa está muito enferrujada. O dreno no centro da mesa está clogged.}
{65200}{}{Mesa Médica}
{65201}{}{Esta mesa está muito enferrujada.}
{65300}{}{Portão}
{65301}{}{Este portão tem uma barra que levanta e desce.}
{65400}{}{Cano}
{65500}{}{Cano}
{65600}{}{Gerador de Força}
{65601}{}{Um gerador de força da Wattz ElectroBox. Bastante padrão como os geradores de apoio antes da guerra.}
{65700}{}{Tanque}
{65701}{}{Um grande tanque de água. Parece bem mantido, o que é provavelmente uma coisa boa.}
{65800}{}{Caixa da Polícia}
{65801}{}{Uma caixa da polícia da Inglaterra, aproximadamente de 1960.}
{65900}{}{Mesa}
{65901}{}{Uma mesa feita lindamente. Feita a mão, mas parece muito mais bacana do que qualquer mesa que você já viu antes.}
{66000}{}{Mesa}
{66001}{}{Uma mesa feita lindamente. Feita a mão, mas parece muito mais bacana do que qualquer mesa que você já viu antes.}
{66100}{}{Mesa}
{66101}{}{Uma mesa feita lindamente. Feita a mão, mas parece muito mais bacana do que qualquer mesa que você já viu antes.}
{66200}{}{Cadeira}
{66201}{}{Uma cadeira de aparência muito bacana.}
{66300}{}{Cadeira}
{66301}{}{Uma cadeira de aparência muito bacana.}
{66400}{}{Cadeira}
{66401}{}{Uma cadeira de aparência muito bacana.}
{66500}{}{Cadeira}
{66501}{}{Uma cadeira de aparência muito bacana.}
{66600}{}{Cadeira}
{66601}{}{Uma cadeira de aparência muito bacana.}
{66700}{}{Cadeira}
{66701}{}{Uma cadeira de aparência muito bacana.}
{66800}{}{Cadeira}
{66801}{}{Uma cadeira de aparência muito bacana.}
{66900}{}{Cadeira}
{66901}{}{Uma cadeira de aparência muito bacana.}
{67000}{}{Cadeira}
{67001}{}{Uma cadeira de aparência muito bacana.}
{67100}{}{Cadeira}
{67101}{}{Uma cadeira de aparência muito bacana.}
{67200}{}{Cadeira}
{67201}{}{Uma cadeira de aparência muito bacana.}
{67300}{}{Cadeira}
{67301}{}{Uma cadeira de aparência muito bacana.}
{67400}{}{Cadeira}
{67401}{}{Uma cadeira de aparência muito bacana.}
{67500}{}{Cadeira}
{67501}{}{Uma cadeira de aparência muito bacana.}
{67600}{}{Cadeira}
{67601}{}{Uma cadeira de aparência muito bacana.}
{67700}{}{Cadeira}
{67701}{}{Uma cadeira de aparência muito bacana.}
{67800}{}{Cama}
{67801}{}{Uma cama de aparência muito bacana.}
{67900}{}{Cama}
{67901}{}{Uma cama de aparência muito bacana.}
{68000}{}{Cama}
{68001}{}{Uma cama de aparência muito bacana.}
{68100}{}{Cama}
{68101}{}{Uma cama de aparência muito bacana.}
{68200}{}{Fogão}
{68201}{}{Um fogão funcional que queima madeira.}
{68300}{}{Fogão}
{68301}{}{Um fogão funcional que queima madeira.}
{68400}{}{Fogão}
{68401}{}{Um fogão funcional que queima madeira.}
{68500}{}{Fogão}
{68501}{}{Um fogão funcional que queima madeira.}
{68600}{}{Poste Quebrado}
{68700}{}{Entrada Destruída}
{68800}{}{Rochas}
{68801}{}{Uma grande formação de rochas. Esta não foi uma ocorrência natural.}
{68900}{}{Rochas}
{68901}{}{Uma grande formação de rochas. Esta não foi uma ocorrência natural.}
{69000}{}{Vaso Sanitário}
{69001}{}{Um grosseiro, mas efetivo vaso sanitário. Há algumas folhas largadas no buraco para gerenciar o odor.}
{69100}{}{Montanha}
{69101}{}{Estas paredes na montanha parecem muito inacessíveis.}
{69200}{}{Montanha}
{69201}{}{Estas paredes na montanha parecem muito inacessíveis.}
{69300}{}{Montanha}
{69301}{}{Estas paredes na montanha parecem muito inacessíveis.}
{69400}{}{Montanha}
{69401}{}{Estas paredes na montanha parecem muito inacessíveis.}
{69500}{}{Montanha}
{69501}{}{Estas paredes na montanha parecem muito inacessíveis.}
{69600}{}{Montanha}
{69601}{}{Estas paredes na montanha parecem muito inacessíveis.}
{69700}{}{Gosma}
{69701}{}{Você vê uma estranha gosma biológica nociva.}
{69800}{}{Gosma}
{69801}{}{Você vê uma estranha gosma biológica nociva.}
{69900}{}{Gosma}
{69901}{}{Você vê uma estranha gosma biológica nociva.}
{70000}{}{Gosma}
{70001}{}{Você vê uma estranha gosma biológica nociva.}
{70100}{}{Gosma}
{70101}{}{Você vê uma estranha gosma biológica nociva.}
{70200}{}{Gosma}
{70201}{}{Você vê uma estranha gosma biológica nociva.}
{70300}{}{Gosma}
{70301}{}{Você vê uma estranha gosma biológica nociva.}
{70400}{}{Gosma}
{70401}{}{Você vê uma estranha gosma biológica nociva.}
{70500}{}{Gosma}
{70501}{}{Você vê uma estranha gosma biológica nociva.}
{70600}{}{Gosma}
{70601}{}{Você vê uma estranha gosma biológica nociva.}
{70700}{}{Gosma}
{70701}{}{Você vê uma estranha gosma biológica nociva.}
{70800}{}{Gosma}
{70801}{}{Você vê uma estranha gosma biológica nociva.}
{70900}{}{Gosma}
{70901}{}{Você vê uma estranha gosma biológica nociva.}
{71000}{}{Gosma}
{71001}{}{Você vê uma estranha gosma biológica nociva.}
{71100}{}{Gosma}
{71101}{}{Você vê uma estranha gosma biológica nociva.}
{71200}{}{Gosma}
{71201}{}{Você vê uma estranha gosma biológica nociva.}
{71300}{}{Gosma}
{71301}{}{Você vê uma estranha gosma biológica nociva.}
{71400}{}{Gosma}
{71401}{}{Você vê uma estranha gosma biológica nociva.}
{71500}{}{Gosma}
{71501}{}{Você vê uma estranha gosma biológica nociva.}
{71600}{}{Gosma}
{71601}{}{Você vê uma estranha gosma biológica nociva.}
{71700}{}{Gosma}
{71701}{}{Você vê uma estranha gosma biológica nociva.}
{71800}{}{Gosma}
{71801}{}{Você vê uma estranha gosma biológica nociva.}
{71900}{}{Gosma}
{71901}{}{Você vê uma estranha gosma biológica nociva.}
{72000}{}{Gosma}
{72001}{}{Você vê uma estranha gosma biológica nociva.}
{72100}{}{Gosma}
{72101}{}{Você vê uma estranha gosma biológica nociva.}
{72200}{}{Gosma}
{72201}{}{Você vê uma estranha gosma biológica nociva.}
{72300}{}{Gosma}
{72301}{}{Você vê uma estranha gosma biológica nociva.}
{72400}{}{Gosma}
{72401}{}{Você vê uma estranha gosma biológica nociva.}
{72500}{}{Gosma}
{72501}{}{Você vê uma estranha gosma biológica nociva.}
{72600}{}{Gosma}
{72601}{}{Você vê uma estranha gosma biológica nociva.}
{72700}{}{Gosma}
{72701}{}{Você vê uma estranha gosma biológica nociva.}
{72800}{}{Gosma}
{72801}{}{Você vê uma estranha gosma biológica nociva.}
{72900}{}{Gosma}
{72901}{}{Você vê uma estranha gosma biológica nociva.}
{73000}{}{Gosma}
{73001}{}{Você vê uma estranha gosma biológica nociva.}
{73100}{}{Gosma}
{73101}{}{Você vê uma estranha gosma biológica nociva.}
{73200}{}{Gosma}
{73201}{}{Você vê uma estranha gosma biológica nociva.}
{73300}{}{Gosma}
{73301}{}{Você vê uma estranha gosma biológica nociva.}
{73400}{}{Gosma}
{73401}{}{Você vê uma estranha gosma biológica nociva.}
{73500}{}{Gosma}
{73501}{}{Você vê uma estranha gosma biológica nociva.}
{73600}{}{Gosma}
{73601}{}{Você vê uma estranha gosma biológica nociva.}
{73700}{}{Gosma}
{73701}{}{Você vê uma estranha gosma biológica nociva.}
{73800}{}{Gosma}
{73801}{}{Você vê uma estranha gosma biológica nociva.}
{73900}{}{Gosma}
{73901}{}{Você vê uma estranha gosma biológica nociva.}
{74000}{}{Gosma}
{74001}{}{Você vê uma estranha gosma biológica nociva.}
{74100}{}{Gosma}
{74101}{}{Você vê uma estranha gosma biológica nociva.}
{74200}{}{Gosma}
{74201}{}{Você vê uma estranha gosma biológica nociva.}
{74300}{}{Gosma}
{74301}{}{Você vê uma estranha gosma biológica nociva.}
{74400}{}{Gosma}
{74401}{}{Você vê uma estranha gosma biológica nociva.}
{74500}{}{Gosma}
{74501}{}{Você vê uma estranha gosma biológica nociva.}
{74600}{}{Gosma}
{74601}{}{Você vê uma estranha gosma biológica nociva.}
{74700}{}{Gosma}
{74701}{}{Você vê uma estranha gosma biológica nociva.}
{74800}{}{Gosma}
{74801}{}{Você vê uma estranha gosma biológica nociva.}
{74900}{}{Computador}
{74901}{}{A quantidade de gosma neste computador torna muito difícil acessá-lo.}
{75000}{}{Computador}
{75001}{}{A quantidade de gosma neste computador torna muito difícil acessá-lo.}
{75100}{}{Computador}
{75101}{}{A quantidade de gosma neste computador torna muito difícil acessá-lo.}
{75200}{}{Computador}
{75201}{}{A quantidade de gosma neste computador torna muito difícil acessá-lo.}
{75300}{}{Computador}
{75301}{}{A quantidade de gosma neste computador torna muito difícil acessá-lo.}
{75400}{}{Computador}
{75401}{}{A quantidade de gosma neste computador torna muito difícil acessá-lo.}
{75500}{}{Computador}
{75501}{}{A quantidade de gosma neste computador torna muito difícil acessá-lo.}
{75600}{}{Computador}
{75601}{}{A quantidade de gosma neste computador torna muito difícil acessá-lo.}
{75700}{}{Computador}
{75701}{}{A quantidade de gosma neste computador torna muito difícil acessá-lo.}
{75800}{}{Computador}
{75801}{}{A quantidade de gosma neste computador torna muito difícil acessá-lo.}
{75900}{}{Computador}
{75901}{}{A quantidade de gosma neste computador torna muito difícil acessá-lo.}
{76000}{}{Computador}
{76001}{}{A quantidade de gosma neste computador torna muito difícil acessá-lo.}
{76100}{}{Monitores}
{76101}{}{Você não consegue ler qualquer coisa no monitor devido a quantidade de gosma espirrada pelas telas.}
{76200}{}{Monitores}
{76201}{}{Você não consegue ler qualquer coisa no monitor devido a quantidade de gosma espirrada pelas telas.}
{76300}{}{Monitores}
{76301}{}{Você não consegue ler qualquer coisa no monitor devido a quantidade de gosma espirrada pelas telas.}
{76400}{}{Monitores}
{76401}{}{Você não consegue ler qualquer coisa no monitor devido a quantidade de gosma espirrada pelas telas.}
{76500}{}{Chão}
{76501}{}{Você juraria que há algo se movendo no chão.}
{76600}{}{Pedestal}
{76601}{}{O pedestal parece como se estivesse respirando lentamente pra dentro e pra fora.}
{76700}{}{Chão}
{76800}{}{Bomba}
{76801}{}{Esta é uma bomba nuclear. Parece muito perigosa apenas assentada ali.}
{76900}{}{Base de Suporte}
{76901}{}{Esta base cradles a bomba nuclear que está assentada nela.}
{77000}{}{Console do Computador}
{77001}{}{Este é um computador de acesso nuclear. O computador parece muito seguro. Há um slot para uma chave estranhamente moldada.}
{77100}{}{Fios}
{77101}{}{Estes fios estão conectando a bomba ao computador.}
{77200}{}{Cadeira}
{77201}{}{Não há nada incomum a respeito desta cadeira.}
{77300}{}{Cadeira}
{77301}{}{Não há nada incomum a respeito desta cadeira.}
{77400}{}{Cadeira}
{77401}{}{Não há nada incomum a respeito desta cadeira.}
{77500}{}{Cadeira}
{77501}{}{Não há nada incomum a respeito desta cadeira.}
{77600}{}{Cadeira}
{77601}{}{Não há nada incomum a respeito desta cadeira.}
{77700}{}{Cadeira}
{77701}{}{Não há nada incomum a respeito desta cadeira.}
{77800}{}{Cadeira}
{77801}{}{Não há nada incomum a respeito desta cadeira.}
{77900}{}{Cadeira}
{77901}{}{Não há nada incomum a respeito desta cadeira.}
{78000}{}{Pilar}
{78001}{}{Um pilar de suporte.}
{78100}{}{Pilar}
{78101}{}{Um pilar de suporte.}
{78200}{}{Pilar}
{78201}{}{Um pilar de suporte.}
{78300}{}{Pilar}
{78301}{}{Um pilar de suporte.}
{78400}{}{Cama}
{78401}{}{Este cama está em condição wretched.}
{78500}{}{Cama}
{78501}{}{Este cama está em condição muito pobre.}
{78600}{}{Cama}
{78601}{}{Este cama está em condição condição pobre.}
{78700}{}{Cama}
{78701}{}{Este cama está em condição muito ruim.}
{78800}{}{Monitores}
{78801}{}{Estes monitores estão quebrados e não podem funcionar.}
{78900}{}{Monitores}
{78901}{}{Estes monitores estão quebrados e não podem funcionar.}
{79000}{}{Monitores}
{79001}{}{Estes monitores estão quebrados e não podem funcionar.}
{79100}{}{Monitores}
{79101}{}{Estes monitores estão quebrados e não podem funcionar.}
{79200}{}{Passagem}
{79201}{}{Muito pouco ar fresco está vindo desta passagem.}
{79300}{}{Passagem}
{79301}{}{Quase nenhum ar fresco está vindo desta passagem.}
{79400}{}{Passagem}
{79401}{}{Nenhum ar fresco está vindo desta passagem.}
{79500}{}{Passagem}
{79501}{}{Apenas uma pequena quantia de ar fresco está vindo desta passagem.}
{79600}{}{Mesa}
{79601}{}{Não há nada incomum a respeito desta mesa, exceto que ela está quase destruída.}
{79700}{}{Mesa}
{79701}{}{Esta mesa foi horrivelmente danificada.}
{79800}{}{Mesa}
{79801}{}{Esta mesa está em condição muito pobre.}
{79900}{}{Mesa}
{79901}{}{Não há razão para procurar nesta mesa.}
{80000}{}{Monitores}
{80001}{}{As telas de exibição neste banco de monitores foram destruídas.}
{80100}{}{Monitores}
{80101}{}{As telas de exibição neste banco de monitores foram danificadas além do reparo.}
{80200}{}{Monitor}
{80201}{}{A tela do monitor está rachada e destruída.}
{80300}{}{Monitor}
{80301}{}{Este monitor is worthless com uma tela de exibição quebrada.}
{80400}{}{Computador}
{80401}{}{Este computador está quebrado.}
{80500}{}{Computador}
{80501}{}{Este computador está quebrado.}
{80600}{}{Computador}
{80601}{}{Este computador está quebrado.}
{80700}{}{Cadeira}
{80701}{}{Esta cadeira está arruinada.}
{80800}{}{Cadeira}
{80801}{}{Esta cadeira está arruinada.}
{80900}{}{Cadeira}
{80901}{}{Esta cadeira está arruinada.}
{81000}{}{Cadeira}
{81001}{}{Esta cadeira está arruinada.}
{81100}{}{Passagem}
{81101}{}{Esta passagem foi danificada além do reparo.}
{81200}{}{Passagem}
{81201}{}{Esta passagem está danificada e não pode ser reparada.}
{81300}{}{Passagem}
{81301}{}{Esta passagem não está funcionando de modo algum.}
{81400}{}{Computador}
{81401}{}{Este computador parece que mal está funcional.}
{81500}{}{Computador}
{81501}{}{Este computador parece que mal está funcional.}
{81600}{}{Monitor}
{81601}{}{O monitor mal está funcionando.}
{81700}{}{Monitor}
{81701}{}{O monitor mal está funcionando.}
{81800}{}{Computador}
{81801}{}{O computador não está funcionando.}
{81900}{}{Computador}
{81901}{}{O computador não está funcionando.}
{82000}{}{Monitor}
{82001}{}{O monitor não está funcionando.}
{82100}{}{Monitor}
{82101}{}{O monitor não está funcionando.}
{82200}{}{Vão da Porta}
{82201}{}{Parece um vão de porta muito bacana. Ele faz o trabalho de segurar uma porta muito bem.}
{82300}{}{Monitores}
{82301}{}{Os monitores estão em boa condição.}
{82400}{}{Monitores}
{82401}{}{Os monitores estão em boa condição.}
{82500}{}{Parede}
{82600}{}{Porta do Banco}
{82601}{}{Uma porta de vault de banco bem robusta. A porta parece muito segura.}
{82700}{}{Luz}
{82701}{}{Uma luz de segurança.}
{82800}{}{Luz}
{82801}{}{Uma luz de segurança.}
{82900}{}{Pilar}
{82901}{}{Este pilar é o pedaço do show da praça de Shady Sands. Ele diz estórias para lembrar o povo da esperança e paz.}
{83000}{}{Receptáculo do Robô}
{83001}{}{Este is a robot recharging bay. When not in service, robots will dock here to shut down and recharge.}
{83100}{}{Receptáculo do Robô}
{83101}{}{Este is a robot recharging bay. When not in service, robots will dock here to shut down and recharge.}
{83200}{}{Receptáculo do Robô}
{83201}{}{Este is a robot recharging bay. When not in service, robots will dock here to shut down and recharge.}
{83300}{}{Receptáculo do Robô}
{83301}{}{Este is a robot recharging bay. When not in service, robots will dock here to shut down and recharge.}
{83400}{}{Receptáculo do Robô}
{83401}{}{Este is a robot recharging bay. When not in service, robots will dock here to shut down and recharge.}
{83500}{}{Máquina}
{83501}{}{Esta máquina tem algo a ver com as baías de serviço dos robôs. Não parece particularmente interessante.}
{83600}{}{Máquina}
{83601}{}{Esta máquina tem algo a ver com as baías de serviço dos robôs. Não parece muito interessante.}
{83700}{}{Listras}
{83800}{}{Listras}
{83900}{}{Listras}
{84000}{}{Listras}
{84100}{}{Listras}
{84200}{}{Listras}
{84300}{}{Listras}
{84400}{}{Listras}
{84500}{}{Listras}
{84600}{}{Listras}
{84700}{}{Listras}
{84800}{}{Porta}
{84801}{}{Uma porta de madeira muito normal.}
{84900}{}{Porta}
{84901}{}{Uma porta de madeira muito normal.}
{85000}{}{Porta}
{85001}{}{Uma porta de madeira muito normal.}
{85100}{}{Sinal}
{85101}{}{Este sign stands for Companhia de Empréstimos Amistosos.}
{85200}{}{Emblema}
{85201}{}{Este emblema é usado pelos Seguidores do Apocalipse.}
{85300}{}{Mesa Médica}
{85301}{}{Esta parece uma mesa de examinação médica.}
{85400}{}{Sinal}
{85401}{}{Falcão Maltês}
{85500}{}{Grafite}
{85600}{}{Grafite}
{85700}{}{Grafite}
{85800}{}{Grafite}
{85900}{}{Grafite}
{86000}{}{Grafite}
{86100}{}{Grafite}
{86200}{}{Grafite}
{86300}{}{Grafite}
{86400}{}{Grafite}
{86500}{}{Grafite}
{86600}{}{Grafite}
{86700}{}{Grafite}
{86800}{}{Grafite}
{86900}{}{Sinal}
{86901}{}{Ele diz: ARMAS. Eles poderiam vender armas ali.}
{87000}{}{Sinal}
{87001}{}{O sinal diz: Polícia.}
{87100}{}{Sinal}
{87101}{}{Este é o sinal dos Far Go Traders.}
{87200}{}{Sinal}
{87201}{}{Este sinal está rotulado: Gunrunners.}
{87300}{}{Sinal}
{87301}{}{Este é o sinal da companhia de comércio Crimson Caravan.}
{87400}{}{Sinal}
{87401}{}{O sinal diz: Hospital. Isto poderia ser uma coisa boa.}
{87500}{}{Sinal}
{87501}{}{Este é o sinal da Crash House.}
{87600}{}{Sinal}
{87601}{}{Este sinal muito unlikely diz: Mercado de Carros Pré-Possuídos do Bob.}
{87700}{}{Sinal}
{87701}{}{Este é o sinal dos Mercadores das Águas, um companhia de comércio do Hub.}
{87800}{}{Casca do Ovo}
{87801}{}{Pedaços de uma casca de ovo quebrada.}
{87900}{}{Casca do Ovo}
{87901}{}{Pedaços de uma casca de ovo quebrada.}
{88000}{}{Casca do Ovo}
{88001}{}{Pedaços de uma casca de ovo quebrada.}
{88100}{}{Casca do Ovo}
{88101}{}{Pedaços de uma casca de ovo quebrada.}
{88200}{}{Casca do Ovo}
{88201}{}{Pedaços de uma casca de ovo quebrada.}
{88300}{}{Casca do Ovo}
{88301}{}{Pedaços de uma casca de ovo quebrada.}
{88400}{}{Casca do Ovo}
{88401}{}{Pedaços de uma casca de ovo quebrada.}
{88500}{}{Casca do Ovo}
{88501}{}{Pedaços de uma casca de ovo quebrada.}
{88600}{}{Poste de Luz}
{88601}{}{Um poste de luz. Parece que está em boa ordem de funcionamento.}
{88700}{}{Sinal}
{88701}{}{O sinal diz: Motel.}
{88800}{}{Cogumelos}
{88801}{}{Esta mesa planter foi preenchido com dung e os cogumelos estão crescendo felizmente nela.}
{88900}{}{Cogumelos}
{88901}{}{Esta mesa planter has been filled with dung e os cogumelos estão crescendo felizmente nela.}
{89000}{}{Esqueleto}
{89100}{}{Sinal}
{89101}{}{O sinal diz: Cadeia.}
{89200}{}{Sinal}
{89201}{}{Este é o sinal do bar Poço da Eskória e casa de loucos.}
{89300}{}{Sinal}
{89301}{}{Um anúncio para as Blades Blades-brand razor.}
{89400}{}{Chuveiro}
{89401}{}{Um chuveiro bastante normal.}
{89500}{}{Chuveiro}
{89501}{}{Um chuveiro bastante normal.}
{89600}{}{Sinal}
{89601}{}{Este é o sinal do the Companhia de Empréstimos Amistosos.}
{89700}{}{Sinal}
{89701}{}{Este é o sinal do the Companhia de Empréstimos Amistosos.}
{89800}{}{Pôster}
{89801}{}{Este é um pôster de filme para um filme de horror dos dias pré-Guerra.}
{89900}{}{Pôster}
{89901}{}{Este é um pôster de filme para um filme de horror dos dias pré-Guerra.}
{90000}{}{Bar}
{90001}{}{Há uma urna assentada neste bar. A urna parece um pouco beat up, mas poderia ser valiosa.}
{90100}{}{Poço do Elevador}
{90101}{}{O poço tem uma corda pendurada lá de cima.}
{90200}{}{Poço do Elevador}
{90201}{}{O poço tem uma corda pendurada na beirada.}
{90300}{}{Cama Médica}
{90301}{}{Esta cama tem um monitor embutido para monitorar o progresso dos pacientes.}
{90400}{}{Bomba D'água}
{90401}{}{Este é um pedaço de maquinaria que bombeia água lá de baixo.}
{90500}{}{Cama Médica}
{90501}{}{Esta cama tem um monitor embutido para monitorar o progresso dos pacientes.}
{90600}{}{Partes da Power Armor}
{90601}{}{Estas são as partes para uma suíte de Power Armor.}
{90700}{}{Luz}
{90701}{}{Esta luz de segurança está atualmente pulsando um vermelho brilhante.}
{90800}{}{Luz}
{90801}{}{Esta luz de segurança está atualmente pulsando um vermelho brilhante.}
{90900}{}{Símbolo}
{91000}{}{Símbolo}
{91100}{}{Símbolo}
{91200}{}{Símbolo}
{91300}{}{Símbolo}
{91400}{}{Símbolo}
{91500}{}{Corda}
{91600}{}{Corda}
{91700}{}{Corda}
{91800}{}{Corda}
{91900}{}{Corda}
{92000}{}{Corda}
{92100}{}{Corda}
{92200}{}{Corda}
{92300}{}{Desfiladeiro}
{92400}{}{Desfiladeiro}
{92500}{}{Desfiladeiro}
{92600}{}{Desfiladeiro}
{92700}{}{Desfiladeiro}
{92800}{}{Desfiladeiro}
{92900}{}{Desfiladeiro}
{93000}{}{Desfiladeiro}
{93100}{}{Chão da Caverna}
{93200}{}{Porta Impenetrável}
{93201}{}{Esta porta parece não ter mecanismo de abertura.}
{93300}{}{Porta Destruída}
{93301}{}{A porta foi arrombada por explosão.}
{93400}{}{Porta}
{93401}{}{Uma porta com uma fechadura intrincada.}
{93500}{}{Tocha}
{93501}{}{Uma tocha acesa num suporte de parede.}
{93600}{}{Tocha}
{93601}{}{Uma tocha acesa num suporte de parede.}
{93700}{}{Monumento de Pedra}
{93800}{}{Monumento de Pedra}
{93900}{}{Monumento de Pedra}
{94000}{}{Poste de Caveiras}
{94001}{}{Um poste com crânios humanos pendurados.}
{94100}{}{Poste de Caveiras}
{94101}{}{Um poste com crânios humanos pendurados.}
{94200}{}{Poste de Caveiras}
{94201}{}{Um poste com crânios humanos pendurados.}
{94300}{}{Planta}
{94301}{}{}
{94400}{}{Planta}
{94500}{}{Árvore}
{94600}{}{Árvore}
{94700}{}{Árvore}
{94800}{}{Cama}
{94900}{}{Cama}
{95000}{}{Buraco}
{95001}{}{Um buraco suspeito na parede.}
{95100}{}{Placa de Pedra Erguida}
{95101}{}{Uma placa de pedra erguida.}
{95200}{}{Placa de Pedra Desativada}
{95201}{}{Uma placa de pedra desativada.}
{95300}{}{Placa de Pedra Acionada}
{95301}{}{Uma placa de pedra acionada.}
{95400}{}{Porta}
{95500}{}{Porta}
{95600}{}{Porta}
{95700}{}{Porta}
{95800}{}{Porta}
{95900}{}{Porta}
{96000}{}{Porta}
{96100}{}{Porta}
{96200}{}{Porta}
{96300}{}{Planta}
{96301}{}{Um pé de milho mutante.}
{96400}{}{Planta}
{96401}{}{Um pé de milho mutante.}
{96500}{}{Planta}
{96501}{}{Um pé de milho mutante. Este está doente.}
{96600}{}{Planta}
{96601}{}{Um pé de milho mutante.}
{96700}{}{Planta}
{96701}{}{Um pé de milho mutante.}
{96800}{}{Planta}
{96801}{}{Um pé de milho mutante.}
{96900}{}{Suporte de Madeira}
{97000}{}{Suporte de Madeira}
{97100}{}{Suporte de Madeira}
{97200}{}{Suporte de Madeira}
{97300}{}{Suporte de Madeira}
{97400}{}{Suporte de Madeira}
{97500}{}{Suporte de Madeira Danificado}
{97501}{}{Este suporte parece que pode desabar se for forçado.}
{97600}{}{Piso Desabado}
{97601}{}{O piso de pedra desabou aqui para o nível inferior.}
{97700}{}{Escada para Baixo}
{97701}{}{Um buraco feito pelo homem com uma escada que leva para baixo.}
{97800}{}{Porta}
{97900}{}{Parede}
{98000}{}{Placa do Reator 5}
{98100}{}{Porta}
{98200}{}{Porta}
{98300}{}{Porta}
{98400}{}{Porta}
{98500}{}{Gosma Radioativa}
{98600}{}{Gosma Radioativa}
{98700}{}{Gosma Radioativa}
{98800}{}{Gosma Radioativa}
{98900}{}{Porta de Segurança}
{99000}{}{Porta do Vault}
{99100}{}{Guindaste}
{99200}{}{Guindaste}
{99300}{}{Poço}
{99400}{}{Poço}
{99500}{}{Latrina}
{99600}{}{Buraco}
{99601}{}{Você não consegue ver o fundo deste poço.}
{99700}{}{Placa de Piso}
{99701}{}{Você vê uma armadilha de placa de piso.}
{99800}{}{Placa de Piso Desativada}
{99801}{}{Esta armadilha de placa de piso foi desativada.}
{99900}{}{Placa de Piso Acionada}
{99901}{}{Esta armadilha de placa de piso foi acionada. Opa!}
{100000}{}{Alambique}
{100001}{}{Isto parece um alambique de álcool a lenha.}
{100100}{}{Partes de Radscorpion}
{100101}{}{Você vê uma grande pilha de partes de Radscorpion. Foram esvaziadas e têm alças presas a elas.}
{100200}{}{Maquinário da Usina}
{100201}{}{Esta é a máquina do Escudo de Plutônio-Gama do reator.}
{100300}{}{Maquinário da Usina}
{100301}{}{Esta é a máquina do Compilador de Ondas Júpiter do reator.}
{100400}{}{Maquinário da Usina}
{100401}{}{Esta é a máquina do Acionador de Barras de Urânio do reator.}
{100500}{}{Maquinário da Usina}
{100501}{}{Esta é a máquina do Impulsor de Netúnio do reator.}
{100600}{}{Maquinário da Usina}
{100601}{}{Esta é a máquina do Capacitor Classe Saturno do reator.}
{100700}{}{Controle da Bomba da Usina}
{100701}{}{Esta é a máquina de bombeamento de refrigerante do reator.}
{100800}{}{Meia-Carcaça de Brahmin}
{100900}{}{Carro}
{101000}{}{Carro Chrysalis Motors}
{101001}{}{Este Chrysalis Motors Highwayman parece estar em boa forma para a idade.}
{101100}{}{Carro}
{101200}{}{Sepultura}
{101201}{}{Há uma sepultura aqui.}
{101300}{}{Lápide}
{101301}{}{Lápide}
{101400}{}{Lápide}
{101401}{}{Lápide}
{101500}{}{Lápide}
{101501}{}{Lápide}
{101600}{}{Lápide}
{101601}{}{Lápide}
{101700}{}{Arado}
{101701}{}{Este arado foi feito para ser puxado por um Brahmin.}
{101800}{}{Arado}
{101801}{}{Este arado foi feito para ser puxado por um Brahmin.}
{101900}{}{Água}
{102000}{}{Placa}
{102001}{}{A placa de entrada de Nova Reno.}
{102100}{}{Placa}
{102101}{}{A placa de entrada de Nova Reno.}
{102200}{}{Placa}
{102201}{}{A placa de entrada de Nova Reno.}
{102300}{}{Placa}
{102301}{}{A placa de entrada de Nova Reno.}
{102400}{}{Placa}
{102401}{}{A placa de entrada de Nova Reno.}
{102500}{}{Placa}
{102501}{}{A placa de entrada de Nova Reno.}
{102600}{}{Sombra}
{102700}{}{Sombra}
{102800}{}{Sombra}
{102900}{}{Pichação}
{103000}{}{Pichação}
{103100}{}{Pichação}
{103200}{}{Pichação}
{103300}{}{Pichação}
{103400}{}{Pichação}
{103500}{}{Pichação}
{103600}{}{Pichação}
{103700}{}{Pichação}
{103800}{}{Pichação}
{103900}{}{Pichação}
{104000}{}{Pichação}
{104100}{}{Pichação}
{104200}{}{Pichação}
{104300}{}{Pichação}
{104400}{}{Pichação}
{104500}{}{Pichação}
{104600}{}{Pichação}
{104700}{}{Pichação}
{104800}{}{Pichação}
{104900}{}{Pichação}
{105000}{}{Pichação}
{105100}{}{Pichação}
{105200}{}{Pichação}
{105300}{}{Pichação}
{105400}{}{Pichação}
{105500}{}{Pichação}
{105600}{}{Pichação}
{105700}{}{Pichação}
{105800}{}{Pichação}
{105900}{}{Pichação}
{106000}{}{Placa}
{106100}{}{Pichação}
{106200}{}{Pichação}
{106300}{}{Pichação}
{106400}{}{Pichação}
{106500}{}{Pichação}
{106600}{}{Pichação}
{106700}{}{Pichação}
{106800}{}{Pichação}
{106900}{}{Pichação}
{107000}{}{Pichação}
{107100}{}{Pichação}
{107200}{}{Pichação}
{107300}{}{Pichação}
{107400}{}{Pichação}
{107500}{}{Pichação}
{107600}{}{Pichação}
{107700}{}{Pichação}
{107800}{}{Pichação}
{107900}{}{Pichação}
{108000}{}{Pichação}
{108100}{}{Pichação}
{108200}{}{Pichação}
{108300}{}{Pichação}
{108400}{}{Pichação}
{108500}{}{Pichação}
{108600}{}{Pichação}
{108700}{}{Pichação}
{108800}{}{Pichação}
{108900}{}{Pichação}
{109000}{}{Pichação}
{109100}{}{Pichação}
{109200}{}{Pichação}
{109300}{}{Pichação}
{109400}{}{Pichação}
{109500}{}{Pichação}
{109600}{}{Pichação}
{109700}{}{Pichação}
{109800}{}{Pichação}
{109900}{}{Pichação}
{110000}{}{Pichação}
{110100}{}{Pichação}
{110200}{}{Pichação}
{110300}{}{Pichação}
{110400}{}{Pichação}
{110500}{}{Pichação}
{110600}{}{Pichação}
{110700}{}{Pichação}
{110800}{}{Pichação}
{110900}{}{Pichação}
{111000}{}{Placa}
{111100}{}{Placa}
{111200}{}{Placa}
{111300}{}{Placa}
{111400}{}{Placa}
{111500}{}{Placa}
{111600}{}{Placa}
{111700}{}{Placa}
{111800}{}{Papel de Parede}
{111900}{}{Papel de Parede}
{112000}{}{Papel de Parede}
{112100}{}{Papel de Parede}
{112200}{}{Papel de Parede}
{112300}{}{Papel de Parede}
{112400}{}{Papel de Parede}
{112500}{}{Papel de Parede}
{112600}{}{Papel de Parede}
{112700}{}{Papel de Parede}
{112800}{}{Papel de Parede}
{112900}{}{Papel de Parede}
{113000}{}{Papel de Parede}
{113100}{}{Papel de Parede}
{113200}{}{Papel de Parede}
{113300}{}{Papel de Parede}
{113400}{}{Papel de Parede}
{113500}{}{Papel de Parede}
{113600}{}{Papel de Parede}
{113700}{}{Papel de Parede}
{113800}{}{Papel de Parede}
{113900}{}{Papel de Parede}
{114000}{}{Papel de Parede}
{114100}{}{Câmera de Cinema}
{114200}{}{Caixão}
{114300}{}{Caixão}
{114400}{}{Caixão}
{114500}{}{Caixão}
{114600}{}{Barras de Aço}
{114700}{}{Barras de Aço}
{114800}{}{Cobertura de Aço da Janela}
{114900}{}{Cobertura de Aço da Janela}
{115000}{}{Sensor a Laser}
{115100}{}{Sensor a Laser}
{115200}{}{Vagonete de Mina}
{115300}{}{Vagonete com Barra de Aço}
{115400}{}{Vagonete com Dinamite}
{115500}{}{Placa de "Fechado"}
{115600}{}{Placa de "Fechado"}
{115700}{}{Placa da Casa Buckner}
{115800}{}{Placa do Vic}
{115900}{}{Parede}
{116000}{}{Parede}
{116100}{}{Scanner de Retina}
{116101}{}{Este é um dispositivo de segurança que escaneia o padrão de retina de uma pessoa.}
{116200}{}{Placa da Sala de Controle}
{116300}{}{Placa da Sala de Controle}
{116400}{}{Placa da Sala de Controle}
{116500}{}{Placa de Zona de Construção}
{116600}{}{Placa de Zona de Construção}
{116700}{}{Máquina}
{116701}{}{Uma máquina que não funciona.}
{116800}{}{Máquina}
{116801}{}{Uma máquina que não funciona.}
{116900}{}{Porta}
{117000}{}{Porta}
{117100}{}{Canos}
{117101}{}{Um conjunto de canos que entram no reator.}
{117200}{}{Tanque}
{117300}{}{Tanques}
{117400}{}{Tanques}
{117500}{}{Tanques}
{117600}{}{Duto}
{117700}{}{Duto}
{117800}{}{Placa da Harpa}
{117900}{}{Cavalete}
{118000}{}{Cavalete}
{118100}{}{Cavalete}
{118200}{}{Duto}
{118300}{}{Duto}
{118400}{}{Placa da Oficina Mecânica}
{118500}{}{Placa do Escritório do Gerente}
{118600}{}{Placa do Almoxarifado}
{118700}{}{Placa de Aviso de Radiação}
{118800}{}{Vapor}
{118900}{}{Máquina}
{118901}{}{Um equipamento diverso da usina de energia.}
{119000}{}{Tanque}
{119100}{}{Fogo}
{119200}{}{Água}
{119300}{}{Placa de Trapper Town}
{119400}{}{Placa do Gecko Dourado}
{119500}{}{Placa da Casa de Banhos}
{119600}{}{Arte Rupestre}
{119700}{}{Arte Rupestre}
{119800}{}{Arte Rupestre}
{119900}{}{Arte Rupestre}
{120000}{}{Fogueira}
{120100}{}{Parede da Caverna}
{120200}{}{Parede da Caverna}
{120300}{}{Parede da Caverna}
{120400}{}{Parede da Caverna}
{120500}{}{Parede da Caverna}
{120600}{}{Parede da Caverna}
{120700}{}{Parede da Caverna}
{120800}{}{Parede da Caverna}
{120900}{}{Parede da Caverna}
{121000}{}{Parede da Caverna}
{121100}{}{Parede da Caverna}
{121200}{}{Parede da Caverna}
{121300}{}{Parede da Caverna}
{121400}{}{Parede da Caverna}
{121500}{}{Parede da Caverna}
{121600}{}{Estaca}
{121601}{}{Esta estaca parece ter uma pessoa empalada no topo!}
{121700}{}{Estaca}
{121701}{}{Esta estaca parece ter uma pessoa empalada no topo!}
{121800}{}{Estaca}
{121801}{}{Esta estaca parece ter uma pessoa empalada no topo!}
{121900}{}{Estaca}
{121901}{}{Esta estaca parece ter uma pessoa empalada no topo!}
{122000}{}{Estaca}
{122001}{}{Esta estaca parece ter uma pessoa empalada no topo!}
{122100}{}{Estaca}
{122101}{}{Esta estaca parece ter uma pessoa empalada no topo!}
{122200}{}{Estaca}
{122201}{}{Esta estaca parece ter um crânio humano fixado no topo.}
{122300}{}{Estaca}
{122301}{}{Esta estaca parece ter um crânio humano fixado no topo.}
{122400}{}{Estaca}
{122401}{}{Esta estaca vazia parece pronta para uma vítima involuntária.}
{122500}{}{Estaca}
{122501}{}{Esta estaca vazia parece pronta para uma vítima involuntária.}
{122600}{}{Estaca}
{122601}{}{Esta estaca vazia parece pronta para uma vítima involuntária.}
{122700}{}{Estaca}
{122701}{}{Esta estaca vazia parece pronta para uma vítima involuntária.}
{122800}{}{Placa de Procurado}
{122801}{}{A imagem nesta placa se parece estranhamente com você!}
{122900}{}{Piso}
{123000}{}{Robobrain Desativado}
{123001}{}{Um corpo cibernético incompleto ao qual faltam várias partes.}
{123100}{}{Obuseiro}
{123101}{}{Este canhão de aparência estranha parece uma relíquia dos tempos pré-Guerra. Você se pergunta como ele foi parar aqui.}
{123200}{}{Placa}
{123300}{}{Placa}
{123400}{}{Placa}
{123500}{}{Placa}
{123600}{}{Interruptor de Energia}
{123700}{}{Cruz}
{123800}{}{Cruz}
{123900}{}{Cruz}
{124000}{}{Cruz}
{124100}{}{Cruz}
{124200}{}{Cruz}
{124300}{}{Bomba de Gasolina}
{124400}{}{Bomba de Gasolina}
{124500}{}{Bomba de Gasolina}
{124600}{}{Placa do Posto Pep}
{124700}{}{Sombra da Placa}
{124800}{}{Cama de Feno}
{124900}{}{Cama de Feno}
{125000}{}{Cama de Feno}
{125100}{}{Cama de Feno}
{125200}{}{Cama de Feno}
{125300}{}{Cama de Feno}
{125400}{}{Placa da Cantina do Dusty}
{125500}{}{Loja do Filho do Bob}
{125501}{}{A banca de um vendedor ambulante.}
{125600}{}{Loja do Filho do Bob}
{125601}{}{A banca de um vendedor ambulante.}
{125700}{}{Loja do Filho do Bob}
{125701}{}{A banca de um vendedor ambulante.}
{125800}{}{Loja do Filho do Bob}
{125801}{}{A banca de um vendedor ambulante.}
{125900}{}{Placa da NCR}
{126000}{}{Placa do Salão do Congresso}
{126100}{}{Placa do Salão do Congresso}
{126200}{}{Cartaz da NCR}
{126300}{}{Cartaz da NCR}
{126400}{}{Cartaz da NCR}
{126500}{}{Cartaz da NCR}
{126600}{}{Placa do Saloon Rawhide}
{126700}{}{Placa do Cassino}
{126800}{}{Placa do Cassino}
{126900}{}{Placa do Cassino}
{127000}{}{Placa do Cassino}
{127100}{}{Placa do Cassino}
{127200}{}{Placa do Cassino}
{127300}{}{Monte de Rochas}
{127301}{}{Estas rochas parecem estar prendendo algo lá dentro.}
{127400}{}{Viga}
{127500}{}{Viga}
{127600}{}{Viga}
{127700}{}{Viga}
{127800}{}{Viga}
{127900}{}{Viga}
{128000}{}{Viga}
{128100}{}{Viga}
{128200}{}{Viga}
{128300}{}{Viga}
{128400}{}{Sombra}
{128500}{}{Sombra}
{128600}{}{Sombra}
{128700}{}{Sombra}
{128800}{}{Sombra}
{128900}{}{Sombra}
{129000}{}{Sombra}
{129100}{}{Sombra}
{129200}{}{Sombra}
{129300}{}{Poço de Elevador}
{129400}{}{Bomba de Gasolina}
{129500}{}{Bomba de Gasolina}
{129600}{}{Bomba de Gasolina}
{129700}{}{Corda}
{129800}{}{Buraco}
{129900}{}{Carne de Brahmin}
{130000}{}{Carne de Brahmin}
{130100}{}{Carne de Brahmin}
{130200}{}{Carne de Brahmin}
{130300}{}{Carne de Brahmin}
{130400}{}{Carne de Brahmin}
{130500}{}{Viga}
{130600}{}{Viga}
{130700}{}{Viga}
{130800}{}{Viga}
{130900}{}{Viga}
{131000}{}{Viga}
{131100}{}{Viga}
{131200}{}{Viga}
{131300}{}{Sombra}
{131400}{}{Sombra}
{131500}{}{Sombra}
{131600}{}{Sombra}
{131700}{}{Sombra}
{131800}{}{Sombra}
{131900}{}{Sombra}
{132000}{}{Sombra}
{132100}{}{Sangue}
{132200}{}{Sangue}
{132300}{}{Sangue}
{132400}{}{Sangue}
{132500}{}{Sangue}
{132600}{}{Sangue}
{132700}{}{Sangue com Ossos}
{132800}{}{Sangue com Ossos}
{132900}{}{Sangue com Ossos}
{133000}{}{Boca da Caverna}
{133100}{}{Acesso a Equipamentos}
{133200}{}{Acesso a Equipamentos}
{133300}{}{Acesso a Equipamentos}
{133400}{}{Acesso a Equipamentos}
{133500}{}{Computador}
{133501}{}{Um terminal de computador do Vault, ligado ao computador principal do Vault.}
{133600}{}{Computador}
{133601}{}{Um terminal de computador do Vault, ligado ao computador principal do Vault.}
{133700}{}{Portão de Vault City}
{133800}{}{Portão de Vault City}
{133900}{}{Parede}
{134000}{}{Parede}
{134100}{}{Parede}
{134200}{}{Parede}
{134300}{}{Parede}
{134400}{}{Parede}
{134500}{}{Parede}
{134600}{}{Parede}
{134700}{}{Porta}
{134800}{}{Porta Arrombada}
{134900}{}{Escombros da Porta}
{135000}{}{Prédio}
{135100}{}{Prédio}
{135200}{}{Prédio}
{135300}{}{Prédio}
{135400}{}{Prédio}
{135500}{}{Prédio}
{135600}{}{Prédio}
{135700}{}{Prédio}
{135800}{}{Porta}
{135900}{}{Templo}
{136000}{}{Templo}
{136100}{}{Templo}
{136200}{}{Templo}
{136300}{}{Templo}
{136400}{}{Templo}
{136500}{}{Fogueira}
{136600}{}{Fogueira}
{136700}{}{Obuseiro}
{136701}{}{Este canhão de aparência estranha parece uma relíquia dos tempos pré-Guerra. Você se pergunta como ele foi parar aqui.}
{136800}{}{Templo}
{136900}{}{Templo}
{137000}{}{Montanha}
{137100}{}{Caverna}
{137200}{}{Trilho da Porta}
{137300}{}{Tocha}
{137301}{}{Uma tocha acesa num suporte de parede.}
{137400}{}{Tocha}
{137401}{}{Uma tocha acesa num suporte de parede.}
{137500}{}{Tocha}
{137501}{}{Uma tocha acesa num suporte de parede.}
{137600}{}{Tocha}
{137601}{}{Uma tocha acesa num suporte de parede.}
{137700}{}{Vertibird}
{137701}{}{NEED LONG DESCRIPTION.}
{137800}{}{Porta Destruída}
{137801}{}{A porta da estação de energia está destruída.}
{137900}{}{Porta Destruída}
{137901}{}{A porta da estação de energia está destruída.}
{138000}{}{Parede}
{138100}{}{Parede}
{138200}{}{Parede}
{138300}{}{Parede}
{138400}{}{Parede}
{138500}{}{Parede}
{138600}{}{Luz}
{138700}{}{Porta}
{138800}{}{Porta}
{138900}{}{Porta}
{139000}{}{Porta}
{139100}{}{Porta}
{139200}{}{Porta}
{139300}{}{Estandarte}
{139400}{}{Poste}
{139500}{}{Poste}
{139600}{}{Estandarte}
{139700}{}{Estandarte}
{139800}{}{Poste}
{139900}{}{Poste}
{140000}{}{Estandarte}
{140100}{}{Sombra}
{140200}{}{Sombra}
{140300}{}{Estandarte}
{140400}{}{Estandarte}
{140500}{}{Estandarte}
{140600}{}{Estandarte}
{140700}{}{Placa do Cat's Paw}
{140800}{}{Placa do Cat's Paw}
{140900}{}{Placa}
{141000}{}{Placa do Trepa-Trepa}
{141100}{}{Placa do Trepa-Trepa}
{141200}{}{Placa do Trepa-Trepa}
{141300}{}{Placa da Farmácia do Renesco}
{141400}{}{Placa da New Reno Arms}
{141500}{}{Placa do Bar do Salvatore}
{141600}{}{Estátua}
{141700}{}{Porta do Armazém}
{141800}{}{Porta do Armazém}
{141900}{}{Placa do Doc Johnson}
{142000}{}{Placa do Xerife}
{142100}{}{Placa do Saloon Malamute}
{142200}{}{Placa da Mina Morningstar}
{142300}{}{Placa da Mina Kokowebe}
{142400}{}{Placa da Mina Kokowebe}
{142500}{}{Placa da Mina Kokowebe}
{142600}{}{Placa de Sinalização}
{142601}{}{Esta placa de madeira aponta para Nova Reno e para o "Inferno". Você suspeita que as direções estão invertidas.}
{142700}{}{Placa Número 1}
{142800}{}{Placa Número 2}
{142900}{}{Placa Número 3}
{143000}{}{Placa Número 4}
{143100}{}{Placa Número 5}
{143200}{}{Placa Número 6}
{143300}{}{Corda}
{143301}{}{Você pode escalar a parede com esta corda.}
{143400}{}{Porta}
{143500}{}{Porta}
{143600}{}{Janela}
{143700}{}{Janela}
{143800}{}{Janela}
{143900}{}{Janela}
{144000}{}{Janela}
{144100}{}{Janela}
{144200}{}{Janela}
{144300}{}{Janela}
{144400}{}{Janela}
{144500}{}{Janela}
{144600}{}{Janela}
{144700}{}{Janela}
{144800}{}{Escada da Piscina}
{144900}{}{Porta}
{145000}{}{Arco}
{145100}{}{Arco}
{145200}{}{Arco}
{145300}{}{Arco}
{145400}{}{Arco}
{145500}{}{Arco}
{145600}{}{Arco}
{145700}{}{Arco}
{145800}{}{Sombra}
{145900}{}{Sombra}
{146000}{}{Sombra}
{146100}{}{Arco}
{146200}{}{Arco}
{146300}{}{Arco}
{146400}{}{Sombra}
{146500}{}{Sombra}
{146600}{}{Portão da Cerca}
{146700}{}{Portão da Cerca}
{146800}{}{Assento de Comando}
{146801}{}{É aqui que o Supervisor normalmente se senta.}
{146900}{}{Abismo}
{147000}{}{Abismo}
{147100}{}{Abismo}
{147200}{}{Abismo}
{147300}{}{Entrada do Cassino}
{147400}{}{Entrada do Cassino}
{147500}{}{Tapete}
{147600}{}{Entrada do Cassino}
{147700}{}{Entrada do Cassino}
{147800}{}{Entrada do Cassino}
{147900}{}{Porta do Cassino}
{148000}{}{Porta do Cassino}
{148100}{}{Entrada do Cassino}
{148200}{}{Entrada do Cassino}
{148300}{}{Entrada do Cassino}
{148400}{}{Entrada do Cassino}
{148500}{}{Entrada do Cassino}
{148600}{}{Entrada do Cassino}
{148700}{}{Entrada do Cassino}
{148800}{}{Entrada do Cassino}
{148900}{}{Entrada do Cassino}
{149000}{}{Entrada do Cassino}
{149100}{}{Porta do Cassino}
{149200}{}{Porta do Cassino}
{149300}{}{Luz de Parede}
{149400}{}{Luz de Parede}
{149500}{}{Luz de Parede}
{149600}{}{Luz de Parede}
{149700}{}{Luz de Parede}
{149800}{}{Parede}
{149900}{}{Parede}
{150000}{}{Ventilador}
{150100}{}{Ventilador}
{150200}{}{Extintor}
{150300}{}{Extintor}
{150400}{}{Cano}
{150500}{}{Distribuidor de Energia}
{150600}{}{Distribuidor de Energia}
{150700}{}{Parede}
{150800}{}{Parede}
{150900}{}{Parede}
{151000}{}{Parede}
{151100}{}{Parede}
{151200}{}{Parede}
{151300}{}{Parede}
{151400}{}{Parede}
{151500}{}{Parede}
{151600}{}{Revestimento de Madeira}
{151700}{}{Revestimento de Madeira}
{151800}{}{Cano}
{151900}{}{Cano}
{152000}{}{Cano}
{152100}{}{Cano}
{152200}{}{Cano}
{152300}{}{Cano}
{152400}{}{Cano}
{152500}{}{Cano}
{152600}{}{Cano}
{152700}{}{Cano}
{152800}{}{Cano}
{152900}{}{Duto de Ar}
{153000}{}{Duto de Ar}
{153100}{}{Porta}
{153200}{}{Porta}
{153300}{}{Porta}
{153400}{}{Porta}
{153500}{}{Porta}
{153600}{}{Porta}
{153700}{}{Chuveiro}
{153800}{}{Parede da Nave}
{153900}{}{Parede da Nave}
{154000}{}{Parede da Nave}
{154100}{}{Parede da Nave}
{154200}{}{Parede da Nave}
{154300}{}{Parede da Nave}
{154400}{}{Parede da Nave}
{154500}{}{Parede da Nave}
{154600}{}{Parede da Nave}
{154700}{}{Parede da Nave}
{154800}{}{Campo de Força}
{154900}{}{Campo de Força}
{155000}{}{Unidade de Extração de Órgãos}
{155001}{}{O modelo mais recente da série de cirurgias "Faça Você Mesmo" da Vault-Tec. Remove órgãos automaticamente ao apertar de um botão.}
{155100}{}{Nave}
{155200}{}{Nave}
{155300}{}{Nave}
{155400}{}{Nave}
{155500}{}{Nave}
{155600}{}{Nave}
{155700}{}{Nave}
{155800}{}{Nave}
{155900}{}{Nave}
{156000}{}{Nave}
{156100}{}{Nave}
{156200}{}{Nave}
{156300}{}{Nave}
{156400}{}{Nave}
{156500}{}{Nave}
{156600}{}{Sombra}
{156700}{}{Sombra}
{156800}{}{Sombra}
{156900}{}{Sombra}
{157000}{}{Sombra}
{157100}{}{Sombra}
{157200}{}{Trono}
{157300}{}{Porta}
{157400}{}{Porta}
{157500}{}{Porta}
{157600}{}{Porta}
{157700}{}{Duto de Ar}
{157800}{}{Auto-Doc}
{157801}{}{Este Auto-Doc foi projetado para curar doenças e administrar várias drogas.}
{157900}{}{Estátua}
{157901}{}{Uma pequena estátua do famoso Vault Dweller.}
{158000}{}{Monte de Rochas}
{158100}{}{Campo de Força}
{158101}{}{Um campo de energia está bloqueando seu caminho.}
{158200}{}{Campo de Força}
{158201}{}{Um campo de energia está bloqueando seu caminho.}
{158300}{}{Campo de Força}
{158301}{}{Um campo de energia está bloqueando seu caminho.}
{158400}{}{Campo de Força}
{158401}{}{Um campo de energia está bloqueando seu caminho.}
{158500}{}{Petroleiro}
{158600}{}{Petroleiro}
{158700}{}{Petroleiro}
{158800}{}{Petroleiro}
{158900}{}{Petroleiro}
{159000}{}{Petroleiro}
{159100}{}{Petroleiro}
{159200}{}{Petroleiro}
{159300}{}{Petroleiro}
{159400}{}{Petroleiro}
{159500}{}{Petroleiro}
{159600}{}{Petroleiro}
{159700}{}{Petroleiro}
{159800}{}{Petroleiro}
{159900}{}{Petroleiro}
{160000}{}{Parede}
{160100}{}{Parede}
{160200}{}{Depressão no Piso}
{160300}{}{Banco de Pedra}
{160400}{}{Banco de Pedra}
{160500}{}{Incensário}
{160600}{}{Antena Parabólica}
{160700}{}{Antena Parabólica}
{160800}{}{Sombra}
{160900}{}{Sombra do Cais}
{161000}{}{Sombra do Cais}
{161100}{}{Sombra do Cais}
{161200}{}{Sombra do Cais}
{161300}{}{Viga}
{161400}{}{Viga}
{161500}{}{Sombra do Cais}
{161600}{}{Sombra do Cais}
{161700}{}{Sombra do Cais}
{161800}{}{Sombra do Cais}
{161900}{}{Escada}
{162000}{}{Cyberdog Desativado}
{162001}{}{Você vê um Cyberdog desativado.}
{162100}{}{Gerador de Energia Destruído}
{162101}{}{Você vê um gerador de energia destruído.}
{162200}{}{Trilho}
{162300}{}{Trilho}
{162400}{}{Trilho}
{162500}{}{Vagonete}
{162600}{}{Vagonete com Barra de Aço}
{162700}{}{Vagonete com Dinamite}
{162800}{}{Vagonete Destruído}
{162900}{}{Vagonete}
{163000}{}{Mesa de Sinuca}
{163100}{}{Mesa de Sinuca}
{163200}{}{Mesa de Sinuca}
{163300}{}{Mesa de Sinuca}
{163400}{}{Mesa de Sinuca}
{163500}{}{Mesa de Sinuca}
{163600}{}{Escrivaninha}
{163700}{}{Bandeira}
{163800}{}{Parede}
{163900}{}{Parede}
{164000}{}{Parede}
{164100}{}{Parede}
{164200}{}{Porta de Exaustão}
{164300}{}{Escrivaninha}
{164400}{}{Escrivaninha}
{164500}{}{Escada para Baixo}
{164600}{}{Escada para Cima}
{164700}{}{Escada para Cima}
{164800}{}{Escada para Cima}
{164900}{}{Computador Central}
{165000}{}{Computador Central}
{165100}{}{Computador Central}
{165200}{}{Placa do Escritório da Caravana}
{165300}{}{Mesa-Caixão}
{165400}{}{Mesa-Caixão}
{165500}{}{Elevador da Mina}
{165600}{}{Elevador da Mina}
{165700}{}{Mastro}
{165800}{}{Bandeira da NCR}
{165900}{}{Placa da Gasolina Poseidon}
{166000}{}{Escada para Baixo}
{166100}{}{Placa da Clínica}
{166200}{}{Placa do Centro Correcional}
{166300}{}{Placa da Alfândega}
{166400}{}{Placa da Alfândega}
{166500}{}{Placa do Escritório de Recepção}
{166600}{}{Placa do Happy Harry}
{166700}{}{Placa do The Hole}
{166800}{}{Placa do Centro de Informações}
{166900}{}{Placa do Centro de Informações}
{167000}{}{Logo de Vault City}
{167100}{}{Placa do Conselho Principal}
{167200}{}{Placa do Conselho Principal}
{167300}{}{Centro de Manutenção}
{167400}{}{Placa do Salão}
{167500}{}{Placa da Taberna}
{167600}{}{Placa do Rancho Westin}
{167700}{}{Placa de Comodidades}
{167800}{}{Placa do Prédio A}
{167900}{}{Placa do Prédio B}
{168000}{}{Central de Alocação de Servos}
{168100}{}{Central de Alocação de Servos}
{168200}{}{Placa do Escritório de Comodidades}
{168300}{}{Placa do Escritório de Comodidades}
{168400}{}{Elevador da Mina}
{168500}{}{Elevador da Mina}
{168600}{}{Elevador da Mina}
{168700}{}{Elevador da Mina}
{168800}{}{Vertibird}
{168900}{}{Vertibird}
{169000}{}{Vertibird}
{169100}{}{Vertibird}
{169200}{}{Vertibird}
{169300}{}{Sombra}
{169400}{}{Sombra}
{169500}{}{Sombra}
{169600}{}{Sombra}
{169700}{}{Vertibird Caído}
{169800}{}{Vertibird Caído}
{169900}{}{Vertibird Caído}
{170000}{}{Vertibird Caído}
{170100}{}{Vertibird Caído}
{170200}{}{Vertibird Caído}
{170300}{}{Sombra}
{170400}{}{Sombra}
{170500}{}{Sombra}
{170600}{}{Ponte Destruída}
{170601}{}{Você vê o que restou da ponte de Arroyo. Não há como voltar para a vila agora.}
{170700}{}{Ponte Destruída}
{170701}{}{Você vê o que restou da ponte de Arroyo. Não há como voltar para a vila agora.}
{170800}{}{Desfiladeiro}
{170900}{}{Porta}
{171000}{}{Porta}
{171100}{}{Parede}
{171200}{}{Parede}
{171300}{}{Parede}
{171400}{}{Parede}
{171500}{}{Parede}
{171600}{}{Parede}
{171700}{}{Parede}
{171800}{}{Parede}
{171900}{}{Duto de Ar}
{172000}{}{Duto de Ar}
{172100}{}{Vidro à Prova de Balas}
{172200}{}{Vidro à Prova de Balas}
{172300}{}{Vidro à Prova de Balas}
{172400}{}{Torreta de Laser Pesada}
{172500}{}{Torreta de Laser Pesada}
{172600}{}{Rochas}
{172700}{}{Rochas}
{172800}{}{Rochas}
{172900}{}{Rochas}
{173000}{}{Rochas}
{173100}{}{Rochas}
{173200}{}{Rochas}
{173300}{}{Rochas}
{173400}{}{Rochas}
{173500}{}{Rochas}
{173600}{}{Rochas}
{173700}{}{Placa do Cassino da Becky}
{173800}{}{Placa da Becky}
{173900}{}{Placa do Saloon Last Gasp}
{174000}{}{Placa do Restaurante da Mom}
{174100}{}{Placa da Guilda dos Escravagistas}
{174200}{}{Placa do Armário de Sobrevivência/Equipamento}
{174300}{}{Placa do Tubby}
{174400}{}{Placa do Tubby}
{174500}{}{Portão do Elevador da Mina}
{174600}{}{Ventilador}
{174700}{}{Ventilador}
{174800}{}{Porta do Gabinete do Presidente}
{174900}{}{Tabela Oftalmológica}
{175000}{}{Ruínas}
{175100}{}{Guardião do Eterno}
{175200}{}{Placa de Fora de Serviço}
{175300}{}{Piso Desabado}
{175400}{}{Vaso Sanitário}
{175500}{}{Cruz}
{175600}{}{Parede}
{175700}{}{Parede}
{175800}{}{Parede}
{175900}{}{Parede}
{176000}{}{Parede}
{176100}{}{Parede}
{176200}{}{Parede}
{176300}{}{Parede}
{176400}{}{Prédio}
{176500}{}{Prédio}
{176600}{}{Prédio}
{176700}{}{Prédio}
{176800}{}{Prédio}
{176900}{}{Prédio}
{177000}{}{Suportes de Aço}
{177100}{}{Suportes de Aço}
{177200}{}{Suportes de Aço}
{177300}{}{Água}
{177400}{}{Água}
{177500}{}{Água}
{177600}{}{Água}
{177700}{}{Água}
{177800}{}{Água}
{177900}{}{Cachoeira}
{178000}{}{Estrada}
{178100}{}{Estrada}
{178200}{}{Estrada}
{178300}{}{Estrada}
{178400}{}{Estrada}
{178500}{}{Estrada}
{178600}{}{Estrada}
{178700}{}{Suporte da Ponte}
{178800}{}{Suporte da Ponte}
{178900}{}{Suporte da Ponte}
{179000}{}{Cerca}
{179100}{}{Lâmpada}
{179200}{}{Lâmpada}
{179300}{}{Baleia Morta}
{179301}{}{Esta baleia parece ter caído de uma grande altura.}
{179400}{}{Baleia Morta}
{179401}{}{Esta baleia parece ter caído de uma grande altura.}
{179500}{}{Barbatana de Baleia}
{179501}{}{A barbatana de uma baleia morta.}
{179600}{}{Olho de Baleia}
{179601}{}{O olho de uma baleia morta.}
{179700}{}{Pedaço de Baleia}
{179701}{}{Um pedaço de baleia!}
{179800}{}{Pedaço de Baleia}
{179801}{}{Um pedaço de baleia!}
{179900}{}{Pedaço de Baleia}
{179901}{}{Um pedaço de baleia!}
{180000}{}{Pedaço de Baleia}
{180001}{}{Um pedaço de baleia!}
{180100}{}{Pedaço de Baleia}
{180101}{}{Um pedaço de baleia!}
{180200}{}{Pernas do Chefe}
{180300}{}{Rochas}
{180400}{}{Rochas}
{180500}{}{Rochas}
{180600}{}{Rochas}
{180700}{}{Placa do Curtume}
{180800}{}{Placa da Pousada da Rose}
{180900}{}{Placa da Vortis Holding}
{181000}{}{Placa da Vortis Holding}
{181100}{}{Placa da Mina Great Wamamingo}
{181200}{}{Placa do Ascorti}
{181300}{}{Nave Caída}
{181301}{}{Um veículo espacial de algum tipo. Parece ter caído aqui recentemente.}
{181400}{}{Caixão}
{181500}{}{Placa da Assoc. dos Pecuaristas}
{181600}{}{Placa do Matadouro}
{181700}{}{Tábua}
{181800}{}{Porta de Madeira}
{181900}{}{Porta de Madeira}
{182000}{}{Geladeira de Refrigerante}
{182100}{}{Geladeira de Refrigerante}
{182200}{}{Fogão}
{182300}{}{Fogão}
{182400}{}{Fogão}
{182500}{}{Fogão}
{182600}{}{Tralha}
{182700}{}{Tralha}
{182800}{}{Tralha}
{182900}{}{Tralha}
{183000}{}{Tralha}
{183100}{}{Tralha}
{183200}{}{Tralha}
{183300}{}{Tralha}
{183400}{}{Cadeira do Presidente}
{183500}{}{Escada}
{183600}{}{Mapa-Múndi}
{183700}{}{Mapa de Situação}
{183800}{}{Mesa da Sala de Guerra}
{183900}{}{Mesa da Sala do Conselho}
{184000}{}{Mesa da Sala do Conselho}
{184100}{}{Mesa da Sala de Guerra}
{184200}{}{Árvore}
{184300}{}{Árvore}
{184400}{}{Rampa}
{184500}{}{Placa Pornô Golden Globes}
{184600}{}{Timão do Navio}
{184700}{}{Controle de Velocidade do Navio}
{184800}{}{Estação de Comunicação}
{184900}{}{Console de Computador}
{185000}{}{Persianas da Vigia}
{185100}{}{Vapor}
{185200}{}{Tanques}
{185201}{}{Um complexo de algum tipo. Você não tem certeza, mas vê grandes tanques de uma gosma esverdeada que parece vagamente importante.}
{185300}{}{Tanques}
{185301}{}{Um complexo de algum tipo. Você não tem certeza, mas vê grandes tanques de uma gosma esverdeada que parece vagamente importante.}
{185400}{}{Tanques}
{185401}{}{Um complexo de algum tipo. Você não tem certeza, mas vê grandes tanques de uma gosma esverdeada que parece vagamente importante.}
{185500}{}{Tanques}
{185501}{}{Um complexo de algum tipo. Você não tem certeza, mas vê grandes tanques de uma gosma esverdeada que parece vagamente importante.}
{185600}{}{Tanques}
{185601}{}{Um complexo de algum tipo. Você não tem certeza, mas vê grandes tanques de uma gosma esverdeada que parece vagamente importante.}
{185700}{}{Tanques}
{185701}{}{Um complexo de algum tipo. Você não tem certeza, mas vê grandes tanques de uma gosma esverdeada que parece vagamente importante.}
{185800}{}{Tanques}
{185801}{}{Um complexo de algum tipo. Você não tem certeza, mas vê grandes tanques de uma gosma esverdeada que parece vagamente importante.}
{185900}{}{Tanques}
{185901}{}{Um complexo de algum tipo. Você não tem certeza, mas vê grandes tanques de uma gosma esverdeada que parece vagamente importante.}
{186000}{}{Motocicleta}
{186001}{}{Este Chrysalis Motors Cruiser parece estar em boa forma para a idade.}
{186100}{}{Motocicleta}
{186101}{}{Este Chrysalis Motors Cruiser parece estar em boa forma para a idade.}
{186200}{}{Sidecar}
{186201}{}{Um velho sidecar de motocicleta. Parece estar em boa forma.}
{186300}{}{Parede da Caverna}
{186400}{}{Placa do Cassino}
{186401}{}{O anúncio do Cassino do Gizmo. Foi desligado.}
{186500}{}{Moscas}
{186600}{}{Montanha}
{186601}{}{Estas paredes de montanha parecem muito inacessíveis.}
{186700}{}{Montanha}
{186701}{}{Estas paredes de montanha parecem muito inacessíveis.}
{186800}{}{Montanha}
{186801}{}{Estas paredes de montanha parecem muito inacessíveis.}
{186900}{}{Montanha}
{186901}{}{Estas paredes de montanha parecem muito inacessíveis.}
{187000}{}{Chão}
{187001}{}{Uma bela vista do Boneyard deste nível da torre. Você tem uma boa noção de quão alto no céu está.}
{187100}{}{Chão}
{187101}{}{Uma bela vista do Boneyard deste nível da torre.}
