{10}{}{<Nenhum>}
{100}{}{Vidro}
{101}{}{Metal}
{102}{}{Plastico}
{103}{}{Madeira}
{104}{}{Po}
{105}{}{Pedra}
{106}{}{Cimento}
{107}{}{Couro}
{150}{}{Armadura}
{151}{}{Recipiente}
{152}{}{Droga}
{153}{}{Arma}
{154}{}{Municao}
{155}{}{Item Misto}
{156}{}{Chave}
{200}{}{Portal}
{201}{}{Escadas}
{202}{}{Elevador}
{203}{}{Fim da Escada}
{204}{}{Topo da Escada}
{205}{}{Cenário Genérico}
{250}{}{dano_normal}
{251}{}{laser}
{252}{}{fogo}
{253}{}{plasma}
{254}{}{elétrico}
{255}{}{pem}
{256}{}{explosão}
{300}{}{Nenhum}
{301}{}{Foguete}
{302}{}{Combustível do Lança-Chamas}
{303}{}{Célula de Energia C}
{304}{}{Célula de Energia D}
{305}{}{.223}
{306}{}{5 mm}
{307}{}{calibre .40}
{308}{}{10 mm}
{309}{}{calibre .44}
{310}{}{14 mm}
{311}{}{calibre 12}
{312}{}{9 mm}
{313}{}{BB}
{314}{}{.45 cal}
{315}{}{2mm}
{316}{}{4.7mm caseless}
{317}{}{HN needler}
{318}{}{7.62mm}
{350}{}{Caucasiano}
{351}{}{Africano}
{400}{}{Bípede}
{401}{}{Quadrupede}
{402}{}{Robótico}
{450}{}{Homens}
{451}{}{Mulheres}
{452}{}{Crianças}
{453}{}{Super Mutantes}
{454}{}{Ghouls}
{455}{}{Brahmin}
{456}{}{Radscorpions}
{457}{}{Ratos}
{458}{}{Flutuadores}
{459}{}{Centauros}
{460}{}{Robos}
{461}{}{Cães}
{462}{}{Manti}
{463}{}{Deathclaws}
{464}{}{Mestre}
{465}{}{Esta linha mostra o numero de homens humanos que você matou durante o curso das suas aventuras.}
{466}{}{Esta linha mostra o numero de mulheres humanas que você matou durante o curso das suas aventuras.}
{467}{}{Esta linha mostra o numero de jovens crianças humanas que você matou durante o curso das suas aventuras. Seu canalha.}
{468}{}{O numero de Super Mutantes que você assassinou durante o curso das suas aventuras.}
{469}{}{Esta linha mostra o numero de homens e mulheres ghouls mutantes que você matou durante o curso das suas aventuras.}
{470}{}{Esta linha mostra o numero de Brahmin (vacas transformadas) que você cortou durante suas viagens.}
{471}{}{O numero de Radscorpions transformados que você pôs para a morte durante sua aventura.}
{472}{}{O numero de ratos que você matou. Inclui todos os membros da família do rato.}
{473}{}{Este é o numero de Flutuadores mutantes que você pôs para a morte.}
{474}{}{Sua contagem de Centauros mutantes mortos.}
{475}{}{Este é o numero de robôs que você destruiu ou desmantelou.}
{476}{}{O numero total de cães que você mandou para o grande canil no céu.}
{477}{}{Esta linha mostra o número total de Mantis mortos, ou de grandes insetos transformados como o louva-deus, que você esmagou até agora.}
{478}{}{Esta linha mostra que você assassinou o Deathclaw e quaisquer dos suas crias.}
{479}{}{Não Exibido.   Erro!}
{480}{}{Você vê: %s.}
{485}{}{Você vasculha o %s.}
{486}{}{Você fecha o %s.}
{487}{}{Esta trancado.}
{490}{}{Você vê: %s.}
{491}{}{Você vê um morto: %s.}
{492}{}{Você vê os restos do: %s.}
{493}{}{Você não vê nada fora do comum.}
{500}{}{Morto}
{501}{}{Quase Morto}
{502}{}{Severamente Ferido}
{503}{}{Ferido}
{504}{}{Sem Ferimentos}
{510}{}{AC Mod: %d}
{511}{}{DR Mod: %d}
{512}{}{Mod Dano: %d/%d}
{518}{}{Você parece: %s }
{519}{}{%s %s }
{520}{}{Você parece: %s.}
{521}{}{%s %s.}
{522}{}{Ele parece: %s.}
{523}{}{Ela parece: %s.}
{524}{}{Ele parece: %s.}
{525}{}{%s tem %d/%d hps.}
{526}{}{Ele tem %d/%d tiros de %s.}
{530}{}{e tem os membros incapacitados.}
{531}{}{mas tem os membros incapacitados.}
{532}{}{e tem os membros incapacitados.}
{533}{}{mas tem os membros incapacitados.}
{535}{}{Ele tem %d/%d hps}
{536}{}{Ela tem %d/%d hps}
{537}{}{Ele tem %d/%d hps}
{540}{}{Ele pesa %d quilos.}
{541}{}{Ele pesa %d libra.}
{544}{}{, }
{545}{}{.}
{546}{}{ e esta empunhando um %s.}
{547}{}{ e esta empunhando um %s com %d/%d tiros de %s.}
{548}{}{O carro não parece estar funcionando no momento.}
{549}{}{O carro está funcionando com %d%% de energia.}
{550}{}{\nErro: lookup_val fora do intervalo!}
{551}{}{\nErro: obj_examine: proto_ptr falhou!}
{580}{}{Você usa o %s.}
{581}{}{Você usa o %s no %s.}
{582}{}{Isso não faz nada.}
{583}{}{Para sua consternação, você percebe que já esta morto.}
{584}{}{Apos você chegar lá embaixo, você percebe que já esta morto.}
{585}{}{Ai de você, você chegou tarde demais.}
{586}{}{Isso não funcionara no morto.}
{587}{}{Você acende o sinal luminoso.}
{588}{}{O sinal luminoso já esta aceso.}
{589}{}{Você configura o timer.}
{590}{}{O timer já esta tique-taqueando!}
{595}{}{Você carrega o carro com mais energia.}
{596}{}{O carro já está cheio de energia.}
{597}{}{A passagem parece estar bloqueada.}
{620}{}{Você ganha %d pontos de experiência por matar o: %s.}
{621}{}{%s você ganha %d pontos de exp.}
{622}{}{Por derrotar seus inimigos, }
{623}{}{Por assassinar seus oponentes, }
{624}{}{Você foi vitorioso em combate, }
{625}{}{Por esmagar seus inimigos, }
{626}{}{Por destruir seus inimigos sem levar um arranhão, }
{650}{}{[Feito]}
{651}{}{[Mais]}
{652}{}{Mais}
{653}{}{[Voltar]}
{654}{}{Voltar}
{655}{}{Continuar}
{656}{}{Err...}
{660}{}{Você não consegue ver lá.}
{661}{}{Muito distante.}
{670}{}{Certo.}
{671}{}{Claro.}
{672}{}{Como quiser.}
{673}{}{O que você mandar.}
{674}{}{Vou tentar.}
{675}{}{Não posso fazer isso.}
{676}{}{Acho que não consigo fazer isso.}
{677}{}{Au!}
{678}{}{Au!}
{700}{}{Você não tem pontos de ação o bastante.}
{800}{}{Você le o livro.}
{801}{}{Você não aprende nada novo.}
{802}{}{Você aprende nova informação sobre a ciência.}
{803}{}{Você aprende muito sobre reparar eletrônicos quebrados.}
{804}{}{Você aprende novos modos de curar ferimentos.}
{805}{}{Você aprende como manejar suas armas melhor.}
{806}{}{Você aprende muito sobre sobrevivência nas regiões despovoadas.}
{900}{}{Os suprimentos na Maleta do Doutor se esgotaram.}
{901}{}{Os suprimentos no Kit de Primeiros Socorros se esgotaram.}
{902}{}{Você não pode fazer isso em combate.}
{903}{}{Esta pessoa não permutara com você.}
{904}{}{Esta pessoa não tem nada a dizer pra você.}
{905}{}{Você não pode pegar esse item. Você esta na sua capacidade máxima de peso.}
{910}{}{Os suprimentos da Bolsa de Paramédico acabaram.}
{911}{}{Os suprimentos do Kit de Primeiros Socorros de Médico de Campo acabaram.}
{913}{}{Esta criatura não pode carregar nada.}
{1450}{}{Homens}
{1451}{}{Mulheres}
{1452}{}{Crianças}
{1453}{}{Super Mutantes}
{1454}{}{Ghouls}
{1455}{}{Brahmin}
{1456}{}{Radscorpions}
{1457}{}{Ratos}
{1458}{}{Flutuadores}
{1459}{}{Centauros}
{1460}{}{Robôs}
{1461}{}{Cães}
{1462}{}{Manti}
{1463}{}{Deathclaws}
{1464}{}{Plantas}
{1465}{}{Geckos}
{1466}{}{Alienígenas}
{1467}{}{Formigas Gigantes}
{1468}{}{Chefão}
{1469}{}{Esta linha mostra o número de homens humanos que você matou ao longo das suas aventuras.}
{1470}{}{Esta linha mostra o número de mulheres humanas que você matou ao longo das suas aventuras.}
{1471}{}{Esta linha mostra o número de crianças humanas que você matou ao longo das suas aventuras. Seu canalha.}
{1472}{}{O número de Super Mutantes que você abateu ao longo das suas aventuras.}
{1473}{}{Esta linha mostra o número de mutantes ghoul, homens e mulheres, que você matou ao longo das suas aventuras.}
{1474}{}{Esta linha mostra o número de Brahmin (vacas mutantes) que você retalhou nas suas viagens.}
{1475}{}{O número de Radscorpions mutantes que você executou durante a sua aventura.}
{1476}{}{O número de ratos que você matou. Inclui todos os membros da família dos ratos.}
{1477}{}{Este é o número de Flutuadores mutantes que você executou.}
{1478}{}{Sua conta de Centauros mutantes mortos.}
{1479}{}{Este é o número de robôs que você destruiu ou desmontou.}
{1480}{}{O número total de cães que você mandou para o grande canil no céu.}
{1481}{}{Esta linha mostra o número total de Manti mortos, os grandes insetos mutantes parecidos com mantis, que você esmagou até agora.}
{1482}{}{Esta linha mostra que você abateu a Deathclaw e qualquer uma das suas crias.}
{1483}{}{Esta linha mostra o número de plantas que você arrancou do mundo.}
{1484}{}{O número de lagartos fofos que você varreu da face do planeta.}
{1485}{}{Uma contagem de coisas alienígenas mortas pelas suas mãos.}
{1486}{}{O número de insetoides que você exterminou no ermo.}
{1487}{}{A contagem de guarda-costas ciborgues homicidas geneticamente modificados que você destruiu.}
