{100}{}{Encontrar o Chip de Água.}
{101}{}{Acalmar a facção rebelde.}
{102}{}{Encontrar o Ladrão de Água.}
{103}{}{Destruir o líder dos Mutantes.}
{104}{}{Destruir a origem dos Mutantes.}
{105}{}{Ajudar o médico a sintetizar o Antídoto.}
{106}{}{Aprender sobre o mundo exterior na biblioteca.}
{107}{}{Conseguir entrar no Arsenal.}
{108}{}{Conseguir voltar para dentro do Vault.}
{109}{}{Matar o Supervisor.}
{110}{}{Matar todos os habitantes do Vault 13.}
{120}{}{Encontrar o Chip de Água.}
{200}{}{Procurar por pistas e informações.}
{201}{}{Procurar por um Chip de Água.}
{202}{}{Achar um jeito de descer o poço do elevador.}
{203}{}{Encontrar os itens escondidos.}
{204}{}{Matar todos os ratos.}
{300}{}{Falar com a Katrina.}
{301}{}{Contratar o Ian.}
{302}{}{Deter os radscorpions.}
{303}{}{Ajudar o Razlo a achar uma cura para o veneno de radscorpion.}
{304}{}{Curar o Jarvis do veneno de radscorpion.}
{305}{}{Resgatar a Tandi dos Khans.}
{306}{}{Ajudar Shady Sands a melhorar a colheita.}
{307}{}{Liderar Seth e os guardas para destruir os Khans.}
{400}{}{Ajudar o Saul.}
{401}{}{Matar o Killian.}
{402}{}{Resgatar a Sinthia.}
{403}{}{Salvar a Trish.}
{404}{}{Deter o Gizmo.}
{405}{}{Acabar com a gangue Skulz.}
{406}{}{Entrar para os Skulz.}
{407}{}{Roubar a urna do Neal no Skum Pitt.}
{408}{}{RESERVED}
{500}{}{Entrar para os Khans.}
{501}{}{Destruir os Khans.}
{502}{}{Matar os escravos.}
{503}{}{Salvar os escravos.}
{504}{}{Envergonhar o Garl vencendo-o em combate corpo-a-corpo.}
{505}{}{Libertar o prisioneiro.}
{506}{}{Libertar a Tandi.}
{507}{}{Juntar-se aos Khans numa investida contra Shady Sands.}
{508}{}{Abusar dos escravos.}
{509}{}{Substituir o Garl como líder dos Khans.}
{600}{}{Destruir os Super Mutantes na Bacia Hidrográfica.}
{601}{}{Consertar a bomba d'água de Necropolis.}
{602}{}{Salvar o prisioneiro.}
{603}{}{Recuperar o Chip de Água.}
{604}{}{Permitir que os Super Mutantes da Bacia partam em paz.}
{605}{}{Seduzir o Harry.}
{606}{}{Receber a recompensa do Set por remover os Super Mutantes.}
{607}{}{Entrar furtivamente no Salão dos Mortos do Set.}
{608}{}{Encontrar uma entrada para a Bacia Hidrográfica.}
{700}{}{Encontrar e destruir a Deathclaw.}
{701}{}{Livrar-se do Jain.}
{702}{}{Livrar-se do comerciante.}
{703}{}{Encontrar as caravanas desaparecidas.}
{704}{}{Roubar o colar dos Comerciantes.}
{705}{}{Entrar para o Círculo dos Ladrões.}
{706}{}{Livrar-se do Decker.}
{707}{}{Enviar água para o Vault 13.}
{708}{}{Tornar-se guarda dos Water Merchants.}
{709}{}{Tornar-se guarda dos Far Go Traders.}
{710}{}{Tornar-se guarda da Crimson Caravan.}
{711}{}{Livrar-se dos saqueadores na Fazenda do Irwin.}
{800}{}{Tornar-se um Iniciado.}
{801}{}{Resgatar o Iniciado do Hub.}
{802}{}{Tornar-se um Cavaleiro.}
{803}{}{Aprender com os Computadores da Biblioteca.}
{804}{}{Receber operações da Lori.}
{805}{}{Reparar a Armadura de Combate Motorizada.}
{806}{}{Seduzir a Lorri.}
{807}{}{Roubar o Motivador Sistólico.}
{808}{}{Entregar Granadas de Pulso para a Sophia.}
{809}{}{Conseguir acesso ao Arsenal.}
{810}{}{Encontrar as Ruínas da Antiga Ordem.}
{811}{}{Explorar a área ao Norte.}
{812}{}{Convencer a Brotherhood a ajudar na Base Militar.}
{813}{}{RESERVED}
{814}{}{RESERVED}
{815}{}{RESERVED}
{816}{}{RESERVED}
{817}{}{RESERVED}
{818}{}{RESERVED}
{900}{}{Conseguir entrar na base.}
{901}{}{Entrar na base sem ser detectado.}
{902}{}{Enganar os Mutantes para abandonarem seus postos de guarda.}
{903}{}{Desativar os campos de força.}
{904}{}{Matar o Tenente.}
{905}{}{Destruir os Tanques.}
{1000}{}{Conseguir entrar no Glow.}
{1001}{}{Desarmar armadilhas da instalação.}
{1002}{}{Ligar a energia do Glow.}
{1100}{}{Tornar-se uma Lâmina.}
{1101}{}{Entregar o Medalhão para o Romero.}
{1102}{}{Entregar o pacote dos Gun Runners.}
{1103}{}{Encontrar o espião dos Filhos entre os Seguidores.}
{1104}{}{Consertar as fazendas hidropônicas de Adytum.}
{1105}{}{Resgatar o Jason Zimmerman.}
{1106}{}{Impedir que as Gangues ataquem Adytum.}
{1107}{}{Matar a Deathclaw Mãe.}
{1108}{}{Convencer os Gun Runners a abastecer as Blades.}
{1109}{}{Matar o líder do exército mutante em Necropolis.}
{1110}{}{RESERVED}
{1111}{}{RESERVED}
{1200}{}{Conseguir entrar no Vault do Mestre.}
{1201}{}{Convencer a Rae a se juntar a você contra o Mestre.}
{1202}{}{Matar o Morpheus.}
{1203}{}{Matar o Mestre.}
{1204}{}{Ajustar o cronômetro da bomba.}
{1300}{}{Ajudar a descarregar a Caravana.}
{1400}{}{RESERVED}
{1401}{}{RESERVED}
{1402}{}{RESERVED}
{1403}{}{RESERVED}
{1500}{}{RESERVED}
{1501}{}{RESERVED}
{1502}{}{RESERVED}
{1503}{}{RESERVED}
{1504}{}{RESERVED}
{1505}{}{RESERVED}
{1506}{}{RESERVED}
{1507}{}{RESERVED}
{1508}{}{RESERVED}
{1509}{}{RESERVED}
{1510}{}{RESERVED}
{1511}{}{RESERVED}
{1512}{}{RESERVED}
{1513}{}{RESERVED}
{1514}{}{RESERVED}
{1515}{}{RESERVED}
{1516}{}{RESERVED}
{1600}{}{RESERVED}
{1601}{}{RESERVED}
{1602}{}{RESERVED}
{1700}{}{RESERVED}
{1800}{}{RESERVED}
{1900}{}{RESERVED}
{2000}{}{RESERVED}
{2100}{}{RESERVED}
{2200}{}{RESERVED}
{2300}{}{RESERVED}
{2400}{}{RESERVED}
{2500}{}{RESERVED}
{2600}{}{RESERVED}
{2700}{}{RESERVED}
{2800}{}{RESERVED}
{2900}{}{RESERVED}
{3000}{}{RESERVED}
{3100}{}{RESERVED}
{3200}{}{RESERVED}
{3201}{}{RESERVED}
{3202}{}{RESERVED}
{3203}{}{RESERVED}
