{101}{}{}
{102}{}{Anciã}
{103}{}{Comerciante}
{104}{}{Guarda-Costas}
{105}{}{Vaca}
{106}{}{Guarda do Fosso dos Gunrunners}
{107}{}{Guarda de Shady Sands}
{108}{}{Perdedor}
{109}{}{Campones de Shady Sands}
{110}{}{Gunrunner}
{111}{}{Entrada para o Mapa}
{112}{}{Radscorpion}
{113}{}{Sentinela Super Mutante}
{114}{}{Poço de Shady Sands}
{115}{}{Set}
{116}{}{Harry}
{117}{}{Stimpak}
{118}{}{Tampa da Boca-de-Lobo}
{119}{}{Boca-de-Lobo}
{120}{}{Escada}
{121}{}{Cadeira}
{122}{}{Maquina de Nuka Cola}
{123}{}{Escrivaninha do Gerente}
{124}{}{Cadaver}
{125}{}{Escrivaninha}
{126}{}{Cadaver do Ghoul}
{127}{}{Rato Toupeira}
{128}{}{Boca-de-Lobo}
{129}{}{Escada}
{130}{}{Gerente Ghoul}
{131}{}{Roteiro do Mapa}
{132}{}{Ghoul}
{133}{}{Aradesh}
{134}{}{Brahmin}
{135}{}{Cougar}
{136}{}{Flash}
{137}{}{Guarda de Junktown}
{138}{}{Campones de Junktown}
{139}{}{Butch}
{140}{}{Cabbot}
{141}{}{Membro das Crianças da Catedral}
{142}{}{Decker}
{143}{}{Anciã}
{144}{}{Gizmo}
{145}{}{Harold}
{146}{}{Jain}
{147}{}{Killian}
{148}{}{Laura}
{149}{}{Loxley}
{150}{}{Tenente}
{151}{}{Mestre}
{152}{}{Maxson}
{153}{}{Morpheus}
{154}{}{Nicole}
{155}{}{Supervisor}
{156}{}{Rhombus}
{157}{}{Tandi}
{158}{}{Vree}
{159}{}{Rato Toupeira}
{160}{}{Camara de Ar de Necropolis}
{161}{}{Barry}
{162}{}{Computador}
{163}{}{Porta}
{164}{}{Capataz Ghoul}
{165}{}{Gary}
{166}{}{Ghoul}
{167}{}{Ghoul}
{168}{}{Ghoul Brilhante}
{169}{}{Cadaver de Ghoul}
{170}{}{Sentinela Ghoul}
{171}{}{Cadaver de Ghoul}
{172}{}{Guarda do Set}
{173}{}{Gerente Ghoul}
{174}{}{Refugiado Ghoul}
{175}{}{Guarda Ghoul}
{176}{}{Ghoul Brilhante Preso}
{177}{}{Habitante do Subsolo}
{178}{}{Guarda de Shady Sands}
{179}{}{Harry}
{180}{}{Larry}
{181}{}{Lider dos Capatazes}
{182}{}{Gerente Ghoul}
{183}{}{Cadaver Mutilado}
{184}{}{Campones Ghoul}
{185}{}{Super Mutante}
{186}{}{Computador da Agua}
{187}{}{Bomba D'água}
{188}{}{Parede}
{189}{}{Prisoneiro Ghoul}
{190}{}{Sally}
{191}{}{Grafite}
{192}{}{Geladeira do Set}
{193}{}{Escrivaninha do Set}
{194}{}{Porta}
{195}{}{Guarda-Costas do Set}
{196}{}{Parede}
{197}{}{Cheiro Estranho}
{198}{}{Stimpak}
{199}{}{Deposito de Necropolis}
{200}{}{Super Mutante}
{201}{}{Terry}
{202}{}{Garret}
{203}{}{Gretch}
{204}{}{Morbid}
{205}{}{Dumar}
{206}{}{Barstow}
{207}{}{Iniciado das Crianças da Catedral}
{208}{}{Curador das Crianças da Catedral}
{209}{}{Vigia dos Habitantes do Subsolo}
{210}{}{Computador}
{211}{}{Sala Bloqueada}
{212}{}{Deserto}
{213}{}{Guarda de Shady Sands}
{214}{}{Cozinheiro de Shady Sands}
{215}{}{Cidadão de Shady Sands}
{216}{}{Cadeira}
{217}{}{Cama da Agatha}
{218}{}{Cama do Razlo}
{219}{}{Esposa do Razlo}
{220}{}{Penteadeira}
{221}{}{Tapete}
{222}{}{Estante de Livros}
{223}{}{Jarro de Frutas}
{224}{}{Escrivaninha}
{225}{}{Prateleira}
{226}{}{Mesa}
{227}{}{Fruta Apos Mutacao}
{228}{}{Cheiro do Curral dos Brahmins}
{229}{}{Razlo}
{230}{}{Cidadão da Vault 13}
{231}{}{Camara de Ar da Vault 13}
{232}{}{Monitor da Vault 13}
{233}{}{Nucleo Central da Vault 13}
{234}{}{Computador da Biblioteca da Vault 13}
{235}{}{Kalnor}
{236}{}{Saqueador}
{237}{}{Garl}
{238}{}{Prisoneira dos Saqueadores}
{239}{}{Petrox}
{240}{}{Tolya}
{241}{}{Gwen}
{242}{}{Diana}
{243}{}{Alya}
{244}{}{Alojamentos}
{245}{}{Sala de Reuniao}
{246}{}{Deposito}
{247}{}{Biblioteca}
{248}{}{Nucleo Central}
{249}{}{Sala de Reuniao}
{250}{}{Alojamentos}
{251}{}{Alojamentos}
{252}{}{Passagem Bloqueada}
{253}{}{Passagem Bloqueada}
{254}{}{Camara de Ar}
{255}{}{Salao dos Mortos}
{256}{}{Gabriel}
{257}{}{Mesa de Jogo de Dados}
{258}{}{Boca-de-Lobo}
{259}{}{Boca-de-Lobo}
{260}{}{Escada}
{261}{}{Escada}
{262}{}{Guarda do Portao}
{263}{}{Guarda do Racionamento D'água}
{264}{}{Bacia Hidrografica}
{265}{}{Boca-de-Lobo}
{266}{}{Boca-de-Lobo}
{267}{}{Boca-de-Lobo}
{268}{}{Cidadão da Vault 13}
{269}{}{Escada}
{270}{}{Escada}
{271}{}{Escada}
{272}{}{Andrew}
{273}{}{Hotel dos Mortos}
{274}{}{Lorriane}
{275}{}{Boca-de-Lobo}
{276}{}{Boca-de-Lobo}
{277}{}{Boca-de-Lobo}
{278}{}{Oficial da Vault 13}
{279}{}{Escada}
{280}{}{Escada}
{281}{}{Escada}
{282}{}{Cavernas dos Radscorpions}
{283}{}{Seth}
{284}{}{Medico da Vault 13}
{285}{}{Cidadão da Vault 13}
{286}{}{Cassino de Junktown}
{287}{}{Crashhouse de Junktown}
{288}{}{Entrada de Junktown}
{289}{}{Passagem Bloqueada}
{290}{}{Camara de Ar}
{291}{}{Provisões Medicas}
{292}{}{Entrada da Vault 15}
{293}{}{Shady Sands}
{294}{}{Shady Sands}
{295}{}{Laboratorio Medico}
{296}{}{Barraco Abandonado}
{297}{}{Seth}
{298}{}{Escriba da Irmandade}
{299}{}{Vault 13}
{300}{}{Elevador}
{301}{}{Elevador}
{302}{}{Elevador}
{303}{}{Elevador}
{304}{}{Elevador Quebrado}
{305}{}{Entrada da Irmandade do Aço}
{306}{}{Poço de Criacao de Ratos}
{307}{}{Escuridão}
{308}{}{Abertura da Caverna}
{309}{}{Cidadão da Vault 13}
{310}{}{Seu Alojamento}
{311}{}{Katrina}
{312}{}{Abertura da Caverna}
{313}{}{Nucleo Central da Vault 13}
{314}{}{Computador}
{315}{}{Sala de Operações da Vault 13}
{316}{}{Sala de Segurança da Vault 13}
{317}{}{Armazem da Vault 13}
{318}{}{Sala de Reuniao da Vault 13}
{319}{}{Laboratorio Medico da Vault 13}
{320}{}{Monte de Ferro Velho}
{321}{}{Guarda de Junktown}
{322}{}{}
{323}{}{Chama}
{324}{}{Elevador}
{325}{}{Elevador}
{326}{}{Elevador}
{327}{}{Elevador}
{328}{}{Vault 15}
{329}{}{Cachorro}
{330}{}{Guarda Ghoul}
{331}{}{Ghoul Zangado}
{332}{}{Guarda Super Mutante}
{333}{}{Sentinela Super Mutante}
{334}{}{Super Mutante}
{335}{}{Ian}
{336}{}{Curtis}
{337}{}{Crianca}
{338}{}{Saqueadores}
{339}{}{Fruta Apos Mutacao}
{340}{}{Guarda Saqueador}
{341}{}{Avellone}
{342}{}{Cachorro}
{343}{}{Duc}
{344}{}{Cidade}
{345}{}{Costa}
{346}{}{Montanha}
{347}{}{Hernandez}
{348}{}{Cavernas}
{349}{}{Miles}
{350}{}{Smitty}
{351}{}{Morador de Adytum}
{352}{}{Regulador}
{353}{}{Lorri}
{354}{}{Sammael}
{355}{}{Caleb}
{356}{}{Taylor}
{357}{}{Julianna}
{358}{}{Sabio dos Seguidores}
{359}{}{Iniciado dos Seguidores}
{360}{}{Batedor dos Nightkin}
{361}{}{Sabio das Crianças da Catedral}
{362}{}{Iniciado das Crianças da Catedral}
{363}{}{Batedor dos Seguidores}
{364}{}{Guarda dos Seguidores}
{365}{}{Pensador Super Mutante}
{366}{}{Heather}
{367}{}{Peter}
{368}{}{Jake}
{369}{}{Orfeo}
{370}{}{Marney}
{371}{}{Neil}
{372}{}{Amber}
{373}{}{Uthern}
{374}{}{Talius}
{375}{}{Guarda das Crianças da Catedral}
{376}{}{Batedor das Crianças da Catedral}
{377}{}{Batedor Super Mutante}
{378}{}{Razor}
{379}{}{Capataz dos Blades}
{380}{}{Fogo}
{381}{}{Beca}
{382}{}{Mestre das Armas dos Blades}
{383}{}{Michelle}
{384}{}{Observador Noturno dos Blades}
{385}{}{Romero}
{386}{}{Irmandade do Aço}
{387}{}{Irmandade do Aço}
{388}{}{Jon}
{389}{}{Prisoneiro}
{390}{}{Escriba da Irmandade}
{391}{}{Escada}
{392}{}{Corpo Carbonizado}
{393}{}{Ossos Secos}
{394}{}{Cadaver envolvido numa armadura estranha}
{395}{}{Holodisco}
{396}{}{Area da Radiação}
{397}{}{Cadaver envolvido numa armadura estranha}
{398}{}{Porta Segura}
{399}{}{Computador}
{400}{}{Porta Segura}
{401}{}{Gerador}
{402}{}{Bomba D'água}
{403}{}{Alojamentos}
{404}{}{Arma Sentinela}
{405}{}{Porta com tinta vermelha nela}
{406}{}{Porta com tinta azul nela}
{407}{}{Porta segura}
{408}{}{Cofre Bem Fechado}
{409}{}{Computador}
{410}{}{Cela}
{411}{}{Mesa}
{412}{}{Computador}
{413}{}{Esqueleto incomum}
{414}{}{Nota}
{415}{}{Farli}
{416}{}{Darrel}
{417}{}{Guarda Paladino da Irmandade}
{418}{}{Talus}
{419}{}{Sophia}
{420}{}{Michael}
{421}{}{Porta Segura}
{422}{}{Escriba da Irmandade}
{423}{}{Escriba da Irmandade}
{424}{}{Sentinela Paladino da Irmandade}
{425}{}{Paladino da Irmandade}
{426}{}{Guarda Paladino da Irmandade}
{427}{}{Paladino da Irmandade}
{428}{}{Elevador com tinta azul nele}
{429}{}{Cavaleiro da Irmandade}
{430}{}{Cavaleiro da Irmandade}
{431}{}{Escrivaninha}
{432}{}{Sistemas de Armas Preparados}
{433}{}{Holodisco Estranho}
{434}{}{Armario}
{435}{}{Fumos Nocivos}
{436}{}{Lasers}
{437}{}{Saqueador Enlouquecido}
{438}{}{Sinthia}
{439}{}{Marcelles}
{440}{}{Cofre Seguro}
{441}{}{Bob}
{442}{}{Trish}
{443}{}{Porta da Vault 13}
{444}{}{Computador da Porta}
{445}{}{Holodisco}
{446}{}{Holodisco}
{447}{}{Holodisco}
{448}{}{Holodisco}
{449}{}{Holodisco}
{450}{}{Holodisco}
{451}{}{Jogador}
{452}{}{Phil}
{453}{}{Dogmeat}
{454}{}{Maquina de Slots}
{455}{}{Maquina de Slots}
{456}{}{Mesa do Blackjack}
{457}{}{Mesa do Blackjack}
{458}{}{Tecnico das Crianças da Catedral}
{459}{}{Abel}
{460}{}{Campo de Força}
{461}{}{Radio}
{462}{}{Sinal}
{463}{}{Porta Muito Segura}
{464}{}{Computador}
{465}{}{Robobrain}
{466}{}{Robobrain}
{467}{}{Flip}
{468}{}{Computador}
{469}{}{Sargento Nightkin}
{470}{}{Sentinela Nightkin}
{471}{}{Computador}
{472}{}{Lenore}
{473}{}{Computador}
{474}{}{Cachorro}
{475}{}{Lenore}
{476}{}{Phil}
{477}{}{Zack}
{478}{}{Theresa}
{479}{}{Cidadão Aborrecido da Vault 13}
{480}{}{Refrigerador}
{481}{}{Escriba da Irmandade}
{482}{}{Jason}
{483}{}{Facinora}
{484}{}{Lasher}
{485}{}{Vinnie}
{486}{}{Victor}
{487}{}{Shark}
{488}{}{Sherry}
{489}{}{Tycho}
{490}{}{Capataz dos Skulz}
{491}{}{Slummer}
{492}{}{Zark}
{493}{}{Calder}
{494}{}{Sentinela Nightkin}
{495}{}{Crianca com Atitude}
{496}{}{Cantor}
{497}{}{Ton}
{498}{}{Cantor}
{499}{}{Irma Francis}
{500}{}{Dr. Wu}
{501}{}{Rutger}
{502}{}{Phrax}
{503}{}{Gerador}
{504}{}{Capataz da Cripta}
{505}{}{Capataz dos Tolos}
{506}{}{Lenny}
{507}{}{Quebrador de Gelo}
{508}{}{Skizzer}
{509}{}{Cidadão do Monte de Lixo}
{510}{}{Rocha}
{511}{}{Lex}
{512}{}{Rayze}
{513}{}{Skippy}
{514}{}{Baka}
{515}{}{Espiar as Criptas}
{516}{}{Espiar os Tolos}
{517}{}{Seguidor do Apocalipse}
{518}{}{Computador}
{519}{}{Rato Irradiado}
{520}{}{Refrigerador}
{521}{}{Escada}
{522}{}{Escada}
{523}{}{Boca-de-Lobo}
{524}{}{Boca-de-Lobo}
{525}{}{Vault de Necropolis}
{526}{}{Mapa da Cidade}
{527}{}{Porta da Camara de Ar}
{528}{}{Prateleira}
{529}{}{Prateleira}
{530}{}{Cavernas}
{531}{}{Porta Segura}
{532}{}{Centro de Comando}
{533}{}{Sentinela Super Mutante}
{534}{}{Krupper}
{535}{}{VanHaggen}
{536}{}{Vasquez}
{537}{}{Batedor de Junktown}
{538}{}{Cidadão de Junktown}
{539}{}{Saqueador}
{540}{}{Jarvis}
{541}{}{Fortaleza}
{542}{}{Tanques}
{543}{}{Entrada da Base Militar}
{544}{}{Crianças da Catedral}
{545}{}{Crianças da Catedral}
{546}{}{Vault do Mestre}
{547}{}{Vault do Mestre}
{548}{}{Computador}
{549}{}{Ogiva Nuclear}
{550}{}{Elevador}
{551}{}{Elevador}
{552}{}{Escada}
{553}{}{Escada}
{554}{}{Escada}
{555}{}{Escada}
{556}{}{Porta}
{557}{}{Cavernas}
{558}{}{Vault 13}
{559}{}{Porta Segura}
{560}{}{Holofotes}
{561}{}{Ladrão D'água}
{562}{}{Jennifer}
{563}{}{Explosão}
{564}{}{Cadeira}
{565}{}{Parede da caverna}
{566}{}{Elevador}
{567}{}{Elevador}
{568}{}{Elevador}
{569}{}{Elevador}
{570}{}{Elevador}
{571}{}{Elevador}
{572}{}{Elevador}
{573}{}{Beberrao}
{574}{}{Vault 15}
{575}{}{Caminhao de Nuka Cola}
{576}{}{Disco Voador}
{577}{}{O Glow}
{578}{}{O Glow}
{579}{}{O Glow}
{580}{}{Boneyard de L.A.}
{581}{}{Boneyard de L.A.}
{582}{}{Boneyard de L.A.}
{583}{}{Boneyard de L.A.}
{584}{}{O Hub}
{585}{}{O Hub}
{586}{}{O Hub}
{587}{}{O Hub}
{588}{}{O Hub}
{589}{}{Caverna}
{590}{}{Cabine Telefonica Estranha}
{591}{}{Pegada Grande}
{592}{}{Grupo de Carros Usados}
{593}{}{Manada de Brahmins}
{594}{}{Boca-de-Lobo}
{595}{}{Escada}
{596}{}{Viola}
{597}{}{Surfe}
{598}{}{Porta}
{599}{}{Dane}
{600}{}{Jonathan}
{601}{}{Estudante da Irmandade}
{602}{}{Crianças da Catedral}
{603}{}{Porta Segura}
{604}{}{Esgotos}
{605}{}{Esgotos}
{606}{}{Esgotos}
{607}{}{Lyle}
{608}{}{Neal}
{609}{}{Andar}
{610}{}{Kenji}
{611}{}{O Glow}
{612}{}{O Glow}
{613}{}{Escada}
{614}{}{Escada}
{615}{}{Escada}
{616}{}{Base Militar}
{617}{}{Radscorpion}
{618}{}{Lars}
{619}{}{Elevador}
{620}{}{Elevador}
{621}{}{Elevador}
{622}{}{Elevador}
{623}{}{Elevador}
{624}{}{Soldado Super Mutante}
{625}{}{Sargento Super Mutante}
{626}{}{Porta Muito Segura}
{627}{}{Trofeu}
{628}{}{Saul}
{629}{}{Gustofer}
{630}{}{Robo}
{631}{}{Sentinela Nightkin}
{632}{}{Sargento Nightkin}
{633}{}{Sentinela Nightkin}
{634}{}{Holodisco}
{635}{}{Garret}
{636}{}{Guarda Super Mutante}
{637}{}{Campo de Força}
{638}{}{Campo de Força}
{639}{}{Campo de Força}
{640}{}{Campo de Força}
{641}{}{Campo de Força}
{642}{}{Campo de Força}
{643}{}{Campo de Força}
{644}{}{Campo de Força}
{645}{}{Computador}
{646}{}{Guarda Super Mutante}
{647}{}{Guarda Super Mutante}
{648}{}{Guarda Super Mutante}
{649}{}{Guarda Super Mutante}
{650}{}{Guarda Super Mutante}
{651}{}{Guarda Super Mutante}
{652}{}{Guarda Super Mutante}
{653}{}{Guarda Super Mutante}
{654}{}{Guarda do Lorenzo}
{655}{}{Guarda do Lorenzo}
{656}{}{Billy}
{657}{}{Bob}
{658}{}{Sinal}
{659}{}{Guarda do Lorenzo}
{660}{}{Cleo}
{661}{}{Guia da Caravana}
{662}{}{Dan}
{663}{}{Esposa do Dan}
{664}{}{Hubiano}
{665}{}{Guarda do Decker}
{666}{}{Demetre}
{667}{}{Agente Fry}
{668}{}{Dogmeat}
{669}{}{Porta Muito Segura}
{670}{}{Andar}
{671}{}{Fazendeiro}
{672}{}{Guarda do Far Go Trader}
{673}{}{Oficial de Policia do Hub}
{674}{}{Mercador do Far Go Trader}
{675}{}{Viciado em Heroina}
{676}{}{Guido}
{677}{}{Porta Segura}
{678}{}{Guarda-Costas}
{679}{}{Guarda das Crianças da Catedral}
{680}{}{Fazendeiro}
{681}{}{Guarda Hubiano}
{682}{}{Daren Hightower}
{683}{}{Guarda do Hightower}
{684}{}{Esposa do Hightower}
{685}{}{Hubiano}
{686}{}{Mercador da Caravana}
{687}{}{Oficial de Policia Hubiano}
{688}{}{Crianca das Flores}
{689}{}{Jake}
{690}{}{Paciente das Crianças da Catedral}
{691}{}{Smitty}
{692}{}{Jasmine}
{693}{}{Posto de Trabalho}
{694}{}{Kane}
{695}{}{Keri}
{696}{}{Guarda do Lorenzo}
{697}{}{Lorenzo}
{698}{}{Mercador Mestre}
{699}{}{Richie}
{700}{}{Rufus}
{701}{}{Rutger}
{702}{}{Sid}
{703}{}{Thorndyke}
{704}{}{Troy}
{705}{}{Comerciante dos Mercadores de Agua}
{706}{}{Guarda dos Mercadores de Agua}
{707}{}{Computador}
{708}{}{Sentinela Super Mutante}
{709}{}{Mercador da Caravana}
{710}{}{Aviso}
{711}{}{Alarme}
{712}{}{Andar}
{713}{}{Andar}
{714}{}{Andar}
{715}{}{Andar}
{716}{}{Armario}
{717}{}{Beth}
{718}{}{Guarda da Irmandade}
{719}{}{Guarda da Irmandade}
{720}{}{Treinador da Irmandade}
{721}{}{Trapaca QA}
{722}{}{Izo}
{723}{}{Katja}
{724}{}{Boca-de-Lobo}
{725}{}{Escada}
{726}{}{Escada}
{727}{}{Boca-de-Lobo}
{728}{}{Escada}
{729}{}{Escada}
{730}{}{Porta Muito Segura}
{731}{}{Sr. Maozinha}
{732}{}{Estudante da Irmandade}
{733}{}{Thomas}
{734}{}{Modificar Reacao}
{735}{}{Boca-de-Lobo}
{736}{}{Escada}
{737}{}{Boca-de-Lobo}
{738}{}{Escada}
{739}{}{Guarda do Gizmo}
{740}{}{Capataz do Ripper}
{741}{}{Holodisco}
{742}{}{Deathclaw}
{743}{}{Cria do Deathclaw}
{744}{}{Pescador}
{745}{}{Filho do Pescador}
{746}{}{Cabine Telefonica Incomum}
{747}{}{Pegada Grande}
{748}{}{Cabine Telefonica Incomum}
{749}{}{Brahmin}
{750}{}{Manada de Brahmins}
{751}{}{Campones Ferido}
{752}{}{Guarda Bruto}
{753}{}{Avivar Para Sempre}
{754}{}{Escada}
{755}{}{Escada}
{756}{}{Maquina dos Jornais}
{757}{}{Vendedor de Carros Usados}
{758}{}{Grupo de Carros Usados}
{759}{}{Irmandade do Aço}
{760}{}{Crianças da Catedral}
{761}{}{Entrada da Base Militar}
{762}{}{Sarah}
{763}{}{Agatha}
{764}{}{Chuck}
{765}{}{Alan}
{766}{}{Brenden}
{767}{}{Patrick}
{768}{}{Ismarc}
{769}{}{Zangado Com Você}
{770}{}{Alex}
{771}{}{Gideon}
{772}{}{Jeremiah}
{773}{}{Guarda Super Mutante}
{774}{}{Guarda Super Mutante}
{775}{}{Dr. Lorri}
{776}{}{Moore}
{777}{}{Lucy}
{778}{}{Wiggup}
{779}{}{Cientista Louco}
{780}{}{Vincent}
{781}{}{Partes da Fazenda}
{782}{}{Prisoneiro}
{783}{}{Prisoneiro}
{784}{}{Computador}
{785}{}{Thomas}
{786}{}{Animal de Estimacao do Mestre}
{787}{}{Computador}
{788}{}{Rae}
{789}{}{Porta Muito Segura}
{790}{}{Assistente do Doutor}
{791}{}{Seu Colega de Quarto}
{792}{}{Iniciado da Irmandade do Aço}
{793}{}{Coiote}
{794}{}{Sentinela Super Mutante}
{795}{}{Guarda Super Mutante}
{796}{}{Xerife Greene}
{797}{}{Atendente do Bar}
{798}{}{Mercador Hubiano}
{799}{}{Lance}
{800}{}{Saqueador}
{801}{}{Mercador Hubiano}
{802}{}{Batedor Paladino da Irmandade}
{803}{}{Trent}
{804}{}{Coordenador do Jogo de Dados}
{805}{}{Maquina de Slots}
{806}{}{Bebado}
{807}{}{Jogador}
{808}{}{Prostituta}
{809}{}{John}
{810}{}{Negociante}
{811}{}{Super Mutante que Ora}
{812}{}{Crianca da Catedral que Ora}
{813}{}{Campones}
{814}{}{Coordenador da Roleta}
{815}{}{Campones de Junktown}
{816}{}{Instrutor da Irmandade}
{817}{}{Escriba da Irmandade}
{818}{}{Cavaleiro da Irmandade}
{819}{}{Paladino da Irmandade}
{820}{}{Maquina de Slots}
{821}{}{Escada}
{822}{}{Vao da Escada}
{823}{}{Escriba da Irmandade}
{824}{}{Cavaleiro da Irmandade}
{825}{}{Terminal do Computador}
{826}{}{Terminal do Computador}
{827}{}{Terminal do Computador}
{828}{}{Terminal do Computador}
{829}{}{Terminal do Computador}
{830}{}{Terminal do Computador}
{831}{}{Terminal do Computador}
{832}{}{Terminal do Computador}
{833}{}{Terminal do Computador}
{834}{}{Armario}
{835}{}{Mantis}
{836}{}{Mesa de Trabalho}
{837}{}{Cientista Louco}
{838}{}{Mulher Prisoneira}
{839}{}{Pia}
{840}{}{Corredor da Revulsao}
{841}{}{Gerador}
{842}{}{Computador}
{843}{}{Pasta}
{844}{}{Holodisco}
{845}{}{Holodisco}
{846}{}{Holodisco}
{847}{}{Refrigerador}
{848}{}{Estante de Livros}
{849}{}{Saqueador}
{850}{}{Saqueador}
{851}{}{Saqueador}
{852}{}{Mercador}
{853}{}{Mercador}
{854}{}{Mercador}
{855}{}{Guarda}
{856}{}{Guarda}
{857}{}{Guarda}
{858}{}{Paladino da Irmandade}
{859}{}{Paladino da Irmandade}
{860}{}{Paladino da Irmandade}
{861}{}{Pessoa da Caravana}
{862}{}{}
{863}{}{Saqueador}
{864}{}{Mercadorias a Venda}
{865}{}{Viajando com a Caravana}
{866}{}{Coisas Ditas Comumente}
{867}{}{Lugar Temporario}
{868}{}{Lugar Temporario}
{869}{}{Lugar Temporario}
{870}{}{Cavaleiro Larry}
{871}{}{Escriba da Vree}
{872}{}{Guarda da Vree}
{873}{}{Guarda do Maxson}
{874}{}{Jeremiah}
{875}{}{Porta}
{876}{}{Porta Robusta}
{877}{}{Viajando com a Caravana}
{878}{}{Mercador da Caravana}
{879}{}{Mercador do Far Go Traders}
{880}{}{Mercador das Crimson Caravan}
{881}{}{Comerciante dos Mercadores da Agua}
{882}{}{Mitch}
{883}{}{Lojista}
{884}{}{Mercadorias a Venda}
{885}{}{Luz que Diminui}
{886}{}{Corda}
{887}{}{Jake}
{888}{}{Guarda Ghoul}
{889}{}{Cela da Cadeia de Junktown}
{890}{}{Sentinela Ghoul}
{891}{}{Sentinela Ghoul}
{892}{}{Ghoul Brilhante}
{893}{}{Computador}
{894}{}{Fazendeiro}
{895}{}{Fazendeiro}
{896}{}{Mercador da Caravana}
{897}{}{Mercador da Caravana}
{898}{}{Mercador da Caravana}
{899}{}{Mercador da Caravana}
{900}{}{Porta}
{901}{}{Porta}
{902}{}{Mat}
{903}{}{Luke}
{904}{}{John}
{905}{}{Porta}
{906}{}{Biblioteca}
{907}{}{Quarto Alugado}
{908}{}{Porta}
{909}{}{Escrivaninha}
{910}{}{Estante de Livros}
{911}{}{Tecnico das Crianças da Catedral}
{912}{}{Perigoso}
{913}{}{Caixa de Armazenagem dos Recipientes D'água}
{914}{}{Computador}
{915}{}{Porta}
{916}{}{Julio}
{917}{}{Carroceiro da Caravana}
{918}{}{Estante de Livros}
{919}{}{Paladino que Ataca nas Rupturas}
{920}{}{Batedor dos Seguidores}
{921}{}{Mike}
{922}{}{Vance}
{923}{}{Usuario de Drogas}
{924}{}{Escombros}
{925}{}{Escombros}
{926}{}{Escombros}
{927}{}{Escombros}
{928}{}{Terminal da Força}
{929}{}{Pegadas}
{930}{}{Guarda do Mercador da Agua}
{931}{}{Robo Sentinela}
{932}{}{Porta Segura}
{933}{}{Mercador}
{934}{}{Guarda da Crimson Caravan}
{935}{}{Guarda do Boxe}
{936}{}{Armario}
{937}{}{Porta Muito Solida}
{938}{}{Mutante Estupido}
{939}{}{Quadro dos Boletins}
{940}{}{Mala dos Gun Runners}
{941}{}{Gunther}
{942}{}{Slappy}
{943}{}{Lojista}
{944}{}{Mesa}
{945}{}{Kyle}
{946}{}{Lemmy}
{947}{}{Guarda}
{948}{}{Batedor Super Mutante}
{949}{}{Pessoa da Caravana do Far Go Trader}
{950}{}{Patrulheiro Super Mutante}
{951}{}{Cofre}
{952}{}{Refrigerador}
{953}{}{Porta}
{954}{}{Patrulheiro Super Mutante}
{955}{}{Lama toxica}
{956}{}{Estranho Misterioso}
{957}{}{}
{958}{}{Porta Muito Segura}
{959}{}{Armario}
{960}{}{Armario da Irmandade}
{961}{}{Holodisco com os Dados da Vault}
{962}{}{Sra. Staple}
{963}{}{Luz do Alarme}
{964}{}{Pressionar o Interruptor}
{965}{}{Cavaleiro Paul}
{966}{}{Leon}
{967}{}{Andar}
{968}{}{Andar}
{969}{}{Andar}
{970}{}{George}
{971}{}{Rick}
{972}{}{Caixa forte}
{973}{}{Porta}
{974}{}{Porta}
{975}{}{Emissor do Campo de Força}
{976}{}{Campo de Força}
{977}{}{Geladeira}
{978}{}{Porta}
{979}{}{Campo de Força}
{980}{}{Emissor do Campo de Força}
{981}{}{Campo de Força}
{982}{}{Emissor do Campo de Força}
{983}{}{Campo de Força}
{984}{}{Emissor do Campo de Força}
{985}{}{Campo de Força}
{986}{}{Emissor do Campo de Força}
{987}{}{Campo de Força}
{988}{}{Emissor do Campo de Força}
{989}{}{Flutuador}
{990}{}{Lenore}
{991}{}{Bob}
{992}{}{Porta}
{993}{}{Campo de Força}
{994}{}{Emissor do Campo de Força}
{995}{}{Campo de Força}
{996}{}{Emissor do Campo de Força}
{997}{}{Campo da Dor}
{998}{}{Campo de Força}
{999}{}{Emissor do Campo de Força}
{1000}{}{Campo de Força}
{1001}{}{Emissor do Campo de Força}
{1002}{}{Campo de Força}
{1003}{}{Emissor do Campo de Força}
{1004}{}{Porta do Elevador}
{1005}{}{}
{1006}{}{Porta Protegida}
{1007}{}{Guarda dos Reguladores}
{1008}{}{Ghoul}
{1009}{}{Guarda do Tenente}
{1010}{}{Computador}
{1011}{}{Parede}
{1012}{}{Mutante da Invasao}
{1013}{}{Guarda dos Reguladores}
{1014}{}{Agente Fry}
{1015}{}{Guarda Mutante}
{1016}{}{Soldado do Mestre}
{1017}{}{Dugan}
{1018}{}{MacRae}
{1019}{}{Guarda da Crimson Caravan}
{1020}{}{Guarda da Crimson Caravan}
{1021}{}{Mae Deathclaw}
{1022}{}{Deathclaw}
{1023}{}{Michael}
{1024}{}{Christine}
{1025}{}{Greg}
{1026}{}{Blade}
{1027}{}{Ovo de Deathclaw}
{1028}{}{Radscorpion}
{1029}{}{Caixa}
{1030}{}{Caixa}
{1031}{}{Emissor do Campo de Força}
{1032}{}{Porta}
{1033}{}{Armario}
{1034}{}{Rato}
{1035}{}{Irwin}
{1036}{}{Armadura Motorizada}
{1037}{}{Cofre}
{1038}{}{Saqueador}
{1039}{}{Mathia}
{1040}{}{Andar}
{1041}{}{Brahmin}
{1042}{}{Elder da Irmandade}
{1043}{}{Rato Toupeira}
{1044}{}{Elder da Irmandade}
{1045}{}{Ghoul}
{1046}{}{Bau de Gelo}
{1047}{}{Holodisco}
{1048}{}{Campo de Força}
{1049}{}{Campo de Força}
{1050}{}{Kenny}
{1051}{}{Guarda da Irmandade}
{1052}{}{Hub}
{1053}{}{Griffith}
{1054}{}{Armario}
{1055}{}{Holodisco}
{1056}{}{Prisoneiro}
{1057}{}{Seguidores}
{1058}{}{Porta}
{1059}{}{Emissor do Campo de Força Danificado}
{1060}{}{Teste}
{1061}{}{Item do Trapaceiro}
{1062}{}{Fregues da Caravana}
{1063}{}{Boxeador}
{1064}{}{}
{1065}{}{}
{1066}{}{Brahmin}
{1067}{}{}
{1068}{}{}
{1069}{}{}
{1070}{}{Hooker}
{1071}{}{}
{1072}{}{}
{1073}{}{}
{1074}{}{}
{1075}{}{}
{1076}{}{}
{1077}{}{}
{1078}{}{Motorcycle}
{1079}{}{Trunk}
{1080}{}{}
{1081}{}{Porta}
{1082}{}{Placa de Piso}
{1083}{}{Placa de Piso}
{1084}{}{Placa de Piso}
{1085}{}{Placa de Piso}
{1086}{}{Placa de Piso}
{1087}{}{Armadilha de Lança}
{1088}{}{Armadilha de Lança}
{1089}{}{Armadilha de Lança}
{1090}{}{Armadilha de Lança}
{1091}{}{Armadilha de Lança}
{1092}{}{Armadilha de Lança}
{1093}{}{Armadilha de Lança}
{1094}{}{Armadilha de Lança}
{1095}{}{Armadilha de Lança}
{1096}{}{Armadilha de Lança}
{1097}{}{Armadilha de Lança}
{1098}{}{Armadilha de Lança}
{1099}{}{Armadilha de Lança}
{1100}{}{Armadilha de Lança}
{1101}{}{Armadilha de Lança}
{1102}{}{Armadilha de Lança}
{1103}{}{}
{1104}{}{}
{1105}{}{}
{1106}{}{Mine}
{1107}{}{Caça-Níqueis}
{1108}{}{Crupiê de Craps}
{1109}{}{Garota do Cassino}
{1110}{}{Buker}
{1111}{}{Locker}
{1112}{}{}
{1113}{}{}
{1114}{}{}
{1115}{}{Porta}
