{1}{}{Perguntar sobre o quê?}
{2}{}{Pronto}
{3}{}{Cancelar}
{110}{}{Seus pés estão coçando muito.}
{120}{}{Você está criando um calo feio em cada pé.}
{130}{}{Seus sapatos estão apertando muito; esses calos estão ficando bem inflamados.}
{140}{}{Aquele calo feio em cada pé parece ter virado um dedo a mais. Mas ao menos aquela coceira ardente e persistente sumiu.}
{141}{}{Meu Deus, é a Bess!}
{970}{}{Esse e o meu nome.}
{971}{}{Você esta falando pra mim.}
{972}{}{Por que você faz perguntas bobas. Eu sou essa pessoa.}
{980}{}{Eu não sei nada sobre isso.}
{981}{}{Lamento. Sem pista.}
{982}{}{Nunca ouvi sobre isso.}
{997}{}{Você é insignificante demais para me questionar.}
{998}{}{Não é da sua conta.}
{999}{}{Isso não te diz respeito.}
{2800}{}{O Mestre}
{2801}{}{Chip da Agua}
{2802}{}{Necropolis}
{2803}{}{Set}
{2804}{}{Bacia Hidrografica}
{2805}{}{Hall}
{2806}{}{Help|Help me|Ajuda|Me ajude|Socorro}
{2807}{}{Doctor|Medic|Doc|Doutor|Medico}
{2808}{}{Buy|Buying|Sell|Selling|Barter|Trade|Trading|Business|Bartering|Comprar|Vender|Trocar|Negociar|Negocio|Comercio|Barganha}
{2809}{}{Water}
{2810}{}{Vault|Vault12|Vault 12|Cofre}
{2811}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Ermo|Terra Devastada|La fora}
{2812}{}{Direction|Directions|Whereto|Where to|Direcao|Direcoes|Onde|Para onde|Caminho}
{2813}{}{Fallout|Fall out|nuclear fallout|precipitacao nuclear|radiacao}
{2814}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev|Roubo|Ladrao|Ladroes|Furto|Criminosos}
{2815}{}{Hub}
{2816}{}{Radiation|Rads|Rad|Radiacao}
{2817}{}{Hotel|Motel|Pousada}
{2818}{}{Supermutant|Supermutants|Super Mutant|Super Mutants|Mutant|Mutants|Super Mutante|Super Mutantes|Mutante|Mutantes}
{2819}{}{Pulp}
{2820}{}{Brahmin|Brahmins|Brahma|Vaca}
{2821}{}{Job|Work|Task|Money|Trabalho|Emprego|Tarefa|Servico|Dinheiro|Grana}
{2822}{}{Sewer|Sewers|Esgoto|Esgotos}
{2823}{}{Ghoul|Ghouls|Carnical|Carnicais}
{2900}{}{Ele não é algum cara grande importante?}
{2901}{}{Eu não sei, mas a bacia hidrografica poderia ter um.}
{2902}{}{Você de pe nela. Tudo que restou dela, pelo menos. Este
 lugar esta morrendo, lentamente mas certamente.}
{2903}{}{Ah, eu gosto dele, eu gosto.  Você pode acha-lo no Hall.}
{2904}{}{É para o norte. Cuidado com os guardas.  Eles levam o trabalho
 deles bem a serio.}
{2905}{}{O Hall dos Mortos.  Onde Set faz seus negócios.  É smack
 right no centro de Necropolis.}
{2906}{}{Você não vai achar ajuda aqui.}
{2907}{}{Você está por conta própria.}
{2908}{}{Não negociamos com gente do seu tipo.}
{2909}{}{De mim você não vai conseguir nada.}
{2910}{}{A maioria de nós veio de um Vault.}
{2911}{}{A radiação torna o lugar perigoso para os pele-lisa. Nós, porém, não nos importamos.}
{2912}{}{Se quiser circular pela cidade, vai ter que passar pelos esgotos.}
{2913}{}{É quando a chuva brilha?}
{2914}{}{Se você for pego, vão te abrir ao meio.}
{2915}{}{Não sei, não me importo.}
{2916}{}{Ao contrário dos pele-lisa, não ligamos para a radiação.}
{2917}{}{Fica a leste daqui. Você chega lá pelos esgotos.}
{2918}{}{Os da Bacia Hidrográfica? Eles te transformam em purê.}
{2919}{}{Já vi um daqueles Mutantes na Bacia esmagar um pele-lisa uma vez.}
{2920}{}{Gosto bem do sabor.}
{2921}{}{Talvez o Set tenha um trabalho pra você.}
{2922}{}{Os esgotos são o único jeito de passar pela maior parte dos escombros da cidade.}
{2923}{}{Somos nós.}
{3400}{}{O Mestre}
{3401}{}{Chip da Agua}
{3402}{}{Necropolis}
{3403}{}{Set}
{3404}{}{Bacia Hidrografica}
{3405}{}{Hall}
{3406}{}{Help|Help me|Ajuda|Me ajude|Socorro}
{3407}{}{Doctor|Medic|Doc|Doutor|Medico}
{3408}{}{Buy|Buying|Sell|Selling|Barter|Trade|Trading|Business|Bartering|Comprar|Vender|Trocar|Negociar|Negocio|Comercio|Barganha}
{3409}{}{Water}
{3410}{}{Vault|Vault12|Vault 12|Cofre}
{3411}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Ermo|Terra Devastada|La fora}
{3412}{}{Direction|Directions|Whereto|Where to|Sewers|Direcao|Onde|Para onde|Caminho|Esgotos}
{3413}{}{Fallout|Fall out|nuclear fallout|precipitacao nuclear|radiacao}
{3414}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev|Roubo|Ladrao|Ladroes|Furto|Criminosos}
{3415}{}{Hub}
{3416}{}{Radiation|Rads|Rad|Radiacao}
{3417}{}{Hotel|Motel|Pousada}
{3418}{}{Supermutant|Supermutants|Super Mutant|Super Mutants|Mutant|Mutants|Super Mutante|Super Mutantes|Mutante|Mutantes}
{3419}{}{Pulp}
{3420}{}{Brahmin|Brahmins|Brahma|Vaca}
{3421}{}{Job|Work|Task|Money|Trabalho|Emprego|Tarefa|Servico|Dinheiro|Grana}
{3422}{}{Sewer|Sewers|Esgoto|Esgotos}
{3423}{}{Ghoul|Ghouls|Carnical|Carnicais}
{3500}{}{Ele não é algum cara grande importante?}
{3501}{}{Eu não sei, mas a bacia hidrografica poderia ter um.}
{3502}{}{Você de pe nela. Tudo que restou dela, pelo menos. Este
 lugar esta morrendo, lentamente mas certamente.}
{3503}{}{Ah, eu gosto dele, eu gosto.  Você pode acha-lo no Hall.}
{3504}{}{É para o norte. Cuidado com os guardas.  Eles levam o trabalho
 deles bem a serio.}
{3505}{}{O Hall dos Mortos.  Onde Set faz seus negócios.  É smack
 right no centro de Necropolis.}
{3506}{}{Você não vai achar ajuda aqui.}
{3507}{}{Você está por conta própria.}
{3508}{}{Volta e meia comerciamos com a Crimson Caravan. Eles vêm do Hub.}
{3509}{}{De mim você não vai conseguir nada.}
{3510}{}{A maioria de nós veio de um Vault.}
{3511}{}{A radiação torna o lugar perigoso para os pele-lisa. Nós, porém, não nos importamos.}
{3512}{}{Você está no Motel. Se quiser circular pela cidade, vai ter que passar pelos esgotos.}
{3513}{}{É quando a chuva brilha?}
{3514}{}{Se você for pego, vão te abrir ao meio.}
{3515}{}{É um lugar a alguns dias em algum ponto a oeste daqui.}
{3516}{}{Ao contrário dos pele-lisa, não ligamos para a radiação.}
{3517}{}{Você é tonto? Isto é o Motel!}
{3518}{}{Os da Bacia Hidrográfica? Eles te transformam em purê.}
{3519}{}{Já vi um daqueles Mutantes na Bacia esmagar um pele-lisa uma vez.}
{3520}{}{Gosto bem do sabor.}
{3521}{}{Não há trabalho pra você aqui.}
{3522}{}{Os esgotos são o único jeito de passar pela maior parte dos escombros da cidade.}
{3523}{}{Somos nós.}
{4000}{}{O Mestre}
{4001}{}{Chip da Agua}
{4002}{}{Necropolis}
{4003}{}{Set}
{4004}{}{Bacia Hidrografica}
{4005}{}{Hall}
{4006}{}{Help|Help me|Ajuda|Me ajude|Socorro}
{4007}{}{Doctor|Medic|Doc|Doutor|Medico}
{4008}{}{Buy|Buying|Sell|Selling|Barter|Trade|Trading|Business|Bartering|Comprar|Vender|Trocar|Negociar|Negocio|Comercio|Barganha}
{4009}{}{Water}
{4010}{}{Vault|Vault12|Vault 12|Cofre}
{4011}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Ermo|Terra Devastada|La fora}
{4012}{}{Direction|Directions|Whereto|Where to|Sewers|Direcao|Onde|Para onde|Caminho|Esgotos}
{4013}{}{Fallout|Fall out|nuclear fallout|precipitacao nuclear|radiacao}
{4014}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev|Roubo|Ladrao|Ladroes|Furto|Criminosos}
{4015}{}{Hub}
{4016}{}{Radiation|Rads|Rad|Radiacao}
{4017}{}{Hotel|Motel|Pousada}
{4018}{}{Supermutant|Supermutants|Super Mutant|Super Mutants|Mutant|Mutants|Guard|Guards|Super Mutante|Mutante|Mutantes|Guarda|Guardas}
{4019}{}{Children of the Cathedral|Children|Cathedral|CoC|Filhos da Catedral|Filhos|Catedral}
{4020}{}{Brahmin|Brahmins|Brahma|Vaca}
{4021}{}{Job|Work|Task|Money|Trabalho|Emprego|Tarefa|Servico|Dinheiro|Grana}
{4022}{}{Sewer|Sewers|Esgoto|Esgotos}
{4023}{}{Ghoul|Ghouls|Carnical|Carnicais}
{4100}{}{Ele não é algum cara grande importante?}
{4101}{}{Eu não sei, mas a bacia hidrografica poderia ter um.}
{4102}{}{Você de pe nela. Tudo que restou dela, pelo menos. Este
 lugar esta morrendo, lentamente mas certamente.}
{4103}{}{Ah, eu gosto dele, eu gosto.  Você pode acha-lo no Hall.}
{4104}{}{Cuidado com os guardas.  Eles levam o trabalho deles
 bem a serio.}
{4105}{}{O Hall dos Mortos.  Onde Set faz seus negócios.  É smack
 right no centro de Necropolis.}
{4106}{}{Você não vai achar ajuda aqui.}
{4107}{}{Os Filhos da Catedral talvez te ajudem.}
{4108}{}{Volta e meia comerciamos com a Crimson Caravan. Eles vêm do Hub.}
{4109}{}{De mim você não vai conseguir nada.}
{4110}{}{Você sabia? Há um Vault antigo bem embaixo da Bacia Hidrográfica.}
{4111}{}{A radiação torna o lugar perigoso para os pele-lisa. Nós, porém, não nos importamos.}
{4112}{}{Você está no Motel. Se quiser circular pela cidade, vai ter que passar pelos esgotos.}
{4113}{}{É quando a chuva brilha?}
{4114}{}{Se você for pego, vão te abrir ao meio.}
{4115}{}{É um lugar a alguns dias em algum ponto a oeste daqui.}
{4116}{}{Ao contrário dos pele-lisa, não ligamos para a radiação.}
{4117}{}{Fica em algum lugar a leste. Você vai ter que passar pelos esgotos pra chegar lá.}
{4118}{}{O Set está furioso, porque eles ocupam a Bacia e ele não pode fazer droga nenhuma a respeito.}
{4119}{}{Eles se instalaram num prédio a sudoeste da Bacia.}
{4120}{}{Gosto bem do sabor.}
{4121}{}{Talvez o Set tenha um trabalho pra você. Fale com ele no Salão dos Mortos, se ainda não falou.}
{4122}{}{Os esgotos são o único jeito de passar pela maior parte dos escombros da cidade.}
{4123}{}{Somos nós.}
{4600}{}{Vault}
{4601}{}{Agua}
{4602}{}{Supervisor}
{4603}{}{Chip}
{4604}{}{Chip da Agua}
{4605}{}{Vault-13}
{4606}{}{Vault13}
{4607}{}{Medico}
{4608}{}{Cura}
{4609}{}{Biblioteca}
{4610}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev|Roubo|Ladrao|Ladroes|Furto|Criminosos}
{4611}{}{Cavern Entrance|Cavern|Entrance|Entrada da Caverna|Caverna|Entrada}
{4612}{}{Living Quarters|Quarters|Alojamentos|Aposentos}
{4613}{}{Command Center|Command|Center|Centro de Comando|Comando|Centro}
{4614}{}{Rebels|Rebelion|Rebel|Rebell|Rebeldes|Rebeliao|Rebelde}
{4615}{}{Cindy}
{4616}{}{Ed}
{4617}{}{Lyle}
{4618}{}{Theresa}
{4619}{}{Storage Room|Storage|Deposito|Almoxarifado}
{4620}{}{Radiation|Rads|Rad|Survival|Radiacao|Sobrevivencia}
{4621}{}{What now|What now?|E agora|E agora?}
{4622}{}{Job|Work|Task|Money|Trabalho|Emprego|Tarefa|Servico|Dinheiro|Grana}
{4700}{}{Isto e onde nos vivemos. Você deveria entender isso.}
{4701}{}{O chip controla o nível de pureza no suprimento de água do
 subsolo. É um pedaço de equipamento critico que não pode ser reparado.}
{4702}{}{Um bom homem fazendo um trabalho difícil.}
{4703}{}{O chip controla o nível de pureza no suprimento de água do
 subsolo.  É um pedaço de equipamento critico que não pode ser reparado.}
{4704}{}{O chip controla o nível de pureza no suprimento de água do
 subsolo.  É um pedaço de equipamento critico que não pode ser reparado.}
{4705}{}{Isto e onde nos vivemos. Você deveria entender isso.}
{4706}{}{Isto e onde nos vivemos. Você deveria entender isso.}
{4707}{}{O medico esta no primeiro andar, no medlab. Vá lá se você esta
 machucado.}
{4708}{}{O medico esta no primeiro andar, no medlab. Vá lá se você esta
 machucado.}
{4709}{}{A biblioteca esta na ala oeste do terceiro andar. Isso e aonde os
 computadores de pesquisa estão localizados.}
{4710}{}{É verdade, o povo está com medo e começou a estocar água. Alguns até tentaram roubar do depósito!}
{4711}{}{Ficaram comentando depois que você saiu do Vault. É verdade que a caverna é a casa de ratos realmente enormes?}
{4712}{}{Você deve estar sentindo falta da sua cama depois de tanto tempo lá fora!}
{4713}{}{Se você está procurando por ele, o Supervisor deve estar no Centro de Comando agora.}
{4714}{}{Desculpe, mas não quero falar sobre isso.}
{4715}{}{Acho que ela está em algum lugar dos Alojamentos.}
{4716}{}{É uma pena mesmo o que aconteceu com ele!}
{4717}{}{Não o vejo muito ultimamente. Talvez ele esteja no quarto dele nos Alojamentos?}
{4718}{}{Ah, eu não falo muito com ela mais.}
{4719}{}{Agora guardamos reservas de água no depósito. Um guarda está garantindo que ninguém roube!}
{4720}{}{Dizem que o mundo lá fora ainda está irradiado demais pra estarmos seguros.}
{4721}{}{Desculpe, eu realmente não sei.}
{4722}{}{O Supervisor não te disse o que precisa ser feito?}
{7000}{}{Killian}
{7001}{}{Gizmo}
{7002}{}{Junktown}
{7003}{}{Shady Sands}
{7004}{}{O Hub}
{7005}{}{Chip da Agua}
{7006}{}{Cassino}
{7007}{}{Loja}
{7008}{}{Deathclaw}
{7009}{}{Medic|Doc|Doctor|Help|Healing|Hurt|Wounded|Injured|Morbid|Doc Morbid|Medico|Doutor|Ajuda|Cura|Ferido|Machucado}
{7010}{}{Buy|Buying|Sell|Selling|Barter|Trade|Trading|Business|Bartering|Comprar|Vender|Trocar|Negociar|Negocio|Comercio|Barganha}
{7011}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Outside|Ermo|Terra Devastada|Devastada|La fora|Fora}
{7012}{}{Direction|Directions|Whereto|Where to|Direcao|Direcoes|Onde|Para onde|Caminho}
{7013}{}{Fallout|Fall out|nuclear fallout|precipitacao nuclear|radiacao}
{7014}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev|Roubo|Ladrao|Ladroes|Furto|Criminosos}
{7015}{}{Necropolis|City of the Dead|City of Dead|Cidade dos Mortos}
{7016}{}{Boneyard|LA|Los Angeles|Angels Boneyard}
{7017}{}{Story|Stories|Rumor|Rumors|Rumour|Rumours|Historia|Historias|Boato|Boatos|Fofoca}
{7018}{}{Pitt|Skum Pitt|SkumPitt|Skumpit|Skum|Skum Pit|ScumPit|ScumPitt|Scum}
{7019}{}{Skuls|Skulz|Skulls|Skullz}
{7020}{}{Khan|Khans|Viper|Vipers|Raider|Raiders|Saqueador|Saqueadores}
{7021}{}{Crash|Crash House}
{7022}{}{Beer|Booze|Cerveja|Bebida|Birita}
{7023}{}{Brahmin|Brahmins|Brahma|Vaca}
{7024}{}{Job|Work|Task|Money|Trabalho|Emprego|Tarefa|Servico|Dinheiro|Grana}
{7025}{}{Lars|Sergeant|Junktown Guards|Guards|Guard|Sargento|Guardas|Guarda}
{7026}{}{Vinnie|Victor|Shark}
{7027}{}{Neal}
{7100}{}{Killian e o prefeito. Ele dirige um loja.}
{7101}{}{Gizmo dirige um cassino. Ele parece ok.}
{7102}{}{Esta e Junktown.}
{7103}{}{Umm, Eu acho que é um lugar bem pequeno. Eu nunca estive lá.}
{7104}{}{É uma cidade maior em algum lugar ao sul.}
{7105}{}{O que? Eu lamento.}
{7106}{}{É um grande predio na parte noroeste da cidade.}
{7107}{}{Loja do Killian? É no centro da cidade..}
{7108}{}{Eu não sei, mas o nome me assusta.}
{7109}{}{Se você estiver machucado, o Doc Morbid com certeza pode te ajudar. A clínica dele fica logo ali na esquina.}
{7110}{}{Killian Darkwater comanda a Loja Geral da cidade. Lá você provavelmente vai achar o que precisa.}
{7111}{}{Temos alguns guardas patrulhando o ermo. É um lugar perigoso, mas a gente se vira.}
{7112}{}{Se você procura uma bebida, o Skum Pitt no extremo norte da cidade é o lugar. Quer comprar ou vender? A loja do Killian fica bem no centro. Claro, também tem o cassino do Gizmo no lado oeste, se você estiver a fim de perder.}
{7113}{}{Fico feliz que não esteja chovendo assim faz um tempo.}
{7114}{}{Eles te enforcam se te pegarem roubando.}
{7115}{}{A Cidade dos Mortos, né? Só ouvimos algumas histórias e boatos.}
{7116}{}{É um lugar em algum ponto bem ao sul, até onde eu sei.}
{7117}{}{Sabe como é... Coisas.}
{7118}{}{Esse é o nosso bar. A comida é razoável, mas a cerveja é ótima.}
{7119}{}{Os Skulz são um bando de arruaceiros que trabalham pro Gizmo. Por sorte não dão tanta dor de cabeça.}
{7120}{}{Por sorte não temos muitos problemas com eles aqui embaixo. Ouvi dizer que é bem pior lá pro norte.}
{7121}{}{Se precisar de um lugar pra dormir, dê uma passada na Crash House.}
{7122}{}{Bem que eu tomaria uma agora.}
{7123}{}{Dependemos deles para o comércio com o Hub.}
{7124}{}{Você deveria falar com o Lars ou o Killian sobre isso.}
{7125}{}{Ele é o Sargento dos guardas de Junktown.}
{7126}{}{Ele é um dos Skulz.}
{7127}{}{Ele é dono do Skum Pitt.}
{7600}{}{Killian}
{7601}{}{Gizmo}
{7602}{}{Junktown}
{7603}{}{Shady Sands}
{7604}{}{O Hub}
{7605}{}{Chip da Agua}
{7606}{}{Cassino}
{7607}{}{Loja}
{7608}{}{Deathclaw}
{7609}{}{Medic|Doc|Doctor|Help|Healing|Hurt|Wounded|Injured|Morbid|Doc Morbid|Medico|Doutor|Ajuda|Cura|Ferido|Machucado}
{7610}{}{Buy|Buying|Sell|Selling|Barter|Trade|Trading|Business|Bartering|Comprar|Vender|Trocar|Negociar|Negocio|Comercio|Barganha}
{7611}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Outside|Ermo|Terra Devastada|Devastada|La fora|Fora}
{7612}{}{Direction|Directions|Whereto|Where to|Direcao|Direcoes|Onde|Para onde|Caminho}
{7613}{}{Fallout|Fall out|nuclear fallout|precipitacao nuclear|radiacao}
{7614}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev|Roubo|Ladrao|Ladroes|Furto|Criminosos}
{7615}{}{Necropolis|City of the Dead|City of Dead|Cidade dos Mortos}
{7616}{}{Boneyard|LA|Los Angeles|Angels Boneyard}
{7617}{}{Story|Stories|Rumor|Rumors|Rumour|Rumours|Historia|Historias|Boato|Boatos|Fofoca}
{7618}{}{Pitt|Skum Pitt|SkumPitt|Skumpit|Skum|Skum Pit|ScumPit|ScumPitt|Scum}
{7619}{}{Skuls|Skulz|Skulls|Skullz}
{7620}{}{Khan|Khans|Viper|Vipers|Raider|Raiders|Saqueador|Saqueadores}
{7621}{}{Crash|Crash House}
{7622}{}{Beer|Booze|Cerveja|Bebida|Birita}
{7623}{}{Brahmin|Brahmins|Brahma|Vaca}
{7624}{}{Job|Work|Task|Money|Trabalho|Emprego|Tarefa|Servico|Dinheiro|Grana}
{7625}{}{Vinnie|Victor|Shark}
{7626}{}{Neal}
{7700}{}{Killian e o prefeito.  Ele assumiu quando o pai dele morreu.}
{7701}{}{Gizmo e um homem grande em Junktown.  Ele dirige o cassino e o
 ring de boxe.  Ele faz muito dinheiro e compra muitas coisas do
 Hub.}
{7702}{}{Esta e Junktown.}
{7703}{}{Bem, é uma comunidade realmente pequena ao norte. As pessoas que
 vivem lá são pela maior parte, fazendeiros.  Nós ocasionalmente negociamos
 com eles, mas ele na maioria das vezes querem ser deixados em paz.}
{7704}{}{O Hub e o centro do comercio por aqui.  Quase todos os
 comerciantes vem do Hub.  Eles tem algumas companhias lá que ainda
 fazem coisas.  Se você quiser, você pode ir com dos grupos de comercio deles
 de volta para o Hub.}
{7705}{}{Eu não sei nada sobre isso.}
{7706}{}{Gizmo dirige ele.  Cuidado com as maquinas de slot, você pode perder
 muito dinheiro se você jogar nelas.}
{7707}{}{Darkwaters?  Esta no centro da cidade.  Você pode permutar com
 ele ou pagar em dinheiro.}
{7708}{}{Eu ouvi pessoas falando sobre ele mas eu nunca o vi.  Eles
 dizem que ele vagueia o deserto, atacando na maioria das vezes a noite..}
{7709}{}{Se você estiver machucado, o Doc Morbid com certeza pode te ajudar. A clínica dele fica ao sul daqui.}
{7710}{}{Killian Darkwater comanda a Loja Geral da cidade. Lá você provavelmente vai achar o que precisa.}
{7711}{}{Temos alguns guardas patrulhando o ermo. É um lugar perigoso, mas a gente se vira.}
{7712}{}{Procurando uma bebida? O Skum Pitt. A loja do Killian fica ao sul. O cassino do Gizmo fica logo ali na esquina, se você estiver atrás de diversão.}
{7713}{}{Fico feliz que não esteja chovendo assim faz um tempo.}
{7714}{}{Eles te enforcam se te pegarem roubando.}
{7715}{}{A Cidade dos Mortos, né? Só ouvimos algumas histórias e boatos.}
{7716}{}{É um lugar em algum ponto bem ao sul, até onde eu sei.}
{7717}{}{Sabe como é... Coisas.}
{7718}{}{Esse é o nosso bar. A comida é razoável, mas a cerveja é ótima.}
{7719}{}{Por que a pergunta? Você quer arrumar confusão?}
{7720}{}{Por sorte não temos muitos problemas com eles aqui embaixo. Ouvi dizer que é bem pior lá pro norte.}
{7721}{}{Se precisar de um lugar pra dormir, dê uma passada na Crash House.}
{7722}{}{Bem que eu tomaria uma agora.}
{7723}{}{Você já provou nossa carne seca especial? Melhor que iguana, com certeza.}
{7724}{}{Não sei, você já tentou falar com o Gizmo? Ele comanda o cassino.}
{7725}{}{Ele é um dos Skulz.}
{7726}{}{Ele é dono do Skum Pitt.}
{8200}{}{Killian}
{8201}{}{Gizmo}
{8202}{}{Junktown}
{8203}{}{Shady Sands}
{8204}{}{O Hub}
{8205}{}{Chip da Agua}
{8206}{}{Cassino}
{8207}{}{Loja}
{8208}{}{Deathclaw}
{8209}{}{Medic|Doc|Doctor|Help|Healing|Hurt|Wounded|Injured|Morbid|Doc Morbid|Medico|Doutor|Ajuda|Cura|Ferido|Machucado}
{8210}{}{Buy|Buying|Sell|Selling|Barter|Trade|Trading|Business|Bartering|Comprar|Vender|Trocar|Negociar|Negocio|Comercio|Barganha}
{8211}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Outside|Ermo|Terra Devastada|Devastada|La fora|Fora}
{8212}{}{Direction|Directions|Whereto|Where to|Direcao|Direcoes|Onde|Para onde|Caminho}
{8213}{}{Fallout|Fall out|nuclear fallout|precipitacao nuclear|radiacao}
{8214}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev|Roubo|Ladrao|Ladroes|Furto|Criminosos}
{8215}{}{Necropolis|City of the Dead|City of Dead|Cidade dos Mortos}
{8216}{}{Boneyard|LA|Los Angeles|Angels Boneyard}
{8217}{}{Story|Stories|Rumor|Rumors|Rumour|Rumours|Historia|Historias|Boato|Boatos|Fofoca}
{8218}{}{Pitt|Skum Pitt|SkumPitt|Skumpit|Skum|Skum Pit|ScumPit|ScumPitt|Scum}
{8219}{}{Skuls|Skulz|Skulls|Skullz}
{8220}{}{Khan|Khans|Viper|Vipers|Raider|Raiders|Saqueador|Saqueadores}
{8221}{}{Crash|Crash House}
{8222}{}{Beer|Booze|Cerveja|Bebida|Birita}
{8223}{}{Brahmin|Brahmins|Brahma|Vaca}
{8224}{}{Job|Work|Task|Money|Trabalho|Emprego|Tarefa|Servico|Dinheiro|Grana}
{8225}{}{Vinnie|Victor|Shark}
{8226}{}{Neal}
{8300}{}{Killian e o prefeito.  Ele assumiu a direção quando o pai dele morreu.}
{8301}{}{Gizmo e um homem grande em Junktown.  Ele dirige o cassino e o 
ring de boxe.  Ele faz muito dinheiro e compra muitas coisas do
 Hub.}
{8302}{}{Esta e Junktown.}
{8303}{}{Bem, é uma comunidade realmente pequena ao norte. As pessoas que
 vivem lá são pela maior parte, fazendeiros.  Nós ocasionalmente negociamos
 com eles, mas ele na maioria das vezes querem ser deixados em paz.}
{8304}{}{O Hub e o centro do comercio por aqui.  Quase todos os
 comerciantes vem do Hub.  Eles tem algumas companhias lá que ainda
 fazem coisas.  Se você quiser, você pode ir com dos grupos de comercio deles
 de volta para o Hub.}
{8305}{}{Eu não sei nada sobre isso.}
{8306}{}{Gizmo dirige ele.  Cuidado com as maquinas de slot, você pode perder
 muito dinheiro se você jogar nelas.}
{8307}{}{Darkwaters?  Esta no centro da cidade.  Você pode permutar com
 ele ou pagar em dinheiro.}
{8308}{}{Eu ouvi pessoas falando sobre ele mas eu nunca o vi.  Eles
 dizem que ele vagueia o deserto, atacando na maioria das vezes a noite.}
{8309}{}{Se você estiver machucado, o Doc Morbid com certeza pode te ajudar. A clínica dele fica ao sul daqui.}
{8310}{}{Killian Darkwater comanda a Loja Geral. Lá você provavelmente vai achar o que precisa.}
{8311}{}{Temos alguns guardas patrulhando o ermo. É um lugar perigoso, mas a gente se vira.}
{8312}{}{A loja do Killian fica logo ali na esquina. Se você procura uma bebida, o Skum Pitt fica ao norte daqui. Também tem o cassino do Gizmo se você estiver atrás de diversão.}
{8313}{}{Fico feliz que não esteja chovendo assim faz um tempo.}
{8314}{}{Eles te enforcam se te pegarem roubando.}
{8315}{}{A Cidade dos Mortos, né? Só ouvimos algumas histórias e boatos.}
{8316}{}{É um lugar em algum ponto bem ao sul, até onde eu sei.}
{8317}{}{Sabe como é... Coisas.}
{8318}{}{Esse é o nosso bar. A comida é razoável, mas a cerveja é ótima.}
{8319}{}{Por que a pergunta? Você quer arrumar confusão?}
{8320}{}{Por sorte não temos muitos problemas com eles aqui embaixo. Ouvi dizer que é bem pior lá pro norte.}
{8321}{}{Se precisar de um lugar pra dormir, dê uma passada na Crash House.}
{8322}{}{Bem que eu tomaria uma agora.}
{8323}{}{Você já provou nossa carne seca especial? Melhor que iguana, com certeza.}
{8324}{}{Não sei, você já tentou falar com o Gizmo?}
{8325}{}{Ele é um dos Skulz.}
{8326}{}{Ele é o dono do Skum Pitt.}
{8800}{}{O Mestre}
{8801}{}{A Guerra}
{8802}{}{O Êxodo}
{8803}{}{O Exercito Estranho}
{8804}{}{A Irmandade}
{8805}{}{Os Mercadores}
{8806}{}{As Caravanas Desaparecidas}
{8807}{}{O Hub}
{8808}{}{Crianças da Catedral}
{8809}{}{Iniciados}
{8810}{}{Escribas}
{8811}{}{Cavaleiros}
{8812}{}{Paladinos}
{8813}{}{Chip da Agua}
{8814}{}{Lorri|Dr Lorri|Dr. Lorri}
{8815}{}{John Maxson|John|Maxson|High Elder}
{8816}{}{Rhombus}
{8817}{}{Vree}
{8818}{}{Medic|Doc|Doctor|Help|Healing|Hurt|Wounded|Injured|Infirmary|Medico|Doutor|Ajuda|Cura|Ferido|Enfermaria}
{8819}{}{Buy|Buying|Sell|Selling|Barter|Trade|Trading|Business|Bartering|Comprar|Vender|Trocar|Negociar|Negocio|Comercio|Barganha}
{8820}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Outside|Ermo|Terra Devastada|Devastada|La fora|Fora}
{8821}{}{Direction|Directions|Whereto|Where to|Direcao|Direcoes|Onde|Para onde|Caminho}
{8822}{}{Fallout|Fall out|nuclear fallout|precipitacao nuclear|radiacao}
{8823}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev|Roubo|Ladrao|Ladroes|Furto|Criminosos}
{8824}{}{Power Armor|PowerArmor|PA|Powered Armor|PoweredArmor|Power|Armor|T-51b|T-51|T51|T51b|Armadura}
{8825}{}{Talus}
{8826}{}{Biblioteca}
{8827}{}{Michael}
{8828}{}{Kyle}
{8829}{}{Brahmin|Brahmins|Brahma|Vaca}
{8830}{}{Job|Work|Task|Money|Trabalho|Emprego|Tarefa|Servico|Dinheiro|Grana}
{8831}{}{Glow|Ancient Order|Ancient|Order|Ordem Antiga|Antiga|Ordem}
{8900}{}{Eu não tenho ideia do que você esta falando.}
{8901}{}{Um ponto terrivelmente baixo na historia humana a qual formou nosso mundo presente. Nós preservamos
 o conhecimento da Guerra para impedir outro holocausto.}
{8902}{}{Uma decisao difícil e pesarosa. Nós perdemos muitas pessoas que escolheram ir embora por sua conta
 propria em vez de viajar com a força principal procurando por um abrigo seguro para viver.}
{8903}{}{Eu não sei muito sobre isso. Os relatorios que eu ouvi e que eles estão se juntando em algum lugar ao norte de nos.}
{8904}{}{Essa e aonde nos estamos.}
{8905}{}{Esses Mercadores das Aguas são bastardos roubadores, mas dos outros grupos, eu não tenho opiniao.}
{8906}{}{Eu não sei nada sobre isso.}
{8907}{}{Um poco de lodo para aqueles mercadores vis. Embora, ocasionalmente, nos deixamos uma das mais civis companhias de
 comercio negociar mercadorias conosco.}
{8908}{}{Eles são um culto.}
{8909}{}{Eles são o futuro da Brotherhood.}
{8910}{}{Eles são os guardioes do conhecimento.}
{8911}{}{Eles são aqueles que fazem as armas para a Brotherhood.}
{8912}{}{Eles são os protetores da Brotherhood.}
{8913}{}{Eu não tenho ideia do que você esta falando.}
{8914}{}{Você vai encontrar a Dra. Lorri no nível 2. Se precisar de equipamento, fale com }
{8915}{}{Ultimamente, o General Maxson fica quase sempre no quarto dele no nível 4. Não sei bem o que está acontecendo com os outros Anciãos.}
{8916}{}{O Paladino-Chefe Rhombus? Você o encontra no nível 1.}
{8917}{}{Ah, a Vree está na biblioteca no nível 3.}
{8918}{}{Se você estiver machucado, a Dra. Lorri pode te ajudar. Procure-a na enfermaria no nível 2.}
{8919}{}{De vez em quando comerciamos com alguns mercadores de fora, mas é só.}
{8920}{}{Não tememos o mundo lá fora.}
{8921}{}{A Dra. Lorri deve estar na enfermaria no nível 2.}
{8922}{}{Nossa Armadura Motorizada nos protege da radiação externa.}
{8923}{}{Irmãos já foram expulsos por crimes menores.}
{8924}{}{Nem todo mundo consegue uma armadura motorizada! Normalmente exige treinamento aprofundado, mas acho que os Anciãos abrem exceções às vezes.}
{8925}{}{Talus é o braço direito do Paladino-Chefe Rhombus.}
{8926}{}{Sabe, onde guardamos os registros históricos e tal? A biblioteca fica no nível 3. A Vree deve estar por lá também.}
{8927}{}{Ele cuida do depósito de suprimentos no nível 1. Se você precisar de algo, vai ter que passar por ele primeiro.}
{8928}{}{Acho que você vai encontrá-lo na oficina do nível 3 fazendo manutenção em algum projeto técnico.}
{8929}{}{Você vê algum curral por aqui?}
{8930}{}{Nem ideia.}
{8931}{}{Cerca de dez anos atrás, enviamos Cavaleiros pra explorar o lugar, mas só acharam ruínas. Ninguém sabe o que aconteceu.}
{11200}{}{Chama Sagrada}
{11201}{}{A Unidade}
{11202}{}{Crianças da Catedral}
{11203}{}{Morpheus}
{11204}{}{Mutantes}
{11205}{}{Mestre}
{11206}{}{Seguidores do Apocalipse}
{11207}{}{Base Militar}
{11208}{}{Os Vats}
{11209}{}{Chip da Agua}
{11210}{}{Medic|Doc|Doctor|Help|Healing|Hurt|Wounded|Injured|Infirmary|Medico|Doutor|Ajuda|Cura|Ferido|Enfermaria}
{11211}{}{Buy|Buying|Sell|Selling|Barter|Trade|Trading|Business|Bartering|Comprar|Vender|Trocar|Negociar|Negocio|Comercio|Barganha}
{11212}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Outside|Ermo|Terra Devastada|Devastada|La fora|Fora}
{11213}{}{Direction|Directions|Whereto|Where to|Direcao|Direcoes|Onde|Para onde|Caminho}
{11214}{}{Fallout|Fall out|nuclear fallout|precipitacao nuclear|radiacao}
{11215}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev|Roubo|Ladrao|Ladroes|Furto|Criminosos}
{11216}{}{Lasher|Father Lasher|Father|Lasher of the Children|Lasher of Children|Criancas|Filhos}
{11217}{}{Wu}
{11218}{}{Brahmin|Brahmins|Brahma|Vaca}
{11300}{}{A Chama Sagrada e aquela que nos levera para um bravo novo mundo
 o qual não tem odio ou guerra.}
{11301}{}{Nós somos todos parte da Unidade. É o amor e paz que nos passamos
 para o nosso povo camarada - humano e mutante.}
{11302}{}{Isso somos nos.}
{11303}{}{Morpheus e o Sumo Sacerdote das Crianças. Tipicamente, ele esta nas
 suas salas quando ele não esta pregando para nos.}
{11304}{}{Eles são pessoas que foram transformadas pela poeira radioativa.
 Mas eles ainda são boas pessoas.}
{11305}{}{Nós todos temos mestres, não temos?}
{11306}{}{Eles são pessoas que procuram destruir a paz a qual o Mestre esta
 tentando por adiante.}
{11307}{}{Lamento, nunca ouvi sobre isso.}
{11308}{}{Lamento, eu não sei do que você esta falando.}
{11309}{}{Eu não tenho pista do que você esta falando.}
{11310}{}{A Unidade é toda a ajuda de que precisamos, mas se você estiver sofrendo, o Dr. Wu alivia a sua dor.}
{11311}{}{Ah, há uma pequena loja dentro da nossa grande catedral.}
{11312}{}{O Sumo Sacerdote diz que vamos transformar o ermo num lugar melhor para todos nós!}
{11313}{}{O Sumo Sacerdote com certeza pode te guiar aonde você precisar ir.}
{11314}{}{Foi o que criou os mutantes, eu acho.}
{11315}{}{Não tema! Se você era um pecador antes, a Chama Sagrada ainda te acolhe.}
{11316}{}{Ele instrui as crianças.}
{11317}{}{Ah, eu não gosto muito dele, mas o que eu sinto não importa.}
{11318}{}{Sim, o que tem eles?}
{15400}{}{Khans}
{15401}{}{Garl}
{15402}{}{Junktown}
{15403}{}{Shady Sands}
{15404}{}{O Hub}
{15405}{}{Chip da Agua}
{15406}{}{Tandi}
{15407}{}{Alya}
{15408}{}{Diana}
{15409}{}{Gwen}
{15410}{}{Petrox}
{15411}{}{Tolya}
{15412}{}{Bebida}
{15413}{}{Drogas}
{15414}{}{Aradesh}
{15415}{}{Help|Hurt|Wounded|Inured|Doc|Doctor|Ajuda|Ferido|Machucado|Medico|Doutor}
{15416}{}{Join|Become Khan|Joining|Entrar|Juntar-se|Virar Khan}
{15417}{}{Leader|Your Boss|Boss|Bossmann|Lider|Chefe|Patrao}
{15418}{}{Medic|Doc|Doctor|Help|Healing|Hurt|Wounded|Injured|Infirmary|Medico|Doutor|Ajuda|Cura|Ferido|Enfermaria}
{15419}{}{Buy|Buying|Sell|Selling|Barter|Trade|Trading|Business|Bartering|Comprar|Vender|Trocar|Negociar|Negocio|Comercio|Barganha}
{15420}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Outside|Ermo|Terra Devastada|Devastada|La fora|Fora}
{15421}{}{Direction|Directions|Whereto|Where to|Direcao|Direcoes|Onde|Para onde|Caminho}
{15422}{}{Fallout|Fall out|nuclear fallout|precipitacao nuclear|radiacao}
{15423}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev|Roubo|Ladrao|Ladroes|Furto|Criminosos}
{15424}{}{Brahmin|Brahmins|Brahma|Vaca}
{15500}{}{Isso somos nos, seu lacaio.}
{15501}{}{Ele e o lider dos Khans.  Ele e o homem mais temido na
 terra despovoada.}
{15502}{}{Eles estão para o sudoeste.  Nós as vezes vamos lá para relaxar
 apos um dia duro saqueando.}
{15503}{}{Por que nós não esmagamos eles completamente esta alem de mim.}
{15504}{}{Eles estão ao sul.  Nós negociamos com eles.  Na maior parte por
 água e munição, mas as vezes eles tambem obtem armas melhores.}
{15505}{}{Por que eu deveria me importar?}
{15506}{}{Eu não conheco ninguém por esse nome.}
{15507}{}{Ela é uma conselheira. Ela planeja os ataques surpresa.}
{15508}{}{She is the armorer. Ela repara nosso equipamento.}
{15509}{}{Ela é a segunda em comando.}
{15510}{}{Ele coleta nossos suprimentos.}
{15511}{}{Ele e o cozinheiro.}
{15512}{}{Você tem algum?}
{15513}{}{Você tem algum?}
{15514}{}{Ele é o chefão de Shady Sands? Não sei muito sobre ele.}
{15515}{}{Aqui você com certeza não vai conseguir ajuda!}
{15516}{}{Isso cabe ao Garl decidir.}
{15517}{}{O Garl lidera os Khans! Ele é o homem mais temido do ermo. Não mexa com ele se você gosta de estar vivo.}
{15518}{}{Está se achando engraçado?}
{15519}{}{A gente não negocia, a gente pega o que é nosso.}
{15520}{}{É aqui que vivemos. É aqui que somos livres.}
{15521}{}{Há uma pequena vila a noroeste daqui, Shady Sands.}
{15522}{}{O quê?}
{15523}{}{Porra, a gente só pega o que é nosso.}
{15524}{}{Às vezes a gente pega uns de Shady Sands. São saborosos.}
{16000}{}{Khans}
{16001}{}{Garl}
{16002}{}{Junktown}
{16003}{}{Shady Sands}
{16004}{}{O Hub}
{16005}{}{Chip da Agua}
{16006}{}{Tandi}
{16007}{}{Aradesh}
{16008}{}{Seth}
{16009}{}{Razlo}
{16010}{}{Medic|Doc|Doctor|Help|Healing|Hurt|Wounded|Injured|Medico|Doutor|Ajuda|Cura|Ferido|Machucado}
{16011}{}{Buy|Buying|Sell|Selling|Barter|Trade|Trading|Business|Bartering|Comprar|Vender|Trocar|Negociar|Negocio|Comercio|Barganha}
{16012}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Outside|Ermo|Terra Devastada|Devastada|La fora|Fora}
{16013}{}{Direction|Directions|Whereto|Where to|Direcao|Direcoes|Onde|Para onde|Caminho}
{16014}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev|Roubo|Ladrao|Ladroes|Furto|Criminosos}
{16015}{}{Scorpions|Scorpion|Rad Scorpion|Radscorpions|Radscorpion|Escorpioes|Escorpiao|Radscorpioes}
{16016}{}{Vipers}
{16017}{}{Brahmin|Brahmins|Brahma|Vaca}
{16018}{}{Plains|Planicie|Planicies|Campina|Campinas}
{16019}{}{Job|Work|Task|Money|Trabalho|Emprego|Tarefa|Servico|Dinheiro|Grana}
{16020}{}{Ian}
{16100}{}{Eles são um grupo sem lei que finjem ser algumas pessoas do
 passado distante.}
{16101}{}{Ele lidera os Khans.  Ele e um dos mais perigosos homens que
 já pos os olhos em Shady Sands.  Ele lidera os clans dos raiders com
 um punho de ferro.}
{16102}{}{Sao 4-6 dias para o sudoeste.  Bom comercio ocasionalmente, mas
 mais frequente do que não, eles tentam to stiff us.}
{16103}{}{Você esta pisando nele.}
{16104}{}{Muito mais longe para o sul do que Junktown.  O Hub é a maior
 cidade que eu ouvi a respeito.  Deve ter mil pessoas lá, no minimo.}
{16105}{}{Lamento, eu não posso ajudar você.}
{16106}{}{Ela é a filha de Aradesh.  Algum dia ela poderia nos liderar, mas
 ela deve aprender a moderar os seus modos.}
{16107}{}{Ele e o lider da nossa comunidade e um verdadeiro heroi.  Você pode
 sempre achar ele no trabalho no salao publico.}
{16108}{}{Ele trabalha com o Aradesh para ter certeza de que nos estamos seguros.}
{16109}{}{Nosso Doutor.  Veja ele se você esta ferido.}
{16110}{}{Se você estiver machucado, procure nosso médico, Razlo. Você o encontra na casa dele a sudoeste.}
{16111}{}{Um dos comerciantes ainda está na cidade. Você vai achá-lo em algum lugar por aqui.}
{16112}{}{Cuidado com os rad scorpions se for lá pra fora.}
{16113}{}{Bom, não tem muita coisa. Como você vê, é aqui que ficam nossas plantações e os brahmin. Se você procura o Seth, ele deve estar na guarita do lado oeste.}
{16114}{}{O Seth e os guardas estão sempre atentos para proteger nossa vila.}
{16115}{}{Cuidado com a cauda deles. O veneno pode ser letal se não for tratado.}
{16116}{}{Pra falar a verdade, eles me assustam mais que os Khans.}
{16117}{}{Ah, tínhamos mais brahmin no passado, mas perdemos alguns em ataques de saqueadores nas planícies há poucos meses.}
{16118}{}{Logo ali fora da nossa vila. É pra onde levamos os brahmin pra pastar.}
{16119}{}{Você deveria falar com o Aradesh, se ainda não falou.}
{16120}{}{O Ian é um dos nossos guardas. Ele foi ferido quando saqueadores atacaram a caravana dele e está conosco desde então.}
{16600}{}{Khans}
{16601}{}{Garl}
{16602}{}{Junktown}
{16603}{}{Shady Sands}
{16604}{}{O Hub}
{16605}{}{Chip da Agua}
{16606}{}{Tandi}
{16607}{}{Aradesh}
{16608}{}{Seth}
{16609}{}{Razlo}
{16610}{}{Medic|Doc|Doctor|Help|Healing|Hurt|Wounded|Injured|Medico|Doutor|Ajuda|Cura|Ferido|Machucado}
{16611}{}{Buy|Buying|Sell|Selling|Barter|Trade|Trading|Business|Bartering|Comprar|Vender|Trocar|Negociar|Negocio|Comercio|Barganha}
{16612}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Outside|Ermo|Terra Devastada|Devastada|La fora|Fora}
{16613}{}{Direction|Directions|Whereto|Where to|Direcao|Direcoes|Onde|Para onde|Caminho}
{16614}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev|Roubo|Ladrao|Ladroes|Furto|Criminosos}
{16615}{}{Scorpions|Scorpion|Rad Scorpion|Radscorpions|Radscorpion|Escorpioes|Escorpiao|Radscorpioes}
{16616}{}{Vipers}
{16617}{}{Brahmin|Brahmins|Brahma|Vaca}
{16618}{}{Plains|Planicie|Planicies|Campina|Campinas}
{16619}{}{Job|Work|Task|Money|Trabalho|Emprego|Tarefa|Servico|Dinheiro|Grana}
{16620}{}{Ian}
{16621}{}{Vault 15|Vault|Vault15}
{16700}{}{Eles são um grupo sem lei que finjem ser algumas pessoas do
 passado distante.}
{16701}{}{Ele lidera os Khans.  Ele e um dos mais perigosos homens que
 já pos os olhos em Shady Sands.  Ele lidera os clans dos raiders com
 um punho de ferro.}
{16702}{}{Sao 4-6 dias para o sudoeste.  Bom comercio ocasionalmente, mas
 mais frequente do que não, eles tentam to stiff us.}
{16703}{}{Você esta pisando nele.}
{16704}{}{Muito mais longe para o sul do que Junktown.  O Hub é a maior
 cidade que eu ouvi a respeito.  Deve ter mil pessoas lá, no minimo.}
{16705}{}{Lamento, eu não posso ajudar você.}
{16706}{}{Ela é a filha de Aradesh.  Algum dia ela poderia nos liderar, mas
 ela deve aprender a moderar os seus modos.}
{16707}{}{Ele e o lider da nossa comunidade e um verdadeiro heroi.  Você pode
 sempre achar ele no trabalho no salao publico.}
{16708}{}{Ele trabalha com o Aradesh para ter certeza de que nos estamos seguros.}
{16709}{}{Nosso Doutor.  Veja ele se você esta ferido.}
{16710}{}{O Razlo é nosso médico. Se você estiver machucado, pode encontrá-lo na casa dele a sudoeste.}
{16711}{}{Claro que negociamos. Se você tiver sorte, um dos comerciantes ainda está na cidade. Procure por ele no lado leste.}
{16712}{}{Cuidado com os rad scorpions se for lá pra fora.}
{16713}{}{Bom, não tem muita coisa. A guarita fica à direita do portão. Você vai achar o Seth lá. Nossas plantações ficam no lado leste. O curral dos brahmin também é perto de lá.}
{16714}{}{O Seth e os guardas estão sempre atentos para proteger nossa vila.}
{16715}{}{Cuidado com a cauda deles. O veneno pode ser letal se não for tratado.}
{16716}{}{Pra falar a verdade, eles me assustam mais que os Khans.}
{16717}{}{Ah, tínhamos mais brahmin no passado, mas perdemos alguns em ataques de saqueadores nas planícies há poucos meses.}
{16718}{}{Logo ali fora da nossa vila. É pra onde levamos os brahmin pra pastar.}
{16719}{}{Você deveria falar com o Aradesh, se ainda não falou.}
{16720}{}{O Ian é um dos nossos guardas. Ele foi ferido quando saqueadores atacaram a caravana dele e está conosco desde então.}
{16721}{}{O Vault 15 é de onde a maioria de nós veio.}
{17800}{}{Adytum}
{17801}{}{Os Seguidores}
{17802}{}{A Catedral}
{17803}{}{Os Rippers}
{17804}{}{Os Blades}
{17805}{}{Os Gun Runners}
{17806}{}{O Hub}
{17807}{}{Junktown}
{17808}{}{Chip da Agua}
{17809}{}{Loja}
{17810}{}{Zimmerman}
{17811}{}{Necropolis}
{17812}{}{O Glow}
{17813}{}{Os Reguladores}
{17814}{}{Os Scavs}
{17815}{}{A Boneyard}
{17816}{}{Medic|Doc|Doctor|Help|Healing|Hurt|Wounded|Injured|Medico|Doutor|Ajuda|Cura|Ferido|Machucado}
{17817}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Outside|Ermo|Terra Devastada|Devastada|La fora|Fora}
{17818}{}{Direction|Directions|Whereto|Where to|Direcao|Direcoes|Onde|Para onde|Caminho}
{17819}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev|Roubo|Ladrao|Ladroes|Furto|Criminosos}
{17820}{}{Brahmin|Brahmins|Brahma|Vaca}
{17821}{}{Cinema}
{17822}{}{Deathclaw}
{17823}{}{Rumor|Rumors|Rumour|Rumours|Boato|Boatos|Fofoca|Fofocas}
{17824}{}{Chuck}
{17825}{}{Caleb}
{17826}{}{Job|Work|Task|Money|Trabalho|Emprego|Tarefa|Servico|Dinheiro|Grana}
{17900}{}{Isso e aqui.}
{17901}{}{Eles vivem ao norte daqui.}
{17902}{}{Fica um bom trecho ao sul de nós.}
{17903}{}{Eles estão no lado oeste.}
{17904}{}{Eles estão no lado leste.}
{17905}{}{Eles estão alem dos Seguidores ao norte.}
{17906}{}{Nós negociamos com eles.}
{17907}{}{Essa não é uma cidade ao norte daqui?}
{17908}{}{A o que?}
{17909}{}{A loja da Tine e no subsolo perto do portao.}
{17910}{}{Ele e o prefeito.}
{17911}{}{Eu ouco que é fora ao leste.}
{17912}{}{Isso e um mito.}
{17913}{}{Eles nos protegem.}
{17914}{}{Eles vao pro lado de fora para pegar coisas.}
{17915}{}{Esta é a Boneyard.}
{17916}{}{Nem ideia.}
{17917}{}{É duro lá fora.}
{17918}{}{Tem os Seguidores, as Blades e os Gun Runners por aqui.}
{17919}{}{Os Regulators atiram em ladrões na hora.}
{17920}{}{Claro que sei o que é um brahmin! Você é burro?}
{17921}{}{É melhor ficar longe de lá, é tudo o que sei.}
{17922}{}{Já ouvi boatos sobre eles. Se quer minha opinião, é tudo papo furado.}
{17923}{}{Você já falou com o Chuck? Ele é doido.}
{17924}{}{Ele está em algum lugar por aqui.}
{17925}{}{Ele é o líder dos Regulators.}
{17926}{}{Não sei.}
{18000}{}{Adytum}
{18001}{}{Os Seguidores}
{18002}{}{A Catedral}
{18003}{}{Os Rippers}
{18004}{}{Os Blades}
{18005}{}{Os Gun Runners}
{18006}{}{O Hub}
{18007}{}{Junktown}
{18008}{}{Chip da Agua}
{18009}{}{Loja}
{18010}{}{Zimmerman}
{18011}{}{Necropolis}
{18012}{}{O Glow}
{18013}{}{Os Reguladores}
{18014}{}{Os Scavs}
{18015}{}{A Boneyard}
{18016}{}{Medic|Doc|Doctor|Help|Healing|Hurt|Wounded|Injured|Medico|Doutor|Ajuda|Cura|Ferido|Machucado}
{18017}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Outside|Ermo|Terra Devastada|Devastada|La fora|Fora}
{18018}{}{Direction|Directions|Whereto|Where to|Direcao|Direcoes|Onde|Para onde|Caminho}
{18019}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev|Roubo|Ladrao|Ladroes|Furto|Criminosos}
{18020}{}{Brahmin|Brahmins|Brahma|Vaca}
{18021}{}{Cinema}
{18022}{}{Deathclaw}
{18023}{}{Rumor|Rumors|Rumour|Rumours|Boato|Boatos|Fofoca|Fofocas}
{18024}{}{Chuck}
{18025}{}{Caleb}
{18026}{}{Job|Work|Task|Money|Trabalho|Emprego|Tarefa|Servico|Dinheiro|Grana}
{18100}{}{Você esta em Adytum, forasteiro.}
{18101}{}{Os Seguidores vivem em uma velha biblioteca ao norte. Eles pregam
 tolerancia e paz.}
{18102}{}{A Catedral é a ways para o sul, pela baia. As Crianças são uma
 religiao pacifica.}
{18103}{}{Eles estão no lado oeste. They are very vicious and have lots of traps.}
{18104}{}{Eles estão no lado leste. Eles usam algum tipo de facas high-tech.}
{18105}{}{Eles estão alem dos Seguidores ao norte. Eles vendem armas para as gangues.}
{18106}{}{Nós negociamos com eles. Eles são a maior cidade que eu conheco.}
{18107}{}{Eles são uma pequena cidade a nordeste de nos.}
{18108}{}{Nunca ouvi sobre isso.}
{18109}{}{A loja da Tine e no subsolo perto do portao. Ele pode vender a você muitos suprimentos.}
{18110}{}{Ele e o prefeito. Ele faz um bom trabalho.}
{18111}{}{É uma cidade dos mortos, varios dias ao leste.}
{18112}{}{Eu ouvi que é bem, bem para o sul.}
{18113}{}{Eles nos protegem das gangues e mantem a paz.}
{18114}{}{Eles vao lá fora para procurar por coisas.}
{18115}{}{Nós estamos na Boneyard.}
{18116}{}{Havia um pequeno hospital com um médico até alguns anos atrás. Os Regulators acabaram com ele, e com razão, por roubar da gente!}
{18117}{}{Crescer no Boneyard é difícil. Se a falta de comida não te matar, as drogas ou as gangues provavelmente matam.}
{18118}{}{Tem os Seguidores ao norte, as Blades ficam a leste daqui.}
{18119}{}{Os Regulators atiram em ladrões na hora.}
{18120}{}{Se você estiver viajando com brahmin, as gangues certamente vão te marcar como alvo.}
{18121}{}{Esse é o antigo covil dos Rippers.}
{18122}{}{Ouvi dizer que há um ninho deles em algum lugar a leste das Blades, mas eu mesmo nunca vi.}
{18123}{}{O povo fala muito.}
{18124}{}{O vidente? Ele está na tenda dele a sudeste de Adytum.}
{18125}{}{Ele é o líder dos Regulators. Normalmente dá pra encontrá-lo perto da entrada.}
{18126}{}{Talvez falar com o Jon Zimmermann?}
{18200}{}{Adytum}
{18201}{}{Os Seguidores}
{18202}{}{A Catedral}
{18203}{}{Os Rippers}
{18204}{}{Os Blades}
{18205}{}{Os Gun Runners}
{18206}{}{O Hub}
{18207}{}{Junktown}
{18208}{}{Chip da Agua}
{18209}{}{Loja}
{18210}{}{Zimmerman}
{18211}{}{Necropolis}
{18212}{}{O Glow}
{18213}{}{Os Reguladores}
{18214}{}{Os Scavs}
{18215}{}{A Boneyard}
{18216}{}{Medic|Doc|Doctor|Help|Healing|Hurt|Wounded|Injured|Medico|Doutor|Ajuda|Cura|Ferido|Machucado}
{18217}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Outside|Ermo|Terra Devastada|Devastada|La fora|Fora}
{18218}{}{Direction|Directions|Whereto|Where to|Direcao|Direcoes|Onde|Para onde|Caminho}
{18219}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev|Roubo|Ladrao|Ladroes|Furto|Criminosos}
{18220}{}{Brahmin|Brahmins|Brahma|Vaca}
{18221}{}{Cinema}
{18222}{}{Deathclaw}
{18223}{}{Rumor|Rumors|Rumour|Rumours|Boato|Boatos|Fofoca|Fofocas}
{18224}{}{Chuck}
{18225}{}{Caleb}
{18226}{}{Job|Work|Task|Money|Trabalho|Emprego|Tarefa|Servico|Dinheiro|Grana}
{18300}{}{Nós somos os descendentes de uma velha Vault que costumava estar sob
 o lado sul desta cidade.}
{18301}{}{Os Seguidores são um povo culto e pacifico. Eles vivem em uma velha
 biblioteca ao norte daqui.}
{18302}{}{As Crianças adoram um misterioso Deus Sombrio. Eles parecem inofensivos,
 mas há algo estranho sobre a religiao deles. A Catedral esta
 ao sul daqui.}
{18303}{}{Os Rippers são todaos inbred. Eles tem um predio fortificado com armadilhas
 ao redor dele onde eles levam prisoneiros para serem torturados e mortos.}
{18304}{}{Os Blades são notorios por suas vibro-facas. Eles são os
 arqui-inimigos dos Rippers. O lider deles é uma mulher chamada Razor.}
{18305}{}{Eles costumavam ser uma gangue, mas eles se estabeleceram em um deposito no lado
 norte e comecaram a negociar armas brancas e do outro tipo para as pessoas.}
{18306}{}{O Hub e um centro de negocio e comercio. Eles tem companhias que
 realmente produzem coisas. Eles estão a leste de nos.}
{18307}{}{Junktown é uma cidade de tamanho moderado ao leste daqui e ao norte do
 Hub.}
{18308}{}{Lamento, não posso ajudar você com isso.}
{18309}{}{Tine dirige o armazem perto do portao da frente. Ele pode vender pra você
 armas e suprimentos de viagem.}
{18310}{}{Jon e nosso prefeito. Ele faz acordos de negócios, dita as normas e
 delega responsibilidades aos Reguladores e aos Scavs.}
{18311}{}{A cidade dos mortos? Esta supostamente em um lugar habitado por estranhos
 canibais longe para o leste. Eu não visitaria lá se eu fosse você.}
{18312}{}{É um grande lugar radioativo longe, longe para o sul, ou assim me foi dito.}
{18313}{}{Eles são a força policial de Adytum. Eles nos protegem das gangues.
  Caleb e o lider.}
{18314}{}{Os Scavs tem o trabalho de procurar a Boneyard por equipamento
 valioso. Eles são liderados por Sammael.}
{18315}{}{A Boneyard dos Anjos e os restos da antiga cidade de Los Angeles.
  Nós estamos no meio da Boneyard.}
{18316}{}{Havia um pequeno hospital com um médico rua abaixo até alguns anos atrás. Os Regulators acabaram com ele por fornecer drogas e químicos às gangues cruéis.}
{18317}{}{Crescer no Boneyard é difícil. Se a falta de comida não te matar, as drogas ou as gangues provavelmente matam.}
{18318}{}{Tem os Seguidores ao norte, as Blades ficam a leste daqui. Se você atravessar o velho Cinema ao norte, também tem os Gun Runners.}
{18319}{}{Tem muito crime no Boneyard, isso é fato. Os Regulators fazem o possível pra manter tudo isso longe de Adytum.}
{18320}{}{As comitivas de comerciantes pagam bem por proteção por aqui, senão perdem seus brahmin rapidinho.}
{18321}{}{É onde os Rippers tinham o esconderijo antes de algo os expulsar.}
{18322}{}{Ouvi dizer que há um ninho deles em algum lugar a leste das Blades, mas eu mesmo nunca vi.}
{18323}{}{O povo fala muito.}
{18324}{}{O vidente? Ele está na tenda dele a sudeste de Adytum.}
{18325}{}{Ele é o líder dos Regulators. Normalmente dá pra encontrá-lo perto da entrada.}
{18326}{}{Você poderia perguntar ao Miles ou ao Sammael.}
{18400}{}{Adytum}
{18401}{}{Os Seguidores}
{18402}{}{A Catedral}
{18403}{}{Os Rippers}
{18404}{}{Os Blades}
{18405}{}{Os Gun Runners}
{18406}{}{O Hub}
{18407}{}{Junktown}
{18408}{}{Chip da Agua}
{18409}{}{Nicole}
{18410}{}{A Boneyard}
{18411}{}{Job|Work|Task|Money|Trabalho|Emprego|Tarefa|Servico|Dinheiro|Grana}
{18500}{}{É uma vila ao sul daqui.}
{18501}{}{Nós somos os Followers of the Apocalypse.}
{18502}{}{Um culto para o sul, alem de Adytum.}
{18503}{}{Uma gangue a oeste.}
{18504}{}{Uma gangue a leste.}
{18505}{}{Uma gangue ao norte.}
{18506}{}{Uma grande cidade comercial para o nordeste.}
{18507}{}{Uma cidade de tamanho medio ao norte do Hub.}
{18508}{}{Não posso ajudar você, lamento.}
{18509}{}{Ela e nossa lider.}
{18510}{}{Esta é a Boneyard.}
{18511}{}{Não posso te ajudar, desculpe.}
{18600}{}{Adytum}
{18601}{}{Os Seguidores}
{18602}{}{A Catedral}
{18603}{}{Os Rippers}
{18604}{}{Os Blades}
{18605}{}{Os Gun Runners}
{18606}{}{O Hub}
{18607}{}{Junktown}
{18608}{}{Chip da Agua}
{18609}{}{Nicole}
{18610}{}{A Boneyard}
{18611}{}{Job|Work|Task|Money|Trabalho|Emprego|Tarefa|Servico|Dinheiro|Grana}
{18700}{}{Uma pequena cidade ao sul. Ocasionalmente alguns deles visitam.}
{18701}{}{Nós somos os Seguidores do Apocalipse. Nós tomamos este nome porque nos
 viemos apos a tempestade da guerra, para trazer o balsamo da paz.}
{18702}{}{Um estranho culto ao sul de Adytum e do resto da Boneyard. Nicole
 diz que eles estão pra fazer alguma coisa.}
{18703}{}{Uma gangue ultra-violenta ao nosso oeste.}
{18704}{}{Uma gangue a leste. Eles usam vibro-facas.}
{18705}{}{Uma gangue que veio do Hub e vende armas. Eles estão ao norte daqui.}
{18706}{}{O Hub é uma grande cidade de comerciantes e negócios a leste.}
{18707}{}{Junktown é uma pequena cidade ao norte do Hub.}
{18708}{}{Eu não posso ajudar você com isso.}
{18709}{}{Ela e nossa lider. Ela tem uma visao de restaurar a paz a um mund faccionalizado.}
{18710}{}{Este lugar é a Boneyard dos Anjos, os restos da antiga cidade de
 Los Angeles.}
{18711}{}{Você já falou com a Nicole?}
{18800}{}{Adytum}
{18801}{}{Os Seguidores}
{18802}{}{A Catedral}
{18803}{}{Os Rippers}
{18804}{}{Os Blades}
{18805}{}{Os Gun Runners}
{18806}{}{O Hub}
{18807}{}{Junktown}
{18808}{}{Chip da Agua}
{18809}{}{Nicole}
{18810}{}{A Boneyard}
{18811}{}{Necropolis|City of the Dead|City of Dead|Cidade dos Mortos}
{18812}{}{Glow|Hot Spot|Spot|Hot Spots|Ponto Quente|Pontos Quentes}
{18813}{}{Regulators|Regulator|Police|Police Force|Reguladores|Policia}
{18814}{}{Scavs|Scav|Scavanger|Scavengers|Saqueadores|Catadores|Catador}
{18815}{}{Boneyard|LA|Los Angeles|Angels Boneyard}
{18816}{}{Medic|Doc|Doctor|Help|Healing|Hurt|Wounded|Injured|Medico|Doutor|Ajuda|Cura|Ferido|Machucado}
{18817}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Outside|Ermo|Terra Devastada|Devastada|La fora|Fora}
{18818}{}{Direction|Directions|Whereto|Where to|Direcao|Direcoes|Onde|Para onde|Caminho}
{18819}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev|Roubo|Ladrao|Ladroes|Furto|Criminosos}
{18820}{}{Brahmin|Brahmins|Brahma|Vaca}
{18821}{}{Cinema}
{18822}{}{Things|Rumor|Rumors|Rumour|Rumours|Coisas|Boato|Boatos|Fofoca}
{18823}{}{Deathclaw}
{18824}{}{Buy|Buying|Sell|Selling|Barter|Trade|Trading|Business|Bartering|Comprar|Vender|Trocar|Negociar|Negocio|Comercio|Barganha}
{18825}{}{Job|Work|Task|Money|Trabalho|Emprego|Tarefa|Servico|Dinheiro|Grana}
{18900}{}{Uma pequena cidade ao sul. Eles são boas pessoas, ainda que um pouco
 paranoicas. Alguns deles trabalham pra nos de tempos em tempos.}
{18901}{}{Nós somos os Seguidores do Apocalipse. É nosso dever trazer paz
 e aprendizado mais uma vez para o mundo, e para ter certeza que as
 armas da guerra nunca cicatrizem de novo a terra.}
{18902}{}{A Catedral e um grande predio ao sul da Boneyard. As Crianças
 são um culto adorando um deus sombrio e maligno. Elas devem ser paradas
 antes que eles espalhem a religiao dels atraves da violência.}
{18903}{}{Inbreds e chacais. Eles atacam qualquer coisa a vista que não esta
 relaciona a eles. Eles vivem a oeste daqui em uma fortaleza rodeada de armadilhas.}
{18904}{}{Um grupo singularmente perigoso vivendo ao leste, que luta com
 vibro-facas. A lider deles, Razor, veio do Hub e moldou eles
 em uma familia feroz.}
{18905}{}{Eles são uma gangue vivendo em um deposito ao norte, dentro de um fosso de
 lama radioativa. Eles vendem armas para as outras gangues.}
{18906}{}{O Hub é uma vasta cidade mercantil ao leste de nos. Eles enviam
 caravanas para muitos lugares, incluindo Adytum.}
{18907}{}{É uma pequena cidade ao norte do Hub. Me foi dito que é um bom lugar para
 parar para o viajante cansado.}
{18908}{}{Embora eu já li sobre a tecnologia das Vaults, esta um pouco alem de mim.}
{18909}{}{Nicole e nossa lider. Ela e compelida pelo insight e espiritualidade para
 trazer paz para um mundo quebrado pela guerra.}
{18910}{}{Este e o coração da Boneyard dos Anjos, nomeada pela velha cidade de
 Los Angeles e pelos esqueletos dos mortos que littered o lugar
 apos a Bomba.}
{18911}{}{A cidade dos mortos? Ouvimos coisas das comitivas de comerciantes, mas eu mesmo nunca estive lá.}
{18912}{}{É um grande lugar radioativo bem, bem ao sul, ou pelo menos foi o que me disseram.}
{18913}{}{São a tal 'força policial' de Adytum. É melhor manter distância deles, porque não são de confiança.}
{18914}{}{Os catadores têm a função de vasculhar o Boneyard atrás de equipamento valioso. São liderados por Sammael.}
{18915}{}{O Boneyard de Angel são as ruínas da velha cidade de Los Angeles. Estamos no meio do Boneyard.}
{18916}{}{Sinto muito, mas não há ninguém por aqui que possa realmente te ajudar com isso.}
{18917}{}{Crescer no Boneyard é difícil. Se a falta de comida não te matar, as drogas ou as gangues provavelmente matam.}
{18918}{}{Tem os Seguidores ao norte, as Blades ficam a leste daqui. Se você atravessar o velho Cinema ao norte, também tem os Gun Runners.}
{18919}{}{Tem muito crime no Boneyard, isso é fato. Os Regulators fazem o possível pra manter tudo isso longe de Adytum.}
{18920}{}{As comitivas de comerciantes pagam bem por proteção por aqui, senão perdem seus brahmin rapidinho.}
{18921}{}{É onde os Rippers tinham o esconderijo antes de algo os expulsar.}
{18922}{}{Sabe como é... Coisas.}
{18923}{}{Ouvi dizer que há um ninho deles em algum lugar a leste das Blades, mas eu mesmo nunca vi.}
{18924}{}{Se você quer negociar suprimentos, provavelmente deveria visitar Adytum. Se for sobre armas, talvez os Gun Runners a leste do velho Cinema possam te ajudar.}
{18925}{}{A Nicole é nossa líder. Talvez ela tenha um trabalho pra você?}
{19000}{}{Mestre}
{19001}{}{Tenente}
{19002}{}{Crianças da Catedral}
{19003}{}{Seguidores do Apocalipse}
{19004}{}{Nightkin}
{19005}{}{Super Mutantes}
{19006}{}{Mediuns}
{19007}{}{Experimentos}
{19008}{}{Chip da Agua}
{19100}{}{Eu não tenho que dizer nada a você.}
{19101}{}{Tal conhecimento não pertence a seres inferiores.}
{19102}{}{Você não precisa se preocupar com eles.}
{19103}{}{Você e muito inferior para me questionar.}
{19104}{}{Não e da sua conta.}
{19105}{}{Isto não te diz respeito.}
{19106}{}{Você e muito tolo para saber deles.}
{19107}{}{Você não esta autorizado a saber deles.}
{19108}{}{Não me aborreca a respeito de brinquedos.}
{22600}{}{Policia}
{22601}{}{Mercadores das Aguas}
{22602}{}{Caravanas Escarlate}
{22603}{}{Comerciantes que Vao Longe}
{22604}{}{Crianças da Catedral}
{22605}{}{Necropolis}
{22606}{}{Local Quente}
{22607}{}{Junktown}
{22608}{}{Irmandade do Aço}
{22609}{}{Shady Sands}
{22610}{}{Boneyard de Los Angeles}
{22611}{}{Torres de Agua}
{22612}{}{Cidade Velha}
{22613}{}{Centro da Cidade}
{22614}{}{As Elevações}
{22615}{}{Deathclaw}
{22616}{}{Chip da Agua}
{22617}{}{Caravans|Caravan|Caravanas|Caravana}
{22618}{}{Unity}
{22619}{}{Hub}
{22620}{}{Adytum}
{22621}{}{Gun Runners|Gun Runner|Gunrunner|Gunrunners}
{22622}{}{Medic|Doc|Doctor|Help|Healing|Hurt|Wounded|Injured|Medico|Doutor|Ajuda|Cura|Ferido|Machucado}
{22623}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Outside|Ermo|Terra Devastada|Devastada|La fora|Fora}
{22624}{}{Direction|Directions|Whereto|Where to|Direcao|Direcoes|Onde|Para onde|Caminho}
{22625}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev|Roubo|Ladrao|Ladroes|Furto|Criminosos}
{22626}{}{Brahmin|Brahmins|Brahma|Vaca}
{22627}{}{Things|Rumor|Rumors|Rumour|Rumours|Coisas|Boato|Boatos|Fofoca}
{22628}{}{Skag|Skags|Muties|Mutant|Mutants|Mutante|Mutantes}
{22629}{}{Greene|Justin|Justin Greene|Sheriff|Sherif|Mayor|Sheriff Greene}
{22630}{}{All|Mitch|General Store|Generalstore|General|Allnone|All-N-One|All-N-One store|Loja}
{22631}{}{Weapon Shop|Weapon|Weapons|Armory|Armor|Armour|Loja de Armas|Arma|Armas|Arsenal|Armadura}
{22632}{}{Friendly Lending Company|FLC}
{22633}{}{Maltese|Maltese Falcon|Maltese Falkon|Falcon|Nightclub|Club|Night}
{22634}{}{Buy|Buying|Sell|Selling|Barter|Trade|Trading|Business|Bartering|Comprar|Vender|Trocar|Negociar|Negocio|Comercio|Barganha}
{22635}{}{Job|Work|Task|Money|Trabalho|Emprego|Tarefa|Servico|Dinheiro|Grana}
{22636}{}{Missing|Missing Caravan|Missing Caravans|Desaparecida|Caravana Desaparecida|Caravanas Desaparecidas|Sumida}
{22637}{}{Decker}
{22638}{}{Butch}
{22700}{}{A policia e dirigida pelo Xerife Greene para manter a lei é a ordem no Hub. Há
 alguns que acreditam que eles são mais um estorvo do que ajuda.}
{22701}{}{Eles controlam toda a água no Hub. Eles tomaram o controle das torres de água e agora
 as pessoas tem que pagar a eles para obter água.}
{22702}{}{Um grupo louco de comerciantes que tomam grandes riscos de modo a chegar ao topo.}
{22703}{}{Um grupo medio moderado de comerciantes que oferecem preços justos sem tem quer procurar perigo para si mesmos.}
{22704}{}{Um culto religioso que adora algo chamad o Mestre. Eles dirigem um hospital no lado sudeste da cidade
 ao lado dos Mercadores das Aguas.}
{22705}{}{Lugar arrepiante. Alguns dizem que é assombrado por humanos transformados que comem os cerebros das pessoas normais por comida. Esta
 em algum lugar ao leste do Hub.}
{22706}{}{Há algumas estorias que dizem que há um lugar a sudeste daqui o qual foi atingido por uma ogiva nuclear.}
{22707}{}{Isso esta ao norte de nos. Há uma quantia justa de comercio entre nos e eles. Dos rumores, Killian e
 Gizmo estão nas gargantas um do outro.}
{22708}{}{Aquele lugar esta a noroeste daqui. Eles são um bando de aberrações tecno que adoram tecnologia. Pessoas muito assustadoras.}
{22709}{}{Uma cidade primitiva que esta longe ao norte daqui. Não muito e conhecido sobre eles, porque eles não tem dinheiro o bastante
 para negociar conosco.}
{22710}{}{Aquele lugar infestado de ratos esta crivado com a guerra entre gangues. Não fosse pelo grande comercio com Adytum e os Gunrunners, eu
 duvido que qualquer comerciante se aventurasse lá.}
{22711}{}{Aqueles armazenam a água para o Hub. Os Mercadores das Aguas controlam as torres.}
{22712}{}{A cidade velha esta no lado mais a nordeste da cidade. As unicas pessoas que vao lá são skags e  muties. Eu ouvi que
 há um antro de ladroes lá.}
{22713}{}{Isso e aonde todos os mercadores vendem coisas. A Loja de Armas, O Armoreiro, A Companhia de Empréstimos Amistosa e o Falcao Maltes estão
 todos naquela area.}
{22714}{}{Isso e aonde todos os mercadores ricos vivem. A lider dos Mercadores das Aguas, Daren Hightower tem um lugar enorme lá.}
{22715}{}{Um mito para assustar criancinhas para se comportarem.}
{22716}{}{Eu não sei nada sobre isso.}
{22717}{}{As três maiores companhias de caravana do Hub são a Crimson Caravan, os Far Go Traders e os Water Merchants.}
{22718}{}{Não é sobre isso que esse pessoal dos Filhos da Catedral vive falando?}
{22719}{}{Você está bem na entrada principal do Hub!}
{22720}{}{É uma pequena vila lá no Boneyard.}
{22721}{}{Eles produzem e vendem armas.}
{22722}{}{Os Filhos da Catedral mantêm um hospital no lado sudeste da cidade, perto dos Water Merchants.}
{22723}{}{Com as caravanas cruzando o ermo o tempo todo hoje em dia, o comércio no Hub está a todo vapor.}
{22724}{}{Se você seguir a estrada pro sul, chega ao distrito do Centro. De lá, vá pro oeste e vai achar os Heights. A Old Town fica a leste, e os Water Merchants ao sul.}
{22725}{}{Dizem que há um 'Circle of Thieves' no Hub. Pra mim parece papo furado. Quer dizer... o Xerife Greene já teria acabado com eles se fosse verdade.}
{22726}{}{Os brahmin são muito importantes para o Hub. Sem eles, não estaríamos onde estamos hoje.}
{22727}{}{Tenho quase certeza de que a Brotherhood of Steel é responsável pelas caravanas desaparecidas.}
{22728}{}{Os skags e mutantes ficam na Old Town. É melhor manter distância deles.}
{22729}{}{O Xerife comanda a polícia local para manter a lei e a ordem no Hub.}
{22730}{}{A loja All-N-One é cara, mas é a melhor Loja Geral do distrito do Mercado.}
{22731}{}{Se você procura armas novas, a loja da Beth é a melhor do distrito do Mercado.}
{22732}{}{Sem tampinhas? A Friendly Lending Company pode te ajudar.}
{22733}{}{O Maltese Falcon é uma boate no lado oeste do Centro.}
{22734}{}{Siga a estrada pro sul até o Mercado dos Comerciantes. A Loja de Armas, o Arsenal, a Friendly Lending Company e o Maltese Falcon ficam todos nessa área.}
{22735}{}{Acho que você acha trabalho fácil numa das companhias de caravana maiores. Tem os Far Go Traders, a Crimson Caravan ou os Water Merchants logo ali na estrada.}
{22736}{}{As caravanas continuam desaparecendo e ninguém sabe ao certo o que acontece com elas. Mas parece que os Far Go Traders são os mais azarados.}
{22737}{}{Ele é dono do Maltese Falcon, lá no Mercado dos Comerciantes.}
{22738}{}{O Butch é dono dos Far Go Traders, um bom homem. Você o encontra no escritório dele no distrito do Centro.}
{23800}{}{Policia}
{23801}{}{Mercadores das Aguas}
{23802}{}{Caravanas Escarlate}
{23803}{}{Comerciantes que Vao Longe}
{23804}{}{Crianças da Catedral}
{23805}{}{Necropolis}
{23806}{}{Local Quente}
{23807}{}{Junktown}
{23808}{}{Irmandade do Aço}
{23809}{}{Shady Sands}
{23810}{}{Boneyard de Los Angeles}
{23811}{}{Torres de Agua}
{23812}{}{Cidade Velha}
{23813}{}{Centro da Cidade}
{23814}{}{As Elevações}
{23815}{}{Deathclaw}
{23816}{}{Chip da Agua}
{23817}{}{Caravans|Caravan|Caravanas|Caravana}
{23818}{}{Unity}
{23819}{}{Hub}
{23820}{}{Adytum}
{23821}{}{Gun Runners|Gun Runner|Gunrunner|Gunrunners}
{23822}{}{Medic|Doc|Doctor|Help|Healing|Hurt|Wounded|Injured|Medico|Doutor|Ajuda|Cura|Ferido|Machucado}
{23823}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Outside|Ermo|Terra Devastada|Devastada|La fora|Fora}
{23824}{}{Direction|Directions|Whereto|Where to|Direcao|Direcoes|Onde|Para onde|Caminho}
{23825}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev|Roubo|Ladrao|Ladroes|Furto|Criminosos}
{23826}{}{Brahmin|Brahmins|Brahma|Vaca}
{23827}{}{Things|Rumor|Rumors|Rumour|Rumours|Coisas|Boato|Boatos|Fofoca}
{23828}{}{Skag|Skags|Muties|Mutant|Mutants|Mutante|Mutantes}
{23829}{}{Greene|Justin|Justin Greene|Sheriff|Sherif|Mayor|Sheriff Greene}
{23830}{}{All|Mitch|General Store|Generalstore|General|Allnone|All-N-One|All-N-One store|Loja}
{23831}{}{Weapon Shop|Weapon|Weapons|Armory|Armor|Armour|Loja de Armas|Arma|Armas|Arsenal|Armadura}
{23832}{}{Friendly Lending Company|FLC}
{23833}{}{Maltese|Maltese Falcon|Maltese Falkon|Falcon|Nightclub|Club|Night}
{23834}{}{Buy|Buying|Sell|Selling|Barter|Trade|Trading|Business|Bartering|Comprar|Vender|Trocar|Negociar|Negocio|Comercio|Barganha}
{23835}{}{Hope|Singer|Doll}
{23836}{}{Job|Work|Task|Money|Trabalho|Emprego|Tarefa|Servico|Dinheiro|Grana}
{23837}{}{Missing|Missing Caravan|Missing Caravans|Desaparecida|Caravana Desaparecida|Caravanas Desaparecidas|Sumida}
{23838}{}{Decker}
{23839}{}{Butch}
{23840}{}{Beth}
{23841}{}{Lorenzo}
{23900}{}{A policia e dirigida pelo Xerife Greene para manter a lei é a ordem no Hub. Há
 alguns que acreditam que eles são mais um estorvo do que ajuda.}
{23901}{}{Eles controlam toda a água no Hub. Eles tomaram o controle das torres de água e agora
 as pessoas tem que pagar a eles para obter água.}
{23902}{}{Um grupo louco de comerciantes que tomam grandes riscos de modo a chegar ao topo.}
{23903}{}{Um grupo medio moderado de comerciantes que oferecem preços justos sem tem quer procurar perigo para si mesmos.}
{23904}{}{Um culto religioso que adora algo chamad o Mestre. Eles dirigem um hospital no lado sudeste da cidade
 ao lado dos Mercadores das Aguas.}
{23905}{}{Lugar arrepiante. Alguns dizem que é assombrado por humanos transformados que comem os cerebros das pessoas normais por comida. Esta
 em algum lugar ao leste do Hub.}
{23906}{}{Há algumas estorias que dizem que há um lugar a sudeste daqui o qual foi atingido por uma ogiva nuclear.}
{23907}{}{Isso esta ao norte de nos. Há uma quantia justa de comercio entre nos e eles. Dos rumores, Killian e
 Gizmo estão nas gargantas um do outro.}
{23908}{}{Aquele lugar esta a noroeste daqui. Eles são um bando de aberrações tecno que adoram tecnologia. Pessoas muito assustadoras.}
{23909}{}{Uma cidade primitiva que esta longe ao norte daqui. Não muito e conhecido sobre eles, porque eles não tem dinheiro o bastante
 para negociar conosco.}
{23910}{}{Aquele lugar infestado de ratos esta crivado com a guerra entre gangues. Não fosse pelo grande comercio com Adytum e os Gunrunners, eu
 duvido que qualquer comerciante se aventurasse lá.}
{23911}{}{Aqueles armazenam a água para o Hub. Os Mercadores das Aguas controlam as torres.}
{23912}{}{A cidade velha esta no lado mais a nordeste da cidade. As unicas pessoas que vao lá são skags e  muties. Eu ouvi que
 há um antro de ladroes lá.}
{23913}{}{Isso e aonde todos os mercadores vendem coisas. A Loja de Armas, O Armoreiro, A Companhia de Empréstimos Amistosa e o Falcao Maltes estão
 todos naquela area.}
{23914}{}{Isso e aonde todos os mercadores ricos vivem. A lider dos Mercadores das Aguas, Daren Hightower tem um lugar enorme lá.}
{23915}{}{Um mito para assustar criancinhas para se comportarem.}
{23916}{}{Eu não sei nada sobre isso.}
{23917}{}{As três maiores companhias de caravana do Hub são a Crimson Caravan, os Far Go Traders e os Water Merchants.}
{23918}{}{Não é sobre isso que esse pessoal dos Filhos da Catedral vive falando?}
{23919}{}{Você está bem no distrito do Centro do Hub.}
{23920}{}{É uma pequena vila lá no Boneyard.}
{23921}{}{Eles produzem e vendem armas.}
{23922}{}{Os Filhos da Catedral mantêm um hospital no lado sudeste da cidade, perto dos Water Merchants.}
{23923}{}{Com as caravanas cruzando o ermo o tempo todo hoje em dia, o comércio no Hub está a todo vapor.}
{23924}{}{Você está no distrito do Centro. Vá pro oeste e vai achar os Heights, ou pro leste pra chegar na Old Town. Os Water Merchants ficam ao sul daqui.}
{23925}{}{Dizem que há um 'Circle of Thieves' no Hub. Pra mim parece papo furado. Quer dizer... o Xerife Greene já teria acabado com eles se fosse verdade.}
{23926}{}{Os brahmin são muito importantes para o Hub. Sem eles, não estaríamos onde estamos hoje.}
{23927}{}{Tenho quase certeza de que a Brotherhood of Steel é responsável pelas caravanas desaparecidas.}
{23928}{}{Os skags e mutantes ficam na Old Town. É melhor manter distância deles.}
{23929}{}{O Xerife comanda a polícia local para manter a lei e a ordem no Hub.}
{23930}{}{A loja All-N-One é cara, mas é a melhor Loja Geral do distrito do Mercado.}
{23931}{}{Se você procura armas novas, a loja da Beth é a melhor do distrito do Mercado.}
{23932}{}{A Friendly Lending Company é uma agiota.}
{23933}{}{O Maltese Falcon é uma boate. É impossível não vê-la seguindo a estrada ao redor do distrito do Mercado.}
{23934}{}{Do que você está falando? Você está no distrito do Centro, o Mercado dos Comerciantes está bem na sua frente!}
{23935}{}{A Hope canta no Maltese Falcon. Que graça de moça.}
{23936}{}{Acho que você acha trabalho fácil numa das companhias de caravana maiores por aqui.}
{23937}{}{As caravanas continuam desaparecendo e ninguém sabe ao certo o que acontece com elas. Mas parece que os Far Go Traders são os mais azarados.}
{23938}{}{Ele é dono do Maltese Falcon.}
{23939}{}{O Butch é dono dos Far Go Traders, um bom homem.}
{23940}{}{A Beth é a gerente da Loja de Armas. Fica logo ali na esquina.}
{23941}{}{O Lorenzo é o dono da Friendly Lending Company.}
{24400}{}{Policia}
{24401}{}{Mercadores das Aguas}
{24402}{}{Caravanas Escarlate}
{24403}{}{Comerciantes que Vao Longe}
{24404}{}{Crianças da Catedral}
{24405}{}{Necropolis}
{24406}{}{Local Quente}
{24407}{}{Junktown}
{24408}{}{Irmandade do Aço}
{24409}{}{Shady Sands}
{24410}{}{Boneyard de Los Angeles}
{24411}{}{Torres de Agua}
{24412}{}{Cidade Velha}
{24413}{}{Centro da Cidade}
{24414}{}{As Elevações}
{24415}{}{Deathclaw}
{24416}{}{Chip da Agua}
{24417}{}{Caravans|Caravan|Caravanas|Caravana}
{24418}{}{Unity}
{24419}{}{Hub}
{24420}{}{Adytum}
{24421}{}{Gun Runners|Gun Runner|Gunrunner|Gunrunners}
{24422}{}{Medic|Doc|Doctor|Help|Healing|Hurt|Wounded|Injured|Medico|Doutor|Ajuda|Cura|Ferido|Machucado}
{24423}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Outside|Ermo|Terra Devastada|Devastada|La fora|Fora}
{24424}{}{Direction|Directions|Whereto|Where to|Direcao|Direcoes|Onde|Para onde|Caminho}
{24425}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev|Roubo|Ladrao|Ladroes|Furto|Criminosos}
{24426}{}{Brahmin|Brahmins|Brahma|Vaca}
{24427}{}{Things|Rumor|Rumors|Rumour|Rumours|Coisas|Boato|Boatos|Fofoca}
{24428}{}{Skag|Skags|Muties|Mutant|Mutants|Mutante|Mutantes}
{24429}{}{Greene|Justin|Justin Greene|Sheriff|Sherif|Mayor|Sheriff Greene}
{24430}{}{All|Mitch|General Store|Generalstore|General|Allnone|All-N-One|All-N-One store|Loja}
{24431}{}{Weapon Shop|Weapon|Weapons|Armory|Armor|Armour|Loja de Armas|Arma|Armas|Arsenal|Armadura}
{24432}{}{Friendly Lending Company|FLC}
{24433}{}{Maltese|Maltese Falcon|Maltese Falkon|Falcon|Nightclub|Club|Night}
{24434}{}{Buy|Buying|Sell|Selling|Barter|Trade|Trading|Business|Bartering|Comprar|Vender|Trocar|Negociar|Negocio|Comercio|Barganha}
{24435}{}{Job|Work|Task|Money|Trabalho|Emprego|Tarefa|Servico|Dinheiro|Grana}
{24436}{}{Missing|Missing Caravan|Missing Caravans|Desaparecida|Caravana Desaparecida|Caravanas Desaparecidas|Sumida}
{24437}{}{Decker}
{24500}{}{A policia e dirigida pelo Xerife Greene para manter a lei é a ordem no Hub. Há
 alguns que acreditam que eles são mais um estorvo do que ajuda.}
{24501}{}{Eles controlam toda a água no Hub. Eles tomaram o controle das torres de água e agora
 as pessoas tem que pagar a eles para obter água.}
{24502}{}{Um grupo louco de comerciantes que tomam grandes riscos de modo a chegar ao topo.}
{24503}{}{Um grupo medio moderado de comerciantes que oferecem preços justos sem tem quer procurar perigo para si mesmos.}
{24504}{}{Um culto religioso que adora algo chamad o Mestre. Eles dirigem um hospital no lado sudeste da cidade
 ao lado dos Mercadores das Aguas.}
{24505}{}{Lugar arrepiante. Alguns dizem que é assombrado por humanos transformados que comem os cerebros das pessoas normais por comida. Esta
 em algum lugar ao leste do Hub.}
{24506}{}{Há algumas estorias que dizem que há um lugar a sudeste daqui o qual foi atingido por uma ogiva nuclear.}
{24507}{}{Isso esta ao norte de nos. Há uma quantia justa de comercio entre nos e eles. Dos rumores, Killian e
 Gizmo estão nas gargantas um do outro.}
{24508}{}{Aquele lugar esta a noroeste daqui. Eles são um bando de aberrações tecno que adoram tecnologia. Pessoas muito assustadoras.}
{24509}{}{Uma cidade primitiva que esta longe ao norte daqui. Não muito e conhecido sobre eles, porque eles não tem dinheiro o bastante
 para negociar conosco.}
{24510}{}{Aquele lugar infestado de ratos esta crivado com a guerra entre gangues. Não fosse pelo grande comercio com Adytum e os Gunrunners, eu
 duvido que qualquer comerciante se aventurasse lá.}
{24511}{}{Aqueles armazenam a água para o Hub. Os Mercadores das Aguas controlam as torres.}
{24512}{}{A cidade velha esta no lado mais a nordeste da cidade. As unicas pessoas que vao lá são skags e  muties. Eu ouvi que
 há um antro de ladroes lá.}
{24513}{}{Isso e aonde todos os mercadores vendem coisas. A Loja de Armas, O Armoreiro, A Companhia de Empréstimos Amistosa e o Falcao Maltes estão
 todos naquela area.}
{24514}{}{Isso e aonde todos os mercadores ricos vivem. A lider dos Mercadores das Aguas, Daren Hightower tem um lugar enorme lá.}
{24515}{}{Um mito para assustar criancinhas para se comportarem.}
{24516}{}{Eu não sei nada sobre isso.}
{24517}{}{As três maiores companhias de caravana do Hub são a Crimson Caravan, os Far Go Traders e os Water Merchants.}
{24518}{}{Não é sobre isso que esse pessoal dos Filhos da Catedral vive falando?}
{24519}{}{Você já está no Hub. Este é o distrito dos Heights.}
{24520}{}{É uma pequena vila lá no Boneyard.}
{24521}{}{Eles produzem e vendem armas.}
{24522}{}{Os Filhos da Catedral mantêm um hospital no lado sudeste da cidade, perto dos Water Merchants.}
{24523}{}{Com as caravanas cruzando o ermo o tempo todo hoje em dia, o comércio no Hub está a todo vapor.}
{24524}{}{Estes são os Heights. Volte pro leste até o distrito do Centro. Continue pro leste pra chegar na Old Town. Os Water Merchants ficam ao sul do distrito do Centro.}
{24525}{}{Dizem que há um 'Circle of Thieves' no Hub. Pra mim parece papo furado. Quer dizer... o Xerife Greene já teria acabado com eles se fosse verdade.}
{24526}{}{Os brahmin são muito importantes para o Hub. Sem eles, não estaríamos onde estamos hoje.}
{24527}{}{Tenho quase certeza de que a Brotherhood of Steel é responsável pelas caravanas desaparecidas.}
{24528}{}{Os skags e mutantes ficam na Old Town. É melhor manter distância deles.}
{24529}{}{O Xerife comanda a polícia local para manter a lei e a ordem no Hub.}
{24530}{}{A loja All-N-One é cara, mas é a melhor Loja Geral do distrito do Mercado.}
{24531}{}{Se você procura armas novas, a loja da Beth é a melhor do distrito do Mercado.}
{24532}{}{Sem tampinhas? A Friendly Lending Company pode te ajudar.}
{24533}{}{O Maltese Falcon é uma boate no lado oeste do Centro.}
{24534}{}{Siga pro leste até o Mercado dos Comerciantes. A Loja de Armas, o Arsenal, a Friendly Lending Company e o Maltese Falcon ficam todos nessa área.}
{24535}{}{Acho que você acha trabalho fácil numa das companhias de caravana maiores. Tem os Far Go Traders, a Crimson Caravan ou os Water Merchants ali na esquina.}
{24536}{}{As caravanas continuam desaparecendo e ninguém sabe ao certo o que acontece com elas. Mas parece que os Far Go Traders são os mais azarados.}
{24537}{}{Ele é dono do Maltese Falcon, lá no Mercado dos Comerciantes.}
{25000}{}{Policia}
{25001}{}{Mercadores das Aguas}
{25002}{}{Caravanas Escarlate}
{25003}{}{Comerciantes que Vao Longe}
{25004}{}{Crianças da Catedral}
{25005}{}{Necropolis}
{25006}{}{Local Quente}
{25007}{}{Junktown}
{25008}{}{Irmandade do Aço}
{25009}{}{Shady Sands}
{25010}{}{Boneyard de Los Angeles}
{25011}{}{Torres de Agua}
{25012}{}{Cidade Velha}
{25013}{}{Centro da Cidade}
{25014}{}{As Elevações}
{25015}{}{Deathclaw}
{25016}{}{Chip da Agua}
{25017}{}{Caravans|Caravan|Caravanas|Caravana}
{25018}{}{Unity}
{25019}{}{Hub}
{25020}{}{Adytum}
{25021}{}{Gun Runners|Gun Runner|Gunrunner|Gunrunners}
{25022}{}{Medic|Doc|Doctor|Help|Healing|Hurt|Wounded|Injured|Medico|Doutor|Ajuda|Cura|Ferido|Machucado}
{25023}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Outside|Ermo|Terra Devastada|Devastada|La fora|Fora}
{25024}{}{Direction|Directions|Whereto|Where to|Direcao|Direcoes|Onde|Para onde|Caminho}
{25025}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev|Roubo|Ladrao|Ladroes|Furto|Criminosos}
{25026}{}{Brahmin|Brahmins|Brahma|Vaca}
{25027}{}{Things|Rumor|Rumors|Rumour|Rumours|Coisas|Boato|Boatos|Fofoca}
{25028}{}{Skag|Skags|Muties|Mutant|Mutants|Mutante|Mutantes}
{25029}{}{Greene|Justin|Justin Greene|Sheriff|Sherif|Mayor|Sheriff Greene}
{25030}{}{All|Mitch|General Store|Generalstore|General|Allnone|All-N-One|All-N-One store|Loja}
{25031}{}{Weapon Shop|Weapon|Weapons|Armory|Armor|Armour|Loja de Armas|Arma|Armas|Arsenal|Armadura}
{25032}{}{Friendly Lending Company|FLC}
{25033}{}{Maltese|Maltese Falcon|Maltese Falkon|Falcon|Nightclub|Club|Night}
{25034}{}{Buy|Buying|Sell|Selling|Barter|Trade|Trading|Business|Bartering|Comprar|Vender|Trocar|Negociar|Negocio|Comercio|Barganha}
{25035}{}{Job|Work|Task|Money|Trabalho|Emprego|Tarefa|Servico|Dinheiro|Grana}
{25036}{}{Missing|Missing Caravan|Missing Caravans|Desaparecida|Caravana Desaparecida|Caravanas Desaparecidas|Sumida}
{25037}{}{Decker}
{25100}{}{A policia e dirigida pelo Xerife Greene para manter a lei é a ordem no Hub. Há
 alguns que acreditam que eles são mais um estorvo do que ajuda.}
{25101}{}{Eles controlam toda a água no Hub. Eles tomaram o controle das torres de água e agora
 as pessoas tem que pagar a eles para obter água.}
{25102}{}{Um grupo louco de comerciantes que tomam grandes riscos de modo a chegar ao topo.}
{25103}{}{Um grupo medio moderado de comerciantes que oferecem preços justos sem tem quer procurar perigo para si mesmos.}
{25104}{}{Um culto religioso que adora algo chamad o Mestre. Eles dirigem um hospital no lado sudeste da cidade
 ao lado dos Mercadores das Aguas.}
{25105}{}{Lugar arrepiante. Alguns dizem que é assombrado por humanos transformados que comem os cerebros das pessoas normais por comida. Esta
 em algum lugar ao leste do Hub.}
{25106}{}{Há algumas estorias que dizem que há um lugar a sudeste daqui o qual foi atingido por uma ogiva nuclear.}
{25107}{}{Isso esta ao norte de nos. Há uma quantia justa de comercio entre nos e eles. Dos rumores, Killian e
 Gizmo estão nas gargantas um do outro.}
{25108}{}{Aquele lugar esta a noroeste daqui. Eles são um bando de aberrações tecno que adoram tecnologia. Pessoas muito assustadoras.}
{25109}{}{Uma cidade primitiva que esta longe ao norte daqui. Não muito e conhecido sobre eles, porque eles não tem dinheiro o bastante
 para negociar conosco.}
{25110}{}{Aquele lugar infestado de ratos esta crivado com a guerra entre gangues. Não fosse pelo grande comercio com Adytum e os Gunrunners, eu
 duvido que qualquer comerciante se aventurasse lá.}
{25111}{}{Aqueles armazenam a água para o Hub. Os Mercadores das Aguas controlam as torres.}
{25112}{}{A cidade velha esta no lado mais a nordeste da cidade. As unicas pessoas que vao lá são skags e  muties. Eu ouvi que
 há um antro de ladroes lá.}
{25113}{}{Isso e aonde todos os mercadores vendem coisas. A Loja de Armas, O Armoreiro, A Companhia de Empréstimos Amistosa e o Falcao Maltes estão
 todos naquela area.}
{25114}{}{Isso e aonde todos os mercadores ricos vivem. A lider dos Mercadores das Aguas, Daren Hightower tem um lugar enorme lá.}
{25115}{}{Um mito para assustar criancinhas para se comportarem.}
{25116}{}{Eu não sei nada sobre isso.}
{25117}{}{As três maiores companhias de caravana do Hub são a Crimson Caravan, os Far Go Traders e os Water Merchants.}
{25118}{}{Não é sobre isso que esse pessoal dos Filhos da Catedral vive falando?}
{25119}{}{Você está bem no distrito da Old Town do Hub.}
{25120}{}{É uma pequena vila lá no Boneyard.}
{25121}{}{Eles produzem e vendem armas.}
{25122}{}{Os Filhos da Catedral mantêm um hospital no lado sudeste da cidade, perto dos Water Merchants.}
{25123}{}{Com as caravanas cruzando o ermo o tempo todo hoje em dia, o comércio no Hub está a todo vapor.}
{25124}{}{Você está na Cidade Velha, amigo. Vá pro oeste pra chegar ao distrito do Centro. Continue pro oeste e tem os Heights. Os Water Merchants ficam ao sul do distrito do Centro.}
{25125}{}{Crime organizado? Não acredite em todo boato, é só o que eu digo.}
{25126}{}{Os brahmin são muito importantes para o Hub. Sem eles, não estaríamos onde estamos hoje.}
{25127}{}{Dá pra acreditar? Dizem que o velho Slappy viu uma dessas Deathclaws. Até onde eu sei, ele sempre foi doido.}
{25128}{}{Os mais pobres do Hub. Você os encontra por aqui na Old Town.}
{25129}{}{O Xerife comanda a polícia local para manter a lei e a ordem no Hub.}
{25130}{}{A loja All-N-One é cara, mas é a melhor Loja Geral do distrito do Mercado.}
{25131}{}{Se você procura armas novas, a loja da Beth é a melhor do distrito do Mercado.}
{25132}{}{Sem tampinhas? A Friendly Lending Company pode te ajudar.}
{25133}{}{O Maltese Falcon é uma boate no lado oeste do Centro.}
{25134}{}{Siga pro oeste até o Mercado dos Comerciantes. A Loja de Armas, o Arsenal, a Friendly Lending Company e o Maltese Falcon ficam todos nessa área.}
{25135}{}{Acho que você acha trabalho fácil numa das companhias de caravana maiores. Tem os Far Go Traders, a Crimson Caravan ou os Water Merchants ali na esquina.}
{25136}{}{As caravanas continuam desaparecendo e ninguém sabe ao certo o que acontece com elas. Mas parece que os Far Go Traders são os mais azarados.}
{25137}{}{Ele é dono do Maltese Falcon, lá no Mercado dos Comerciantes.}
{25600}{}{Policia}
{25601}{}{Mercadores das Aguas}
{25602}{}{Caravanas Escarlate}
{25603}{}{Comerciantes que Vao Longe}
{25604}{}{Crianças da Catedral}
{25605}{}{Necropolis}
{25606}{}{Local Quente}
{25607}{}{Junktown}
{25608}{}{Irmandade do Aço}
{25609}{}{Shady Sands}
{25610}{}{Boneyard de Los Angeles}
{25611}{}{Torres de Agua}
{25612}{}{Cidade Velha}
{25613}{}{Centro da Cidade}
{25614}{}{As Elevações}
{25615}{}{Deathclaw}
{25616}{}{Chip da Agua}
{25617}{}{Caravans|Caravan|Caravanas|Caravana}
{25618}{}{Unity}
{25619}{}{Hub}
{25620}{}{Adytum}
{25621}{}{Gun Runners|Gun Runner|Gunrunner|Gunrunners}
{25622}{}{Medic|Doc|Doctor|Help|Healing|Hurt|Wounded|Injured|Medico|Doutor|Ajuda|Cura|Ferido|Machucado}
{25623}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Outside|Ermo|Terra Devastada|Devastada|La fora|Fora}
{25624}{}{Direction|Directions|Whereto|Where to|Direcao|Direcoes|Onde|Para onde|Caminho}
{25625}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev|Roubo|Ladrao|Ladroes|Furto|Criminosos}
{25626}{}{Brahmin|Brahmins|Brahma|Vaca}
{25627}{}{Things|Rumor|Rumors|Rumour|Rumours|Coisas|Boato|Boatos|Fofoca}
{25628}{}{Skag|Skags|Muties|Mutant|Mutants|Mutante|Mutantes}
{25629}{}{Greene|Justin|Justin Greene|Sheriff|Sherif|Mayor|Sheriff Greene}
{25630}{}{All|Mitch|General Store|Generalstore|General|Allnone|All-N-One|All-N-One store|Loja}
{25631}{}{Weapon Shop|Weapon|Weapons|Armory|Armor|Armour|Loja de Armas|Arma|Armas|Arsenal|Armadura}
{25632}{}{Friendly Lending Company|FLC}
{25633}{}{Maltese|Maltese Falcon|Maltese Falkon|Falcon|Nightclub|Club|Night}
{25634}{}{Buy|Buying|Sell|Selling|Barter|Trade|Trading|Business|Bartering|Comprar|Vender|Trocar|Negociar|Negocio|Comercio|Barganha}
{25635}{}{Job|Work|Task|Money|Trabalho|Emprego|Tarefa|Servico|Dinheiro|Grana}
{25636}{}{Missing|Missing Caravan|Missing Caravans|Desaparecida|Caravana Desaparecida|Caravanas Desaparecidas|Sumida}
{25637}{}{Decker}
{25700}{}{A policia e dirigida pelo Xerife Greene para manter a lei é a ordem no Hub. Há
 alguns que acreditam que eles são mais um estorvo do que ajuda.}
{25701}{}{Eles controlam toda a água no Hub. Eles tomaram o controle das torres de água e agora
 as pessoas tem que pagar a eles para obter água.}
{25702}{}{Um grupo louco de comerciantes que tomam grandes riscos de modo a chegar ao topo.}
{25703}{}{Um grupo medio moderado de comerciantes que oferecem preços justos sem tem quer procurar perigo para si mesmos.}
{25704}{}{Um culto religioso que adora algo chamad o Mestre. Eles dirigem um hospital no lado sudeste da cidade
 ao lado dos Mercadores das Aguas.}
{25705}{}{Lugar arrepiante. Alguns dizem que é assombrado por humanos transformados que comem os cerebros das pessoas normais por comida. Esta
 em algum lugar ao leste do Hub.}
{25706}{}{Há algumas estorias que dizem que há um lugar a sudeste daqui o qual foi atingido por uma ogiva nuclear.}
{25707}{}{Isso esta ao norte de nos. Há uma quantia justa de comercio entre nos e eles. Dos rumores, Killian e
 Gizmo estão nas gargantas um do outro.}
{25708}{}{Aquele lugar esta a noroeste daqui. Eles são um bando de aberrações tecno que adoram tecnologia. Pessoas muito assustadoras.}
{25709}{}{Uma cidade primitiva que esta longe ao norte daqui. Não muito e conhecido sobre eles, porque eles não tem dinheiro o bastante
 para negociar conosco.}
{25710}{}{Aquele lugar infestado de ratos esta crivado com a guerra entre gangues. Não fosse pelo grande comercio com Adytum e os Gunrunners, eu
 duvido que qualquer comerciante se aventurasse lá.}
{25711}{}{Aqueles armazenam a água para o Hub. Os Mercadores das Aguas controlam as torres.}
{25712}{}{A cidade velha esta no lado mais a nordeste da cidade. As unicas pessoas que vao lá são skags e  muties. Eu ouvi que
 há um antro de ladroes lá.}
{25713}{}{Isso e aonde todos os mercadores vendem coisas. A Loja de Armas, O Armoreiro, A Companhia de Empréstimos Amistosa e o Falcao Maltes estão
 todos naquela area.}
{25714}{}{Isso e aonde todos os mercadores ricos vivem. A lider dos Mercadores das Aguas, Daren Hightower tem um lugar enorme lá.}
{25715}{}{Um mito para assustar criancinhas para se comportarem.}
{25716}{}{Eu não sei nada sobre isso.}
{25717}{}{As três maiores companhias de caravana do Hub são a Crimson Caravan, os Far Go Traders e os Water Merchants.}
{25718}{}{Não é sobre isso que esse pessoal dos Filhos da Catedral vive falando?}
{25719}{}{Este é o Hub.}
{25720}{}{É uma pequena vila lá no Boneyard.}
{25721}{}{Eles produzem e vendem armas.}
{25722}{}{Há um hospital no lado sudeste da cidade, perto dos Water Merchants.}
{25723}{}{Com as caravanas cruzando o ermo o tempo todo hoje em dia, o comércio no Hub está a todo vapor.}
{25724}{}{É na Torre d'Água que você encontra os Water Merchants. Ao norte daqui fica o mais central, o distrito do Centro. Os Heights ficam a oeste dele, e a Old Town a leste.}
{25725}{}{Dizem que há um 'Circle of Thieves' no Hub. Pra mim parece papo furado. Quer dizer... o Xerife Greene já teria acabado com eles se fosse verdade.}
{25726}{}{Os brahmin são muito importantes para o Hub. Sem eles, não estaríamos onde estamos hoje.}
{25727}{}{Tenho quase certeza de que a Brotherhood of Steel é responsável pelas caravanas desaparecidas.}
{25728}{}{Os skags e mutantes ficam na Old Town. É melhor manter distância deles.}
{25729}{}{Ele comanda a polícia e tenta manter a lei e a ordem no Hub.}
{25730}{}{A loja All-N-One é cara, mas é a melhor Loja Geral do distrito do Mercado.}
{25731}{}{Se você procura armas novas, a loja da Beth é a melhor do distrito do Mercado.}
{25732}{}{Sem tampinhas? A Friendly Lending Company pode te ajudar.}
{25733}{}{O Maltese Falcon é uma boate no lado oeste do Centro.}
{25734}{}{Siga pro norte até o Mercado dos Comerciantes. A Loja de Armas, o Arsenal, a Friendly Lending Company e o Maltese Falcon ficam todos nessa área.}
{25735}{}{Bom, você poderia dar uma passada nos Water Merchants, eu acho.}
{25736}{}{As caravanas continuam desaparecendo e ninguém sabe ao certo o que acontece com elas. Mas parece que os Far Go Traders são os mais azarados.}
{25737}{}{Ele é dono do Maltese Falcon, lá no Mercado dos Comerciantes.}
{27400}{}{Adytum}
{27401}{}{Os Seguidores}
{27402}{}{A Catedral}
{27403}{}{Os Rippers}
{27404}{}{Os Blades}
{27405}{}{Os Gun Runners}
{27406}{}{O Hub}
{27407}{}{Junktown}
{27408}{}{Chip da Agua}
{27409}{}{Razor}
{27410}{}{Necropolis}
{27411}{}{O Glow}
{27412}{}{A Boneyard}
{27413}{}{Regulators|Regulator|Police|Police Force|Reguladores|Policia}
{27414}{}{Scavs|Scav|Scavanger|Scavengers|Saqueadores|Catadores|Catador}
{27415}{}{Boneyard|LA|Los Angeles|Angels Boneyard}
{27416}{}{Medic|Doc|Doctor|Help|Healing|Hurt|Wounded|Injured|Medico|Doutor|Ajuda|Cura|Ferido|Machucado}
{27417}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Outside|Ermo|Terra Devastada|Devastada|La fora|Fora}
{27418}{}{Direction|Directions|Whereto|Where to|Direcao|Direcoes|Onde|Para onde|Caminho}
{27419}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev|Roubo|Ladrao|Ladroes|Furto|Criminosos}
{27420}{}{Brahmin|Brahmins|Brahma|Vaca}
{27421}{}{Cinema}
{27422}{}{Deathclaw}
{27423}{}{Rumor|Rumors|Rumour|Rumours|Boato|Boatos|Fofoca|Fofocas}
{27424}{}{Job|Work|Task|Money|Trabalho|Emprego|Tarefa|Servico|Dinheiro|Grana}
{27500}{}{Eles são uma cidade a oeste.}
{27501}{}{Um bando de fracotes.}
{27502}{}{Loucos religiosos.}
{27503}{}{Nossos inimigos jurados!}
{27504}{}{Isso somos nos!}
{27505}{}{Eles vendem armas para nos as vezes.}
{27506}{}{Eu acho que é um lugar de comercio.}
{27507}{}{Nunca ouvi sobre isso.}
{27508}{}{A o que?}
{27509}{}{Ela e nossa lider, a piranha mais fodona da cidade!}
{27510}{}{Necro- o que? Isso e doente.}
{27511}{}{Você esta brincando, certo?}
{27512}{}{Esta é a Boneyard.}
{27513}{}{Eles atiram na gente à primeira vista.}
{27514}{}{Eles saem lá pra fora pra buscar coisas.}
{27515}{}{Você é idiota? O Boneyard é aqui; você está nele.}
{27516}{}{Nem ideia.}
{27517}{}{É duro lá fora.}
{27518}{}{Tem os Seguidores e os Gun Runners por aqui. Se você seguir pro sul, chega em Adytum.}
{27519}{}{O Boneyard é um lugar perigoso. É melhor tomar cuidado, amigo.}
{27520}{}{É, eu também estou com fome.}
{27521}{}{É melhor ficar longe de lá, é tudo o que sei.}
{27522}{}{Já ouvi boatos sobre eles. Se quer minha opinião, é tudo papo furado.}
{27523}{}{Não sei de nada.}
{27524}{}{É, aqui não.}
{27600}{}{Adytum}
{27601}{}{Os Seguidores}
{27602}{}{A Catedral}
{27603}{}{Os Rippers}
{27604}{}{Os Blades}
{27605}{}{Os Gun Runners}
{27606}{}{O Hub}
{27607}{}{Junktown}
{27608}{}{Chip da Agua}
{27609}{}{Razor}
{27610}{}{Necropolis}
{27611}{}{O Glow}
{27612}{}{A Boneyard}
{27613}{}{Regulators|Regulator|Police|Police Force|Reguladores|Policia}
{27614}{}{Scavs|Scav|Scavanger|Scavengers|Saqueadores|Catadores|Catador}
{27615}{}{Boneyard|LA|Los Angeles|Angels Boneyard}
{27616}{}{Medic|Doc|Doctor|Help|Healing|Hurt|Wounded|Injured|Medico|Doutor|Ajuda|Cura|Ferido|Machucado}
{27617}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Outside|Ermo|Terra Devastada|Devastada|La fora|Fora}
{27618}{}{Direction|Directions|Whereto|Where to|Direcao|Direcoes|Onde|Para onde|Caminho}
{27619}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev|Roubo|Ladrao|Ladroes|Furto|Criminosos}
{27620}{}{Brahmin|Brahmins|Brahma|Vaca}
{27621}{}{Cinema}
{27622}{}{Deathclaw}
{27623}{}{Rumor|Rumors|Rumour|Rumours|Boato|Boatos|Fofoca|Fofocas}
{27624}{}{Job|Work|Task|Money|Trabalho|Emprego|Tarefa|Servico|Dinheiro|Grana}
{27700}{}{Eles são uma vila de fracotes a sudoeste.}
{27701}{}{Pregadores da paz pateticos a oeste. Nós esmagariamos ele se nós não estivessemos
 ocupados enfrentando os Rippers.}
{27702}{}{Aberrações religiosas. Inofensivos e inuteis.}
{27703}{}{Nossos arqui-inimigos a oeste serao esmagados em breve!}
{27704}{}{Nós somos os Blades! Nunca se esqueça!}
{27705}{}{Eles eram uma gangue uma vez, mas eles amoleceram.  Apesar disso,
eles vendem boas armas.}
{27706}{}{Comerciantes e mercadores.}
{27707}{}{Eu ouvi sobre esse lugar, mas nada a respeito dele.}
{27708}{}{A o que?}
{27709}{}{Razor é a lutadora mais eximia de todos nos. Ela nos levera a
 vitoria.}
{27710}{}{Essa é uma estoria sobre uma cidade de canibais, usada para assutar as crianças.}
{27711}{}{Deve ser onde uma bomba atomica caiu.}
{27712}{}{Esta é a Boneyard.}
{27713}{}{Eles nos protegem das gangues e mantêm a paz.}
{27714}{}{Eles saem lá pra fora pra procurar coisas.}
{27715}{}{Você é idiota? O Boneyard é aqui; você está nele.}
{27716}{}{Tivemos um médico certa vez. Os Regulators o executaram por roubo.}
{27717}{}{Crescer no Boneyard é difícil. Se a falta de comida não te matar, as drogas ou as gangues provavelmente matam.}
{27718}{}{Adytum fica ao sul daqui. Se você seguir a estrada principal pro oeste e depois pro norte, vai achar os Seguidores.}
{27719}{}{O Boneyard é um lugar perigoso. É melhor tomar cuidado, amigo.}
{27720}{}{Se você estiver viajando com brahmin, as gangues certamente vão te marcar como alvo.}
{27721}{}{Esse é o antigo covil dos Rippers.}
{27722}{}{Ouvi dizer que há um ninho deles em algum lugar a leste daqui, mas eu mesmo nunca vi.}
{27723}{}{O povo fala muito.}
{27724}{}{se você está procurando trabalho, está no lugar errado.}
{27800}{}{Adytum}
{27801}{}{Os Seguidores}
{27802}{}{A Catedral}
{27803}{}{Os Rippers}
{27804}{}{Os Blades}
{27805}{}{Os Gun Runners}
{27806}{}{O Hub}
{27807}{}{Junktown}
{27808}{}{Chip da Agua}
{27809}{}{Razor}
{27810}{}{Necropolis}
{27811}{}{O Glow}
{27812}{}{A Boneyard}
{27813}{}{Regulators|Regulator|Police|Police Force|Reguladores|Policia}
{27814}{}{Scavs|Scav|Scavanger|Scavengers|Saqueadores|Catadores|Catador}
{27815}{}{Boneyard|LA|Los Angeles|Angels Boneyard}
{27816}{}{Medic|Doc|Doctor|Help|Healing|Hurt|Wounded|Injured|Medico|Doutor|Ajuda|Cura|Ferido|Machucado}
{27817}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Outside|Ermo|Terra Devastada|Devastada|La fora|Fora}
{27818}{}{Direction|Directions|Whereto|Where to|Direcao|Direcoes|Onde|Para onde|Caminho}
{27819}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev|Roubo|Ladrao|Ladroes|Furto|Criminosos}
{27820}{}{Brahmin|Brahmins|Brahma|Vaca}
{27821}{}{Cinema}
{27822}{}{Deathclaw}
{27823}{}{Rumor|Rumors|Rumour|Rumours|Boato|Boatos|Fofoca|Fofocas}
{27824}{}{Caleb}
{27825}{}{Job|Work|Task|Money|Trabalho|Emprego|Tarefa|Servico|Dinheiro|Grana}
{27900}{}{Não seja enganado. Adytum parece uma pequena vila mas seus Reguladores
 são fortes.}
{27901}{}{Hmph. Não comece. Eles não tem o estomago ou a coragem pra
 lutar.}
{27902}{}{Eles são cultuadores em uma grande igreja ao sul. Eles parecem inofensivos mas
 algo esquisito esta acontecendo lá.}
{27903}{}{Os Rippers are like mangy dogs - vicious, inbred e estupidos.}
{27904}{}{Ve minha lamina? Nós fazemos estas nos mesmo. Cada um de nos faz sua
 propria. Dai nosso nome.}
{27905}{}{Eles desceram do Hub procurando por turf, mas eles decidiram se
 tornar vendedores em vez de guerreiros.}
{27906}{}{Essa é uma cidade de comercio ao leste. Mercadores de lá vem aqui
 as vezes negociar com Adytum e com os Gun Runners.}
{27907}{}{Eu acho que é a nordeste daqui. É uma cidade pequena.}
{27908}{}{A o que?}
{27909}{}{Razor e nossa lider e campea. Eu não tenho duvida que a experiência dela
 nos garantira a vitoria finalmente sobre esses Rippers.}
{27910}{}{Bem longe a leste daqui. Supostamente, ghouls que comem carne humana vivem lá.
 Eu não queria enfrentar os ghouls.}
{27911}{}{Essa supostamente devem ser as ruinas de algum lugar que foi atingido
 direto por uma bomba atomica. Eu acho que é bem para o sul.}
{27912}{}{Esta é a Boneyard.}
{27913}{}{São a força policial de Adytum. Eles nos caçam e atiram à primeira vista. Aquele desgraçado do Caleb é o líder.}
{27914}{}{Os catadores têm a função de vasculhar o Boneyard atrás de equipamento valioso. São liderados por Sammael.}
{27915}{}{O Boneyard de Angel são as ruínas da velha cidade de Los Angeles. Estamos no meio do Boneyard.}
{27916}{}{Tivemos um médico certa vez. Os Regulators pegaram ele e o executaram por 'roubar suprimentos'... A verdade é que ele só não aceitou trabalhar exclusivamente pra eles.}
{27917}{}{Crescer no Boneyard é difícil. Se a falta de comida não te matar, as drogas ou as gangues provavelmente matam.}
{27918}{}{Adytum fica ao sul daqui. Tem os Seguidores a noroeste. Se você atravessar o velho Cinema a leste daqui, também tem os Gun Runners.}
{27919}{}{Tem muito crime no Boneyard, isso é fato. Sei que levamos a culpa por alguns, mas os Regulators são bem piores, se quer minha opinião.}
{27920}{}{As comitivas de comerciantes pagam bem por proteção por aqui, senão perdem seus brahmin rapidinho.}
{27921}{}{É onde os Rippers tinham o esconderijo antes de algo os expulsar.}
{27922}{}{Ouvi dizer que há um ninho deles em algum lugar a leste daqui, mas eu mesmo nunca vi.}
{27923}{}{Alguns dizem que a Deathclaw ocupou o velho Cinema.}
{27924}{}{O grande chefe dos Regulators. Normalmente não põe o pé pra fora de Adytum. Aposto que ele sabe que a gente tentaria dar o bote nele.}
{27925}{}{se você está procurando trabalho, está no lugar errado.}
{28600}{}{Adytum}
{28601}{}{Os Seguidores}
{28602}{}{A Catedral}
{28603}{}{Os Rippers}
{28604}{}{Os Blades}
{28605}{}{Os Gun Runners}
{28606}{}{O Hub}
{28607}{}{Junktown}
{28608}{}{Chip da Agua}
{28609}{}{A Boneyard}
{28610}{}{Buy|Buying|Sell|Selling|Barter|Trade|Trading|Business|Bartering|Comprar|Vender|Trocar|Negociar|Negocio|Comercio|Barganha}
{28611}{}{Medic|Doc|Doctor|Help|Healing|Hurt|Wounded|Injured|Medico|Doutor|Ajuda|Cura|Ferido|Machucado}
{28612}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Outside|Ermo|Terra Devastada|Devastada|La fora|Fora}
{28613}{}{Direction|Directions|Whereto|Where to|Direcao|Direcoes|Onde|Para onde|Caminho}
{28614}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev|Roubo|Ladrao|Ladroes|Furto|Criminosos}
{28615}{}{Brahmin|Brahmins|Brahma|Vaca}
{28616}{}{Cinema}
{28617}{}{Deathclaw}
{28618}{}{Rumor|Rumors|Rumour|Rumours|Boato|Boatos|Fofoca|Fofocas}
{28619}{}{Regulators|Regulator|Police|Police Force|Reguladores|Policia}
{28620}{}{Job|Work|Task|Money|Trabalho|Emprego|Tarefa|Servico|Dinheiro|Grana}
{28700}{}{Uma pequena vila ao sul daqui.}
{28701}{}{Um grupo de hippies ao sul.}
{28702}{}{Você quer dizer aqueles caras nos mantos marrons?}
{28703}{}{Gangue do hair-trigger gang a oeste.}
{28704}{}{Gangue furtiva a leste.}
{28705}{}{Sim? O que?}
{28706}{}{Nós compramos armas deles e vendemos elas direto pra você!}
{28707}{}{Sim, pequena cidade ao norte do Hub.}
{28708}{}{A o que?}
{28709}{}{Esta é a Boneyard.}
{28710}{}{O Zack, lá dentro do forte, cuida de todo o comércio.}
{28711}{}{Você está por conta própria.}
{28712}{}{Ao perambular pelas velhas ruínas, tente não se meter no meio de briga de gangue.}
{28713}{}{Não há muitos lugares pra onde ir daqui, né?}
{28714}{}{Estamos observando cada movimento seu.}
{28715}{}{Você viu algum por aqui?}
{28716}{}{É onde os Rippers tinham o esconderijo.}
{28717}{}{Criaturas terríveis. Grandes e cruéis, com garras afiadas.}
{28718}{}{Você acha que a gente ouve muitos boatos por aqui?}
{28719}{}{Uns mercenários contratados pra proteger Adytum das gangues.}
{28720}{}{Já falou com o Gabriel?}
{28800}{}{Adytum}
{28801}{}{Os Seguidores}
{28802}{}{A Catedral}
{28803}{}{Os Rippers}
{28804}{}{Os Blades}
{28805}{}{Os Gun Runners}
{28806}{}{O Hub}
{28807}{}{Junktown}
{28808}{}{Chip da Agua}
{28809}{}{A Boneyard}
{28810}{}{Buy|Buying|Sell|Selling|Barter|Trade|Trading|Business|Bartering|Comprar|Vender|Trocar|Negociar|Negocio|Comercio|Barganha}
{28811}{}{Medic|Doc|Doctor|Help|Healing|Hurt|Wounded|Injured|Medico|Doutor|Ajuda|Cura|Ferido|Machucado}
{28812}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Outside|Ermo|Terra Devastada|Devastada|La fora|Fora}
{28813}{}{Direction|Directions|Whereto|Where to|Direcao|Direcoes|Onde|Para onde|Caminho}
{28814}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev|Roubo|Ladrao|Ladroes|Furto|Criminosos}
{28815}{}{Brahmin|Brahmins|Brahma|Vaca}
{28816}{}{Cinema}
{28817}{}{Deathclaw}
{28818}{}{Rumor|Rumors|Rumour|Rumours|Boato|Boatos|Fofoca|Fofocas}
{28819}{}{Regulators|Regulator|Police|Police Force|Reguladores|Policia}
{28820}{}{Job|Work|Task|Money|Trabalho|Emprego|Tarefa|Servico|Dinheiro|Grana}
{28900}{}{Essa é uma pequena vila ao sul. Eles são muito bem fortificados.}
{28901}{}{Um grupo de amantes da paz se escondendo ao sul daqui. Nós deveriamos simplesmente
 nos livrar deles.}
{28902}{}{Ah sim, aqueles monges velhos loucos. Eles são doidos. A igreja grande deles
 esta ao sul da Boneyard.}
{28903}{}{Ei, eles podem ser estupidos, mas eles com certeza compram muitas armas!}
{28904}{}{Eles sempre usam aquelas vibro-facas esquisitas que eles fazem. Eu gostaria de
 por minhas mãos em uma. Mas pelo menos eles compram algumas armas tambem.}
{28905}{}{Você esta falando conosco.}
{28906}{}{É um grande centro de comercio pra tras no leste. Nós negociamos com os
 mercadores do Hub para comprar e vender armas e armaduras.}
{28907}{}{Uma pequena cidade ao norte do Hub. Bem estrita.}
{28908}{}{Nunca ouvi sobre isso.}
{28909}{}{Nós estamos no lado norte da Boneyard.}
{28910}{}{Fale com o Zack se quiser negociar.}
{28911}{}{Desculpe, não posso te ajudar.}
{28912}{}{Ao perambular pelas velhas ruínas, tente não se meter no meio de briga de gangue.}
{28913}{}{Não há muitos lugares pra onde ir daqui, né?}
{28914}{}{Estamos observando cada movimento seu.}
{28915}{}{Você viu algum por aqui?}
{28916}{}{É onde os Rippers tinham o esconderijo antes de a Deathclaw os expulsar.}
{28917}{}{Criaturas terríveis. Grandes e cruéis, com garras afiadas.}
{28918}{}{Você acha que a gente ouve muitos boatos por aqui?}
{28919}{}{Aqueles Regulators são uns desgraçados de coração frio e estão nos espremendo por tudo que temos. Nós fazemos as armas e eles ficam ricos com isso.}
{28920}{}{Você é bom numa briga?}
{29000}{}{Adytum}
{29001}{}{Os Seguidores}
{29002}{}{A Catedral}
{29003}{}{Os Rippers}
{29004}{}{Os Blades}
{29005}{}{Os Gun Runners}
{29006}{}{O Hub}
{29007}{}{Junktown}
{29008}{}{Chip da Agua}
{29009}{}{A Boneyard}
{29010}{}{Buy|Buying|Sell|Selling|Barter|Trade|Trading|Business|Bartering|Comprar|Vender|Trocar|Negociar|Negocio|Comercio|Barganha}
{29011}{}{Medic|Doc|Doctor|Help|Healing|Hurt|Wounded|Injured|Medico|Doutor|Ajuda|Cura|Ferido|Machucado}
{29012}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Outside|Ermo|Terra Devastada|Devastada|La fora|Fora}
{29013}{}{Direction|Directions|Whereto|Where to|Direcao|Direcoes|Onde|Para onde|Caminho}
{29014}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev|Roubo|Ladrao|Ladroes|Furto|Criminosos}
{29015}{}{Brahmin|Brahmins|Brahma|Vaca}
{29016}{}{Cinema}
{29017}{}{Deathclaw}
{29018}{}{Rumor|Rumors|Rumour|Rumours|Boato|Boatos|Fofoca|Fofocas}
{29019}{}{Regulators|Regulator|Police|Police Force|Reguladores|Policia}
{29020}{}{Job|Work|Task|Money|Trabalho|Emprego|Tarefa|Servico|Dinheiro|Grana}
{29100}{}{Eles são uma pequena cidade ao sul. Eles não negociam conosco. Eu
 não poderia me importar menos com eles.}
{29101}{}{Eles tentam converter todo mundo aos seus caminhos de paz enquanto eles se
 escondem na biblioteca deles ao sul. Eles não ajudam os negócios em nada!}
{29102}{}{A Catedral e esta grande igreja ao sul da Boneyard, onde algum
 culto estranho adora um Deus Sombrio. Eu acho que eles são aberrações.}
{29103}{}{Os Rippers são todos uma grande familia, literalmente. Eles são impossiveis de
 se lidar se eles não conhecem você, então nem mesmo tente. Eles esta em uma grande
 fortaleza booby-trapped a sudoeste de nos. Cuidado pelas minas terrestes se
 você e estúpido o bastante para visitar.}
{29104}{}{Eles converteram diversos pequenos predios ao sudoeste em seu
 lar. Eles são muito bem organizados e mais espertos do que os Rippers.
 Eles as vezes deixam forasteiros entrarem tambem. A lider deles, Razor, e uma
 mulher forte.}
{29105}{}{Esses somos nos. Bom dinheiro em vender armas para os Blades e os Rippers aqui.}
{29106}{}{Essa é a cidade do comercio a leste daqui onde nos obtemos nossas armas e fazemos
 comercio. Eles enviam caravanas para todos os lugares. Você poderia provavelmente
 viajar com uma caravana quando alguma se mostrar em Adytum.}
{29107}{}{É uma pequena cidade fronteirica bem ao norte do Hub. Há um grande
 cassino lá, mas o xerife da cidade e um pouco muito
 autoritario.}
{29108}{}{Eu não tenho ideia do que é isso.}
{29109}{}{Este e o lado norte da Boneyard. É engracado, pessoas do
 lado de fora a usam como uma maldicao - se algo esta ruim eles dizem 'Morde o
 Osso'. Mas ela não é muito ruim uma vez que você fique acostumado com ela.}
{29110}{}{Se você quer comprar ou vender, tenho certeza que a gente fecha negócio.}
{29111}{}{Desculpe, não posso te ajudar.}
{29112}{}{Ao perambular pelas velhas ruínas, tente não se meter no meio de briga de gangue.}
{29113}{}{Tem o velho Cinema a oeste daqui. Você deve conhecê-lo, porque é o único caminho pelo qual você poderia ter chegado até nós.}
{29114}{}{Estamos observando cada movimento seu.}
{29115}{}{Você nunca conseguiria passar um brahmin por aquelas Deathclaws.}
{29116}{}{É onde os Rippers tinham o esconderijo antes de a Deathclaw os expulsar.}
{29117}{}{Há um ninho daquelas malditas Deathclaws bem do lado de fora da nossa fábrica.}
{29118}{}{Você acha que a gente ouve muitos boatos por aqui?}
{29119}{}{Aqueles Regulators são uns desgraçados de coração frio e estão nos espremendo por tudo que temos. Nós fazemos as armas e eles ficam ricos com isso.}
{29120}{}{Fale com o Gabriel, ele pode ter um trabalho pra você.}
{500}{}{Apos destruir o Mestre e seu laboratorio no qual ele estava criando seu exercito de Super Mutantes, você
 retorna para o lar, só para descobrir que você e lancado fora da sua vault por ser muito destrutivo. Obrigado a você
 por jogar Fallout. }
{9400}{}{O Mestre}
{9401}{}{A Guerra}
{9402}{}{O Êxodo}
{9403}{}{O Exercito Estranho}
{9404}{}{A Irmandade}
{9405}{}{Os Mercadores}
{9406}{}{As Caravanas Desaparecidas}
{9407}{}{O Hub}
{9408}{}{Crianças da Catedral}
{9409}{}{Iniciados}
{9410}{}{Escribas}
{9411}{}{Cavaleiros}
{9412}{}{Paladinos}
{9413}{}{Chip da Agua}
{9500}{}{Eu não tenho ideia do que você esta falando.}
{9501}{}{Um ponto terrivelmente baixo na historia humana a qual formou nosso mundo presente. Nós preservamos o
 conhecimento da Guerra para impedir outro holocausto.}
{9502}{}{Uma decisao difícil e pesarosa. Nós perdemos muitas pessoas que escolheram ir embora por sua conta
 propria em vez de viajar com a força principal procurando por um abrigo seguro para viver.}
{9503}{}{Eu não sei muito sobre isso. Os relatorios que eu ouvi e que eles estão se juntando em algum lugar ao norte de nos.}
{9504}{}{Essa e aonde nos estamos.}
{9505}{}{Esses Mercadores das Aguas são bastardos roubadores, mas dos outros grupos, eu não tenho opiniao.}
{9506}{}{Eu não sei nada sobre isso.}
{9507}{}{Um poco de lodo para aqueles mercadores vis. Embora, ocasionalmente, nos deixamos uma das mais civis companhias
 de comercio negociar mercadorias conosco.}
{9508}{}{Eles são um culto.}
{9509}{}{Eles são o futuro da Irmandade.}
{9510}{}{Eles são os guardioes do conhecimento.}
{9511}{}{Eles são aqueles que fazem as armas para a Irmandade.}
{9512}{}{Eles são os protetores da Irmandade.}
{9513}{}{Eu não tenho ideia do que você esta falando.}
{10000}{}{O Mestre}
{10001}{}{A Guerra}
{10002}{}{O Êxodo}
{10003}{}{O Exercito Estranho}
{10004}{}{A Irmandade}
{10005}{}{Os Mercadores}
{10006}{}{As Caravanas Desaparecidas}
{10007}{}{O Hub}
{10008}{}{Crianças da Catedral}
{10009}{}{Iniciados}
{10010}{}{Escribas}
{10011}{}{Cavaleiros}
{10012}{}{Paladinos}
{10013}{}{Chip da Agua}
{10100}{}{Eu não tenho ideia do que você esta falando.}
{10101}{}{Um ponto terrivelmente baixo na historia humana a qual formou nosso mundo presente. Nós preservamos o
 conhecimento da Guerra para impedir outro holocausto.}
{10102}{}{Uma decisao difícil e pesarosa. Nós perdemos muitas pessoas que escolheram ir embora por sua conta
 propria em vez de viajar com a força principal procurando por um abrigo seguro para viver.}
{10103}{}{Eu não sei muito sobre isso. Os relatorios que eu ouvi e que eles estão se juntando em algum lugar ao norte de nos.}
{10104}{}{Essa e aonde nos estamos.}
{10105}{}{Esses Mercadores das Aguas são bastardos roubadores, mas dos outros grupos, eu não tenho opiniao.}
{10106}{}{Eu não sei nada sobre isso.}
{10107}{}{Um poco de lodo para aqueles mercadores vis. Embora, ocasionalmente, nos deixamos uma das mais civis companhias
 de comercio negociar mercadorias conosco.}
{10108}{}{Eles são um culto.}
{10109}{}{Eles são o futuro da Irmandade.}
{10110}{}{Eles são os guardioes do conhecimento.}
{10111}{}{Eles são aqueles que fazem as armas para a Irmandade.}
{10112}{}{Eles são os protetores da Irmandade.}
{10113}{}{Eu não tenho ideia do que você esta falando.}
{11800}{}{Chama Sagrada}
{11801}{}{A Unidade}
{11802}{}{Crianças da Catedral}
{11803}{}{Morpheus}
{11804}{}{Mutantes}
{11805}{}{Mestre}
{11806}{}{Seguidores do Apocalipse}
{11807}{}{Base Militar}
{11808}{}{Os Vats}
{11809}{}{Chip da Agua}
{11900}{}{A Chama Sagrada e aquela que nos levera para um bravo novo mundo
 o qual não tem odio ou guerra.}
{11901}{}{Nós somos todos parte da Unidade. É o amor e paz que nos passamos
 para o nosso povo camarada - humano e mutante.}
{11902}{}{Isso somos nos.}
{11903}{}{Morpheus e o Sumo Sacerdote das Crianças.
 Tipicamente, ele esta nas suas salas quando ele não esta pregando para nos.}
{11904}{}{Eles são pessoas que foram transformadas pela poeira radioativa.
 Mas eles ainda são boas pessoas.}
{11905}{}{Nós todos temos mestres, não temos?}
{11906}{}{Eles são pessoas que procuram destruir a paz a qual o Mestre esta
 tentando por adiante.}
{11907}{}{Lamento, nunca ouvi sobre isso.}
{11908}{}{Lamento, eu não sei do que você esta falando.}
{11909}{}{Eu não tenho pista do que você esta falando.}
{19600}{}{Mestre}
{19601}{}{Tenente}
{19602}{}{Crianças da Catedral}
{19603}{}{Seguidores do Apocalipse}
{19604}{}{Nightkin}
{19605}{}{Super Mutantes}
{19606}{}{Mediuns}
{19607}{}{Experimentos}
{19608}{}{Chip da Agua}
{19700}{}{Eu não tenho que dizer nada a você.}
{19701}{}{Tal conhecimento não pertence a seres inferiores.}
{19702}{}{Você não precisa se preocupar com eles.}
{19703}{}{Você e muito inferior para me questionar.}
{19704}{}{Não e da sua conta.}
{19705}{}{Isto não te diz respeito.}
{19706}{}{Você e muito tolo para saber deles.}
{19707}{}{Você não esta autorizado a saber deles.}
{19708}{}{Não me aborreca a respeito de brinquedos.}
{20200}{}{Mestre}
{20201}{}{Tenente}
{20202}{}{Crianças da Catedral}
{20203}{}{Seguidores do Apocalipse}
{20204}{}{Nightkin}
{20205}{}{Super Mutantes}
{20206}{}{Mediuns}
{20207}{}{Experimentos}
{20208}{}{Chip da Agua}
{20300}{}{Eu não tenho que dizer nada a você.}
{20301}{}{Tal conhecimento não pertence a seres inferiores.}
{20302}{}{Você não precisa se preocupar com eles.}
{20303}{}{Você e muito inferior para me questionar.}
{20304}{}{Não e da sua conta.}
{20305}{}{Isto não te diz respeito.}
{20306}{}{Você e muito tolo para saber deles.}
{20307}{}{Você não esta autorizado a saber deles.}
{20308}{}{Não me aborreca a respeito de brinquedos.}
{20800}{}{Mestre}
{20801}{}{Tenente}
{20802}{}{Crianças da Catedral}
{20803}{}{Seguidores do Apocalipse}
{20804}{}{Nightkin}
{20805}{}{Super Mutantes}
{20806}{}{Mediuns}
{20807}{}{Experimentos}
{20808}{}{Chip da Agua}
{20900}{}{Eu não tenho que dizer nada a você.}
{20901}{}{Tal conhecimento não pertence a seres inferiores.}
{20902}{}{Você não precisa se preocupar com eles.}
{20903}{}{Você e muito inferior para me questionar.}
{20904}{}{Não e da sua conta.}
{20905}{}{Isto não te diz respeito.}
{20906}{}{Você e muito tolo para saber deles.}
{20907}{}{Você não esta autorizado a saber deles.}
{20908}{}{Não me aborreca a respeito de brinquedos.}
{21400}{}{Mestre}
{21401}{}{Tenente}
{21402}{}{Crianças da Catedral}
{21403}{}{Seguidores do Apocalipse}
{21404}{}{Nightkin}
{21405}{}{Super Mutantes}
{21406}{}{Mediuns}
{21407}{}{Experimentos}
{21408}{}{Chip da Agua}
{21500}{}{Eu não tenho que dizer nada a você.}
{21501}{}{Tal conhecimento não pertence a seres inferiores.}
{21502}{}{Você não precisa se preocupar com eles.}
{21503}{}{Você e muito inferior para me questionar.}
{21504}{}{Não e da sua conta.}
{21505}{}{Isto não te diz respeito.}
{21506}{}{Você e muito tolo para saber deles.}
{21507}{}{Você não esta autorizado a saber deles.}
{21508}{}{Não me aborreca a respeito de brinquedos.}
