{100}{}{FEITO}
{101}{}{OPções}
{102}{}{FECHAR}
{103}{}{IMPRIMIR}
{104}{}{IDADE}
{105}{}{SEXO}
{106}{}{NOME}
{107}{}{HOMEM}
{108}{}{MULHER}
{109}{}{BENEFICIOS}
{110}{}{KARMA}
{111}{}{MORTES}
{112}{}{PTS DE TECNICA}
{113}{}{Nível:}
{114}{}{Exp:}
{115}{}{Prox. Nível:}
{116}{}{PTS DO PERS.}
{117}{}{TECNICAS}
{118}{}{Você deve usar todos os pontos de personagem}
{119}{}{antes de começar o jogo!}
{120}{}{Pontos do Personagem}
{121}{}{Quantia de pontos do personagem livres que podem ser adicionados a uma das estat. basicas.}
{122}{}{Proximo Nível}
{123}{}{A quantia de pontos de experiência necessarios pra promover pro próximo nível.}
{124}{}{Beneficios}
{125}{}{Karma}
{126}{}{- Mortes}
{127}{}{Beneficios adicionam habilidades adicionais. A cada terceiro nível de exp, você pode escolher um benefício.}
{128}{}{Estes são os efeitos das escolhas que você faz durante o jogo.}
{129}{}{Um contador que mantem rastro dos tipos e números das criaturas que você matou ou viu serem mortas na sua presença.}
{130}{}{Pontos das Tecnicas}
{131}{}{Use pontos de técnicas livres para aumentar o nível de uma técnica.}
{132}{}{No nível maximo.}
{133}{}{Incapaz de incrementar.}
{134}{}{No nível minimo.}
{135}{}{Incapaz de decrementar.}
{136}{}{Não há pontos de técnica livres disponiveis.}
{137}{}{Base:}
{138}{}{TEC DE IDEN}
{139}{}{TRACOS OPCIONAIS}
{140}{}{Você já tem o maximo de}
{141}{}{tres técnicas de identificaçao!}
{142}{}{Você deve selecionar todas as técnicas de identificaçao}
{143}{}{antes de iniciar o jogo!}
{144}{}{Tecnicas de Identificaçao}
{145}{}{Tecnicas de Ident. são técnicas nas quais seu/sua personagem se especializa. Cada técnica de ident. ganha +20% e aumenta 2x mais rapido. Você deve escolher 3 técnicas de ident.}
{146}{}{Traços Opcionais}
{147}{}{Traços opcionais descrevem seu/sua personagem em mais detalhes. Todos os traços terao efeitos positivos e negativos. Você pode escolher até 2 traços durante a criaçao.}
{148}{}{Você já tem o maximo de}
{149}{}{dois traços!}
{150}{}{Tecnicas}
{151}{}{Tecnicas são conhecimento aprendido. Tecnicas aumentam com a experiência ou durante o curso do jogo atraves de eventos especiais. Mais alto o nível da técnica, melhor você e nessa técnica.}
{152}{}{ESCOLHA UM BENEFÍCIO}
{153}{}{ESCOLHA UM NOVO TRACO}
{154}{}{PERDER UM TRACO}
{155}{}{ESCOLHA UMA NOVA TECNICA DE IDENTIFICACÃO}
{156}{}{TRACOS}
{157}{}{Todas as estat. devem estar entre 1 e 10}
{158}{}{antes de começar o jogo!}
{160}{}{Aviso: você não mudou o nome do seu}
{161}{}{personagem. Usar este personagem mesmo assim?}
{175}{}{Próx. Nível:}
{200}{}{M.Ruim}
{201}{}{Ruim}
{202}{}{Pobre}
{203}{}{Justo}
{204}{}{Médio}
{205}{}{Bom}
{206}{}{M.Bom}
{207}{}{Ótimo}
{208}{}{Excelente}
{209}{}{Heroico}
{300}{}{Pts de Vida}
{301}{}{Pts de Ação }
{302}{}{Classe de Arm.}
{303}{}{Desarmado}
{304}{}{Corpo-a-Corpo}
{305}{}{Res ao Dano }
{306}{}{Res a Veneno   }
{307}{}{Res a Radiação}
{308}{}{Sequencia}
{309}{}{Taxa de Cura}
{310}{}{Chance Critica}
{311}{}{Carregar Peso}
{312}{}{Envenenado}
{313}{}{Irradiado}
{314}{}{Dano no Olho}
{315}{}{Braço Dir Mutilado}
{316}{}{Braço Esq Mutilado}
{317}{}{Perna Dir Mutilada}
{318}{}{Perna Esq Mutilada}
{400}{}{Seu/Sua personagem foi envenenado. O veneno fara dano por um periodo de tempo até que seja curado ou ele passe do seu sistema.}
{401}{}{Seu/Sua personagem esta sofrendo de uma quantia significante de envenenamento por radiação. Maior o dano por radiação, mais mortal o efeito.}
{402}{}{Isto significa que seu/sua personagem foi seriamente atingido em um ou ambos dos seus olhos. Isto afeta sua Percepção.}
{403}{}{O braço dir foi severamente ferido e não consegue funcionar bem. Se um braço foi incapacitado, você não pode usar armas de duas mãos. Se ambos os braços foram incapacitados, você não consegue atacar com armas.}
{404}{}{O braço esq do seu/sua pers. foi severamente ferido e não consegue funcionar bem. Se um braço foi incapacitado, você não pode usar armas de 2 mãos. Se ambos os braços foram incapacitados, você não consegue atacar com armas.}
{405}{}{Seu/Sua personagem tem uma perna direita incapacitada.}
{406}{}{Seu/Sua personagem tem uma perna esquerda incapacitada.}
{500}{}{Janeiro}
{501}{}{Fevereiro}
{502}{}{Março}
{503}{}{Abril}
{504}{}{Maio}
{505}{}{Junho}
{506}{}{Julho}
{507}{}{Agosto}
{508}{}{Setembro}
{509}{}{Outubro}
{510}{}{Novembro}
{511}{}{Dezembro}
{600}{}{SALVAR}
{601}{}{CARREGAR}
{602}{}{IMPRIMIR}
{603}{}{APAGAR}
{604}{}{FEITO}
{605}{}{Você tem certeza que você quer apagar}
{606}{}{o personagem atual?}
{607}{}{ foi salvo com sucesso.}
{608}{}{ foi carregado com sucesso.}
{609}{}{já existe.}
{610}{}{Você deseja sobrescrever?}
{611}{}{Erro ao salvar }
{612}{}{Erro ao carregar }
{613}{}{Arquivo do personagem invalido.}
{614}{}{Dados do personagem invalidos.}
{615}{}{Erro ao ler a lista de arquivos!}
{616}{}{IMPRIMIR}
{617}{}{JOGADOR}
{618}{}{BLANK.GCD}
{620}{}{FALLOUT}
{621}{}{REGISTRO DO PESSOAL DO VAULT-13}
{622}{}{horas}
{623}{}{ ::: Estatísticas :::}
{624}{}{       Força:}
{625}{}{        Pts de Dano:}
{626}{}{        Sequencia:}
{627}{}{     Percepção:}
{628}{}{       Classe de Arm.:}
{629}{}{        Taxa de Cura:}
{630}{}{      Resistência:}
{631}{}{     Pts de Ação:}
{632}{}{      Chance Critico:}
{633}{}{       Carisma:}
{634}{}{      Dano Corpo-a-Corpo:}
{635}{}{         Carregar Peso:}
{636}{}{   Inteligencia:}
{637}{}{       Res ao Dano:}
{638}{}{        Agilidade:}
{639}{}{    Res a Radiação:}
{640}{}{           Sorte:}
{641}{}{       Res a Veneno:}
{642}{}{  Nome:}
{643}{}{Idade:}
{644}{}{               Gênero:}
{645}{}{Homem}
{646}{}{Mulher}
{647}{}{ Nível:}
{648}{}{                Exp:}
{649}{}{Prox. Nível:}
{650}{}{ ::: Traços :::           ::: Benefícios :::           ::: Karma :::}
{651}{}{ ::: Tecnicas :::                ::: Mortes :::}
{652}{}{ ::: Inventario :::}
{653}{}{                                      Peso Total:}
{654}{}{ ::: Inventário :::}
{655}{}{                                      Peso Total:}
{656}{}{ ::: Vícios :::}
{657}{}{ ::: Reputação :::}
{1000}{}{Reputaço (Geral) }
{1001}{}{Frenético}
{1002}{}{Campeão}
{1003}{}{Assassino de Crianças}
{1004}{}{Vicio em Nuka Cola}
{1005}{}{Vicio em Buffout}
{1006}{}{Vicio em Mentats}
{1007}{}{Vicio em Psycho}
{1008}{}{Vicio em RadAway}
{1009}{}{Vicio em Álcool}
{1010}{}{Vício em Jet}
{1011}{}{Vício em Tragic}
{1012}{}{THIS GOES WITH THE TEMPORARY ONE FOR DESCRIPTIONS #1112: DON'T TRANSLATE THIS}
{1013}{}{Perito em Sexo}
{1014}{}{Campeão de Boxe}
{1015}{}{Gigolô}
{1016}{}{Coveiro}
{1017}{}{Homem de Confiança: Salvatore}
{1018}{}{Casado}
{1019}{}{Astro Pornô}
{1020}{}{Escravagista}
{1021}{}{Virgem do Ermo}
{1022}{}{Homem de Confiança: Bishop}
{1023}{}{Homem de Confiança: Mordino}
{1024}{}{Homem de Confiança: Wright}
{1025}{}{Separado}
{1100}{}{Esta é uma estat. que representa sua reputação geral. Mais alto o número, melhor conhecido e respeitado você é. Se sua rep. é negativa, você é odiado por alguns por suas ações mas.}
{1101}{}{Você matou um grande número de pessoas. Isto não é geralmente uma coisa boa para ficar conhecido. Pessoas do lado errado da trilha contudo gostarão um pouco mais de você.}
{1102}{}{Suas ações revelaram que você ser um campeão das pessoas. Sua guerra contra o mal e vilania é amplamente conhecida. Pessoas honráveis respeitarão mais você.}
{1103}{}{Você matou crianças, a juventude da terra devastada. Isto é considerado ser uma coisa realmente ruim. Sua pessoa má, má.}
{1104}{}{Você aprecia totalmente a Nuka-Cola, o pop do mundo pós-nuclear.}
{1105}{}{Você está viciado no chem Buffout. Você deve tomar este chem numa base diária ou sofrer os efeitos da retirada.}
{1106}{}{Você esta sofrendo do vicio em Mentats. Você deve tomar este chem particular ou sofrer com a retirada.}
{1107}{}{Você tem um vicio em chems. Se você não tomar Psycho numa agenda regular, você sofrerá, Se você o fizer, outros sofrerão.}
{1108}{}{Seu corpo se tornou viciado em Radaway. Enquanto não ameaça a vida, você deve toma-lo regularmente.}
{1109}{}{Você tem um problema com álcool. Realmente, você tem muitos problemas com o seu hábito de beber.}
{1110}{}{TEMPORÁRIO - O que é isto?}
{1111}{}{Tragicamente, você é viciado no Colecionismo. Está constantemente em busca de novas expansões.}
{1112}{}{TEMPORARY - What is this?}
{1113}{}{Você entende de sexo. Entende de preliminares. Sabe como agradar alguém do sexo oposto e deixá-lo com vontade de mais.}
{1114}{}{Você é o campeão dos pesos-pesados do Norte da Califórnia. Ganhou fama, respeito, o amor de milhares... e um bônus na sua robustez e perícia desarmado.}
{1115}{}{Sejamos honestos: você dorme com qualquer coisa que ande sobre duas pernas. Às vezes, você nem é tão exigente assim.}
{1116}{}{"Estão mortos, não se importam" virou seu lema. Desenterrar os restos dos outros é mais que um hobby para você.}
{1117}{}{Você é um "Homem de Confiança" da Família Salvatore. É bem conhecido, bem respeitado e fica ótimo de fedora.}
{1118}{}{Você se amarrou. Ei, o problema é seu, não nosso.}
{1119}{}{Você é uma estrela grande, brilhante e reluzente. Suas façanhas sexuais são bem conhecidas por toda Nova Reno.}
{1120}{}{Você foi marcado como membro da Guilda dos Escravagistas. A tatuagem na sua testa deixa sua profissão evidente para todos que você encontra.}
{1121}{}{Você realmente precisa sair mais. Suas façanhas sexuais têm sido... bem, bidimensionais.}
{1122}{}{Você é um "Homem de Confiança" da Família Bishop. É bem conhecido, bem respeitado e fica ótimo de fedora.}
{1123}{}{Você é um "Homem de Confiança" da Família Mordino. É bem conhecido, bem respeitado e fica ótimo de fedora.}
{1124}{}{Você é um "Homem de Confiança" da Família Wright. É bem conhecido, bem respeitado e fica ótimo de fedora.}
{1125}{}{Seu cônjuge não está mais com você. Espero que esteja feliz.}
{2000}{}{Idolatrado}
{2001}{}{Estimado}
{2002}{}{Aceito}
{2003}{}{Neutro}
{2004}{}{Antipatia}
{2005}{}{Odiado}
{2006}{}{Difamado}
{2100}{}{Todos nesta área gostariam de ser você. Você é a sensação da cidade e é apontado como um exemplo reluzente de tudo o que uma pessoa pode ser.}
{2101}{}{As pessoas acenam e te cumprimentam por onde você passa nesta área. Todos já ouviram falar de você, e gostam do que ouviram.}
{2102}{}{Embora você não seja recebido de braços abertos, a maioria das pessoas desta área ao menos acena em reconhecimento quando se encontram. Você se encaixa tão bem quanto a maioria.}
{2103}{}{Normalmente desconfiadas de estranhos, as pessoas desta área ainda não formaram uma opinião sobre você.}
{2104}{}{Você é só mais um forasteiro nesta área. Provavelmente tramando algo.}
{2105}{}{Você provou às pessoas desta área que a desconfiança inicial delas tinha fundamento. As pessoas desta área te olham e cochicham entre si quando você se aproxima. Elas sabem que você está tramando algo.}
{2106}{}{Encarando e cochichando, alguns atravessam a rua para não passar perto de você, enquanto outros cospem e se viram quando você se aproxima. Todos sabem que você é uma das piores coisas que já rastejou para dentro desta área.}
{3000}{}{Salvador dos Condenados}
{3001}{}{Guardião do Ermo}
{3002}{}{Escudo da Esperança}
{3003}{}{Defensor}
{3004}{}{Andarilho}
{3005}{}{Traidor}
{3006}{}{Espada do Desespero}
{3007}{}{Flagelo do Ermo}
{3008}{}{Cria do Demônio}
{4000}{}{Reputação}
{4001}{}{Vícios}
{4100}{}{Representa sua reputação em um local específico.}
{4101}{}{Coisas com as quais você ficou viciado.}
{5000}{}{Lamento, você só pode imprimir seu/sua}
{5001}{}{personagem na versão completa.}
{5002}{}{Lamento, você só pode salvar seu/sua}
{5003}{}{personagem na versão completa.}
{5004}{}{Lamento, você só pode carregar um}
{5005}{}{personagem salva na versão completa.}
{5006}{}{MODO TRAPAÇA}
{5007}{}{Não disponível no demo.}
{000}{}{      Força: 00        Pts de Dano: 000/000          Sequencia: 00}
