{0}{}{Você tem certeza que deseja sair?}
{1}{}{Versão de demonstração}
{2}{}{Personagem padrão será usado.}
{3}{}{Captura de tela salva.}
{4}{}{"Quick load" carregado com sucesso.}
{5}{}{"Quick save" salvo com sucesso.}
{6}{}{Tempo limite da demonstração excedido.}
{7}{}{Pipboy não está disponível em combate!}
{8}{}{Erro ao salvar captura de tela.}
{9}{}{Introdução}
{10}{}{Novo Jogo}
{11}{}{Carregar Jogo}
{12}{}{Créditos}
{13}{}{Sair}
{14}{}{Copyright(c) 1997 Interplay Productions. All rights reserved.}
{15}{}{Pontos de Ação}
{16}{}{Pontos de Vida}
{17}{}{A opção de sensor de movimento não está instalada.}
{18}{}{O sensor de movimento não tem recargas restantes.}
{20}{}{Copyright(c) 1997 Interplay Productions.  All rights reserved.}
{30}{}{Deseja continuar jogando?}
{100}{}{Erro ao salvar arquivo de configuração do jogo!}
{101}{}{Configurações de jogo não foram salvas.}
{1000}{}{Você se sente muito enjoado.}
{1001}{}{Você se sente muito enjoado, e após vomitar levemente, fica ligeiramente cansado.}
{1002}{}{Você está muito cansado, o vômito não para, e o seu tempo de recuperação é prejudicado.}
{1003}{}{Você está tendo uma hemorragia violenta. Você está muito doente, e seu cabelo está caindo.}
{1004}{}{Você está tendo uma hemorragia violenta e contínua. O vômito está manchado de vermelho por causa do seu sangue. Sua pele está caindo dos seus ossos.}
{1005}{}{Há sangramento em seus intestinos e você está com diarreia grave. Você se sente inchado e em intensa agonia.}
{1006}{}{Você morreu de doença de radiação.}
{1007}{}{Você recebeu uma grande dose de radiação.}
{1008}{}{O contador Geiger está clicando.}
{1009}{}{O contador Geiger está clicando descontroladamente.}
{2000}{}{Você não consegue chegar lá.}
{2001}{}{A fechadura está emperrada.}
{3000}{}{Você foi envenenado!}
{3001}{}{Você sofre dano do veneno.}
{3002}{}{Você se sente um pouco melhor.}
{3003}{}{Você se sente melhor.}
{4000}{}{Devido ao seu manuseio inepto, o explosivo detona prematuramente.}
{5000}{}{usa}
{5001}{}{está sem munição para}
{5002}{}{recarrega}
{6000}{}{Perguntar sobre o quê?}
{7000}{}{Você não está usando o Pip-Boy!}
{8000}{}{Você está sobrecarregado.}
{8001}{}{%s está sobrecarregado.}
{8500}{}{Você ganha %d pontos de experiência pelo uso bem-sucedido da perícia Homem ao Ar Livre.}
{9000}{}{%s melhorou em algumas habilidades.}
{9010}{}{Está tudo voltando pra mim agora...}
{9011}{}{Quer saber? Acho que estou aprendendo uma coisa ou outra.}
{9012}{}{Estou ficando bem bom nisso.}
{9013}{}{Viu? Toda coisa boa melhora com o tempo.}
{9020}{}{Au!}
{9021}{}{Au!}
{9022}{}{Au!}
{9023}{}{Au! Au!}
{9030}{}{Tenho certeza de que isso é um bom sinal.}
{9031}{}{Rá. Acho que cão velho aprende truque novo sim.}
{9032}{}{Parece que toda essa viagem valeu a pena.}
{9033}{}{Aprendi alguns truques novos.}
{9040}{}{Ah cara... eu realmente aprendi algo com isso.}
{9041}{}{Ainda há tanto que podemos aprender.}
{9042}{}{Acho que finalmente estou pegando o jeito disso.}
{9043}{}{Não acredito que sobrevivi até aqui.}
{9050}{}{ANÁLISE DE DADOS COMPLETA. ATUALIZANDO TODOS OS SISTEMAS.}
{9051}{}{NOVOS DADOS COLETADOS. APRIMORANDO SISTEMAS DE MIRA.}
{9052}{}{READAPTAÇÃO DE SISTEMA CONCLUÍDA.}
{9053}{}{DESEMPENHO ÓTIMO ATINGIDO.}
{9060}{}{}
