[sfall]
;Table for overriding ASCII codes for keyboard character input when entering the player's name and saved game descriptions
;Only character codes in the ASCII range 33-126 can be overridden
;Character codes that do not need to be overridden can be omitted by using commas as delimiters
;You must also set a key for switching layouts using the XltKey option in ddraw.ini
;Default character code table for the English layout (letter codes only)
;XltTable=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,,,,,,,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,,,,

;##############################################################################

SaveInCombat=Não é possível salvar neste momento.
KarmaGain=Você ganhou %d de reputação.
KarmaLoss=Você perdeu %d de reputação.
HighlightFail1=Você não está carregando um sensor de movimento.
HighlightFail2=Seu sensor de movimento está sem carga.
SuperStimExploitMsg=Você não pode usar um super stim em alguém que não está ferido!
BlockedCombat=Você não pode entrar em combate neste momento.
SaveSfallDataFail=ERRO ao salvar as informações estendidas do jogo salvo! Verifique se outros programas estão interferindo nos arquivos/pastas de jogos salvos e tente novamente.
PartyLvlMsg=Nv:
PartyACMsg=CA:
PartyAddictMsg=Viciado
NPCPickupFail=%s não consegue pegar o item.
AmmoInfoGlovz=Div: RD/%d, LD/%d
AmmoInfoYAAM=Mod. LD: %d

PartyOrderAttackHuman=Pode deixar comigo.|Ok, entendido.|Parece um bom plano.
PartyOrderAttackCreature=::Rosnado::
PartyOrderAttackRobot=::Bipe::

HiResInfo=Esta versão do sfall tem seu próprio modo integrado de High Resolution Patch, que é compatível com as configurações do High Resolution Patch feito por Mash.\n\nSe você quiser continuar usando o Hi-Res Patch do Mash sem ver esta mensagem, desative a opção 'HiResMode' no ddraw.ini.\nOu você pode desativar o Hi-Res Patch externo para obter as novas melhorias gráficas do sfall.\n\nVocê quer desativar o High Resolution Patch feito por Mash?

[AppearanceMod]
RaceText=Raça
StyleText=Estilo
DoneBtn=Feito

;Custom names for player's unarmed attacks (max 16 characters)
[Unarmed]
;Punch=Punch:
;Kick=Kick:
;StrongPunch=Strong Punch:
;HammerPunch=Hammer Punch:
;Haymaker=Haymaker:
;Jab=Jab:
;PalmStrike=Palm Strike:
;StrongKick=Strong Kick:
;SnapKick=Snap Kick:
;PowerKick=Power Kick:
;HipKick=Hip Kick:
;HookKick=Hook Kick:
;PiercingKick=Piercing Kick: