{100}{}{Você vê: Tratador de Centauro}
{101}{}{Você vê um tratador de centauro Super Mutante.}
{200}{}{Fetch!}
{210}{}{Vem cá, cachorrinho.}
{211}{}{Você é um bom garoto!}
{212}{}{Bom garoto!}
{213}{}{Sim, sim, você é.}
{220}{}{Onde ocê tá, cachorrinho?}
{221}{}{Hã? Onde ocê foi?}
{222}{}{Doggie?}
{223}{}{Hã, cachorrinho?}
{224}{}{Cachorrinho, cachorrinho, cachorrinho..?}
{230}{}{Uhhhh...}
{231}{}{Ocê procurano cachorrinho?}
{232}{}{Lou orgulho, sim.}
{233}{}{Ocê ir embora! Num tem motivo pra aqui.}
{240}{}{Lou orgulho, eu pegá intrusão!}
