{100}{}{Obrigado a você.}
{101}{}{Tchau.}
{102}{}{Ola.}
{103}{}{Você ganha }
{104}{}{ pontos de experiência.}
{105}{}{Uh oh!}
{106}{}{Clique!}
{107}{}{Opps!}
{108}{}{Ouch!}
{109}{}{Vejo você por ai.}
{110}{}{Take it sleazy.}
{111}{}{Foi divertido.}
{112}{}{Aqui vai você.}
{113}{}{Algo mais?}
{114}{}{Sim.}
{115}{}{Não.}
{116}{}{Você ganha }
{117}{}{ pontos de técnica em Armas Pequenas.}
{118}{}{ pontos de técnica em Armas Grandes.}
{119}{}{ pontos de técnica em Armas de Energia.}
{120}{}{ pontos de técnica em Combate Desarmado.}
{121}{}{ pontos de técnica em Armas de Combate Corpo-a-Corpo.}
{122}{}{ pontos de técnica em Arremesso.}
{123}{}{ pontos de técnica em Primeiros Socorros.}
{124}{}{ pontos de técnica em Doutor.}
{125}{}{ pontos de técnica em Furtivo.}
{126}{}{ pontos de técnica em Roubar.}
{127}{}{ pontos de técnica em Gazua.}
{128}{}{ pontos de técnica em Armadilhas.}
{129}{}{ pontos de técnica em Ciencia.}
{130}{}{ pontos de técnica em Reparo.}
{131}{}{ pontos de técnica em Discurso.}
{132}{}{ pontos de técnica em Permutacao.}
{133}{}{ pontos de técnica em Jogo.}
{134}{}{ pontos de técnica em Homem ao Ar Livre.}
{135}{}{Você ganha um ponto de técnica em Armas Pequenas.}
{136}{}{Você ganha um ponto de técnica em Armas Grandes.}
{137}{}{Você ganha um ponto de técnica em Armas de Energia.}
{138}{}{Você ganha um ponto de técnica em Combate Desarmado.}
{139}{}{Você ganha um ponto de técnica em Melee Weapons.}
{140}{}{Você ganha um ponto de técnica em Arremesso.}
{141}{}{Você ganha um ponto de técnica em Primeiros Socorros.}
{142}{}{Você ganha um ponto de técnica em Doutor.}
{143}{}{Você ganha um ponto de técnica em Sneak.}
{144}{}{Você ganha um ponto de técnica em Roubar.}
{145}{}{Você ganha um ponto de técnica em Gazua.}
{146}{}{Você ganha um ponto de técnica em Armadilhas.}
{147}{}{Você ganha um ponto de técnica em Ciencia.}
{148}{}{Você ganha um ponto de técnica em Reparo.}
{149}{}{Você ganha um ponto de técnica em Discurso.}
{150}{}{Você ganha um ponto de técnica em Permutacao.}
{151}{}{Você ganha um ponto de técnica em Jogatina.}
{152}{}{Você ganha um ponto de técnica em Outdoorsman.}
{153}{}{Sua Força e aumentada em }
{154}{}{Sua Percepcao e aumentada em }
{155}{}{Sua Resistência e aumentada em }
{156}{}{Sua Carisma e aumentada em }
{157}{}{Sua Inteligencia e aumentada em }
{158}{}{Sua Agilidade e aumentada em }
{159}{}{Sua Sorte e aumentada em }
{160}{}{pontos.}
{161}{}{Sua Força e aumentada por um ponto.}
{162}{}{Sua Percepcao e aumentada por um ponto.}
{163}{}{Sua Resistência e aumentada por um ponto.}
{164}{}{Sua Carisma e aumentada por um ponto.}
{165}{}{Sua Inteligencia e aumentada por um ponto.}
{166}{}{Sua Agilidade e aumentada por um ponto.}
{167}{}{Sua Sorte e aumentada por um ponto.}
{168}{}{Obrigado pela sua ajuda.}
{169}{}{Obrigado por nada.}
{170}{}{Aradesh esta furioso e se recusa a falar mais com você.}
{171}{}{Eu acredito que o Master deseja falar com você.}
{172}{}{Você pagara pela sua BLASFÊMIA!}
{173}{}{Este robo parece estar inoperavel. Isto e possivelmente devido a falta de força.}
{174}{}{Você não vê nada especial neste robo.}
{175}{}{Este Blade se recusa a falar com você.}
{176}{}{A mala esta selada e não abre.}
{177}{}{Por favor, nos devemos nos apressar. Nós não temos tempo para falar.}
{178}{}{So o Morpheus tem a chave pra esta porta. Eu devo sair agora pra deixar
 a Nicole saber o que esta acontecendo aqui.}
{179}{}{Por favor, eu tenho que sair daqui antes que eles descubram quem eu sou.}
{180}{}{Você falha em roubar qualquer coisa e imagina se você foi pego.}
{181}{}{Os membros da Brotherhood pegaram você roubando.}
{186}{}{Você ouve o alto-falante alto: Aviso! Alerta de Intruso.}
{187}{}{A gosma retardou a transmissao dos seus keystrokes.}
{200}{}{Você um campo emissor horrivelmente danificado.}
{201}{}{O emissor esta muito danificado para usar.}
{202}{}{O emissor esta muito danificado para reparar.}
{203}{}{Você nota que o campo esta danificado o bastante para caminhar atraves dele.}
{190}{}{ ativa o Stealth Boy.}
{300}{}{Seu Dano Corpo-a-Corpo é aumentado em 1 ponto.}
{301}{}{% de Resistência a Dano.}
{305}{}{Dehydrated}
{306}{}{Os efeitos da desidratação passaram.}
{214}{}{O veneno saiu do seu organismo.}
{400}{}{A explosão enfraquece muito este campo de energia. Agora deve ser inofensivo atravessá-lo.}
{500}{}{A porta zomba de você, desafiadora, resistindo à explosão, recebendo apenas amassados e marcas de queimadura.}
{501}{}{A porta se preocupa com sua capacidade de aguentar mais castigo, enquanto range e se curva com a explosão.}
{502}{}{A porta geme em agonia enquanto é arrancada das dobradiças, caindo ao chão com um estrondo poderoso.}
{503}{}{Você ganha }
{504}{}{ de experiência pelo uso bem-sucedido de explosivos.}
{505}{}{A explosão não chega a destruir a porta. Você vai precisar de mais uma.}
{601}{}{Você não deveria estar aqui, Iniciado.}
{602}{}{O que você esta fazendo aqui?}
{603}{}{Por favor saia. Você não deveria estar aqui.}
{604}{}{Ei, Iniciados não.}
{605}{}{Desculpe, eu não deveria estar falando com ninguém. Você sabe como é.}
{606}{}{Esta não é a biblioteca, meu rapaz. Se você quer explorar,
 vá para a biblioteca.}
{607}{}{Esta não é a biblioteca, minha garota. Se você quer explorar,
 please vá para a biblioteca.}
{700}{}{ experience!}
{701}{}{ de experiência por destruir os Tanques.}
{702}{}{ de experiência por destruir o Mestre.}
{182}{}{Vamos detonar!}
{183}{}{Parece que você poderia usar um pouco de assistencia.}
{184}{}{Eu ajudarei a ti.}
{185}{}{Eu não falo muito.}
{188}{}{Os radscorpions estão agora selados na caverna deles.}
{189}{}{A boca da caverna beckons você mais fundo no covil dos radscorpions.}
