{100}{}{CARREGAR O JOGO}
{101}{}{ESCOLHA UM SLOT}
{102}{}{SALVAR O JOGO}
{103}{}{ESCOLHA UM SLOT}
{104}{}{FEITO}
{105}{}{FECHAR}
{106}{}{Erro ao carregar a lista de jogos salvos!}
{107}{}{Diretorio dos jogos salvos:}
{108}{}{Não existe ou esta corrompido.}
{109}{}{SALVAR O JOGO}
{110}{}{CARREGAR O JOGO}
{111}{}{- VAZIO -}
{112}{}{- ARQUIVO CORROMPIDO -}
{113}{}{- VERSAO ANTIGA -}
{114}{}{Vazio.}
{115}{}{Erro!}
{116}{}{Versão antiga.}
{117}{}{JAN}
{118}{}{FEV}
{119}{}{MAR}
{120}{}{ABR}
{121}{}{MAI}
{122}{}{JUN}
{123}{}{JUL}
{124}{}{AGO}
{125}{}{SET}
{126}{}{OUT}
{127}{}{NOV}
{128}{}{DEZ}
{129}{}{Nível}
{130}{}{DESCRICAO}
{131}{}{Ja existe um jogo salvo, sobrescrever?}
{132}{}{Erro ao salvar o jogo!}
{133}{}{Incapaz de salvar o jogo.}
{134}{}{Erro ao carregar o jogo!}
{135}{}{Incapaz de carregar o jogo.}
{136}{}{O arquivo do jogo salvo esta em uma versão mais antiga.}
{137}{}{Mapa}
{140}{}{Jogo Salvo.}
{141}{}{Jogo Carregado.}
{200}{}{Lamento, você não pode salvar ou carregar}
{201}{}{na versão demo.}
