{100}{}{Você enfureceu o Larry.}
{101}{}{Você vê o Larry.}
{102}{}{Se você perturbar o chefe ele vai bater em você.}
{103}{}{Humanos não são permitidos em Necropolis. Você vem comigo.}
{104}{}{Mas . . .}
{105}{}{Nunca!}
{106}{}{Hngh!!}
{107}{}{Morra humano!}
{108}{}{O mutante ignora você.}
{1000}{}{Agua}
{1001}{}{Necropolis}
{1002}{}{Set}
{1003}{}{Bacia Hidrografica}
{1004}{}{Hall}
{1005}{}{Lou}
{1006}{}{Ghouls}
{1007}{}{Normais}
{1100}{}{Eu não sei.}
{1101}{}{Você de pe nela.}
{1102}{}{Ele é uma bicha. Nós deveriamos simplesmente erradicar ele e seus ghouls.}
{1103}{}{É aqui.}
{1104}{}{Eu não sei.}
{1105}{}{Ele é chefe do Harry.}
{1106}{}{Coisas covardes.}
{1107}{}{Mais coverde que os ghouls.}
