{100}{}{Você vê o lider da caravana.}
{101}{}{Bem, aqui nos estamos. Aqui esta o seu pagamento de }
{102}{}{ tampinhas. [Ele puxa pra fora um saco de dinheiro com forma de orelha de cachorro e da a você o dinheiro.] Você tera as outras }
{103}{}{ tampinhas se você retornar conosco pro Hub. Nós descansaremos aqui por um tempo, mas não vá muito longe ou a caravana saira sem você.}
{104}{}{Aaa... OK.}
{105}{}{Quanto tempo antes que a caravana saia?}
{106}{}{O que você pode me dizer sobre Junktown?}
{107}{}{O que você pode me dizer sobre a Boneyard?}
{108}{}{O que você pode me dizer sobre a Brotherhood of Steel?}
{109}{}{Eu não sei se você entendera isto, mas nos saimos em duas horas ou assim que você estiver pronto.}
{110}{}{Um...}
{111}{}{Hã?}
{112}{}{Vai. Bom.}
{113}{}{Cara, nos estamos contratando burros estes dias.}
{114}{}{Nós geralmente saimos duas horas apos a chegada. Não há nada aqui que nós não tenhamos
 visto antes, então se você quiser sair mais cedo nos estamos prontos assim que você estiver.}
{115}{}{Eu acho que eu darei uma olhada antes de nos irmos. Vejo você mais tarde.}
{116}{}{OK. Vamos voltar pro Hub. Nada que eu queira ver aqui tambem.}
{117}{}{O que você pode me dizer sobre Junktown?}
{118}{}{O que você pode me dizer sobre a Boneyard?}
{119}{}{O que você pode me dizer sobre a Brotherhood of Steel?}
{120}{}{Bem, e parecida um pouco com o Hub, mesmo. Ela tem sua cota de problemas: gangues, facinoras,
 ladroes, você sabe... as coisas de sempre. De tudo por tudo, e meu tipo de cidade. [Risadas]}
{121}{}{Quanto tempo antes que a caravana saia?}
{122}{}{Eu acho que eu darei uma olhada antes de nos irmos. Vejo você mais tarde.}
{123}{}{Esta parte da Boneyard e chamada Adytum. A Boneyard e basicamente comandada por gangues. Tipo de area ruim, então cuidado aonde pisa aqui. Adytum e comandada pelos Regulators. Eles estão tentando manter este lugar unido a despeito de todas as guerras de gangues. Eles são compreensivelmente suspeitos de estranhos, então se você não falou com eles ainda eu sugiro a você que o faca antes de começar a vaguear por ai.}
{124}{}{Vazio}
{125}{}{Quanto tempo antes que a caravana saia?}
{126}{}{Eu acho que eu darei uma olhada antes de nos irmos. Vejo você mais tarde.}
{127}{}{Não há muito que eu possa dizer a você sobre eles. A Brotherhood se mantem para eles mesmos na maior parte. Muitas pessoas dão a eles uma reputação ruim, mas do que eu posso dizer eles são boas pessoas. Um pouco fanaticos, talvez, mas caras bons.}
{128}{}{Quanto tempo antes que a caravana saia?}
{129}{}{Eu acho que eu darei uma olhada antes de nos irmos. Vejo você mais tarde.}
{130}{}{Você esta pronto pra ir?}
{131}{}{Vai!}
{132}{}{Não. Eu ainda estou dando uma olhada por aqui.}
{133}{}{Sim. Nós podemos ir.}
{134}{}{Esta parte da Boneyard e chamada Adytum. A Boneyard e basicamente comandada por gangues. Tipo de area ruim, então cuidado aonde pisa aqui.}
{135}{}{Quanto tempo antes que a caravana saia?}
{136}{}{Eu acho que eu darei uma olhada antes de nos irmos. Vejo você mais tarde.}
{137}{}{OK. Você conseguiu. Aqui estão suas }
{138}{}{ tampinhas. Se você quer mais trabalho, então vai falar com o chefe de novo. Eu ficaria mais do que feliz em trabalhar com você de novo. Eu falarei bem de você pro chefe. Vai com calma.}
{139}{}{Tchau Tchau.}
{140}{}{Vejo você em breve.}
{141}{}{Ei, como esta indo?}
{142}{}{Se você quer mais trabalho, vai verificar com o chefe.}
{143}{}{Há algo errado com você?}
{144}{}{Vocè e um tremendo psicopata!}
{145}{}{Eu não trabalho com você!}
{146}{}{200}
{147}{}{400}
{148}{}{600}
{149}{}{O que você pode me dizer sobre Necropolis?}
{150}{}{Lugar anormal e imundo, cara!}
{151}{}{A caravana saiu.}
{200}{}{Hmmmpf...}
{201}{}{Hmm... Eu gostaria de saber ler.}
{300}{}{Meta-se com o que é da sua conta?}
{400}{}{Eu não sou pago para falar.}
{501}{}{Apenas me diga, por que você abandonou aquela maldita caravana? Eu não posso acreditar! Sorte a sua, eles terminaram sem seu traseiro lamentavel! Saia! Eu não devo pagar nada a você!}
{502}{}{Eu não posso acreditar! Nós perdemos todas as caravanas! Saia! Eu não devo pagar nada a você!}
{504}{}{Apenas vá até o chefe and tente pensar em alguma estoria creditavel sobre porque você abandonou aquela maldita caravana. Pode ser então que você conseguira seu pagamento.}
{505}{}{Eu não posso acreditar! Nós perdemos todas as malditas caravanas! Eu não acho que eu deva pagar nada a você. Vá falar com o chefe.}
{600}{}{Bom, aqui estamos. Não posso te pagar a tarifa normal, já que perdemos parte da caravana. Temos que cobrir nossos prejuízos, sabe. Aqui está seu pagamento de }
{601}{}{ tampinhas. [Ele puxa pra fora um saco de dinheiro com forma de orelha de cachorro e da a você o dinheiro.] Você tera as outras }
{602}{}{Se você quiser mais trabalho, é só falar com o chefe. Eu trabalharia com você de novo, tranquilo. Vá com calma.}
{603}{}{ tampinhas. (Ele tira uma velha bolsa surrada e te dá as tampinhas) }
{604}{}{Certo, você conseguiu. Não posso te pagar nada, já que perdemos a caravana inteira. Temos que cobrir nossos prejuízos, sabe. Queria que fosse diferente, mas são as regras.}
{605}{}{Certo, você conseguiu. Não posso te pagar nada, já que todos os brahmin morreram. Você nos custou muito dinheiro, amigão. Sem brahmin, sem caravana, sem dinheiro. Espero que não deixem você trabalhar com a gente de novo.}
{506}{}{Algum trabalho pra mim aqui?}
{507}{}{Eu querê trabalho!}
{508}{}{Precisamos de músculos pra descarregar a caravana. Vou te pagar }
{509}{}{ caps.}
{510}{}{Ug!}
{511}{}{Nop.}
{512}{}{Deixa comigo.}
{513}{}{Não gosto disso.}
{520}{}{Você passou uma hora descarregando a caravana.}
{521}{}{Você ajuda a terminar de descarregar a caravana e lhe são dados }
{522}{}{ caps.}
