{100}{}{Você acha que couro puny salvara você do Baka?}
{101}{}{Você não é páreo pra gente!}
{102}{}{Se eu fosse feio assim eu me mataria.}
{103}{}{Vocês Crypts não têm chance.}
{104}{}{Você gosta de dor?}
{105}{}{Vou curtir isto.}
{106}{}{Você vai morrer, escória!}
{107}{}{Hora do acerto de contas.}
{108}{}{Você está pronto pra um pouco de dor?}
{109}{}{A única coisa mais estúpida que você é o Rayze.}
{110}{}{Acho que restos de parto podem viver um tempinho.}
{111}{}{Os Crypts serão enterrados mais uma vez!}
{112}{}{Pereça, escória!}
{113}{}{Quem disse que vocês podiam sair das suas covas? Voltem!}
{114}{}{Seus modos reles serão erradicados da face da terra!}
{115}{}{Só os Tolos têm o verdadeiro conhecimento pra governar Scrapheap.}
{116}{}{Suma, gosma de tripa de galinha de três pernas!}
{117}{}{O que aconteceu com você? Sua mãe te deixou cair de cabeça ao nascer?}
{118}{}{}
{119}{}{}
{120}{}{}
{200}{}{Correr, Tolo, enquanto você ainda tem a chance de viver.}
{201}{}{Hey, Rayze, a temporada de caça acabou de ser aberta, e Fools estão na lista de animais burros.}
{202}{}{Ei pessoal, deixe um tolo para eu matar.}
{203}{}{Os Crypts vão te enterrar!}
{204}{}{Tolos não têm razão pra viver.}
{205}{}{Os Tolos vão perecer.}
{206}{}{Olha quem foi atingido pela vara da feiura.}
{207}{}{Você vai ser enterrado, Tolo!}
{208}{}{Vou chutar uns traseiros pra valer! Estou pronto pra guerraaaa!}
{209}{}{Crypts mandam! E Tolos babam!}
{210}{}{Nós somos os portadores da morte!}
{211}{}{Não se preocupe, vai ser rápido e doloroso!}
{212}{}{BABUÍNOS ROXOS!}
{213}{}{Os Brahmin têm mais juízo que um Tolo.}
{214}{}{Os Tolos são tão fracos que até o Lex consegue surrar todos eles.}
{215}{}{Haha! Mais tolos pra matar!!}
{216}{}{A única coisa que vocês Tolos vão governar é uma lápide.}
{217}{}{Já era hora. Estava esperando por isto.}
{218}{}{Até o Lenny tem melhor pontaria que você.}
{219}{}{Comam chumbo, tolos.}
{220}{}{Vou montar sua cabeça numa estaca.}
{300}{}{Ei! O gerador quebrou. Vamos sair desta espelunca.}
{400}{}{Com o gerador quebrado, há pouco motivo pras gangues brigarem por Scrapheap. Seu trabalho aqui está concluído, mas sua missão de encontrar o chip de purificação de água continua.}
{402}{}{Com as gangues derrotadas, Scrapheap é um refúgio seguro mais uma vez.}
{403}{}{Obrigado, tchau.}
{404}{}{Certo, obrigado.}
{405}{}{Hmm. Tchau.}
{406}{}{Falou.}
{407}{}{Obrigado.}
{408}{}{Certo, tchau.}
{409}{}{[mais]}
