{100}{}{Você vê Zack Barstow, um Iniciado dos Filhos da Catedral.}
{101}{}{Bem-vindo aos Filhos da Catedral. Como posso te ajudar hoje?}
{102}{}{Urrrooo?}
{103}{}{Qual é o sentido do universo?}
{104}{}{Estou bem machucado. Acha que pode me ajudar?}
{105}{}{Como se conserta a bomba d'água?}
{106}{}{Você pode me contar algo sobre este lugar?}
{107}{}{Sou inadequado pra isso. Talvez, se você falar com a Laura, ela esteja disposta a te dar a informação que você precisa saber.}
{108}{}{Ah, consertar bombas d'água é fácil. É só uma flag.}
{109}{}{Não tenho as ferramentas pra te ajudar com esse problema. Por favor, fale com um dos meus superiores.}
{110}{}{Ah, isso. Isso é só uma flag.}
{111}{}{Por favor, consulte a Laura. Já te disse tudo o que sei.}
