{100}{}{Isto parece estranho. Parece que pode ser usado no seu Pip Boy.}
{101}{}{Pip Boy exibe: Arquivo Achado no Sistema. Abortando download.}
{102}{}{Pip Boy exibe: Baixando dados do disco.}
{103}{}{Este disco está em mau estado. Não tem um rótulo próprio, mas tem "sobrepor" arranhado na lateral.}
{104}{}{Você vê: Disco de Sobreposição de Segurança.}
{105}{}{Usuário: "admin". Senha: "muerte". Protocolo de sobreposição de segurança: Gama Ômicron Delta.}
{106}{}{**BEGIN-DISK**}
{107}{}{**END-DISK**}
{108}{}{[Continuar]}
{109}{}{O Pip-Boy 2000 exibe: 'Usuário: "admin". Senha: "muerte". Sobreposição de segurança: Gama Ômicron Delta.'}
