{100}{}{Você vê: Olho Flutuante.}
{150}{}{O robô está desligado.}
{151}{}{unused}
{152}{}{A bateria embutida está morta e precisa ser trocada, mas você não descobre como.}
{153}{}{Parece que o robô está ligado ao sistema de energia do Glow. Ele não consegue operar fora dali.}
{154}{}{Você não faz ideia do que há de errado com o robô.}
{155}{}{Os movimentos do robô estão frenéticos demais. Você não consegue inspecioná-lo.}
{156}{}{Parece que os sensores dele estão com defeito.}
{157}{}{unused}
{158}{}{Parece que o robô está ligado ao sistema de energia do Glow. Ele não consegue operar fora dali.}
{159}{}{ de experiência por consertar com sucesso os sensores do robô.}
{160}{}{Você não consegue consertar os sensores do robô.}
{161}{}{Você reconecta um monte de cabos. Agora talvez seja possível usar uma Célula de Energia Pequena ou de Microfusão como bateria substituta.}
{162}{}{ de experiência por substituir a bateria embutida por uma célula de Microfusão improvisada.}
{163}{}{O robô talvez não seja tão eficaz quanto era 100 anos atrás, mas funciona.}
{164}{}{Você não faz ideia do que está fazendo aqui e destrói o robô no processo.}
{165}{}{Você não conseguiu improvisar uma bateria.}
{166}{}{ de experiência por substituir a bateria embutida por uma célula de energia pequena modificada.}
{200}{}{[Clique] ERRO DE SISTEMA. [Bip] Unidade incapaz de processar a última tarefa ativa. O gerenciador de tarefas não responde. Ordens?}
{201}{}{Você me entende?}
{202}{}{Módulo de voz online. Sistema nominal. Ordens?}
{203}{}{Qual foi sua última tarefa?}
{204}{}{Acessando fila de tarefas... Última tarefa: Segurança de perímetro. Tarefa cancelada após sofrer graves flutuações de energia. Sobrecarga de bateria. Componentes de hardware danificados.}
{205}{}{Qual é o seu status?}
{206}{}{Status de manutenção: OK... Status da bateria: RUIM... Conexão com a rede local: BOA... Sistemas de armas: ONLINE.}
{207}{}{Você consegue me seguir?}
{208}{}{Nova tarefa: NEGATIVO. Fila de tarefas cheia. Ordens?}
{209}{}{Apague a memória.}
{210}{}{Processando. Por favor, aguarde... [Bip]}
{211}{}{Reiniciando sistema. Por favor, aguarde... [Bip]}
{212}{}{[Clique] SISTEMA ONLINE... CARGA DE MEMÓRIA 39%... Todos os sistemas nominais. Ordens?}
{213}{}{Siga-me.}
{214}{}{Uhh... Talvez eu devesse só te dar uns tapinhas?}
{215}{}{ERRO. [Bip] Reiniciando sistema. Por favor, aguarde.}
{216}{}{(Você bate no robô, mas nada de bom acontece)}
{217}{}{Bom, pelo menos eu tentei.}
{900}{}{O Olho Flutuante não pode ser mais reparado no momento.}
{901}{}{O Olho Flutuante foi reparado um pouco.}
{902}{}{O Olho Flutuante está todo consertado agora.}
{1000}{}{Inicializar parâmetros. Todos os sistemas online. Ordens?}
{1001}{}{}
{1014}{}{Você deveria fazer manutenção em si mesmo agora.}
{1015}{}{Precisamos conversar sobre o que você pode fazer.}
{1020}{}{Vamos falar sobre nossa formação.}
{1030}{}{Certo, obrigado.}
{1040}{}{Siga-me, preciso da sua ajuda de novo.}
{1050}{}{[Pronto]}
{1060}{}{Deixa pra lá.}
{1004}{}{Processando ordens...}
{1005}{}{Calibrando novos parâmetros.}
{1006}{}{Calibrando...}
{1007}{}{Tasks?}
{1008}{}{Tasks?}
{1009}{}{Confirmado.}
{1010}{}{[Clique] Esta unidade está programada pra seguir um protocolo automatizado de segurança de perímetro e/ou de VIP. Esta unidade também tem um sistema embutido de scanner de longo alcance pra detecção precoce de ameaças.}
{1011}{}{[Bip] Esta unidade é equipada com um sistema de teiser Wattz 2.4 aprimorado pra engajamentos corpo-a-corpo rápidos.}
{1100}{}{Este eyebot está totalmente reparado e pronto pra ação.}
{1200}{}{Status de manutenção: Bom. Nenhum reparo necessário.}
{1300}{}{Status de manutenção: Danificado. Sugerindo reparos adicionais em breve.}
{1400}{}{Status de manutenção: Ruim. Sugerindo reparos adicionais em breve.}
{1401}{}{Status da bateria: OK.}
{1402}{}{Status da bateria: BOM.}
{1500}{}{É melhor a gente ficar junto.}
{1501}{}{Confirmado. Em espera.}
{1600}{}{Confirmado.}
{1700}{}{Modo de formação de curto alcance confirmado.}
{1800}{}{Modo de formação de médio alcance confirmado.}
{1900}{}{Modo de formação de longo alcance confirmado.}
{2000}{}{Falha ao processar tarefa. ERRO: Sobrecarga sensorial. Tamanho do grupo excede os parâmetros. Permanecendo em espera.}
{2001}{}{Tarefa confirmada. Cancelar espera.}
{2002}{}{Carregando... Tarefa recursiva criada... Encerrando entrada.}
{2010}{}{Ah é, tanto faz então.}
{3500}{}{Status de manutenção: Danificado. Reparos adicionais necessários.}
