{100}{}{O que você quer?}
{101}{}{Me deixe em paz}
{102}{}{O quê?}
{103}{}{Não mexa com minhas coisas.}
{104}{}{Oi.}
{105}{}{Arrrr!}
{106}{}{Grrrrr!}
{107}{}{Uungh.}
{108}{}{Uhh.}
{109}{}{Ei, você ouviu que Set foi desativado?}
{110}{}{Conjunto está morto. Set está morto. Set está morto. . .}
{111}{}{Há água suficiente para todos.
 Set garante isso.}
{112}{}{Eu ouvi dizer que os mutantes foram expulsos da cidade.}
{113}{}{Desde que os mutantes saíram, tem sido melhor.}
{114}{}{Olá.}
{200}{}{Você examina a coisa lamentável, mas não consegue descobrir o que pode
 fizeram do jeito que é.}
{201}{}{Parece ter sido humano uma vez, ou pelo menos descendente de
 humanos. Você adivinha que a dissuasão no corpo é mais provável
 a ácido ou radiação.}
{202}{}{O corpo do humanóide parece ser altamente irradiado, mas ainda assim
 funcionamento. Enquanto era uma vez humano, parece ter voltado a um
 estilo de vida mais animalesco}
{203}{}{O corpo do humanóide parece ser altamente irradiado, e muito
 do músculo e da matéria cerebral parecem ter se deteriorado. No entanto, genética
 indicadores levam você a acreditar que ele descendeu, como você, daqueles
 que entrou nos cofres.}
{204}{}{Esta coisa lastimável está altamente irradiada. Você não consegue determinar se ela enlouqueceu por ficar enjaulada ou se simplesmente perdeu massa cerebral demais por dano de radiação.}
{205}{}{O corpo do humanoide parece altamente irradiado, porém manteve massa cerebral e função motora suficientes pra conseguir falar com clareza.}
{300}{}{Você foi irradiado!}
{301}{}{Você recebe uma dose moderada de radiação.}
{302}{}{Você recebe uma grande dose de radiação.}
{303}{}{Você foi levemente irradiado.}
{304}{}{Você foi irradiado.}
{305}{}{Você foi moderadamente irradiado.}
{306}{}{Você foi fortemente irradiado.}
{1004}{}{Você recebeu uma dose leve de radiação.}
{1005}{}{Você recebeu uma pequena dose de radiação.}
{1006}{}{Você recebeu uma dose moderada de radiação.}
{1007}{}{Você recebeu uma grande dose de radiação.}
