{100}{}{Você vê: Griffith.}
{101}{}{O ghoul veste uma jaqueta de motociclista velha e remendada. Você vê vestígios de tatuagens na pele apodrecida dele.}
{125}{}{Você ganha }
{128}{}{ de experiência por obter a motocicleta.}
{160}{}{Você é um maldito LADRÃO!}
{161}{}{Mas que? Cadê minha..?!}
{200}{}{O Griffith parece não voltar. Talvez você devesse tentar encontrá-lo?}
{201}{}{Ele está demorando mesmo...}
{202}{}{Ugh... que teeeédio.}
{500}{}{Tira as mãos da minha moto, pele-lisa!}
{501}{}{Eu mandei você ficar longe!}
{510}{}{Me obriga!}
{520}{}{Ah, tá.}
{1000}{}{Ei, pele-lisa, tá olhando o quê?}
{1001}{}{Você ainda por aqui, pele-lisa?}
{1002}{}{Mudou de ideia, pele-lisa?}
{1010}{}{Quem é você?}
{1020}{}{O que você está fazendo aqui?}
{1030}{}{Essa moto é sua?}
{1031}{}{Pode me contar de novo sobre a sua moto?}
{1040}{}{Beleza, eu vigio sua moto.}
{1050}{}{Uhh... Qem ocê?}
{1100}{}{Me chamam de Griffith.}
{1110}{}{O que você está fazendo aqui, Griffith?}
{1120}{}{Ótimo. Até mais, Griffith!}
{1200}{}{O que parece que eu estou fazendo?}
{1210}{}{Não sei. Está esperando alguém?}
{1300}{}{Exatamente! E sabe de uma coisa? Parece que achei quem eu estava esperando!}
{1310}{}{É mesmo?}
{1400}{}{Tem uma coisa que eu preciso fazer. Vai me levar umas horas, e não posso deixar minha moto aqui sozinha.}
{1410}{}{Você quer que eu vigie sua moto?}
{1420}{}{Então o que você quer que eu faça?}
{1500}{}{Os outros ghouls por aqui, eles não estão nem aí e eu não posso confiar neles.}
{1501}{}{Você, por outro lado, dá pra ver que *se importaria*! Além disso, eu te pago se tudo estiver no lugar quando eu voltar.}
{1510}{}{Qual é o pagamento?}
{1520}{}{Acho que dá pra fazer isso.}
{1600}{}{Um saco de tampinhas? Não é um trabalho difícil. Só leva um tempo, é só isso.}
{1610}{}{Acho que dá pra fazer isso.}
{1620}{}{Desculpe, mas não tenho tempo pra isso. Até mais.}
{1700}{}{Ótimo! Volto em algumas horas.}
{1710}{}{[Você vê o ghoul desaparecer nos esgotos]}
{1800}{}{Pele-lisa, você é burro? Preciso de alguém pra vigiar minha moto!}
{1810}{}{Ei, não me chame de burro!}
{1820}{}{Oh.}
{1900}{}{É a minha moto, isso mesmo.}
{1910}{}{Pode me contar mais sobre ela?}
{1920}{}{Parece um Chryslus Motors Cruiser original. Já vi desses em filmes holográficos antigos!}
{2000}{}{Você está olhando pra um Chryslus Motors Cruiser original, fabricado em... Hã... Na verdade, não sei quando foi fabricado, mas é pré-guerra! Ótima tecnologia. Mantenho ele funcionando há anos.}
{2010}{}{Você a vende?}
{2100}{}{Eu... o quê? Está de sacanagem comigo, pele-lisa? Eu nunca venderia minha moto!}
{2200}{}{Bom, merda. Você é tão inútil quanto todo mundo por aqui.}
{2300}{}{Isso mesmo, pele-lisa! Uma das melhores máquinas que a humanidade já fez!}
{2400}{}{Parece que você sabe mais sobre essas motos pré-guerra do que eu.}
{3000}{}{Santo brahmin, você é burro pra caramba, não é?}
{3010}{}{Uh...}
{3100}{}{Vou te dizer uma coisa, pele-lisa... Tem uma coisa que eu preciso fazer. Ei! Você está ouvindo?}
{3101}{}{Se você fizer o que eu digo, eu te dou uma bela grana, entendeu? Olha, um monte de tampinhas de garrafa! Você gosta de tampinhas, não gosta?}
{3110}{}{Eu gostá!}
{3120}{}{Nah.}
{3200}{}{Você o quê? Você não gosta de tampinhas, pele-lisa? Droga, você deve ser bem lerdo mesmo.}
{3210}{}{Eu ir.}
{3220}{}{Uh, eu gostá de tampinha!}
{3300}{}{Ótimo, ótimo! Agora escuta. Tenho que ir embora um pouco. Entendeu? *Eu* vou. *Você* fica aqui. Não deixa ninguém tocar na minha moto, tá? Bom. Não vai demorar muito, só espera aqui.}
{3310}{}{[Você vê o ghoul desaparecer nos esgotos]}
