{100}{}{Você desativa a fechadura com sucesso.}
{101}{}{Você não consegue desativar a fechadura.}
{102}{}{Você tranca o objeto com sucesso.}
{103}{}{Você não consegue trancar o objeto.}
{200}{}{ desativa a fechadura com sucesso.}
{201}{}{ não consegue desativar a fechadura.}
{202}{}{ tranca o objeto com sucesso.}
{203}{}{ não consegue trancar o objeto.}
{300}{}{A explosão destrói a fechadura do objeto.}
{301}{}{A explosão não consegue remover a fechadura do objeto.}
{400}{}{Você força a fechadura do objeto e a abre com sucesso.}
{401}{}{Você não consegue forçar a fechadura do objeto pra abrir.}
{500}{}{ força a fechadura do objeto e a abre com sucesso.}
{501}{}{ não consegue forçar a fechadura do objeto pra abrir.}
