{100}{}{Você vê o Dogmeat.}
{101}{}{Arf! Arf Arf! Arf! Arf! Arf! Arf! Arf! Arf!}
{102}{}{[Sniff. Sniff.] Grrrr! Snarl!}
{103}{}{[Sniff. Sniff] Woof!}
{110}{}{Você vê: Dogmeat.}
{117}{}{Woof-woof!}
{118}{}{Ruff. Ruff.}
{119}{}{Woof!}
{120}{}{Woof?}
{200}{}{Acho que a gente tem que falar sobre nossa distância.}
{201}{}{Na verdade, você está numa boa distância por enquanto.}
{2500}{}{Grrrrr.}
{2510}{}{O que foi? Você não gosta de tanta companhia, hein?}
{2511}{}{[Pronto]}
{3500}{}{*Wimper*}
{3501}{}{Awooooooooooo! *wimper*}
{3502}{}{}
