{100}{}{Isto parece estranho. Você acha que pode ser o que a Irmandade
 enviou para você recuperar.}
{101}{}{Pip Boy exibe: Arquivo Achado no Sistema. Abortando download.}
{102}{}{Pip Boy exibe: Baixando os dados do Disco.}
{103}{}{Você vê um disco que Sophia deu a você.}
{104}{}{Você vê um disco que Maxson deu a você.}
{107}{}{Você vê um Disco do Local da Vault.}
{125}{}{Você vê um disco estranho da Base Militar.}
{127}{}{Este holodisco em particular está em excelente estado. O rótulo brilhante diz: "Localizações de Vault v34.129".}
{105}{}{Você vê um disco estranho da Base Militar.}
{106}{}{Você vê um holodisco estranho.}
