{100}{}{Você vê um disco com alguma marcacao estranha nele.}
{101}{}{PIPBoy exibe: Informacao já armazenada.}
{102}{}{PIPBoy exibe: Baixando dados.}
{103}{}{Este holodisco parece ter sido usado pra gravar dados de áudio de um relé de rádio militar.}
{104}{}{Você vê: Disco de Transmissões de Rádio dos Super Mutantes.}
{105}{}{Ele tem umas marcas estranhas e manchas que você acha que podem ser sangue.}
