{100}{}{Você vê um membro dos Blades.}
{101}{}{Oi.}
{102}{}{Olá.}
{103}{}{Tenha um bom dia.}
{104}{}{Tempo bom o que nos estamos tendo hoje.}
{105}{}{Eu imagino se chovera.}
{106}{}{Você já viu a chuva brilhar?}
{107}{}{Tenho que voltar ao trabalho.}
{108}{}{Não recebemos muitos forasteiros aqui.}
{109}{}{Tenho que ir.}
{110}{}{Falou.}
{111}{}{Bom dia.}
{112}{}{Obrigado pela sua ajuda.}
{113}{}{Nós não esqueceremos você.}
{114}{}{Bacana ter você do nosso lado.}
{115}{}{As coisas vao ficar melhores agora.}
