{0}{}{DESERT1.MAP}
{1}{}{DESERT2.MAP}
{2}{}{DESERT3.MAP}
{3}{}{HALLDED.MAP}
{4}{}{HOTEL.MAP}
{5}{}{WATRSHD.MAP}
{6}{}{VAULT13.MAP}
{7}{}{VAULTENT.MAP}
{8}{}{VAULTBUR.MAP}
{9}{}{VAULTNEC.MAP}
{10}{}{JUNKENT.MAP}
{11}{}{JUNKCSNO.MAP}
{12}{}{JUNKKILL.MAP}
{13}{}{BROHDENT.MAP}
{14}{}{BROHD12.MAP}
{15}{}{BROHD34.MAP}
{16}{}{CAVES.MAP}
{17}{}{CHILDRN1.MAP}
{18}{}{CHILDRN2.MAP}
{19}{}{CITY1.MAP}
{20}{}{COAST1.MAP}
{21}{}{COAST2.MAP}
{22}{}{COLATRUK.MAP}
{23}{}{FSAUSER.MAP}
{24}{}{RAIDERS.MAP}
{25}{}{SHADYE.MAP}
{26}{}{SHADYW.MAP}
{27}{}{GLOWENT.MAP}
{28}{}{LAADYTUM.MAP}
{29}{}{LAFOLLWR.MAP}
{30}{}{MBENT.MAP}
{31}{}{MBSTRG12.MAP}
{32}{}{MBVATS12.MAP}
{33}{}{MSTRLR12.MAP}
{34}{}{MSTRLR34.MAP}
{35}{}{V13ENT.MAP}
{36}{}{HUBENT.MAP}
{37}{}{DETHCLAW.MAP}
{38}{}{HUBDWNTN.MAP}
{39}{}{HUBHEIGT.MAP}
{40}{}{HUBOLDTN.MAP}
{41}{}{HUBWATER.MAP}
{42}{}{GLOW1.MAP}
{43}{}{GLOW2.MAP}
{44}{}{LABLADES.MAP}
{45}{}{LARIPPER.MAP}
{46}{}{LAGUNRUN.MAP}
{47}{}{CHILDEAD.MAP}
{48}{}{MBDEAD.MAP}
{49}{}{MOUNTN1.MAP}
{50}{}{MOUNTN2.MAP}
{51}{}{FOOT.MAP}
{52}{}{TARDIS.MAP}
{53}{}{TALKCOW.MAP}
{54}{}{USEDCAR.MAP}
{55}{}{BRODEAD.MAP}
{56}{}{DESCRVN1.MAP}
{57}{}{DESCRVN2.MAP}
{58}{}{MNTCRVN1.MAP}
{59}{}{MNTCRVN2.MAP}
{60}{}{VIPERS.MAP}
{61}{}{DESCRVN3.MAP}
{62}{}{MNTCRVN3.MAP}
{63}{}{DESCRVN4.MAP}
{64}{}{MNTCRVN4.MAP}
{65}{}{HUBMIS1.MAP}
{100}{}{Deserto}
{101}{}{Deserto}
{102}{}{Deserto}
{103}{}{Necropolis}
{104}{}{Necropolis}
{105}{}{Necropolis}
{106}{}{Vault 13}
{107}{}{Vault 15}
{108}{}{Vault 15}
{109}{}{Necropolis}
{110}{}{Junktown}
{111}{}{Junktown}
{112}{}{Junktown}
{113}{}{Irmandade}
{114}{}{Irmandade}
{115}{}{Irmandade}
{116}{}{Shady Sands}
{117}{}{Catedral}
{118}{}{Catedral}
{119}{}{Ruinas da Cidade}
{120}{}{Costa}
{121}{}{Costa}
{122}{}{Deserto}
{123}{}{Deserto}
{124}{}{Saqueadores}
{125}{}{Shady Sands}
{126}{}{Shady Sands}
{127}{}{Glow}
{128}{}{Boneyard}
{129}{}{Boneyard}
{130}{}{Base Militar}
{131}{}{Base Militar}
{132}{}{Base Militar}
{133}{}{Base Militar}
{134}{}{Base Militar}
{135}{}{Vault 13}
{136}{}{Hub}
{137}{}{Hub}
{138}{}{Hub}
{139}{}{Hub}
{140}{}{Hub}
{141}{}{Hub}
{142}{}{Glow}
{143}{}{Glow}
{144}{}{Boneyard}
{145}{}{Boneyard}
{146}{}{Boneyard}
{147}{}{Catedral}
{148}{}{Militares}
{149}{}{Montanhas}
{150}{}{Montanhas}
{151}{}{Deserto}
{152}{}{Deserto}
{153}{}{Deserto}
{154}{}{Deserto}
{155}{}{Irmandade}
{156}{}{Deserto}
{157}{}{Deserto}
{158}{}{Montanhas}
{159}{}{Montanhas}
{160}{}{Acampamento dos Viper}
{161}{}{Deserto}
{162}{}{Montanhas}
{163}{}{Deserto}
{164}{}{Montanhas}
{165}{}{Deserto}
{166}{}{Deserto}
{167}{}{Deserto}
{168}{}{Deserto}
{169}{}{Deserto}
{170}{}{Deserto}
{171}{}{Templo}
{172}{}{Templo}
{173}{}{Deserto}
{174}{}{Ferro-Velho}
{175}{}{Shady Sands}
{176}{}{Hub}
{177}{}{Hub}
{178}{}{Ruínas da Cidade}
{179}{}{Ruínas da Cidade}
{180}{}{Montanhas}
{181}{}{Montanhas}
{182}{}{Montanhas}
{183}{}{Montanhas}
{184}{}{Montanhas}
{185}{}{Montanhas}
{186}{}{Montanhas}
{187}{}{Montanhas}
{188}{}{Montanhas}
{189}{}{Vipers}
{190}{}{Ruínas da Cidade}
{191}{}{Ruínas da Cidade}
{200}{}{Deserto}
{201}{}{}
{202}{}{}
{203}{}{Deserto}
{204}{}{}
{205}{}{}
{206}{}{Deserto}
{207}{}{}
{208}{}{}
{209}{}{Esgotos}
{210}{}{Salão}
{211}{}{}
{212}{}{Esgotos}
{213}{}{Hotel}
{214}{}{}
{215}{}{Esgotos}
{216}{}{Bacia Hidrográfica}
{217}{}{}
{218}{}{Entrada}
{219}{}{Alojamento}
{220}{}{Centro de Comando}
{221}{}{Entrada da Caverna}
{222}{}{}
{223}{}{}
{224}{}{Cavernas}
{225}{}{Alojamento}
{226}{}{Centro de Comando}
{227}{}{Esgotos}
{228}{}{Alojamento}
{229}{}{Centro de Comando}
{230}{}{Entrada}
{231}{}{Laboratorio}
{232}{}{}
{233}{}{Cassino}
{234}{}{}
{235}{}{}
{236}{}{Casa do Acidente}
{237}{}{}
{238}{}{}
{239}{}{Entrada}
{240}{}{}
{241}{}{}
{242}{}{Nivel 1}
{243}{}{Nivel 2}
{244}{}{}
{245}{}{Nivel 3}
{246}{}{Nivel 4}
{247}{}{}
{248}{}{Cavernas}
{249}{}{}
{250}{}{}
{251}{}{Entrada}
{252}{}{Torre - Nivel 1}
{253}{}{}
{254}{}{Torre - Nivel 2}
{255}{}{Torre - Nivel 3}
{256}{}{Torre - Nivel 4}
{257}{}{Ruínas da Cidade}
{258}{}{}
{259}{}{}
{260}{}{Costa}
{261}{}{}
{262}{}{}
{263}{}{Costa}
{264}{}{}
{265}{}{}
{266}{}{Especial}
{267}{}{}
{268}{}{}
{269}{}{Especial}
{270}{}{}
{271}{}{}
{272}{}{Base}
{273}{}{}
{274}{}{}
{275}{}{Jardim}
{276}{}{Curral dos Brahmin}
{277}{}{}
{278}{}{Prefeitura}
{279}{}{}
{280}{}{}
{281}{}{Entrada}
{282}{}{}
{283}{}{}
{284}{}{Adytum}
{285}{}{Subsolo}
{286}{}{}
{287}{}{Biblioteca}
{288}{}{Subsolo}
{289}{}{}
{290}{}{Entrada}
{291}{}{}
{292}{}{}
{293}{}{Fortaleza - Nivel 1}
{294}{}{Fortaleza - Nivel 2}
{295}{}{}
{296}{}{Tanques - Nivel 1}
{297}{}{Tanques - Nivel 2}
{298}{}{}
{299}{}{Covil - Nivel 1}
{300}{}{Covil - Nivel 2}
{301}{}{}
{302}{}{Covil - Nivel 3}
{303}{}{Covil - Nivel 4}
{304}{}{}
{305}{}{Entrada da Caverna}
{306}{}{}
{307}{}{}
{308}{}{Entrada}
{309}{}{}
{310}{}{}
{311}{}{Covil}
{312}{}{}
{313}{}{}
{314}{}{Centro da Cidade}
{315}{}{Esconderijo do Decker}
{316}{}{}
{317}{}{Montes}
{318}{}{}
{319}{}{}
{320}{}{Old Town}
{321}{}{Grupo de Ladrões}
{322}{}{}
{323}{}{Mercadores}
{324}{}{}
{325}{}{}
{326}{}{Nivel 1}
{327}{}{Nivel 2}
{328}{}{Nivel 3}
{329}{}{Nivel 4}
{330}{}{Nivel 5}
{331}{}{Nivel 6}
{332}{}{Centro da Cidade}
{333}{}{}
{334}{}{}
{335}{}{Deposito}
{336}{}{Subsolo}
{337}{}{}
{338}{}{Fortaleza}
{339}{}{}
{340}{}{}
{341}{}{Cratera}
{342}{}{}
{343}{}{}
{344}{}{Ruinas}
{345}{}{}
{346}{}{}
{347}{}{Montanhas}
{348}{}{}
{349}{}{}
{350}{}{Montanhas}
{351}{}{}
{352}{}{}
{353}{}{Especial}
{354}{}{}
{355}{}{}
{356}{}{Especial}
{357}{}{}
{358}{}{}
{359}{}{Especial}
{360}{}{}
{361}{}{}
{362}{}{Especial}
{363}{}{}
{364}{}{}
{365}{}{Ruinas}
{366}{}{}
{367}{}{}
{368}{}{Deserto}
{369}{}{Deserto}
{370}{}{Deserto}
{371}{}{Deserto}
{372}{}{Deserto}
{373}{}{Deserto}
{374}{}{Montanhas}
{375}{}{Montanhas}
{376}{}{Montanhas}
{377}{}{Montanhas}
{378}{}{Montanhas}
{379}{}{Montanhas}
{380}{}{Deserto}
{381}{}{Deserto}
{382}{}{Deserto}
{383}{}{Montanhas}
{384}{}{Montanhas}
{385}{}{Montanhas}
{386}{}{Deserto}
{387}{}{Deserto}
{388}{}{Deserto}
{389}{}{Montanhas}
{390}{}{Montanhas}
{391}{}{Montanhas}
{392}{}{Deserto}
{393}{}{Deserto}
{394}{}{Deserto}
{395}{}{Fazenda do Irwin}
{396}{}{}
{397}{}{}
{398}{}{Fazenda do Irwin}
{399}{}{}
{400}{}{}
{401}{}{Deserto}
{402}{}{Deserto}
{403}{}{Deserto}
{404}{}{Montanhas}
{405}{}{Montanhas}
{406}{}{Montanhas}
{407}{}{Ruínas da Cidade}
{408}{}{Ruínas da Cidade}
{409}{}{Ruínas da Cidade}
{410}{}{Costa}
{411}{}{Costa}
{412}{}{Costa}
{413}{}{Deserto}
{414}{}{}
{415}{}{}
{416}{}{Entrada}
{417}{}{}
{418}{}{}
{419}{}{Templo: Saguão}
{420}{}{Templo: Corredor}
{421}{}{Templo: Santuário Interno}
{422}{}{Deserto}
{423}{}{}
{424}{}{}
{425}{}{Cidade}
{426}{}{}
{427}{}{}
{428}{}{Cavernas}
{429}{}{}
{430}{}{}
{431}{}{Fazenda}
{432}{}{}
{433}{}{}
{434}{}{Covil}
{435}{}{}
{436}{}{}
{437}{}{Ruínas da Cidade}
{438}{}{}
{439}{}{}
{440}{}{Ruínas da Cidade}
{441}{}{}
{442}{}{}
{443}{}{Montanhas}
{444}{}{}
{445}{}{}
{446}{}{Montanhas}
{447}{}{Caverna}
{448}{}{}
{449}{}{Montanhas}
{450}{}{Caverna}
{451}{}{}
{452}{}{Montanhas}
{453}{}{Caverna}
{454}{}{}
{455}{}{Montanhas}
{456}{}{Caverna}
{457}{}{}
{458}{}{Montanhas}
{459}{}{Caverna}
{460}{}{Montanhas}
{461}{}{Montanhas}
{462}{}{Mina}
{463}{}{Deserto}
{464}{}{Montanhas}
{465}{}{Mina}
{466}{}{Deserto}
{467}{}{Montanhas}
{468}{}{Mina}
{469}{}{Deserto}
{470}{}{Acampamento}
{471}{}{}
{472}{}{}
{473}{}{Ruínas da Cidade}
{474}{}{}
{475}{}{}
{476}{}{Ruínas da Cidade}
{477}{}{}
{478}{}{}
{1500}{}{Vault 13}
{1501}{}{Vault 15}
{1502}{}{Shady Sands}
{1503}{}{Junktown}
{1504}{}{Saqueadores}
{1505}{}{Necropolis}
{1506}{}{Hub}
{1507}{}{Brotherhood}
{1508}{}{Base Militar}
{1509}{}{Glow}
{1510}{}{Boneyard}
{1511}{}{Catedral}
{1512}{}{unused}
{1513}{}{unused}
{1514}{}{Nômades}
{1515}{}{unused}
{1516}{}{unused}
{1517}{}{unused}
{1518}{}{unused}
{1519}{}{unused}
{1520}{}{unused}
{1521}{}{Moto sem Energia}
{1522}{}{unused}
{1523}{}{unused}
{1524}{}{unused}
{1525}{}{unused}
{1526}{}{ }
{1527}{}{ }
{1528}{}{ }
{1529}{}{ }
{1530}{}{unused}
{1531}{}{unused}
{1532}{}{unused}
{1533}{}{unused}
{1534}{}{unused}
{1535}{}{unused}
{1536}{}{unused}
{1537}{}{unused}
{1538}{}{unused}
{1539}{}{unused}
{1540}{}{unused}
{1541}{}{unused}
{1542}{}{unused}
{1543}{}{unused}
{1544}{}{Caravana}
{1545}{}{unused}
{1546}{}{unused}
{1547}{}{ }
{1548}{}{unused}
{1549}{}{ }
{1550}{}{ }
{1551}{}{ }
{1552}{}{ }
{1553}{}{Pegada Gigante}
{1554}{}{Caixa de Chamada Incomum}
{1555}{}{Loja de Carros do Bob}
{1556}{}{Caminhão de Nuka-Cola}
{1557}{}{Disco Voador Caído}
{1558}{}{Rebanho de Brahmin}
{1559}{}{Guardião do Eterno}
{1560}{}{Ferro-Velho}
{1561}{}{Cavernas}
{1562}{}{Fazenda do Irwin}
{1563}{}{Covil da Deathclaw}
{1564}{}{ }
{1000}{}{Erro: Sem espaco em disco o bastante para salvar o mapa!}
{500}{}{Vault 13}
{501}{}{Vault 15}
{502}{}{Shady Sands}
{503}{}{Junktown}
{504}{}{Saqueadores}
{505}{}{Necropolis}
{506}{}{Hub}
{507}{}{Irmandade}
{508}{}{Base Militar}
{509}{}{Glow}
{510}{}{Boneyard}
{511}{}{Catedral}
