{106}{}{Você vê uma mulher.}
{107}{}{Você vê um homem.}
{100}{}{Você vê um bêbado.}
{110}{}{Me deixe com as minhas mágoas.}
{111}{}{Ocê é meu melhó amigo.}
{112}{}{Ora, você é... (hic) onde é que eu tô?}
{113}{}{Quem é você?}
{114}{}{Eu te conheço?}
{115}{}{Tô me sentindo meio enjoado.}
{116}{}{As bebidas são por minha conta, digo, por sua.}
{117}{}{Por que tem dois de você?}
{118}{}{Fica parado, rapaz!}
{119}{}{Fica parada, garota!}
{101}{}{Você vê um cliente.}
{104}{}{Você vê um apostador.}
{120}{}{Cai fora, verme!}
{121}{}{Ocê tá baixando o nível deste lugar.}
{122}{}{Sai daqui, você vai me dar azar!}
{123}{}{Não quebra minha concentração.}
{124}{}{Ainda vou vencer esse maldito jogo!}
{125}{}{Você é bom nisso?}
{126}{}{Você viu aquilo? Foi impossível!}
{127}{}{Acho que estão trapaceando.}
{128}{}{Agora sim essas são boas probabilidades.}
{129}{}{É barbada.}
{130}{}{O quê? Como é que eu perdi?}
{131}{}{Esta mesa está amaldiçoada!}
{132}{}{Estou ocupado.}
{133}{}{Não está vendo que estou jogando aqui?}
{134}{}{Aposta ou cai fora.}
{102}{}{Você vê uma mulher de aparência vulgar.}
{302}{}{Olhando melhor, fica óbvio que é uma prostituta. Ela te lança um sorriso falso.}
{200}{}{Ei, querido, procurando um bom momento?}
{201}{}{O que você procura, querido?}
{202}{}{Procurando companhia?}
{203}{}{E aí, gatinho.}
{204}{}{Gostou do que viu? Eu gostei.}
{205}{}{Me mostra o que você tem, docinho.}
{206}{}{Gosto de brutalidade, se você curte isso.}
{207}{}{Sem doença, sou limpa!}
{208}{}{Faço em grupo, por um pouquinho a mais.}
{209}{}{Faço qualquer coisa pelo preço certo...}
{210}{}{Nunca fiquei com uma garota antes...}
{211}{}{Sou seu sonho realizado, docinho.}
{212}{}{Se você tem as tampinhas, eu topo.}
{213}{}{Gostou do que viu? Eu gostei.}
{214}{}{E aí, benzinho.}
{215}{}{Ei, querido, procurando um bom momento?}
{216}{}{Gosto de brutalidade, se você curte isso.}
{217}{}{Sem doença, sou limpa!}
{218}{}{Faço em grupo, por um pouquinho a mais.}
{219}{}{Faço qualquer coisa pelo preço certo...}
{232}{}{Muié bunita. Comigo?}
{233}{}{Ah, meu Deus... querido, eu preciso ganhar a vida, mas até eu tenho padrões.}
{235}{}{EU QUERÉ!}
{405}{}{Bom... acho que posso abrir uma exceção. Mas é bom você ter um monte de tampinhas.}
{243}{}{Cap?}
{244}{}{[suspiro] Sim, seu idiota, tampinhas de garrafa. Me paga 150 e eu te mostro um bom momento. Deve dar pra afogar minha vergonha no bar e ainda ter lucro.}
{238}{}{Hmpf.}
{239}{}{Desculpa, querido. Se você arrumar um cérebro novo, volta pra me ver.}
{240}{}{Mmf. Tá-bom, eu ir.}
{257}{}{Aqui vai.}
{258}{}{Eu num tê grana...}
{259}{}{Hmpf!}
{260}{}{Não acredito que estou fazendo isso...}
{261}{}{Vai logo, eu vou vomitar agora.}
{262}{}{Preciso arrumar um emprego novo.}
{263}{}{Você de novo? Vai se ferrar, não trabalho com retardados que não podem pagar.}
{264}{}{Urr...}
{265}{}{Buh?}
{220}{}{Quanto custa a diversão?}
{221}{}{Vinte tampinhas.}
{249}{}{Certo, parece bom.}
{222}{}{Vamos aos negócios...}
{227}{}{Beleza. O que você procura, querido?}
{223}{}{Não, obrigado, não tenho interesse.}
{225}{}{Quanto por uma ação em grupo?}
{241}{}{Depende do que você procura, benzinho.}
{226}{}{Cem tampinhas.}
{230}{}{Dança no colo.}
{231}{}{Striptease.}
{234}{}{Se divirta sozinho, eu só assisto.}
{237}{}{Qualquer coisa e tudo! Me surpreenda...}
{245}{}{Não me importo, vamos logo acabar com isso.}
{246}{}{Só sexo.}
{236}{}{O de sempre.}
{250}{}{Pensando bem, deixa pra lá.}
{251}{}{Como quiser, docinho. Você vai voltar.}
{228}{}{Certo, me siga...}
{242}{}{Certo, todo mundo me siga...}
{254}{}{[Continuar]}
{229}{}{Obrigada, estranho. [ela embolsa as tampinhas e te manda um beijo]}
{256}{}{Obrigada, docinho. Volte logo!}
{224}{}{Obrigado pelo bom momento. Até mais.}
{247}{}{Pra você, }
{248}{}{Pra você, docinho? }
{300}{}{ tampinhas.}
{252}{}{Não tenho todas essas tampinhas.}
{253}{}{Então por que diabos você está falando comigo? Cai fora!}
{255}{}{[Pronto]}
{400}{}{Bom, isso foi interessante.}
{401}{}{Au!}
{402}{}{É melhor a gente voltar ao trabalho agora.}
{403}{}{Eca, me sinto suja.}
{404}{}{Ah, uau...}
{105}{}{Você vê uma mulher muito bonita. Ela parece estar ocupada.}
{301}{}{Olhando melhor, fica óbvio que é uma prostituta com um cliente. Ela te faz sinal pra sair, imediatamente.}
{135}{}{Nos deixe em paz ou eu chamo os guardas.}
{136}{}{Cuidado, sou amiga íntima do Delegado Fry.}
{137}{}{Você se importa?}
{138}{}{Sem espiadinha!}
{139}{}{Não faço em grupo.}
{140}{}{Estou cansada demais pra mais uma.}
{141}{}{Você está sonhando, amigo, cai fora!}
{142}{}{Sai daqui, porra!}
{143}{}{O que diabos você acha que está fazendo?}
{144}{}{Olha os modos!}
{145}{}{Vou chamar a polícia!}
{146}{}{Nem pense nisso!}
{147}{}{Cai fora!}
{148}{}{Some!}
{149}{}{O que você está olhando?}
{109}{}{Você vê um mercenário.}
{150}{}{Você se importa?}
{151}{}{Saia do nosso quarto, porra!}
{152}{}{Cai fora!}
{153}{}{Você faz parte do combo?}
{154}{}{Some, tarado!}
{155}{}{Qual é o seu problema?}
{156}{}{Some antes que eu me irrite.}
{157}{}{Arrume a sua.}
{158}{}{Ela é minha.}
{108}{}{Você vê um apostador muito irritado.}
{159}{}{Droga!}
{160}{}{Você está trapaceando?}
{161}{}{Aquilo devia ter sido meu.}
{162}{}{Quase!}
{163}{}{Passou perto.}
{164}{}{Quais são as regras mesmo?}
{165}{}{Eu era bom nisso.}
{166}{}{Obrigado por nada.}
{167}{}{Não acredito nisso!}
{168}{}{Eu fiz de propósito, juro.}
{103}{}{Você vê um homem de aparência estranha.}
{169}{}{Façam suas apostas.}
{170}{}{Mantenha as mãos longe, senhor.}
{171}{}{Vencedor!}
{172}{}{Desculpem, pessoal, talvez na próxima.}
{173}{}{Outro vencedor!}
{174}{}{Tira a mão!}
{175}{}{Sua vez, senhor.}
{176}{}{Desculpe, essa aposta é inválida.}
{177}{}{É isso.}
{178}{}{Mais alguém?}
