{100}{}{Você destranca a porta.}
{101}{}{Você quebrou suas gazuas!}
{102}{}{Você não consegue abrir esta tranca.}
{103}{}{Você não foi capaz de abrir a tranca.}
{104}{}{A porta esta trancada.}
{105}{}{A porta esta aberta.}
{106}{}{A porta esta fechada mas destrancada.}
{107}{}{A porta esta trancada.}
{108}{}{A porta range com muito barulho.}
{109}{}{A porta já esta destrancada.}
{110}{}{A tranca esta alem da sua habilidade de abrir.}
{111}{}{A fechadura está além da habilidade de }
{112}{}{ de arrombá-la.}
{120}{}{Você vê uma porta de metal.}
{1000}{}{Você vê uma porta de madeira.}
{1010}{}{Você vê uma porta de metal.}
{1020}{}{Você vê uma porta robusta com uma fechadura (que pode ser arrombada com gazuas) e uma armadilha altamente explosiva no batente, que talvez você consiga forçar pra abrir.}
{1030}{}{Você vê uma porta robusta com uma fechadura e uma armadilha altamente explosiva no batente, que talvez você consiga forçar pra abrir.}
{1040}{}{Você vê uma porta robusta sem nenhum mecanismo de travamento aparente e uma armadilha altamente explosiva no batente, que talvez você consiga forçar pra abrir.}
{1050}{}{Você vê uma porta robusta com uma fechadura velha e enferrujada e uma armadilha altamente explosiva no batente, que talvez você consiga forçar pra abrir.}
{1060}{}{Você vê uma porta robusta com uma fechadura (que pode ser arrombada com gazuas) e uma armadilha no batente, que talvez você consiga forçar pra abrir.}
{1070}{}{Você vê uma porta robusta com uma fechadura e uma armadilha no batente, que talvez você consiga forçar pra abrir.}
{1080}{}{Você vê uma porta robusta sem nenhum mecanismo de travamento aparente e uma armadilha no batente, que talvez você consiga forçar pra abrir.}
{1090}{}{Você vê uma porta robusta com uma fechadura velha e enferrujada e uma armadilha no batente, que talvez você consiga forçar pra abrir.}
{1100}{}{Você vê uma porta robusta com uma fechadura (que pode ser arrombada com gazuas) e um fio cortado no batente, que talvez você consiga forçar pra abrir.}
{1110}{}{Você vê uma porta robusta com uma fechadura e um fio cortado no batente, que talvez você consiga forçar pra abrir.}
{1120}{}{Você vê uma porta robusta sem nenhum mecanismo de travamento aparente e um fio cortado no batente, que talvez você consiga forçar pra abrir.}
{1130}{}{Você vê uma porta robusta com uma fechadura velha e enferrujada e um fio cortado no batente, que talvez você consiga forçar pra abrir.}
{1140}{}{Você vê uma porta robusta com uma fechadura (que pode ser arrombada com gazuas), que talvez você consiga forçar pra abrir.}
{1150}{}{Você vê uma porta robusta com uma fechadura, que talvez você consiga forçar pra abrir.}
{1160}{}{Você vê uma porta robusta sem nenhum mecanismo de travamento aparente, que talvez você consiga forçar pra abrir.}
{1170}{}{Você vê uma porta robusta com uma fechadura velha e enferrujada, que talvez você consiga forçar pra abrir.}
{1180}{}{Você vê uma porta robusta com uma fechadura (que pode ser arrombada com gazuas) e uma armadilha altamente explosiva no batente.}
{1190}{}{Você vê uma porta robusta com uma fechadura e uma armadilha altamente explosiva no batente.}
{1200}{}{Você vê uma porta robusta sem nenhum mecanismo de travamento aparente e uma armadilha altamente explosiva no batente.}
{121}{}{Você vê uma porta robusta com uma fechadura velha e enferrujada e uma armadilha altamente explosiva no batente.}
{122}{}{Você vê uma porta robusta com uma fechadura (que pode ser arrombada com gazuas) e uma armadilha no batente.}
{123}{}{Você vê uma porta robusta com uma fechadura e uma armadilha no batente.}
{124}{}{Você vê uma porta robusta sem nenhum mecanismo de travamento aparente e uma armadilha no batente.}
{125}{}{Você vê uma porta robusta com uma fechadura velha e enferrujada e uma armadilha no batente.}
{126}{}{Você vê uma porta robusta com uma fechadura (que pode ser arrombada com gazuas) e um fio cortado no batente.}
{127}{}{Você vê uma porta robusta com uma fechadura e um fio cortado no batente.}
{128}{}{Você vê uma porta robusta sem nenhum mecanismo de travamento aparente e um fio cortado no batente.}
{129}{}{Você vê uma porta robusta com uma fechadura velha e enferrujada e um fio cortado no batente.}
{130}{}{Você vê uma porta robusta com uma fechadura (que pode ser arrombada com gazuas).}
{131}{}{Você vê uma porta robusta com uma fechadura.}
{132}{}{Você vê uma porta robusta sem nenhum mecanismo de travamento aparente.}
{133}{}{Você vê uma porta robusta com uma fechadura velha e enferrujada.}
{134}{}{Você vê uma porta danificada com uma fechadura (que pode ser arrombada com gazuas) e uma armadilha altamente explosiva no batente.}
{135}{}{Você vê uma porta danificada com uma fechadura e uma armadilha altamente explosiva no batente.}
{136}{}{Você vê uma porta danificada sem nenhum mecanismo de travamento aparente e uma armadilha altamente explosiva no batente.}
{137}{}{Você vê uma porta danificada com uma fechadura velha e enferrujada e uma armadilha altamente explosiva no batente.}
{138}{}{Você vê uma porta danificada com uma fechadura (que pode ser arrombada com gazuas) e uma armadilha no batente.}
{139}{}{Você vê uma porta danificada com uma fechadura e uma armadilha no batente.}
{140}{}{Você vê uma porta danificada sem nenhum mecanismo de travamento aparente e uma armadilha no batente.}
{141}{}{Você vê uma porta danificada com uma fechadura velha e enferrujada e uma armadilha no batente.}
{142}{}{Você vê uma porta danificada com uma fechadura (que pode ser arrombada com gazuas) e um fio cortado no batente.}
{143}{}{Você vê uma porta danificada com uma fechadura e um fio cortado no batente.}
{144}{}{Você vê uma porta danificada sem nenhum mecanismo de travamento aparente e um fio cortado no batente.}
{145}{}{Você vê uma porta danificada com uma fechadura velha e enferrujada e um fio cortado no batente.}
{146}{}{Você vê uma porta danificada com uma fechadura (que pode ser arrombada com gazuas).}
{147}{}{Você vê uma porta danificada com uma fechadura.}
{148}{}{Você vê uma porta danificada sem nenhum mecanismo de travamento aparente.}
{149}{}{Você vê uma porta danificada com uma fechadura velha e enferrujada.}
{150}{}{Você vê uma porta velha com uma fechadura (que pode ser arrombada com gazuas) e uma armadilha altamente explosiva no batente.}
{151}{}{Você vê uma porta velha com uma fechadura e uma armadilha altamente explosiva no batente.}
{152}{}{Você vê uma porta velha sem nenhum mecanismo de travamento aparente e uma armadilha altamente explosiva no batente.}
{153}{}{Você vê uma porta velha com uma fechadura velha e enferrujada e uma armadilha altamente explosiva no batente.}
{154}{}{Você vê uma porta velha com uma fechadura (que pode ser arrombada com gazuas) e uma armadilha no batente.}
{155}{}{Você vê uma porta velha com uma fechadura e uma armadilha no batente.}
{156}{}{Você vê uma porta velha sem nenhum mecanismo de travamento aparente e uma armadilha no batente.}
{157}{}{Você vê uma porta velha com uma fechadura velha e enferrujada e uma armadilha no batente.}
{158}{}{Você vê uma porta velha com uma fechadura (que pode ser arrombada com gazuas) e um fio cortado no batente.}
{159}{}{Você vê uma porta velha com uma fechadura e um fio cortado no batente.}
{160}{}{Você vê uma porta velha sem nenhum mecanismo de travamento aparente e um fio cortado no batente.}
{161}{}{Você vê uma porta velha com uma fechadura velha e enferrujada e um fio cortado no batente.}
{162}{}{Você vê uma porta velha com uma fechadura (que pode ser arrombada com gazuas).}
{163}{}{Você vê uma porta velha com uma fechadura.}
{164}{}{Você vê uma porta velha sem nenhum mecanismo de travamento aparente.}
{165}{}{Você vê uma porta velha com uma fechadura velha e enferrujada.}
{166}{}{Você aciona a armadilha e leva }
{167}{}{ pontos de dano.}
{168}{}{ aciona a armadilha e leva }
{169}{}{ pontos de dano.}
{170}{}{Você abre a fechadura da porta com destreza.}
{171}{}{Sua falta de perícia emperrou a fechadura desta porta.}
{172}{}{Você não consegue arrombar a fechadura desta porta.}
{189}{}{Você tranca a porta com destreza.}
{190}{}{Você não consegue trancar a porta.}
{194}{}{Você encontra uma armadilha na porta.}
{195}{}{Você não encontra nenhuma armadilha na porta.}
{196}{}{Você desarma a armadilha com habilidade.}
{198}{}{Você não consegue desarmar a armadilha.}
{173}{}{ abre a fechadura da porta com destreza.}
{174}{}{ emperrou a fechadura desta porta por falta de perícia.}
{175}{}{ não conseguiu arrombar a fechadura desta porta.}
{191}{}{ tranca a porta com destreza.}
{192}{}{ não conseguiu trancar a porta.}
{199}{}{ encontra uma armadilha na porta.}
{2000}{}{ não encontra nenhuma armadilha na porta.}
{2010}{}{ desarma a armadilha com habilidade.}
{2020}{}{ não consegue desarmar a armadilha.}
{176}{}{Você arranca a fechadura da porta.}
{177}{}{Você força as costas ao tentar arrancar a fechadura e leva um ponto de dano.}
{178}{}{Você força as costas ao tentar arrancar a fechadura e leva }
{179}{}{ pontos de dano.}
{180}{}{Você é fraco demais pra arrancar a fechadura.}
{181}{}{ arranca a fechadura da porta.}
{182}{}{ força as costas ao tentar arrancar a fechadura e leva um ponto de dano.}
{183}{}{ força as costas ao tentar arrancar a fechadura e leva }
{184}{}{ pontos de dano.}
{185}{}{ é fraco demais pra arrancar a fechadura.}
{186}{}{ força as costas ao tentar arrancar a fechadura e leva um ponto de dano.}
{187}{}{ força as costas ao tentar arrancar a fechadura e leva }
{188}{}{ pontos de dano.}
{193}{}{Isso não faz nem um arranhão na porta.}
{1931}{}{A porta está danificada, mas ainda não abre.}
{200}{}{Não há tranca nesta porta pra abrir.}
{201}{}{Você nota algumas irregularidades na parede.}
{203}{}{A porta parece estar trancada.}
{204}{}{Você nota uma armadilha no batente da porta.}
{205}{}{ nota uma armadilha no batente da porta.}
{206}{}{Você não consegue colocar uma armadilha nesta porta, porque a porta está aberta.}
{207}{}{ não consegue colocar uma armadilha nesta porta, porque a porta está aberta.}
{208}{}{Você coloca uma armadilha no batente da porta com habilidade.}
{209}{}{Você não consegue colocar a armadilha no batente da porta corretamente.}
{210}{}{ coloca uma armadilha no batente da porta com habilidade.}
{211}{}{ não consegue colocar a armadilha no batente da porta corretamente.}
{300}{}{Você destranca a porta.}
{301}{}{Você tranca a porta.}
{302}{}{Você não consegue trancar esta porta enquanto ela está aberta.}
{303}{}{Essa chave não serve nesta fechadura.}
{320}{}{Não há como trancar esta porta.}
{330}{}{Esta porta está travada aberta.}
{400}{}{Você destranca a porta.}
{414}{}{Você vê uma porta robusta com uma fechadura (que pode ser arrombada com gazuas), que talvez você consiga forçar pra abrir.}
{415}{}{Você vê uma porta robusta com uma fechadura, que talvez você consiga forçar pra abrir.}
{416}{}{Você vê uma porta robusta sem nenhum mecanismo de travamento aparente, que talvez você consiga forçar pra abrir.}
{417}{}{Você vê uma porta robusta, que talvez você consiga forçar pra abrir.}
{500}{}{Esta porta é pesada demais pra forçar a abertura.}
{501}{}{Parece que você precisa fazer o gerador funcionar primeiro.}
{502}{}{Você vê: Porta do elevador.}
{503}{}{Parece que você precisa de um dispositivo elétrico pra abrir esta fechadura.}
{620}{}{Você entorta o pé de cabra além do reconhecível. Está inútil agora.}
{621}{}{ entorta o pé de cabra além do reconhecível. Está inútil agora.}
