{100}{}{Você ganha 500 pontos de experiência por parar os Radscorpions.}
{101}{}{ de experiência por proteger Shady Sands matando todos os radscorpions.}
{102}{}{Parece ter se originado do escorpião-imperador norte-americano.}
{188}{}{Os radscorpions estão agora selados na caverna, não representando mais uma ameaça a Shady Sands.}
{189}{}{}
{200}{}{A boca da caverna te chama pra mais fundo no covil dos radscorpions...}
