{100}{}{Você vê uma máquina estranha. }
{101}{}{Você vê um caça-níqueis. }
{102}{}{Você vê um caça-níqueis reluzente. }
{103}{}{Você vê um caça-níqueis brilhante. }
{130}{}{Ela tem três olhos e um braço.}
{140}{}{A aposta mínima é }
{141}{}{ tampinhas.}
{150}{}{Você jura que consegue vê-la te olhando pelo canto do olho. }
{151}{}{Sua armação lustrosa e a alavanca dourada reluzem sedutoramente sob as luzes. }
{165}{}{É voltada pros grandes apostadores. }
{180}{}{O alto valor de prêmio dela parece bem atraente. }
{200}{}{(Sua mão treme quando você alcança suas moedas. A máquina continua sussurrando pra você.) *Vem, docinho... isso... vem agora... não me provoca*}
{201}{}{Você vê um caça-níqueis. Sua armação lustrosa e a alavanca dourada reluzem sedutoramente sob as luzes. A abertura de moedas te chama, e você sente o rosto corar de expectativa.}
{202}{}{(Sua mão treme quando você alcança suas moedas. A máquina continua sussurrando pra você.) *Vem, meu bem... isso... pega a alavanca... segura firme... vem agora*}
{250}{}{Inserir }
{251}{}{ tampinhas. }
{252}{}{Jogar a última }
{253}{}{ tampinha.}
{254}{}{Encerrar por hoje.}
{255}{}{Você está falido. É forçado a encerrar por esta noite.}
{256}{}{Encerrar por esta noite.}
{257}{}{Você está falido. É forçado a encerrar por hoje.}
{258}{}{Chega! Estou indo embora!}
{259}{}{Chega! Estou indo embora!}
{500}{}{Os rolos giram na máquina... }
{599}{}{... }
{600}{}{Nada. }
{601}{}{Uma cereja. }
{602}{}{Duas cerejas. }
{603}{}{Três }
{613}{}{. }
{604}{}{JACKPOT! }
{605}{}{JACKPOT DUPLO!!! }
{700}{}{O prêmio é }
{701}{}{ tampinhas.}
{1001}{}{cereja}
{1002}{}{laranja}
{1003}{}{plum}
{1004}{}{bell}
{1005}{}{bar}
{1006}{}{melão}
{1007}{}{sete}
{1101}{}{cerejas}
{1102}{}{laranjas}
{1103}{}{ameixas}
{1104}{}{sinos}
{1105}{}{bars}
{1106}{}{melões}
{1107}{}{setes}
{2000}{}{*Vem brincar comigo um pouquinho, cowboy.*}
{2001}{}{*Olá, marujo.*}
{2002}{}{*Põe uma tampinha, puxa o braço. Vou ser boazinha com você.*}
{2003}{}{*Tique Tique Tiiiiique*}
{2004}{}{*Dim*}
{2005}{}{*Bin*}
{2006}{}{*Cha-ching*}
{2007}{}{*Zzzzzzz*}
{2008}{}{*Trim-trim*}
{2009}{}{*Dindim-dim*}
{2010}{}{*E aí, gata. Vem brincar comigo um pouquinho.*}
{2011}{}{*Olá, linda.*}
{2012}{}{*Ora, mas que coisinha mais bonita. Por que você não vem brincar comigo?*}
{2175}{}{(Você encara o caça-níqueis percebendo que não tem o bastante pra jogar, e amaldiçoa sua pobreza. Talvez outra hora)}
{2176}{}{Sair.}
{2185}{}{(A luz de "FORA DE SERVIÇO" no caça-níqueis está piscando.)}
{2186}{}{Sair.}
{2100}{}{Você vê uma estranha caixa de metal dourado com três olhos e um braço. É uma das coisas mais bonitas que você já viu.}
{2101}{}{Me }
{2102}{}{qem ocê?}
{2103}{}{Eu sinti falta da MÃE. }
{2104}{}{sinti falta do VAUL-T. Eu qué ir pra casa}
{2105}{}{(Apertar a mão dela)}
{2106}{}{você um mutante estranho}
{2107}{}{Louvado seja o Vault! Louvado seja o Vault!}
{2108}{}{Você é um chip de água?}
{2109}{}{Sair vagando, procurar outras coisas brilhantes}
{2110}{}{Sair.}
{2130}{}{A estranha e bonita caixa de metal dourado com três olhos e um braço não responde.}
{2131}{}{ME }
{2132}{}{! OCÊ ME RESPONDE!}
{2133}{}{(Apertar a mão dela)}
{2134}{}{Eu Vault Dweller. Ocê fala comigo AGORA.}
{2135}{}{você um mutante estranho}
{2136}{}{Você é um chip de água?}
{2137}{}{Sair vagando, procurar outras coisas brilhantes}
{2138}{}{(Sair.)}
{2151}{}{Você agarra o braço dela e o aperta calorosamente. Ao fazer isso, ouve-se um *bzzzzzzz,* e a caixa fala! "Por favor, insira dinheiro."}
{2152}{}{Aaaaii! Robô! Robô! Correee}
{2153}{}{(Sair.)}
{2200}{}{(Você consegue ouvi-la rindo de você.)}
{2201}{}{*Hehehe, por que você simplesmente não desiste, docinho.*}
{2202}{}{*Talvez você devesse deixar outra pessoa puxar minha alavanca.*}
{2203}{}{(Uma leve risada maníaca emana da máquina.)}
{2204}{}{(Você ouve o caça-níqueis rindo de você.)}
{2205}{}{(O caça-níqueis dá uma risadinha de você.)}
{2206}{}{*Vem cá, perdedor, não desiste de mim*}
{2207}{}{*Já consegui o que queria de você, benzinho. Por que não desiste?*}
{2208}{}{*Lixo!*}
{2209}{}{*Não deixa a porta te acertar na saída.*}
{2247}{}{*Aieeeeeee! Isso, docinho! Ai, meu Deus, sim! Sim! Sim, de novo! Mais rápido! Mais forte! O que você está esperando?! De novo!*}
{2248}{}{*Isso, docinho... continua puxando a alavanca mais rápido, mais forte, mais rápido... vem agora*}
{2249}{}{*Vem, docinho... acontece com todo mundo pelo menos uma vez... tenta de novo... por favor*}
{2250}{}{*Por favor, não desiste de mim ainda, benzinho! Preciso de você agora mais do que nunca!*}
{2251}{}{*Vem, meu amor... tenta de novo... pega a alavanca... segura firme... vem agora*}
{2252}{}{*Isso, meu amor... continua puxando a alavanca mais rápido, mais forte, mais rápido... vem agora*}
{2253}{}{*Ennnnghhhh! Isso, meu amor! Quem é o seu Dono?! Quem é o seu Dono?!! Faz de novo! Puxa mais forte dessa vez! Mais forte!*}
{2280}{}{(Você vê um caça-níqueis. Sua armação lustrosa e a alavanca dourada reluzem sedutoramente sob as luzes. A abertura de moedas te chama, e você sente o rosto corar de expectativa. Enquanto você a encara, uma das três janelinhas te dá uma piscadela. Da abertura de moedas você ouve uma voz rouca.) *Ora, essa! Aloooo, docinho. Vai mostrar a uma garota o que é diversão?*}
{2281}{}{(Você vê um caça-níqueis. Sua armação forte e robusta e a alavanca dourada reluzem como um deus-sol sob as luzes. A abertura de moedas te chama sedutoramente, e você sente as coxas arderem de expectativa. Enquanto você a encara, de repente uma voz masculina e grave sussurra da abertura de moedas.) *Nunca vi uma mulher bonita como você por aqui, moça. Está a fim de arriscar a sorte?*}
{2282}{}{::Beliscar-se::}
{2283}{}{Uh... alô?}
{2284}{}{::Respirar fundo e ir embora.::}
{2300}{}{*Ainda estou aqui, mocinha bonita.* (O caça-níqueis abaixa a voz.) *Olha, vem cá... você quer fazer uma aposta?*}
{2301}{}{*Ainda estou aqui, docinho.* (O caça-níqueis abaixa a voz.) *Você é um baita pedaço de homem, sabia? Vem agora... você quer enfiar umas moedinhas em mim?*}
{2302}{}{Qem *é* voooocê?}
{2303}{}{Clarrru eu apostu umas moedas em voooocê}
{2304}{}{Acho melhor eu ir embora antes que eu enfie algo em você de que eu possa me arrepender. (Sair.)}
{2305}{}{::Respirar fundo e ir embora.:: (Sair.)}
{2320}{}{*Sou o seu homem ideal.* (O caça-níqueis te dá uma piscadela.) *Me dá umas moedas, e eu te dou prazer de um jeito que NENHUM homem jamais te deu.*}
{2321}{}{*Sou a sua mulher ideal, docinho. Tudo o que eu quero é um pouco de atenção. Você pode ajudar a bonitinha aqui? Vem, só uma moeda ou duas?*}
{2322}{}{A gente num pode só convershá}
{2340}{}{*Claro que pode, meu amor, claro que pode.* (O caça-níqueis parece solidário.) *O que está incomodando essa sua cabecinha linda?*}
{2341}{}{*Claro que pode, docinho, claro que pode.* (O caça-níqueis parece solidário.) *O que está te incomodando, gato?*}
{2342}{}{Eu sinti falta da MÃE e do VAULT e num acho o Chip de Água e *snif*}
{2343}{}{Eu sinti falta da MÃE e o VAULT foi ATACADO e num sei onde eles estão e *snif*}
{2344}{}{Eu preciso deter uns mutante grande e mau e num sei COMO e minha-minha-minha Mãe SUMIU e *snif*}
{2345}{}{Eu terminei o jogo e agora tô só vagano por aí e tô preocupado que já acabô TUDO e *snif*}
{2346}{}{É que o Fhallowt dois num s'porta minha placa 3D Fxxxx e eu gastei tanta *graninha* nela e *snif*}
{2347}{}{Eu tentei fazer um bom persunagem mas acho que gastei os pontos tudo *errado* e agora tenho um persunagem uma budega e *snif*}
{2348}{}{tô tendo uma conversha com um caça-níqueis, tô bem mal das pernas}
{2370}{}{*Calma, calma... não esquenta mais essa cabecinha linda com isso... deixa que eu cuido de tudo. Vem, descansa a cabeça em mim. Isso. Põe tudo pra fora.*}
{2371}{}{*Calma, calma... não esquenta mais com isso, docinho... deixa que eu cuido de tudo. Vem, descansa essa cabeça bonita em mim. Isso. Põe tudo pra fora.*}
{2372}{}{Obrigadu, caça-níqueis *snif* ocê é o melhó}
{2373}{}{Ocê a únika pessoa *legal* que eu conheci até agora todo mundo é tão máu e tentô me *machucá* e pegá meu dinheru e *snif*}
{2380}{}{*Você vai ficar bem, meu amor? Não me sinto à vontade te deixando sair sozinho desse jeito.*}
{2381}{}{(Você descansa sua cabeça cansada na máquina.)}
{2382}{}{*Você vai ficar bem, docinho? Não me sinto à vontade te deixando sair sozinha desse jeito.*}
{2383}{}{Vô ficá bem... obrigadu por convershá comigo, caça-níqueis... eu te aaamu}
{2400}{}{*Você é a única heroína que temos neste mundinho vagabundo de canalhas e ladrões! Se cuida agora, ouviu, meu amor?* (Vira-se.) *É melhor você ir antes que eu comece a agir de um jeito pouco masculino.*}
{2401}{}{(Uma lágrima parece se formar em uma das janelinhas.) }
{2402}{}{*Você é o único herói que temos neste mundinho vagabundo de canalhas e ladrões! Você... você... se cuida agora, ouviu, docinho?* (Vira-se.) *É melhor você ir antes que eu comece a soluçar.*}
{2403}{}{Tchauzinhuuu}
{3000}{}{Vem cá, }
{3001}{}{! O bebê precisa de um par de sapatos novo!}
{3002}{}{! O papai precisa de um rifle de plasma novo!}
{4000}{}{Parece que tem alguém bloqueando a máquina.}
{5000}{}{Enganar a máquina pra que ela te dê todo o dinheiro dela.}
{5001}{}{A máquina parece congelar e então você ouve um leve estrondo enquanto uma avalanche de moedas começa a cair do dispensador.}
{5002}{}{[Recolher o dinheiro e ir embora.]}
