{100}{}{Você vê: Baka.}
{101}{}{Você vê uma mulher.}
{102}{}{Crypts não deveriam estar aqui, deveriam, rapazes? [Os outros Tolos balançam a cabeça.] Acho que você deveria ir embora.}
{103}{}{Cometi um erro ao me juntar aos Crypts. Quero estar do seu lado.}
{104}{}{Vim com uma mensagem do Phrax.}
{105}{}{Vou querer, obrigado.}
{106}{}{Então devemos vestir o manto de um traidor? Alguém que entregaria os próprios? Nenhum cão é tão baixo quanto você.}
{107}{}{Sinto que seu manto pode virar de novo, mas suas palavras me convencem.}
{108}{}{O Phrax não é corajoso o bastante pra dizer esta mensagem com a própria voz? Ele não é homem, disso eu sei. E manda este rapaz pra dizer as palavras dele. Bom, então, diga-as e acabe logo.}
{109}{}{Die.}
{110}{}{Ele disse pra você sair da cidade e não será morto.}
{111}{}{Ele disse pra ter um bom dia.}
{112}{}{Hahaha! Gosto de um homem com senso de humor. Você pode viver. Desculpa, só brincadeira.}
{113}{}{Acho que você não entende bem as consequências do que acabou de dizer. Espero que as aprenda antes que seus ossos sequem no sol do deserto. Infelizmente, acho que você não tem muito tempo.}
{114}{}{O que temos aqui? Ouvimos que havia alguém novo na cidade. Deve ser você, todos os outros parecem tão familiares. Permita-me apresentar. Sou Baka, Rainha dos Tolos.}
{115}{}{Por que vocês se chamam de Tolos?}
{116}{}{Ouvi dizer que os Crypts e vocês estão tendo algumas dificuldades.}
{117}{}{Você me parece uma tola.}
{118}{}{Depois da Guerra, só os Tolos restam. Se eu fosse corajosa o bastante, teria tirado minha própria vida anos atrás. Em vez disso, bajulo os deuses do acaso que sobraram.}
{119}{}{Compreensível. Mais ou menos concordo com isso. Posso entrar?}
{120}{}{Bem que a gente precisa de mais uma mão. Deixa eu pensar nisso. [Ela leva a mão ao queixo e desfila pela sala dramaticamente.]}
{121}{}{Cuidado com as palavras que você escolhe. Nem todos são tão indulgentes quanto eu. Eu faço o papel, ou o papel me faz, mas sempre há espaço pra mais um cadáver dar vida ao drama.}
{122}{}{Não tenho certeza, isso foi uma ameaça?}
{123}{}{Vou tentar me comportar.}
{124}{}{Foi, e agora está entre as últimas palavras que você vai ouvir.}
{125}{}{Ótimo, veja que assim seja.}
{126}{}{O que você quer agora?}
{127}{}{Quero entrar pra sua gangue.}
{128}{}{Por que você quer o Gerador de Energia?}
{129}{}{Não sei se devo confiar em você. Prove seu valor.}
{130}{}{Essa galinha entra num bar...}
{131}{}{Sou o melhor lutador daqui.}
{132}{}{Você bem que precisa de um bom homem por aqui.}
{133}{}{[Minutos se passam enquanto você termina sua piada. Com um sorriso nervoso, você encara os olhos dela. Ela ri.] Gostei de você. Você provou que entende a Piada. Agora você é um Tolo. Nos traia e morra.}
{134}{}{Isso a gente vai ver.}
{135}{}{Skippy? Sua vez.}
{136}{}{Só uma coisa separa Scrapheap do ermo: o fedor de esterco de Brahmin. Mas sem esse esterco, não haveria gerador de energia.}
{137}{}{Por que vocês não o controlam?}
{138}{}{Obrigado!}
{139}{}{Porque os Crypts controlam! Eles nos superam em número por enquanto, mas se você se juntasse a nós, poderíamos derrotá-los.}
{140}{}{Claro. Eu entro.}
{141}{}{Não, obrigado.}
{142}{}{Você é um Tolo. Achou que eu deixaria você entrar tão fácil?}
{143}{}{Sim.}
{144}{}{Ãh, não!}
{145}{}{Ah, tá. Você está dentro. Agora você é um Tolo. Nos traia e morra. Blá-blá-blá.}
{146}{}{Você mente!}
{147}{}{Bom, como é ser um Tolo?}
{148}{}{Estou gostando.}
{149}{}{Ótimo! O que eu faço agora?}
{150}{}{Como consigo uma dessas armaduras maneiras?}
{151}{}{É bom mesmo. Poucos conseguem mergulhar nas profundezas humorísticas da plena Tolice.}
{152}{}{É, sim. Obrigado. É, e agora?}
{153}{}{Hmm, sim. Boa pergunta. Bom, suponho que devamos planejar nosso ataque aos Crypts. Temos que assumir o controle daquele gerador de energia, ou tudo está perdido.}
{154}{}{O que você quer que eu faça?}
{155}{}{Bom, já que você é o membro mais novo dos Tolos, e portanto o mais descartável, quero que você espione o inimigo e reporte.}
{156}{}{Tá.}
{157}{}{E então, devemos atacar?}
{158}{}{Sim!}
{159}{}{No!}
{160}{}{Então por que você me incomoda? Faça seu trabalho e reporte o mais rápido possível!}
{161}{}{Excelente! Tolos! Vamos à batalha!}
{162}{}{Você é um Tolo em liberdade condicional dupla-secreta. Você não ganha a armadura de Tolo até passar da condicional.}
{163}{}{[pronto]}
{164}{}{[mais]}
{165}{}{Os Crypts serão enterrados mais uma vez!}
{166}{}{Pereça, escória!}
{167}{}{Quem disse que vocês podiam sair das suas covas? Voltem!}
{168}{}{Ãh, nada.}
{169}{}{Você mente! Vá ao seu trabalho antes que eu abra uma lata de porrada em você!}
{170}{}{Acho que não estou pronto.}
{171}{}{É, tá. Adeus.}
{172}{}{Só os Tolos restam! Agora eu, Rainha Baka, governo o Scrapheap.}
{173}{}{Você será como um Tolo, mas escute bem e marque estas minhas palavras: se você nos trair como trairia seus antigos companheiros, então morrerá - com uma careta, não com um riso.}
{174}{}{E não, você não vestirá o manto de um Tolo. Você vestirá o manto de traidor, e meu garrote será seu par.}
{175}{}{Sim, você pode ser o próximo bobo da corte dos Tolos. Bem-vindo aos Tolos. Nos traia e morra.}
{176}{}{E sem aquele gerador de energia, não há motivo pra estar neste chiqueiro. O gerador fornece luz, calor e até algumas experiências de arrepiar.}
{177}{}{Vá reunir informações ou algo assim, e traga notícias do inimigo. [Ela faz um gesto dispensando você com a mão.]}
{178}{}{Deuses da fortuna, deuses do destino. Não me importo, contanto que eu dê a última risada. Não podemos nos juntar à morte, então rimos dela.}
{179}{}{O Phrax não é corajoso o bastante pra dizer esta mensagem com a própria voz? Ele não é homem, disso eu sei. E manda você pra dizer as palavras dele. Bom, então, diga-as e acabe logo.}
