{100}{}{Você vê um membro devoto das Crianças da Catedral.}
{101}{}{Nós oferecemos a cura do corpo para curar o espirito. Eu posso ajudar você?}
{102}{}{Sim. Ajude-me.}
{103}{}{Quem são vocês?}
{104}{}{Uhn.}
{105}{}{Esta tudo bem, minha criança. Nós examinaremos você agora.}
{106}{}{Abencoados são os meek da mente. Não há nada errado com você,
 minha criança. Vá correr e brincar.}
{107}{}{Você foi curado. Seja mais cuidadoso no futuro.}
{108}{}{Você esta ferido.}
{109}{}{Você não esta ferido. Isso e bom.}
{110}{}{Eu vejo que você esta envenenado.}
{111}{}{Hmm, um pouco de envenenamento por radiação. Infelizmente, nós não podemos curar isso.}
{113}{}{Nós pedimos uma doacao de $}
{114}{}{ antes que nos possamos curar você. Isto e aceitavel?}
{115}{}{Sim.}
{116}{}{Não.}
{117}{}{Mas eu não tenho esse tipo de dinheiro!}
{118}{}{Você aceita $}
{119}{}{?}
{120}{}{As Crianças não haggle. Agora, você aceitara nosso preço?}
{121}{}{Sim, claro que eu aceitarei}
{122}{}{Não, obrigado a você.}
{123}{}{Obrigado a você, meu filho. Deixe-nos rezar pela sua cura.}
{124}{}{Obrigado a você, minha filha. Deixe-nos rezar pela sua cura.}
{125}{}{Ai vai você. Que a paz e as bencaos das Crianças vao com você.}
{126}{}{Você não tem dinheiro o bastante. Se você doar tudo que você puder, nos
 curaremos você. Isto e aceitavel?}
{127}{}{Sim.}
{128}{}{Não.}
{129}{}{Se você doar tudo que você tem, nos curaremos você. Isto e aceitavel?}
{130}{}{Sim.}
{131}{}{Não.}
{132}{}{Você tem mais do que o bastante pra fazer a doacao. Você precisa de
 estudo de matematica, minha criança.}
{133}{}{Nós somos as Crianças da Catedral. Nós vivemos e trabalhamos entre aqueles
 infelizes vivendo na terra devastada. Se você um dia for até a Boneyard, passe
 na Catedral.}
{134}{}{Obrigado a você.}
{135}{}{O que vocês fazem?}
{136}{}{Nós somos os curadores e professores da paz. Nós curamos o corpo pra curar
 o espirito. Tudo que nos pedimos é uma pequena doacao pra pagar pelos nossos
 suprimentos de cura.}
{137}{}{Soa como uma boa ideia pra mim.}
{138}{}{Soa como um monte de bosta se você me perguntar.}
{139}{}{Nós não pedimos pra você. Eu posso dizer que você esta cansado de escutar
 sobre as nossas crencas. Se você precisar de algo mais, nos estaremos aqui.}
{140}{}{É a mais santa das ideias, Nós estamos trabalhando em direção a ultima
 paz na terra devastada. Todas as criaturas viverao como uma.}
{141}{}{Obrigado a você. Bom dia.}
{142}{}{Nós não temos tempo pra falar. Nós estamos saindo. Este lugar e
 perigoso para nos.}
{143}{}{Por que você esta fazendo isto? Nós não faremos nenhum mal a você!}
{980}{}{Não sei nada sobre isso.}
{981}{}{Desculpe. Nem ideia.}
{982}{}{Nunca ouvi falar.}
{1000}{}{Catedral}
{1001}{}{Mutantes}
{1002}{}{Mestre}
{1003}{}{Boneyard}
{1004}{}{Seguidores}
{1005}{}{Chip}
{1006}{}{Apocalipse}
{1007}{}{Necropolis}
{1008}{}{Set}
{1009}{}{Bacia Hidrografica}
{1010}{}{Hall}
{1011}{}{Unity}
{1012}{}{Buy|Buying|Sell|Selling|Barter|Trade|Trading|Comprar|Vender|Trocar|Negociar|Comerciar}
{1013}{}{Water}
{1014}{}{Vault|Vault12|Vault 12|Cofre}
{1015}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Ermo|Terra Devastada|La fora}
{1016}{}{Direction|Directions|Whereto|Where to|Direcao|Onde|Para onde|Caminho}
{1017}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev|Roubo|Ladrao|Furto}
{1018}{}{Holy Flame}
{1019}{}{Fallout|Fall out|nuclear fallout|Radiation|Rads|Radiacao|precipitacao nuclear}
{1020}{}{Rippers|Ripper|Estripador}
{1021}{}{Blades|Blade|Lamina|Laminas}
{1022}{}{Gun Runners|Gunrunners|Gun Runner|Gunrunner|Contrabandistas de Armas}
{1023}{}{Adytum}
{1100}{}{Esses somos nos.}
{1101}{}{Elas são pessoas que sofreram mutacao da poeira nuclear.
 Mas eles ainda são pessoas boas.}
{1102}{}{Nós todos temos mestres, não temos?}
{1103}{}{A boneyard e um solo de criacao do odio. Existem os Seguidores
 do Apocalipse, as gangues: Os Rippers, Os Blades, os Gun Runners e um
 pequeno acampamento chamado Adytum.}
{1104}{}{Eles são as pessoas que procuram destruir a paz da qual o
 Mestre esta tentando implementar.}
{1105}{}{Eu não tenho pista do que você esta falando.}
{1106}{}{Eles são as pessoas que procuram destruir a paz da qual o
 Mestre esta tentando implementar.}
{1107}{}{Isso e aqui. Os restos tristes de um mundo antigo.}
{1108}{}{Eu acredito que ele e um dos ghouls.}
{1109}{}{Isso e direto pra lá a nordeste.}
{1110}{}{Eu não sei nada sobre isso.}
{1111}{}{Todos nós somos parte da Unidade. É o amor e a paz que transmitimos ao nosso próximo, seja ele humano ou mutante.}
{1112}{}{Talvez a gente possa ceder alguns suprimentos.}
{1113}{}{Claro que vamos compartilhar... por uma pequena doação.}
{1114}{}{Os ghouls às vezes falam sobre os velhos tempos. Porém, eu não sei nada sobre isso.}
{1115}{}{Se você é mesmo um crente, a Chama Sagrada vai te guiar pelo ermo até a segurança.}
{1116}{}{Meu filho, não há nenhum outro lugar pra ir?}
{1117}{}{Você não deveria pensar em tamanha maldade, meu filho.}
{1118}{}{A Chama Sagrada e aquela que nos levera para um bravo novo mundo
 o qual não tem odio ou guerra.}
{1119}{}{A precipitação nuclear. Ela traz a morte sobre todos nós.}
{1120}{}{Uma das gangues do Boneyard. Da última vez que ouvi, foram exterminados por algo ou alguém.}
{1121}{}{É uma gangue do Boneyard.}
{1122}{}{Uma das gangues do Boneyard.}
{1123}{}{É um pequeno assentamento no Boneyard.}
