{100}{}{Você vê: Alex, o Regulador do turno da noite.}
{101}{}{Vamos, entre, }
{102}{}{Lamento, eu não posso deixar você entrar. Volte pela manhã.}
{103}{}{Alto! Quem vem lá?}
{104}{}{Eu sou apenas um viajante. Eu gostaria de entrar.}
{105}{}{Não é da sua conta.}
{106}{}{Um, lamento. Eu sairei.}
{107}{}{Estranhos não são permitidos dentro das paredes de Adytum, por ordem do prefeito.}
{108}{}{Eu apenas preciso de um lugar para dormir a noite.}
{109}{}{Eu lamento, mas eu não posso deixar você entrar. Vire-se e saia ou eu terei
 que atirar.}
{110}{}{Olha, é meu dever é minha honra servir como o vigia da noite para Adytum,
 então é da minha conta. Você vire-se e saia, ou a coisa vai ficar séria.}
{111}{}{Saia da minha frente, John Law.}
{112}{}{Tente voltar pela manhã.}
{113}{}{Ah, já basta. Agora as lutas estão de fora!}
{114}{}{Nghgh.}
