{100}{}{Você vê um cão. Ele parece estar te seguindo.}
{101}{}{Você vê um cão.}
{102}{}{Woof!}
{103}{}{Grrr!}
{104}{}{Parece que você fez um amigo deste cachorro.}
{105}{}{Você ganha 200 de experiência por fazer amizade com o cão.}
{106}{}{Você ganha 335 de experiência por derrotar o cão e deixar o Phil voltar pra casa dele.}
{107}{}{Vem cá, garoto.}
{108}{}{Ruff. Ruff.}
{109}{}{Por algum motivo, este cão gosta de você.}
{110}{}{Você vê: Dogmeat.}
{111}{}{Arf! Arf Arf! Arf! Arf! Arf! Arf! Arf! Arf!}
{112}{}{[Sniff. Sniff.] Grrrr! Snarl!}
{113}{}{[Sniff. Sniff] Woof!}
{114}{}{ de experiência por ajudar o Phil a resolver seu dilema canino.}
{115}{}{O cão parece achar que você é o dono dele.}
{116}{}{ de experiência por ajudar o Phil a resolver seu dilema canino.}
{117}{}{Woof-woof!}
{118}{}{Vem, parceiro.}
{119}{}{Fica aqui e espera, tá?}
{120}{}{Bom cão.}
{121}{}{Puppie!!!}
{122}{}{Woof?}
{123}{}{Arf?}
{300}{}{Cachorro!! cachorro ser amigo?}
{301}{}{cachorro Fica! num move!}
{304}{}{Bom cachorro!}
{302}{}{Sai do caminho, parceiro. Bom garoto.}
{303}{}{ Vira-lata burro!}
