{100}{}{Você vê Mitch da loja All-N-One.}
{101}{}{Como eu posso ajudar você hoje?}
{102}{}{Eu gostaria de comprar algo.}
{103}{}{Eu gostaria de vender algo.}
{104}{}{Nada. Obrigado.}
{105}{}{Runk.}
{106}{}{Ótimo. Aqui está o que eu tenho.}
{107}{}{Ótimo, sempre procurando novas coisas.}
{108}{}{Lamento, eu não consigo entender você. Volte quando você obtiver cérebro novo.}
{109}{}{Obrigado. Volte sempre.}
{110}{}{Você vê Jake, o Negociante de Armas.}
