{100}{}{Você vê Alya, uma saqueadora do deserto.}
{101}{}{Eu sou Alya dos Khans. Como eu poderia ajudar você hoje?}
{102}{}{Eu estou procurando por uma mulher chamada Tandi. Você viu ela?}
{103}{}{Que tal um beijinho?}
{104}{}{Por que seu bando de saqueadores atacou Shady Sands?}
{105}{}{Não, obrigado.}
{106}{}{Uhu!}
{107}{}{Se ela é uma dessas mulheres de Shady Sands, talvez você devesse procurar lá.
 Agora vá, eu preciso terminar de afiar minhas facas. }
{108}{}{Beije isto!}
{109}{}{Nós não atacamos aqueles que são de Shady Sands. Nós somos da mesma origem.
 É apenas certo que eles compartilhem conosco o que é deles!}
{110}{}{Mas você esta ferindo suas crianças e os aterrorizando.}
{111}{}{Isso me parece.}
{112}{}{Uh, sim. Eu acho que eu irei agora.}
{113}{}{Você soa tão fracote como eles. Olha, se eles estivessem com qualquer problema
 de fome, então seria culpa deles por não planejarem a longo prazo.
 Considere o que nós fazemos como uma troca de talentos.}
{114}{}{Uma troca de talentos?!? Como isto pode ser uma troca de talentos? Vocês não
 dão nada a eles.}
{115}{}{Com certeza, e galinhas tem 3 pernas.}
{116}{}{Uh, sim. Eu acho que eu irei agora.}
{117}{}{Eu lamento, mas eu não consigo entender você. Eu estou afiando minhas facas e não
 gostaria de ser incomodada.}
{118}{}{Nós damos a eles a coisa mais importante possível. Nós damos excitação as suas
 vidas pacatas.}
{119}{}{Eu não acho que eles querem seu tipo de excitação.}
{120}{}{Eu acho que eu farei as vidas deles entediantes de novo. Eu começarei com você!}
{121}{}{Uh, sim. Eu acho que eu irei agora.}
{122}{}{Eu não perguntei. Mas já que você não tem qualquer conceito de diversão,
 eu acho que eu encerrarei sua existência.}
{123}{}{Zombar de mim não é um bom presságio. Eu sugiro a você que deixe minha presença.}
{124}{}{Maldito justo. Agora saia da minha frente.}
{125}{}{Eu estou ocupada agora me preparando para nosso próximo saque.}
{200}{}{You see: Alya, one of Garl's advisors.}
