{100}{}{Você vê a Jade.}
{101}{}{Você vê a Beca.}
{102}{}{}
{103}{}{}
{104}{}{Você vê um membro dos Blades.}
{105}{}{Você vê um membro dos Blades.}
{106}{}{Você acha que poderiam ser Livros.}
{107}{}{Você acha que poderiam ser Cicatrizes.}
{108}{}{Você acha que poderia ser Gunner.}
{109}{}{Você acha que poderia ser Twitch.}
{110}{}{Você acha que poderia ser Hammer.}
{111}{}{Você acha que poderia ser Razor.}
{112}{}{Estes são os quartos de dormir. Agora saia daqui antes que eu chute sua bunda.}
{113}{}{Tente.}
{114}{}{Lamento sobre isso. Tchau.}
{115}{}{Posso ficar aqui?}
{116}{}{Não. Estes são paras os Blades de verdade, não para alguma bicha.}
{117}{}{Ei, homie! Qual a boa? fique here se você precisa de um lugar seguro.}
{118}{}{Então, você se ofereceu pra ajudar. Melhor que nada, eu acho. Obrigado. Vou espalhar a notícia.}
{119}{}{É, vou lá ver o que consigo fazer.}
{120}{}{Oi de novo. Ouvi dizer que você realmente nos ajudou. Você é mais que digno do nosso respeito, de fato. Estamos livres agora. (Você agora é membro da gangue das Blades.)}
{121}{}{Não posso te ajudar com isso. Vá falar com o Razor.}
