{100}{}{Você vê uma mulher de aparência gentil num uniforme de médica.}
{101}{}{Você vê: Lorri, a Médica-Chefe das instalações médicas da Brotherhood.}
{102}{}{Olá, como posso ajudar?}
{103}{}{Estou ferido.}
{104}{}{Estou irradiado.}
{105}{}{Você faz operações?}
{106}{}{Me fale de novo sobre as operações.}
{107}{}{Ocê conserta?}
{108}{}{Você está ferido? Deixa eu ver...}
{109}{}{Era esse o problema. Pronto. Tome mais cuidado lá fora.}
{110}{}{Desculpe, não posso te ajudar se você não me disser o que há de errado.}
{111}{}{ Você parece bem.}
{112}{}{Pronto. Espero que se sinta melhor.}
{113}{}{Pronto, mas pare de se meter em tanta briga!}
{114}{}{Isso deve resolver, tudo consertado.}
{115}{}{Novo em folha.}
{116}{}{Tudo melhor!}
{117}{}{Radiação é muito perigosa; você deveria ter mais cuidado.}
{118}{}{Não tenho tempo pra brincadeiras.}
{119}{}{Claro, mas é muito caro e demorado.}
{120}{}{Details?}
{121}{}{Certo, deixa pra lá.}
{122}{}{Bom, eu posso te deixar mais forte, mais perceptivo, aumentar sua resistência, ajudar a melhorar seu aprendizado e aumentar sua destreza. Também estudei procedimentos de cirurgia plástica. Sobre qual você quer mais informação?}
{222}{}{Bom, eu posso te deixar mais forte, mais perceptivo, aumentar sua resistência, ajudar a melhorar seu aprendizado e aumentar sua destreza. Sobre qual você quer mais informação?}
{124}{}{Quem é você?}
{125}{}{Meu nome é Lorri. Lidero a equipe médica e realizo todas as grandes cirurgias e procedimentos médicos. Sou praticamente a única Médica aqui, então prefiro tratar as coisas de forma informal. E você é?}
{126}{}{Certo, sobre qual operação você quer conversar?}
{127}{}{Strength.}
{128}{}{Perception.}
{129}{}{Endurance.}
{123}{}{Charisma.}
{130}{}{Intelligence.}
{131}{}{Agility.}
{132}{}{Deixa pra lá.}
{133}{}{Essa é fácil de fazer, mas tem um longo tempo de recuperação. Custa apenas }
{134}{}{I'm }
{135}{}{Eu topo!}
{136}{}{Passo.}
{137}{}{Bom, essa é uma operação difícil. Custa }
{138}{}{É um prazer conhecer você, Irmão }
{139}{}{Essa aqui não é tão difícil. Leva cerca de uma semana e vai custar }
{140}{}{Fui envenenado!}
{141}{}{Essa é a mais complexa e perigosa! Vai levar 3 semanas e custa }
{142}{}{ Agora, o que posso fazer por você?}
{143}{}{Essa operação não é tão difícil, mas é muito cara e demorada. Vai levar 3 semanas e custar }
{144}{}{[Continuar]}
{145}{}{Essa operação é moderadamente difícil, com um longo tempo de recuperação. Vai custar }
{146}{}{Certo, pronto. Espero que a espuma não tenha irritado sua pele.}
{147}{}{Sinto muito, mas não posso te ajudar se você não tem o dinheiro.}
{148}{}{Sinto muito, mas você é de fora. Depois de uns dez anos na Brotherhood, eu poderia fazer a operação de graça, mas temos despesas e você ainda não é um membro regular da Brotherhood.}
{149}{}{Me avise quando tiver os fundos necessários pra esta operação.}
{150}{}{Não consigo avaliar com precisão sua força física enquanto você está usando Power Armor. Por favor, tire-a e fale comigo de novo.}
{151}{}{I'm }
{152}{}{.}
{153}{}{Você quer perguntar sobre outra?}
{155}{}{Barriga sente mal!}
{157}{}{Hep?}
{158}{}{Olá de novo, como posso ajudar?}
{154}{}{Certo, lá vai... Brincadeira. Podemos começar agora mesmo. (Você inala o anestésico e lentamente apaga)}
{156}{}{E então, como estamos nos sentindo? (Você já percebe a diferença) Você é bem tagarela dormindo. Está liberado! Bom dia.}
{159}{}{Fora o velho e entra o novo... Cadê meu alicate? (Você despenca como uma pedra num abismo)}
{161}{}{Hmmm. Você está exatamente igual, mas como se sente? (Seus sentidos parecem muito mais aguçados) Bom, você está ocupando um leito valioso. Pode ir!}
{164}{}{Espero que você tenha coração... (Ela te dá uma piscadela enquanto você apaga)}
{166}{}{Bom, você parece um pouco mais parrudo agora. (Você se sente ótimo!) Me avise se houver algum problema, e não vá nadar por pelo menos uma hora.}
{180}{}{Espero que você não acabe com um olho vesgo feito o último... (Você luta pra resistir às drogas, mas são poderosas demais)}
{181}{}{Nossa, nossa, você está deslumbrante. Me superei de verdade. (Ela te olha de cima a baixo algumas vezes e então parece cair em si) Ah, desculpe, você está liberado agora.}
{182}{}{Obrigado!}
{185}{}{Não tão deslumbrante quanto você.}
{168}{}{Onde mesmo está o cérebro? Pra que serve essa coisa? (Você tenta resistir às drogas, mas é uma batalha perdida)}
{170}{}{Bom, parece que coloquei tudo de volta. Tudo parece estar funcionando bem. (É como se os caminhos dos seus pensamentos tivessem ligações diretas com tudo na sua cabeça, e suas memórias estão muito mais nítidas)}
{174}{}{Certo, vamos dar uma testada. Tente não se contrair. (As drogas são tão... amigáveis. Seu sono vem rápido)}
{176}{}{Certo, você está pronto pra ação. (Você move os membros e sente a velocidade e o controle aumentados) Tudo o que peço é que, por favor, não danifique minha obra-prima.}
{200}{}{Você vê a assistente da Médica.}
{233}{}{ de vale, mas leva 3 semanas pra cicatrizar.}
{237}{}{ de vale, mas a recuperação dessa operação é de só uma semana.}
{239}{}{ script.}
{241}{}{ script.}
{243}{}{ script.}
{245}{}{ de vale e leva 3 semanas pra cicatrizar.}
{279}{}{Você deveria falar com a Médica.}
{280}{}{Ela é a Médica, não eu.}
{281}{}{Estou só em treinamento.}
{282}{}{Não posso te ajudar, oficialmente.}
{283}{}{A Lorri é a Médica.}
{284}{}{Você tem que perguntar à Médica.}
{285}{}{Não se preocupe, ela só está de brincadeira.}
{286}{}{Ela só gosta de provocar, não se preocupe.}
{500}{}{Sinto muito, mas esta operação não vai te ajudar.}
{400}{}{Hmmm. Se alguém aqui precisa de um aumento de inteligência, é você. Aliás, faço por 3000 de vale, em vez dos 6000 que você normalmente precisaria pra operação. Não posso garantir que vá ajudar, mas acho que valeria a tentativa. Também vai levar 3 semanas de recuperação. Só que você provavelmente não está entendendo isso, né?}
{401}{}{Eu querer Esperto.}
{402}{}{Não querer! Médicos é assustador...}
{403}{}{Muito bem, então. Você está irradiado ou machucado? Vou te ajudar se puder.}
{404}{}{eu Dói.}
{405}{}{cAbelo caindo Fora!}
{406}{}{Nã-ã.}
{407}{}{Certo. Você acordou. Deixa eu ver. Você se sente mais esperto?}
{408}{}{Hã?}
{409}{}{Sim!}
{410}{}{Droga! Foi um fracasso. Bom, eu não tinha muito com que trabalhar. Desculpe, você é só um idiota e provavelmente vai continuar um idiota. Só podemos fazer a operação uma vez, lamento dizer.}
{411}{}{Fantástico, foi um sucesso! Consegui aumentar seu QI a um nível aceitável. Como é ter meio cérebro?}
{412}{}{É ótimo. Obrigado, Doutora. Tchau.}
{413}{}{Pronto. Tudo melhor.}
{502}{}{Que outras operações você pode fazer?}
{503}{}{Bom, tecnicamente eu não deveria falar sobre isso, mas temos outros procedimentos disponíveis. Aviso que alguns deles são muito perigosos e têm risco de efeitos colaterais, enquanto outros são bem seguros, mas têm um tempo de recuperação extremamente longo. Você quer mais informação?}
{504}{}{Ah, sim, deixa eu ver aqui...}
{300}{}{Fofo, mas não estou interessada. Volte se precisar de atendimento médico.}
{301}{}{Sem ofensa, querida, mas você está um pouco abaixo dos meus padrões. Mas fico lisonjeado.}
{302}{}{Ah, muito obrigada. (Ela cora) Eu não recebo muitos elogios. Ser Médica da Brotherhood é, na maior parte, um trabalho estressante e ingrato. Gosto de brincar, pra me manter animada e distraída.}
{303}{}{Eu entendo. Não ajudaria botar pra fora um pouco de vez em quando?}
{304}{}{De nada. Tchau!}
{305}{}{Bom... às vezes eu me sinto sozinha, e você não tira 'férias' quando é a única médica da Brotherhood. Ah, mas o que estou dizendo? Isso é tão bobo.}
{306}{}{Você devia engolir o choro. Tenha orgulho do seu trabalho e o resto vem.}
{307}{}{A vida é curta e depois a gente morre. Você não quer aproveitá-la enquanto dura?}
{308}{}{Não é nada bobo. (Toca de leve o rosto dela, então se aproxima e a beija)}
{309}{}{Sim, acho que você tem razão. (Ela balança a cabeça e suspira, depois se recompõe e sorri) Bom, de volta ao trabalho! Obrigada pelo elogio.}
{310}{}{(Ela pensa por um instante) Você tem razão. E eu quero. Me dê uns dez minutos - preciso preparar a mesa de exames. (Ela sorri maliciosamente e morde o lábio inferior)}
{311}{}{(Ela pega sua mão e te leva até o quarto dela...)}
{312}{}{Isso foi lindo. Eu... acho que estou apaixonada por você. (Ela dá uma risadinha) Brincadeira! Certo, hora de ir. Tenho trabalho a fazer.}
{313}{}{Ah, uau. Fazia anos que ninguém me pegava desse jeito. Acho que vou ficar dolorida por uma semana, mas valeu a pena. (Ela te olha com desejo) Vamos repetir isso em breve!}
{315}{}{Com certeza. Até mais.}
{314}{}{E aí, gato. A fim de mais diversão?}
{316}{}{O que você está faze- ... (Ela se assusta a princípio, mas logo se derrete no seu abraço e retribui o beijo com ternura, gemendo baixinho. Conforme o beijo fica mais apaixonado, ela para e se afasta) Vem comigo. (Ela se levanta e te leva aos aposentos dela...)}
{317}{}{Sim! Você me faz sentir tão bonita e desejada.}
{318}{}{(Ela sorri e pega sua mão...)}
{319}{}{Bom, eu bem que preciso revisar minhas aulas de anatomia... (Ela pisca)}
