{100}{}{É um animal domesticado.}
{101}{}{Não há nada natural a respeito destas vacas. A segunda cabeca
 só pode ser o resultado de alguma mutacao estranha.}
{102}{}{Parece normal pra você.}
{103}{}{Moo.}
{104}{}{O animal te ignora.}
{105}{}{O animal grunhe, mas de resto não responde.}
{106}{}{Uma vaca mutante de duas cabeças. Esta é um animal selvagem.}
{107}{}{Parece bem normal pra você.}
{108}{}{Não há nada de natural nessas vacas. A segunda cabeça só pode ser resultado de alguma mutação estranha.}
{109}{}{Moo.}
{110}{}{Moo!}
{111}{}{Muu, eu digo.}
{113}{}{Você enfureceu a vaca por atacar a amiga dela.}
{201}{}{Mooo...}
{202}{}{Muuu Muuu Muuu...}
{203}{}{Mooo...}
{204}{}{Moooooo...}
{205}{}{Mooooooooo...}
{206}{}{:: GRUNT ::}
{210}{}{Você se tornou um expert em expedir excremento!}
