{100}{}{Você vê o Butch.}
{101}{}{Me diga sobre si próprio.}
{102}{}{Ouviu quaisquer bons rumores?}
{103}{}{O que mais esta por aqui, alem do Hub?}
{104}{}{O que esta não Hub?}
{105}{}{Obrigado, isso e tudo.}
{106}{BUTCH01}{O que você quer?}
{107}{}{Eu preciso fazer algumas perguntas pra você.}
{108}{}{Nada, obrigado.}
{109}{BUTCH02}{Tempo e dinheiro. Papo-furado não é dinheiro. Você aqui a respeito do trabalho ou o que?}
{110}{}{Sim.}
{111}{}{Qual trabalho?}
{112}{}{Aqui pelo o que ou pelo dinheiro?}
{113}{BUTCH03}{Maldicao quente, alguém com coragem! Feito e feito. Vá falar com o meu segundo, Rutger, e obtenha os detalhes.}
{114}{}{Espere! Eu tenho algumas perguntas sobre este trabalho primeiro!}
{115}{}{Certo, obrigado.}
{116}{BUTCH04}{Ahh, não espalhe! Faca-os rapido.}
{117}{}{Quanto paga?}
{118}{}{Uh . . . qual é o trabalho?}
{119}{}{Bem, se você se sente desse modo, eu simplesmente irei falar com o Rutger.}
{120}{BUTCH05}{Uh . . . Rutger manejara isso. Ele faz toda a coisa trivial para os Far Go Traders. Agora saia, por que eu tenho trabalho pra fazer!}
{121}{}{Uma pergunta mais, ok?}
{122}{}{Certo, obrigado.}
{123}{BUTCH06}{Apenas uma. }
{124}{}{ [Você nota que ele parece tenso.]}
{125}{}{Uh . . . qual é o trabalho?}
{126}{}{Há um tempo limite não trabalho?}
{127}{}{Uh, de novo, quanto ele paga?}
{128}{}{Simplesmente quao estúpido e você?}
{129}{}{Você parece tenso. Quer falar a respeito?}
{130}{BUTCH07}{Mas que . . . você concordou com um trabalho sem saber o que e? Maldicao quente, você deve estar desesperado. Eu gosto disso!}
{131}{}{Apenas me diga o que e, ok?}
{132}{}{Bem, você parece bem desesperado, tambem, então nos estamos quites.}
{133}{BUTCH08}{Bem, algumas caravanas estão desaparecendo de nos ultimamente. Maldicao se alguém pode imaginar o que aconteceu com elas.}
{134}{}{Então o que você quer que eu faca?}
{135}{}{Eu aposto que você nem ao menos procurou por elas.}
{136}{BUTCH09}{Simples. Descubra quem o esta fazendo e me diga. Ou os destrua. Não faz uma maldita diferenca pra mim. Apenas faca o trabalho feito!}
{137}{}{Quaisquer pistas de quem esta fazendo isto?}
{138}{}{Eu os destruirei.}
{139}{}{Soa assustador . . . melhor eu passar.}
{140}{BUTCH10}{Nah. Apenas a coisa normal.}
{141}{}{Ah vamos. Tem que haver algo que eu possa usar.}
{142}{butch11}{Escute, eu não tenho tempo para trocar estorias com você.}
{143}{butch12}{Bem há uh . . . alguma coisa, mas eu nunca escuto a esses rumores.}
{144}{}{Bem, eu escuto. O que e?}
{145}{}{Certo, obrigado.}
{146}{BUTCH13}{Você uh . . . você realmente quer ouvir ele, huh? Bem, alguns dizem que é o deathclaw, mas . . . mas Eu não sei nada a respeito disso.}
{147}{}{Você soa assustado.}
{148}{}{Obrigado. Eu posso fazer algumas perguntas pra você?}
{149}{}{Como eu descubro sobre o deathclaw?}
{150}{butch13a}{Como você . . . vá falar com a Beth, ela sabe mais sobre essa bosta.}
{151}{}{Sim, você esta tão assutado quanto um cachorro chicoteado.}
{152}{}{Eu irei verificar.}
{153}{}{Eu preciso de um pouco mais de informação.}
{154}{BUTCH14}{Escute você, eu não estou assustado. Eu sou . . . cauteloso. Melhor você não ser estúpido com o deathclaw. Vá falar com a Beth, ela dira mais a você.}
{155}{}{você soa tão assutado quanto um cachorro chicoteado.}
{156}{}{Lamennnto. Eu irei verificar.}
{157}{}{Eu preciso de um pouco mais de informação.}
{158}{BUTCH15}{Eu estou cansado dos seus insultos seu/sua . . . seu/sua cabeca de prego! Não volte! Rutger, leve este inseto chato pra longe!}
{159}{BUTCH16}{Feito e feito. Agora saia daqui, mas volte e fale pra mim quando você achar alguma coisa.}
{160}{BUTCH17}{Faca-o rapido.}
{161}{BUTCH18}{Então o que diabos eu estou fazendo ainda olhando pra você? Saia!}
{162}{butch19}{Uh . . . o que você disse?}
{163}{}{Eu estava implicado que você estava muito assutado para ir procurar por elas.}
{164}{}{Nada. Então o que você quer que eu faca?}
{165}{BUTCH20}{Você sabe, eu não gosto de você. Mas isso não importa. Você quer o trabalho ou não?}
{166}{}{Com certeza.}
{167}{}{Não, obrigado.}
{168}{BUTCH19}{Uh . . . o que você disse?}
{169}{}{Você me ouviu.}
{170}{}{Nada. Então, o que você quer que eu faca?}
{171}{BUTCH22}{Sim, ontem! Vá!}
{172}{BUTCH23}{Hmmm. O que você quer saber?}
{173}{}{Apenas curioso.}
{174}{}{Nenhuma razão.}
{175}{}{Deixa pra lá. Eu tenho mais algumas perguntas.}
{176}{BUTCH24}{Bem, eu dirigi os Far Go Traders por volta de cinco anos. Antes disso eu estava em Adytum. Antes disso, próximo do Glow.}
{177}{}{Algo mais?}
{178}{}{Bem, obrigado.}
{179}{BUTCH25}{Realmente não.}
{180}{BUTCH26}{Sim, bem, eu não gosto de ir por ai falando sobre minha vida pessoal e tal.}
{181}{}{Ah vamos, por favor?}
{182}{}{Ah, tudo bem.}
{183}{BUTCH27}{O que eu pareco, uma . . . uma . . . uma dessas coisas de turistas? Puxa.}
{184}{}{Não, você parece ser um homem brilhante.}
{185}{}{Eu apenas quero conhecer alguns lugares comuns.}
{186}{BUTCH28}{Obrigado. Agora, há alguma coisa mais?}
{187}{BUTCH29}{Bem, você tem a Old Town e as Alturas, mas isso são apenas casas. No centro tem todas as lojas e tal.}
{188}{}{Quais lojas?}
{189}{}{Obrigado.}
{190}{BUTCH30}{Apenas coisas. Você quer ver a cidade, vá olhar por ai você mesmo!}
{191}{}{Uh, obrigado por nada.}
{192}{}{Obrigado.}
{193}{BUTCH19}{Uh . . . o que você disse?}
{194}{}{Você e surdo?}
{195}{}{Nada. Eu preciso fazer a você mais algumas perguntas.}
{196}{BUTCH32}{Bem, você tem o Maltese Falcon, um lugar bacana para comer,
 acredite você em mim. É então . . . vamos ver, a loja Tudo em Um,
 a loja de armas . . . e, claro, os pedacos de iguana do Bob's.}
{197}{}{Obrigado.}
{198}{}{Algo mais?}
{199}{BUTCH33}{Tem o hospita das Crianças da Catedral no lado oeste do Centro.
 É então, claro, você os Mercadores da Agua ao sul é a Caravana Escarlate
 a oeste.}
{200}{}{Obrigado.}
{201}{BUTCH34}{Bem, você tem Junktown ao norte é a Irmandade
 do Aço a noroeste. É, claro, a Boneyard ao
 sul.}
{202}{}{Algo mais?}
{203}{}{Obrigado.}
{204}{BUTCH35}{Bem, Necropolis esta a leste. Mas uh . . . Eu não cuspiria lá
 se saisse ouro, se você me entende. Aqueles ghouls comem a face de um homem
 mais rapido do que uma senhora velha fazendo compras num dia de barganha.}
{205}{}{Soa como diversão.}
{206}{BUTCH35a}{Puhh. Talvez pra você! Se você gostar disso, então o Glow esta abaixo
 ao sul. É um poco radioativo.}
{207}{}{Talvez eu trabalharei no meu bronzeado.}
{208}{BUTCH36}{Simplesmente um monte de lugares diferentes. Vá descobrir por si próprio!}
{209}{}{Bem, obrigado por nada.}
{210}{}{Obrigado.}
{211}{BUTCH37}{Bem, o que você tem?}
{212}{}{Bem, eu descobri quem esta levando as caravanas.}
{213}{}{Bem, eu sei que não era o deathclaw que levou as caravanas.}
{214}{}{Agora mesmo, nada. Tchau.}
{215}{BUTCH38}{Realmente? Quem?}
{216}{}{Sao estes grandes caras mutantes.}
{217}{}{Ratos! GRANDES ratos com GRANDES dentes . . .}
{218}{BUTCH39}{O q . . . o que os mutantes queriam com as nossas caravanas?}
{219}{}{Eu não sei, mas eles parecem estar levando prisoneiros humanos.}
{220}{}{Eu não sei com certeza. Mas são mutantes, não o deathclaw.}
{221}{BUTCH40}{O que, Eu pareco a crate shy of a load? Você ao menos viu
 o deathclaw?}
{222}{}{Estive lá, vi isso, matei ele.}
{223}{}{Eu estou dizendo a você que não era o deathclaw.}
{224}{BUTCH41}{Você . . . você matou ele? Bem . . . eu uh . . . um . . . uh,
 de onde estes mutantes vieram?}
{225}{}{Eu não sei ainda. Mas eles tem um posto avancado nas montanhas.}
{226}{}{Eles trabalham para o Mestre. Apesar disso, eles não são seus mutantes comuns.}
{227}{BUTCH42}{Um posto avancado? Bem . . . um . . . bem uh. Eu terei que falar com
 o Comite. Sim . . . sim, eles saberao o que fazer. Feito e feito.
 Saia, por que eu tenho coisa pra fazer . . . ok?}
{228}{BUTCH43}{O Mestre? É-Ele e mais um mito do que o deathclaw.
 Você . . . você não acha que ele e de verdade, você acha?}
{229}{}{Eu não tenho certeza. Mas eu pretendo descobrir.}
{230}{}{Sim, eu vi ele! É ele esta vindo pegar você!}
{231}{BUTCH44}{Sim, feito e  . . . sim, você faca isso! Uh, eu preciso
 falar com o Comite. Eles saberao o que fazer. A-A-Agora saia!
 Eu tenho muito pra fazer . . . ok?}
{232}{BUTCH45}{O que! Bem . . . bem . . . eu não estou com medo! Rutger!
 Eu tenho armas! Rutger!}
{233}{BUTCH46}{Tudo bem, então não era o deathclaw. Mas o que os
 mutantes na Cidade Velha queriam com nossas caravanas? A menos que seja
 algum tipo de conspiracao.}
{234}{}{Não, não, não, seu cabeca de prego. Estes mutantes são grandes
 e verdes e eles tem um exercito nas montanhas ao norte.}
{235}{}{Você realmente e estúpido, não e? Você não esta escutando!}
{236}{BUTCH47}{O que? Saia! Eu preciso dizer ao Comite sobre isto.
 Continue, saia!}
{237}{BUTCH48}{Vamos. Você pode fazer melhor do que isso.}
{238}{}{Não, realmente. Eles são este caras mutantes verdes, grandes.}
{239}{}{Você esta certo.}
{240}{}{Ah, vamos. Você acha que uma mulher como eu mentiria?}
{241}{BUTCH49}{Eu não tenho tempo para isto. Saia e não
 volte até que você ache alguma coisa util!}
{242}{BUTCH50}{Bem, então, o que e?}
{243}{}{Realmente, SÃO estes grandes caras mutantes . . . }
{244}{}{Ratos, eu disse a você! Grandes, peludos . . . }
{245}{BUTCH51}{Ratos? Você deve estar brincando comigo.}
{246}{}{Não, realmente, ratos GRANDES!}
{247}{}{Você esta certo. Eu estava apenas brincando.}
{248}{BUTCH52}{Bem . . . ok. Eu direi ao Comite, mas eu não
 acho que eles acreditarao. Embora eu tenha visto ratos grandes por ai . . .}
{249}{BUTCH53}{Como você sabe? Você viu o deathclaw?}
{250}{}{Estive lá, vi isso, matei ele.}
{251}{}{Apenas confie em mim. Eu sei.}
{252}{BUTCH54}{Você . . . você o matou?}
{253}{}{Sim, com certeza matei.}
{254}{BUTCH54a}{Bem então, então quem esta roubando minhas caravanas?}
{255}{}{Eu não sei ainda, mas eu descobrirei.}
{256}{}{Ralph o fez.}
{257}{BUTCH55}{Uhh, faca isso. É volte e me diga  . . . ok?}
{258}{BUTCH56}{Quem diabos e Ralph?}
{259}{}{Deixa pra lá. Eu obterei mais info sobre o problema da caravana.}
{260}{}{Ele esta vindo pela sua alma!}
{261}{BUTCH57}{Ei! Você esta fazendo de mim uma diversão, não esta? Rutger, mostre a este
 panaca a rua! É não volte sem alguma informação verdadeira!}
{262}{BUTCH58}{Sim, certo. Como se eu acreditasse nisso. Saia até que você
 possa me achar algo util.}
{263}{BUTCH59}{Bem, o que você tem pra mim?}
{264}{}{Foram os mutantes.}
{265}{}{Bem, eu sei que não foi o deathclaw que levou as caravanas.}
{266}{BUTCH60}{Deixe-me em paz! Você pegou sua recompensa, agora saia!}
{267}{BUTCH61}{Ei, ponha isso pra baixo!}
{268}{BUTCH62}{Basta. Rutger vai arrancar das suas costas!}
{269}{BUTCH63}{Pare com isso agora mesmo!}
{270}{BUTCH64}{Bem, o que você esta fazendo aqui? Saia!}
{272}{butch65}{Ah . . . bem, não e, então saia!}
{273}{BUTCH66}{Rutger vai transformar você num pretzel humano. Divirta-se. RUTGER!}
{274}{BUTCH67}{Bem, você e brilhante, não e? Aqui esta o trabalho:
 Descubra quem esta roubando minhas caravanas. Dinheiro, grande. Você falha, machucar, grande.
 Entende? Agora saia daqui!}
{275}{BUTCH67a}{Uau, você e burro. Eu não tenho tempo para isto. Vá falar com o Rutger.}
{276}{BUTCH68}{Vá falar com o Rutger. Ele pode dizer mais a você sobre essa bosta.}
{277}{BUTCH69}{Como eu disse a você . . .}
{278}{BUTCH70a}{Como eu disse . . .}
{279}{BUTCH71}{Eu não vou repetir a mim mesmo de novo!}
{280}{BUTCH72}{Escute, eu não vou dize-lo de novo!}
{281}{BUTCH73}{Ele e o dono do Maltese Falcon no lado oeste.
 Eu ficaria longe dele; ele não é honesto, como eu.}
{282}{BUTCH74}{Uh não. Uh não, nós não falamos sobre isso.}
{283}{BUTCH75}{O Maltese Falcon e um clube noturno no lado oeste.
 Hope canta lá. Que boneca.}
{284}{BUTCH76}{Mas que dor eles são. Nós achamos que o esconderijo deles esta na Cidade Velha,
 mas nós não podemos provar.}
{285}{BUTCH77}{Ah, ele e o xerife. Mas se você ver um crime, reporte para mim.
 Justin não governa o roost por aqui.}
{286}{BUTCH78}{O Velho Harold? O que do você quer com aquele mutante velho? Ele esta na Cidade Velha.
 Simplesmente pergunte por lá.}
{287}{BUTCH79}{Aqueles bastardos. Daren Hightower pensa que ele possui o maldito Hub,
 simplesmente por causa da Torre de Agua.}
{288}{BUTCH80}{Ele dirige os Mercadores da Agua. Nasty, bastardo ganancioso e o que ele é.}
{289}{BUTCH81}{Você pode acha-los no limite noroeste do Centro.
 Eles controlavam o hospital antes das Crianças se mudarem.
 Fale sobre trocar o estranho pelo esquisito.}
{290}{BUTCH82}{Ele e o chefe da Crimson Caravan. Se você me perguntar ele esta louco.}
{291}{BUTCH83}{Você não sabe aonde seus proprios pés estão?}
{292}{BUTCH84}{Esse sou eu. Você cego ou algo assim?}
{293}{BUTCH85}{Uh, Beth é a gerente da Loja de Armas.
 Ela ouve muitos rumores, se você esta nesse tipo de coisa.}
{294}{BUTCH86}{Rutger e meu assistente.}
{295}{BUTCH87}{Esta  a sul do Mercado dos Mercadores. A unica fonte de água aqui
 e por muito da area ao redor. Os Mercadores da Agua possuem a maldita coisa.}
{296}{BUTCH88}{Tres das minhas caravanas desapareceram no mes passado.
 A principio eu pensei que eram ou os Mercadores da Agua ou a Caravana Escarlate,
 mas eles tiveram desaparecimentos tambem.}
{297}{BUTCH89}{Esta aonde todos negociam. Smack dab no meio da cidade.}
{298}{BUTCH90}{Uh, não eu-eu não  . . . Vá falar com a Beth, ela sabe mais sobre
 essa bosta.}
{299}{BUTCH91}{O Glow e um poco radioativo bem, bem pra baixo ao sul.
 Radiação demais pra qualquer um viver lá.}
{300}{BUTCH92}{A Old Town esta não lado leste. Os skags ficam por lá.}
{301}{butch93}{Esta não lado oeste.}
{302}{BUTCH94}{Junktown? Sim, eu estive no norte naquele lugar algumas vezes.
 Consegui algumas boas bebidas.}
{303}{BUTCH95}{Junktown? Esta ao norte. Ouvi que eles estão tendo algum problema,
 com o prefeito deles Killian sendo morto e tal.}
{304}{BUTCH96}{Ele e o prefeito de Junktown, isso e tudo que eu sei.}
{305}{BUTCH97}{Eu ouvi que ele esta morto. O que mais você precisa saber?}
{306}{BUTCH98}{Ah, eles são um bando de loucos por armas a noroeste.
 Realmente esquisito. Apesar disso eles fazem uma maldita boa arma.}
{307}{BUTCH99}{Ele lidera a Brotherhood. É tudo que eu sei.}
{308}{BUTCH100}{Bem, é uma grande cidade arruinada ao sul. As Crianças,
 os Seguidores e Adytum estão lá. junto com todas as gangues e tal.}
{309}{BUTCH101}{Por que? O que você ouviu? Eu ouvi que foi ransacked,
 mas ninguém sabe quem o fez. Mas uh, eu não estou preocupado. Ninguem consegue tomar o Hub.}
{310}{BUTCH102}{Bem, e o lugar aonde todos vao para negociar na
 Boneyard. É o único lugar civilizado o bastante para faze-lo.}
{311}{BUTCH103}{Da ultima vez que eu ouvi, ele e o prefeito de Adytum.}
{312}{BUTCH104}{Bem, eles dirigem um grande, velho hospital no lado sudoeste
 do Centro. Bando de loucos religiosos, se você me perguntar.}
{313}{BUTCH105}{Ele dirige as Crianças da Catedral abaixo na Boneyard.}
{314}{BUTH105a}{Jain é a Suma Sacerdotisa das Crianças da Catedral
 e sets up o hospital aqui no Hub.}
{315}{BUTCH106}{Eu uh . . . ouvi estorias, isso e tudo. Nenhuma verdade nelas.}
{316}{BUTCH107}{Melhores preços nas melhores armas na cidade. Todos dizem que sim,
 não é apenas por que eu as possuo! Apenas trot out e faca um acerto.
 Você não pode perder.}
{317}{BUTCH108}{Agora ai esta uma comida boa. Bob tem a melhor iguana
 chamuscada deste lado do deserto.}
{318}{BUTCH109}{Bem, você . . . uh . . . você não quer ir lá.
 Os preços são realmente altos é a qualidade e ruim.}
{319}{BUTCH110}{O que do você quer com esses loucos? Puxa, toda essa pregacao
 de paz e abracos nas arvores. Me faz ficar enjoado.}
{320}{BUTCH111}{Não sei nada sobre isso.}
{321}{BUTCH112}{Eu . . . uh . . . não acho que eu queira dizer a você. Sim, isso e tudo.}
{322}{BUTCH113}{Nunca ouvi dele. Você deve ter inventado ou algo assim.}
{323}{BUTCH114}{Bem, da ultima vez que eu ouvi foi trashed por alguém. Apesar disso, não sei por quem.}
{324}{}{Eu estou ocupado agora. Fale com o Rutger. Ele deixara eu saber se você e de valor de se ver.}
{325}{}{Eu não tenho nada a dizer pra você.}
{326}{}{Aonde eu pego minha recompensa?}
{327}{}{De novo, o que eu supostamente tinha que fazer?}
{328}{}{Saia daqui!}
{329}{}{Nada ainda.}
{330}{}{Snargle!!!}
{331}{}{Saia daqui, seu/sua retardado.}
{332}{}{Bem a noroeste, de um posto militar fortificado. E não são mutantes comuns, não. São enormes e fortemente armados. Trabalham pra um maluco chamado O Mestre. São organizados e estão sequestrando gente das caravanas.}
{333}{}{Bem a noroeste, de um posto militar fortificado. E não são mutantes comuns, não. São enormes e fortemente armados.}
{334}{}{Bem a noroeste. É algum tipo de posto avançado ou centro de operações. Trabalham pra um maluco chamado O Mestre. São organizados e estão sequestrando gente das caravanas.}
{335}{}{Bem a noroeste. É algum tipo de posto avançado ou centro de operações.}
{336}{}{Do noroeste. Trabalham pra um maluco chamado O Mestre. São organizados e estão sequestrando gente das caravanas.}
{337}{}{Do noroeste. Acho que eles têm algum tipo de posto avançado por lá.}
{338}{}{Ainda não sei, mas trabalham pra um maluco chamado O Mestre. São organizados e estão sequestrando gente das caravanas.}
{339}{}{Ainda não sei, mas havia um grande mutante verde numa caverna perto da cidade, tagarelando sobre alguma missão desse cara chamado "Mestre".}
{340}{}{Ainda não sei, mas achei este disco esquisito com um grande mutante verde que disse algo sobre o "Mestre" dele.}
{341}{}{Não, não, não, seu tapado. Esses mutantes são verdes, e vêm de bem longe, do noroeste, de um posto militar fortificado. E não são mutantes comuns, não. São enormes e fortemente armados. Trabalham pra um maluco chamado O Mestre. São organizados e estão sequestrando gente das caravanas.}
{342}{}{Não, não, não, seu tapado. Esses mutantes são verdes, e vêm de bem longe, do noroeste, de um posto militar fortificado. E não são mutantes comuns, não. São enormes e fortemente armados.}
{343}{}{Não, não, não, seu tapado. Esses mutantes são grandes e verdes, e vêm de bem longe, do noroeste. É algum tipo de posto avançado ou centro de operações. Trabalham pra um maluco chamado O Mestre. São organizados e estão sequestrando gente das caravanas.}
{344}{}{Não, não, não, seu tapado. Esses mutantes são grandes e verdes, e vêm de bem longe, do noroeste. É algum tipo de posto avançado ou centro de operações.}
{345}{}{Não, não, não, seu tapado. Esses mutantes são grandes e verdes, e vêm do noroeste. Trabalham pra um maluco chamado O Mestre. São organizados e estão sequestrando gente das caravanas.}
{346}{}{Não, não, não, seu tapado. Esses mutantes são grandes e verdes, e vêm do noroeste. Acho que eles têm algum tipo de posto avançado por lá.}
{347}{}{Não, não, não, seu tapado. Esses mutantes são grandes e verdes, e trabalham pra um maluco chamado O Mestre. São organizados e estão sequestrando gente das caravanas.}
{348}{}{Não, não, não, seu tapado. Esses mutantes são grandes e verdes. Havia um numa caverna perto da cidade, tagarelando sobre alguma missão desse cara chamado "Mestre".}
{349}{}{Não, não, não, seu tapado. Esses mutantes são grandes e verdes. Achei este disco esquisito com um grande mutante verde que disse algo sobre o "Mestre" dele.}
{500}{BUTCH55a}{Uhh, faca isso. É volte e me diga . . . ok?}
{501}{butch63a}{Ei! Pare com isso!}
{502}{BUTCH69a}{Como eu disse a você . . .}
{503}{BUTCH70b}{Como eu disse . . .}
{504}{BUTH105b}{Eu não tenho ideia do que você esta falando.}
{980}{BUTCH111}{Não sei nada sobre isso.}
{981}{BUTCH112}{Eu . . . uh . . . não acho que eu queira dizer a você. Sim, isso e tudo.}
{982}{BUTCH113}{Nunca ouvi dele. Você deve ter invetado ou algo assim.}
{1000}{}{Decker}
{1001}{}{Submundo}
{1002}{}{Maltes}
{1003}{}{Ladroes}
{1004}{}{Justin}
{1005}{}{Harold}
{1006}{}{Mercadores}
{1007}{}{Daren}
{1008}{}{Escarlate}
{1009}{}{Demetre}
{1010}{}{Comerciante}
{1011}{}{Butch}
{1012}{}{Beth}
{1013}{}{Rutger}
{1014}{}{Agua}
{1015}{}{Desaparecido}
{1016}{}{Mercado}
{1017}{}{Garra}
{1018}{}{Glow}
{1019}{}{Cidade}
{1020}{}{Alturas}
{1021}{}{Junktown}
{1022}{}{Killian}
{1023}{}{Brotherhood}
{1024}{}{Elder}
{1025}{}{Angel's}
{1026}{}{Adytum}
{1027}{}{Jon}
{1028}{}{Catedral}
{1029}{}{Morpheus}
{1030}{}{Jain}
{1031}{}{Mestre}
{1032}{}{Arma}
{1033}{}{Bob's}
{1034}{}{Tudo-Em-Um}
{1035}{}{Seguidores}
{1036}{}{Harris}
{1037}{}{Falcao}
{1038}{}{Clube Noturno}
{1039}{}{Mercador}
{1040}{}{Hightower}
{1100}{BUTCH73}{Ele e o dono do Maltese Falcon no lado oeste.
 Eu ficaria longe dele; ele não é honesto, como eu.}
{1101}{BUTCH74}{Uh não. Uh não, nós não falamos sobre isso.}
{1102}{BUTCH75}{O Maltese Falcon e um clube noturno no lado oeste.
 Hope canta lá. Que boneca.}
{1103}{BUTCH76}{Mas que dor eles são. Nós achamos que seu esconderijo e na Cidade Velha,
 mas nós não podemos provar.}
{1104}{BUTCH77}{Ah, ele e o xerife. Mas se você ver um crime, reporte para mim.
 Justin não governa o roost por aqui.}
{1105}{BUTCH78}{O Velho Harold? O que do você quer com aquele mutante velho? Ele esta na Cidade Velha.
 Simplesmente pergunte por lá.}
{1106}{BUTCH79}{Aqueles bastardos. Daren Hightower pensa que ele possui o maldito Hub,
 simplesmente por causa da Torre de Agua.}
{1107}{BUTCH80}{Ele dirige os Mercadores da Agua. Nasty, bastardo ganancioso e o que ele é.}
{1108}{BUTCH81}{Você pode acha-los no limite noroeste do Centro.
 Eles controlavam o hospital antes das Crianças se mudarem.
 Fale sobre trocar o estranho pelo esquisito.}
{1109}{BUTCH82}{Ele e o chefe da Crimson Caravan. Se você me perguntar ele esta louco.}
{1110}{BUTCH83}{Você não sabe aonde seus proprios pés estão?}
{1111}{BUTCH84}{Esse sou eu. Você cego ou algo assim?}
{1112}{BUTCH85}{Uh, Beth é a gerente da Loja de Armas.
 Ela ouve muitos rumores, se você esta nesse tipo de coisa.}
{1113}{BUTCH86}{Rutger e meu assistente.}
{1114}{BUTCH87}{Esta  a sul do Mercado dos Mercadores. A unica fonte de água aqui
 e por muito da area ao redor. Os Mercadores da Agua possuem a maldita coisa.}
{1115}{BUTCH88}{Tres das minhas caravanas desapareceram no mes passado.
 A principio eu pensei que eram ou os Mercadores da Agua ou a Caravana Escarlate,
 mas eles tiveram desaparecimentos tambem.}
{1116}{BUTCH89}{Esta aonde todos negociam. Smack dab no meio da cidade.}
{1117}{BUTCH90}{Uh, não eu-eu não  . . . Vá falar com a Beth, ela sabe mais sobre
 essa bosta.}
{1118}{BUTCH91}{O Glow e um poco radioativo bem, bem pra baixo ao sul.
 Radiação demais pra qualquer um viver lá.}
{1119}{BUTCH92}{A Old Town esta não lado leste. Os skags ficam por lá.}
{1120}{BUTCH93}{Esta não lado oeste.}
{1121}{BUTCH94}{Junktown? Sim, eu estive no norte naquele lugar algumas vezes.
 Consegui algumas boas bebidas.}
{1122}{BUTCH96}{Junktown? Esta ao norte. Ouvi que eles estão tendo algum problema,
# com o prefeito deles Killian sendo morto e tal.}
{1123}{BUTCH98}{Eu ouvi que ele esta morto. O que mais você precisa saber?}
{1124}{BUTCH99}{Ele lidera a Brotherhood. É tudo que eu sei.}
{1125}{BUTCH100}{Bem, é uma grande cidade arruinada ao sul. As Crianças,
 os Seguidores e Adytum estão lá. junto com todas as gangues e tal.}
{1126}{BUTCH102}{Por que? O que você ouviu? Eu ouvi que foi ransacked,
# mas ninguém sabe quem o fez. Mas uh, eu não estou preocupado. Ninguem consegue tomar o Hub.}
{1127}{BUTCH103}{Da ultima vez que eu ouvi, ele e o prefeito de Adytum.}
{1128}{BUTCH104}{Bem, eles dirigem um grande, velho hospital no lado sudoeste
 do Centro. Bando de loucos religiosos, se você me perguntar.}
{1129}{BUTCH105}{Ele dirige as Crianças da Catedral abaixo na Boneyard.}
{1130}{BUTH105a}{Jain é a Suma Sacerdotisa das Crianças da Catedral
 e sets up o hospital aqui no Hub.}
{1131}{BUTCH106}{Eu uh . . . ouvi estorias, isso e tudo. Nenhuma verdade nelas}
{1132}{BUTCH107}{Melhores preços nas melhores armas na cidade. Todos dizem que sim,
 não é apenas por que eu as possuo! Apenas trot out e faca um acerto.
 Você não pode perder.}
{1133}{BUTCH108}{Agora ai esta uma comida boa. Bob tem a melhor iguana chamuscada
 deste lado do deserto.}
{1134}{BUTCH110}{Bem, você . . . uh . . . você não quer ir lá.
 Os preços são realmente altos é a qualidade e ruim.}
{1135}{BUTCH87}{O que do você quer com esses loucos? Puxa, toda essa pregacao
 de paz e abracos nas arvores. Me faz ficar enjoado.}
{1136}{BUTCH98}{Esse sou eu. Você cego ou algo assim?}
{1137}{BUTCH99}{O Maltese Falcon e um clube noturno não lado oeste.
 Hope canta lá. Que boneca.}
{1138}{BUTCH109}{O Maltese Falcon e um clube noturno não lado oeste.
 Hope canta lá. Que boneca.}
{1139}{BUTCH02}{Aqueles bastardos. Daren Hightower pensa que ele possui o maldito Hub,
 simplesmente por causa da Torre de Agua.}
{1140}{BUTCH68}{Ele dirige os Mercadores da Agua. Nasty, bastardo ganancioso e o que ele é.}
{1041}{}{Greene}
{1042}{}{Caravana}
{1043}{}{Romara}
{1044}{}{Comerciantes}
{1045}{}{Torre}
{1046}{}{Caravanas}
{1047}{}{Darkwater}
{1048}{}{Aço}
{1049}{}{Anjos}
{1050}{}{Boneyard}
{1051}{}{Zimmerman}
{1052}{}{Armas}
{1053}{}{Armazem}
{1054}{}{Armas}
{1055}{}{Bobs}
{1056}{}{Iguana}
{1057}{}{Apocalipse}
{1058}{}{Morte}
{1059}{}{Deathclaw}
{1060}{}{Quente}
{1061}{}{Cidade velha}
{1062}{}{Velho}
{1063}{}{Falcao}
{1064}{}{Tudo}
{1065}{}{Lixo}
{1141}{}{Ah, ele e o xerife. Mas se você ver um crime, reporte para mim.
 Justin não governa o roost por aqui.}
{1142}{}{Você pode acha-los no limite noroeste do Centro.
 Eles controlavam o hospital antes das Crianças se mudarem.
 Fale sobre trocar o estranho pelo esquisito.}
{1143}{}{Ele e o chefe da Caravana Escarlate. Se você me perguntar ele esta louco.}
{1144}{}{Você não sabe aonde seus proprios pés estão?}
{1145}{}{Esta ao sul do Mercado dos Mercadores. A unica fonte de água aqui
 e por muito da area ao redor. Os Mercadores da Agua possuem a maldita coisa.}
{1146}{}{Tres das minhas caravanas desapareceram no mes passado.
 A principio eu pensei que eram ou os Mercadores da Agua ou a Caravana Escarlate,
 mas eles tiveram desaparecimentos tambem.}
{1147}{}{Ele e o prefeito de Junktown, isso e tudo que eu sei.}
{1148}{}{Ah, eles são um bando de loucos por armas a noroeste. Realmente esquisito. Apesar disso eles fazem uma maldita boa arma.}
{1149}{}{Bem, é uma grande cidade arruinada ao sul. As Crianças,
 os Seguidores e Adytum estão lá. junto com todas as gangues e tal.}
{1150}{}{Bem, é uma grande cidade arruinada ao sul. As Crianças,
 os Seguidores e Adytum estão lá. junto com todas as gangues e tal.}
{1151}{}{Da ultima vez que eu ouvi, ele e o prefeito de Adytum.}
{1152}{}{Melhores preços nas melhores armas na cidade. Todos dizem que sim,
 não é apenas por que eu as possuo! Apenas     e faca um acerto.
 Você não pode perder.}
{1153}{}{Melhores preços nas melhores armas na cidade. Todos dizem que sim,
 não é apenas por que eu as possuo! Apenas     e faca um acerto.
 Você não pode perder.}
{1154}{}{Melhores preços nas melhores armas na cidade. Todos dizem que sim,
 não é apenas por que eu as possuo! Apenas     e faca um acerto.
 Você não pode perder.}
{1155}{}{Agora ai esta uma comida boa. Bob tem a melhor iguana
 chamuscada deste lado do deserto.}
{1156}{}{Agora ai esta uma comida boa. Bob tem a melhor iguana
 chamuscada deste lado do deserto.}
{1157}{}{O que do você quer com esses loucos? Puxa, toda essa pregacao
 de paz e abracos nas arvores. Me faz ficar enjoado.}
{1158}{}{Uh, não, eu-eu não . . . Vá falar com a Beth, ela sabe mais sobre
 essa bosta.}
{1159}{}{Uh, não, eu-eu não . . . Vá falar com a Beth, ela sabe mais sobre
 essa bosta.}
{1160}{}{O Glow e um poco radioativo bem, bem pra baixo ao sul.
 Radiação demais pra qualquer um viver lá.}
{1161}{}{A cidade velha esta não lado leste. Os skags ficam por lá.}
{1162}{}{A cidade velha esta não lado leste. Os skags ficam por lá.}
{1163}{}{Ele lidera a Irmandade. Isso e tudo que eu sei.}
{1164}{}{Bem, você . . . uh . . . você não quer ir lá.
 Os preços são realmente altos é a qualidade e ruim.}
{1165}{}{Junktown? Sim, eu estive no norte naquele lugar algumas vezes.
 Consegui algumas boas bebidas.}
