{100}{}{Você vê um balconista das Caravanas Escarlate.}
{101}{}{Você vê um balconista dos Mercadores das Águas.}
{102}{}{Você vê um balconista dos Far Go Traders.}
{103}{}{Ola. Você esta procurando por um trabalho?}
{104}{}{Sim.}
{105}{}{Não.}
{106}{}{Otimo. Nós temos espaco para outro guarda. Você esta interessado?}
{107}{}{OK. Se você precisar de trabalho, apenas stop by and well will set you up.}
{108}{}{Lamento ouvir isso. Tchau.}
{109}{}{Excelente. Nós temos caravanas saindo para: a Boneyard, Junktown, Necropolis e Irmandade do Aço. Em qual você
 gostaria de trabalhar?}
{110}{}{Excelente. Nós temos caravanas saindo para: a Boneyard, Junktown e Irmandade do Aço. Em qual você
 gostaria de trabalhar?}
{111}{}{Excelente. Nós temos caravanas saindo para: a Boneyard e Junktown. Em qual você
 gostaria de trabalhar?}
{112}{}{Boneyard.}
{113}{}{Junktown.}
{114}{}{Brotherhood of Steel.}
{115}{}{Necropolis.}
{116}{}{Nenhuma.}
{117}{}{Otimo. Nós saimos agora.}
