{100}{}{Deseja entrar no diálogo de debug? [Se não tiver certeza, clique em Não]}
{101}{}{Voltar o relógio (Pode Travar, especialmente após 03/11/2161).}
{102}{}{Certo. Quanto? [Os números no início são o número que você pode teclar pra escolher a opção]}
{103}{}{Um segundo  [10 ticks]}
{104}{}{Um minuto}
{105}{}{Uma hora}
{106}{}{Um dia}
{107}{}{Uma semana}
{108}{}{Um mês [30 dias]}
{109}{}{Seis meses}
{110}{}{Deixa pra lá.}
{111}{}{Adiantar o relógio (Pode Travar, especialmente após 03/11/2174).}
{112}{}{Certo. Quanto? [Os números no início são o número que você pode teclar pra escolher a opção]}
{113}{}{Um segundo  [10 ticks]}
{114}{}{Um minuto}
{115}{}{Uma hora}
{116}{}{Um dia}
{117}{}{Uma semana}
{118}{}{Um mês [30 dias]}
{119}{}{Seis meses}
{120}{}{Deixa pra lá.}
{121}{}{Me dê todas as chaves do jogo.}
{122}{}{Numa mochila ou direto no seu inventário?}
{123}{}{Numa mochila.}
{124}{}{No meu inventário.}
{125}{}{Deixa pra lá.}
{126}{}{13 years}
{127}{}{13 years}
{200}{}{Como posso te Trapacear hoje?}
{201}{}{Experience.}
{202}{}{Dano, Veneno, Radiação.}
{203}{}{Poison}
{204}{}{Radiation}
{205}{}{Deletar TODOS os itens do meu inventário - Inclui os equipados!}
{206}{}{Alternar variável global "APENAS CORREÇÕES DE BUG" [gvar 0]}
{207}{}{Nada. [fechar diálogo]}
{208}{}{Modo "Apenas Correções" atualmente ATIVADO. Desativar?}
{209}{}{Sim, desative.}
{210}{}{Não. [voltar]}
{211}{}{Modo "Apenas Correções" atualmente DESATIVADO. Ativar?}
{212}{}{Sim, ative.}
{213}{}{before: }
{214}{}{after: }
{215}{}{[Te entrega um Burrito Supremo] Aproveite sua Carne Grau D.}
{216}{}{Agora você brilha feito uma lâmpada de 50 rads.}
{217}{}{Pronto.}
{221}{}{[Sorrindo maldosamente] Fiquei feliz em te 'ajudar'.}
{222}{}{Como posso abusar de você hoje?}
{223}{}{Aleijar Perna Esquerda}
{224}{}{Aleijar Perna Direita}
{225}{}{Aleijar Braço Esquerdo}
{226}{}{Aleijar Braço Direito}
{227}{}{Me Cegue }
{228}{}{Não me machuque. [choramingo]}
{229}{}{ROLAGENS DE TESTE mmm, rolagens}
{230}{}{Pronto.}
{231}{}{mensagem aqui}
{232}{}{500}
{233}{}{1 mil}
{234}{}{5 mil}
{235}{}{10 mil}
{236}{}{50 mil}
{237}{}{210 mil}
{238}{}{menos 5 mil}
{239}{}{Deixa pra lá}
{240}{}{Certo, você as tem.}
{241}{}{Quantos pontos de Exp você quer? [Os números no início são o número que você pode teclar pra escolher a opção]}
{242}{}{Pontos de vida.}
{243}{}{Certo, quantos PV você quer perder?}
{244}{}{One HP.}
{245}{}{Five HP.}
{246}{}{Ten HP.}
{247}{}{Vinte PV.}
{248}{}{Trinta PV.}
{249}{}{Quarenta PV.}
{250}{}{Cinquenta PV.}
{251}{}{999 PV. (me mate...)}
{252}{}{Teletransportar pra outro mapa...}
{253}{}{Necropolis - Hotel}
{254}{}{Vault 13 - Interior}
{255}{}{Junktown - Cassino}
{256}{}{Brotherhood - 1/2}
{257}{}{Base Militar - Tanques}
{258}{}{Shady Sands - Oeste}
{259}{}{O Hub - Centro}
{260}{}{Deixa pra lá.}
{261}{}{Covil do Mestre - 3/4}
{262}{}{Certo, qual mapa?}
{263}{}{Modificar o tempo de jogo}
{264}{}{Me dê itens de debug de trapaça (muitos)}
{265}{}{Sim.}
{266}{}{Certo, voltar ou adiantar?}
{267}{}{Você tem certeza?}
{268}{}{Não. [voltar]}
{269}{}{Necropolis,  Vault 13,  Vault 15}
{270}{}{Junktown,  Brotherhood of Steel,  Cidade}
{271}{}{Filhos da Catedral, Vault do Mestre, Costa, Montanha}
{272}{}{The Hub}
{273}{}{Boneyard Adytum,  Saqueadores}
{274}{}{Shady Sands,  Base Militar}
{275}{}{O Glow,  Deserto}
{276}{}{Caravanas}
{277}{}{Specials}
{305}{}{Necropolis - WATRSHD.MAP}
{306}{}{Vault 13 - VAULT13.MAP}
{307}{}{Vault 15 - VAULTENT.MAP}
{308}{}{Vault 15 - VAULTBUR.MAP}
{278}{}{Deixa pra lá.}
{279}{}{Deixa pra lá.}
{280}{}{Slideshow de Final.}
{300}{}{DESERT1.MAP}
{301}{}{DESERT2.MAP}
{302}{}{DESERT3.MAP}
{303}{}{Necropolis - HALLDED.MAP}
{304}{}{Necropolis - HOTEL.MAP}
{309}{}{Necropolis - VAULTNEC.MAP}
{310}{}{JUNKENT.MAP}
{311}{}{JUNKCSNO.MAP}
{312}{}{JUNKKILL.MAP}
{313}{}{BROHDENT.MAP}
{314}{}{BROHD12.MAP}
{315}{}{BROHD34.MAP}
{316}{}{CAVES.MAP - Radscorpion Caves}
{317}{}{CHILDRN1.MAP}
{318}{}{CHILDRN2.MAP}
{319}{}{CITY1.MAP}
{320}{}{COAST1.MAP}
{321}{}{COAST2.MAP}
{322}{}{COLATRUK.MAP}
{323}{}{FSAUSER.MAP}
{324}{}{RAIDERS.MAP}
{325}{}{SHADYE.MAP}
{326}{}{ShadyW.map}
{327}{}{GLOWENT.MAP}
{328}{}{LAADYTUM.MAP - Entrance}
{329}{}{LAFOLLWR.MAP}
{330}{}{MBENT.MAP}
{331}{}{MBSTRG12.MAP - MB lvl 1, 2}
{332}{}{MBVATS12.MAP - MB lvl 3, 4}
{333}{}{MSTRLR12.MAP}
{334}{}{MSTRLR34.MAP}
{335}{}{Vault 13 - V13ENT.MAP}
{336}{}{HUBENT.MAP}
{337}{}{DETHCLAW.MAP - Cave}
{338}{}{HUBDWNTN.MAP}
{339}{}{HUBHEIGT.MAP}
{340}{}{HUBOLDTN.MAP}
{341}{}{HUBWATER.MAP}
{342}{}{GLOW1.MAP}
{343}{}{GLOW2.MAP}
{344}{}{LABLADES.MAP}
{345}{}{LARIPPER.MAP}
{346}{}{LAGUNRUN.MAP}
{347}{}{CHILDEAD.MAP}
{348}{}{MBDEAD.MAP}
{349}{}{MOUNTN1.MAP}
{350}{}{MOUNTN2.MAP}
{351}{}{FOOT.MAP}
{352}{}{TARDIS.MAP}
{353}{}{TALKCOW.MAP}
{354}{}{USEDCAR.MAP}
{355}{}{BRODEAD.MAP (not used in-game)}
{356}{}{DESCRVN1.MAP}
{357}{}{DESCRVN2.MAP}
{358}{}{MNTCRVN1.MAP}
{359}{}{MNTCRVN2.MAP}
{360}{}{VIPERS.MAP (not used in-game)}
{361}{}{DESCRVN3.MAP}
{362}{}{MNTCRVN3.MAP}
{363}{}{DESCRVN4.MAP}
{364}{}{MNTCRVN4.MAP}
{365}{}{HUBMIS0.MAP - Irwin}
{366}{}{HUBMIS1.MAP - Irwin}
{1000}{}{Modificar Cronômetros.}
{1010}{}{Invasão do Vault 13.}
{1011}{}{Cronômetro de Água do Vault 13.}
{1020}{}{Adicionar 100 dias.}
{1030}{}{Remover 100 dias.}
