{100}{}{Você vê antes de você um Nightkin.}
{101}{}{Morra!}
{102}{}{Me deixe ou morra!}
{103}{}{Não gosto do seu tom. Se minha mensagem não chegar ao Mestre,
 Eu cuidarei para que sua morte seja lenta e dolorosa.}
{104}{}{Eu só queria cumprimentá-lo pela ótima corcunda em suas costas.
 Sua respiração poderia usar algum trabalho, no entanto. . .}
{105}{}{Você poderia me indicar o responsável?}
{106}{}{Cara, você poderia usar uma bebida pior que eu!}
{107}{}{Eu não vou sair!}
{108}{}{Certo. Eu saio.}
{109}{}{Não é prudente jogar com o Nightkin. Saia daqui!}
{110}{}{Eu não penso assim}
{111}{}{Eu vou gostar de ver você morrer!}
{112}{}{Você não escuta? Não é prudente ignorar o Nightkin.}
{113}{}{Eu preciso falar com você. É urgente!}
{114}{}{Ninguém nunca me acusou de ser sábio!}
{115}{}{Eu só quero falar com o homem no comando!}
{116}{}{Você deveria ser durão ou algo assim?}
{117}{}{Me desculpe! Tenha um bom dia.}
{118}{}{Você quer ver insensato? É imprudente me dar um lábio, imbecil!}
{119}{}{Suba as escadas. Outros da minha espécie julgarão o valor da sua mensagem.}
{120}{}{Este é seu último aviso!}
{121}{}{Claro que é! Grande negócio . . .}
{122}{}{Eu REALMENTE preciso falar com o cara no comando!}
{123}{}{Certo! OK! Eu sinto Muito! Tenha um bom dia.}
{124}{}{Você sabe qual é o seu erro? Você dá avisos. Eu não. Morrer!}
{125}{}{[feito]}
