{100}{}{Você vê o Iniciado Ronald das Crianças da Catedral.}
{101}{}{Você vê a Iniciada Caroline das Crianças da Catedral.}
{102}{}{Você vê o Iniciado Myles das Crianças da Catedral.}
{103}{}{Você vê a Iniciada Alisha das Crianças da Catedral.}
{104}{}{Você vê o Iniciado Thomas das Crianças da Catedral.}
{105}{}{Você vê o Iniciado Gabriel das Crianças da Catedral.}
{106}{}{Você vê a Iniciada Charlene das Crianças da Catedral.}
{107}{}{Você vê o Iniciado Ekdar das Crianças da Catedral.}
{108}{}{Você vê o Iniciado Hopper das Crianças da Catedral.}
{109}{}{Você vê o Iniciado Radek das Crianças da Catedral.}
{110}{}{Esses Seguidores perdidos foram faceis de matar.}
{111}{}{Agora que os Seguidores estão fora do caminho, a reconstrucao pode começar.}
{112}{}{No final desta busca, eu espero ser um Escriba ou Estudioso.}
{113}{}{Algum dia eu serei um estudioso e irei adiante pregar a Unidade.}
{114}{}{Orfeo é uma pessoa difícil de se trabalhar.}
{115}{}{Eu ainda estou assustado por causa dos Nightkin.}
{116}{}{Os Elders disseram que os Nightkin são nossos aliados.}
{117}{}{Vá embora.}
{118}{}{Eu não gosto do seu tipo.}
{119}{}{Se você tem um problema com o Set, você tem um problema comigo.}
{120}{}{A paz esteja com você. Por favor, fale com a Laura.}
{121}{}{A Laura me ensinou que somos todos um só povo e devemos buscar o bem nas pessoas. Ela é muito sábia.}
{122}{}{A Laura é uma pessoa sábia e maravilhosa.}
{123}{}{Você vê um dos acólitos dos Filhos da Catedral.}
