{100}{}{Nós estamos voltando pro Hub.}
{101}{}{Você vai retornar conosco?}
{102}{}{Eu amo este trabalho!}
{103}{}{Espero que eu tenha balas o bastante.}
{104}{}{Pronto pra ir.}
{105}{}{Vamos lá!}
{106}{}{Mova-se!}
{107}{}{Nós matamos todos eles!}
{108}{}{Essa foi fácil!}
{109}{}{Não fale, mova seu traseiro!}
{110}{}{Você esta pronto pra ir?}
{111}{}{Eu não sou pago para falar.}
{112}{}{Lugar anormal e imundo, cara!}
{113}{}{Eu não sou pago para falar.}
{114}{}{Cuide da sua vida, sim?}
{115}{}{Cuide da sua vida, sim?}
