{100}{}{Você vê o Darrel.}
{101}{}{Você vê um Paladino.}
{102}{}{Saudaçoes e bem-vindo a Brotherhood of Steel.}
{103}{}{Duh...}
{104}{}{O que é a Brotherhood of Steel.}
{105}{}{Você sabe aonde eu consigo achar um Chip de Agua?}
{106}{}{Você sabe algumas coisa sobre as caravanas desaparecidas?}
{107}{}{Deixa pra lá.}
{108}{}{Ri de você) Amigo, eu não acho que você tenha uma
 chance de entrar aqui. Os Elders tem um requerimento
 minimo do QI para os novos Iniciados.}
{109}{}{Sim..um..bem..um.. Não. É simplesmente que as pessoas
 nem ao menos tentam entender o que nos somos.}
{110}{}{A Irmandade e um coletivo de homens e mulheres que
 dedicaram as vidas deles a preservaçao da tecnologia.}
{111}{}{Eu ouvi que vocês sacrificam filhotes.}
{112}{}{Que tipo de armadura e essa que você esta usando?}
{113}{}{Como eu descubro mais sobre sua tecnologia?}
{114}{}{Tchau.}
{115}{}{Não... Eu nunca ouvi sobre um desses. Uma das nossas
 escribas chefe pode saber. Talvez você possa pedir um
 deles. Isso e, se você se unir a nos.}
{116}{}{Me unir? Como eu me uno?}
{118}{}{Caras, vocês não sabem de nada.}
{119}{}{Sacrificar filhotes!!! Aonde diabos você ouviu essa?
 Não acredite em tudo que você ouvir nas terras devastadas,
 eles são todos um bando de lunaticos pateticos.}
{120}{}{Na verdade eu achei que teria sido bem legal.}
{121}{}{Lamento ter aborrecido você.}
{122}{}{Todos são lunaticos fora da Brotherhood of Steel?}
{123}{}{O unico jeito de saber algo mais sobre nos e se
 unir a nos. Meu amigo Cabbot pode ajudar você com isso.}
{125}{}{Vocês tem um Chip de Agua na Brotherhood?}
{126}{}{Você precisara falar com o Cabbot sobre isso.}
{127}{}{De qualquer maneira, a respeito do que é a Brotherhood of Steel?}
{128}{}{Isso esta Certo... É simplesmente que as pessoas nem
 ao menos tentam entender o que nos fazemos.}
{129}{}{O que há pra entender?}
{130}{}{Bem... Eu mesmo acho que vocês poderiam ser um pouco loucos.}
{131}{}{Tecnologia. Isso e tudo que alguém precisa entender.
 Junte-se a nos e você vira a saber disto.}
{132}{}{Como alguém se une a Brotherhood?}
{133}{}{Vocês são um pouco demais da ala de politica de esqueda pra mim.}
{134}{}{Eu lamento que você se sinta desse modo.}
{135}{}{Esta é a Armadura de Infantaria Energizada pra Combate Modelo T-51b
 ou mais geralmente conhecida como Power Armor.}
{136}{}{Eu estive vagueando pelas terras devastadas por semanas e semanas
 e eu nunca vi armadura como esta antes.}
{137}{}{Parece que seria cumbersome de usar.}
{139}{}{A Irmandade é a unica usuaria da the Power Armor nas terras
 devastadas. So aos honrados e cavaleiros da mais alta estatura e
 dado o privilegio de usar a melhor armadura.}
{140}{}{Isso ainda não responde por que eu nunca a vi antes.}
{141}{}{Como alguém se une a Brotherhood?}
{143}{}{Heathens tentaram e falharam em tomar nossa Power Armor de nos.
 Eles teriam que matar um irmao pra possuir o direito de nascença dele
 e se chegasse a isso a armadura estaria numa condiçao tão ruim que a
 tornaria inutil.}
{144}{}{Eu acho que eu tentarei toma-lá do seu corpo morto e frio.}
{145}{}{Tchau.}
{146}{}{Eu tenho que sacrificar um filhote pra me unir?}
{147}{}{Dificil? Nem de longe. A armadura sagrada e tão belamente
 construida com especificaçoes tão exatas que se a sente como uma
 extensao do proprio corpo do abençoado. Ela aumenta muitas vezes
 a força da pessoa e ajuda você a resistir os efeitos da radiaçao
 para que você possa servir mais efetivamente a irmandade. Eu me
 sentiria diminuido sem minha armadura sagrada.}
{148}{}{Como que ninguém mais nas terras devastadas tem esta armadura?}
{149}{}{Eu quero uma dessas.}
{151}{}{Você precisa falar com o Cabbot se você deseja se unir.}
{152}{}{Eu não consigo acreditar. Eles estão enviando ele lá pra baixo?}
{153}{}{Eu não consigo acreditar. Eles estão enviando ela lá pra baixo?}
{154}{}{Então você pegou a famosa missao do Glow. (Risadas)}
{155}{}{Não... Eu estou indo para a Ordem Antiga.}
{156}{}{O Glow, O que é isso?}
{157}{}{Não e da sua conta o que eu estou fazendo.}
{158}{}{Sim, eu aceitei. Tchau.}
{159}{}{Glow ou Ordem Antiga são a mesma coisa. Ainda não e
 um bom lugar pra visitar.}
{160}{}{Por que você diz isso?}
{161}{}{Quao difícil poderia ser. Tudo que eu tenho que fazer e ir pegar algo
 e trazer de volta. É a velha coisa de mandar o cara novo numa busca.}
{162}{}{Por que os dois nomes?}
{163}{}{O que é tão especial a respeito deste lugar?}
{164}{}{O Glow, como e conhecido aos topsiders, era supostamente um lugar
 aonde algumas das armas mais avançadas daquele tempo eram desenvolvidas.
 Pelo menos isso e o que nos dizem nas escritas antigas. Agora tanto
 quato qualquer um de nos pode dizer é uma grande cratera cheia de
 radiaçao. Eu acho que os Elders enviam candidatos a Irmandade lá
 embaixo apenas pra se livrar deles.}
{165}{}{Outros? Houveram outros antes de mim?}
{166}{}{Eu estou indo para a Ordem Antiga. Aonde isso esta localizado?}
{167}{}{Você esta certo. Não e da minha conta.}
{168}{}{Bem? Pra começar são bons 10 dias de viagem para o sudeste
 daqui. É então há a radiaçao. Há uma razão pela qual nenhum de
 nos ja foi até a "Ordem Antiga". Se você não tiver Rad-X você
 sera cozinhado antes mesmo de você saber o que atingiu você.}
{170}{}{Me deixe ir direto ao ponto...}
{171}{}{A maioria dos topsiders acham que é apenas um grande buraco
 radioativo. Assim o nome se tornou o Glow ou alguns até mesmo o
 chama de Lugar Quente. Nós na Irmandade sabemos a verdade. De
 acordo com as escritas antigas este lugar era a fonte de toda
 a nossa tecnologia. É quem sabe o que ainda pode estar lá.}
{173}{}{Me deixe ir direto ao ponto...}
{174}{}{Outros tentaram. Nós nunca mais ouvimos sobre eles de novo.}
{175}{}{Inferno, você quase me convenceu de querer me unir
 a Irmandade.}
{176}{}{Eles eram fracos. Eu verei vocês por ai.}
{177}{}{Com o que eu deveria tomar cuidado quando eu for lá embaixo?}
{179}{}{O Glow é a Ordem Antiga são a mesma coisa.}
{180}{}{O que é o Glow?}
{181}{}{Não me entenda mal, a Irmandade e um otimo lugar pra se unir.
 É de longe o lugar mais seguro pra viver nas terras devastadas. Em
 nenhum outro lugar você achara armas e armaduras melhores. Nós
 servimos a tecnologia é a tecnologia nos serve.}
{182}{}{Soa bem. Eu vou seguir meu caminho.}
{183}{}{O que você pode me dizer sobre o Glow?}
{184}{}{Não soa como se o problema valesse a pena.}
{185}{}{O que?}
{186}{}{Por que a Ordem Antiga tem dois nomes?}
{187}{}{Aonde esta a Ordem Antiga? É os perigos são?}
{188}{}{Eu posso fazer algumas perguntas pra você?}
{189}{}{A maioria dos topsiders acham que é apenas um grande buraco
 radioativo. Por isso o nome se tornou o Glow ou alguns até mesmo o
 chamam de Local Quente. Nós na Irmandade sabemos a verdade. De
 acordo com as escritas antigas este lugar era a fonte de toda
 a nossa tecnologia. É quem sabe o que ainda pode estar lá.}
{190}{}{Tenho outra pergunta pra você.}
{191}{}{Eu posso ajudar você?}
{192}{}{Deixa pra lá. Tchau.}
{193}{}{Com certeza, pergunte.}
{194}{}{Ola}
{195}{}{Sim, o Rutger veio aqui pessoalmente a não muito tempo atras e isso não
 e do feitio dele. Ele estava tentando descobrir o que tem acontecido com as
 caravanas dele. Eu não tenho ideia do que poderia ter sido. Alguns outros
 dizem que eles viram algo perto do hub, mas desapareceu antes que eles
 pudessem chegar perto o bastante. É tudo muito aflitivo, eu espero que
 seja resolvido em breve.}
{196}{}{Eu ouvi que vocês fazem sacrificios de animais! Talvez vocês peguem
 estas caravanas para seus rituais sombrios!}
{197}{}{Alguma suspeita?}
{198}{}{Bem, se você ver qualquer coisa deixe-me saber. Eu mesmo gostaria
 de chegar rapido ao fundo disto.}
{199}{}{Não mesmo, mas eu suspeito que foi foul play... mas então de novo,
 há muitas criaturas estranhas e perigosas lá fora nas terras devastadas.
 Poderia simplesmente ser alguma criatura ou mais provavelmente uma
 manada ou bando delas. Eu espero que isso ajude. Bom dia.}
{201}{}{Obrigado pelo seu tempo. Tchau.}
{202}{}{Certo, obrigado. Tchau.}
{203}{}{Obrigado pela informaçao. Tchau.}
{204}{}{Obrigado, Tchau.}
{205}{}{Certo... Obrigado pela informaçao.}
{206}{}{Eu agradeço a você pelo aviso. Tchau.}
{207}{}{Obrigado. Tchau.}
{208}{}{Obrigado pelo seu tempo.}
{209}{}{Se você esta procurando obter algumas armas melhores talvez
 você deva tentar o Glow em baixo ao sul. (O Darrel apointa pro sul)}
{210}{}{Aqui, leve alguns Rad-X. (O Darrel da algumas pilulas pra você)}
{211}{}{Engula estas assim. (O Darrel se movimenta como se tomando
 as pilulas e esfrega a barriga dele). Mmmmm yummm.}
{212}{}{Espera espera! Ainda não! (O Darrel impede você de tomar as pilulas)
 Espere até você chegar no Glow.}
{300}{}{[Mais]}
