{100}{}{Você vê um mutante morrendo.}
{101}{}{O mutante esta próximo da morte.}
{102}{}{Você vê o corpo de um mutante.}
{103}{}{O mutante esta morto.}
{104}{}{Foi tão rapido... Meus irmaos se foram... Não pude ajudar...}
{105}{}{Quem é você?}
{106}{}{Eu, eu sou... Eu não lembrar... Era o lider de... Talvez meu holodisco... [O mutante fracamente da a você um holodisco ensanguentado]}
{107}{}{De onde você veio?}
{108}{}{Nós... Nós estavamos patrulhando por primarios... Vieram do... Do noroeste.}
{109}{}{Quem enviou você?}
{110}{}{Pai... Aonde esta você pai?... Sim Mestre... [O mutante da seu ultimo suspiro e collapses]}
{111}{}{Uhhhh....  Arrgghh....}
{112}{}{Mestre....}
{113}{}{Irmaos... Aonde...?}
