{100}{}{Você vê um morador do Hub.}
{101}{}{Eu não posso acreditar que eu estou vivo e eu não posso acreditar que você derrotou todos ele! Espere, o que eu estou dizendo? Eu estou vivo,
 não estou? Eu acreditarei em qualquer coisa que você me disser agora mesmo.}
{102}{}{Eu vou matar você agora.}
{103}{}{Me de todo seu dinheiro!}
{104}{}{Limpe sua vida e saia daqui ou eu acabarei com você tambem!}
{105}{}{Uh?}
{106}{}{Uh, mas? Você? (suspiro) Okay, faca-o rapidamente por favor. Eu odeio dor.}
{107}{}{Não me machuque!}
{108}{}{Okay. (Ele da a você 20 pratas do hub.) Eu posso ir agora?}
{109}{}{Sim.}
{110}{}{Não.}
{111}{}{Uh, por que?}
{112}{}{Por que eu disse que sim! Você tem um problema com isso?}
{113}{}{Okay, você pode sair.}
{114}{}{Não, lamento, senhor! Por favor não me machuque -- Eu não gosto da dor!}
{115}{}{Não, lamento, senhora! Por favor não me machuque -- Eu não gosto da dor!}
{118}{}{Você e estúpido? Eu quero dizer, muito obrigado por ter salvo minha vida, bondoso senhor.  Eu tenho que ir agora. Tchau.}
{119}{}{Você e estupida? Eu quero dizer, muito obrigado por ter salvo minha vida, bondosa senhora.  Eu tenho que ir agora. Tchau.}
{122}{}{Sim . . . sim . . . sim senhor. Eu nunca farei nada ruim, jamais, de novo!  Eu . . . Eu não trapacearei. Eu não mentirei, chantagear, roubar, assassinar ou sequestrar.}
{123}{}{Sim . . . sim . . . sim senhora. Eu nunca farei nada ruim, jamais, de novo!  Eu . . . Eu não trapacearei. Eu não mentirei, chantagear, roubar, assassinar ou sequestrar.}
{126}{}{Apenas saia daqui!}
{127}{}{Você é um mentiroso!}
{128}{}{Sim, senhor!}
{129}{}{Sim, senhora!}
