{100}{}{Este equipamento não está funcional.}
{1000}{}{::BEEP:: ::BEEP::}
{1001}{}{::TZZZZ::}
{1002}{}{[War, War never changes...]}
{1003}{}{::BEEP::}
{101}{}{Você reencaixa um chip solto e, surpreendentemente, o monitor acende!}
{102}{}{O dano parece ser físico, e não elétrico. Talvez ainda inicialize com um pouco de trabalho.}
{104}{}{Você se atrapalha e corta as mãos na carcaça. Ai!}
{105}{}{Macro$oft (tm) Wyndoze 99 (c) booting up...   Done.
            U:\ > }
{106}{}{DIR}
{107}{}{SAIR}
{108}{}{FALLOUT    <DIR>          10-20-99   1:04p
                          0 bytes in 0 files, 0 bytes allocated, 4,379,255 bytes free}
{109}{}{CD FALLOUT}
{110}{}{Uau! Que jogo ótimo!}
{111}{}{ U:\ > }
{113}{}{FALLOUTW.EXE}
{114}{}{U:\Fallout\ > }
{115}{}{FALLOUTW.EXE     1384432   10-20-99   1:04p
                      FALLDEMO.EXE     995328    04-22-97   2:13p
                   2,379,760 bytes in 2 files,  2,436,874 bytes allocated}
{116}{}{[Continuar]}
{117}{}{> CARREGANDO...  }
{119}{}{ de experiência por jogar Fallout.}
{120}{}{    U:\Fallout\ > }
{121}{}{Não me canso desse jogo Fallout. Não fazem mais como nos tempos pré-Guerra.}
{126}{}{FALLDEMO.EXE}
{130}{}{Não entendo nada disso. Não sou um gênio da tecnologia!}
{140}{}{rrrggg... Ãh-dôh?}
{153}{}{Interessante. Aposto que a versão completa vai ser um ótimo jogo!}
{154}{}{Hmm. A versão completa do Fallout é melhor, mas esta demo tem um charme único mesmo assim.}
{155}{}{ de experiência por jogar a Demo Interativa do Fallout.}
{400}{}{Com o gerador quebrado, há pouco motivo pras gangues brigarem por Scrapheap. O povo de Scrapheap terá uma vida mais pobre sem energia; mas, com as gangues eliminadas, ao menos terão uma vida. Seu trabalho aqui está concluído, mas sua missão de encontrar o chip de purificação de água continua.}
{401}{}{Após uma longa batalha e muito derramamento de sangue, você prevalece. Com as gangues derrotadas, Scrapheap é um refúgio seguro mais uma vez. Os moradores estão gratos - eles te dão informações valiosas, e sua tarefa em Scrapheap está concluída. Porém, a missão de encontrar o chip de purificação de água continua.}
{500}{}{500 Após deter o Mestre e o laboratório com o qual ele criava seu exército de Super Mutantes, você volta pra casa, só pra descobrir que foi expulso do seu Vault por ser destrutivo demais. Obrigado por jogar Fallout.}
{501}{}{501 Após convencer o Mestre a abandonar sua dominação malconcebida e destruir os Tanques, você volta pra casa, só pra descobrir que foi exilado, supostamente pra impedir que outros deixem o Vault. Obrigado por jogar Fallout.}
{502}{}{502 Após destruir os Tanques, o Mestre e seu exército de Super Mutantes, você volta pra casa, mas é proibido de entrar. Você revida, deixando pra trás o corpo despedaçado do Supervisor. Obrigado por jogar Fallout.}
{503}{}{503 Você é mergulhado no FEV e se junta à Unidade do Mestre, revelando a localização do Vault 13. Você é recompensado liderando o ataque contra o seu Vault, matando o Supervisor com as próprias mãos. Obrigado por jogar Fallout.}
