{100}{}{Você vê um cachorro. Ele parece estar seguindo você.}
{101}{}{Você vê um cachorro.}
{102}{}{Woof!}
{103}{}{Grrr!}
{104}{}{Parece que você fez um amigo deste cachorro.}
{105}{}{Você ganha 550 pontos de experiência por fazer amizade com o cachorro.}
{106}{}{Você ganha 335 pontos de experiência por derrotar o cachorro e deixar o Phil voltar pra sua casa.}
{107}{}{Você ganha 35 pontos de experiência por matar o cachorro.}
{108}{}{Você ganha 200 pontos de experiência por fazer amizade com o cão.}
