{100}{}{O gerador de energia foi sabotado. Não funciona mais.}
{101}{}{Você vê um gerador de energia. É a única fonte de energia no Scrapheap.}
{102}{}{Você corta alguns fios no transformador. O gerador de energia não funciona mais.}
{103}{}{Os cortadores não têm mais uso.}
{104}{}{Esse item é inútil no gerador.}
{105}{}{Você não nota nada em particular sobre o gerador.}
{106}{}{O próprio gerador parece bastante inviolável; no entanto, você percebe um conjunto de fios entre o transformador
 e o gerador.}
{107}{}{Você não pode ver nada de especial sobre este grande gerador.}
{108}{}{Você não pode determinar mais nada sobre o gerador.}
{109}{}{Os fios podem ser reparados, mas pode demorar um pouco e não há garantia de sucesso.}
{110}{}{Você não pode ver nada de especial sobre o gerador danificado.}
{111}{}{Você não pode mais fazer reparos.}
{112}{}{Não há necessidade de reparar o gerador de energia. Está funcionando perfeitamente.}
{113}{}{Você não pode reparar o gerador em funcionamento.}
{114}{}{Leva várias horas, mas você conserta o gerador de energia. Com o poder restaurado e as gangues desaparecidas,
 as pessoas da cidade são gratas. Eles te dão algumas informações valiosas. Sua tarefa no Scrapheap está concluída. o
 missão para encontrar o chip de água ainda aguarda.}
{115}{}{Você não pode consertar o gerador. O povo de Scrapheap levará uma vida mais pobre sem o seu poder;
 mas com as gangues fora, pelo menos eles terão uma vida. Sua tarefa no Scrapheap está concluída. A missão de
 encontrar o chip de água ainda aguarda.}
{116}{}{Mais adulterações com o gerador não rendem nada.}
{117}{}{Essa habilidade não tem efeito no gerador.}
{118}{}{O gerador já está em execução.}
{119}{}{Você não pode iniciar o gerador porque está quebrado.}
