{100}{}{Isto parece estranho. Parece que pode ser usado no seu Pip Boy.}
{101}{}{Pip Boy exibe: Arquivo Achado no Sistema. Abortando o download.}
{102}{}{Pip Boy exibe: Baixando dados do disco.}
{103}{}{Você nota que o disco tem um rótulo apagado e gasto que diz "Registro dos Experimentos Delta".}
{104}{}{Você vê: Disco dos Experimentos Delta.}
{105}{}{Os Militares consideraram necessário que pesquisássemos mais a fundo os efeitos da tecnologia de ondas sobre organismos vivos. Tomamos a luz e o som como base dos nossos estudos. Manipulando a amplitude das ondas de luz e ampliando a frequência, conseguimos lasers que cortam alguns metros de aço. Infelizmente, a energia pra realizar tal tarefa ainda não foi totalmente desenvolvida. Temos outros cientistas investigando isso.}
{106}{}{**BEGIN-DISK**}
{107}{}{**END-DISK**}
{108}{}{[Continuar]}
