{100}{}{O armario esta trancado.}
{101}{}{Você localiza uma armadilha no armario, é a desarma.}
{102}{}{Você localiza uma armadilha no armario, mas falha em desarma-lá.}
{103}{}{Você localiza uma armadilha no armario, e acidentalmente a detona!}
{104}{}{Você desarma a armadilha.}
{105}{}{Você falha em desarmar a armadilha.}
{106}{}{Você acidentalmente detona a armadilha!}
{107}{}{Você destranca o armario.}
{108}{}{Você falha em bypass a tranca no armario.}
{109}{}{O armario já esta destrancado.}
{110}{}{Enquanto mexia com a tranca, você trip up the tumblers. Não há
 jeito de bypassing esta tranca agora.}
{111}{}{Você nota que há um dispositivo explosivo   no armario.}
{200}{}{ destranca o armário.}
