{100}{}{Você vê: Caçador Experiente.}
{101}{}{Você vê: Irataba, o Caçador.}
{102}{}{Ele parece ser um caçador experiente.}
{150}{}{ pontos de experiência por aprender a esfolar geckos.}
{200}{}{NOOOOOOO!}
{201}{}{Não temos tempo pra você. Por favor, siga seu caminho agora.}
{202}{}{Boa viagem.}
{203}{}{Sinto muito, mas não temos tempo nem peles pra passar por isso de novo.}
{204}{}{Você vai pagar pelo que fez!}
{205}{}{Guarde sua arma, então podemos conversar.}
{1000}{}{Saudações, viajante. O que podemos fazer por você?}
{1001}{}{O que podemos fazer por você?}
{1010}{}{Quem é você?}
{1020}{}{O que você está fazendo aqui?}
{1030}{}{Prepare-se pra morrer!}
{1100}{}{Sou Irataba, e este é meu filho Cairook.}
{1110}{}{De onde você é?}
{1120}{}{I am }
{1121}{}{. É um prazer conhecer você e seu filho.}
{1130}{}{O que você está fazendo aqui?}
{1200}{}{Nossa vila não fica muito longe daqui. Sem ofensa, mas prefiro não te dizer onde exatamente ela fica.}
{1210}{}{Que pena, eu queria massacrar vocês todos.}
{1300}{}{Obrigado. É bom encontrar um rosto amigável, pra variar.}
{1301}{}{Você gostaria de se juntar a nós? Estou ensinando meu filho a esfolar um gecko.}
{1310}{}{Pode contar comigo.}
{1320}{}{Não tenho tempo pra isso agora, mas obrigado.}
{1400}{}{Que assim seja. Boa viagem, }
{1401}{}{.}
{1402}{}{Que assim seja. Boa viagem, estranho.}
{1500}{}{Estávamos caçando geckos e agora estou ensinando meu filho a esfolá-los.}
{1510}{}{Interessante. Você pode me ensinar a esfolar um gecko?}
{1511}{}{Se sua oferta ainda vale, você pode me ensinar a esfolar um gecko?}
{1520}{}{Entendi. Bom, então, adeus.}
{1600}{}{Não tenho tempo pra te ensinar, viajante.}
{1610}{}{Bom, então, adeus.}
{1700}{}{Muito bem. Sente-se, pegue esta faca e me observe... [Você observa e aprende]}
{1800}{}{... Sim, é isso. Parece que você pegou o jeito. Agora, se praticar mais e afiar suas habilidades, talvez um dia seja tão bom quanto eu.}
{1810}{}{Obrigado por me ensinar isso, Irataba. Acho que vou praticar em alguns geckos. Adeus.}
{1900}{}{... Não, não é assim. Está vendo este corte aqui? Você estragou a pele e ela ficou inútil.}
{1901}{}{Não se preocupe, esta pele não valia muito pra começo de conversa. Mas você precisa praticar mais os caminhos do homem do campo. Por ora, não acho que posso ajudar você.}
{1910}{}{É, tá bom. Vou praticar mais então. Adeus.}
