{100}{}{Você não vê um painel de controle neste emissor. Talvez haja outro
 modo de baixar este campo de força.}
{101}{}{Você temporariamente desativa o campo de força com o dano no emissor.}
{102}{}{Você destroi completamente o emissor do campo de força e o campo de força se dissipa.}
{103}{}{Você temporariamente desativa o emissor do campo de força emitter.}
{104}{}{Você falha em fazer qualquer coisa com o emissor do campo de força.}
{105}{}{Você ativa o emissor do campo de força.}
{150}{}{Sua tentativa de re-grampear o emissor de força falha.}
{151}{}{Você desliga o emissor de força.}
{200}{}{Você um campo emissor horrivelmente danificado.}
{201}{}{O emissor esta muito danificado para usar.}
{202}{}{O emissor esta muito danificado para reparar.}
{203}{}{Você nota que o campo esta danificado o bastante para caminhar atraves dele.}
{204}{}{Uma explosão bem posicionada poderia desativar o emissor completamente.}
{205}{}{Você não vê como prender os explosivos ao emissor. Você vai ter que colocá-los perto dele.}
{206}{}{Você não consegue causar dano algum ao emissor.}
