{100}{}{Você vê um charlatão.}
{101}{}{Você vê: Dr. Cleave O. Buker.}
{102}{}{Você vê um vendedor de óleo de cobra.}
{103}{}{Você vê um grande curandeiro.}
{110}{}{Você vê um viajante solitário com uma carroça pintada de cores vivas à distância.}
{150}{}{Eu vou te mostrar, seu jeca degenerado!}
{1000}{}{Olha ali, um viajante! Bem-vindo, bem-vindo! VOCÊ sofre de sífilis? Ferimentos de bala? Escalpelamentos? Inchaços? Escorbuto? Talvez raiva ou... incômodas picadas de cobra? Então chegue mais perto, o Dr. Cleave O. Buker tem a medicação certa pra alguém como você!}
{1001}{}{Ah! Bem-vindo, bem-vindo! Chegue mais perto, o Dr. Cleave O. Buker tem a medicação certa pra alguém como você!}
{1010}{}{Isso soa exatamente como o que eu preciso agora! Me mostre o que você tem pra vender.}
{1011}{}{Uh, UAU!}
{1020}{}{Tá bom, mas é bom você não estar desperdiçando meu tempo.}
{1030}{}{Não, obrigado, e adeus.}
{1031}{}{Uh, na.}
{1100}{}{Um homem que sabe o que é bom pra ele! Dê uma olhada nesta cura milagrosa cem por cento original e duzentos por cento eficaz, e eu garanto que você não vai achar isto mais barato em nenhum outro lugar por aqui!}
{1101}{}{Uma mulher que sabe o que é bom pra ela! Dê uma olhada nesta cura milagrosa cem por cento original e duzentos por cento eficaz, e eu garanto que você não vai achar isto mais barato em nenhum outro lugar por aqui!}
{1102}{}{Dê uma olhada e maravilhe-se!}
{1110}{}{[MAIS]}
{1200}{}{Este produto de alta qualidade, usado NO MUNDO INTEIRO, contra reumatismo! Problemas de fígado! Indigestão e especialmente TODAS as doenças do sangue! ...}
{1210}{}{Quer saber? Me mostre seu produto de novo.}
{1211}{}{Uhm...}
{1220}{}{Beleza, entendi. Adeus.}
{1221}{}{Bye!}
{1300}{}{Desperdiçando seu tempo?! Meu caro senhor! Tomar este remédio vai te dar muito mais tempo!}
{1301}{}{Desperdiçando seu tempo?! Minha cara senhora! Tomar este remédio vai te dar muito mais tempo!}
{1310}{}{[MAIS]}
