{100}{}{Você vê the Bartender.}
{101}{}{Sim, o que você quer?}
{102}{}{Agua.}
{103}{}{Cerveja.}
{104}{}{Licor.}
{105}{}{O que quer que me fara esmagado o mais depressa.}
{106}{}{Nada.}
{107}{}{Tuh?}
{108}{}{Se você não tem as tampinhas, saia!}
{109}{}{Como quiser.}
{110}{}{Eu acho que você teve o bastante, camarada.}
{111}{}{Eu acho que você teve o bastante, dama.}
{112}{}{Sim . . . bem, desapareca.}
{113}{}{Isso será dois tampinhas.}
{114}{}{Certo.}
{115}{}{Não, obrigado.}
{116}{}{Isso será cinco tampinhas.}
{117}{}{Com certeza.}
{118}{}{Isso será dez tampinhas.}
{119}{}{Hmmm, para alguém do seu tamanho . . .}
{120}{}{ }
{121}{}{ dez}
{122}{}{ vinte}
{123}{}{ trinta}
{124}{}{ quarenta}
{125}{}{ cinquenta}
{126}{}{ sessenta}
{127}{}{ setenta}
{128}{}{ oitenta}
{129}{}{ noventa}
{130}{}{ cem}
{131}{}{ tampinhas devem dar.}
{132}{}{Otimo! Isso custara }
{133}{}{ tampinhas de novo.}
{134}{}{Mantenha eles vindo.}
{135}{}{Deixe pra lá.}
{136}{}{Aqui. (O bartender desliza até você um dirty tin cup cheio de alguma}
{137}{}{ água murky. Apos beber a água, você tem um gosto estranho na sua}
{138}{}{ boca.}
{139}{}{Aqui. (O bartender desliza até você outro cup cheio da mesma}
{140}{}{ água murky, e apos você bebe-lá, você e lembrado do quao}
{141}{}{ estranho era o gosto da ultima vez . . .}
{142}{}{Isto deve ser divertido . . . (O bartender continua mandando elas e}
{143}{}{ você perde a conta. Apos um tempo você ouve um muffled thump, então}
{144}{}{ você percebe que você esta deitado no chao com a face pra baixo . . .}
{145}{}{Aqui vamos nos de novo . . . (O bartender alinha elas enquanto todos}
{146}{}{ no bar cantam . . .}
{147}{}{ . . .}
{148}{}{ . . .}
{149}{}{ . . .}
{150}{}{ (Em breve tudo comeca a desaparecer . . .)}
{151}{}{Não pensava que você parecia alguém que conseguiria aguentar o licor}
{152}{}{ deles.}
{153}{}{Isso é uma pena. Nós estamos todos desejando ver você 'fazer'}
{154}{}{ de novo.}
{155}{}{Aww . . . você não vai nos mostrar o quanto aguenta de novo? Bem}
{156}{}{ okay, aqui esta sua cerveja. Algo mais?}
{157}{}{Você tem certeza que você consegue resistir a tentacao? Você fez um ato dos}
{158}{}{ bons da ultima vez. Bem, aqui esta. (O bartender entrega a vcoe uma}
{159}{}{ garrafa de licor.) Algo mais?}
{160}{}{Aqui esta. (O bartender entrega a você uma garrafa de cerveja.) Algo}
{161}{}{ mais?}
{162}{}{Me faca ficar amassado de novo!}
{163}{}{Aqui esta. (O bartender entrega a você uma garrafa de liquor.)}
{164}{}{ Algo mais?}
{165}{}{Você tem um gosto muito ruim na sua boca.}
{166}{}{Você pensa que sua cabeca esta para explodir.}
{167}{}{Você vê um Craps Dealer.}
{168}{}{Você vê um Roulette Dealer.}
{169}{}{Você vê uma maquina de slots.}
{170}{}{Você nota que as odds não parecem certos.}
{171}{}{Você acha que os dados estão carregados.}
{172}{}{Você acha que a mesa esta rigged.}
{173}{}{Facam suas apostas. }
{174}{}{5 tampinhas.}
{175}{}{15 tampinhas.}
{176}{}{25 tampinhas.}
{177}{}{50 tampinhas.}
{178}{}{Não, obrigado.}
{179}{}{Rurh.}
{180}{}{Lamento, mas você não esta em forma pra fazer quaisquer apostas. (Você}
{181}{}{ olha pro jogo e esta thoroughly confuso.)}
{182}{}{Lamento, melhor sorte da proxima vez.}
{183}{}{Vencedor! (Você push.)}
{184}{}{Vencedor! (Você obtem o dobro do seu dinheiro.)}
{185}{}{Vencedor! (Você obtem o triplo do seu dinheiro.)}
{186}{}{Você tem que ter o dinheiro pra jogar, camarada.}
{187}{}{Você tem que ter o dinheiro pra jogar, dama.}
{188}{}{Você nota que as odds parecem certos.}
{189}{}{(Quanto dinheiro você poe?)}
{190}{}{1 tampinha.}
{191}{}{2 tampinhas.}
{192}{}{3 tampinhas.}
{193}{}{4 tampinhas.}
{194}{}{5 tampinhas.}
{195}{}{Nada.}
{196}{}{(Você não sabe o que fazer com ela, mas ela com certeza parece bonita.)}
{197}{}{(Você perdeu.)}
{198}{}{(Você push.)}
{199}{}{(Você obtem o dobro do seu dinheiro.)}
{200}{}{(Você obtem o triplo do seu dinheiro.)}
{201}{}{(Você não tem dinheiro o bastante.)}
{202}{}{Você atualmente tem }
{203}{}{ tampinhas. 
 Quantas você gostaria de apostar?}
{204}{}{  Você quer jogar de novo?}
{205}{}{Você perde todo o seu dinheiro no primeiro giro, mas recupera }
{206}{}{ tampinhas na Rodada Radioativa!}
{207}{}{Vencedor! Você recupera sua aposta e ganha }
{208}{}{Dim Dim Dim! Você ganha o dobro da sua aposta e ainda leva }
{209}{}{JACKPOT! Você ganha o triplo da sua aposta e ainda leva }
{210}{}{ tampinhas na Rodada Radioativa!}
{211}{}{ tampinha na Rodada Radioativa.}
{212}{}{ tampinha na Rodada Radioativa.}
