{100}{}{Você vê um mercador do trem da caravana dos Far Go Traders.}
{101}{}{Você vê um mercador do trem da caravana das Caravanas Escarlates.}
{102}{}{Você vê um mercador do trem da caravana dos Mercadores da Agua.}
{103}{}{Você queria retornar pro Hub? Eu pagarei a você outros 400 scripts.}
{104}{}{Você queria retornar pro Hub? Eu pagarei a você outros 600 scripts.}
{105}{}{Você queria retornar pro Hub? Eu pagarei a você outros 200 scripts.}
{106}{}{Sim.}
{107}{}{Não.}
{108}{}{Ug.}
