{100}{}{Você vê um garoto lean e unkempt.}
{101}{}{Eu não acho que eu deveria falar com você. Vai embora.}
{102}{}{Por que você tem uma arma sacada? Nós não temos nada, nem mesmo peixe!}
{103}{}{Oi. O que quer?}
{104}{}{Como esta a pescaria?}
{105}{}{Eu estou ficando com poucos suprimentos . . .}
{106}{}{Viu algo incomum ultimamente?}
{107}{}{Quer ouvir sobre minhas aventuras nas cavernas dos radscorpions?}
{108}{}{Runk!}
{109}{}{Oi. Você não é aquela pessoa que vai por ai ajudando as pessoas? Você
 deve ter muitas estorias interessantes pra dizer!}
{110}{}{De onde você vem?}
{111}{}{Oi. Eu vejo que você não é estúpido o bastante para estar pescando aqui. O que é que há?}
{112}{}{Não tenho certeza. O papai e eu estivemos vagueando pelas terras devastadas por tanto
 tempo. Nós tinhamos um amigo, um cacador de escorpioes conosco, mas ele enlouqueceu e nós
 tivemos que mata-lo e então nos . . .}
{113}{}{Hmmm, talvez eu não devesse falar sobre isso.}
{114}{}{Diga-me sobre seu pai.}
{115}{}{É quanto aos escorpioes?}
{116}{}{É uma droga. Lamento. Eu não deveria usar a palavra 'droga.' O papai acha que as
 pessoas que dizem droga o tempo todo ou são simpletons com um cerebro morto ou
 perdedores desarticulados. O papai esta sempre tentando soar mais esperto.}
{117}{}{Eu concordo com seu pai.}
{118}{}{Lamento. Eu não sou o único a falar sobre suprimentos.}
{119}{}{Eu vi uma coisa grande como uma aranha gigante com duas cabecas e uma
 cabeca parecia humana. O papai acha que eu suguei radiação demais. Eu não sei.
 Agua contaminada faz coisas ruins com o cerebro.}
{120}{}{Sim, como o que?}
{121}{}{O que é um runk?}
{122}{}{Com certeza!}
{123}{}{A pior coisa sobre cacar radscorpions e esperar pra eles cairem
 em um bom local de emboscada.}
{124}{}{A pior coisa sobre cacar radscorpions e perseguir eles apos eles
 correrem!}
{125}{}{A pior coisa sobre cacar radscorpions e ser ferroado na face pelo
 ferrao deles.}
{126}{}{Sim. Você ouviu sobre os saqueadores que cairam no ninh do radscorpion
 e eles foram todos ferroados e comidos vivos, exceto por um que correu com
 metade da cara dele mastigada!}
{127}{}{Cara, essa foi uma boa!}
{128}{}{Bem, ele e meio alto e entendiante, e eu não tenho certeza de que ele e
 meu pai de verdade. Eu acho que ele deve ter me roubado quando eu era um bebe.
 Mas ele me alimenta na maior parte do tempo então eu gosto dele, eu acho.}
{129}{}{Eles são grandes e eles são malvados e eles estão ficando fora de controle.
 O papai disse que costumava haver herois que vagueavam pelas terras devastadas e
 matavam eles, mas a maioria deles estão mortos agora, eu acho.}
{130}{}{Que tipos de herois?}
{131}{}{Sim, adultos sempre concordam um com o outro. É simplesmente estúpido.}
{132}{}{O grande Henry costumava ir conosco, e ele era melhor do que papai e eu,
 até que ele ficou insano e tentou me estrangular. O papai teve que atirar nele!}
{133}{}{Seu pai e um bom atirador?}
{134}{}{Quem é o grande Henry?}
{135}{}{Bem, isso soa otimo! Apesar diss, melhor eu voltar pra pescaria ou nos
 vamos ficar tão famintos que nos vamos ter que comer você!}
{136}{}{Muitos herois. O cara que fundou a Irmandade do Aço, Roger Maxim, ele
 era um matador de escorpioes de verdade. Quando eu ficar mais velho, eu vou
 descobrir aonde eles estão e me juntar a eles!}
{137}{}{Soa bem.}
{138}{}{É realmente difícil se juntar a Brotherhood. É é uma longa viagem perigosa.}
{139}{}{Ele esta okay, eu creio. Na verdade, eu vi ele acertar um radscorpion
 entre os olhos a setenta jardas, mas foi um tiro fluke.}
{140}{}{Ele era um cara lá embaixo, do sul. Algum tipo de saqueador que tentava
 viver da terra, não das pessoas. Ele era um cara otimo, de verdade, mas as
 vezes, ele ficava louco é uma vez ele . . . uh . . . não importa.}
{141}{}{Sim. Eu vou ser um he-roi, assim como ele. Aposte você nisso!}
{142}{}{Você acha que viver assim e fácil? Eu não tenho medo hardship e não há
 nada seguro aqui, então eu não vou desistir. Eu apenas vou ficar velho o
 bastante pra strike out por conta propria.}
{143}{}{É quanto a batalha entre um radscorpion e um homem?}
{144}{}{So aproximadamente doze vezes . . .}
{145}{}{Uh, sim senhor.}
{146}{}{Eu acho que desta vez eu pegarei um resfriado . . .}
{147}{}{Depressa! Eu estou faminto!}
{148}{}{Tem tanto tempo desde que você pegou alguma coisa, eu esqueci como e
 que é o gosto.}
{149}{}{Pai, você ouviu algo?}
