{100}{}{Comporte-se perto do Doutor, e eu não terei que
 agir de forma medieval na sua cara.}
{101}{}{Nós estamos fechados. Volte mais tarde.}
{102}{}{Eu tenho que ver o Doutor.}
{103}{}{OK, eu o farei.}
{104}{}{É muito importante que eu veja o Doutor.}
{105}{}{Hnnn.}
{106}{}{Tempo bacana que nos estamos tendo, huh?}
{107}{}{Isso e simplesmente muito ruim. Saia daqui, e não volte
 até de manha. Este escritorio não esta aberto de noite.}
{108}{}{Espere um segundo, eu vou checar com o Doutor.}
{109}{}{O que você quer agora?}
{110}{}{Eu tenho que ver o Doutor.}
{111}{}{O Doutor esta disponivel?}
{112}{}{Hnnn!}
{113}{}{De modo algum. O Doutor esta dormindo. Volte mais tarde.}
{114}{}{Eu não sei, por que você não fala com ele você mesmo?}
{115}{}{Sim, OK. Saia.}
{116}{}{Ei, isto e propriedade privada. Melhor você sair, agora.}
{117}{}{Coma meu esterco.}
{118}{}{Se você não sair do meu caminho, você precisara do Doutor
 por razões pessoais.}
{119}{}{Você não sabia que as mulheres são o sexo mais fraco?}
{120}{}{Pensa que eu sou fraca? Observe isto então . . .}
{121}{}{Eu simplesmente sairei.}
{122}{}{Pegue suas ameacas puny threats e corra pra casa pra mamae. Você esta
 falando com um homem de verdade aqui.}
{123}{}{Pensa que eu sou fraca? Observe isto então . . .}
{124}{}{Eu simplesmente sairei.}
{125}{}{Whoa! Se você realmente quer ver ele, vá em frente.}
{126}{}{Bem, quando o Doutor esta aqui?}
{127}{}{O doutor vê os pacientes das 8 as 5. Agora saia daqui.}
{128}{}{Quando o Doutor esta aqui?}
{129}{}{Eu disse pra você não voltar.}
