{100}{}{Você vê Lou dos Nightkin.}
{101}{}{Você vê Sue dos Nightkin.}
{102}{}{Você vê Drew dos Nightkin.}
{103}{}{Você vê Kurt dos Nightkin.}
{104}{}{Você vê Bert dos Nightkin.}
{105}{}{Você vê Tyche dos Nightkin.}
{106}{}{Você vê Mike dos Nightkin.}
{107}{}{Você vê Char dos Nightkin.}
{108}{}{Você vê Reine dos Nightkin.}
{109}{}{Você vê Daggarth dos Nightkin.}
{110}{}{Mim foi dito pra levar você pra fazer algo. Algo a respeito de normais.
 Mim não lembrar o que.}
{111}{}{Mim pensa que normais e estúpido.}
{112}{}{Todos os normais deveriam morrer!}
{113}{}{Uthern um esperto. Uh huh.}
{114}{}{Chefe diz que normais não são nadas.}
{115}{}{Não sei por que chefe quer estes livros.}
{116}{}{Mim feliz que aqueles normais não estão por perto. Eles feios.}
{117}{}{Mim e melhor do que você! Mim e melhor do que você!}
{118}{}{Mim squish você agora!}
{119}{}{Mim squish você agora!}
