{10}{}{Você ganha }
{11}{}{ de experiência.}
{100}{}{O que você quer?}
{101}{}{Deixe-me em paz.}
{102}{}{O que?}
{103}{}{Não mexa com minhas coisas.}
{104}{}{Oi.}
{105}{}{Ei, você ouviu que Set foi desativado?}
{106}{}{Conjunto está morto. Set está morto. Set está morto. . .}
{107}{}{Uungh.}
{108}{}{Ãhh.}
{109}{}{Ei, você ouviu que Set foi morto?}
{110}{}{Set esta morto. Set esta morto. Set esta morto . . .}
{111}{}{Há bastante água para ir para todos.
 Set faz ter certeza disso.}
{112}{}{Eu ouvi que os mutantes got run out da cidade.}
{113}{}{Desde que os mutantes sairam tem sido melhor.}
{114}{}{Ola.}
{200}{}{Você examina a coisa pitiful, mas não consegue pensar em que poderia
 te-lá feito do jeito que é.}
{201}{}{Parece ter sido humano uma vez, ou pelo menos descendeu de humanos.
 Você supoe que a deterioracao no corpo e mais provável devido a acido
 ou radicao.}
{202}{}{O corpo do humanoide parece estar altamente irradiado, mas ainda
 funcionando. Enquanto era uma vez humano, parece ter revertido a um
 estilo de vida mais animalistico.}
{203}{}{O corpo do humanoide parece estar altamente irradiado, e muito da
 materia dos musculos e cerebro parecem ter deteriorado. Contudo,
 indicadores levam você a acreditar que descendeu, como você,
 daqueles que entraram nas vaults.}
{204}{}{Não, obrigado.}
{205}{}{Não, valeu.}
{206}{}{Claro.}
{207}{}{Sim.}
{208}{}{Não.}
{209}{}{Certo.}
{300}{}{Ug.}
{301}{}{Og.}
{302}{}{Ooga.}
{303}{}{Urg.}
{350}{}{[FIM]}
{351}{}{[TCHAU]}
{352}{}{[MAIS]}
{353}{}{[CONTINUAR]}
{354}{}{[COMBATE]}
{355}{}{[DAR DINHEIRO]}
{375}{}{Tchau.}
{376}{}{Adeus.}
{450}{}{A barra está limpa. Vamos nessa!}
{900}{}{A porta velha e gasta parece que poderia ser destruída com um explosivo bem posicionado.}
{905}{}{Woof! Woof!}
{910}{}{Você leva um choque do piso eletrificado.}
{911}{}{ leva um choque do piso eletrificado.}
{912}{}{O nível de energia cai a zero e depois volta a 50% quando os geradores reserva entram em ação.}
{913}{}{Ouve-se um leve zumbido quando a energia volta a fluir pela base.}
{930}{}{Hoooooowl!}
{950}{}{Você tira um tempo para praticar alguns golpes. Você ganha 5 pontos de perícia em Combate Desarmado.}
{951}{}{O rato-toupeira lutador parte para o golpe fatal.}
{952}{}{A luta acabou.}
{953}{}{Você tira um tempo para praticar alguns golpes.}
{954}{}{Você coloca seus óculos de visão noturna.}
{955}{}{Você tira seus óculos de visão noturna.}
{956}{}{Você não aprende nada de novo.}
{957}{}{Você aprende bastante sobre o manejo de armas pesadas.}
{958}{}{Você aprende bastante sobre o manejo de armas de energia.}
{959}{}{Você aprende bastante sobre técnicas médicas.}
{960}{}{Você aprende bastante sobre arrombar fechaduras.}
{961}{}{Você aprende bastante sobre ciência e tecnologia.}
{962}{}{Você aprende bastante sobre explosivos e armadilhas.}
{963}{}{Suas habilidades de comunicação melhoram.}
{964}{}{Você aprende bastante sobre negociação.}
{965}{}{Falta-lhe a inteligência necessária para entender este livro.}
{966}{}{Este livro é um pouco avançado demais para o seu conhecimento atual do assunto.}
{967}{}{Você adquire novas habilidades através do estudo persistente.}
{968}{}{Seu vocabulário melhora.}
{969}{}{Sua eloquência melhora.}
{970}{}{Você aprende bastante sobre sobrevivência ao ar livre.}
{971}{}{Você aprende bastante sobre eletrônica avançada.}
{1003}{}{Você desativa os campos de força.}
{1004}{}{Você invade o computador.}
{1012}{}{AVISO! FUSÃO total do Reator!}
{1013}{}{AVISO! TOXINAS liberadas nos dutos de ar.}
{1050}{}{Você mói o veneno de radscorpion, transformando-o em antídoto.}
{2000}{}{zero}
{2001}{}{um}
{2002}{}{dois}
{2003}{}{três}
{2004}{}{quatro}
{2005}{}{cinco}
{2006}{}{seis}
{2007}{}{sete}
{2008}{}{oito}
{2009}{}{nove}
{2010}{}{dez}
{2011}{}{onze}
{2012}{}{doze}
{2013}{}{treze}
{2014}{}{quatorze}
{2015}{}{quinze}
{2016}{}{dezesseis}
{2017}{}{dezessete}
{2018}{}{dezoito}
{2019}{}{dezenove}
{21020}{}{vinte}
{2021}{}{vinte e um}
{2022}{}{vinte e dois}
{2023}{}{vinte e três}
{2024}{}{vinte e quatro}
{2025}{}{vinte e cinco}
{2026}{}{vinte e seis}
{2027}{}{vinte e sete}
{2028}{}{vinte e oito}
{2029}{}{vinte e nove}
{2030}{}{trinta}
{2031}{}{trinta e um}
{2032}{}{trinta e dois}
{2033}{}{trinta e três}
{2034}{}{trinta e quatro}
{2035}{}{trinta e cinco}
{2036}{}{trinta e seis}
{2037}{}{trinta e sete}
{2038}{}{trinta e oito}
{2039}{}{trinta e nove}
{2040}{}{quarenta}
{2041}{}{quarenta e um}
{2042}{}{quarenta e dois}
{2043}{}{quarenta e três}
{2044}{}{quarenta e quatro}
{2045}{}{quarenta e cinco}
{2046}{}{quarenta e seis}
{2047}{}{quarenta e sete}
{2048}{}{quarenta e oito}
{2049}{}{quarenta e nove}
{2050}{}{cinquenta}
{2051}{}{cinquenta e um}
{2052}{}{cinquenta e dois}
{2053}{}{cinquenta e três}
{2054}{}{cinquenta e quatro}
{2055}{}{cinquenta e cinco}
{2056}{}{cinquenta e seis}
{2057}{}{cinquenta e sete}
{2058}{}{cinquenta e oito}
{2059}{}{cinquenta e nove}
{2060}{}{sessenta}
{2061}{}{sessenta e um}
{2062}{}{sessenta e dois}
{2063}{}{sessenta e três}
{2064}{}{sessenta e quatro}
{2065}{}{sessenta e cinco}
{2066}{}{sessenta e seis}
{2067}{}{sessenta e sete}
{2068}{}{sessenta e oito}
{2069}{}{sessenta e nove}
{2070}{}{setenta}
{2071}{}{setenta e um}
{2072}{}{setenta e dois}
{2073}{}{setenta e três}
{2074}{}{setenta e quatro}
{2075}{}{setenta e cinco}
{2076}{}{setenta e seis}
{2077}{}{setenta e sete}
{2078}{}{setenta e oito}
{2079}{}{setenta e nove}
{2080}{}{oitenta}
{2081}{}{oitenta e um}
{2082}{}{oitenta e dois}
{2083}{}{oitenta e três}
{2084}{}{oitenta e quatro}
{2085}{}{oitenta e cinco}
{2086}{}{oitenta e seis}
{2087}{}{oitenta e sete}
{2088}{}{oitenta e oito}
{2089}{}{oitenta e nove}
{2090}{}{noventa}
{2091}{}{noventa e um}
{2092}{}{noventa e dois}
{2093}{}{noventa e três}
{2094}{}{noventa e quatro}
{2095}{}{noventa e cinco}
{2096}{}{noventa e seis}
{2097}{}{noventa e sete}
{2098}{}{noventa e oito}
{2099}{}{noventa e nove}
{2100}{}{cem}
{3000}{}{}
{3025}{}{}
{3050}{}{Se você tentar isso de novo, vou ter que te matar.}
{3051}{}{Não tenho nada pra roubar, seu idiota.}
{3052}{}{Acho que a gente não se conhece *tão* bem assim.}
{3053}{}{Encoste nisso de novo e você vai ter que pagar.}
{3054}{}{Tire as mãos de mim!}
{3055}{}{Faça isso de novo e eu arranco sua cabeça.}
{3056}{}{Mãos ao alto... digo, mãos longe!}
{3057}{}{Procurando encrenca?}
{3058}{}{Encoste em mim de novo e morra.}
{3059}{}{Só encrenca é de graça.}
{3060}{}{Ei! Pra trás.}
{3061}{}{Olha o que faz!}
{3062}{}{Tá querendo morrer?}
{3063}{}{Tenta isso de novo e eu quebro sua cabeça.}
{3064}{}{Isso é meu; tira a mão!}
{3075}{}{}
{3100}{}{ entrou no grupo}
{3101}{}{ saiu do grupo}
{3300}{}{}
{3325}{}{Por que você não põe tudo de volta onde achou?}
{3326}{}{Sabe, não é bonito pegar o que não é seu.}
{3327}{}{Sai daí, moleque!}
{3328}{}{Agora não vem me dizer que você está "só procurando suas chaves". Cai fora daqui!}
{3329}{}{Seja lá o que estiver procurando, não está aí. Entendeu?}
{3350}{}{}
{3375}{}{}
{3600}{}{}
{3625}{}{Ei, você! Por que está bisbilhotando isso aí?}
{3626}{}{Se você não tem uma chave na mão, é melhor se afastar.}
{3627}{}{Está trancado por um motivo, moleque.}
{3628}{}{Para com isso antes que dê encrenca!}
{3650}{}{}
{3675}{}{}
{3700}{}{Mudar FRM do alvo}
{3701}{}{Power Armor}
{3702}{}{Mantos Roxos}
{3703}{}{Armadura de Combate (F)}
{3704}{}{Traje do V13 (F)}
{3705}{}{Armadura de Couro (F)}
{3706}{}{Mad Maxx (F)}
{3707}{}{Armadura de Metal (F)}
{3708}{}{Traje do V13 (MB)}
{3709}{}{Armadura de Metal (MB)}
{3710}{}{Armadura de Combate (M)}
{3711}{}{Traje do V13 (M)}
{3712}{}{Armadura de Couro (M)}
{3713}{}{Mad Maxx (M)}
{3714}{}{Armadura de Metal (M)}
{3715}{}{Brahmin}
{3716}{}{Dog}
{3717}{}{Mr Handy}
{3718}{}{Lt Lou (Needs patch by ColJack)}
{3719}{}{Rato-Toupeira}
{3720}{}{Couro Preto (SM)}
{3721}{}{Mutante Verde}
{3722}{}{Radscorpion Grande}
{3723}{}{Floater}
{3724}{}{Rat}
{3725}{}{Centaur}
{3726}{}{Manto Azul}
{3727}{}{Child}
{3728}{}{Ghoul Verde}
{3729}{}{Ser Radiante}
{3730}{}{Power Armor (Sem Capacete)}
{3731}{}{Monk}
{3732}{}{Blonde}
{3733}{}{Punk}
{3734}{}{Armadura de Metal (F Calça Amarela)}
{3735}{}{Tandi}
{3736}{}{Slut}
{3737}{}{Traje do V13 (F Ruiva)}
{3738}{}{Camponês Negro (Camisa Vermelha)}
{3739}{}{Camponês (Camisa Amarela)}
{3740}{}{Camponês Careca (Camisa Verde)}
{3741}{}{Anão Ruivo}
{3742}{}{Loser}
{3743}{}{Armadura de Couro (M Careca)}
{3744}{}{Jaqueta de Couro (Brutamontes Cabeludo)}
{3745}{}{Camponês (Boné Azul)}
{3746}{}{Deathclaw Adulta}
{3747}{}{Mantis}
{3748}{}{Robobrain}
{3749}{}{Olho Flutuante}
{3750}{}{Rato-Porco}
{3751}{}{Mantos Marrons}
{3752}{}{Doutor Careca}
{3753}{}{Egg}
{3754}{}{Radscorpion Pequeno}
{3755}{}{Deathclaw Pequena}
{3761}{}{Robô Sentinela}
{3764}{}{Cidadão}
{3769}{}{Cidadã}
{3774}{}{Ghoul Neutro}
{3778}{}{Traje de Vault (F Preto)}
{3779}{}{Mantos Pretos}
{3782}{}{Cop}
{3784}{}{Technician}
{3798}{}{[FIM]}
{3799}{}{ }
{3800}{}{[VOLTAR]}
{3801}{}{[VOLTAR AO MENU]}
{3802}{}{[SAIR]}
{3803}{}{Inserir PID do item (formato 4 dígitos:0000) }
{3804}{}{Primeiro Número (1000)}
{3805}{}{Segundo Número (100)}
{3806}{}{Terceiro Número   (10)}
{3807}{}{Quarto Número   (1)}
{3808}{}{PID: }
{3809}{}{Nome do Item: }
{3810}{}{Objeto-Alvo Inválido}
{3900}{}{}
{3925}{}{Ei você! O que está fazendo aí?}
{3926}{}{Você não deveria estar aqui!}
{3927}{}{Se você acha que vai passar por mim assim, pode esquecer!}
{3928}{}{É melhor você não estar tramando o que eu acho que está, forasteiro.}
{3929}{}{O quê? Acha que eu não te noto? Cai fora daqui!}
{3950}{}{}
{3975}{}{}
{4000}{}{Verificar resistências e limiares de dano.}
{4001}{}{%}
{4002}{}{ foi curado.}
{4003}{}{A perna esquerda aleijada sarou.}
{4004}{}{A perna direita aleijada sarou.}
{4005}{}{O braço esquerdo aleijado sarou.}
{4006}{}{O braço direito aleijado sarou.}
{4007}{}{O olho danificado sarou.}
{4008}{}{ não está ferido.}
{4010}{}{LIMIARES E RESISTÊNCIAS:}
{4011}{}{/}
{4012}{}{--}
{4100}{}{Normal:     }
{4101}{}{Laser:      }
{4102}{}{Fogo:       }
{4103}{}{Plasma:     }
{4104}{}{Elétrico:   }
{4105}{}{PEM:        }
{4106}{}{Explosão:   }
{4107}{}{Radiação:   }
{4108}{}{Veneno:     }
{4109}{}{ parece saudável.}
{4200}{}{}
{4225}{}{}
{4250}{}{}
{4275}{}{}
{4300}{}{Sim, Mestre?}
{4301}{}{}
{4500}{}{}
{4525}{}{}
{4550}{}{}
{4575}{}{}
{4600}{}{}
{4800}{}{}
{4825}{}{}
{4850}{}{}
{4875}{}{}
{4900}{}{}
{5100}{}{}
{5125}{}{}
{5150}{}{}
{5175}{}{}
{5400}{}{Fique longe daí.}
{9000}{}{Reparos Concluídos.}
{9001}{}{Rearmamento Concluído.}
{9002}{}{Reparando Dano Estrutural.}
{9003}{}{Nenhum Dano Estrutural Detectado.}
{9004}{}{Função de reparo.}
{9005}{}{Insira o Comando.}
{9006}{}{Guardar este local.}
{9007}{}{Inicializando Função de Sentinela.}
{9008}{}{Equipar Armamento.}
{9009}{}{Você não tem uma no seu inventário.}
{9010}{}{Rifle de Plasma.}
{9011}{}{Rifle Laser.}
{9012}{}{Minigun.}
{9013}{}{Laser Gatling.}
{9014}{}{Armas.}
{9015}{}{Munição.}
{9016}{}{5mm JHP.}
{9017}{}{5mm AP.}
{9018}{}{Célula de Energia.}
{9019}{}{O Mr. Handy está programado para usar armas de energia e miniguns.}
{10000}{}{Preciso te dizer uma coisa.}
{10001}{}{Você deveria se curar agora.}
{10002}{}{Preciso que você espere aqui até eu voltar.}
{10003}{}{Guarde sua arma.}
{10004}{}{Fique perto de mim.}
{10005}{}{Não se afaste muito.}
{10006}{}{Devíamos nos espalhar um pouco.}
{10007}{}{É só isso por enquanto.}
{10008}{}{Precisamos mudar nossa distância um do outro.}
{10009}{}{Preciso falar com você sobre seu equipamento.}
{10010}{}{Pensando bem, acho que esta distância está boa por ora.}
{10011}{}{Na verdade, acho que não há nada que eu precise saber sobre seu equipamento.}
{10012}{}{Preciso que você tire a armadura que está usando.}
{10013}{}{Preciso saber que tipo de armas você sabe usar.}
{10100}{}{Vamos.}
