{101}{}{Eu não preciso dos seus servicos agora. Talvez mais tarde.}
{102}{}{Ajuda! Me Salva!}
{103}{}{Você deve morrer pelo que você fez!}
{104}{}{Me poupe! Por favor!}
{105}{}{Eles já estão mortos? Talvez haja mais deles!}
{106}{}{Sua chegada foi bem na hora, meu amigo. Permita-me presentear você com
 um pequeno     da minha gratidão.}
{107}{}{Sua chegada foi bem na hora, minha amiga. Permita-me presentear você com
 um pequeno token da minha gratidão.}
{110}{}{O comerciante te agradece pela ajuda.}
