{100}{}{Você vê um membro da gangue dos Skulz.}
{101}{}{Ei! O que você pensa que esta fazendo?!}
{102}{}{Você esta no territorio dos Skulz, estranho. Melhor você sair.}
{103}{}{Tem algumas tampinhas?}
{104}{}{O que você esta olhando?}
{105}{}{Saia daqui.}
{106}{}{Zzzzz}
{107}{}{Cara, com certeza esta quente hoje.}
{108}{}{Eu estou faminto.}
{109}{}{Vamos fazer alguma coisa.}
{110}{}{Por que nós não rough someone up?}
{111}{}{Eu quero ter um pouco de diversão.}
{112}{}{Yawn . . .}
