{100}{}{Você vê um morador da Vault.}
{101}{}{Eu não posso acreditar que você nos traiu!}
{102}{}{Traidor!}
{103}{}{Eu odeio você. Por que você voltou?}
{104}{}{Eu espero que você se engasgue na sua vilania!}
{105}{}{}
{106}{}{}
{107}{}{}
{108}{}{}
{109}{}{Obrigado a você por nos salvar.}
{110}{}{Eu estava com um pouco de incerteza se você conseguiria faze-lo,
 mas eu confio em você agora.}
{111}{}{Obrigado a você! Obrigado a você!}
{112}{}{Você é um heroi. Meu garotinho quer se como você quando ele crescer.
 Eu não sei se eu gosto disso.}
{113}{}{Você é uma heroina. Minha garotinha quer ser como você quando ela
 crescer. Eu não sei se eu gosto disso.}
{114}{}{Você é um cara swell!}
{115}{}{Você é uma garota swell!}
{116}{}{Você tem certeza que você precisa disso aqui?}
{117}{}{Isso é uma arma!}
{118}{}{Você realmente usou isso contra alguém?}
{119}{}{Por que você acha que é necessario carregar
 uma arma aqui?}
{120}{}{É bom ver você de novo.}
{121}{}{Eu estou feliz que você esta indo bem.}
{122}{}{Você parece OK pra mim. Todos esses rumores devem
 ser mentiras.}
{123}{}{Oi }
{124}{}{. Mantenha
 o bom trabalho.}
{125}{}{Eu espero que tudo esteja indo bem lá fora.
 Nós com certeza poderiamos usar a água.}
{126}{}{Nós estamos comecando a ficar sem água. Isto
 é terrível!}
{127}{}{Por favor apresse-se e ache aquele chip. Nós
 precisamos de você.}
{128}{}{Eu estou feliz que você esteja indo bem.
 Mantenha o bom trabalho.}
{129}{}{Eu odeio dizer isto, mas se você não achar
 o Chip de Agua em breve nos vamos todos
 morrer.}
{130}{}{Minha pequena esta sempre chorando no meio
 da noite por um drink de água e eu não posso
 dar nada pra ela.}
{131}{}{Nós não vamos conseguir, vamos?}
{132}{}{As rações de água estão chegando ao fim.}
{133}{}{A secao hidroponica fechou agora. Significa
 que o nosso suprimento de comida esta se esgotando.}
{134}{}{Hmm. Você ainda parece humano pra mim. Não
 pode ser tão ruim lá fora.}
{135}{}{Oi }
{136}{}{.}
{137}{}{Eu espero que você esteja indo bem na sua busca.}
{138}{}{Vejo você por ai.}
{139}{}{Você falou com o Supervisor recentemente?}
{140}{}{O Supervisor esta muito preocupado a respeito do
 status da sua missao.}
{141}{}{Você precisa se apressar. Nós não podemos afford
 qualquer falha da sua parte.}
{142}{}{Eu espero que você esteja fazendo o melhor que você pode.}
{143}{}{Isto não é hora de descansar, volte pra lá.}
{144}{}{Isto não é o que você deveria estar fazendo,
 e?}
{145}{}{Nós vamos morrer e e sua culpa.}
{146}{}{Não fique parado aqui, volte lá pra fora! Agora!}
{147}{}{Se nos morrermos, será sua culpa.}
{148}{}{O lado de fora corrompeu você, não e?}
{149}{}{Apenas me deixe em paz.}
{150}{}{Eu acho que você deveria deixar eu é minha familia
 em paz, }
{151}{}{. Seria
 o melhor.}
{152}{}{Você deveria estar envergonhado de si próprio.}
{153}{}{É pensar que eu costumava gostar de você.}
{154}{}{O morador da Vault se recusa a falar com você.}
{155}{}{Um olhar vazio encontra seu pedido para conversar.}
{156}{}{Eu me arrependo que nos escolhemos você para ir lá fora.}
{157}{}{A água e foul, mas sua companhia e pior.}
{158}{}{Vai embora. Apenas saia. Você pode redimir a si próprio
 achando aquele Chip de Agua.}
{159}{}{Eu espero que você esteja satifeito.}
{160}{}{O morador da Vault se recusa a conversar com você.}
{161}{}{Você causou isto! Em primeiro lugar você tambem
 provavelmente quebrou o Chip de Agua!}
{162}{}{Eu odeio você. Eu realmente, realmente odeio você.}
{163}{}{O morador da Vault apenas lacrimeja grandes lagrimas.}
{164}{}{Seu pedido para conversar e encontrado com um olhar frio.}
{165}{}{Obrigado a você.}
{166}{}{Esta tarde. Volte outra hora.}
{167}{}{O morador da Vault esta descansando.}
