{100}{}{Você vê um guarda ghoul.}
{101}{}{Nós vamos levar você ao Set. Eu acho que ele vai querer falar com você,
 pessoalmente.}
{102}{}{Você não deveria estar aqui . . .}
{103}{}{Garret me disse que estava ok. Ele me disse pra pegar algo do quarto do
 Set pra ele. Você sabe aonde e?}
{104}{}{OK. Eu sairei então.}
{105}{}{Hã?}
{106}{}{Isso não soa correto. Melhor você vir comigo.}
{107}{}{Eu acho que não.}
{108}{}{OK.}
{109}{}{Eu não acho que você queira ir para aquela sala.}
{110}{}{Por que?}
{111}{}{Certo, eu não quero ir para aquela sala. Agora o que?}
{112}{}{Eu acho que seria melhor se você saisse.}
{113}{}{Nós estamos aqui pra ter certeza de que pessoas que não pertencam ao
 quarto do Set não entrem nele. Não pra seguranca do Set realmente, mas para a
 deles. Algo mais?}
{114}{}{Sim. Seus cardacos estão desamarrados.}
{115}{}{Não. Obrigado.}
{116}{}{Eu estou no dever. Vai embora.}
