{100}{}{O quadro desta porta de segurança tem restos de tinta azul.}
{101}{}{Você recebe um leve choque do campo elétrico na porta e dá um ponto
 de dano.}
{102}{}{Você recebe um forte choque do campo elétrico na porta. Você sustenta}
{103}{}{points of damage}
{104}{}{Você força a porta aberta.}
{105}{}{A porta está trancada.}
{106}{}{Autorização concedida. Agora desarmar o campo elétrico.}
{107}{}{Você não está autorizado a entrar nesta sala.}
{108}{}{Este item não afeta os sistemas de segurança.}
{109}{}{Você escolhe a fechadura na porta de segurança.}
{110}{}{Parece haver algum tipo de medida de segurança nesta porta.}
{111}{}{Você não conseguiu pegar a fechadura na porta.}
{112}{}{Esta habilidade não tem efeito na porta.}
{113}{}{Você desarmar o sistema de segurança do campo elétrico na porta.}
{114}{}{Você intesificou o poder do campo elétrico.}
{115}{}{Você não consegue desarmar o campo elétrico.}
{116}{}{Você escolhe a fechadura da porta sem desligar o sistema de segurança.}
{117}{}{Você não escolhe a fechadura e recebe sérios danos do sistema de segurança.}
{118}{}{Você não escolhe o bloqueio e recebe dano do sistema de segurança.}
{119}{}{Você está chocado com o sistema de segurança e perde a concentração para escolher o bloqueio.}
{120}{}{Você recebe um choque intenso do sistema de segurança e perde a concentração para escolher o bloqueio.}
{121}{}{Você falha ao tentar selecionar esse bloqueio e destruir suas escolhas}
{122}{}{Você não escolhe esse bloqueio.}
{123}{}{Você vê uma porta robusta e enferrujada.}
{124}{}{Você vê uma porta destrancada com tinta vermelha.}
{125}{}{Você vê uma porta destrancada com tinta vermelha.}
{126}{}{Você vê uma porta destrancada com um campo vermelho em movimento na frente dela.}
{127}{}{Você vê uma porta destrancada com um sistema de segurança de alta tensão armado sobre ela.}
{128}{}{Você vê uma porta com tinta vermelha.}
{129}{}{Você vê uma porta com tinta vermelha.}
{130}{}{Você vê uma porta com um campo vermelho em movimento na frente dela.}
{131}{}{Você vê uma porta com um sistema de segurança de alta tensão armado sobre ela.}
{132}{}{Você vê uma porta trancada com tinta vermelha.}
{133}{}{Você vê uma porta trancada com tinta vermelha.}
{134}{}{Você vê uma porta trancada com um campo vermelho em movimento na frente dela}
{135}{}{Você vê uma porta trancada com um sistema de segurança de alta tensão armado sobre ela.}
{136}{}{A fechadura desta porta vermelha parece precisar de uma senha especial.}
{137}{}{A fechadura desta porta vermelha parece precisar de uma senha especial.}
{138}{}{A fechadura desta porta parece precisar de uma senha especial. Além disso, você percebe um campo vermelho cintilante diante da porta.}
{139}{}{A fechadura desta porta parece precisar de uma senha vermelha especial. Além disso, você observa um sistema de segurança de alta voltagem armado sobre ele.}
{140}{}{Você vê uma porta destrancada.}
{141}{}{Você vê uma porta destrancada.}
{142}{}{Você vê uma porta destrancada com um campo em movimento na frente dela.}
{143}{}{Você vê uma porta destrancada com um sistema de segurança de alta tensão armado sobre ela.}
{144}{}{Você vê uma porta.}
{145}{}{Você vê uma porta.}
{146}{}{Você vê uma porta com um campo em movimento na frente dela.}
{147}{}{Você vê uma porta com um sistema de segurança de alta tensão armado sobre ela.}
{148}{}{Você vê uma porta trancada.}
{149}{}{Você vê uma porta trancada.}
{150}{}{Você vê uma porta trancada com um campo em movimento na frente dela}
{151}{}{Você vê uma porta trancada com um sistema de segurança de alta tensão armado sobre ela.}
{152}{}{A fechadura desta porta parece precisar de uma senha especial.}
{153}{}{A fechadura desta porta parece precisar de uma senha especial.}
{154}{}{A fechadura desta porta parece precisar de uma senha especial. Além disso, você percebe um campo cintilante diante da porta.}
{155}{}{A fechadura desta porta parece precisar de uma senha especial. Além disso, você observa um sistema de segurança de alta voltagem armado sobre ele.}
{156}{}{Você vê uma porta destrancada com tinta azul.}
{157}{}{Você vê uma porta destrancada com tinta azul.}
{158}{}{Você vê uma porta destrancada com um campo azul em movimento na frente dela.}
{159}{}{Você vê uma porta destrancada com um sistema de segurança de alta tensão armado sobre ela.}
{160}{}{Você vê uma porta com tinta azul.}
{161}{}{Você vê uma porta com tinta azul.}
{162}{}{Você vê uma porta com um campo azul em movimento na frente dela}
{163}{}{Você vê uma porta com um sistema de segurança de alta tensão armado sobre ela.}
{164}{}{Você vê uma porta trancada com tinta azul.}
{165}{}{Você vê uma porta trancada com tinta azul.}
{166}{}{Você vê uma porta trancada com um campo azul em movimento na frente dela.}
{167}{}{Você vê uma porta trancada com um sistema de segurança de alta tensão armado sobre ela.}
{168}{}{A fechadura desta porta azul parece precisar de uma senha especial.}
{169}{}{A fechadura desta porta azul parece precisar de uma senha especial.}
{170}{}{A fechadura desta porta parece precisar de uma senha especial. Além disso, você percebe um campo azul cintilante diante da porta.}
{171}{}{A fechadura desta porta parece precisar de uma senha especial. Além disso, você observa um sistema de segurança de alta voltagem armado sobre ele.}
{172}{}{Você vê uma porta destrancada com tinta azul.}
{173}{}{Você vê uma porta destrancada com tinta azul.}
{174}{}{Você vê uma porta destrancada com um campo azul em movimento na frente dela.}
{175}{}{Você vê uma porta destrancada com um sistema de segurança de alta tensão armado sobre ela.}
{176}{}{Você vê uma porta com tinta azul.}
{177}{}{Você vê uma porta com tinta azul.}
{178}{}{Você vê uma porta com um campo azul em movimento na frente dela.}
{179}{}{Você vê uma porta com um sistema de segurança de alta tensão armado sobre ela.}
{180}{}{Você vê uma porta trancada com tinta azul.}
{181}{}{Você vê uma porta trancada com tinta azul.}
{182}{}{Você vê uma porta trancada com um campo azul em movimento na frente dela.}
{183}{}{Você vê uma porta trancada com um sistema de segurança de alta tensão armado sobre ela.}
{184}{}{A fechadura desta porta azul parece precisar de uma senha especial.}
{185}{}{A fechadura desta porta azul parece precisar de uma senha especial.}
{186}{}{A fechadura desta porta parece precisar de uma senha especial. Além disso, você percebe um campo azul cintilante diante da porta.}
{187}{}{A fechadura desta porta parece precisar de uma senha azul especial. Além disso, você observa um sistema de segurança de alta voltagem armado sobre ele.}
{188}{}{Você vê uma porta com tinta vermelha.}
{189}{}{Você vê uma porta com um campo vermelho em movimento na frente dela.}
{190}{}{Você vê uma segurança de alta voltagem nesta porta vermelha.}
{191}{}{Você vê uma segurança de alta voltagem nesta porta vermelha. Você quer saber se há uma senha para contornar isso.}
{192}{}{Você vê uma porta.}
{193}{}{Você vê uma porta com um campo em movimento na frente dela.}
{194}{}{Você vê uma sistema de segurança de alta voltagem nesta porta.}
{195}{}{Você vê uma sistema de segurança de alta voltagem nesta porta. Você quer saber se há uma senha para contornar isso.}
{196}{}{Você vê uma porta com tinta azul.}
{197}{}{Você vê uma porta com um campo azul em movimento na frente dela.}
{198}{}{Você vê uma segurança de alta voltagem nesta porta azul.}
{199}{}{Você vê uma sistema de segurança de alta voltagem nesta porta azul. Você quer saber se há uma senha para contornar isso.}
{200}{}{Você vê uma porta com tinta azul.}
{201}{}{Você vê uma porta com um campo azul em movimento na frente dela.}
{202}{}{Você vê uma segurança de alta voltagem nesta porta azul.}
{203}{}{Você vê uma sistema de segurança de alta voltagem nesta porta azul. Você quer saber se há uma senha para contornar isso.}
{204}{}{Você percebe que há uma armadilha nessa porta.}
{205}{}{O elevador está inoperante. Parece que precisa de mais energia do que a energia de emergência pode suportar.}
