{100}{}{A moldura desta porta de segurança tem restos de tinta vermelha.}
{101}{}{Você recebe um choque leve do campo eletrico na porta e leva um ponto
 de dano.}
{102}{}{Você recebe um choque forte do campo eletrico na porta. Você sofre }
{103}{}{ pontos de dano.}
{104}{}{Você força a porta pra abri-lá.}
{105}{}{A porta esta trancada.}
{106}{}{Autorizaçao garantida. Agora desarmando o campo eletrico.}
{107}{}{Você não esta autorizado a entrar nesta sala.}
{108}{}{Este item não tem efeito nos sistemas de segurança.}
{109}{}{Você abre a tranca na porta de segurança.}
{110}{}{Parece haver algum tipo de medida de segurança nesta porta.}
{111}{}{Você falhou em abrir a tranca na porta.}
{112}{}{Esta tecnica não tem efeito na porta.}
{113}{}{Você desarmar o campo eletrico on the porta.}
{114}{}{Você intesificou a força do campo eletrico.}
{115}{}{Você falha em desarmar o campo eletrico.}
{116}{}{Você abre a tranca na porta sem alertar o sistema de segurança.}
{117}{}{Você falha em abrir a tranca e leva um dano serio do sistema de segurança.}
{118}{}{Você falha em abrir a tranca e leva dano do sistema de segurança.}
{119}{}{Você e eletrocutado pelo sistema de segurança e perde a concentraçao pra abrir a tranca.}
{120}{}{Você toma um choque intenso do sistema de segurança e perde a concentraçao pra abrir a tranca.}
{121}{}{Você falha totalmente em tentar abrir esta tranca e destroi suas gazuas.}
{122}{}{Você falha em abrir esta tranca.}
{123}{}{Você vê uma porta reforçada e enferrujada.}
{124}{}{Você vê uma porta destrancada com tinta amarela nela.}
{125}{}{Você vê uma porta destrancada com tinta amarela nela.}
{126}{}{Você vê uma porta destrancada com um campo amarelo se movendo na frente dela.}
{127}{}{Você vê uma porta destrancada com um sistema de segurança de alta voltagem armado nela.}
{128}{}{Você vê uma porta com tinta amarela nela.}
{129}{}{Você vê uma porta com tinta amarela nela.}
{130}{}{Você vê uma porta com um campo vermelho se movendo na frente dela.}
{131}{}{Você vê uma porta com um sistema de segurança de alta voltagem armado nela.}
{132}{}{Você vê uma porta trancada com tinta amarela nela.}
{133}{}{Você vê uma porta trancada com tinta amarela nela.}
{134}{}{Você vê uma porta trancada com um campo amarelo se movendo na frente dela.}
{135}{}{Você vê uma porta trancada com um sistema de segurança de alta voltagem armado nela.}
{136}{}{A tranca nesta porta amarela parece precisar de uma chave-passe especial.}
{137}{}{A tranca nesta porta amarela parece precisar de uma chave-passe especial.}
{138}{}{A tranca nesta porta parece precisar de uma chave de passe especial. Adicionalmente, você nota um campo amarelo shimmering diante da porta.}
{139}{}{A tranca nesta porta parece precisar de uma chave de passe amarela especial. Adicionalmente, você nota um sistema de segurança de alta voltagem armado nela.}
{140}{}{Você vê uma porta destrancada.}
{141}{}{Você vê uma porta destrancada.}
{142}{}{Você vê uma porta destrancada com um campo se movendo na frente dela.}
{143}{}{Você vê uma porta destrancada com um sistema de segurança de alta voltagem armado nela.}
{144}{}{Você vê uma porta.}
{145}{}{Você vê uma porta.}
{146}{}{Você vê uma porta com um campo se movendo na frente dela.}
{147}{}{Você vê uma porta com um sistema de segurança de alta voltagem armado nela.}
{148}{}{Você vê uma porta trancada.}
{149}{}{Você vê uma porta trancada.}
{150}{}{Você vê uma porta trancada com um campo se movendo na frente dela.}
{151}{}{Você vê uma porta trancada com um sistema de segurança de alta voltagem armado nela.}
{152}{}{A tranca nesta porta parece precisar de uma chave de passe especial.}
{153}{}{A tranca nesta porta parece precisar de uma chave de passe especial.}
{154}{}{A tranca nesta porta parece precisar de uma chave de passe especial. Adicionalmente, você nota um campo shimmering diante da porta.}
{155}{}{A tranca nesta porta parece precisar de uma chave de passe especial. Adicionalmente, você nota um sistema de segurança de alta voltagem armado nela.}
{156}{}{Você vê uma porta destrancada com tinta vermelha nela.}
{157}{}{Você vê uma porta destrancada com tinta vermelha nela.}
{158}{}{Você vê uma porta destrancada com um campo vermelho se movendo na frente dela.}
{159}{}{Você vê uma porta destrancada com um sistema de segurança de alta voltagem armado nela.}
{160}{}{Você vê uma porta com tinta vermelha nela.}
{161}{}{Você vê uma porta com tinta vermelha nela.}
{162}{}{Você vê uma porta com um campo vermelho se movendo na frente dela.}
{163}{}{Você vê uma porta com um sistema de segurança de alta voltagem armado nela.}
{164}{}{Você vê uma porta trancada com tinta vermelha nela.}
{165}{}{Você vê uma porta trancada com tinta vermelha nela.}
{166}{}{Você vê uma porta trancada com um campo vermelho se movendo na frente dela.}
{167}{}{Você vê uma porta trancada com um sistema de segurança de alta voltagem armado nela.}
{168}{}{A tranca nesta porta vermelha parece precisar de uma chave-passe especial.}
{169}{}{A tranca nesta porta vermelha parece precisar de uma chave-passe especial.}
{170}{}{A tranca nesta porta parece precisar de uma chave-passe especial. Adicionalmente, você nota um campo vermelho levemente tremulo diante da porta.}
{171}{}{A tranca nesta porta parece precisar de uma chave de passe especial. Adicionalmente, você nota um sistema de segurança de alta voltagem armado nela.}
{172}{}{Você vê uma porta destrancada com tinta vermelha nela.}
{173}{}{Você vê uma porta destrancada com tinta vermelha nela.}
{174}{}{Você vê uma porta destrancada com um campo vermelho se movendo na frente dela.}
{175}{}{Você vê uma porta destrancada com um sistema de segurança de alta voltagem armado nela.}
{176}{}{Você vê uma porta com tinta vermelha nela.}
{177}{}{Você vê uma porta com tinta vermelha nela.}
{178}{}{Você vê uma porta com um campo vermelho se movendo na frente dela.}
{179}{}{Você vê uma porta com um sistema de segurança de alta voltagem armado nela.}
{180}{}{Você vê uma porta trancada com tinta vermelha nela.}
{181}{}{Você vê uma porta trancada com tinta vermelha nela.}
{182}{}{Você vê uma porta trancada com um campo vermelho se movendo na frente dela.}
{183}{}{Você vê uma porta trancada com um sistema de segurança de alta voltagem armado nela.}
{184}{}{A tranca nesta porta vermelha parece precisar de uma chave-passe especial.}
{185}{}{A tranca nesta porta vermelha parece precisar de uma chave-passe especial.}
{186}{}{A tranca nesta porta parece precisar de uma chave-passe especial. Adicionalmente, você nota um campo vermelho levemente tremulo diante da porta.}
{187}{}{A tranca nesta porta parece precisar de uma chave-passe vermelha especial. Adicionalmente, você nota um sistema de segurança de alta voltagem armado nela.}
{188}{}{Você vê uma porta com tinta amarela nela.}
{189}{}{Você vê uma porta com um campo amarelo se movendo na frente dela.}
{190}{}{Você vê um sistema de segurança de alta voltagem nesta porta amarela.}
{191}{}{Você vê um sistema de segurança de alta voltagem nesta porta amarela. Você imagina se há uma chave-passe pra evita-lo.}
{192}{}{Você vê uma porta.}
{193}{}{Você vê uma porta com um campo se movendo na frente dela.}
{194}{}{Você vê um sistema de segurança de alta voltagem nesta porta.}
{195}{}{Você vê um sistema de segurança de alta voltagem nesta porta. Você imagina se há uma chave-passe pra evita-lo.}
{196}{}{Você vê uma porta com tinta vermelha nela.}
{197}{}{Você vê uma porta com um campo vermelho se movendo na frente dela.}
{198}{}{Você vê um sistema de segurança de alta voltagem nesta porta vermelha.}
{199}{}{Você vê um sistema de segurança de alta voltagem nesta porta vermelha. Você imagina se há uma chave-passe pra evita-lo.}
{200}{}{Você vê uma porta com tinta vermelha nela.}
{201}{}{Você vê uma porta com um campo vermelho se movendo na frente dela.}
{202}{}{Você vê um sistema de segurança de alta voltagem nesta porta vermelha.}
{203}{}{Você vê um sistema de segurança de alta voltagem nesta porta vermelha. Você imagina se há uma chave-passe pra evita-lo.}
{204}{}{Você nota que há uma armadilha nesta porta.}
{205}{}{O elevador esta inoperavel. Parece precisar de força.}
