{100}{}{System:
                                                         Primary Power:                  OFF-LINE
                           Secondary Power:               ON-LINE}
{101}{}{Gerenciamento de Energia}
{102}{}{P*w*r*M*n*g*m*nt}
{103}{}{Sair}
{104}{}{Gerenciamento dos Sistemas de Energia}
{105}{}{Energia Primária}
{106}{}{Energia de Emergência}
{107}{}{VOLTAR}
{108}{}{Gerenciamento de Energia Primária:       OFFLINE}
{109}{}{Reinicializar Energia Primária}
{110}{}{VOLTAR}
{111}{}{Primary Power Management:
                                          ERROR! ERROR! ERROR!
                                               Primary System Initialization Failed}
{112}{}{Diagnose}
{113}{}{VOLTAR}
{114}{}{Failure:        Generator Level 6
                                       0 Feed Return:  Inoperable
                                          Service Needed}
{115}{}{VOLTAR}
{116}{}{Gerenciamento de Energia de Emergência:     ONLINE}
{117}{}{Desativar Energia de Emergência}
{118}{}{VOLTAR}
{119}{}{System:
                                                         Primary Power:                  ON-LINE
                           Emergency Power:                ON STANDBY}
{120}{}{Gerenciamento de Energia}
{121}{}{Sair}
{122}{}{Gerenciamento de Energia Primária:       ONLINE}
{123}{}{Desativar Energia Primária}
{124}{}{VOLTAR}
{125}{}{System:
                                                         Primary Power:                  ON-LINE}
{126}{}{d*s*bl* pr*m*ry p*w*r}
{127}{}{Desativar Energia Primária}
{128}{}{Sair}
{129}{}{P*w*r S*st*ms M*n*g*m*nt}
{130}{}{pr*m*ry p*w*r}
{131}{}{*m*rg*ncy p**er}
{132}{}{VOLTAR}
{133}{}{pr*m*r p*w*r m*n*g*m*n*}
{134}{}{r**n*t**l*z* pr*m*ry p*w*r}
{135}{}{VOLTAR}
{136}{}{pr*m*r* p*w*r m*n*g*m*nt:
                                          *RR*R! *RR*R! *RR*R*!
                                              g*n*r*t*r n**ds r*p**r}
{137}{}{VOLTAR}
{138}{}{*m*rg*nc* p*w*r m*n*g*m*nt:     *N-L*N*}
{139}{}{System:
                                                         Primary Power:                  OFF-LINE
                           Emergency Power:               OFF-LINE}
{140}{}{Ativar Energia de Emergência}
{141}{}{d**gn*s* pr*m*r* p*w*r}
{142}{}{pr*m*r* p*w*r *v*l**t**n}
{143}{}{*n*bl* *m*rg*nc* p*w*r}
{144}{}{p*w*r m*n*g*m*nt r*s*rc*}
{145}{}{Sair}
{146}{}{S*st*m *rr*r!
                                                         *nv*l*d *s*r. n*t*f* *dm*n*str*t**n.
                          S*st*m h*lt*d.}
{147}{}{Sair}
{148}{}{d*s*bl* *m*rg*nc* p*w*r}
{200}{}{Conceda-me acesso ao Mainframe.}
{201}{}{Acesso negado. Encerrando entrada.}
{202}{}{Acesso Concedido.}
{203}{}{Menu Principal}
{204}{}{Sair do Mainframe}
{205}{}{Encerrar Programa}
{206}{}{Selecionar Opção}
{207}{}{Informações da Base}
{208}{}{Informações de Segurança}
{209}{}{Informações de Pesquisa}
{210}{}{Terminal de Energia}
{211}{}{West Tech Research Facility:
                                             Founded in 2002 as a private contractor for the
 United States government, the company initially consisted of two divisions--
the Advanced Weapons Research and the Biomedical Sciences divisions.}
{241}{}{ In 2069,
 West Tech was the single largest contractor for the United States government;
 its largest contract being Powered Infantry Armor Model T-51b. }
{242}{}{In light of
 significant advances in 2076 by the NBC on the Pan-Immunity Virion Project,
 the United States Defense Department, in fear of international espionage,}
{243}{}{ moved a team onto the site to secure and oversee the project, now dubbed the
 FEV (Forced Evolutionary Virus) project.}
{212}{}{Security:
                                                     Security Robots: Active}
{213}{}{Security:
                                                     Security Robots: Inactive}
{214}{}{Desativar Robôs de Segurança}
{215}{}{Ativar Robôs de Segurança}
{216}{}{Research:
                                                     Records most current at West Tech Research Facility}
{217}{}{Registros de Funcionários da Divisão de Pesquisa}
{218}{}{Power Armor. Status: Concluído}
{219}{}{FEV (Vírus Evolutivo Forçado). Status: Pendente }
{220}{}{Registros de Pessoal de Pesquisa}
{221}{}{Robert Anderson
                                                     Research Assistant
                                                 Security Clearance: Blue
                                    Stationed: Mariposa Military Base}
{222}{}{Nick Davis
                                                     Director of NBC Division of West Tech Research
               Security Clearance: Blue
                                            Stationed: West Tech Research Facility}
{223}{}{John Isaac
                                                     Research Assistant
                                             Security Clearance: Red
                                    Stationed: West Tech Research Facility}
{224}{}{Steve Remco
                                                     Research Assistant
                                             Security Clearance: Blue
                                    Stationed: Mariposa Military Base}
{225}{}{Charles Rignhold
                                                     Research Head of Laser Development
                           Security Clearance: Blue
                                       Stationed: West Tech Research Facility}
{226}{}{Michele Santose
                                                     Lab Technician
                                                     Security Clearance: Red
                                        Stationed: West Tech Research Facility}
{227}{}{Erin Shellman
                                                           Lab Technician
                                                     Security Clearance: Blue
                                        Stationed: Mariposa Military Base}
{228}{}{Leon VonFelden
                                                     Research Head of FEV
                                       Security Clearance: Blue
                                       Stationed: Mariposa Military Base}
{229}{}{Download Records to PIPBoy}
{230}{}{VOLTAR}
{231}{}{Power Armor Specs:
                                                     The T-51b Powered Infantry
 Armor is designed with the latest passive defense features for both civilian and
 military disturbances. }
{250}{}{The back-mounted TX-28 MircoFusion Pack generates 60,000 Watts to power
 the HiFlo hydraulic systems built into the frame of the suit. }
{251}{}{Made of the latest poly-laminate composite, the T-51b shell is lightweight
 and capable of absorbing over 2500 Joules of kinetic impact. }
{252}{}{The 10 micron silver ablative coating can reflect laser and radiation
 emissions without damage to the composite subsurface.}
{232}{}{FEV Summary Digest:
                                                     2073. As China became increasingly aggressive with their use of
 biological weapons, the United States government felt that a countermeasure was needed. The
 Pan-Immunity Virion Project (PVP) was officially formed September 15, 2073. }
{233}{}{2075. It became clear that the best way to combat the newly created
 biological weapons was to alter uninfected DNA só that it was no longer susceptible to standard
 viral infection.}
{234}{}{2076. Unforseen side effects began surfacing in early 2076 with the
 PVP. Animal test subjects began showing an abnormal growth rate accompanied by increased brain
 activity. }
{235}{}{The U.S. government took notice of these discoveries, and in the interests of national
 security, moved a team on-site to secure and oversee the project, which was now dubbed the FEV
 (Forced Evolutionary Virus) project.}
{236}{}{2077. FEV nears completion. Test on lab animals are at a near 100%
 success rate. Size and muscle density increase approximately 60%, and the protential intelligence
 increase by 200%. }
{237}{}{Effects upon human subjects remain unknown; although they are theoretically
 promising. }
{238}{}{The military, wishing to continue further testing, builds a large facility at the
 Mariposa military installation in central California. At this new facility, testing of the FEV
 virus continues on volunteer subjects from the military.}
{239}{}{Command Received:
                           Command Executed}
{240}{}{Acesso Negado}
