{100}{}{Você vê a Heather dos Patrulheiros dos Seguidores.}
{101}{}{O que você esta fazendo aqui?}
{102}{}{Izto!}
{103}{}{Ir adeus.}
{104}{}{Eu estou apenas olhando por ai.}
{105}{}{Eu estou aqui pra matar você!}
{106}{}{Apenas curioso sobre o que esta acontecendo aqui.}
{107}{}{Mesmo? É o que você poderia estar procurando?}
{108}{}{Eu acho que eu ja achei ela.}
{109}{}{Eu estou procurando por um espiao.}
{110}{}{Nada mesmo. Apenas olhando por ai.}
{111}{}{Apenas informação.}
{112}{}{Obrigada, mas eu ja estou namorando. Eu acho que é hora de você sair.}
{113}{}{Sim, o espiao. Eu ouvi sobre essa peste incomoda. Eu realmente desejo
 que nos pudessemos pegar ele.}
{114}{}{Eu ouvi algumas vezes que era uma espia.}
{115}{}{Você ouviu qualquer coisa sobre este espiao?}
{116}{}{Você é a espia!}
{117}{}{Boa sorte pra você. Lamento que eu aborreci você.}
{118}{}{Eu aposto que era o fanfarrao Neil que falou demais. Eu terei que ter
 uma conversa com ele mais tarde.}
{119}{}{Você acha que o Neil e o espiao?}
{120}{}{Então quem você acha que o espiao e?}
{121}{}{Você soa um pouco na defensiva. Por que? Algum motivo?}
{122}{}{Eu tenho quase certeza disso. Eu apenas preciso de alguma prova.}
{123}{}{Eu obterei a prova pra você.}
{124}{}{Ele parece uma pessoa bacana. Eu não sei.}
{125}{}{Por que você acha que é ele?}
{126}{}{Obrigado. Você não sabe o quanto isto significa pra mim. Uma vez que
 você obtiver a prova, mate ele.}
{127}{}{O que há pra não saber? Ele tem acesso as Crianças. Ele trabalha
 durante a noite quando a maioria esta adormecida. Tem que ser ele.}
{128}{}{Certo, Eu verificarei.}
{129}{}{Esqueça. Eu acho que você esta tentando me distrair!}
{130}{}{Eu verdadeiramente lamento que você pense dessa forma. Eu não posso ter
 alguém pensando que eu sou uma espia. Agora eu vou ter que matar você.}
{131}{}{Ele tem acesso as Crianças durante a noite. Ningem jamais vê ele no
 dever. Deve ser ele.}
{132}{}{Certo, Eu verificarei.}
{133}{}{Esqueça. Eu acho que você esta tentando me distrair!}
{134}{}{Eu não estou certo de quem ele é. Eu acho que pode ser ou um guarda ou uma
 estudiosa. Eles continuam entrando furtivamente na Catedral das Crianças a noite.}
{135}{}{Quaisquer outras pistas em que você possa pensar?}
{136}{}{Mas eu ouvi que só os patrulheiros fazem ataques as Crianças.}
{137}{}{Certo. Obrigado a você pela sua ajuda.}
{138}{}{Na verdade, não. Só que acho que é um homem e provavelmente um estudioso ou guarda.}
{139}{}{Certo. Obrigado a você pela sua ajuda.}
{140}{}{Verdade. Nós patrulheiros fazemos muitos ataques contra as Crianças, e com muitas
 perdas ultimamente. Este espiao nos custa caro.}
{141}{}{Você parece realmente angustiado a respeito disto. Eu procurarei pelo espiao e matarei ele.}
{142}{}{Poderia o espiao ser um patrulheiro?}
{143}{}{Obrigado a você pela sua ajuda.}
{144}{}{Por que um de nos faria isso?}
{145}{}{Se você matar os patrulheiros então você para os ataques.}
{146}{}{Eu não sei. Por que você faria isso?}
{147}{}{Não sei. Apenas imaginando.}
{148}{}{Soa como um bom pensamento. Eu notei que o Peter nunca e atacado nos
 ataques. Eu acho que ele pode ser o espiao.}
{149}{}{Certo, Eu verificarei.}
{150}{}{Esqueça. Eu acho que você esta tentando me distrair!}
{151}{}{Você acha que sou eu?}
{152}{}{Eu lamento. Eu estou um pouco estressado.}
{153}{}{Sim! Agora você morrera!}
{154}{}{Então vá imaginar em algum outro lugar. Eu devo voltar ao trabalho.}
{155}{}{Eu acho que ele pensa que eu sou a espia. Mas eu não sou.}
{156}{}{Talvez ele esteja certo.}
{157}{}{Por que ele pensaria isso?}
{158}{}{Por que eu sou a nova patrulheira. Eu só estive aqui por um ano
 e o problema comecou por volta de 5 meses atras.}
{159}{}{Eu acho que o Neil pode estar certo.}
{160}{}{Eu acho que o Neil poderia ser o espiao. Eu irei verificar.}
{161}{}{Então procure em algum outro lugar. Este não é o lugar pra você.}
{162}{}{Se você precisa de informação fale com a Nicole. Ela pensa que ela sabe de tudo.}
{163}{}{Eu posso ser persuadido a dizer a você algo que esta acontecendo. Por um preço.}
{164}{}{Quanto?}
{165}{}{Você venderia segredos?}
{166}{}{Esqueça. Eu não tenho dinheiro.}
{167}{}{Trezentas tampinhas é a informação e sua.}
{168}{}{Com certeza.}
{169}{}{De modo algum.}
{170}{}{Havera um ataque no extremo sul da fortaleza das Crianças. Agora vá.}
{171}{}{Tentando me trapacear? Eu vou dar uma licao pra você!}
{172}{}{Eu lamento que você se sinta desse modo. Mas bom dia pra você.}
{173}{}{Eu preciso sobreviver de algum jeito. Agora, você a quer ou não?}
{174}{}{Com certeza.}
{175}{}{De modo algum.}
{176}{}{Nada. Agora saia.}
{177}{}{Me deixa. Eu estou tentando obter um pouco de descanso.}
{200}{}{Não tenho nenhuma informação nova agora.}
