{100}{}{O que você quer?}
{101}{}{Me deixe em paz.}
{102}{}{O quê?}
{103}{}{Não mexa com minhas coisas.}
{104}{}{Oi.}
{105}{}{Ei, você ouviu que Set foi desativado?}
{106}{}{Conjunto está morto. Set está morto. Set está morto. . .}
{107}{}{Uungh.}
{108}{}{Ãhh.}
{109}{}{Ei, você ouviu que Set foi morto?}
{110}{}{Set esta morto. Set esta morto. Set esta morto . . .}
{111}{}{Há água suficiente pra todo mundo. O Set garante isso.}
{112}{}{Eu ouvi que os mutantes got run out da cidade.}
{113}{}{Desde que os mutantes sairam tem sido melhor.}
{114}{}{Olá.}
{200}{}{Você examina a coisa lastimável, mas não consegue descobrir o que pode tê-la deixado do jeito que está.}
{201}{}{Parece ter sido humano um dia, ou ao menos descendente de humanos. Você imagina que a deterioração do corpo se deve provavelmente a ácido ou radiação.}
{202}{}{O corpo do humanoide parece altamente irradiado, mas ainda funcional. Embora um dia tenha sido humano, parece ter revertido a um estilo de vida mais animalesco.}
{203}{}{O corpo do humanoide parece estar altamente irradiado, e muito da
 materia dos musculos e cerebro parecem ter deteriorado. Contudo,
 indicadores levam você a acreditar que descendeu, como você,
 daqueles que entraram nas vaults.}
