{100}{}{Você vê um dos guardas de Hightower.}
{101}{}{É melhor você sair. Daren Hightower não leva visitantes.}
{102}{}{Sua empresa não é desejada.}
{103}{}{Deixar!}
{104}{}{Não é permitido aqui.}
{105}{}{Vá embora ou você vai se arrepender.}
{106}{}{Esta casa está fora dos limites para quem gosta de você.}
{107}{}{What the… Get em!}
{108}{}{Você cometeu um grande erro ao chegar aqui!}
{109}{}{O que você está fazendo aqui? Você é carne morta.}
{110}{}{Mmmm, parece bom.}
{111}{}{É esse brahmin que eu cheiro?}
{112}{}{Prenda nas minhas veias!}
{113}{}{Alguma coisa na geladeira?}
{114}{}{Quanto tempo mais?}
{115}{}{Eu estou com fome.}
{116}{}{Está quase pronto?}
{117}{}{Eu vou desmaiar!}
