{100}{}{Você vê um oficial da policia.}
{101}{}{Saudações! Você deveria tomar cuidado com… uh, eu quero dizer, tomar cuidado… (o oficial da um olhar
 para os outros oficiais e tilts a cabeca dele na sua direção.)}
{102}{}{Oi estranho… Espere! Eu conheco você! Você e procurado por roubo! Não se mexa!}
{103}{}{Okay, eu desisto.}
{104}{}{Você vai morrer!}
{105}{}{Kor Rok!}
{106}{}{(Você se entrega.)}
{107}{}{Cuidado com suas costas, este não é um lugar seguro.}
{108}{}{Cuidado com seus scripts, }
{109}{}{cara.}
{110}{}{mulher.}
{111}{}{Você não deveria estar aqui, não é seguro.}
{112}{}{A Old Town e realmente decaida.}
{113}{}{Este lugar fede.}
{114}{}{Nós deviamos tear esta area inteira abaixo.}
{115}{}{Eu sei que aquele maldito Circulo dos Ladroes esta por aqui, em algum lugar.}
{116}{}{Pobre Harold, ele teve uma vida difícil.}
{117}{}{Não faca nada ilegal.}
{118}{}{Ei. Eu conheco você. Sem mais brigas okay?}
{119}{}{Melhor você não estar pensando em começar outra briga!}
{120}{}{Se você pegarmos você brigando de novo, você vai pra cadeia!}
{121}{}{Você ouviu? Os Far Go Traders foram eliminados.}
{122}{}{Os Mercadores da Agua são estoria, isso é uma bencao.}
{123}{}{Alguém matou a Crimson Caravan.}
{124}{}{Você ouviu? O Submundo foi finalmente eliminado!}
{125}{}{O Decker esta morto!}
{126}{}{Esta cidade estaria mais segura com o Decker fora do quadro.}
