{100}{}{Você vê o Jacob, o negociante de armas.}
{101}{}{Oi! Bem-vindo ao Jake's. Eu tenho algumas mercadorias muito boas no estoque. Sinta-se livre pra olhar por ai.}
{102}{}{Eu gostaria de fazer um acordo com você.}
{103}{}{O que você esta vendendo aqui?}
{104}{}{O que você pode me dizer sobre um chip purificador de água?}
{105}{}{Me fale sobre si próprio.}
{106}{}{Deixa pra lá. Tchau.}
{107}{}{qherer.}
{108}{}{naO qherer.}
{109}{}{Eu negocio com armas de alto calibre. A melhor coisa que você consegue achar neste lado da
 Irmandade, e ja que a Irmandade não lida com forasteiros, eu tenho que dizer que eu sou o melhor.
 Eu tenho um Rifle de Sniper, e você ficaria sob pressao pra achar o combustivel de Lanca Chamas em
 qualquer outro lugar nas terras devastadas. Ah sim... eu tenho um contador geiger tambem. Muito raro.}
{110}{}{Me mostre o que você tem.}
{111}{}{Me diga mais sobre o Rifle de Sniper.}
{112}{}{Para o que eu precisaria de um contador geiger?}
{113}{}{Talvez eu verificarei com você mais tarde. Tchau.}
{114}{}{Cara, você gosta das coisas raras! Aonde você estava quando eu estava vendendo algumas capsulas de uranio
 vazias há alguns anos atras? Apesar disso, eu não vendo chips. Não há um mercado para eles. Algo mais?}
{115}{}{Me mostre o que você tem.}
{116}{}{Então o que você TEM.}
{117}{}{Me fale sobre si próprio.}
{118}{}{Bem, eu estive por ai. Costumava trabalhar com o Sindicato dos Trabalhdores Atomicos. Tipo a Irmandade,
 mas menos amistosos. Eles queriam se manter pra si mesmos e eu... bem, eu queria ver o mundo e ser meu proprio
 chefe, então eu sai.}
{119}{}{Vamos ver o que você tem.}
{120}{}{Me diga o que você tem.}
{121}{}{O que você pode me dizer sobre um chip purificador de água?}
{122}{}{Bom encontrar você, amigo. Eu posso parar mais tarde. Tchau.}
{123}{}{Ah, o DKS é uma boa arma de longo alcance. Era originalmente .308, mas nos a modificamos para a capsula
 mais comum de .223. Nós modificamos o barril tambme. O mais importante, verifique este gatilho. Leve, huh? O
 gatilho se move perfeitamente agora. No geral, esta é uma boa escolha pra cacar qualquer tipo de animal...}
{124}{}{Soa bem. Vamos ver se nos podemos fazer um acordo.}
{125}{}{Para o que eu precisaria de um contador geiger?}
{126}{}{Talvez eu verificarei com você mais tarde. Tchau.}
{127}{}{Pra que você precisa de um contador geiger!? [Risadas] Ja faz 80 anos ou mais desde que as bombas cairam,
 ainda há radiacao por ai seu pateta. Você não consegue vê-lá, nunca poderia, mas esta lá. Inferno, eu desejo apostar
  que você tem algumas contagens em você agora. Todos que vivem nas terras devastadas tem algumas contagens de RAD.}
{128}{}{Me mostre o que você tem para vender.}
{129}{}{Me diga mais sobre a radiacao.}
{130}{}{Como um contador geiger funciona?}
{131}{}{Pateta!?! Você sempre insulta seus frequeses? Se você ahca que eu vou comprar algo de você agora
 você esta tristemente enganado.}
{132}{}{Bem, alguns a chamam de a Morte Fantasma, por que é isso que ela é. Você não consegue vê-lá, você não consegue ouvi-lá,
 você não consegue nem ao menos cheira-lá. Ela basicamente cresce no seu sistema. Você nunca a sente até que seja tarde demais.
 Mais viagens que você faz até os Hot Spots, o mais ela aumenta e nunca deixara seu sistema. Jamais. Os Rads apenas continuam
 aumentando. Bem... a menos que você possa obter um pouco de alguns Rad-Aways.}
{133}{}{Vamos ver se nos podemos fazer um acordo.}
{134}{}{Como um contador geiger funciona?}
{135}{}{Aonde eu posso achar Rad-Away? Eu não o vi sendo vendido em muitos lugares.}
{136}{}{Uau. Você sabe muito. Soa como se você estivesse por ai.}
{137}{}{Obrigado pela informação. Tchau.}
{138}{}{É bem simples na verdade. Você usa e ele diz pra você quantos Rads você tem. Tanto quanto você mantenha
 seu contador de Rads abaixo de 100 você vai ficar bem. Vá acima de 100 e você vai ter alguns problemas. A pior
 parte e que você nem ao menos sabe que você esteve sugando Rads até alguns dias depois. Vá acima de 1000 e
 você esta cozinhado - a menos que você obtenha a hold de um lote inteiro de Rad-Aways.}
{139}{}{Vamos ver se nos podemos fazer um acordo.}
{140}{}{O que você pode me dizer sobre a radiacao?}
{141}{}{Eu não vou por esta bosta difícil de vender. Vejo você mais tarde.}
{142}{}{Deixa pra lá.}
{143}{}{}
{144}{}{pEgar.}
{145}{}{Mim ir.}
{146}{}{Sim.}
{147}{}{Não. Apenas olhando.}
{148}{}{Eu não quero qualquer problema. Se você quer fazer negócios então vamos faze-los. Se não, saia.}
{149}{}{pEgar.}
{150}{}{Mim ir.}
{151}{}{Vamos ver o que você tem.}
{152}{}{Você pode ir pro inferno. Eu vou aonde eu quero, quando eu quero!}
{153}{}{Eu estou saindo.}
{154}{}{O que diabos você esta fazendo aqui?!?!?}
{155}{}{Eu não a carrego. Qualquer que eu ache eu mantenho pra mim mesmo. La pra cima aqui na rua, há um cara que
 pode ser capaz de ajudar você. O nome dele e Vance. Não faca muitas perguntas sobre ele. Vamos apenas dizer que
 esta é a area de expertise dele. Apenas diga a ele que o Jacob enviou você e ele deve ajudar bem a você.}
{156}{}{Como um contador geiger funciona?}
{157}{}{Obrigado pela informação. Tchau.}
{158}{}{Aqui esta o que eu tenho.}
{159}{}{Tchau.}
{160}{}{Obrigado.}
{161}{}{Ook.}
{162}{}{Os mutantes eliminaram eles por volta de 10 anos atras, então eu creio que eu tomei a decisao certa.
 Eu eventualmente me estabeleci aqui. Os policiais não gostam do meu comercio e eu fui rousted mais do que
 uma vez, mas eu sou muito mais honesto do que a maioria dos mercadores aqui.}
{163}{}{Ei, como esta indo meu amigo? Querendo comprar alguma coisa?}
{164}{}{Ei, como esta indo minha amiga? Querendo comprar alguma coisa?}
{165}{}{Sua selecao e boa, mas eu estou procurando por algo com um pouco mais de poder. Alguma ideia de aonde eu poderia ir?}
{166}{}{Bem, você poderia tentar os Gun Runners na Boneyard. Eles provavelmente terao algo que preencha as suas necessidades.
 Eu ouvi que os caras na Irmandade do Aco tem alguns hardwares bem poderosos tambem, então você poderia verificar com eles.}
{1999}{}{Você consegue modificar ou melhorar armas?}
{2000}{}{Claro. O que você quer que eu dê uma olhada?}
{2001}{}{Claro, mas você não parece ter nada em que eu possa ajudar. Traga pistolas e rifles, e talvez eu consiga te ajudar.}
{2002}{}{Traga pistolas e rifles, e talvez eu consiga te ajudar.}
{2010}{}{Você consegue fazer algo com alguma dessas pistolas que eu tenho?}
{2020}{}{Um dos meus rifles bem que precisava de uns acessórios.}
{2025}{}{Você consegue turbinar meu lança-chamas?}
{2030}{}{Você consegue fazer algo com este aguilhão de gado aqui?}
{2040}{}{Vamos ver se fazemos um negócio, então.}
{2050}{}{Deixa pra lá. Até mais.}
{2100}{}{Deixa eu ver o que você tem.}
{2110}{}{Na verdade, você poderia melhorar uma das minhas outras armas?}
{2120}{}{Eu queria outra coisa...}
{2130}{}{Na verdade, nenhuma delas. Tenho que ir.}
{2140}{}{Caro demais pro meu bolso. Volto quando tiver mais grana.}
{2200}{}{Posso instalar um carregador rápido nesse magnum por }
{2201}{}{Hmm, essa Desert Eagle ficaria uma belezura com um pente ampliado. Faço isso por }
{2202}{}{ tampinhas.}
{2203}{}{Ah, uau! Vejo que você tem uma Mauser M/96 aí! Não é fácil achar munição pra essa coisa hoje em dia. Se você quiser, posso convertê-la pra 10mm por }
{2210}{}{Instale o carregador rápido no magnum.}
{2220}{}{Amplie o pente desta Desert Eagle aqui.}
{2230}{}{Converta a Mauser pra 10mm.}
{2300}{}{Posso pôr uma boa mira pra qualquer clima nesse rifle de caça por }
{2301}{}{Nada como ter um rifle de assalto com pente ampliado. Posso equipar o seu com um por }
{2302}{}{Esse rifle de assalto avançado é uma boa arma. Ei, tenho uma mira de baixa luminosidade pra ele. É seu por }
{2303}{}{Sua espingarda de combate... posso colocar um pente de tambor nela por }
{2310}{}{Certo, então... ponha uma mira no rifle de caça Colt.}
{2320}{}{Amplie o pente do rifle de assalto AK-112.}
{2330}{}{Instale essa mira de baixa luminosidade na AK-198.}
{2340}{}{Instale um adaptador de pente circular na Winchester City-Killer.}
{2400}{}{Você quer esse aguilhão turbinado? A gente pode SUPERCARREGAR ele por }
{2410}{}{Claro.}
{2500}{}{Deixa eu dar uma olhada... É, dá pra fazer algo com isso por }
{2510}{}{Legal. Vamos nessa.}
{2600}{}{Espera aqui, vai levar só um instante.}
{2601}{}{Pronto. Mais alguma coisa?}
