{100}{}{Você vê um cacador de recompensa burly com um botao que diz,
 'Eu sou o Christopher e você e carne.'}
{101}{}{O que você quer?}
{102}{}{Uma rosquinha.}
{103}{}{O que você esta fazendo aqui?}
{104}{}{Apenas olhando por ai.}
{105}{}{Nada.}
{106}{}{Nós não apreciamos mafiosos aqui. Desapareca.}
{107}{}{Essa piada não foi engracada nem mesmo na primeira vez. Você esta
 pra descobrir por que eu sou um dos cacadores de recompensa mais
 temidos na terra devastada. É eu nem mesmo serei pago por isso.}
{108}{}{Não e da sua conta.}
{109}{}{Bem, vá olhar mais em algum outro lugar.}
{110}{}{Você sabia que há uma recompensa de 1.500 tampinhas na sua cabeca
 por matar crianças? Hora de coletar!}
{200}{}{ tampinhas pela sua cabeça por matar crianças? Hora de cobrar!}
{111}{}{[Christopher te olha, considerando algo... aparentemente ele já tomou uma decisão] Me diga, com que frequência você visita o Hub ou Junktown?}
{112}{}{Frequência suficiente, por que você pergunta?}
{113}{}{Bom, sabe... Os negócios tomam quase todo o meu tempo e não tenho oportunidade de ir lá. E, como fumante incurável, sinto muita falta de um velho isqueiro Zippo. Dizem que muitos desses itens pré-Guerra podiam ser achados nas lojas de lá. Se você me arranjar um Zippo, compartilho com você informações sobre os assentamentos vizinhos. Acho que pode ser útil!}
{114}{}{Que pena. Parece que eu te julguei mal. Cai fora daqui.}
{115}{}{Por que não, vou arranjar um pra você.}
{116}{}{Certo.}
{117}{}{Ei, tenho um aqui mesmo. Não preciso muito dele e posso te dar em troca da informação.}
{118}{}{Obrigado! [pega o isqueiro] Então, o que exatamente você quer ouvir?}
{119}{}{Aqui está seu isqueiro. Hora de me dar alguma informação.}
{120}{}{Sem mais perguntas, obrigado.}
{121}{}{[Mais]}
{122}{}{O que mais você quer saber?}
{123}{}{Preciso de alguma informação.}
{124}{}{Buuhhh.. Wuh?}
{125}{}{Você está falando sério? Suma da minha frente.}
{126}{}{Vou fazer um favor ao mundo colocando uma bala no seu crânio.}
{970}{}{Esse é meu nome.}
{971}{}{Você está falando comigo.}
{972}{}{Sou eu.}
{980}{}{Não sei nada sobre isso.}
{981}{}{Desculpe. Nem ideia.}
{982}{}{Nunca ouvi falar.}
{1000}{}{Adytum}
{1001}{}{Seguidores}
{1002}{}{Catedral}
{1003}{}{Rippers}
{1004}{}{Blades}
{1005}{}{Arma}
{1006}{}{Hub}
{1007}{}{Junktown}
{1008}{}{Agua}
{1009}{}{Nicole}
{1100}{}{Uma pequena cidade ao sul. Ocasionalmente alguns deles nos visitam.}
{1101}{}{Esses são as aberrações amantes da paz que vivem perto de nos.}
{1102}{}{Um culto estranho ao sul de Adytum e do resto da Boneyard. Nicole
 diz que eles estão pra fazer alguma coisa.}
{1103}{}{Uma gangue ultra-violenta a nosso oeste.}
{1104}{}{Uma gangue ao leste. Eles usam vibro-facas.}
{1105}{}{Uma gangue que veio do Hub, e vende armas. Eles estão ao norte daqui.}
{1106}{}{O Hub é uma cidade grande de comerciantes e negócios, a leste.}
{1107}{}{Junktown é uma cidade pequena bem ao norte do Hub.}
{1108}{}{Eu não posso ajudar você com isso.}
{1109}{}{Ela é a lider dos Seguidores.}
{1010}{}{Boneyard}
{1011}{}{Runners}
{1012}{}{Chip}
{1110}{}{Esta lugar e o Boneyard dos Anjos, os restos da antiga cidade de
 Los Angeles.}
{1111}{}{Uma gangue que veio do Hub, e vende armas. Eles estão ao norte daqui.}
{1112}{}{Eu não posso ajudar você com isso.}
