{100}{}{Você vê um paladino.}
{101}{}{Desculpe, estamos em alerta. Eu não posso falar agora.}
{102}{}{Você vê alguma coisa.}
{103}{}{Esses mutantes pagarão pelo que fizeram.}
{104}{}{Não se preocupe, temos tudo sob controle.}
{105}{}{Eu não ficaria por aqui se eu fosse você, provavelmente
 ser mais derramamento de sangue.}
{106}{}{Fique de olho em nós, Iniciados.}
{107}{}{Eu não ficaria por aqui se fosse você mais estranho, provavelmente
 ser mais derramamento de sangue.}
{108}{}{Fique de olho estranho, problemas estão se formando.}
{109}{}{Deixar.}
{110}{}{Não me distraia, estamos em alerta.}
{111}{}{Mantenha bastante.}
{112}{}{Pare de desperdiçar meu tempo, inicie.}
{113}{}{Abotoe seu estranho na escotilha.}
{114}{}{Bata-se estranho, antes que haja mais derramamento de sangue.}
{115}{}{Este mundo deve ser limpo dessas abominações vil.}
{116}{}{O que foi isso?}
{117}{}{Meus pés doem.}
{118}{}{Eles pagarão por isso ...}
{119}{}{Deixe-os tentar de novo.}
{120}{}{O que o ... Ah, não é nada.}
{121}{}{Fique alerta!}
{200}{}{Bob, qual é o seu status?}
{201}{}{Tudo claro.}
{202}{}{Eu não acho que eles estejam voltando.}
{203}{}{Não conte com isso}
{204}{}{Já ouvimos falar dos exploradores?}
{205}{}{Ainda não.}
{206}{}{Os Scouts relatam que tudo está claro.}
{207}{}{Bom}
{208}{}{Então, o que você estava trabalhando nesta manhã, Ray?}
{209}{}{Apenas tentando aumentar o alcance do rifle de plasma.}
{210}{}{Você já viu o Gatling laser?}
{211}{}{Sim, eu ajudei com o primeiro protótipo.}
{212}{}{Saia com a tagarelice!}
{213}{}{Sim, senhor. Desculpe senhor.}
