{100}{}{Você vê Jake dos seguidores.}
{101}{}{Você vê um seguidor do Apocalipse.}
{102}{}{Bem-vindo, meu amigo! Como posso ajudá-lo hoje?}
{103}{}{Eu ajuda! Eu ajuda!}
{104}{}{Eu ouvi dizer que você é um lutador decente. Vamos descobrir.}
{105}{}{Eu ouço que você precisa de ajuda. Qual é o problema?}
{106}{}{O que você pode me dizer sobre os seguidores?}
{107}{}{Você quer ajudar. Eu não acho que você é bom o suficiente para
 me ajude. Vá falar com Neil.}
{108}{}{Eu adoraria lutar com você, mas estou muito ocupado ajudando
 Nicole agora.}
{109}{}{Figuras. Você parecia um covarde para mim mesmo.}
{110}{}{Adequa-te a ti mesmo. Tchau.}
{111}{}{Como um covarde como você se tornou o segundo no comando?}
{112}{}{Ei. Só porque eu não quero lutar não significa que eu sou um
 covarde. Eu simplesmente não sinto isso.}
{113}{}{Eu estava certo. Apenas um covarde.}
{114}{}{Alguns de nós usaremos nossos cérebros para chegarmos mais longe neste mundo.
 Muito pode ser resolvido com paz e pensamento.}
{115}{}{Quando você vai usar seus cérebros então?}
{116}{}{Você está certo. Eu sinto Muito.}
{117}{}{Isso é isto. Eu não vou mais falar com você.}
{118}{}{Isso é melhor. Agora. Eu tenho um problema com um espião por aqui.
 Você vai me ajudar?}
{119}{}{Sim. O que é isso?}
{120}{}{Conserte-se se você é tão bom.}
{121}{}{Acabei de dizer que temos um espião por aqui. Acho que pode ser um
 dos guardas que é o espião. Embora possa ser um escuteiro.
 Esses são os dois únicos grupos que têm acesso ao
 Crianças.}
{122}{}{Certo. Vou pegar seu espião e eliminar o problema.}
{123}{}{Tem alguma pista sobre esse espião?}
{124}{}{Esqueça. Eu não vou te ajudar.}
{125}{}{Muito obrigado. Agora vá!}
{126}{}{Nada realmente. As únicas coisas que eu realmente sei é
 que muitas informações de baixo nível estão chegando ao
 Crianças. Isto não é bom. Heather acha que é ou
 Neil ou Peter.}
{127}{}{Certo. Eu vou verificar isso.}
{128}{}{Esqueça. Eu não vou te ajudar.}
{129}{}{Eu não posso deixar você ir embora.}
{130}{}{eu vou então. Tchau!}
{131}{}{Estamos tendo problemas com algumas de nossas informações
 escapando para as crianças. Eu acho que é um espião.}
{132}{}{Certo. Então qual é o problema?}
{133}{}{Certo, eu vou lidar com esse espião.}
{134}{}{Ainda tem alguma pista?}
{135}{}{Esqueça. Eu não vou te ajudar.}
{136}{}{Atualmente, não posso te dizer nada. Dia bom.}
{137}{}{Estou tentando dormir. Não me incomode.}
{138}{}{Apresse-se e descubra essa vil escória!}
{139}{}{Eu sabia que era Heather o tempo todo. Ela era enganosa de
 o começo. Eu deveria ter dito a todos o que eu pensava no começo.}
{140}{}{Eu nunca aprendi nada com você. Seu treinamento
 foi inútil.}
{141}{}{Eu tenho um pacote para você do Gabriel.}
{142}{}{Hmm. Entendo. Obrigado.}
{143}{}{Dê o fora.}
{144}{}{É o caminho mais difícil. É sempre o caminho mais difícil.}
