{100}{}{Você vê a Jennifer.}
{101}{}{Você vê uma Paladina.}
{102}{}{Com licença, Irmao. Você deveria guardar sua arma
 sempre que você estiver na Irmandade. Nós somos uma ordem
 amistosa mas como você sabe, os tempos são ruins.}
{103}{}{Alguns membros da Irmandade poderiam ficar ofendidos
 se um estranho... eu quero dizer, um novo Iniciado... se
 aproxima deles com uma arma.}
{104}{}{Bom dia, Iniciado. Como eu posso ajudar você?}
{105}{}{Oi, Irma, e bom ver que há mulheres de rank nesta
 organizaçao. Eu não sabia o que esperar com um nome como
 a Irmandade.}
{106}{}{Ei, pernas bonitas. Você e muito bonita.
 Que hora eu deveria encontrar você?}
{107}{}{Oooooga!}
{108}{}{Você poderia me dizer aonde eu poderia achar nosso Elder Supremo?}
{109}{}{Quem esta no comando deste buraco?}
{110}{}{Aonde esta este cara Supremo?}
{111}{}{Gruk!}
{112}{}{Maxson, o Elder Supremo, pode ser achado no quarto andar. Se
 você pegar o outro elevador pra baixo até o nivel quatro, ele deve
 estar ou na Sala do Conselho ou nas Salas dos Elders.}
{113}{}{Você pode perguntar a um dos guardas naquele nivel;
 eles devem saber aonde ele esta no momento.}
{114}{}{Obrigado.}
{115}{}{Aonde eu posso conseguir algumas armas melhores?}
{116}{}{Você deve falar com o Talus. Ele poderia ser capaz de ajudar
 você ou pelo menos dizer a você com quem falar.}
{117}{}{Durante o dia o Talus esta normalmente supervisionando a
 sala de treinamento. Você sabe aonde essa esta?}
{118}{}{Sim, eu sei. Obrigado.}
{119}{}{Não.}
{120}{}{Claro que eu sei!}
{121}{}{A sala do treinamento esta logo ali na esquina. Apenas vá
 por este corredor, vire a esquerda, vá atraves da porta no fim
 do corredor e ela estara do outro lado da porta a sua direita.}
{122}{}{Você tem extremamente prestativo. Muito obrigado. Eu
 espero que nos possamos conversar de novo em breve. Bom dia.}
{123}{}{Salao de treinamento? Você acha que eu poderia conseguir um pouco de
 treinamento lá? Eu sou um membro da Irmandade agora, certo?}
{124}{}{Obrigado por sua ajuda, Irma. É bom ver que há mulheres
 no rank desta organizaçao. Eu não sabia o que esperar com um
 nome como a Irmandade.}
{125}{}{Obrigado, docinho. Você sabe, você parece muito bem.
 O que você diz de você e eu verificarmos o 'equipamento'
 um do outro mais tarde? Que horas você sai?}
{126}{}{Ah, aquele lugar. Certo, tchau.}
{127}{}{Com licença? Há algo errado?}
{128}{}{Muk lug?}
{129}{}{Eu lamento, eu não acho que eu possa ajudar você. Você deveria
 ir ver a doutora. Ela esta no segundo nivel.}
{130}{}{Claro que há. Dois dos nossos cinco Elders são mulheres,
 nossa escriba mestra é uma mulher e nós temos muitas outras
 mulheres em todos os ranks diferentes.}
{131}{}{As mulheres da Irmandade tambem são chamadas de Irmaos. Nós não
 chamamos as mulheres de Irmas. Depois de tudo, esta é a Irmandade do
 do Aço, não a Irmandade dos Homens ou das Mulheres de Aço.}
{132}{}{Você não acha peculiar que seja chamada de a Irmandade
 implicando que os membros dela consistam unicamente de homens?}
{133}{}{Mas por que é chamada de Brotherhood então?}
{134}{}{Bem, apenas parecia estranho.}
{135}{}{Eu não sei. Esse foi nosso nome por toda a minha vida.
 Eu tenho certeza que há uma razão nisso.}
{136}{}{Eu creio que você esta certo.}
{137}{}{Bem, ainda parece um pouco estranho pra mim.}
{138}{}{Isso e estranho. Eu nunca realmente pensei muito nisso
 Nós fomos a Irmandade do Aço por toda a minha vida. Nossos
 ancestrais devem ter tido uma razão pra nomea-lá assim.}
{139}{}{Mas isso não significa que as coisas não podem mudar.}
{140}{}{Sim, você provavelmente esta certo.}
{141}{}{Então, há mais alguma coisa com a qual eu posso ajudar você?}
{142}{}{Sim aonde eu posso achar o Supremo?}
{143}{}{Aonde eu posso conseguir armas melhores?}
{144}{}{Não, isso e tudo. Tchau.}
{145}{}{Não, nos somos muito estritos no que diz respeito a tradiçao.
 Eu não acho que poderia ser mudado. Não me aborrece de modo algum
 ser adereçada como Irmao. Apesar disso isso e curioso.}
{146}{}{Eu acho que eu terei uma conversa com a Vree. Ela poderia
 ser capaz de dar algum insight sobre o por que que os nossos
 ancestrais decidiram nos chamar a Irmandade do Aço.}
{147}{}{Quem é Vree? Uma dos Elders?}
{148}{}{Vree é a Escriba Mestra. Ela e aquela com quem você
 deveria falar se você tem quaisquer perguntas tecnicas mas
 não pertube ela durante as meditaçoes dela a noite.}
{149}{}{Ela quase sempre fica na sala dela a qual esta tambem
 ocupada pelo mainframe no terceiro andar.}
{150}{}{Buraco? Como você ousa falar assim da Irmandade.
 Você é um membro da nossa ordem agora e deveria estar
 orgulhoso de ser um membro da Irmandade do Aço.}
{151}{}{Orgulhoso? Por que? Você todos são apenas um bando de hop-heads roboticos
 se escondendo do mundo real. Não há nada do que estar orgulhoso ai.}
{152}{}{Eu lamento. Eu perco um pouco o controle
 de mim mesmo as vezes.}
{153}{}{Sim, certo.}
{154}{}{Bem, Eu creio que todos nos as vezes.}
{155}{}{Então, quem esta no comando deste lugar?}
{156}{}{Sim. Bem, eu tenho que ir.}
{157}{}{Maxson, o Elder Supremo. Ele esta no quarto andar.}
{158}{}{}
{159}{}{}
{160}{}{}
{161}{}{}
{162}{}{}
{163}{}{Bem, você e fofo... mas eu acho que não. Eu não acho que
 seria uma boa ideia me envolver com um forasteiro de qualquer
 maneira. Apesar disso você e fofo e de algum modo atraente. }
{164}{}{Eu não sei se e porque você e um forasteiro ou por causa
 da sua extrema... falta de tato? Então, 'docinho', há alguma
 coisa mais que eu possa fazer por você?}
{165}{}{Sim, uh, eu acho. Uh, quem esta no comando por aqui?}
{166}{}{Uh, ok... um. Que tal algumas armas então?
 Aonde eu posso por minhas maos em algumas dessas?}
{167}{}{Hmmph!}
{168}{}{Não.}
{169}{}{Isso é... bem engraçado. Você esta brincando eu espero? Na verdade...
 não responda isso. Eu não acho que eu queira saber.}
{170}{}{Sim, engraçado MESMO. Quase tanto quanto a sua cara!}
{171}{}{Muito obrigado. Isso e exatamente o que eu precisava ouvir agora.}
{172}{}{Eu vou sair daqui.}
{173}{}{Eu lamento. É apenas que vocês forasterios tem um modo
 tão estranho de falar com as pessoas as vezes. Há qualquer
 coisa com que eu possa ajudar você?}
{174}{}{Bem, eu acho que eu deveria falar com esta pessoa Elder Supremo.
 Aonde ele esta?}
{175}{}{Eu gostaria de obter algumas armas melhores.
 Com quem eu falo a respeito disso?}
{176}{}{Não.}
{177}{}{Você esta falando serio? Eu jamais ouvi uma frase tão
 horrivel em toda a minha vida!}
{178}{}{Sim? Bem, eu não saio muito. Certo?}
{179}{}{Saia da minha frente sua lata de lixo andante!}
{180}{}{Pfft!}
{181}{}{Bem, sim, você e um membro da Irmandade, mas os Elders
 puseram um limite em todo o treinamento dos novos Iniciados.}
{182}{}{Por que?}
{183}{}{Ah, isso e simplesmente OTIMO! Por que diabos eu me uni a
 este grupo estúpido? Aonde esta a porta?!}
{184}{}{Há rumores sobre algum tipo de exercito. Eu acho que os Elders
 querem concentrar os recursos deles naqueles que ja estão distantes o
 bastante no treinamento deles pra fazer a diferença se nos tivermos
 uma grande batalha nas nossas maos.}
{185}{}{Nós acreditamos fortemente que treinar alguns poucos lutadores
 extremamente bem e melhor do que dar um treinamento mediocre pra um
 bando de lutadores. Salvar vidas e um de nossos objetivos primarios.}
{186}{}{Você poderia provavelmente entender um pouco do treinamento
 apenas observando. O irmao Thomas e o melhor treinador que nos ja
 tivemos na Irmandade.}
{187}{}{Bem, eu estou trabalhando lá fora da Irmandade, certo? É
 um mundo muito hostil lá fora e eu estarei pondo minha vida em risco a
 cada minuto que eu estou lá fora. Você não acha que deveria ser dado
 treinamento a mim se eu quisesse ou precisasse ou você só 'diz' que
 e seu objectivo primario 'salvar' vivas?}
{188}{}{Obrigado pela sugestao, eu darei uma olhada.}
{189}{}{Você são todos um bando de tolos.}
{190}{}{Você pode me dizer aonde o Maxson esta?}
{191}{}{Bem, eu só estou repetindo o que foi dito a mim. Se você falar com
 o Thomas ou o Talus eles poderiam ser capazes de fazer uma exceçao.}
{192}{}{Certo, obrigado.}
{193}{}{Melhor eles conseguirem. Eu pulei through enough hoops por vocês.}
{194}{}{Então, você pode me dizer aonde o Maxson esta?}
{195}{}{Ah, meu querido. Quando nos vamos nos casar?}
{196}{}{Você esta tão bonito, como sempre.}
{197}{}{Me da um beijo.}
{198}{}{Eu senti tanta falta de você.}
{199}{}{Eu esperarei por você.}
{200}{}{Eu estive pensando em você o dia todo.}
{201}{}{Você fica tão fofo quando você olha pra mim assim.}
{202}{}{Não me assuste assim. Eu pensei que eu nunca veria você de novo.}
{203}{}{Você não veio na noite passada.}
{204}{}{Quanto tempo faz desde que eu vi você pela ultima vez?
 Parece uma eternidade.}
{205}{}{Eu senti tanta falta de você.}
{206}{}{Vem pra cama, docinho.}
{207}{}{Nós podemos nos casar de manha.}
{208}{}{Eu acho que nos deveriamos ter pelo menos cinco filhos.}
{209}{}{Aonde você quer ir na nossa lua de mel? Eu ouvi
 que as Crianças da Catedral tem um lugar lindo.}
{210}{}{Meus pais ainda estão esperando pra conhecer você.}
{211}{}{Ola de novo. Eu espero que as coisas estejam bem com você.
 Eu espero que você tenha falado com a Vree.}
{212}{}{Oi, Irmao }
{213}{}{.}
{214}{}{Seja cuidadoso se você for pro norte. Nossos patrulheiros nunca retornaram.}
{215}{}{Irmao }
{216}{}{, e bom ver você de novo.}
{217}{}{Você falou com o Rhombus? Ele e o Cavaleiro Chefe. Ele esta
 logo ali naquela sala.}
{218}{}{Eu não tenho tempo pra falar. Eu estou ocupado.}
{219}{}{Lamento, eu não estou com humor pra falar com pessoas rudes.}
{220}{}{Não me aborreça.}
{221}{}{O que? Você não consegue aborrecer outra pessoa?}
{222}{}{Vai embora.}
{223}{}{Eu não quero falar com você.}
{224}{}{Iniciado. volte aos seus estudos.}
{225}{}{Sem tempo pra falar, Iniciado.}
{226}{}{Venha aqui seu gostosao!}
{227}{}{Querido, por aqui!}
{228}{}{ Eu senti sua falta.}
{229}{}{Eu ja tenho o berçario pronto, querido.}
{230}{}{Oi, docinho.}
{231}{}{Eu vejo você.}
{232}{}{Você tem que encontrar meus pais.}
{233}{}{Ô-ôu!}
{234}{}{Venha aqui, meu little snookums.}
{235}{}{Você esta me provocando?}
{236}{}{Você esta se fazendo de difícil não esta?}
{237}{}{Por aqui, docinho!}
{238}{}{Oi docinho!}
{239}{}{Ai esta você. Eu estava começando a me preocupar.}
{240}{}{Venha aqui e me de um beijo, lindo.}
{241}{}{Entre, querido.}
