{100}{}{Você vê a Julianna.}
{101}{}{Você vê uma simples cidada de Adytum.}
{102}{}{Ola.}
{103}{}{Erf.}
{104}{}{Ola.}
{105}{}{Eu tenho uma mensagem de Romero.}
{106}{}{Eu posso saber seu nome, senhorita?}
{107}{}{Eu sou Julianna.}
{108}{}{Você tem um trabalho aqui?}
{109}{}{Eu posso perguntar um pouco sobre sua cidade?}
{110}{}{Eu faco o que Caleb pede. Mas eu só sou realmente capaz de fazer um pouco
 de      . Eu não tenho as técnicas pra ajudar o Smitty ou Miles.}
{111}{}{Me diga um pouco sobre esses outros que você mencionou.}
{112}{}{Nós sobrevivemos, e os Reguladores procuram ter ceteza de que nada aconteca
 pra nos machucar. Na maior parte não nos deixando sair daqui.}
{113}{}{Bem, Miles faz quimica, e ele odeia balas e coisas. Smitty
 e um artesao que constroi coisas como potes e facas.}
{114}{}{Você tem uma mensagem de Romero? O que e?}
{115}{}{Ele diz que ele terminou com você.}
{116}{}{Ele diz que ele envia seu amor.}
{117}{}{Ele enviou este locket como um token.}
{118}{}{Não . . . não pode ser verdade . . . eu . . .}
{119}{}{Ele não fez nada mais?}
{120}{}{Não, lamento.}
{121}{}{Ah sim, ele enviou este locket.}
{122}{}{Que romantico! Ah, eu devo ver ele de algum jeito! Se apenas . . .
 talvez . . . talvez a Lorraine possa levar pra ele uma mensagem . . .}
{123}{}{Ah! Muito obrigado por sua ajuda! Nós decidimos viver
 aqui agora, com os Seguidores, em paz.
 Obrigado por ajudar o nosso amor.}
{124}{}{Eu não posso viver sem ele!}
{125}{}{Julianna tira uma faca e enfia em si mesma!}
{126}{}{Você ganha 250 pontos de experiência por ajudar os amantes unidos-pelas-
 estrelas com a entraga do     Romero pra Julianna.}
