{100}{}{Você escapou da cela. Você e agora definitivamente um fugitivo em
 Junktown!}
{101}{}{A porta parece solida, e tem uma tranca stout. Ainda, trancas podem ser abertas, e
 portas podem ser destruidas.}
{102}{}{A porta está trancada.}
{103}{}{Você destranca a porta.}
{104}{}{Você tranca a porta.}
{105}{}{Você falha em destrancar a porta.}
{106}{}{Você falha em trancar a porta.}
{107}{}{Você ganha 250 pontos de experiência por busting out da cadeia!}
{108}{}{ de experiência por escapar da cadeia!}
{200}{}{ destranca a porta.}
{201}{}{ tranca a porta.}
{202}{}{ não consegue destrancar a porta.}
{203}{}{ não consegue trancar a porta.}
