{100}{}{Você vê: Kalnor, um guarda de Junktown.}
{101}{}{É melhor você se comportar por aqui.}
{102}{}{Esta não é uma cidade boa pra arrumar encrenca.}
{103}{}{Comporte-se, e não vamos precisar ser grossos.}
{104}{}{Você é gente boa.}
{105}{}{Continue o bom trabalho.}
{106}{}{Dia bonito, não é?}
{107}{}{Isto é Junktown. Bom lugar pra se viver, contanto que você fique do nosso lado bom.}
{108}{}{Cuidado com o Gizmo e os capangas dele.}
{109}{}{Eu gosto do meu chefe.}
{110}{}{É melhor você guardar isso. Junktown é um lugar amigável, amigo, e queremos que continue assim.}
{111}{}{Guardar o quê?}
{112}{}{Não me diga o que fazer, seu perdedor.}
{113}{}{Parece justo. A propósito, qual é a lei local sobre armas?}
{114}{}{Uh, oh.}
{115}{}{Sua arma, idiota. O Killian não vai tomar suas armas, mas é bom você mantê-las no coldre.}
{116}{}{Ah, desculpe.}
{117}{}{De jeito nenhum! Não vou baixar minhas armas por ninguém!}
{118}{}{É melhor você se comportar, porque é a lei, e eu faço cumprir a lei. Guarde sua arma. Não saque a menos que em legítima defesa e você não terá problema com a gente, os guardas. Desobedeça a lei e a gente te devolve pro ermo sem lei - vivo ou morto.}
{119}{}{Certo, já que você põe dessa forma.}
{120}{}{Enfia suas leis!}
{121}{}{Bom, é, por mim tudo bem. Mas é melhor você tomar cuidado.}
{122}{}{Bom que perguntou. Nenhuma arma pode ser sacada, exceto em legítima defesa. Se você começar uma briga, a culpa é sua. Fora isso, é seu direito andar armado. Só não puxe faca ou arma sem justa causa. Tenha um bom dia.}
{123}{}{Ei você, sem armas! E não me interessa se sua mãe te deixou cair de cabeça quando criança. Sem armas.}
{124}{}{Ei! Você! O que está fazendo aí bisbilhotando?}
{125}{}{Nada.}
{126}{}{Não estou bisbilhotando. Só gosto de andar com cautela.}
{127}{}{Ãhhh.}
{128}{}{Seja lá o que estiver fazendo, não faça nesta cidade.}
{129}{}{Ei! Nada de figuras suspeitas na cidade! Cai fora daqui antes que a gente te expulse!}
{130}{}{Bom, é, tá bom. Tanto faz. Só não faça nada fora da linha.}
{131}{}{Obrigado, tchau.}
{132}{}{Com certeza. Vou jogar a cautela ao vento, senhor.}
{133}{}{Com certeza. Vou jogar a cautela ao vento, senhora.}
{134}{}{É melhor você olhar por onde pisa por aqui, porque a gente vai estar de olho em você.}
{135}{}{Bem-vindo a Junktown. O que posso fazer por você?}
{136}{}{Nada, obrigado.}
{137}{}{O que você está fazendo aqui? Que lugar é este?}
{138}{}{Onde eu consigo alguns suprimentos?}
{139}{}{Wa-wa!}
{140}{}{Isso eu não sei. Talvez seja melhor você falar com o Killian. Ele está ao norte. É pra lá, tá?}
{141}{}{O que parece? Sou um guarda, e estou de olho em estranhos como você. E este lugar se chama Junktown. Ei, não ria. Acontece que eu gosto do nome. A gente mais comercia. Às vezes negocia com aqueles convencidos do Hub. Ei, você não é do Hub, é?}
{142}{}{O quê? O Hub? Claro que sou!}
{143}{}{Eu? Não, não sou do Hub.}
{144}{}{Então você deve conhecer a maioria das regras. Tenha um bom dia. E desculpa a parte dos convencidos, tá?}
{145}{}{É! Ei, sem problema. Tchau.}
{146}{}{Vai me causar um sério trauma mental. Até mais.}
{147}{}{Hmmm. Tá bom. Não cabe a nós fazer perguntas. Tenha um bom dia e não arrume confusão.}
{148}{}{Ah, poxa. O lugar pra isso é a Darkwater's. O Killian é o dono. Fica um pouco ao norte. O Killian tem os melhores suprimentos da cidade.}
{149}{}{Obrigado. Tchau.}
{150}{}{Você quer me mostrar onde guarda os SEUS suprimentos?}
{152}{}{É, não. Desculpa, moça. Tenho trabalho a fazer aqui.}
{153}{}{Tenha um bom dia.}
{154}{}{Fique longe de encrenca.}
{155}{}{Rapaz, espero mesmo que meu substituto chegue logo. Parece que estou de guarda há uma eternidade.}
{156}{}{Sinto muito, os portões estão fechados pela noite. Volte de manhã.}
{157}{}{Ei, eu preciso entrar!}
{158}{}{Sem problema. Até de manhã.}
{159}{}{Desculpe incomodar, senhor, mas eu gostaria de entrar na sua cidade. Você pode ver que eu não causaria mal algum.}
{160}{}{Hunh-huh!}
{161}{}{Volte... de... dia...}
{162}{}{Desculpe, regra é regra. Estranhos não entram durante a noite.}
{163}{}{Bom, eu não deveria fazer isso, mas você parece uma pessoa bacana o bastante. Pode entrar, mas não arrume confusão.}
{164}{}{Ei! É você! Pode entrar, }
{165}{}{. Bom te ver de novo!}
{166}{}{Ei, é melhor você dar meia-volta e sair andando daqui.}
{167}{}{Pode entrar.}
