{110}{}{WOOOAAAAAH!}
{111}{}{O QUE É ISSO?!}
{112}{}{WAA!}
{113}{}{LOOK!}
{114}{}{BRRRRRRRR!}
{115}{}{QUE MAAAANEIRO!}
{116}{}{WOAH!}
{117}{}{ISSO É DE VERDADE?}
{118}{}{}
{119}{}{COOL!}
{120}{}{WOOW!}
{125}{}{AAAAAAAHHHH!}
{126}{}{AAAAH!}
{127}{}{MOMY!}
{128}{}{AAAAAH!}
{129}{}{Ajude-me!}
{130}{}{Você é assustador!}
{150}{}{Isto é seu, moço?}
{151}{}{Isto é seu, moça?}
{152}{}{Você é tão maneiro!}
{153}{}{Que maneiro!}
{154}{}{Meu tio diz que você é um exibido!}
{155}{}{Vou ser igual a você quando crescer!}
{156}{}{Queria que o Jason pudesse ver isto!}
{157}{}{Posso ir com você?}
{158}{}{Vamos! BRRRRRR!}
{159}{}{Isto é melhor que as carroças de Brahmin idiotas!}
{160}{}{Você é daqui?}
{161}{}{Nunca te vi antes.}
{162}{}{Você é novo aqui, né?}
{163}{}{Você vai ficar mais tempo?}
{164}{}{Você não parece tão assustador!}
{165}{}{!}
{166}{}{Eu não roubo nada! Prometo!}
{167}{}{}
