{100}{}{Você vê um homem com cicatrz, altamente musculoso e com um bigode.}
{101}{}{Você vê Lars, o sargento dos guardas de Junktown.}
{102}{}{Ele carrega as cicatrizes de feridas anteriores e parece uma mão velha.}
{103}{}{Ele tem cicatrizes de ferimentos de faca e balas. Seus músculos muscles mostram
 um homem endurecido pela adversidade.}
{104}{}{Você sabe, não é sábio tentar roubar dos guardas aqui em Junktown,
 vagabundo!}
{105}{}{Eu posso ajudar você, estranho?}
{106}{}{Então, o que há pra fazer por aqui?}
{107}{}{Você pode me dar um esclarecimento sobre Junktown?}
{108}{}{Quem é você?}
{109}{}{Eergh.}
{110}{}{Se você está no comando dos guardas aqui, eu acho que eu tenho um pouco de informação
 para você.}
{111}{}{Ei! Você! Nós sabemos sobre você, seu/sua monstro!}
{112}{}{Bastante, tanto quanto você fique no nosso lado. Nós temos o armazém do Killian
 Darkwaters', aonde você pode fazer algum comércio. É há o cassino do Casino, se você é um
 jogador. Ou se você apenas quer uma bebida, você pode ir para o Skum Pitt.
 Apenas não fique muito bebado.}
{113}{}{Ei, Eu gosto de uma bebedeira!}
{114}{}{Bem, melhor você manter-se sob controle. Nós somos uma cidade livre mas nós
 não toleramos pisar na bola com outras pessoas. Não cause quaisquer problemas e
 você não dará causa para eu e meus homens te 'acalme'.}
{115}{}{Que pau na lama!}
{116}{}{Olhe, camarada, meu trabalho aqui é manter a paz e se eu tenho que quebrar algumas
 cabeças para fazer isto acontecer, então algumas pessoas vão ser feridas sim. Então apenas assita.}
{117}{}{Eu e meus homens aqui trabalhamos para Killian Darkwater. Nós mantemos alguma ordem nesta
 cidade, lidando com todos os assassinos, ladrões e outras scumbags que venham
 do deserto. Se você quer meu conselho, você também ficará longe do Gizmo. Aquele
 cabeça gorda dirige uma operação crooked, mas não não fomos capazes de provar nada.
 Ele e seus lacaios, os Skulz, vão cair em algum tempo em breve, se
 Killian tem qualquer coisa a dizer a respeito.}
{118}{}{Que chatisse. Nenhuma diversão aqui.}
{119}{}{Bom saber que alguém está mantendo a paz por aqui. Obrigado.}
{120}{}{Então, o que impede vocês garotos da lei de simplesmente prenderem Gizmo e os Skulz?}
{121}{}{Que isto, é apenas nosso trabalho. Mas é bom saber que alguém o aprecia.
 Obrigado.}
{122}{}{Tenho que fazê-lo com todo gosto. Nós sabemos que Gizmo dirige uma operação duvidosa
 e tal, mas nós precisamos de evidência robusta para derrubá-lo. É mesmo com os Skulz; eles
 são muito bom nisto, nós trazemos um ou dois deles para cá, mas nada muda. Nós simplesmente
 não temos qualquer evidência direta ligando eles a qualquer dos assassinatos ou assaltos.}
{123}{}{Talvez eu possa ajudar você com isso.}
{124}{}{Bem, boa sorte.}
{125}{}{Inferno, se você acha que você consegue obter alguma sujeira de ambos, nós apreciaríamos
 a ajuda. Killian é aquele para falar se você quer falar sobre o Gizmo. Mas se você
 pouder obter um pouco de info sobre os Skulz, apenas volte pra mim e eu e os garotos
 tomaremos conta deles.}
{126}{}{Obrigado. Cuidado por aí.}
{127}{}{Eu sou o cabeça dos guardas aqui em Junktown. O nome é Lars. Falando nisto,
 quem é você, estranho?}
{128}{}{Eu sou }
{129}{}{.}
{130}{}{Cai fora, Eu não tenho que dizer nada a você.}
{131}{}{Bem-vindo a Junktown, }
{132}{}{. Em que eu posso ajudar você?}
{133}{}{Você pode me dar mais detalhes sobre Junktown?}
{134}{}{Apenas procurando por algo pra fazer. Tem quaisquer sugestões?}
{135}{}{Bom dia, viajante. Você precisa de alguma coisa?}
{136}{}{O que?}
{137}{}{Eu estou procurando por um pouco de trabalho.}
{138}{}{Apenas parando para dizer olá.}
{139}{}{Eu tenho testemunho sobre as atividades ilegais que os Skulz
 estavam envolvidos.}
{140}{}{Sim, eu estou no comando dos guardas aqui. O que você tem para mim?}
{141}{}{Nada, apenas verificando.}
{142}{}{Eu tenho um pouco de testemunho de Sherry de que os Skulz estão envolvidos em algumas
 atividades ilegais.}
{143}{}{Então, você tem alguma info sobre os Skulz, eh? O que você pode me dizer?}
{144}{}{Eles estão envolvidos em alguns muggings e mortes aqui.}
{145}{}{Eu convenci uma deles, Sherry, a testemunhar que eles estavam envolvidos
 em atividade criminal.}
{146}{}{Isso é ótimo e tal, mas eu não posso apenas prendê-los todos pelo dizer de uma
 pessoa. Eu preciso de evidência dura ou de testemunho de dentro.}
{147}{}{Eu verei o que eu posso fazer.}
{148}{}{Eu tive testemunho de Sherry, um membro formal da gangue.}
{149}{}{Excelente. Eu pegarei ela para algumas perguntas e eu tenho certeza que eu
 obterei toda a informação que eu preciso para tirar ele daqui.}
{150}{}{Olha, isto não é um jogo. As pessoas estão se ferindo aqui. Se você achar alguma
 evidência verdadeira, volte, mas do contrário, não desperdice meu tempo!}
{151}{}{Se você não é averso a um pouco de skullduggery, Eu preciso de alguém par obter
 alguma evidência dura sobre os Skulz, provando que eles estão envolvidos em atividades
 ilegais aqui. Ou você pode falar com o Killian; ele poderia ter algum trabalho para você.}
{152}{}{Obrigado pela sua assistência. Junktown está um pouco mais segura agora, por causa de
 sua ajuda.}
{153}{}{Mova-se, camarada.}
{154}{}{Você ganha 300 pontos de experiência por tomar um turno arriscado contra os Skulz.}
{155}{}{Você está pronto para ajudar a derrubar o Gizmo?}
{156}{}{Você pode apostar. Vamos nail aquele tub.}
{157}{}{Não, eu mudei minha de idéia.}
{158}{}{Tudo certo, vamos fazê-lo.}
{159}{}{Bem, melhor você esperar aqui para que você não fique preso no fogo cruzado.}
{160}{}{Killian me enviou para ajudar a run o Gizmo fora da cidade.}
{161}{}{Killian me enviou. Nós vamos derrubar o Gizmo.}
{162}{}{Obrigado por toda a sua ajuda. Aqui estão 500 tampinhas. Você sempre será bem-vindo em
 Junktown, amigo.}
{163}{}{O que? Hmm. Nós veremos a respeito disso. Eu enviarei alguns homens para emboscá-los
 quando eles tentarem. Você vai estar lá?}
{164}{}{Não obrigado, eu já fiz meu bom ato do dia.}
{165}{}{Sim.}
{166}{}{Os Skulz estão planejando matar o Neal!}
{167}{}{Os homens do Lars rapidamente eliminam os Skulz.}
{168}{}{Parece que Lars ainda pode estar vivo, mas ele definitivamente está fora de cena.}
{169}{}{Viajante, você simplesmente ferrou com tudo. Nós precisávamos de evidência para que nós
 pudéssemos derrubar Gizmo com tudo certo e legalmente. Olha, fora do registro, eu estou feliz de ter
 aquela porra gorda fora do quadro, mas nós não podemos condenar de assassinato. Melhor você sair de
 Junktown e nunca voltar.}
{170}{}{Nós não gostamos do seu tipo aqui. Você tem por volta de quinze segundos antes que eu
 exploda seu cabeça.}
{171}{}{Olá de novo! O que eu posso fazer por você?}
{172}{}{Aham.}
{173}{}{Nã-ã.}
{174}{}{Você ganha 500 pontos de experiência por ajudar na eliminação da
 gangue dos Skulz.}
{970}{}{Esse é meu nome.}
{971}{}{Você está falando comigo.}
{972}{}{Sou eu.}
{980}{}{Não sei nada sobre isso.}
{981}{}{Desculpe. Não faço ideia.}
{982}{}{Nunca ouvi falar.}
{1000}{}{Gizmo}
{1001}{}{Gizmo}
{1002}{}{Junktown}
{1003}{}{Shady Sands|Shady|Sands}
{1004}{}{Hub}
{1005}{}{Water Chip|Waterchip|Chip|Chip de Agua}
{1006}{}{Casino|Gizmo's Casino|Gizmo's|Gizmos|Gizmos Casino|Cassino}
{1007}{}{Loja}
{1008}{}{Deathclaw}
{1009}{}{Medic|Doc|Doctor|Help|Healing|Hurt|Wounded|Injured|Morbid|Doc Morbid|Medico|Doutor|Ajuda|Cura|Ferido|Machucado}
{1010}{}{Buy|Buying|Sell|Selling|Barter|Trade|Trading|Business|Comprar|Vender|Trocar|Negociar|Negocio|Comercio|Barganha}
{1011}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Outside|Ermo|Terra Devastada|Devastada|La fora|Fora}
{1012}{}{Direction|Directions|Whereto|Where to|Direcao|Direcoes|Onde|Para onde|Caminho}
{1013}{}{Fallout|Fall out|nuclear fallout|Radiacao|precipitacao}
{1014}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev|Roubo|Ladrao|Ladroes|Furto|Crime|Criminosos}
{1015}{}{Necropolis|City of the Dead|City of Dead|Cidade dos Mortos}
{1016}{}{Boneyard|The Boneyard|L.A. Boneyard|LA|Los Angeles|LA Boneyard|Cemiterio}
{1017}{}{Story|Stories|Rumor|Rumors|Rumour|Rumours|Historia|Historias|Boato|Boatos|Rumores}
{1018}{}{Pitt|Skum Pitt|SkumPitt|Skumpit|Skum|Skum Pit|ScumPit|ScumPitt|Scum}
{1019}{}{Skuls|Skulz|Skulls|Skullz}
{1020}{}{Khan|Khans|Viper|Vipers|Raider|Raiders|Saqueador|Saqueadores}
{1021}{}{Crash|Crash House|Casa de Descanso}
{1022}{}{Beer|Booze|Cerveja|Bebida|Birita}
{1023}{}{Brahmin|Brahmins|Brahma|Vaca}
{1024}{}{Job|Work|Task|Money|Trabalho|Emprego|Tarefa|Servico|Dinheiro|Grana}
{1100}{}{Ele comanda o cassino. Ele é um crook.}
{1101}{}{Ele comanda o cassino. É um vigarista.}
{1102}{}{Isto é Junktown.}
{1103}{}{Ãh, acho que é um lugar bem pequeno. Nunca estive lá.}
{1104}{}{É uma cidade maior em algum lugar ao sul.}
{1105}{}{O quê? Desculpe.}
{1106}{}{É um prédio grande na parte noroeste da cidade.}
{1107}{}{A loja do Killian? Fica no centro da cidade.}
{1108}{}{Sei lá, mas o nome me dá medo.}
{1109}{}{Se você estiver machucado, o Doc Morbid com certeza pode te ajudar. A clínica dele fica ao sul daqui.}
{1110}{}{Killian Darkwater comanda a Loja Geral. Lá você provavelmente vai achar o que precisa.}
{1111}{}{Temos alguns guardas patrulhando o ermo. É um lugar perigoso, mas a gente se vira.}
{1112}{}{A loja do Killian fica logo ali na esquina. Se estiver procurando uma bebida, o Skum Pitt fica ao norte daqui. Também tem o cassino do Gizmo se você estiver atrás de diversão.}
{1113}{}{Fico feliz que não esteja chovendo assim faz um tempo.}
{1114}{}{Eles te enforcam se te pegarem roubando.}
{1115}{}{A Cidade dos Mortos, né? Só ouvimos algumas histórias e boatos.}
{1116}{}{É um lugar em algum ponto bem ao sul, até onde eu sei.}
{1117}{}{Sabe como é... Coisas.}
{1118}{}{Esse é o nosso bar. A comida é razoável, mas a cerveja é ótima.}
{1119}{}{Estamos de olho neles. Por que a pergunta? Você quer arrumar confusão?}
{1120}{}{Por sorte não temos muitos problemas com eles aqui embaixo. Ouvi dizer que é bem pior lá pro norte.}
{1121}{}{Se precisar de um lugar pra dormir, dê uma passada na Crash House.}
{1122}{}{Não, obrigado.}
{1123}{}{Dependemos deles para o comércio com o Hub.}
{1124}{}{Fale com o Killian. Ele é nosso Prefeito e pode ter um trabalho ou dois pra você.}
