{100}{}{Você vê: Lenny.}
{101}{}{Você vê um perdedor que cheira a Brahmin.}
{102}{}{[mais]}
{103}{}{[pronto]}
{104}{}{Você machucou um dos meus amigos! Vamos fazer você pagar por isso! Peguem ele, meninas!}
{105}{}{Uh, oi.}
{106}{}{O que você está fazendo aqui?}
{107}{}{Que animais são esses?}
{108}{}{Por que esses animais fedem tanto?}
{109}{}{Fedem? Eu não tinha notado. Acho que passei tanto tempo com eles que não me incomoda mais. São meus amigos.}
{110}{}{Estes são Brahmin. São meus amigos. Durmo no curral com eles pra não ficarem assustados à noite. Este lugar pode ficar meio apavorante, se você me entende.}
{111}{}{Não sei o que você quer dizer. Por que este lugar é apavorante?}
{112}{}{Posso comprar um?}
{113}{}{NÃO! Não! Não sou escravagista, como algumas dessas pessoas. Como você venderia seus amigos!?}
{114}{}{Eu não quis dizer isso, são só animais.}
{115}{}{Eu não faria isso, só estava te testando.}
{116}{}{Sussa, ganho mais dinheiro assim.}
{117}{}{Ah, entendo. Você não percebe o quanto os Brahmin são importantes pra mim. Tudo bem. Acho que as pessoas não me entendem.}
{118}{}{Uh, tchau.}
{119}{}{Você é malvado. Eu te odeio.}
{120}{}{Tanto faz.}
{121}{}{Ah. Ah, entendi. Ei, você é meio legal. Gostei de você. Devia te avisar sobre aqueles caras Tolos. Eles não gostam de mim. Não gostam de ninguém.}
{122}{}{Obrigado pela informação.}
{123}{}{As pessoas más. Elas brigam por coisas. Coisas que eu não entendo. Os piores são os Tolos. Eles pegam no meu pé. Não gostam de mim. [funga] Eu não gosto deles.}
{124}{}{Ah, você de novo.}
{125}{}{Me conte o que você sabe sobre os Tolos.}
{126}{}{Me conte o que você sabe sobre os Crypts.}
{127}{}{Quero saber sobre o gerador de energia.}
{128}{}{Até mais.}
{129}{}{Não gosto dos Tolos, eles vivem pegando no meu pé. Eles moram na garagem ao norte. Brigam com os Crypts, mas todos nós perdemos.}
{130}{}{Obrigado.}
{131}{}{Os Crypts são muito maus. Eles controlam a 'letricidade e, se a gente for mau, eles tiram da gente. Odeiam os Tolos, mais que tudo. Mais do que odeiam meus amigos.}
{132}{}{O que é a 'letricidade?}
{133}{}{O gerador? Ah, disso eu não sei.}
{134}{}{Ela alimenta as luzes. Faz todas as coisas funcionarem. Não sei bem, mas se a gente não tiver, não é bom.}
{135}{}{Não vou falar com você.}
{136}{}{Estou passando um tempo com meus amigos. Passo muito tempo com eles. São legais. Não me tratam mal. Não como algumas pessoas. [Lenny aperta os olhos.] Odeio algumas pessoas. Odeio os Tolos.}
{137}{}{Você me assusta.}
{138}{}{Foi gentil, mas você não respondeu minha pergunta.}
{139}{}{Ah, desculpa. O Lex diz que eu o assusto também. Não é por querer. E nunca assusto meus amigos.}
{140}{}{O que são seus amigos?}
{141}{}{Quem é o Lex?}
{142}{}{Ah, eu cuido dos Brahmin e garanto que nada aconteça com eles.}
{143}{}{Viu, não foi tão difícil, foi? O que são seus amigos?}
{144}{}{O Lex é legal. O Lex trata meus amigos como família. Uma vez por mês, ele até leva um dos meus amigos pra casa pro jantar. [Lenny sorri.] Aí ele deixa eles brincarem com um monte de Brahmin do céu. Não é legal?}
{145}{}{Sim, Lenny, é muito legal. Agora me conte sobre seus amigos.}
{146}{}{Lenny, acho que você precisa saber de uma coisa. O Lex come seus amigos.}
{147}{}{Não, você mente! Você é um mentiroso! O Lex nunca faria isso! Seu mentiroso fedorento! Vou te machucar por dizer isso na frente dos meus amigos.}
