{100}{}{Este computador contem uma grande quantidade de informação
 preservada de antes da Grande Guerra.}
{101}{}{Você usa o sistema de ensinamento do computador da vault.}
{102}{}{Você gasta algum tempo no sistema de ensinamento do computador
 da vault mas não aprende nada de importancia.
 O mundo exterior e seu professor agora.}
{103}{}{Você gasta algum tempo pesquisando um pouco de informação importante.}
{104}{}{Você gasta algum tempo na interweb não fazendo nada de importancia.}
{105}{}{Você mexe com o computador um pouco, mas é necessario um pouco de técnica
 cientifica pra realmente conseguir qualquer coisa util deste terminal.}
{106}{}{Você passa }
{107}{}{ horas no sistema de ensino do computador do Vault, mas não aprende nada de importante novo. O mundo exterior é seu professor agora.}
{108}{}{ horas na internet fazendo nada de importante. Foi divertido, mas te deixa com um vazio por dentro.}
{109}{}{ horas na internet procurando pornografia e vídeos de gatos.}
