{100}{}{O armario esta trancado.}
{101}{}{Você quebrou seus lockpicks.}
{102}{}{Você destranca o armario.}
{103}{}{Você falha em destrancar o armario.}
{104}{}{O armário já está destrancado.}
{105}{}{Suas gazuas quebram na fechadura!}
{106}{}{Você abre a fechadura com destreza.}
{107}{}{O armário está trancado.}
{108}{}{Você quebrou suas gazuas.}
{109}{}{Você destranca o armário.}
{110}{}{Você não consegue destrancar o armário.}
{111}{}{A explosão destrói completamente a fechadura.}
{112}{}{O recipiente é destruído pela explosão!}
