{100}{}{Você vê uma jovem de cabelos escuros.}
{101}{}{Você vê: Lorraine, uma catadora de Adytum.}
{102}{}{Oi. Você é novo por aqui?}
{103}{}{Sou. Você pode me situar um pouco?}
{104}{}{Sim, eu sou. Me chamo }
{105}{}{. }
{106}{}{Whuuu?}
{107}{}{Acho que sim. O que você precisa saber?}
{108}{}{Quem é você?}
{109}{}{Você pode me dar alguma informação sobre o Boneyard de L.A.?}
{110}{}{Me fale um pouco sobre os outros moradores de Adytum.}
{111}{}{O que você faz da vida?}
{112}{}{Deixa pra lá, obrigado.}
{113}{}{Sou a Lorraine.}
{114}{}{Posso te fazer umas perguntas?}
{115}{}{Sou catadora. Trabalho com o Sammael pra coletar coisas nas ruínas, pra gente usar na construção ou pra trocar.}
{116}{}{Por que nem todo mundo aqui faz isso?}
{117}{}{Quantos catadores existem?}
{118}{}{Posso te perguntar sobre outra coisa?}
{119}{}{Foi bom falar com você.}
{120}{}{Bom, tem as Deathclaws lá fora, mais os Regulators que ficam com uma porcentagem por cima, mais um tanto pela proteção aqui em Adytum. Acho que o povo não tem o dinheiro adiantado, nem a coragem de encarar uma Deathclaw nos olhos.}
{121}{}{Qual é a dos Regulators?}
{122}{}{Como vocês escapam das Deathclaws?}
{123}{}{Posso te perguntar sobre outras coisas?}
{124}{}{Obrigado. Tchau.}
{125}{}{Ah, tem uns meia dúzia de nós. O Sammael foi o primeiro, e ainda é o melhor.}
{126}{}{Posso te perguntar sobre outras coisas?}
{127}{}{Interessante. Obrigado.}
{128}{}{Eles mantêm a paz por aqui e controlam todo o dinheiro que entra e sai. O resto do povo daqui basicamente trabalha pros Regulators, e esse não é o trabalho mais compreensivo. Muitos deles nunca veem além da cerca que cerca este lugar.}
{129}{}{Tudo isso faz a gente se perguntar o que a Julianna estava pensando.}
{130}{}{Como assim, a Julianna?}
{131}{}{Bem desagradável. Posso perguntar outras coisas?}
{132}{}{Obrigado pelo aviso.}
{133}{}{Ah, ela acabou se apaixonando por um Lâmina um tempo atrás. A coitada não pode sair da cidade, claro, e o Caleb mataria o rapaz assim que o visse. Muito trágico.}
{134}{}{É... se você diz.}
{135}{}{Posso fazer outras perguntas?}
{136}{}{Hmm. Obrigado por me situar. Tchau.}
{137}{}{A gente só cata depois do anoitecer. E somos muito bons no que fazemos. O Sammael tem um testezinho que ele gosta de aplicar nas pessoas antes de deixá-las virar catadoras.}
{138}{}{Que teste é esse?}
{139}{}{Ainda parece perigoso.}
{140}{}{Entendi. Se importa se a gente voltar um pouco?}
{141}{}{Interessante. Tchau.}
{142}{}{O Sammael faz a pessoa se esconder em algum lugar dentro de Adytum durante o dia. Se ele não achar o aluno em uma hora, deixa a pessoa entrar na próxima expedição de catadores.}
{143}{}{Que sistema estúpido!}
{144}{}{Parece funcionar. Você ainda está viva.}
{145}{}{Han. Posso te perguntar sobre outras coisas?}
{146}{}{Interessante. Tchau.}
{147}{}{Ora, não há nem o mais leve traço de romântico em você? Sério, é uma pena. Amor não correspondido e tudo mais. Trágico.}
{148}{}{Hmpf. Isso mostra o quanto você sabe. Diga isso ao Sammael. Se conseguir encontrá-lo.}
{149}{}{Sim, embora possa ser duro. É muito perigoso, especialmente se você for pega.}
{150}{}{Sem dúvida. Posso perguntar sobre outra coisa?}
{151}{}{Obrigado pela informação.}
{152}{}{Uau, acho que você está um pouco além da minha ajuda.}
{153}{}{Isto aqui já foi uma cidade grande, chamada Los Angeles. Mas as bombas atingiram com força total. Agora, só resta o Boneyard de Angel. Nós, moradores de Adytum, só tentamos sobreviver nos escombros.}
{154}{}{Você pode me contar mais sobre Los Angeles?}
{155}{}{Entendi. Obrigado.}
{156}{}{Muita gente morava aqui. Pelo que ouvi, os sobreviventes se esconderam num lugar grande chamado Vault, e saíram anos depois. Alguns deles fundaram os Regulators e então Adytum, enquanto os }
{157}{}{outros formaram as Blades. Os Gun Runners não são daqui originalmente.}
{158}{}{Onde fica esse Vault?}
{159}{}{Qual é a dos Regulators?}
{160}{}{De onde são os Gun Runners?}
{161}{}{Criar jogos de computador? Não acho que isso seja particularmente importante.}
{162}{}{Obrigado pela ajuda.}
{163}{}{Bom, supostamente ficava em algum lugar ao sul daqui, mas eu não sei mesmo. Acho que todo mundo foi embora porque ele estava quebrado.}
{164}{}{Posso te fazer mais umas perguntas?}
{165}{}{Hmm. Obrigado.}
{166}{}{Não tenho certeza. Acho que eles vieram de algum lugar mais ao norte daqui.}
{167}{}{O que você sabe sobre os Regulators?}
{168}{}{Posso perguntar sobre outras coisas?}
{169}{}{Obrigado pela informação.}
{170}{}{Sobre quem você quer saber?}
{171}{}{Jon Zimmerman.}
{172}{}{Caleb.}
{173}{}{Miles.}
{174}{}{Tine.}
{175}{}{Smitty.}
{176}{}{Nobody.}
{177}{}{O Zimmerman cuida da nossa cidade. Ele garante que todos sejam alimentados e que cada um tenha um trabalho a fazer.}
{178}{}{O Caleb é o líder dos Regulators. É função dele proteger Adytum. Ele parece gostar disso um pouco mais do que deveria.}
{179}{}{Ah, nosso químico residente. O Miles faz balas, e também construiu o destilador de água que garante água limpa do poço pra gente. Ele está trabalhando numa fazenda subterrânea agora, mas está faltando umas peças.}
{180}{}{O Tine cuida da loja. Fica no búnquer perto do portão. Ele comercia com os mercadores do Hub pra gente.}
{181}{}{Hmm. O Smitty é um tipo de inventor. É bom em consertos. Ele funde balas e conserta coisas quebradas pela cidade.}
{182}{}{Posso perguntar sobre outra pessoa?}
{183}{}{A gente pode falar de outro assunto?}
{184}{}{Obrigado.}
{185}{}{Você está de brincadeira? Se não existissem jogos de computador, você não estaria jogando este jogo, não é?}
{200}{}{Oi de novo.}
