{100}{}{Você vê diante de você a mesa low stakes Craps. Custa $20 pra jogar.}
{101}{}{Você fez um 7. Você vence!!}
{102}{}{Você fez olhos de cobra. Você perde.}
{103}{}{Você fez }
{104}{}{! Você vence!!}
{105}{}{Você fez }
{106}{}{. Você perde.}
{107}{}{Você fez }
{108}{}{ antes de fazer seu ponto. Você perde.}
{109}{}{Você fez seu ponto. Você vence.}
{110}{}{Você fez }
{111}{}{. Este e seu ponto. Girando de novo.}
