{100}{}{Você vê o Loxley, lider da Guilda dos Ladroes.}
{101}{LOX_0}{É um pequeno presente do meu pai e mae. Na verdade, de algumas gerações antes disso. Você gosta?}
{102}{}{Combina com você.}
{103}{}{Não, machuca meus ouvidos.}
{104}{LOX_0A}{Por que? Obrigado. Você não sabe mas tenho que trabalhr um pouco pra mante-lo com tão pouco refinamento. Mas basta disso. Loxley e o nome. É o seu e?}
{105}{}{Eu sou }
{106}{}{.}
{107}{}{O que é que você quer?}
{108}{}{O que é este lugar?}
{110}{LOX_1F}{É bastante impressionante passar assim atraves das defesas! Qual e o seu nome, amor?}
{109}{LOX_1M}{Faz um trabalho muito bom de passar atraves das defesas camarada! Eu estou bastante impressionado. Mande seu nome!}
{111}{}{Eu sou }
{112}{}{.}
{113}{}{O que é que você quer?}
{114}{}{O que é este lugar?}
{115}{}{Você tem um sotaque bastante interessante, meu amigo.}
{116}{}{Você fala como um idiota.}
{117}{}{Nuhh?}
{118}{LOX_2F}{Bastante grato de fazer sua acquaintance na verdade...por agora. Vamos tomar conta da outra parte de educacao não vamos? O que diabos, diabos, diabos você esta fazendo aqui?}
{119}{}{Eu quero me juntar ao Circulo.}
{120}{}{Eu preciso pedir algumas coisas pra você.}
{121}{}{Eu estou levando todos vocês para a cadeia.}
{122}{LOX_3}{Ah, que bacana. A joiner. Bem, você trabalhou duro para um look-see. Ma se você realmente quer se juntar, então você tera que aceitar o segundo teste.}
{123}{}{O que é isso?}
{124}{}{Soa assustador . . . Que tal eu passar?}
{125}{}{Uh . . . qual era o primeiro teste?}
{126}{LOX_4}{Bastante simples, mesmo. Você se provou como ladrao. Faca sucesso e o mundo e seu! Se não, então você nunca nos vera de novo. Exceto se você vier procurando. E se você não entendeu essa ultima parte é uma ameaca.}
{127}{}{Qual e o teste?}
{128}{}{Você quer dizer que você se mudara deste lugar se eu falhar ou tentara me matar?}
{129}{}{Você esta me ameacando?}
{130}{LOX_5}{É tão, tão simples. Nas Alturas você achara a casa do Daren Hightower toda plump e ripe para pegar. Você esta preparado para a vida? Você aceita o desafio?}
{131}{}{Eu estou pronto!}
{132}{}{Inferno, não!}
{134}{LOX_6F}{Esse e o espirito, amor!}
{133}{LOX_6M}{Esse e o espirito, camarada!}
{135}{LOX_6B}{Apenas fale com a Jasmine na sala do outro lado desta camara. Ela dara os detalhes pra você, um mapa e algumas pequenas mercadorias pra ajudar você no seu caminho. Mas lembre-se, se você pensar em nos delatar pros policiais, nos seremos uma memória antes que eles cheguem. Mas basta de melancolia. Alegre-se, boa sorte e ta-ta!}
{136}{LOX_7}{Bem, então por que diabos você esta aqui? Pela vista? Pelo ambiente? Pela minha bonita face?}
{137}{}{Não, Eu vim fazer algumas perguntas pra você.}
{138}{}{Certamente não pela cara.}
{139}{}{Você esta certo. Eu gostaria de me juntar ao Circulo.}
{140}{LOX_8}{Isso e tudo? Algumas perguntas! Bem, ou você e incrivelmente bravo ou um total retardado. Pergunte, pergunte!... e então nos mostraremos a porta pra você.}
{141}{LOX_9}{Você deve estar brincando! Você pensou que eu cairia por uma frase como essa? Saia, seu commoner!}
{142}{LOX_10}{Ah, mas que atitudezinha! Mas todos nos somos amigos aqui, não somos?}
{143}{}{Eu não vejo o por que.}
{144}{}{Você esta certo. Eu lamento.}
{145}{LOX_11}{Ohhh, coração quebrado. Nossa chance de camaradagem perdida. [Suspiro] Jasmine, mostra a este pequeno sod a porta.}
{146}{LOX_12}{Ooh, um pouco pra tras e adiante. Eu gosto de alguém que joga no limite. Eu acho que você sera uma grande adicao ao nosso pequeno bando feliz. O que você diz?}
{147}{}{Certo!}
{148}{}{Eu digo que é um lunatico total.}
{149}{lox_12b}{Certo!}
{150}{LOX_13}{Ah, bosh and bother. Bem, na verdade estou bastante sorry de ouvir isso. Você daria um bom ladrao. Mas o Circulo não é para os terminalmente estupidos. Então, Jasmine, mostre a porta pro nosso convidado, por favor.}
{151}{LOX_14}{Ah, pelo que você me toma? Se você quer assassinato a sangue frio fale com o Decker e o bando dele. Se você falhar, o que parece muito mais provavelm neste ponto, nos simplesmente desapareceremos. Agora, então se importa de tentar ou não?}
{152}{}{Com certeza.}
{153}{}{Não.}
{154}{LOX_16}{Ah, não. Eu estou com tanto medo. A vida e tão difícil. Loxley, eu preferiria ser um covarde por toda a minha vida do que ter um unico momento de triunfo.. Ah, você e apenas outro punheteiro, não e? Fora!}
{155}{LOX_17}{Não pensei ainda, have we? O primeiro teste era apenas chegar aqui! Essa é a unica razão por que eu estou considerando você.}
{156}{}{Certo, eu farei o que quer que você queira!!}
{157}{}{Qual e o próximo teste?}
{158}{}{Bem, tudo que eu preciso fazer e fazer algumas perguntas pra você.}
{159}{LOX_18}{Há há há. Ooh, isso e bem divertido. Nós levar pra cadeia você vai? É como, posso eu perguntar, você planeja este feito?}
{160}{}{Apenas venha conosco silenciosamente e ninguém se machucara.}
{161}{}{Bem, talvez eu deixarei você passar desta vez.}
{162}{LOX_21}{What's it to me? É simples, mesmo. Diga-me seu nome ou nos mostramos a porta pra você.}
{163}{}{Certo. Eu sou }
{164}{}{.}
{165}{}{Que tal eu mostrar minha bota pra você?}
{166}{LOX_22}{Este e o famoso Circulo dos Ladroes! Eu pensei que você sabia disto, vendo como você passou por todas as defesas e tudo mais. Mas não importa. Você é bastante promissor, e o Circulo poderia usar alguém como você.}
{167}{}{Certo, o que eu tenho que fazer?}
{168}{}{Não obrigado. Apesar disso, eu gostaria de fazer algumas perguntas pra você.}
{169}{}{Sem chance.}
{170}{LOX_23}{Bem, você passou atraves das minhas defesas então você certamente tem tecnicas. Qual e o seu nome?}
{171}{}{Eu sou }
{172}{}{.}
{173}{}{O que é que você quer?}
{174}{}{O que é este lugar?}
{175}{}{Você tem um sotaque bastante interessante, meu amigo.}
{176}{}{Você fala como um idiota.}
{177}{LOX_24}{O que diabos você quer?}
{178}{}{O que eu fiz? Por que esta tão hostil?}
{179}{}{Para estar longe de você.}
{180}{}{Ei, Eu estou do seu lado. Eu estou aqui como um amigo.}
{181}{LOX_25}{Eu não gosto de você. Não sei por que, não me importo.}
{182}{}{Me de uma chance!}
{183}{}{Bem, você e apenas um idiota então, não e?}
{184}{LOX_26}{Obrigado por um momento tão amavel. Jasmine, mostre a saida para o nosso convidado.}
{185}{LOX_27}{Ah, que bacana ver você de novo. Você tem uma pequena alguma coisa pra mim?}
{186}{}{Minha resignacao. Eu decidi não fazer seu teste estúpido.}
{187}{}{Eu não entendi ainda.}
{188}{}{Aqui esta o colar . . .}
{189}{LOX_29}{Há! Há! Muito bem! Parabens. Você e agora um membro do mundialmente famoso Circulo dos Ladroes. Vamos pegar a Jasmine aqui e and throw a topper, shall we?}
{190}{LOX_30}{Ah, que engracado. Apesar disso, eu realmente devo dizer a você, que eu não me importo muito com este tipo de piada. Kind of a chuckle. O tipo de coisa de poe-mais-uma-no-velho-Loxley. Digo isto a você. Mais uma chance. Traga o colar aqui.}
{191}{LOX_31}{Você e realmente apenas uma completa dor no traseiro, não e?}
{192}{LOX_32}{Estupido! Ah. Eu estou tão desapontado que você se sinta deste modo. Ah, bem, nosso pequeno Circulo tera que continuar sem sua presença cintilante. Tao triste. Jasmine, a porta pro nosso convidado. É sem privelegios de retorno, hmm?}
{193}{LOX_33}{Então o que diabos, diabos você esta fazendo aqui? Xo! Vai embora. So que desta vez volte com o colar.}
{194}{}{Algo interessante acontece por aqui?}
{195}{}{Diga-me a respeito do Hub.}
{196}{}{Ouviu quaisquer bons rumores ultimamente?}
{197}{}{Diga-me mais sobre o Circulo.}
{198}{}{Eu estou procurando pelas caravanas desaparecidas. Quaisquer sugestoes?}
{199}{LOX_35}{Bem, a cidade inteira esta em um uproar, com as caravanas desaparecidas e tal. Algo doloroso. Corta os negócios do Circulo, você não sabia?}
{200}{}{Você sabe quem poderia ser responsável?}
{201}{}{Obrigado. Eu posso fazer mais algumas perguntas pra você?}
{202}{LOX_36}{Eu não sei, mas eu espero que eles descubram em breve. As pessoas estão edgy e torna nosso trabalho um pouco mais sticky, say what? Sem mencionar toda a baboseira supersticiosa voando por ai.}
{203}{}{Que tipo de baboseira?}
{204}{}{Obrigado. Eu posso fazer mais algumas perguntas pra você?}
{205}{LOX_37}{Ah, some bosh and bother que o deathclaw agarrou as caravanas, e as trouxe até o covil dele para um cha da tarde.}
{206}{}{Soa gostoso. Eu posso fazer mais algumas perguntas pra você?}
{207}{LOX_38A}{Ah, absolutamente. Nós somos todos amigos aqui.}
{208}{lox_38b}{[Suspiro] Por que não?}
{209}{LOX_38C}{Pergunte imediatamente, pergunte imediatamente.}
{210}{LOX_39}{Não, realmente. Você teve uma. Considere a si próprio sortudo. Tchau, ta-ta.}
{211}{lox_40}{Nada em que você estaria interessado.}
{212}{}{Me teste.}
{213}{}{Certo, obrigado. Eu posso fazer mais algumas perguntas pra você?}
{214}{LOX_41}{Ah, nada. apenas a maldita cidade inteira tem estado em armas com todas as caravanas desaparecidas. Isso e tudo.}
{215}{}{Gee, obrigado. Eu posso fazer mais algumas perguntas pra você?}
{216}{LOX_42}{Ah, apenas o de sempre. As caravanas dos mercadores engordam por causa dos pobres, enquanto o vilao Decker brinca com todos.}
{217}{LOX_43}{Bem, você tem os numeros comuns de lojas e coisas. Misture com alguns loucos das Crianças da Catedral. Adicione um dollop de Decker e do submundo dele tornando a vida difícil pra todos nos. Top it com um sprinkle de mercadores gananciosos e isso cobrira tudo.}
{218}{}{Mercadores são quando muito a escoria, huh?}
{219}{}{Soa como se você fosse um verdadeiro ajudante do Decker.}
{220}{LOX_43A}{Proxima pergunta, por favor.}
{221}{LOX_44}{Muito certo! É por isso que o Circulo foi formado. Você tem todos esses buggers rics, se alimentando dos pobres. É aqueles pobres estão esperando por um heroi. Por causa da ajudar que nos damos a ele, eles praticamente se ajoelham aos nossos pes.}
{222}{}{O que esta errado com fazer dinheiro?}
{223}{}{Igual o Robin Hood.}
{224}{LOX_47}{Qual e o mal! seu pequeno... bem, eu estava errado sobre você, não estava? Jasmine, mostre a porta pra este lambedor de botas de mercador!}
{225}{LOX_48}{Você conhece a estoria! Eu sabia que havia algo especial sobre você. Ah, meu avo me disse isso há muito tempo atras. Ele era um ladrao! Mas basta disso. Algo mais que você precise perguntar?}
{226}{LOX_51}{Alem das caravanas desaparecidas, não muito. Ah, espere. Um dos meus camaradas voltou ontem todo com um brilho com um toque de envenenamento por radiacao. Nasty business. Provavelmente tip-toed muito perto do velho Lugar Quente.}
{227}{LOX_53}{Nós roubamos dos ricos, plain e simples. Nós damos aproximadamente, oh, dez a vinte por cento pro pessoal pobre na Old Town. O Circulo mantem vinte, o que deixa o resto para o ladrao. Não e um negocio ruim.}
{228}{LOX_54}{Nós somos um bando de crooks! O que você pensava que nos fossemos? Um bando de cozinheiros?}
{229}{LOX_55A}{Você poderia verificar com os mercadores, embora seu tempo seria melhor gasto sizing them up pra um pouco de trabalho de remocao noturna. Enquanto eu acho que ele e bunk absoluto, pergunte por ai sobre o deathclaw. Ou mesmo siga uma caravana, se você perdeu totalmente a cabeca.}
{230}{LOX_55B}{Bem, como diabos eu deveria saber? Eu pareco um mercador?}
{231}{LOX_56}{Algums regras basicas. Primeiro, jamais seja pego, e dois, nunca, jamais roube do Circulo. Put it down.}
{232}{LOX_57}{Você não tem o hang of this, tem? Jasmine, a porta pro nosso tolo amigo e não deixe-me ver essa face de novo.}
{233}{LOX_58}{Eu não acho que você entendeu bem. Poupe para os mercadores, sim?}
{234}{LOX_59}{O que diabos você esta fazendo aqui? Saia!}
{235}{LOX_60}{Você vê, e como eu disse...}
{236}{LOX_61}{Bem, como eu disse...}
{237}{LOX_62}{Você e simplesmente thick? Eu disse a você...}
{238}{LOX_63}{Qual você e, surdo ou estúpido? Como eu disse...}
{239}{LOX_64}{Não e divertido repetir a mim mesmo.}
{240}{LOX_65}{Ugh! Não adianta. Obviamente nenhuma quantia de pounding pode possivelmente enfiar essa informação no seu cranio thick.}
{241}{LOX_66}{Não. Decker e um slick one. Ele tem a cidade inteira no bolso dele, ele tem. Ele da a 'protecao' dele aos mercadores, tudo enquanto poe eles uns contra os outros. Não e alguém com quem você queira mexer, mas ele geralmente pode ser achado no Maltese Falcon.}
{242}{LOX_67}{Ele e um traficante de armas na parte norte da Old Town. bloke bem perigoso, alguns dos seus itens são um pouco letais demais.}
{243}{LOX_68}{Não muito apreciador de nos realmente.}
{244}{LOX_69}{Harold? Ele e um tipo bom, sendo um ghoul e tal. Vive no lado sul.}
{245}{LOX_70}{O braco direito do Decker, definitivamente não é alguém com quem mexer. Você geralmente consegue achar ele no Maltese Falcon.}
{246}{LOX_71}{Eles, Sentando no alto e poderosos na Torre de Agua deles ao sul do centro, cobrando de todos nos pessoas decentes por qualquer gota de água que brota do chao. Eles deveriam todos  levar um tiro.}
{247}{LOX_72}{Eles tem uma pequena loja de artigos gerais no centro. Apesar disso, não pode confiar neles. Escondendo no armazem sangrento deles na maior parte do tempo. Eles vendem algumas drogas ruins e kits medicos. Muito mais baratos do que das Crianças da Catedral, eu posso dizer isso a você.}
{248}{LOX_73}{A coisa mais perto de decente de todas as tres caravanas. So perdeu por algumas milhas.}
{249}{LOX_74}{Criminosos. Absolutos criminosos. Eles estão espremendo a vida fora da cidade. Os Far Go Traders, a Crimson Caravan e os piores do bando, os Mercadores da Agua. Você pode ter o lote.}
{250}{lox_75}{É pra baixo no meio da cidade.}
{251}{LOX_76}{Não muito a dizer, realmente. De noite, assustar suas crianças com estorias sobre uma fera vivendo no norte e que se alimenta da carne de pequenas crianças mas em qualquer lugar.}
{252}{LOX_77}{Parece que todo dia outro se torna desaparecido. As pessoas estão com medo de sair da cidade sem protecao. Alguns até mesmo culpam o deathclaw.}
{253}{LOX_78}{Por volta de tres anos atras, um dos mercadores foi bem ao sul procurando outras cidades. Ele voltou com todo o cabelo e dentes caindo, balbuciando sobre algum grande span de radiacao. Quem sabe, talvez algo especial lá embaixo antes da guerra.}
{254}{LOX_79}{A maioria dos pobres que trabalham para os mercadores vivem aqui, em construções tão finas que elas não bloqueiam o sol. Enquanto isso, aqueles bastardos ricos estão confortaveis nas suas casas bacanas na alturas, Me faz ficar doente.}
{255}{LOX_80}{Construções bacanas. Compradas com o sangue dos pobres.}
{256}{LOX_81}{Você pode sempre achar o Bob no centro direto do Mercado dos Mercadores. Ele provavelmente estara vendendo aqueles pedacos de ihe keels over dead.}
{257}{LOX_82}{Agora, esse e um bando assustador. Eles strut around o dia todo falando sobre o deus da noite deles, como se ele fosse a melhor coisa desde os buracos nos bolsos dos mercadores. Eles podem curar você bem barato. Eu dou isso a eles. Você consegue acha-los naquele hospital no centro deles.}
{258}{LOX_83}{Ah, outro bando de loucos. Eles sentam na grande fortaleza grande deles ao norte, apenas esperando por outra guerra.}
{259}{LOX_84}{Precisa ser um pouco cuidadoso lá. Os Rippers e os Blades gostam de esculpir você apenas por diversão. Enquanto a cidade lá, Adytum, apenas tenta ficar viva. Se você achar a si próprio traipsing por lá e acontecer de encontrar os Blades, tente dizer oi para a Razor por mim. Pensar nela me traz memorias, se traz.}
{260}{LOX_85}{Eles são os sucateiros lá embaixo na Boneyard. Eles tem estado lutando por anos e eles nem ao menos sabem pelo o que mais. É bastante estúpido.}
{261}{LOX_86}{Ah, que mulher! Ela costumava ser uma ladra aqui, até que ela decidiu se mudar pra baixo ao sul na Boneyard. Da ultima vez que eu ouvi ela se juntou aos Blades. Ah, bem, o cerebro não era sua parte mais forte.}
{262}{LOX_87}{Hmm, não faço a menor ideia.}
{263}{LOX_88}{Eu realmente não sei.}
{264}{LOX_89}{Hmm. Não tenho uma pista, de verdade.}
{265}{LOX_90}{Bem, [Som derisivo], como um  retardado total, tal como você mesmo passa das minhas defesas? Lamento, não são permitidos idiotas selvagens, nos gostamos de boa conversa aquui. Jasmine, mostre a(o) nosso amigo que baba a porta por favor.}
{266}{LOX_91}{Fale com Jasmine e ela dara a você os detalhes.}
{267}{}{Loxley parece muito ocupado pra falar.}
{268}{}{Jasmine dara a você sua recompensa.}
{980}{LOX_87}{Hmm, não faço a menor ideia.}
{981}{LOX_88}{Eu realmente não sei.}
{982}{LOX_89}{Hmm. Não tenho uma pista, de verdade.}
{983}{LOX_90}{Bem, [Som derisivo], como um  retardado total, tal como você mesmo passa das minhas defesas? Lamento, não são permitidos idiotas selvagens, nos gostamos de boa conversa aquui. Jasmine, mostre a(o) nosso amigo que baba a porta por favor.}
{1000}{}{Decker}
{1001}{}{Jacob}
{1002}{}{Policia}
{1003}{}{Harold}
{1004}{}{Kane}
{1005}{}{Old}
{1006}{}{Crimson}
{1007}{}{Comerciantes}
{1008}{}{Caravanas}
{1009}{}{Mercado}
{1010}{}{Claw}
{1011}{}{Desaparecido}
{1012}{}{Quente}
{1013}{}{Cidade}
{1014}{}{Alturas}
{1015}{}{Bob's}
{1016}{}{Catedral}
{1017}{}{Brotherhood}
{1018}{}{Angel's}
{1019}{}{Blades}
{1020}{}{Razor}
{1021}{}{Mercadores}
{1022}{}{Local}
{1023}{}{Iguana}
{1024}{}{Pedacos}
{1025}{}{Bobs}
{1026}{}{Aco}
{1027}{}{Angels}
{1028}{}{Boneyard}
{1029}{}{Caravana}
{1030}{}{Morte}
{1031}{}{Deathclaw}
{1032}{}{Glow}
{1033}{}{Old Town}
{1100}{LOX_66}{Não. Decker e um slick one. Ele tem a cidade inteira no bolso dele, ele tem. Ele da a 'protecao' dele aos mercadores, tudo enquanto poe eles uns contra os outros. Não e alguém com quem você queira mexer, mas ele geralmente pode ser achado no Maltese Falcon.}
{1101}{LOX_67}{Ele e um traficante de armas na parte norte da Old Town. bloke bem perigoso, alguns dos seus itens são um pouco letais demais.}
{1102}{LOX_68}{Não muito apreciador de nos realmente.}
{1103}{LOX_69}{Harold? Ele e um tipo bom, sendo um ghoul e tal. Vive no lado sul.}
{1104}{LOX_70}{O braco direito do Decker, definitivamente não é alguém com quem mexer. Você geralmente consegue achar ele no Maltese Falcon.}
{1105}{LOX_79}{A maioria dos pobres que trabalham pros comerciantes mora aqui, em prédios tão finos que nem bloqueiam o sol. Enquanto isso, aqueles ricos desgraçados vivem confortáveis nas casas bonitas deles lá nos Heights. Me dá enjoo.}
{1106}{LOX_72}{Eles tem uma pequena loja de artigos gerais no centro. Apesar disso, não pode confiar neles. Escondendo no armazem sangrento deles na maior parte do tempo. Eles vendem algumas drogas ruins e kits medicos. Muito mais baratos do que das Crianças da Catedral, eu posso dizer isso a você.}
{1107}{LOX_73}{A coisa mais perto de decente de todas as tres caravanas. So perdeu por algumas milhas.}
{1108}{LOX_74}{Criminosos. Absolutos criminosos. Eles estão espremendo a vida fora da cidade. Os Far Go Traders, a Crimson Caravan e os piores do bando, os Mercadores da Agua. Você pode ter o lote.}
{1109}{lox_75}{É pra baixo no meio da cidade.}
{1110}{LOX_76}{Não muito a dizer, realmente. De noite, assustar suas crianças com estorias sobre uma fera vivendo no norte e que se alimenta da carne de pequenas crianças mas em qualquer lugar.}
{1111}{LOX_77}{Parece que todo dia outro se torna desaparecido. As pessoas estão com medo de sair da cidade sem protecao. Alguns até mesmo culpam o deathclaw.}
{1112}{LOX_78}{Por volta de tres anos atras, um dos mercadores foi bem ao sul procurando outras cidades. Ele voltou com todo o cabelo e dentes caindo, balbuciando sobre algum grande span de radiacao. Quem sabe, talvez algo especial lá embaixo antes da guerra.}
{1113}{LOX_79}{A maioria dos pobres que trabalham para os mercadores vivem aqui, em construções tão finas que elas não bloqueiam o sol. Enquanto isso, aqueles bastardos ricos estão confortaveis nas suas casas bacanas na alturas, Me faz ficar doente.}
{1114}{LOX_80}{Construções bacanas. Compradas com o sangue dos pobres.}
{1115}{LOX_81}{Você pode sempre achar o Bob no centro direto do Mercado dos Mercadores. Ele provavelmente estara vendendo aqueles pedacos de ihe keels over dead.}
{1116}{LOX_82}{Agora, esse e um bando assustador. Eles strut around o dia todo falando sobre o deus da noite deles, como se ele fosse a melhor coisa desde os buracos nos bolsos dos mercadores. Eles podem curar você bem barato. Eu dou isso a eles. Você consegue acha-los naquele hospital no centro deles.}
{1117}{LOX_83}{Ah, outro bando de loucos. Eles sentam na grande fortaleza grande deles ao norte, apenas esperando por outra guerra.}
{1118}{LOX_84}{Precisa ser um pouco cuidadoso lá. Os Rippers e os Blades gostam de esculpir você apenas por diversão. Enquanto a cidade lá, Adytum, apenas tenta ficar viva. Se você achar a si próprio traipsing por lá e acontecer de encontrar os Blades, tente dizer oi para a Razor por mim. Pensar nela me traz memorias, se traz.}
{1119}{LOX_85}{Eles são os sucateiros lá embaixo na Boneyard. Eles tem estado lutando por anos e eles nem ao menos sabem pelo o que mais. É bastante estúpido.}
{1120}{LOX_86}{Ah, que mulher! Ela costumava ser uma ladra aqui, até que ela decidiu se mudar pra baixo ao sul na Boneyard. Da ultima vez que eu ouvi ela se juntou aos Blades. Ah, bem, o cerebro não era sua parte mais forte.}
{1121}{LOX_71}{Eles, Sentando no alto e poderosos na Torre de Agua deles ao sul do centro, cobrando de todos nos pessoas decentes por qualquer gota de água que brota do chao. Eles deveriam todos  levar um tiro.}
{1122}{LOX_78}{Por volta de tres anos atras, um dos mercadores foi bem ao sul procurando outras cidades. Ele voltou com todo o cabelo e dentes caindo, balbuciando sobre algum grande span de radiacao. Quem sabe, talvez algo especial lá embaixo antes da guerra.}
{1123}{LOX_81}{Você pode sempre achar o Bob no centro direto do Mercado dos Mercadores. Ele provavelmente estara vendendo aqueles pedacos de ihe keels over dead.}
{1124}{LOX_81}{Você pode sempre achar o Bob no centro direto do Mercado dos Mercadores. Ele provavelmente estara vendendo aqueles pedacos de ihe keels over dead.}
{1125}{LOX_81}{Você pode sempre achar o Bob no centro direto do Mercado dos Mercadores. Ele provavelmente estara vendendo aqueles pedacos de ihe keels over dead.}
{1126}{LOX_83}{Ah, outro bando de loucos. Eles sentam na grande fortaleza grande deles ao norte, apenas esperando por outra guerra.}
{1127}{LOX_84}{Precisa ser um pouco cuidadoso lá. Os Rippers e os Blades gostam de esculpir você apenas por diversão. Enquanto a cidade lá, Adytum, apenas tenta ficar viva. Se você achar a si próprio traipsing por lá e acontecer de encontrar os Blades, tente dizer oi para a Razor por mim. Pensar nela me traz memorias, se traz.}
{1128}{LOX_84}{Precisa ser um pouco cuidadoso lá. Os Rippers e os Blades gostam de esculpir você apenas por diversão. Enquanto a cidade lá, Adytum, apenas tenta ficar viva. Se você achar a si próprio traipsing por lá e acontecer de encontrar os Blades, tente dizer oi para a Razor por mim. Pensar nela me traz memorias, se traz.}
{1129}{LOX_74}{Criminosos. Absolutos criminosos. Eles estão espremendo a vida fora da cidade. Os Far Go Traders, a Crimson Caravan e os piores do bando, os Mercadores da Agua. Você pode ter o lote.}
{1130}{LOX_76}{Não muito a dizer, realmente. De noite, assustar suas crianças com estorias sobre uma fera vivendo no norte e que se alimenta da carne de pequenas crianças mas em qualquer lugar.}
{1131}{LOX_76}{Não muito a dizer, realmente. De noite, assustar suas crianças com estorias sobre uma fera vivendo no norte e que se alimenta da carne de pequenas crianças mas em qualquer lugar.}
{1132}{LOX_78}{Por volta de tres anos atras, um dos mercadores foi bem ao sul procurando outras cidades. Ele voltou com todo o cabelo e dentes caindo, balbuciando sobre algum grande span de radiacao. Quem sabe, talvez algo especial lá embaixo antes da guerra.}
{1133}{LOX_79}{A maioria dos pobres que trabalham para os mercadores vivem aqui, em construções tão finas que elas não bloqueiam o sol. Enquanto isso, aqueles bastardos ricos estão confortaveis nas suas casas bacanas na alturas, Me faz ficar doente.}
{1034}{}{Velho}
{1134}{}{A maioria dos pobres que trabalham para os mercadores vivem aqui, em construções tão finas que elas não bloqueiam o sol. Enquanto isso, aqueles bastardos ricos estão confortaveis nas suas casas bacanas na alturas, Me faz ficar doente.}
