{100}{}{Você vê um homem forte, stout com uma barba bushy.}
{101}{}{Você vê o MacRae.}
{102}{}{Ola Lad, o que você poderia estar procurando hoje?}
{103}{}{Ola Lass, o que você poderia estar procurando hoje?}
{104}{}{Ei, O que mais você estaria procurando saber?}
{105}{}{Quem é você?}
{106}{}{O que você pode me dizer sobre os Blades?}
{107}{}{Nada, obrigado.}
{108}{}{Bem, eu sou o MacRae. Eu ajudo os Blades contra alguns dos deathclaws e daquele bando dos
 Reguladores. Ensino eles um pouco sobre protegerem a si mesmos contra esses malvados.}
{109}{}{Que tipo de coisa você ensina a eles?}
{110}{}{Você viu os deathclaws?}
{111}{}{Qual e o problema com os Regulators?}
{112}{}{Eu posso perguntar algo mais pra você?}
{113}{}{Bem, minha especialidade e lutar com meus punhos, e levar um soco ou dois mais do que
 o cara que os da em mim.}
{114}{}{Soa como um ideia burra, eu preferiria usar uma arma.}
{115}{}{Você acha que você poderia me ensinar alguma coisa?}
{116}{}{Eu posso perguntar algo mais pra você?}
{117}{}{Bem, se e assim como você esta se sentindo você pode simplesmente se virar e ir embora.}
{118}{}{Você parece ser um lad legal, mas meu tempo esta ocupado em manter os Blades treinados.
 Se as coisas se endireitarem, eu poderia então ter o tempo.}
{119}{}{Tudo bem, eu posso perguntar algo mais pra você?}
{120}{}{Obrigado pela informacaormacao.}
{121}{}{Ver eles eu vi. Corri pra caramba, eu corri. Se você esta procurando por eles você achara
 eles logo ali. [MacRae aponta pro leste]}
{122}{}{Eu estava achndo que os deathclaws eram a cria de ato não natural, mas os Reguladores são maus. Venha
 uma vez por mes mais ou menos e eles mostram suas caras feias e arrastam um pai pra longe dos seus pequenos.}
{123}{}{Qualquer coisa que eu poderia fazer pra ajudar?}
{124}{}{Soa ruim, eu poderia fazer outra pergunta pra você?}
{125}{}{Obrigado pela informação.}
{126}{}{Você vai querer falar com a Razor. Uma boa lass se houve uma.}
{127}{}{Um bom grupo de pessoas e o que os Blades são. Presos entre os malditos Reguladores e os
 deathclaws ain't meant a vida mais feliz pra eles, mas eles sobrevivem.}
{128}{}{[MacRae bate nas suas costas] Obrigado a você, os Blades vao viver uma vida melhor. Então,
 o que um velho escoces pode fazer por você?}
{129}{}{Você disse mais cedo que se você tivesse algum tempo livre, você poderia me ensinar algumas coisas.}
{130}{}{O que você tem feito ultimamente?}
{131}{}{O que você faz por aqui?}
{132}{}{Sem problema.}
{133}{}{Bem, tem estado um pouco quieto desde que os Blades ajudaram Adytum com os Reguladores. Meus
 servicos de ensino não tem estado com tanta demanda.}
{134}{}{O que você ensina?}
{135}{}{Lamento ouvir isso, espero que as coisas fiquem mais interessantes.}
{136}{}{Você poderia me ensinar?}
{137}{}{Soa interessante, mas eu tenho que ir.}
{138}{}{Bem, eu creio que eu tenho o tempo. Poderia tambem começar agora mesmo. [MacRae comeca a mostrar
 pra você algumas posições de luta, e modos de levar socos como um verdadeiro escoces.]}
{139}{}{Você ser um aprendiz rapido. Espero que ajude você nas suas viagens.}
{140}{}{Bem, eu costumava ajudar os Blades ensinando eles algumas coisas sobre proteger a si mesmos
 contra os deathclaws e os Reguladores. Agora que você tomou conta de tudo isso as coisas ficaram
 um pouco entediantes ultimamente.}
{141}{}{Bom ver você.}
{1180}{}{Você parece uma moça de bem, mas meu tempo anda ocupado mantendo as Blades treinadas. Se as coisas se ajeitassem, aí talvez eu tivesse tempo.}
