{100}{}{Você vê Marcelles.}
{101}{}{Você vê uma mulher de aparencia forte.}
{102}{}{Gracas a deus que você esta aqui! Algum cara louco tem a Sinthia mantida
 como refem. Ele esta ameacando matar ela! Você tem que ajudar.}
{103}{}{Não, não me aborreca.}
{104}{}{Hmm. Eu vou ver.}
{105}{}{Bosta!}
{106}{}{Ah    , eu espero que você consiga faze-lo. Ele esta no quarto dela. Ajude ela!}
{107}{}{Você é uma pessoa incrivelmente fria. Ela poderia morrer sem sua ajuda.}
{108}{}{Dificil. Essa é a vida.}
{109}{}{Tudo bem, não harp on me. Eu olharei isso.}
{110}{}{Ajude a Sinthia. Ela esta com problemas.}
{111}{}{Obrigado a você por ajudar a Sinthia. Ela geralmente não é um
 problema. Você merece uma boa noite de sono. Comigo. Mas não peca
 por outra de graca.}
{112}{}{Hnn. Facinora.}
{113}{}{Obrigado.}
{114}{}{Sem problema. Quarto Número 1. Siga-me.}
{115}{}{Aprecie sua estada. Não seja uma dor paras os outros.}
{116}{}{Você deveria ter salvado a Sinthia. É sua culpa que ela morreu.
 Eu espero que você esteja feliz consigo mesmo.}
{117}{}{Sim, que seja.}
{118}{}{Hnnn.}
{119}{}{Bem-vindo a Crash House. Como eu posso ajudar você, estranho?}
{120}{}{Eu estou procurando por um pouco de água.}
{121}{}{Eu preciso de uma boa noite de sono.}
{122}{}{Eu estou procurando por um pouco de informação.}
{123}{}{Hnnn.}
{124}{}{Sim, nos servimos o seu tipo tambem. Sao $25 pela noite.
 Uma semana custara a você $150.}
{125}{}{Não.}
{126}{}{Tá bom.}
{127}{}{Ahkay. Semana.}
{128}{}{Sim, você tambem. Tenha um bom dia.}
{129}{}{Okay, obrigado. Seu quarto e o quarto #1. Siga-me. Não dispare
 quaisquer armas aqui, okay?}
{130}{}{Tenha uma boa estada.}
{131}{}{Você precisa de um pouco de dinheiro antes que eu possa alugar a você um quarto.}
{132}{}{Então você deveria tentar o Skum Pitt. Eu ouvi que você consegue muita
 água na sua cerveja lá.}
{133}{}{Eu não sei sobre isso, mas eu alugarei um quarto pra você. É um bom lugar
 pra descansar e curar. $25 por um dia ou uma semana por $150. A maioria das
 pessoas vao na taxa semanal. Você deveria ir tambem, se você me pergunta.}
{134}{}{Certo. Uma semana.}
{135}{}{Apenas uma noite.}
{136}{}{Não, obrigado.}
{137}{}{Eu sou apenas uma gerente de hotel, bub. Não peca muito de mim.}
{138}{}{Aqui estão $50, diga-me o que você sabe.}
{139}{}{Eu seu que você esta $50 mais pobre. Eu não faco coisa de fofoca, okay?
 Volte se você quiser um quarto.}
{140}{}{O que você pensa que eu sou? Uma tola? Se você vai me subornar tenha
 dinheiro o bastante.}
{141}{}{Bem-vindo de volta. o que eu posso fazer por você?}
{142}{}{Eu quero alugar um quarto.}
{143}{}{Hnnn.}
{144}{}{Você ja esta alugando o quarto Número 1 de mim. Você quer que eu mostre
 a você aonde e?}
{145}{}{Com certeza.}
{146}{}{Não.}
{147}{}{Sim.}
{148}{}{Não.}
{149}{}{É este ainda e seu quarto. Tenha um bom dia.}
{150}{}{Você conhece the drill. Um dia são $25. Uma semana são $150.}
{151}{}{Não.}
{152}{}{Dia.}
{153}{}{Semana.}
{154}{}{Com certeza. Sao $25 por um dia ou $150 pela semana inteira.}
{155}{}{Certo. Uma semana.}
{156}{}{Apenas uma noite.}
{157}{}{Não, obrigado.}
{158}{}{Certo. O quarto Número 1 é seu. Tenha uma boa estada.}
{159}{}{Sim, o que você quer?}
{160}{}{Eu quero alugar um quarto.}
{161}{}{Hnn.}
{162}{}{Não. Vá embora.}
{163}{}{Eu não gosto da sua face. Eu não acho que eu alugarei um quarto pra você.}
{164}{}{Eu realmente preciso de um lugar pra ficar.}
{165}{}{Não. Tenha uma boa noite.}
{166}{}{Certo. Uma noite. $100.}
{167}{}{O que! Isso e ultrajante!}
{168}{}{Certo.}
{169}{}{Lide com isso. Sim ou não.}
{170}{}{Não.}
{171}{}{Certo.}
{172}{}{Bom. Aqui vai você. Quarto Número 1. Tenha uma boa noite, verifique a hora,
 são 11 horas.}
{173}{}{Você matou o Killian, não matou?}
{174}{}{Sim, com certeza matei.}
{175}{}{Não, não era eu. Realmente não era.}
{176}{}{Hnn.}
{177}{}{Saia! Você e muito burro pra perceber o que você fez, mas a minha
 vida e o inferno agora!}
{178}{}{Seu filho da puta. Eu não consigo acreditar que você matou ele. Ele
 era um bom homem, e agora eu tenho todos os tipos de problemas . . .
 saia, e não volte.}
{179}{}{Sim, o que quer que seja que você disse, mas isso não é o que eu
 ouvi. Melhor você se comportar por aqui, ou eu pegarei a velha Betsy
 e ram some buckshot up no seu traseiro.}
{180}{}{Esta tarde. Eu espero que você não esteja desperdicando meu tempo.}
{181}{}{Ei! Aquela geladeira e apenas pra fregueses!}
{182}{}{Não, obrigado.}
{183}{}{Marcelles charges in para confrontar o saqueador!}
{184}{}{Uh, nada. Deixa pra lá.}
{185}{}{Ah, nada. Deixa pra lá.}
