{100}{}{Você vê o Dr. Solone, M.D.}
{101}{}{Você vê a Enfermeira Marney.}
{102}{}{Você vê um doutor.}
{103}{}{Você vê uma enfermeira.}
{104}{}{Bem-vindos. Como eu poderia ajudar você hoje?}
{105}{}{Hurrgh.}
{106}{}{Eu estou ferido. Você pode me consertar?}
{107}{}{Você pode me ensinar sobre medicina?}
{108}{}{Sim, eu vejo que você esta sofrendo de algum dano. Isto
 pode levar algum tempo. Você gostaria que eu tentasse
 consertar suas feridas?}
{109}{}{Ãhã.}
{110}{}{Nã-ã.}
{111}{}{Sim, por favor.}
{112}{}{Não, obrigado.}
{113}{}{Ai vai você. Isso deve deixar você todo pronto. Por favor
 seja mais cuidadoso lá fora.}
{114}{}{Você e boa nisso. Você pode me ensinar sobre cuidado de traumas?}
{115}{}{Okay. Obrigado.}
{116}{}{Eu posso ensinar um pouco pra você. Mas levara varias horas. Você esta
 querendo ficar?}
{117}{}{Sim.}
{118}{}{Lamento, muito ocupado.}
{119}{}{Você é um estudante muito bom. Eu espero que você permaneca no nosso
 lado. Tchau.}
{120}{}{Como você desejar. Boa sorte lá fora.}
{121}{}{Eu posso ensinar um pouco pra você, mas não muito. Levera algum
 tempo. Você esta querendo ficar?}
{122}{}{Sim.}
{123}{}{Eu lamento, mas eu tenho falta de um tempo extra.}
{124}{}{Você é um estudante excelente. Boa sorte pra você.}
{125}{}{Agora mesmo, nada. Obrigado de qualquer maneira.}
