{100}{}{A porta esta trancada. Um codigo de seguranca e requerido para destranca-lá.}
{101}{}{Você insere o codigo da fita, e destranca a porta.}
{102}{}{A porta não esta trancada.}
{103}{}{Você bypass o codigo de seguranca e destranca a porta.}
{104}{}{Você e incapaz de destrancar a porta.}
{105}{}{Você e incapaz de destrancar a porta. Isto poderia ser mais fácil se você
 usasse um conjunto de ferramentas lockpicking eletronicas nela.}
{106}{}{A explosao e poderosa, mas nem ao menos dent ou marcou a
 porta de seguranca.}
