{100}{}{O que você quer?}
{101}{}{Ei, você vai comer esse rato morto?}
{102}{}{O que?}
{103}{}{Você viu meu cachorro, Elvis? Ele esta por aqui em algum lugar.}
{104}{}{Oi.}
{105}{}{Ei, você ouviu que Set foi desativado?}
{106}{}{Conjunto está morto. Set está morto. Set está morto. . .}
{107}{}{Eu vou gnaw seus ossos!}
{108}{}{Morte! Morte! Morte!}
{109}{}{Ei, você ouviu que Set foi morto?}
{110}{}{Set esta morto. Set esta morto. Set esta morto . . .}
{111}{}{Há bastante água to go around para todos.
 Set faz ter certeza disso.}
{112}{}{Eu ouvi que os mutantes fugiram da cidade.}
{113}{}{Desde que os mutantes sairam tem sido melhor.}
{114}{}{Ola.}
