{100}{}{Você vê Michelle.}
{101}{}{}
{102}{}{}
{103}{}{Você vê um membro dos Blades.}
{104}{}{Você vê um membro dos Blades.}
{105}{}{Você acha que podem ser Livros.}
{106}{}{Você acha que isso pode ser Scars.}
{107}{}{Você acha que pode ser Artilheiro.}
{108}{}{Você acha que pode ser o Twitch.}
{109}{}{Você acha que pode ser o Hammer.}
{110}{}{Você acha que pode ser Razor.}
{111}{}{O que você está fazendo aqui?}
{112}{}{Hhrrrnnn.}
{113}{}{Nada. Honesto.}
{114}{}{Estou apenas olhando em volta.}
{115}{}{Isto! * smack *}
{116}{}{Um idiota. Eu acho que é melhor você sair daqui. De outra forma,
 você pode se tornar uma prática de alvo.}
{117}{}{Arroo!}
{118}{}{Arook}
{119}{}{Nothing, eh? Eu acho que você está escondendo alguma coisa. Fora com isso
 antes de ver sua coragem.}
{120}{}{Eu sou realmente um marciano.}
{121}{}{Estou aqui para parar as guerras de gangues.}
{122}{}{Não estou à altura de nada.}
{123}{}{Eu estou até isso! * smack *}
{124}{}{Todo mundo sabe que não existem coisas como marcianos.
 Todos os alienígenas são de Vênus. Agora você morre!}
{125}{}{Claro, e eu sou a rainha do México.}
{126}{}{Honestos. Eu quero parar as guerras para que eu possa ajudar Adytum.}
{127}{}{Sua Majestade, eu realmente procuro terminar as guerras.}
{128}{}{Se a sua inteligência fosse maior, eu tentaria
 explicar os benefícios da paz.}
{129}{}{Se você está aqui para fazer isso, então você precisa tentar encontrar
 Navalha. Ela vai deixar você saber o que achamos disso.}
{130}{}{Uh, obrigado. Eu acho que.}
{131}{}{Certo. Tchau.}
{132}{}{Zomba de mim, você vai? Eu acho que deveria esperar tanto de um
 criança. Ah, por falar nisso. Aqui!}
{133}{}{Fancy talk só vai te levar tão longe. Aqui vai ficar
 você cerca de seis pés abaixo.}
{134}{}{Se você está fazendo nada, então vamos colocá-lo para
 alguma coisa. Eu acho que 'alvo' faz uma coisa boa.}
{135}{}{Você olhou. Agora o que você quer? Pense rápido. Isso pode significar
 a diferença entre sair daqui e se tornar
 um residente permanente.}
{136}{}{Gostaria de viver aqui.}
{137}{}{Eu sou realmente um Estripador disfarçado.}
{138}{}{Eu quero trazer paz às gangues.}
{139}{}{Deixando}
{140}{}{Nada de especial. Apenas olhando para o lixo para ser
 reciclado.}
{141}{}{Nós nunca dissemos nada sobre viver. Você seria apenas
 residir aqui. Indefinidamente. Aproveite sua estadia.}
{142}{}{Fico feliz que você tenha dito isso. Eu tenho significado para aguçar isso. }
{143}{}{Em breve vou ter um esconderijo para afiá-lo.}
{144}{}{Não tão rápido. A única maneira de alguém sair daqui é se eles
 são uma Lâmina ou em uma bolsa.}
{145}{}{Então eu quero ser uma Blade.}
{146}{}{Quão grande é essa sacola?}
{147}{}{Você esquece a terceira opção. Eu!}
{148}{}{chance de gordura. Mas ele é um teste. Se você pode encontrar Razor, então
 você pode falar com ela sobre isso.}
{149}{}{Grande o suficiente para encher suas partes do corpo quando terminarmos.}
{150}{}{Eu não sou Bela Adormecida. Eu não preciso ser despertado.
 Saia ou morra.}
{151}{}{Ouça que você está fora pela cabeça do bastardo. Dê a ele um extra
 faca torcer para mim.}
{152}{}{Bem-vindo de volta. O buraco está aberto e pronto para abrigá-lo mais uma vez.}
