{100}{}{Você vê o Doutor Morbid.}
{101}{}{Eu sou o Doutor Morbid, Eu posso ajudar você?}
{102}{}{Sim, eu preciso de um pouco de ajuda.}
{103}{}{Eu preciso de um pouco de assistencia medica.}
{104}{}{Não, hoje não.}
{105}{}{Nng.}
{106}{}{É.}
{107}{}{Bem, ok então. Volta de novo.}
{108}{}{Bem, se não hoje então talvez no futuro
 próximo.}
{109}{}{Espero que não. Tchau.}
{110}{}{Nós teremos que ver não teremos? Mas eu duvido.}
{111}{}{Hmm, vamos dar uma olhada.}
{112}{}{Você parece estar com saude proxima de perfeita. Serao $10
 pelo exame.}
{113}{}{Dez tampinhas pra você me dizer isso? Você deve estar brincando.}
{114}{}{Aqui vai. Tome seu dinheiro.}
{115}{}{Eu nuna faço piada. Especialmente quando tem a ver com trauma
 fisico. Você pagara ou eu terei que recorrer a outras formas de
 compensaçao, muitas das quais são muito mais dolorosas do que
 simplesmente pagar minha fee.}
{116}{}{Certo, aqui esta seu dinheiro.}
{117}{}{Me morda. Eu estou saindo.}
{118}{}{Que seja do seu jeito. Cougar, Flash. Mostrem o
 laboratorio para o nosso 'paciente'.}
{119}{}{Obrigado por fazer negocio. Volte de novo.}
{120}{}{Você não tem dinheiro o bastante. Eu tenho um jeito
 muito especial de lidar com devedores - Eu não tenho.
 Flash e Cougar, levem nossa nova fonte descoberta de
 renda para o laboratorio para processamento.}
{121}{}{Certo, Eu tenho os resultados do seu teste:}
{122}{}{Você esta }
{123}{}{O custo total sera de $}
{124}{}{. O pagamento e feito antes do
 tratamento. Sem exceçoes. Você pagara?}
{125}{}{Sim, Eu pagarei.}
{126}{}{Não, Eu não tenho o dinheiro. Will you float me?}
{127}{}{Não.}
{128}{}{É.}
{129}{}{Nã.}
{130}{}{Não. Eu não empresto a ninguém e eu quero dizer a ninguém,
 qualquer quantia de dinheiro. Vai embora seu pauper.}
{131}{}{É sua vida. Tchau.}
{132}{}{Excelente. Vamos começar. Isto poderia machucar um pouco...}
{133}{}{Ai vai. Volte de novo!}
{134}{}{Ah, de volta tão cedo. Com o que eu posso ajudar você?}
{135}{}{Eu preciso de cura.}
{136}{}{Nada, só conversando.}
{137}{}{Wock!}
{138}{}{Por favor o faça em algum outro lugar. Eu estou ocupado.}
{139}{}{Hmmm. Eu não gosto da sua aparencia estranho. Mas o que eu posso
 fazer por você? Eu nunca jamais rejeito um fregues que paga.}
{140}{}{eu preciso de um pouco de ajuda.}
{141}{}{Eu preciso de um pouco de assistencia medica.}
{142}{}{Nada hoje, obrigado.}
{143}{}{Hep.}
{144}{}{Ah, e você de novo. Eu gosto doe seu estilo mesmo se eu não
 gosto de você. Com o que eu posso ajudar você agora?}
{145}{}{Eu preciso de cura.}
{146}{}{Nada, só conversando.}
{147}{}{Wock!}
{148}{}{Ah, É um fregues! Com o que eu posso ajudar você?}
{149}{}{Eu preciso de cura.}
{150}{}{Nada, só conversando.}
{151}{}{Você parece excitado em me ver. Por que?}
{152}{}{Wock!}
{153}{}{Meus negócios cairam recentemente. Eu estou feliz de ver quaisquer
 fregueses estes dias. Não que eu me importe com sua companhia claro.}
{154}{}{Excelente, Eu preciso de um pouco de cura.}
{155}{}{Por que seus negócios cairam?}
{156}{}{Claro. Eu entendo. Tenha um bom dia.}
{157}{}{Bem, se você precisar de alguma coisa por favor passe. Ninguem consegue ganhar dos meus serviços!}
{158}{}{No caso de você não ter notado eu tenho alguns competidores.}
{159}{}{ Se queixar com o Killain não dara em nada. Ele não vê
 nada errado com os recem-chegados.}
{160}{}{ Aquelas malditas Crianças se mudara para a porta ao lado e tal, hm, muito
 do meu negocio foi pra eles. Eu não gosto mas eu não posso baixar meus preços
 pra competir com o deles. Eu só posso fornecer um serviço melhor.}
{161}{}{Ahh, Eu do preciso de um pouco de cura.}
{162}{}{Hmm, preços melhores, interessante. Obrigado.}
{163}{}{Ahh, um fregues repetido. Excelente neste dias! Como eu
 posso ajudar você?}
{164}{}{Eu preciso de cura.}
{165}{}{Nada, só conversando.}
{166}{}{Wock!}
{167}{}{Eu espero que você tenha uma boa razão pra me perturbar. Meu tempo e extremamente
 valioso.}
{168}{}{Eu estou morrendo aqui! Por favor me ajude!}
{169}{}{Eu lamento perturbar você mas eu preciso de assistencia.}
{170}{}{Aggh!}
{171}{}{Eu não acho seu humor engraçado. Por favor saia pra que eu
 possa retornar ao meu trabalho.}
{172}{}{Hmm. Bem, você parece bem pra mim. Talvez você precise de um pouco
 de descanso. Tente a Crash House na esquina. Boa noite.}
{173}{}{Eu lamento, eu não trato idiotas a esta hora da noite.
 Algo a ver com luas cheias e loucura eu suponho. Tenha uma
 boa noite.}
{174}{}{Você de novo. Eu espero que você tenha outra boa razão pra
 me perturbar...}
{175}{}{Eu estou morrendo aqui! Por favor me ajude!}
{176}{}{Eu lamento perturbar você mas eu preciso de assistencia.}
{177}{}{Aggh!}
{178}{}{perfeitamente saudavel,}
{179}{}{leveremente ferido,}
{180}{}{moderadamente ferido,}
{181}{}{seriamente ferido,}
{182}{}{próximo da morte,}
{183}{}{ na minha opiniao medica.}
{184}{}{ de acordo com meus testes.}
{185}{}{ sem duvida.}
{186}{}{ na minha humilde opiniao.}
{187}{}{ Você esta definitivamente sofrendo por causa do veneno.}
{188}{}{ Você foi envenenado.}
{189}{}{ Você sabia que você foi envenenado?}
{190}{}{ Você tem uma toxina mortal nua sua corrente sanguinea.}
{191}{}{ Você tem um envenenamento menor por radiaçao.}
{192}{}{ Você tem um serio envenenamento por radiaçao.}
{193}{}{ Seu corpo absorveu uma quantia incrivel de radiaçao.}
{194}{}{ Eu nunca vi tais leituras no meu radscanner. Eu acho que
 você esta para morrer. Eu dou a você de duas a tres semanas.}
{195}{}{ Não há muito que eu possa fazer a respeito.}
{196}{}{Eu espero que você tenha uma boa razão pra me perturbar. Meu tempo e extremamente
 valioso.}
{197}{}{Eu estou morrendo aqui! Por favor me ajude!}
{198}{}{Eu lamento perturbar você mas eu preciso de um pouco de assistencia.}
{199}{}{Aggh!}
{200}{}{Eu não acho seu humor engraçado. Por favor saia pra que eu possa retornar ao meu trabalho.}
{201}{}{Hmm. Bem, você parece bem pra mim. Talvez você precise de um pouco de descanso.
 Tente a Crash House na esquina. Boa noite.}
{202}{}{Eu lamento, eu não trato idiotas a noite. Algo sobre luas cheias e loucura
 eu suponho. Tenha uma boa noite.}
{203}{}{Você de novo. Eu espero que você tenha outra boa razão pra me perturbar...}
{204}{}{Invasor! Esta é uma sala privada!}
{205}{}{him!}
{206}{}{her!}
{207}{}{Throw down, açougueiro!}
{208}{}{Espere!}
{209}{}{Ack!}
{210}{}{Não tente conversar pra fugir desta!}
{211}{}{Por que eu deveria?}
{212}{}{Eu não represento perigo pra você!}
{213}{}{Eu estou pondo um fim na sua operaçao aqui e agora!}
{214}{}{Não! Eu não deixarei você acabar com minha operaçao! Gretch, get }
{215}{}{Por que?!}
{216}{}{Eu sei o que você esta fazendo aqui e eu não impedirei você.}
{217}{}{Você e obviamente de longe mais poderoso do que eu sou.}
{218}{}{Isso e verdade. Infelizmente você viu demais. Hmm....}
{219}{}{ terei que lidar com você. Lamento.}
{220}{}{ Você deve provar sua sinceridade. É eu poderia ser capaz de
 obter um pouco de lucro com este negocio.}
{221}{}{O que você quer dizer?}
{222}{}{Sem acordo, de jeito nenhum.}
{223}{}{Certo. Que seja do seu jeito!}
{224}{}{Eu tomarei algo de você. É então nos estaremos quites.}
{225}{}{Certo.}
{226}{}{De jeito nenhum.}
{227}{}{Excelente!}
{228}{}{O Doutor Morbid pega uma ferramente cirurgica e antes que você consiga reagir
 remove um dos seus olhos. É extremamente doloroso.}
{229}{}{Agora, metade do que você acabou e ver e meu de novo.}
{230}{}{VOCE ARRANCOU MEU OLHO FORA! SEU FUDEDOR DE...}
{231}{}{Agora agora. Cuidado com o linguajar.}
{232}{}{O doutor saiu.}
{233}{}{Eu sei sobre você e o Bob da Iguana seu açougueiro sujo.}
{234}{}{O q... o que você poderia possivelmente querer dizer?}
{235}{}{Eu tive uma pequena conversa com seu troll...}
{236}{}{[Ele olha furtivamente de lado a lado] Isso não prova nada. O Gretch
 e um pouco... lento na cabeça. Ninguem escuta ele por aqui. Melhor você
 sair.}
{237}{}{Espere, a gente não pode chegar a um acordo?}
{970}{}{Sou o Doc Morbid, posso ajudar?}
{980}{}{O que é isso?}
{981}{}{Do que você está balbuciando?}
{982}{}{Isso é uma piada? Não faço ideia do que seja isso.}
{1000}{}{Killian|Kilian|Sheriff|Sherrif|Mayor|Darkwater|Darkwaters|Agua}
{1001}{}{Gizmo}
{1002}{}{Junktown|Junk Town|Cidade}
{1003}{}{Shady Sands|SHADY|SANDS}
{1004}{}{The Hub|HUB}
{1005}{}{Water Chip|Waterchip|Chip|Agua}
{1006}{}{Casino|Gizmo's Casino|Gizmo's|Gizmos|Gizmos Casino}
{1007}{}{Store|General Store|Loja}
{1008}{}{Deathclaw}
{1009}{}{Medic|Doc|Doctor|Help|Healing|Hurt|Wounded|Injured|Morbid|Doc Morbid|Medico|Doutor|Ajuda|Cura|Ferido|Machucado}
{1010}{}{Buy|Buying|Sell|Selling|Barter|Trade|Trading|Comprar|Vender|Trocar|Negociar|Comerciar}
{1011}{}{Wasteland|Wastes|Waste|Badland|Badlands|Waste Land|Outside|Ermo|Terra Devastada|Devastada|La fora|Fora}
{1012}{}{Direction|Directions|Whereto|Where to|Direcao|Direcoes|Onde|Para onde|Caminho}
{1013}{}{Fallout|Fall out|nuclear fallout|Radiacao|precipitacao}
{1014}{}{Stealing|Thief|Crime|Criminals|Thieves|Thiev|Roubo|Ladrao|Furto}
{1015}{}{Necropolis|City of the Dead|City of Dead}
{1016}{}{Boneyard|The Boneyard|L.A. Boneyard|LA|Los Angeles|LA Boneyard}
{1017}{}{Mutant|Mutants|Mutante|Mutantes}
{1018}{}{Pitt|Skum Pitt|SkumPitt|Skumpit|Skum|Skum Pit|ScumPit|ScumPitt|Scum}
{1019}{}{Skuls|Skulz|Skulls|Skullz}
{1020}{}{Khan|Khans|Viper|Vipers|Raider|Raiders|Saqueador|Saqueadores}
{1021}{}{Crash|Crash House}
{1100}{}{O Killian é o Prefeito da cidade.}
{1101}{}{O Gizmo comanda o cassino e o ringue de boxe.}
{1102}{}{É um lugar tranquilo, na maior parte do tempo.}
{1103}{}{Nunca ouvi falar.}
{1104}{}{Ah, sim, o Hub. Tenho sócios lá embaixo.}
{1105}{}{Não sei nada sobre isso.}
{1106}{}{O Gizmo comanda. Cuidado com os caça-níqueis, você pode perder muito dinheiro se jogar neles.}
{1107}{}{Ache a Loja Geral se você continuar seguindo pro norte na cidade.}
{1108}{}{Ouço as pessoas comentando, mas eu nunca vi. Dizem que ela vagueia pelo deserto, atacando principalmente à noite.}
{1109}{}{Você está aqui. O que você quer?}
{1110}{}{Killian Darkwater comanda a Loja Geral. Vá lá se quiser negociar.}
{1111}{}{Por que você se importa? Junktown é obviamente o lugar melhor.}
{1112}{}{Não tenho tempo pra te mostrar a cidade. Pergunte a outra pessoa!}
{1113}{}{Só fique debaixo de um teto, tá?}
{1114}{}{Eles te enforcam se te pegarem roubando.}
{1115}{}{Já ouvi falar disso. Supostamente é perigoso pra não-mutantes como nós.}
{1116}{}{É um lugar em algum ponto bem ao sul, até onde eu sei.}
{1117}{}{Criaturas horríveis. Tenho pena delas.}
{1118}{}{Esse é o bar a algumas casas ao norte daqui.}
{1119}{}{São a gangue local. Tenho que remendá-los de volta de vez em quando.}
{1120}{}{Por sorte não temos muitos problemas com eles aqui embaixo. Ouvi dizer que é bem pior lá pro norte.}
{1121}{}{Se você precisa de um lugar pra dormir, dê uma passada na Crash House.}
