{451}{}{A motocicleta não precisa de reparos.}
{452}{}{A chave serve!}
{454}{}{Parece que você precisa de uma chave pra ligar a motocicleta.}
{500}{}{A motocicleta não é grande o bastante pro seu grupo!}
{501}{}{Nem todos nós vamos caber na moto.}
{502}{}{Alguém vai ter que esperar aqui.}
{503}{}{A moto não é grande o bastante pra todos nós.}
{504}{}{Isso realmente não vai dar certo pra gente.}
{505}{}{Tenho um mau pressentimento sobre isto.}
{510}{}{Você carrega a moto com mais energia.}
{511}{}{A moto já está totalmente carregada.}
{512}{}{A moto está funcionando com }
{513}{}{% de energia.}
{520}{}{O regulador da célula de combustível está faltando.}
