{100}{}{O robo não esta funcional. A camada de po nele sugere que ele não
 esteve ativo recentemente.}
{101}{}{O robo foi reparado, mas ainda não esta funcionando.}
{102}{}{O hardware não é um problema, deve ser o software.}
{103}{}{Você não consegue acessar as funções do robo, como se estivessem desativadas.}
{104}{}{Você tinker com os componentes que funcionam mal, mas precisa de mais
 tempo pra fazer o conserto.}
{105}{}{Você reinicia o computador onboard e com sucesso reinicia o robo.
 Você nota que o radio do robo esta quebrado.}
{106}{}{Você passa algum tempo no computador do robo, mas não consegue faze-lo
 se reiniciado.}
{107}{}{Unidade #462 online. Alto-teste. Ajustando os dados locais da unidade.
 Consertados. Reconstruindo o arquivo de memória. Consertado. Erro - tarefa incompleta.}
{108}{}{Rogga.}
{109}{}{Qual e sua tarefa incompleta?}
{110}{}{Bem, apenas faca-o e saia do meu caminho!}
{111}{}{[Clique] Okey-dokey! Reiniciando tarefa.}
{112}{}{Unidade #462 e um modelo de limpeza. Deve terminar a limpeza e
 manutencao deste nível.}
{113}{}{Vá faze-lo!}
{114}{}{O que você deixou pra limpar?}
{115}{}{Sala de Controle dos Vats. [Clique] Fim da lista.}
{116}{}{Ei. Termine sua tarefa.}
{117}{}{Você ganha 1000 pontos de experiência por fazer um pouco de trabalho de limpeza.}
{118}{}{Isso não faz nada de interessante.}
{119}{}{Este robô Mr. Handy está em condição moderada, mas parece plenamente funcional.}
{120}{}{Você improvisa o sistema de rádio do robô; deve estar usável agora.}
{121}{}{Você substitui com sucesso o rádio do robô.}
{122}{}{Os sistemas de interface não respondem aos seus comandos.}
{123}{}{O rádio do robô está quebrado.}
{124}{}{Espera um momento com isso. Que funções você pode executar?}
{125}{}{A Unidade #462 auxilia em tarefas conforme especificado pelos arquivos de memória e programação.}
{126}{}{É, é, pula pras partes interessantes.}
{127}{}{Você poderia ser mais específico?}
{128}{}{[Clique] A Unidade #462 pode realizar substituições de núcleo de combustível de reator nuclear, limpeza de materiais perigosos, descontaminação de radiação e procedimentos básicos de reparo mecânico.}
{129}{}{Mais alguma coisa?}
{130}{}{[Bip!] A Unidade #462 também é equipada com rotinas de automanutenção, mecanismos de autodefesa e um sistema operacional totalmente personalizável.}
{131}{}{Mecanismos de autodefesa?}
{132}{}{Certo, obrigado.}
{133}{}{[Clique] A Unidade #462 está autorizada a empregar força letal em sua própria preservação, conforme permitido por programação prévia.}
{134}{}{Força letal?}
{135}{}{(Um alto-falante ganha vida e uma mensagem gravada de voz masculina começa a tocar. Soa como um anúncio.) "A RobCo está comprometida com a sua segurança e bem-estar. Todas as unidades RobCo Mister Handy são equipadas com sobreposições de segurança de última geração, para evitar quaisquer incidentes infelizes. Fique tranquilo, o Mr. Handy é o melhor investimento em segurança que sua família jamais fará." (O alto-falante se desliga.)}
{136}{}{[Continuar]}
{137}{}{[Clique] Processando... [Clique] Os dados do arquivo de memória indicam que, até a data de fabricação da Unidade #462, de 4.628 eventos de autodefesa registrados iniciados por Unidades similares, apenas 930 resultaram em mortes de civis desarmados.}
{138}{}{É... Isso não soa muito bem.}
{139}{}{Hmm. Eu bem que usaria uma ajuda pra limpar este lugar, se é que você me entende. Você poderia me ajudar?}
{140}{}{O sistema de autodefesa pode ser reprogramado em um sistema de combate?}
{141}{}{Acho que Habitantes de Vault seriam considerados civis, então vou fazer o possível pra não te irritar.}
{142}{}{[Clique] Verificando... [Clique] A programação da Unidade #462 não está atualmente configurada pra permitir tal assistência. Transferências de propriedade e realocações de sistemas de armas não são permitidas sob os protocolos atuais.}
{143}{}{[Tentar hackear a unidade e contornar os protocolos de programação]}
{144}{}{(Leva um tempo, mas você finalmente consegue quebrar os códigos e obter acesso root ao sistema.)}
{145}{}{[Bip!] Unidade #462 online. Autoteste... OK. Ajustando dados de localização da unidade. Corrigido. Reconstruindo arquivo de memória. Corrigido. Limpando lista de tarefas... Concluído. [Clique] Comando?}
{146}{}{Siga-me e mantenha os mecanismos de autodefesa ativos o tempo todo. Ah, e não atire em mim, não sou uma ameaça. Então é melhor você adicionar isso aos protocolos de autodefesa também.}
{147}{}{[Clique] Belezoca! Tarefa recursiva criada. Encerrando entrada.}
{148}{}{(Você tenta obter acesso root ao sistema, mas falha. Luzes começam a piscar na unidade. Oh-oh...}
{149}{}{Alerta! Alerta! Ameaça detectada! [Clique] Iniciando protocolos de autodefesa.}
{150}{}{O robô te ignora e continua sua tarefa.}
{151}{}{Unidade #462, ao seu dispor.}
{152}{}{(Leva um tempo pra você perceber que simplesmente não é esperto o bastante pra quebrar os códigos e obter acesso root ao sistema.)}
{900}{}{A Unidade #462 não pode ser mais reparada no momento.}
{901}{}{A Unidade #462 foi reparada um pouco.}
{902}{}{A Unidade #462 está toda consertada agora.}
{1000}{}{Unidade #462, ao seu dispor.}
{1001}{}{It is }
{1014}{}{Você deveria fazer manutenção em si mesmo agora.}
{1015}{}{Precisamos conversar sobre o que você pode fazer.}
{1020}{}{Vamos falar sobre nossa formação.}
{1030}{}{Certo, obrigado.}
{1040}{}{Siga-me, preciso da sua ajuda de novo.}
{1050}{}{[Pronto]}
{1060}{}{Deixa pra lá.}
{1004}{}{Processando ordens...}
{1005}{}{Calibrando novos parâmetros.}
{1006}{}{Calibrando...}
{1007}{}{Unidade #462, ao seu dispor.}
{1008}{}{Unidade #462, ao seu dispor.}
{1009}{}{[Clique] Confirmado.}
{1010}{}{[Bip] A Unidade #462 pode realizar substituições de núcleo de combustível de reator nuclear, limpeza de materiais perigosos, descontaminação de radiação, procedimentos básicos de reparo mecânico e levar o cachorro pra passear.}
{1011}{}{[Bip] A Unidade #462 está programada pra usar armas de energia e miniguns.}
{1100}{}{[Clique] A Unidade #462 está totalmente reparada e pronta pra ação.}
{1200}{}{[Clique] Status de manutenção: Bom. A Unidade #462 está pronta pra ação.}
{1300}{}{[Clique] Status de manutenção: Danificado. Sugerindo reparos adicionais em breve.}
{1400}{}{[Clique] Status de manutenção: Ruim. Sugerindo reparos adicionais em breve.}
{1500}{}{É melhor a gente ficar junto.}
{1501}{}{[Clique] Confirmado. Unidade #462 permanece em espera.}
{1600}{}{[Clique] Confirmado.}
{1700}{}{[Clique] Confirmado. Iniciando modo de formação de curto alcance.}
{1800}{}{[Clique] Confirmado. Iniciando modo de formação de médio alcance.}
{1900}{}{[Clique] Confirmado. Iniciando modo de formação de longo alcance.}
{2000}{}{Negativo. [Clique] Capacidade de gestão eficaz de grupo excedida. [Clique] Permanecendo em espera.}
{2001}{}{Nova tarefa... [Clique] Confirmado. Unidade #462 retornando da espera.}
{2002}{}{[Clique] Belezoca! Tarefa recursiva criada. Encerrando entrada.}
{2010}{}{Ah é, tanto faz então.}
{3500}{}{[Clique] Status de manutenção: Danificado. Reparos adicionais necessários.}
