{100}{}{Você vê um camponês.}
{101}{}{Obrigado por se livrar das gangues, mas sem o gerador, vamos ter uma vida pior.}
{102}{}{Estou com frio.}
{103}{}{Quero umas luzes.}
{104}{}{Deveríamos te agradecer, eu acho.}
{105}{}{Se você não matar todas as gangues, elas vão se vingar da gente!}
{106}{}{Você começou este banho de sangue, você termina.}
{107}{}{Eu ajudaria, mas estou com este joelho ruim.}
{108}{}{A culpa é toda sua.}
{109}{}{Violência não resolve nada.}
{110}{}{Achei que você fosse um cara bom.}
{111}{}{Só mais um Crypt. Suponho que você vá me machucar agora.}
{112}{}{Não vou causar encrenca.}
{113}{}{Por favor, me deixe em paz.}
{114}{}{Ouvi dizer que você entrou pros Tolos.}
{115}{}{É um Tolo! Opa, não quis dizer desse jeito.}
{116}{}{Não vou causar encrenca nenhuma.}
{117}{}{Por favor, me deixe em paz.}
{118}{}{Prometo rir das suas piadas.}
{119}{}{Estou com fome.}
{120}{}{Pra onde foram todas as pessoas boas?}
{121}{}{O Phil ainda está tendo problema com aquele cachorro?}
{122}{}{Scrapheap vai ser levada pelo vento do deserto, se aquelas gangues conseguirem o que querem.}
{123}{}{É frio à noite sem os aquecedores.}
{124}{}{Esses Brahmin fedem mesmo durante o verão.}
{125}{}{Eletricidade, eletricidade.}
{126}{}{Oi.}
{127}{}{[pronto]}
