{100}{}{Você vê Jerry, um jovem Iniciado.}
{101}{}{Você vê um Iniciado Knight.}
{102}{}{Você vê um Escriba Iniciado.}
{103}{}{Olá! Você deve ser irmão}
{104}{}{, o novo iniciado do lado de fora. Meu nome é Jerry, sou seu
 novo companheiro de quarto. Eu sou um iniciado também! Eu estive estudando muito. Você está
 um cavaleiro iniciante ou escriba?}
{105}{}{Eu não decidi.}
{106}{}{Cavaleiro.}
{107}{}{Escriba.}
{108}{}{Uk.}
{109}{}{Sim, ser um cavaleiro seria ótimo, eles vêem muita ação e
 Consiga construir todas as coisas. Eu ainda não decidi, mas estou inclinado
 em direção a um cavaleiro. Estou te entediando? Algumas pessoas dizem que eu falo muito
 mas eu não acho que eles entendam. Eu só tenho muito a dizer.}
{110}{}{Não, de maneira nenhuma}
{111}{}{Eu tenho que ir. Muito prazer em conhece-lo.}
{112}{}{Sim, os escribas têm uma posição tão criativa. Seria ótimo
 pensar em novas armas, modificar as antigas e manter registros de todos os
 detalhe de cada item na Irmandade. Estou te entediando? Algumas pessoas
 digamos que eu falo muito, mas eu não acho que eles entendam. Eu apenas tenho
 muito a dizer.}
{113}{}{Sim, ainda estou tentando decidir. É tão difícil, ambos são
 muito empolgante. By the way, se você quiser o beliche de cima, deixe-me
 sabe, eu não me importo.}
{114}{}{Obrigado, tchau.}
{115}{}{Você está bem? Talvez você precise ver o médico ou talvez
 você só precisa dormir um pouco. Bem, é melhor eu voltar a estudar. Tchau.}
{116}{}{Ah, a propósito, estou feliz que você seja minha nova colega de quarto. Meu último
 um sempre usava tampões de ouvido, não sei por quê. De qualquer forma, sinta-se livre para
 Deixa o que quiseres aqui, eu não ocupo muito espaço. Você quer
 o beliche de cima? Eu vou mudar se você quiser ... você não ronca, não é? Ah,
 Não importa. Até mais.}
{117}{}{Sim, foi o que eu pensei. Bem, eu estou feliz que você será meu novo
 colega de quarto. Meu último sempre usava tampões de ouvido, não sei por quê. De qualquer forma,
 Sinta-se livre para deixar qualquer coisa que você gosta aqui, eu não ocupar muito espaço.
 Você quer o beliche superior? Eu vou mudar se você quiser ... você não ronca
 você? Não importa. Até mais.}
{118}{}{Apenas deixe-me saber se estou roncando.}
{119}{}{Thomas diz que eu falo muito.}
{120}{}{Talus diz que eu seria um bom Cavaleiro se eu não falasse tanto.}
{121}{}{Prazer em vê-lo novamente, companheiro de quarto!}
{122}{}{Eu não dormi bem na noite passada.}
{123}{}{Oi novamente}
{124}{}{Eu tenho que ir em uma patrulha amanhã.}
{125}{}{Eu serei um Iniciado Sênior em alguns anos.}
{126}{}{Este não é o seu quarto, por favor, deixe.}
{127}{}{Eu acho que você está no quarto de Jerry.}
{128}{}{Boa sorte, você fica com Jerry na boca.}
{129}{}{O que você está fazendo aqui?}
{130}{}{Você é um Iniciado também?}
{131}{}{Visitando?}
{132}{}{Seu quarto é o primeiro da esquerda quando você entra.}
