{100}{}{Você vê um bebado.}
{101}{}{Você vê um fregues.}
{102}{}{Você vê uma dama muito bonita.}
{103}{}{Você vê um homem de aparencia estranha.}
{104}{}{Você vê um jogador.}
{105}{}{Você vê uma mulher, ela parece estar ocupada.}
{106}{}{Você vê uma mulher.}
{107}{}{Você vê um homem.}
{108}{}{Você vê um jogador muito aborrecido.}
{109}{}{Você vê um mercenario.}
{110}{}{Deixe-me com as minhas lamentações.}
{111}{}{Vocer meu mais melhor amigo.}
{112}{}{Por que você esta . . . (hic) aonde eu estou?}
{113}{}{Quem é você?}
{114}{}{Eu conheco você?}
{115}{}{Eu me sinto um pouco queasy.}
{116}{}{As bebidas são por minha conta, eu quero dizer, sua.}
{117}{}{Por que há dois de você?}
{118}{}{Parado em pe amigo!}
{119}{}{Parado em pe garota!}
{120}{}{Desapareca skag!}
{121}{}{Você cair a classe deste joint.}
{122}{}{Vai embora, você vai me dar azar!}
{123}{}{Não quebre minha concentracao.}
{124}{}{Eu ainda derrotarei este maldito jogo!}
{125}{}{Você é um pouco bom nisto?}
{126}{}{Você viu isso? Isso foi impossivel!}
{127}{}{Eu acho que eles estão trapaceando.}
{128}{}{Agora esses são good odds.}
{129}{}{É uma coisa certa.}
{130}{}{O que? Como eu poderia ter perdido?}
{131}{}{Esta mesa esta jinxed!}
{132}{}{Eu estou ocupado.}
{133}{}{Você não consegue ver que eu estou jogando um jogo aqui?}
{134}{}{Aposte ou desapareca.}
{135}{}{Deixe-nos em paz ou eu chamarei os guardas.}
{136}{}{Cuidado, eu sou um amigo próximo do Deputy Fry.}
{137}{}{Você se importa?}
{138}{}{Sem shows!}
{139}{}{Eu não faco grupal.}
{140}{}{Eu estou muito cansada pra outra.}
{141}{}{Você esta sonhando amigo, desapareca!}
{142}{}{Saia!}
{143}{}{O que diabos voe acha que você esta fazendo?}
{144}{}{Tenha modos!}
{145}{}{Eu chamarei os policiais!}
{146}{}{Nem mesmo pense!}
{147}{}{Saia!}
{148}{}{Desapareca!}
{149}{}{O que você esta olhando?}
{150}{}{Você se importa?}
{151}{}{Saia do nosso quarto!}
{152}{}{Saia!}
{153}{}{Você e parte do combo?}
{154}{}{Desapareca pervertido!}
{155}{}{Qual e seu problema?}
{156}{}{Desapareca antes que eu fique zangada.}
{157}{}{Arrume a sua.}
{158}{}{Ela é minha.}
{159}{}{Maldicao!}
{160}{}{Você esta trapaceando?}
{161}{}{Essa deveria ter sido minha.}
{162}{}{Quase!}
{163}{}{Acabei de perder.}
{164}{}{Quais são as regras de novo?}
{165}{}{Eu costumava ser bom nisto.}
{166}{}{Obrigado por nada.}
{167}{}{Eu não acredito!}
{168}{}{Eu tive a intenção de fazer isso.}
{169}{}{Facam suas apostas.}
{170}{}{Mantenha suas mãos longe.}
{171}{}{Vencedor!}
{172}{}{Lamento pessoal, talvez da proxima vez.}
{173}{}{Outro vencedor!}
{174}{}{Tira a mão!}
{175}{}{Seu turno, senhor.}
{176}{}{Lamento, essa é uma aposta invalida.}
{177}{}{Basta.}
{178}{}{Alguém mais?}
