{100}{}{Você vê varias criaturas flutuantes esquisitas...}
{111}{}{Você e de repente atacado por um enxame de mantis!}
{101}{}{Você vê um pequeno enxame de ratos se aproximando rapidamente.}
{102}{}{Você vê um grupo de camponeses sendo atacados por saqueadores!}
{103}{}{Você vê algumas pessoas pescando.}
{104}{}{Há um cadaver grisly próximo que foi parcialmente comido.}
{105}{}{Você topa com algumas pocas de água..}
{106}{}{Com muita sede, você bebe um pouco de água.. Ela não tem um gosto tão bom.}
{107}{}{A água parece altamente radioativa e foul.}
{108}{}{Ahhh..}
{109}{}{Arrgg..}
{110}{}{Yuck!}
