{100}{}{Você entrou numa emboscada dos super mutantes!}
{101}{}{Parece que você entrou numa guerra de gangues!}
{102}{}{Um grupo de saqueadores hostis bursts forth!}
{103}{}{Um grande grupo de ratos vem scurrying down pelas ruas!}
{104}{}{Um grupo de membros de gangues bursts forth!}
{105}{}{Você e de repente atacado por ratos!}
{106}{}{Você encontra um grupo de Super Mutantes de aparência ameaçadora.}
