{105}{}{Radscorpions!}
{121}{}{Você vê um viajante solitario a distancia.}
{106}{}{Um radscorpion particularmente furtivo parece estar tentando emboscar você.}
{107}{}{De lugar nenhum um radscorpion de repente ataca!}
{108}{}{Você tropecou numa familia de Mole Rats.}
{100}{}{Você e quase esmagado por uma grande rocha numa avalanche.}
{102}{}{A rocha deslocada traz com ela os restos de um viajante há muito morto.}
{136}{}{Você tropeca num grupo de radscorpions hostis.}
{120}{}{Você acha varios ratos scavenging por aqui.}
{122}{}{O chao a frente esta littered com escombros e corpos. Parece uma velha zona de batalha.}
{128}{}{Você vê um radscorpion solitario, skittering about.}
{135}{}{Você encontra os ossos de algum viajante morto há muito tempo.}
{129}{}{Tremendos Mole rats estão nosing por aqui.}
{130}{}{Você acha varios ratos scavenging por aqui.}
{134}{}{Você vê varios ratos correndo em direção a você.}
{114}{}{Você esta viajando atraves de penhascos sheer e terreno rugged.}
{115}{}{Felizmente, suas técnicas de escalada estão aptas para a tarefa.}
{116}{}{Você acha uma caverna com uma pequena fonte e consegue obter sua primeira boa noite de sono há muito tempo.}
{117}{}{Você cai de um ledge, aterrissando em varias pedras afiadas.}
{118}{}{Você cai de um cliffside no chao rochoso abaixo.}
{109}{}{Você e quase esmagado por uma grande rocha numa avalanche.}
{123}{}{Você e quase esmagado por uma grande rocha numa avalanche.}
{132}{}{Você cai sobre um terreno duro e torce um tornozela, dolorosamente.}
{133}{}{Você cai sobre um terreno duro e scrape um pouco de carne.}
{101}{}{Você escapa com nenhum dano.}
{110}{}{Você escapa com nenhum dano.}
{124}{}{Você escapa com nenhum dano.}
{131}{}{Você quase cai num terreno duro. Eles poderiam usar um pouco de gerenciamento do ambiente aqui.}
{104}{}{Algumas lascas de rocha rasgam sua face e mãos, mas você escapa com dano minimo.}
{113}{}{Algumas lascas de rocha rasgam sua face e mãos, mas você
 escapa com dano minimo.}
{127}{}{Algumas lascas de rocha rasgam sua face e mãos, mas você escapa com dano minimo.}
{147}{}{Sua tentativa patética de escapar das rochas é um fracasso colossal. Todos os seus membros são esmagados e espancados num jorro espetacular de sangue. Incrivelmente, você sobrevive.}
{148}{}{Você não consegue achar nenhum apoio durante a queda, e aterrissa com um baita estrondo, esmagando as duas pernas feito baratas-radioativas.}
{138}{}{Você sustem }
{139}{}{ pontos de dano e uma perna esquerda aleijada.}
{140}{}{ pontos de dano e uma perna direita aleijada.}
{141}{}{ pontos de dano.}
{144}{}{ pontos de dano e um braço esquerdo aleijado.}
{145}{}{ pontos de dano e um braço direito aleijado.}
{146}{}{ pontos de dano e dois membros aleijados.}
{103}{}{Sua perna e danificada criticamente por rochas que caem.}
{112}{}{Sua perna e danificada criticamente por rochas que caem.}
{126}{}{Sua perna e danificada criticamente por rochas que caem.}
{125}{}{Você escapa com nenhum dano. A rocha deslocada revela um deposito de ouro.}
{111}{}{Você escapa com nenhum dano. A rocha deslocada revela um deposito
 de ouro.}
{142}{}{Você reabastece seu cantil vazio na nascente.}
{143}{}{Você reabastece seus cantis vazios na nascente.}
{119}{}{Você tropeca num grande grupo de radscorpions.}
{200}{}{Você tropeça em um bando de geckos.}
{201}{}{Você tropeça em um bando de geckos hostis.}
{202}{}{Você encontra vários geckos vasculhando por aqui.}
{203}{}{Você se vê no meio de plantas de esporos!}
{204}{}{Como você usou uma corda ao escalar, consegue evitar ferimentos piores.}
