{100}{}{Este parece um terminal de controle de robôs.}
{101}{}{Não há resposta.}
{102}{}{Reprogramação completa. Inicializando subsistemas de comunicação por voz.
 Inicializando subsistema de personalidade. [Click!] Como este terminal pode ser útil?}
{103}{}{Hum.}
{104}{}{Quem ou o que é você?}
{105}{}{Qual é a sua função?}
{106}{}{Exibir lista de programas.}
{107}{}{Erro na entrada de dados. Comando não em conjunto. Por favor reinicie.}
{108}{}{Hum.}
{109}{}{La-lá.}
{110}{}{Brai!}
{111}{}{Niggle!}
{112}{}{Fim do subsistema de comunicação. Fim do processo.}
{113}{}{Este terminal é uma Inteligência Artificial. Este terminal
 faz parte de uma rede matriz WLAN para otimizar as operações de 
 unidades remotas.}
{114}{}{Obrigado. Uh, fim da entrada de dados.}
{115}{}{Quais são as unidades remotas que você controla?}
{116}{}{Quais programas estão em execução?}
{117}{}{Este terminal é responsável pela operação de todos os robôs industriais 
 da General Atomics International nesta instalação.}
{118}{}{Por favor seja mais específico.}
{119}{}{Quais programas estão em execução?}
{120}{}{O modelo dos robôs industriais é comumente referido como 
 'Robobrain'. [Click!] A General Atomics International possui os 
 melhores modelos de robôs industriais do mundo. 
 Compre dois ou mais robôs GAI e economize! Oferta especial nos modelos 'Mr. Handy'! 
 [Click!] Aplicativo de publicidade encerrado.}
{121}{}{Quais programas estão em execução?}
{122}{}{As aplicações atuais são: Manutenção de Instalações v2.1, Movimento v4.8b, 
 Reparo v0.8a, Controle de Pragas v1.4, Hearts v1.0 e Sensores '76.}
{123}{}{Encerrar a Movimentação.}
{124}{}{Encerrar o Sensores.}
{125}{}{Encerrar o Controle de Pestes.}
{126}{}{Encerrar os Corações.}
{127}{}{Obrigado. Fim da entrada de dados.}
{128}{}{Tentativa de encerramento. [Click!] Erro de sistema. Falha ao encerrar a 
 aplicação. Direitos de exclusão não disponíveis.}
{129}{}{Hmm, ajustar os parâmetros da Movimentação.}
{130}{}{Ajustar os parâmetros dos Sensores.}
{131}{}{Modificar o Controle de Pestes.}
{132}{}{Jogar Corações.}
{133}{}{Obrigado. Fim da entrada de dados.}
{134}{}{Aplicação atual: Movimento v4.8b. Configuração atual: 
 [maximum/half rate/minimum]. Alterar para: máximo, meia taxa ou mínimo.}
{135}{}{Máximo de movimentação.}
{136}{}{Taxa de movimentação pela metade.}
{137}{}{Mínimo de movimentação.}
{138}{}{Aplicação atual: Sensores '76. Configuração atual: 
[full/minimum]. Alterar para: completo ou mínimo.}
{139}{}{Sensores completos.}
{140}{}{Mínimo de sensores.}
{141}{}{Aplicação atual: Controle de Pragas v1.4. Configuração atual: [Click!] não autorizado.
 Alterar para: [Click!] todos, nenhum, pequeno, grande ou não autorizado.}
{142}{}{Todas as pestes.}
{143}{}{Sem pestes.}
{144}{}{Pequenas pestes vivas.}
{145}{}{Grandes pestes vivas.}
{146}{}{Pestes não autorizadas.}
{147}{}{Aplicativo Corações em execução. Usuário Vence. [Click!] Obrigado a você pelo jogo.}
{148}{}{Aplicativo Corações em execução. Este terminal vence. [Click!] Obrigado a você 
pelo jogo.}
{149}{}{Parâmetro do programa alterado. As aplicações atuais são: 
 Manutenção de Instalações v2.1, Movimento v4.8b, Reparo v0.8a, 
 Controle de Pragas v1.4, Corações v1.0 e Sensores '76.}
{150}{}{Ajustar os parâmetros da Movimentação.}
{151}{}{Ajustar os parâmetros dos Sensores.}
{152}{}{Modificar o Controle de Pestes.}
{153}{}{Jogar Corações.}
{154}{}{Obrigado. Fim da entrada de dados.}
{155}{}{As aplicações atuais são: Manutenção de Instalações v2.1, Movimento v4.8b, 
 Reparo v0.8a, Controle de Pragas v1.4, Hearts v1.0 e Sensores '76.}
{156}{}{Hmm, ajustar os parâmetros da Movimentação.}
{157}{}{Ajustar os parâmetros dos Sensores.}
{158}{}{Modificar o Controle de Pestes.}
{159}{}{Jogar Corações.}
{160}{}{Obrigado. Fim da entrada de dados.}
{161}{}{Inicializando subsistemas de comunicação por voz. Inicializando 
 subsistemas de personalidade. [Click!] Como este terminal pode ser útil?}
{162}{}{Hhumm.}
{163}{}{Me mostre seus programas.}
{164}{}{Desligar todos os campos de força.}
{165}{}{Você sabe o que este local é?}
{166}{}{Iniciar desligamento de emergência.}
{167}{}{Fim da entrada de dados.}
{168}{}{Este terminal não pode realizar essa função. Pedido negado.}
{169}{}{Me mostre seus programas.}
{170}{}{Você sabe o que este local é?}
{171}{}{Iniciar desligamento de emergência.}
{172}{}{Fim da entrada de dados.}
{173}{}{Esta é o -- secreto [click!] [click!]}
{174}{}{Abortar pedido. Mostrar programas.}
{175}{}{Sobrescrever, continuar o pedido.}
{176}{}{[Click!] Esta é a instalação de controle de produção da VEF. 
 Este terminal está online desde 2074. Processo final pré-produção em 2075. 
 Atualmente, está em construção final e tem previsão de abrir em 2078. [Click!]}
{177}{}{Você sabe o que VEF é?}
{178}{}{Você sabe qual data é?}
{179}{}{VEF é o Vírus Evolutivo Forçado [click!], um produto dos Laboratórios 
 Livermore/Broansoun. Ele foi projetado para aumentar a complexidade genética 
 de uma série de DNA/RNA em um período de tempo mais curto.}
{180}{}{Mostrar programas.}
{181}{}{Fim da entrada de dados.}
{182}{}{Afirmativo. A data do terminal é 2 de Fevereiro de 2077.}
{183}{}{Mostrar programas.}
{184}{}{Fim da entrada de dados.}
{185}{}{Essa data está incorreta. Por favor recalibrar.}
{186}{}{Corrigindo. [Click!] Erro. Tentando autodiagnóstico.
[Click! CLICK!] ERRO! ERRO FATAL DO SISTEMA. SISTEMA CORROMPIDO,
 TENTANDO RECOMPILAÇÃO. [Long pause.]}
{187}{}{Terminal?}
{188}{}{[click] Erro na recompilação . . . [click]}
{189}{}{Não consigo processar o pedido. Encerrando diálogo.}
{190}{}{Confirmar codescram de emergência.}
{191}{}{Confirmado.}
{192}{}{Encerrar o procedimento de desligamento.}
{193}{}{[Click!]}
{194}{}{Processando o pedido. Encerrando o diálogo.}
{195}{}{Este computador não é compatível com o seu rádio. Ele utiliza uma banda 
 de alta frequência especial apenas para uso robótico.}
{196}{}{Você pressiona alguns botões, mas o computador parece estar danificado. 
 Dará algum trabalho para operá-lo.}
{197}{}{O computador não está fisicamente danificado, mas parece ter dados corrompidos.}
