{100}{}{Você vê Rock.}
{101}{}{Você vê um homem.}
{102}{}{É melhor você pensar em guardar essa arma, filho. Os Crypts não gostam quando as pessoas exibem armamento desse jeito.}
{103}{}{Ah, é? Vou ter uma conversinha com eles sobre isso. Onde eles estão?}
{104}{}{Ah, tá. Onde eu consigo uma bebida?}
{105}{}{Quem são os Crypts?}
{106}{}{Você parece precisar de uma bebida gelada.}
{107}{}{[pronto]}
{108}{}{É, vá ao prédio grande logo na entrada da cidade e diga que o Rock te mandou.}
{109}{}{Tá.}
{110}{}{Os Crypts? São a maior e mais perigosa turma daqui. Não mexa com eles, se você quer deixar Scrapheap em uma peça só.}
{111}{}{Onde eles estão?}
{112}{}{Estão no prédio grande logo depois do portão. Você está procurando um trabalho fixo? Algum lugar pra usar essa sua arma?}
{113}{}{Não.}
{114}{}{É, estou sim.}
{115}{}{Então sugiro que você dê meia-volta e vá embora. Scrapheap não é lugar pra quem não está com os Crypts. Se você quer entrar, pode - mas é a sua vida.}
{116}{}{Tá.}
{117}{}{Ótimo. Diga a eles que o Rock te mandou, lá na casa grande.}
{118}{}{Tá.}
{119}{}{Fico feliz em saber que você está do lado bom em Scrapheap. Bem-vindo à gangue.}
{120}{}{Obrigado.}
{121}{}{Você cometeu um erro. Um erro terrível, terrível.}
{122}{}{Bem-vindo a Scrapheap, filho. Não seja um tolo, e você vai se dar bem.}
{123}{}{Obrigado, que lugar é este?}
{124}{}{Quem manda aqui?}
{125}{}{Scrapheap é o sovaco do deserto. Nenhum lugar melhor pra criar filhos, na minha opinião. [Ri] Este lugar faz Junktown parecer uma cidade viva dos antigos.}
{126}{}{Obrigado.}
{127}{}{Bom, tem uma comuna, comandada pelo Lex. Mas o poder de verdade está sempre por trás do trono. Neste caso, os que você não deve mexer são os Crypts.}
{128}{}{Obrigado.}
{129}{}{Bom, você faz um monte de perguntas. Acho que você deveria seguir seu caminho agora.}
{130}{}{Tá.}
{131}{}{[pronto]}
{132}{}{Os Crypts vão te enterrar!}
{133}{}{Tolos não têm razão pra viver.}
{134}{}{Os Tolos vão perecer.}
{135}{}{Olha quem foi atingido pela vara da feiura.}
{136}{}{É melhor você pensar em guardar essa arma. Os Crypts não gostam quando as pessoas exibem armamento desse jeito.}
{137}{}{Bem-vindo a Scrapheap. Não seja um tolo, e você vai se dar bem.}
