{100}{}{Você vê o Sammael, um dos Scavs de Adytum.}
{101}{}{Você vê um homem grungy com roupas azuis escuras.}
{102}{}{Ei, eu não acredito que nós nos encontramos. Você e?}
{103}{}{Eu sou }
{104}{}{.}
{105}{}{Quem esta perguntando?}
{106}{}{Eruh?}
{107}{}{O prazer e meu. Me chamo Sammael.}
{108}{}{O que você faz aqui?}
{109}{}{Foi bom conversar com você.}
{110}{}{Ninguem especial. Deixa pra lá.}
{111}{}{Eu sou um Scav -- um scavenger. Meu trabalho éprocurar por toda a
 Boneyard por itens uteis e informação. Trabalho perigoso.}
{112}{}{Por que é perigoso?}
{113}{}{Como você evita os deathclaws?}
{114}{}{Você patrulhou quaisquer das outras areas?}
{115}{}{Obrigado, tchau.}
{116}{}{Vejo você por ai. Se você me ver. Ei.}
{117}{}{Bem, você tem os deathclaws lá fora, e então você tem os Reguladores
 de volta aqui em Adytum. Ambos não são os tipos que mais perdoam.}
{118}{}{Como você evita os deathclaws?}
{119}{}{Você patrulhou quaisquer das outras areas?}
{120}{}{Obrigado, tchau.}
{121}{}{Nós só trabalhamos a noite, e nós somos bons no que nos fazemos. Mas eu
 admito que nem todo mundo sempre volta. Eu enviei um cara na ultima semana pra
 procurar por algumas partes pro Miles, e nós não ouvimos falar dele desde
 então. A ultima transmissiao que eu obtive dele era que ele achou as
 partes e estava no caminho de volta dele.}
{122}{}{Eu fiz um pouco de patrulhamento. De quem você quer saber a respeito?}
{123}{}{Dos Blades.}
{124}{}{Dos Deathclaws.}
{125}{}{Dos Gun Runners.}
{126}{}{Dos Followers of the Apocalypse.}
{127}{}{Das Crianças da Catedral.}
{128}{}{De ninguém, obrigado.}
{129}{}{Os Blades são uma vista bastante lamentavel pra um grupo de pessoas.
 Apesar disso eles vem aqui, e alguns deles terminam aqui em Adytum se eles
 concordam em fazer o que os Reguladores oferecem a eles pra fazer.}
{130}{}{Bem, se você não viu eles antes. Eles são malvados como o inferno, e
 não gostam de nada mais do que arrancar fora o coração de um pobre Scav.}
{131}{}{Eu ouvi que há um ninho deles em algum lugar a leste do Blades,
 mas eu mesmo não vi.}
{132}{}{Os Gun Runners se mudaram pra uma grande fabrica a nordeste há não
 muito tempo atras. Não posso dizer muito a você por que eles tem um fosso
 cheio de lixo radioativoe, e você tem que passar pelos deathclaws
 pra chegar lá.}
{133}{}{Os Seguidores pregam a paz é a tolerancia. Ideia bacana, mas não
 e pratica. Eles vivem numa grande biblioteca a noroeste de nos.}
{134}{}{As Crianças da Catedral estão baseadas numa grande igreja
 ao sul daqui. Há algumas coisas estranhas acontecendo lá. Eu vi
 criaturas que não podem ser humanas entrando e saindo
 de lá.}
{135}{}{E se as estorias estão corretas, a igreja esta construida sobre
 uma vault antiga, da qual os predecessores de Adytum viveram.}
{136}{}{Eia. Nós vemos um ao outro mais uma vez. O que é que há?}
{137}{}{De novo, qual era seu trabalho?}
{138}{}{Nada, obrigado.}
{139}{}{Ah, eu entendo. Certo. Tchau!}
{140}{}{O Miles disse que eu deveria falar com você sobre peças pras fazendas hidropônicas dele. Você sabe algo sobre isso?}
{141}{}{Ah, sim. Na verdade, sei. Semana passada mandei um cara pro norte procurar as peças pro Miles, mas não tivemos notícias dele desde então. A última transmissão que recebi foi que ele tinha achado as peças e estava voltando. Ainda não tive tempo de verificar pessoalmente, e não quero perder mais uma pessoa pro que quer que tenha causado o desaparecimento dele.}
{142}{}{Que azar, sinto muito. Obrigado pela informação. Tchau.}
{143}{}{Se eu conseguir alguma informação sobre o seu cara, tem algum tipo de recompensa?}
{144}{}{Ótimo, obrigado. Vou procurar as peças naquela área. Aviso se eu encontrar seu amigo desaparecido.}
{145}{}{Quando quiser. Falou.}
{146}{}{Você faria isso? Seria ótimo. Como eu disse, as coisas andam corridas por aqui e não podemos nos dar ao luxo de perder mais gente.}
{147}{}{[ri] Não, na verdade não. Se eu tivesse as tampinhas pra isso, já teria contratado alguém pra localizá-lo. [pensa por um instante] Mas gosto do seu espírito. Vou te dizer uma coisa: se você o encontrar, vejo o que posso fazer por você.}
{148}{}{Boa notícia, achei seu cara. Má notícia, ele está bem morto.}
{149}{}{Sinto muito ter que te dizer isso, mas parece que seu amigo foi morto pelas Deathclaws no armazém.}
{150}{}{Droga! [suspira] Já imaginava. Obrigado.}
{151}{}{Ah, é mesmo. Aqui está sua recompensa. [Ele te entrega o que parece uma motosserra em miniatura, de mão] Havia uma gangue aqui que usava essas. Fique à vontade pra matar alguns daqueles desgraçados das Deathclaws com ela. Até mais.}
{152}{}{Aqui, pegue isto pelo trabalho, é o mínimo que posso fazer. [Ele te entrega 200 tampinhas]}
