{100}{}{A porta de seguranca esta trancada.}
{101}{}{A porta de seguranca não esta trancada.}
{102}{}{Você consegue destrancar a porta de seguranca.}
{103}{}{Você falha em destrancar a porta de seguranca.}
{104}{}{Você consegue engatilhar o alerta passivo na porta, clamping down a
 tranca eletronica. Bom trabalho, chromo.}
{105}{}{Você ganha 25 pontos de experiência por abrir a tranca.}
{106}{}{ de experiência por arrombar a fechadura.}
{200}{}{ consegue destrancar a porta de segurança.}
{201}{}{ não consegue destrancar a porta de segurança.}
{202}{}{ acaba acionando o alerta passivo da porta, travando a fechadura eletrônica.}
