{100}{}{Você vê um Paladino solitário. Ele parece ao mesmo tempo assustado e irritado.}
{101}{}{Pare aí mesmo, estranho! Identifique-se!}
{102}{}{Me }
{103}{}{.}
{104}{}{I'm }
{105}{}{. O que aconteceu com este lugar?}
{106}{}{Meu nome não é importante.}
{107}{}{Cuidado, }
{108}{}{, você pode se machucar. Um exército de mutantes maus veio a este lugar e fez um grande bum. Viu?}
{109}{}{Aham.}
{110}{}{Viu. Então é melhor você achar outro lugar pra ir. Não é seguro aqui.}
{111}{}{Eu ir.}
{112}{}{Mutantes. Foi um exército realmente grande. Eles vieram, mataram todos, levaram tudo o que puderam e explodiram este lugar.}
{113}{}{E como você conseguiu sobreviver a tudo isso?}
{114}{}{Eu estava voltando de uma patrulha de longo alcance. Quando cheguei, a batalha já tinha acabado. Não pude fazer nada. Então me escondi e os observei.}
{115}{}{Você quer dizer que estava assustado demais pra fazer algo?}
{116}{}{Ninguém mais sobreviveu a esta invasão?}
{117}{}{Olha, posso não ser o homem mais corajoso da Brotherhood, mas também não sou um idiota. Não havia realmente nada que eu pudesse fazer.}
{118}{}{Covarde. Agora fique e guarde um monte de ruínas. É melhor eu ir matar alguns desses seus mutantes.}
{119}{}{Desculpe. Mais alguém sobreviveu a este massacre?}
{120}{}{Vários grupos de reconhecimento, alguns paladinos em patrulha... pouco demais pra fazer algo. A Brotherhood of Steel está praticamente morta. Vou ficar aqui por enquanto, tentar reunir o máximo de sobreviventes que puder e contar a eles o que aconteceu aqui. Depois... na verdade, não sei o que vem depois. Nunca tive a chance nem de pensar nisso.}
{121}{}{Entendo. Continue o bom trabalho, Paladino, preciso ir.}
{122}{}{Adeus, }
{123}{}{. Se você encontrar sobreviventes da Brotherhood nas suas viagens, conte a eles o que aconteceu aqui.}
{124}{}{Pare aí mesmo... Ah, é você, }
{125}{}{.}
{126}{}{Aham.}
{127}{}{Sim, sou eu. O que aconteceu aqui?}
{130}{}{Adeus, }
{131}{}{. Se você encontrar alguns dos nossos Irmãos, conte a eles o que aconteceu aqui.}
{132}{}{Claro. Preciso mesmo ir agora.}
{133}{}{Então é melhor você ir. Não tenho nada a dizer pra você.}
{150}{}{O Paladino te ignora. Parece estar mergulhado nos próprios pensamentos.}
