{100}{}{Você nota uma camera de seguranca a qual parece estar ativa.}
{101}{}{Você nota armas escondidas rastrando seu movimento.}
{102}{}{Portas de armas escondidas abrem fogo! Twisting and weaving,
 você consegue evitar ferimentos!}
{103}{}{Portas de armas escondidas abrem fogo! Twisting and evading,
 você e grazed by gunfire.}
{104}{}{Você sofre }
{105}{}{ de dano.}
{106}{}{Portas de armas escondidas abrem fogo! Startled, you trip e
 cai, sofrendo apenas ferimentos leves.}
{107}{}{Você sofre }
{108}{}{ de dano.}
{109}{}{Portas de armas escondidas abrem fogo! Você foi atingido!}
{110}{}{Você sofre }
{111}{}{ de dano.}
