{100}{}{Você ganha 400 pontos de experiência por trazer a Tandi de volta.}
{101}{}{Ao sul, você vê uma parede adobe rodeando um vila de aparencia
 pacifica.}
{102}{}{Um pequeno barracao e tudo que resta desta area. Felizmente, seus
 registros indicam uma entrada secundaria para a vault 15 ali.}
{103}{}{Você vê uma pequena construcao, com uma serie de tendas proximas.
 Os habitantes parecem sujos e maus.}
{104}{}{Você chega a uma cidade de tamanho medio. Uma parede de carros sucateados
 bloqueiam a entrada fácil. Uma fumaca hazy descansa baixo sobre a cidade.}
{105}{}{Ao sul você vê uma cidade grande. Fazendas Outlying rodeiam a cidade.
 Há muita vida neste oasis do deserto.}
{106}{}{Você se aproxima de uma cidade sombria e quebrada. Pouca vida pode ser
 vista. Um fedor de morte rodeia a area.}
{107}{}{Uma pequena construcao rodeada por uma cerca chainlink esta ao norte.
 Guardas ameacadores com armadura pesada patrulham a area.}
{108}{}{Uma grande cratera sprawls ao norte.}
{109}{}{Guardas mutantes podem ser vistos a nordeste na frente de um local
 fortificado construido no lado da montanha.}
{110}{}{Uma grande construcao ornamentada se ergue ao ceu. Uma multidao de pessoas
 caminham sem direção diante dele.}
{111}{}{Você consegue ver um armazem ao norte, com um fosso de gosma brilhante ao redor dela.}
{112}{}{Uma grande fabrica fortificada, com paredes pintadas com grafite e portas
 para armas ameacadores looms a frente.}
{113}{}{Os sinais de atividade da gangues são evidentes no clube noturno parcialmente
 reconstruido e minusculos postos avancados aqui.}
{114}{}{No coração da cidade, uma grande biblioteca, fortificada e restaurada, se ergue
 com presença proibitiva ainda graciosa. Você sente uma sensacao de paz.}
{115}{}{Uma vila cercada, patrulhada por guardas, espera defiantly ao sul.}
{116}{}{Você vê uma pegada gigante no chao. Você procura mas não acha outras
 trilhas na area.}
{117}{}{Marcas de Scorch e cinzas cobrem a area.}
{118}{}{Esta area parece que foi atingida por uma bomba de fogo de alta pressao.}
{119}{}{Você vê o acampamento de um bando itinerante de saqueadores. Parece que você veio ao lugar errado na hora errada.}
{150}{}{Diante de você jaz uma cidade silenciosa, cheia de cadáveres e carnificina. Algo horrível aconteceu aqui.}
{155}{}{Uma estrutura cercada por uma cerca de arame fica ao norte. Parece ter sido danificada por uma explosão. O fedor de morte aqui é quase insuportável.}
{151}{}{Esta cidade está silenciosa e sinistra, repleta de corpos. Algo terrível aconteceu aqui...}
{152}{}{O fedor de morte aqui é quase insuportável. Super Mutantes patrulham a área.}
{153}{}{Você chega ao seu destino só pra encontrar morte e o vento do deserto.}
{154}{}{Você vê a cena de um massacre. Parece não haver sobreviventes, embora você consiga ouvir o leve som de movimento.}
{200}{}{Você ouve alguns sons vindos de dentro das cavernas.}
{201}{}{Você entra numa caverna escura. Há fezes de rato por toda parte.}
{202}{}{Você ouve alguns sons vindos de dentro da mina.}
