{100}{}{Você vê Sinthia, a sedutora gata a venda.}
{101}{}{Você vê uma mulher pouty, shapely.}
{102}{}{Ei querido, como você esta?}
{103}{}{Certo. Tchau.}
{104}{}{Bem, mas eu poderia estar melhor.}
{105}{}{Ãhh.}
{106}{}{Ah, gato, Eu entendo. Você tem que correr pra casa pra mamae.
 Bem, volte aqui quando você precisar de um pouco de amor!}
{107}{}{Sim, docinho, o mesmo pra você.}
{108}{}{Você achara o que quer ou quem quer que seja que você esta procurando,
 docinho, e isso fara todos vocês melhores, eu tenho certeza.}
{109}{}{Talvez eu possa ajudar você com isso.}
{110}{}{Talvez você possa. Quanto você cobra?}
{111}{}{Eu não deixaria meu cachorro tocar você.}
{112}{}{Ah, gato, se você tem que perguntar . . . mais do que você pode pagar.
 Talvez da proxima vez, docinho. Vejo você por ai.}
{113}{}{Ah, docinho, isso e apenas simplesmente nojento.}
{114}{}{Ah, Deus, por favor me ajude.}
{115}{}{Por favor não deixe ele me matar.}
{116}{}{Eu sou muito jovem para morrer.}
{117}{}{Ah, Deus, Eu sou muito bonita pra morrer.}
{118}{}{Obrigado a você pelo que você fez. Ninguem nunca tomou conta de mim
 assim antes.}
{119}{}{Eu posso realmente tomar conta de você mais tarde.}
{120}{}{De nada.}
{121}{}{Unh.}
{122}{}{Obrigado de novo.}
{123}{}{Isso e tudo no que você consegue pensar? Puxa. Algumas pessoas.}
{124}{}{Eu quero dizer, meu chefe nem ao menos enviou alguns dos seus capangas
 pra ajudar. Você pensaria que por todo o dinheiro que eu faco para aquele
 perdedor que ele pelo menos viveria pra cumprir a parte dele na barganha.}
{125}{}{Quem é seu chefe?}
{126}{}{Que barganha?}
{127}{}{Gizmo, claro. Ele comanda todo o pecado nesta cidade. O
 Killian com certeza não me toleraria ou o meu tipo se não fosse
 pelo fato de que eu dou para o Giz um monte de dinheiro, eu
 teria que fazer outras coisas pra ele.}
{128}{}{É, docinho, esses pensamentos simplesmente não fazem muito bem
 ao meu estomago.}
{129}{}{O que mais Gizmo controla?}
{130}{}{Você deveria apenas hang it up e continuar com a sua vida.}
{131}{}{Você me diz. Mas o que mais eu posso fazer? Parece que
 a minha vida foi planejada por alguma outra pessoa. Ah, bem.
 Uma garota tem que viver.}
{132}{}{Mas amor, esta e de graca.}
{133}{}{Obrigada de novo docinho. Nós mulheres devemos ficar juntas.}
{134}{}{Simplesmente cada coisa ruim que uma pessoa pudesse fazer nesta
 cidade. Ele possui o Cassino. Ele manda em mim e em algumas das outras
 garotas, até mesmo algumas garotinhas. Eu ouvi que ele esta tentando
 tomar o bar.}
{135}{}{Você fique longe dele, ok? Me escuta, ele não e
 o tipo de patron que ele faz você pensar que ele é.
 Fique longe.}
{136}{}{O Giz quer tomar conta do Killian, se você entende o que quero dizer.}
{137}{}{Por que docinho? Eu tomo conta dos homens e eles tomam conta de mim
 em returno. O Gizmo recebe 25% e eu supostamente recebo protecao dele.
 Você viu quao bem isso foi, huh?"}
{138}{}{O que mais Gizmo controla?}
{139}{}{Você se sente como fazendo outra visita para a Sinthia.}
{140}{}{Talvez Sinthia gostaria de um pouco de companhia . . .}
{141}{}{Seu merda! Você matou ele! Por que você tinha que mata-lo? Seu bastardo!
 Eu não consigo acreditar que você matou ele. Tudo que ele queria era alguém pra
 conversar. Você não se importa com a vida humana se importa?}
{142}{}{Sua merda! Você matou ele! Por que você tinha que mata-lo? Sua piranha!
 Eu não consigo acreditar que você matou ele. Tudo que ele queria era alguém
 pra conversar. Você não se importa com a vida humana se importa?}
{143}{}{Apenas saia do meu quarto!}
{144}{}{Você matou ele! Eu não consigo acreditar que você matou ele. Todo que ele
 queria era alguém pra conversar . . .}
{145}{}{Ele não esta morto. Ele apenas vai ter uma cabeca machucada quando
 ele acordar.}
{146}{}{Hnnn.}
{147}{}{Sim, que seja. Saia do meu quarto!}
{148}{}{Ah, lamento. Eu pensei que ele estava morto. Eu pensei que você matou ele.
 Ele não é um cara tão ruim depois de tudo. Apenas um pouco solitario.}
{149}{}{Sem problema.}
{150}{}{Você de novo. Com o que eu posso ajudar você desta vez?}
{151}{}{Apenas parando pra ver como você esta indo.}
{152}{}{Eu tenho $40, se você tem dez minutos.}
{153}{}{Eu preciso de um pouco mais de informação sobre o seu chefe.}
{154}{}{Ah, docinho, Eu acho que não. Imagine como as crianças
 seriam.}
{155}{}{Indo bem, gracas a você, docinho.}
{156}{}{O que você quer saber, mas seja rapido, docinho, eu estou
 contando o tempo.}
{157}{}{Quanto guardas ele tem?}
{158}{}{Aonde ele guarda o dinheiro?}
{159}{}{Ele tem quaisquer fraquezas?}
{160}{}{Obrigado boneca, mas eu não preciso saber de nada mais.}
{161}{}{Hmm. Eu sei de oito pessoalmente, se você entende o que quero dizer.
 Eu acho que ele tem outros dez ou mais.}
{162}{}{Dinheiro? Como eu saberia? Ele só toma meu dinheiro, ele não
 me mostra o dele. Eu adivinharia que ele esta no quarto dele, mas
 por tudo que eu sei ele poderia mante-lo aonde o sol não brilha.
 É para o Giz esse e um grande lugar.}
{163}{}{So que ele pensa que ele não tem nada. Bem, isso e ele
 ele e um gordo slob que não consegue se mover por nada. Ele
 tem que ter os guardas dele pra ajuda-lo a se mover por ai.
 Mesmo então eles tem que usar um pequeno triciclo. Ei heh.}
{164}{}{Docinho, você tem um encontro.}
{165}{}{Com certeza docinho, por você.}
{166}{}{Eu mostrarei a você uma boa diversão.}
{167}{}{Docinho, você precisa de um pouco mais de dinheiro. Eu gosto de você e tal,
 mas uma garota tem que viver.}
{168}{}{Eu reservo o direito de recusar a admissao e docinho,
 você não vai chegar em nenhum lugar perto de mim!}
{169}{}{Sinthia esta adormecida.}
{170}{}{Sinthia esta ocupada.}
{171}{}{Sinthia se recusa a falar com você.}
{172}{}{Lamento docinho, eu não transo com aberrações.}
{173}{}{Leve seu dinheiro, sua atitude e seu pequeno prick para algum outro lugar!}
{174}{}{Ah, Deus, alguém me ajude!}
{175}{}{You ganha }
{176}{}{ de experiencia por resgatar a Sinthia com sucesso.}
{177}{}{Os guardas removem o saqueador enquanto ele esta inconsciente.}
