{100}{}{A porta para o Skum Pitt esta trancada.}
{101}{}{Você consegue destrancar a porta.}
{102}{}{Você mexe com a porta, mas falha em destranca-lá.}
{103}{}{Você ouve algo snap. Parece que a tranca esta emperrada.}
{104}{}{A porta não esta trancada.}
{200}{}{ consegue destrancar a porta.}
{201}{}{ mexe na porta, mas não consegue destrancá-la.}
{202}{}{ ouve algo estalar. Parece que a fechadura emperrou.}
