{100}{}{Você vê o Slappy.}
{101}{}{Boogie, Boogie, Boogie.}
{102}{}{É uma aranha bitty, smashin ', smashin'.}
{103}{}{Vamos jogar a Guerra Termo-Nuclear Global.}
{104}{}{Onde está meu blankie!?!}
{105}{}{Da ... Da ... Da ...}
{106}{}{A Lua está lá fora}
{107}{}{Gimme 'the Sugar Baby.}
{108}{}{Oooh, bonita, coisa bonita. Por que a lua?}
{109}{}{uh, eu conversei com o Harold. O Deathclaw parece muito desagradável. O que você pode me falar sobre isso?}
{110}{}{Beth me disse para falar sobre a Deathclaw.}
{111}{}{O que você faz por aqui?}
{112}{}{Qual é o seu problema?}
{113}{}{Lua Grande, eu gosto da Lua!}
{114}{}{Todo brilhante, é todo brilhante, o brilhante desce, e então estamos condenados.}
{115}{}{Ahh.}
{116}{}{Deathclaw, Deathclaw, Dah Dah Deathclaw.}
{117}{}{Venha, o que você sabe sobre a Deathclaw?}
{118}{}{Qual é o seu problema?}
{119}{}{Não me faça tirar isso de você!}
{120}{}{Faça, eu, faça, então você faz, então todos nós fazemos.}
{121}{}{Não realmente, o que você faz?}
{122}{}{Você é um maluco.}
{123}{}{Problemas são como tigelas de sopa, largas e rasas.}
{124}{}{Isso é mais parecido com sua mente.}
{125}{}{Deathclaw assustador, realmente assustador. Parece bacana embora. Quero ver?}
{126}{}{Você pode me levar para a Deathclaw?}
{127}{}{Inferno não!}
{128}{}{Yeah, Deathclaw, Deathclaw, indo ver a Deathclaw.}
{129}{}{Apenas cale a boca e me leve lá.}
{130}{}{Ah, deixa pra lá. Você cuida agora.}
{131}{}{Eu faço isso, então eu faço isso. Você vê Harold? Harold é divertido, seu cabelo cai, cai ao vento. Ali
 vai ... vento, vento.}
{132}{}{Tanto faz.}
{133}{}{Libra e Libra e Libra e Libra.}
{134}{}{Por que o vento está? Por que porque porque porque?}
{135}{}{Beth, Beth, sho sha Beth. Como Harold, você fala com Harold. Harold conta sua história. Slappy help then.}
{136}{}{OK, vou falar com o Harold primeiro}
{150}{}{Você ganha }
{151}{}{ de experiência por descobrir sobre a Deathclaw.}
{2000}{}{Ohhh! Não. Não não não não. Eu *não* vou *até* a Deathclaw!}
{2010}{}{Só cala a boca e me mostra no meu Pip-Boy onde ela fica.}
{2100}{}{Ahh. Mostrar! Aqui... Aqui... Aqui...}
{2110}{}{[Mais]}
{2200}{}{[Leva um tempo pra decifrar as indicações do Slappy, mas no fim você consegue localizá-la na cordilheira a oeste do Hub]}
{1000}{}{DEATHCLAW|DEATH|CLAW|DEATH CLAW|DEATH CLAWS|DEATHCLAWS|CLAWS|MONSTER|MONSTRO}
{1001}{}{SLAPPY}
{1100}{}{É, Deathclaw, Deathclaw.}
{1101}{}{Me chamam de Slappy! ... Slappy, Slap-py!}
