{100}{}{Você vê uma placa elevada. Parece ser parte de uma armadilha.}
{101}{}{ vê uma placa elevada. Parece ser parte de uma armadilha.}
{102}{}{Você vê uma placa elevada.}
{103}{}{ vê uma placa elevada.}
{104}{}{Você aciona a armadilha e por pouco desvia do projétil disparado da parede.}
{105}{}{ aciona a armadilha e por pouco desvia do projétil disparado da parede.}
{106}{}{Você vê uma placa elevada que parece inofensiva.}
