{100}{}{Você vê um homem alegre com corte de cabelo rente.}
{101}{}{Você vê o comerciante da cidade, Tine.}
{102}{}{Nós não temos muitos estranhos por aqui. O que você quer?}
{103}{}{Ola, estranho! O que eu posso fazer por você hoje?}
{104}{}{Meu nome e }
{105}{}{.}
{106}{}{Eu posso perguntar a você sobre os mercadores do Hub?}
{107}{}{Eu gostaria de fazer alguns negócios.}
{108}{}{Qual é a sua opinião sobre Adytum?}
{109}{}{Nenhuma.}
{110}{}{Sim, eu negocío com eles.}
{111}{}{Eu faco algum comercio com eles de tempos em tempos. Na maior parte
 eu vendo balas em troca de comida.}
{112}{}{Eu só o Tine. Você tem algum negocio pra conduzir?}
{113}{}{Prazer em encontrar você. Eu sou o Tine.}
{114}{}{Otimo fazer negocio com você. Venha de novo.}
{115}{}{Que seja.}
{116}{}{Matenha contato!}
{117}{}{O que?}
{118}{}{Ola de novo! Com o que eu posso ajudar você?}
{119}{}{É uma boa cidade. Poderia ser um pouco mais feliz se os Reguladors não mantivessem
 tal dominio forte sobre as coisas. Mas ei, esse e o estilo deles.}
{120}{}{Não é uma cidadezinha ruim. Zimmerman e um homem justo, ms talvez não o cara mais
 brilhante. É claro, nos temos o Miles, provavelmente o unico homem em cem milhas que
 sabe alguma coisa de ciencia.}
