{100}{}{Você vê um computador da Brotherhood altamente avancado.}
{101}{}{É negado a você o acesso a este terminal.}
{102}{}{A licao termina em seis horas. Você se sente exausto.}
{103}{}{Você já absorveu tanto quanto você consegue.}
{200}{}{Você vê um computador. Você vê alguns pedacos que poderiam ser carne humana.}
{201}{}{Você mexe com o computador por um momento, mas não consegue passar do
 sistema de seguranca.}
{202}{}{Este computador esta funcionando perfeitamente.}
{203}{}{Você acha um arquivo de dados interessante sobre uma base secreta a noroeste.}
{204}{}{Você ganha }
{205}{}{ pontos de experiência por hackear este computador.}
