{100}{}{Você vê um dos guardas de Shady Sands.}
{101}{}{Ei, eu acho que é melhor você sair.
 Nós não queremos seu tipo aqui.}
{102}{}{Eu não consigo acreditar que Tandi desapareceu. Eu espero que você esteja
 indo acha-lá. Realmente machucaria o Aradesh se algo ruim acontecesse a ela.}
{103}{}{Obrigado por trazer a Tandi de volta. É um bom sinal para o futuro,
 você não acha?}
{104}{}{É uma pena o que aconteceu com Tandi. Eu espero que Aradesh esteja ok.}
{105}{}{Bem-vindo, estranho. Nós não vemos seu tipo frequentemente.}
{106}{}{Uh, obrigado. Tchau.}
{107}{}{Por que não?}
{108}{}{Hnnng!}
{109}{}{Não tão rapido! Esta é uma pequena comunidade. Nós não vemos estranhos frequentemente,
 e nós realmente não precisamos deles se você entende o que o quero dizer. Se você
 não tem uma boa razão pra estar aqui melhor seria pra você continuar indo.}
{110}{}{Ei, eu não vou machucar ninguém.}
{111}{}{Uh.}
{112}{}{Eu não estava dizendo que você ia. Apenas que seria melhor você nos deixar em paz.}
{113}{}{Eu tentarei não causar problema.}
{114}{}{Eu estou cheio e cansado do seu lixo. Prepare-se pra encontrar seu criador.}
{115}{}{Olha, Shady Sands não precisa do seu tipo do Hub, ou
 Junktown, ou de onde que que seja que você tenha vindo.
 Nós estamos muito bem sozinhos.}
{116}{}{O ultimo comerciante do Hub nos vendeu uma bomba de irrigacao
 que funciona mal. Nós tivemos o bastante com suas negociações sujas.}
{117}{}{Você entendeu tudo errado. Eu não sou assim.}
{118}{}{Sim, certo. Assim você diz. Apenas não se meta em qualquer problema, Certo?}
{119}{}{Sem problema.}
{120}{}{Sim, que seja.}
{121}{}{Bem, talvez você não seja. Você parece um pouco diferente para mim.
 Eu direi isso pra você. Você deveria ir falar com o Aradesh.
 Ele esta no centro da cidade.}
{122}{}{Nós não queremos seu tipo aqui. Volte para de onde quer que você tenha vindo.}
{123}{}{Ei, sem necessidade de armas. Nós não olhamos muito bondosamente
 com aqueles que as usam por aqui.}
{124}{}{Ei, você não se revelou ser uma pessoa ruim depois de tudo.
 Tenha um bom dia.}
{125}{}{Eu realmente desejo que você simplemente deixe a cidade.}
{126}{}{[MAIS]}
