{100}{}{Você vê o Irmao Thomas.}
{101}{}{Por que, ola. Você deve ser o novo Iniciado sobre o qual Talus me disse a respeito.
 Esta terrivelmente tarde pra uma chamada social, o que eu posso fazer por você?}
{102}{}{Eu preciso de alguns suprimentos.}
{103}{}{Eu preciso de treinamento.}
{104}{}{Eu queria um pouco de ajuda medica.}
{105}{}{Nada, lamento aborrecer você.}
{106}{}{Yuk Yuk?}
{107}{}{Ruh.}
{108}{}{O que poderia você possivelmente querer a esta hora?}
{109}{}{Eu não tenho tempo para isto.}
{110}{}{O que? Eu pareco o homem da requisicao? Se você nem mesmo sabe quem eu sou,
 por que você esta me aborrecendo? Por favor saia!}
{111}{}{Maldicao }
{112}{}{, Eu sou um treinador, não um doutor. Ela esta no nível dois.}
{113}{}{Bem, por que você esta me aborrecendo sobre isso? O Michael esta provavelmente 
 adormecido agora, a menos que Talus pos ele no dever de sentinela. Verifique na sala
 de suprimentos de manha.}
{114}{}{Bem, os Elders disseram não pra um novo treinamento de iniciados mas... com
 certeza. Você parece um lad jovem bacana. Eu odiaria que algo acontecesse com você
 lá fora, quando eu poderia ter sido capaz de ajudar. Pro que você esta procurando}
{115}{}{Bem, os Elders disseram não pra um novo treinamento de iniciados mas... com
 certeza. Você parece uma jovem moca bacana. Eu odiaria que algo acontecesse com
 você lá fora, quando eu poderia ter sido capaz de ajudar. Para o que você esta
 procurando treinamento?}
{118}{}{Armas pequenas.}
{119}{}{Armas grandes.}
{120}{}{Armas de energia.}
{121}{}{Combate desarmado.}
{122}{}{Armas pra corpo-a-corpo.}
{123}{}{Arremesso.}
{124}{}{Nada, lamento.}
{125}{}{Why I ought to throw you right out of my room, but I'm a nice old
 man. The Elders said no new initiate training but...I might be able to
 help. They probably didn't have you in mid when they said that. What are
 you looking to train in?}
{126}{}{Ola de novo. Bom ver você. Não seja timido, eu não mais durmo muito.
 Você esta procurando por mais treinamento? O que será hoje... Eu quero
 dizer, esta noite?}
{127}{}{Eu sabia que você voltaria! No que você esta mood para esta noite?}
{128}{}{Você vai me fazer perguntas idiotas de novo? Eu realmente não tenho o
 o tempo.}
{129}{}{Bem, você entende, armas de calibre diferentes tem...}
{130}{}{Apos um dia de treinamento intenso você se sente mais treinado com armas pequenas.}
{131}{}{O...}
{132}{}{Apos dois dias de treinamento intenso você se sente mais treinado com armas grandes.}
{134}{}{Apos alguns dias de treinamento intenso você se sente mais treinado com armas 
 de energia.}
{135}{}{Apos um dia de treinamento intenso você se sente mais treinado em combate desarmado.}
{136}{}{Apos dois dias de treinamento intenso você se sente mais treinado com armas 
 corpo-a-corpo.}
{137}{}{Apos um dia de treinamento intenso você se sente mais treinado em objetos de
 arremesso.}
{138}{}{Sem problema. Deixe-me sabe se você mudar de ideia.}
{139}{}{Eu não sei por que eu estou desperdicando meu tempo com você.}
{140}{}{Sim? Ah, eu suponho que você esta procurando por mais treinamento. Bem,
 eu não mais durmo muito de qualquer modo, por que não? O que será?}
{141}{}{Agora o que? Mais questoes estupidas?}
{142}{}{Ah, esta tudo bem. Como eu disse, eu dificilmente durmo. Volte a qualquer
 hora.}
{143}{}{Bem, pare de me pestering então. Eu sou um homem velho e eu preciso do meu
 sono de beleza.}
