{100}{}{ sente que há uma armadilha por perto.}
{101}{}{Você sente que há uma armadilha por perto.}
{102}{}{ detona uma armadilha, alertando a base sobre sua presença.}
{103}{}{Você detona uma armadilha, alertando a base sobre sua presença.}
{104}{}{Você ganha }
{105}{}{ de experiência pelo uso bem-sucedido da sua perícia de Armadilhas.}
{106}{}{ desarma a armadilha.}
{107}{}{Você desarma a armadilha.}
{108}{}{ aciona uma armadilha!}
{109}{}{Você aciona uma armadilha!}
{110}{}{Você detecta uma armadilha aqui, mas não consegue desarmá-la.}
{111}{}{Você não consegue desarmá-la.}
{112}{}{ não consegue desarmá-la.}
{113}{}{ aciona a armadilha!}
{114}{}{Você aciona a armadilha!}
