{100}{}{Você vê a Trish, uma garconete do Skum Pitt.}
{101}{}{O que diabos você esta fazendo no meu quarto?}
{102}{}{Gug!}
{103}{}{Oops, lamento. Eu pensei que este era meu quarto.}
{104}{}{Lamento. Tchau.}
{105}{}{De jeito nenhum! Eu não gosto disso! Vai falar com a Sinthia lá embaixo no salao.
 Ela poderia estar disponivel, mas ela nunca esta livre.}
{106}{}{Sim, certo. Que seja. Este e o meu quarto. Saia daqui.}
{107}{}{O que diabos você esta fazendo no meu quarto?}
{108}{}{Grub!}
{109}{}{Oops, lamento. Eu pensei que este era meu quarto.}
{110}{}{Você conhece um cara chamado Saul?}
{111}{}{Eu costumava pensar que sim. Agora, eu não tenho tanta certeza.}
{112}{}{Ele realmente se importa com você.}
{113}{}{Eu acho que você deveria deixa-lo.}
{114}{}{Assim ele diz. Se ele o fizesse, ele não estaria fazendo o que ele esta fazendo.}
{115}{}{O que é isso?}
{116}{}{É a respeito do boxe, certo?}
{117}{}{Você diria isso. Você quer tomar seu lugar, certo?}
{118}{}{Não. Você e muito shanky.}
{119}{}{Com certeza.}
{120}{}{Apenas me deixe em paz.}
{121}{}{Talvez você esteja certo. Talvez eu precise entender o que ele faz
 e deixar assim.}
{122}{}{Sua luta, claro. Eu não entendo.}
{123}{}{É uma coisa de homem.}
{124}{}{Claro que não, querido.}
{125}{}{Claro que é o boxe. Ele e um cara realmente legal, mas ele precisa
 sair disso antes que mate ele.}
{126}{}{Talvez isso seja o que ele quer fazer.}
{127}{}{Ei, eu encontrei você no Skum Pitt. O que diabos você esta fazendo no meu quarto?}
{128}{}{Plato}
{129}{}{Eu queria dar uma olhada mais de perto em você.}
{130}{}{Eu queria obter um pouco de informação de você, e eu não queri faze-lo
 na frente daquele bartender.}
{131}{}{Apenas me deixe em paz, seu perdedor. A Sinthia poderia ser seu tipo de
 mulher, mas eu com certeza não sou.}
{132}{}{Você deveria me deixar em paz. I realmente não quero falar com você.}
{133}{}{Lamento perturbar você.}
{134}{}{Saia do meu quarto!}
{135}{}{Eu vou trazer a Marcelles e ela limpara seu relogio.}
{136}{}{Meu namorado poderia derrotar você.}
{137}{}{Olha, este e meu quarto. Por favor saia.}
{138}{}{Obrigado por ajudar com o Saul. Ele e realmente um cara bacana.}
{139}{}{Você fez meu namorado ser morto. Eu deveria odiar você, mas eu sabia que
 ia acontecer mais cedo ou mais tarde. Por favor me deixe em paz.}
{140}{}{Ei, obrigado por me ajudar quando aqueles Skulz pularam em mim. Não há
 muitas pessoas querendo fazer esse tipo de coisa estes dias.}
{141}{}{Hnnn.}
{142}{}{De nada. Vejo você por ai.}
{143}{}{De nada. Eu poderia fazer algumas perguntas?}
{144}{}{Eu creio que sim.}
{145}{}{Quem possui o bar?}
{146}{}{Quem é Gizmo?}
{147}{}{Por que você gritou por Saul?}
{148}{}{Obrigado, tchau.}
{149}{}{Neal possui o bar. Ele e um bom cara, sempre me tratou bem. Nós
 costumavamos namorar, mas ele ficou um pouco muito serio pro meu gosto.
 Eu não quero ser uma viuva.}
{150}{}{Ah! Saul, onde esta você?!?}
{151}{}{Zzzz}
{152}{}{Lamento, nos estamos fechados. Volte mais tarde.}
{153}{}{Nada, obrigado.}
{154}{}{Gizmo comanda o Cassino. Ele gostaria de tomar o bar do Neal, mas o
 Neal não quer vender.}
{155}{}{O Killian e o Gizmo não gostam um do outro. Um deles ou tera que
 sair da cidade ou ser enterrado debaixo dela.}
{156}{}{Bem-vindo ao Skum Pitt. Eu posso pegar algo para você beber?}
{157}{}{Sim, o que você tem?}
{158}{}{Saul e meu namorado. Ele e realmente bom para mim.}
{159}{}{Na verdade, eu posso fazer algumas perguntas?}
{160}{}{Não, como uma questão de fato, você não pode. Se você nai vai pedir uma
 bebida então você esta no lugar errado.}
{161}{}{Do que você gostaria?}
{162}{}{Gizmo, bem, Gizmo tem a intenção de tomar o bar. E se o Neal não vender,
 eu aposto que algumas coisas ruins acontecerao.}
{163}{}{Um dia, algum vagabundo vai matar o Neal por um copo de porcaria de água
 ou algo estúpido assim. No caso de você não ter notado, ser dono de um bar e
 trabalho difícil estes dias.}
{164}{}{Nuka-cola, 3 tampinhas.}
{165}{}{Cerveja, 5 tampinhas.}
{166}{}{A coisa forte, 20 tampinhas.}
{167}{}{Você vê uma garconete.}
{168}{}{Ainda assim, trabalhar para o Gizmo vai mata-lo.}
{169}{}{Não, mas você não pode muda-lo e ele não pode mudar você. Se você não gosta
 do que ele faz, então você deveria procurar em outro lugar.}
{170}{}{Hnnngh! Hoo!}
{171}{}{Lamento, parece que você já a little gone.}
{172}{}{Você ganha 300 pontos de experiência por ajudar a derrotar os Skulz na
 briga de bar.}
{173}{}{You ganha 250 pontos de experiência por salvar o relacionamento de Saul e Trish.}
{174}{}{Aqui vai você. Aprecie.}
{200}{}{Tive uma conversa com o Saul.}
{201}{}{E daí?}
{202}{}{Ele disse que você não gosta do boxe dele.}
{203}{}{Claro que não gosto! Ele é um cara muito legal, mas precisa largar isso antes que o mate.}
{204}{}{ de experiência por mediar a relação de Saul e Trish.}
