{100}{}{Você vê o Vasquez, o mercenario desperado.}
{101}{}{Você vê um pistoleiro seedy-looking.}
{102}{}{O que você quer?}
{103}{}{Quem é você?}
{104}{}{Hnn.}
{105}{}{Eu não trabalho para os fracos de mente. Você saia agora.}
{106}{}{Você não ouviu sobre mim? Eu fiquei magoado! Meu nome e Vasquez
 Villanova Hernandez Ortega. Eu sou um famoso desperado,  meu amigo. É,
 se você tiver necessidade, eu sou um pistoleiro para contratar.}
{107}{}{Mesmo? Quanto você custa?}
{108}{}{Vejo você por ai, talvez . . . boa sorte. Ei.}
{109}{}{Ahh, direto ao ponto meu amigo. Excelente. Eu ajudarei você
 na cidade por meros $500 por semana. Meus servicos não são
 baratos, mas então, eu valho o preço.}
{110}{}{Otimo, eu contratarei você. Aqui estão $500.}
{111}{}{Lamento aborrecer você, mas eu não acho que eu preciso
 dos seus servicos.}
{112}{}{Eu lamento meu amigo, mas eu não trabalho por dinheiro
 imaginario. Eu preciso de dinheiro vivo.}
{113}{}{Excelente. Eu sou seu. Vamos lá, este lugar me da tedio.}
{114}{}{Vá em frene, eu sou seu para comandar!}
{115}{}{Vamos pegar alguma coisa pra beber!}
{116}{}{Aonde nos iremos primeiro?}
{117}{}{Tanto quanto você fique em Junktown, eu sou seu. Eu não
 gosto de sair desta cidade.}
{118}{}{Você sabia que há uma recompensa pela minha cabeca?
 Contudo, e muito pequena.}
{119}{}{Ah, meu amigo. É bom ver você de novo.}
{120}{}{Eu quero contratar você por uma semana.}
{121}{}{Bom encontrar você de novo.}
{122}{}{Hnn.}
{123}{}{Bem, talvez não seja tão bom ver você de novo. Tenha
 um bom dia.}
{124}{}{Claro. Minha cota e pequena, e meu valor e tão
 grande. $500, por favor.}
{125}{}{Aqui vai você.}
{126}{}{Você não deveria ter feito isso, meu amigo que em
 breve vai estar morto.}
{130}{}{Pela cidade?}
{151}{}{Esta é a loja do Killian, uma loja geral. Sempre tem bastante estoque pra gente como nós.}
{152}{}{O cassino do Gizmo. Um antro de jogatina e atividade do submundo. Talvez você goste, meu amigo?}
{153}{}{Precisa de um quarto pra dormir? A Crash House é onde você vai ter sorte.}
{154}{}{Isto é a cadeia. É muito entediante, confie em mim.}
{155}{}{Se você estiver machucado, o Doc Morbid pode te ajudar. Ele tirou um dos meus dentes um tempo atrás. Ainda dói, aliás.}
{156}{}{Aqueles caras de manto são novos por aqui, e me dão arrepios.}
{157}{}{Você pode apostar nas lutas do ringue. Uma vez ganhei um bom dinheiro.}
{158}{}{Isto é território dos Skullz, meu amigo. Não deveríamos estar aqui.}
{159}{}{Precisa de uma bebida? O Skum Pitt abre à noite. Deveríamos voltar então.}
{160}{}{Ahh, o lugar certo pra estar agora! Precisa de uma bebida? Você vai conseguir aqui no Skum Pitt!}
{161}{}{Bom, isto era território dos Skullz. Não mais agora.}
{162}{}{Talvez esse cachorro esteja só com fome.}
{163}{}{Ah... Até mais, meu amor.}
{200}{}{Meu amigo, seu rodeio já está grande demais.}
{201}{}{Preciso mudar de formação.}
{202}{}{A que distância você me quer?}
{203}{}{Fique perto.}
{204}{}{Mantenha uma distância moderada.}
{205}{}{Vá pra um alcance maior.}
{206}{}{Que tipos de perícia com armas você tem?}
{207}{}{Sou um pistoleiro, meu amigo. Atiro com minha pistola!}
{208}{}{É só isso.}
{209}{}{Preciso que você venha comigo de novo.}
{210}{}{Espere aqui até eu voltar.}
{211}{}{Se você diz.}
{300}{}{Meu amigo, estou pronto.}
{301}{}{Nada que vá nos atrasar, meu amigo.}
{302}{}{Você tem algo que ajude, meu amigo?}
{303}{}{Ei, talvez você devesse dar uma olhada nisto.}
{310}{}{Certo. Estou indo.}
{311}{}{Aqui?}
{312}{}{Vou ficar aqui.}
{313}{}{Assim é melhor, meu amigo?}
{970}{}{Esse é meu nome.}
{971}{}{Meu amigo, você está falando comigo.}
{972}{}{Sou eu.}
{980}{}{Não sei nada sobre isso.}
{981}{}{Desculpe. Nem ideia, meu amigo.}
{982}{}{Nunca ouvi falar.}
{2000}{}{Vamos discutir nossas táticas de combate.}
{2001}{}{Yes?}
{2010}{}{Saque sua melhor arma.}
{2011}{}{Troque sua armadura.}
{2012}{}{Prefira combate à distância a combate de perto.}
{2013}{}{Prefira combate de perto a combate à distância.}
{2014}{}{Escolha a distância por conta própria.}
{2015}{}{É só isso por enquanto.}
{2100}{}{Claro.}
{2101}{}{Pode deixar, meu amigo.}
{2102}{}{Como você quiser, meu amigo.}
{3500}{}{Sinto muito, meu amigo, mas estou quase precisando de muletas e cadeira de rodas por aqui.}
{3501}{}{Sinto muito, meu amigo, mas estou brilhando feito um letreiro de neon por aqui. Tem algum remédio anti-radiação?}
{3502}{}{Sinto muito, meu amigo, mas estou com veneno correndo pelo corpo. Tem algum antídoto?}
{3503}{}{Vamos embora, este lugar me entedia.}
