{100}{}{Você vê uma porta típica de Vault.}
{101}{}{Esta é uma porta típica de Vault. Parece que os acoplamentos de energia dela estão travados.}
{102}{}{Porta num move}
{103}{}{Esta porta está travada. Seria preciso uma pessoa muito forte pra abri-la.}
{104}{}{*Hrnnnnnn*... *hfff*... *hfff*}
{105}{}{Mesmo com o pé de cabra, você ainda não é forte o bastante pra forçar a porta.}
{106}{}{*Hrnnnnnn*}
{107}{}{Com a ajuda do pé de cabra, você força a porta e a abre.}
{108}{}{*Hrnnnnn*}
{109}{}{Usando sua força física bruta, você força a porta e a abre.}
{110}{}{Uau. Isso não fez nem um arranhão nela.}
{111}{}{BUM num machuca porta}
{112}{}{A porta está travada, não trancada.}
{113}{}{Porta travadinha num trancadinha}
{114}{}{A porta não fecha. Está emperrada.}
{115}{}{Porta num move.}
