{100}{}{Você vê o Zack.}
{101}{}{Você vê um Gun Runner.}
{102}{}{Oi, eu sou o Zack. Você quer comprar armas? Me deixe ver o que você tem pra negociar.}
{103}{}{Não.}
{104}{}{Certo.}
{105}{}{Você pode me dar um desconto?}
{106}{}{Você quer comprar armas? Me deixe ver o que você tem pra negociar.}
{107}{}{Lamento aborrecer você.}
{108}{}{Bom fazer negócios com você.}
{109}{}{}
{110}{}{Certo. Volte se você precisar de alguma coisa.}
{111}{}{Melhor você decidir rapido. Você esta aqui pra
 comprar equipamentou ou você apenas veio aqui pra levar um tiro?}
{112}{}{Você tem um verdadeiro problema de atitude.}
{113}{}{Lamento, talvez eu pudesse usar algum equpamento depois de tudo.}
{114}{}{O que diabos você esta fazendo aqui então?}
{115}{}{Nada.}
{116}{}{Com certeza.}
{117}{}{Sim, bem, até o Gabriel dizer que sim, você tem que pagar
 o preço completo como todo mundo.}
{118}{}{Eu não sei sobre isso.}
{119}{}{De qualquer maneira mostre-me o que você tem.}
{120}{}{Otimo! Mostre-me o que você tem.}
{121}{}{Eu pararei depois por aquele desconto.}
{122}{}{Eu posso conseguir um desconto melhor?}
{123}{}{Lamento. Eu dei a você o melhor desconto que eu posso.}
{998}{}{Zack, seu equipamento é de primeira qualidade, mas estou procurando algo *ainda mais* especial.}
{999}{}{A gente pode falar de novo sobre o equipamento *ainda mais* especial?}
{1000}{}{Desculpe, mas isso é tudo que tenho no momento.}
{1001}{}{Eu poderia tentar arranjar materiais melhores de novo, agora que as Deathclaws não incomodam mais. Mas vai levar um tempo.}
{1010}{}{Precisa de ajuda com alguma coisa?}
{1100}{}{Pagar novos catadores vai custar. Se você quer acelerar o processo, um investimento de 10.000 tampinhas provavelmente ajudaria.}
{1110}{}{Não tenho esse tanto de dinheiro.}
{1120}{}{Espero mesmo que valha a pena, Zack! [Pagar 10.000 tampinhas]}
{1130}{}{Ufa. Talvez depois.}
{1200}{}{Volte quando tiver esse tanto de dinheiro.}
{1300}{}{Não posso prometer nada. Você tem que dar uma passada de vez em quando, porque esse tipo de estoque costuma vender rápido.}
{1400}{}{Certo.}
{1999}{}{Você consegue modificar ou melhorar armas?}
{2000}{}{Com certeza consigo. O que você tem?}
{2001}{}{Com certeza consigo, mas você não parece ter nada em que a gente possa mexer. Traga umas... éh, pistolas e rifles "normais", e talvez a gente consiga te ajudar.}
{2002}{}{Você não parece ter nada em que a gente possa mexer. Traga umas... éh, pistolas e rifles "normais", e talvez a gente consiga te ajudar.}
{2010}{}{Você consegue fazer algo com alguma dessas pistolas que eu tenho?}
{2020}{}{Um dos meus rifles bem que precisava de uns acessórios.}
{2025}{}{Você consegue turbinar meu lança-chamas?}
{2030}{}{Você consegue fazer algo com este aguilhão de gado aqui?}
{2040}{}{Deixa pra lá. Eu estava interessado em outra coisa...}
{2050}{}{Na verdade, nada hoje.}
{2100}{}{Deixa eu ver o que você tem.}
{2110}{}{Na verdade, você poderia melhorar uma das minhas outras armas?}
{2120}{}{Deixa pra lá. Eu queria outra coisa...}
{2130}{}{Na verdade, nenhuma delas. Tenho que ir.}
{2140}{}{Caro demais pro meu bolso. Volto quando tiver mais grana.}
{2200}{}{A gente pode pôr um carregador rápido nesse magnum aí por }
{2201}{}{Essa Desert Eagle que você tem... se quiser, a gente dá um pente ampliado a ela por }
{2202}{}{ caps.}
{2203}{}{Essa Pistola Laser... tenho certeza que a gente consegue melhorar a emissão do laser com um novo sistema de mira.}
{2210}{}{Instale o carregador rápido no magnum.}
{2220}{}{Amplie o pente desta Desert Eagle aqui.}
{2230}{}{Melhore a pistola laser Wattz 1000 com um novo sistema de mira.}
{2300}{}{A gente pode pôr uma mira nesse rifle de caça por }
{2301}{}{Esse rifle de assalto que você tem aí... A gente dá um pente ampliado a ele por }
{2302}{}{Tenho uma mira de baixa luminosidade que a gente pode pôr nesse rifle de assalto avançado que você tem, por }
{2303}{}{Sua espingarda de combate... A gente dá um adaptador pra pentes de tambor a ela por }
{2304}{}{Tenho certeza que a gente ainda tem um chip especial de reciclagem que dá pra pôr no seu rifle laser por }
{2310}{}{Certo, então... ponha uma mira no rifle de caça Colt.}
{2320}{}{Amplie o pente do rifle de assalto AK-112.}
{2330}{}{Instale essa mira de baixa luminosidade na AK-198.}
{2340}{}{Instale um adaptador de pente circular na Winchester City-Killer.}
{2350}{}{Melhore o sistema de recarga do rifle laser Wattz 2000.}
{2400}{}{Você quer esse aguilhão turbinado? A gente pode SUPERCARREGAR ele por }
{2410}{}{Claro.}
{2500}{}{Deixa eu dar uma olhada... É, dá pra fazer algo com isso por }
{2510}{}{Legal. Vamos nessa.}
{2600}{}{Espera aqui.}
{2601}{}{Pronto. Mais alguma coisa?}
