{100}{}{Você vê um homem de olhar afiado e postura de negócios.}
{101}{}{Você vê um crupiê de craps.}
{102}{}{Ele tem um bastão e muitas fichas. Você poderia tentar a sorte com ele.}
{103}{}{Façam suas apostas. Temos outro apostador.}
{104}{}{Quanto você vai apostar na LINHA DE PASSE?}
{105}{}{Quanto você vai apostar na LINHA DE NÃO-PASSE?}
{106}{}{Quanto você vai apostar na LINHA DE VINDA?}
{107}{}{Quanto você vai apostar na LINHA DE NÃO-VINDA?}
{108}{}{Quanto você vai apostar no CAMPO?}
{157}{}{Quanto você vai apostar na sua APOSTA DE POSIÇÃO?}
{109}{}{Ponto marcado}
{110}{}{Linha de passe.}
{111}{}{Linha de não-passe.}
{112}{}{Linha de vinda.}
{113}{}{Linha de não-vinda.}
{114}{}{Apostas de proposição...}
{115}{}{Apostas de posição...}
{116}{}{Apostar no Campo}
{118}{}{Rolar}
{119}{}{Aposta na linha de passe definida em:}
{120}{}{Aposta na linha de não-passe definida em:}
{121}{}{Aposta na linha de vinda definida em:}
{122}{}{Aposta na linha de não-vinda definida em:}
{123}{}{7:}
{124}{}{d3s:}
{125}{}{d4s:}
{126}{}{d5s:}
{127}{}{d2s:}
{128}{}{1&2:}
{129}{}{5&6:}
{130}{}{1&1:}
{131}{}{6&6:}
{132}{}{Craps:}
{133}{}{Pls 4:}
{134}{}{Pls 5:}
{135}{}{Pls 6:}
{136}{}{Pls 8:}
{137}{}{Pls 9:}
{138}{}{Pls 10:}
{139}{}{On 4:}
{140}{}{On 5:}
{141}{}{On 6:}
{142}{}{On 8:}
{143}{}{On 9:}
{144}{}{On 10:}
{145}{}{Odds 4:}
{146}{}{Odds 5:}
{147}{}{Odds 6:}
{148}{}{Odds 8:}
{149}{}{Odds 9:}
{150}{}{Odds 10:}
{151}{}{Field bet set at:}
{152}{}{Qual APOSTA DE PROPOSIÇÃO?}
{153}{}{Quanto?}
{154}{}{Apostas de rolagem única...}
{155}{}{Apostas hardway...}
{156}{}{Que tipo de aposta?}
{200}{}{rolar 7 (paga 5 pra 1)}
{201}{}{dois 3 (paga 10 pra 1)}
{202}{}{dois 4 (paga 10 pra 1)}
{203}{}{dois 5 (paga 8 pra 1)}
{204}{}{dois 2 (paga 8 pra 1)}
{205}{}{1 e 2 (paga 15 pra 1)}
{206}{}{5 e 6 (paga 15 pra 1)}
{207}{}{1 e 1 (paga 30 pra 1)}
{208}{}{6 e 6 (paga 30 pra 1)}
{209}{}{Qualquer Craps (paga 8 pra 1)}
{299}{}{Qual APOSTA DE POSIÇÃO?}
{300}{}{no 4 (paga 1.8)}
{301}{}{no 5 (paga 1.4)}
{302}{}{no 6 (paga 1.16)}
{303}{}{no 8 (paga 1.16)}
{304}{}{no 9 (paga 1.4)}
{305}{}{no 10 (paga 1.8)}
{400}{}{Voltar...}
{500}{}{}
{501}{}{ tampinhas.}
{600}{}{Sete paga as linhas, ponto encerrado.}
{601}{}{Onze paga as linhas.}
{602}{}{Dois, craps perde as linhas.}
{603}{}{Três, craps perde as linhas.}
{604}{}{Doze, craps perde as linhas.}
{610}{}{Sete perde as linhas de não, ponto encerrado.}
{611}{}{Onze perde as linhas de não.}
{612}{}{Dois, craps paga as linhas de não.}
{613}{}{Três, craps paga as linhas de não.}
{614}{}{Doze, craps empata as linhas de não.}
{620}{}{Aposta de proposição 7}
{621}{}{Aposta de proposição dois 3}
{622}{}{Aposta de proposição dois 4}
{623}{}{Aposta de proposição dois 5}
{624}{}{Aposta de proposição dois 2}
{625}{}{Aposta de proposição 1 e 2}
{626}{}{Aposta de proposição 5 e 6}
{627}{}{Aposta de proposição 1 e 1}
{628}{}{Aposta de proposição 6 e 6}
{629}{}{Aposta de proposição Craps 2,3,12}
{630}{}{Perde!}
{631}{}{Ganha!}
{650}{}{Aposta de posição 4}
{651}{}{Aposta de posição 5}
{652}{}{Aposta de posição 6}
{653}{}{Aposta de posição 8}
{654}{}{Aposta de posição 9}
{655}{}{Aposta de posição 10}
{660}{}{Aposta no campo 2 ganha em dobro.}
{661}{}{Aposta no campo 3 ganha.}
{662}{}{Aposta no campo 4 ganha.}
{663}{}{Aposta no campo 9 ganha.}
{664}{}{Aposta no campo 10 ganha.}
{665}{}{Aposta no campo 11 ganha.}
{666}{}{Aposta no campo 12 ganha em triplo.}
{667}{}{Aposta no campo perde.}
{670}{}{Aposta fixa 4}
{671}{}{Aposta fixa 5}
{672}{}{Aposta fixa 6}
{673}{}{Aposta fixa 8}
{674}{}{Aposta fixa 9}
{675}{}{Aposta fixa 10}
{680}{}{Aposta de odds 4}
{681}{}{Aposta de odds 5}
{682}{}{Aposta de odds 6}
{683}{}{Aposta de odds 8}
{684}{}{Aposta de odds 9}
{685}{}{Aposta de odds 10}
{700}{}{Sem odds de Ponto retornadas.}
{701}{}{Jogar}
{702}{}{Não}
{710}{}{Die1:}
{711}{}{Die2:}
{712}{}{Desculpe, tenho que ir.}
{713}{}{Desculpe, não quero fazer esta aposta.}
{714}{}{Ponto encerrado.}
{800}{}{Apostar Odds nos Números de Jogo.}
{801}{}{Escolha o multiplicador de odds. Odds em:}
{802}{}{x de odds.}
{803}{}{atualmente em:}
{804}{}{Aposta de odds no 4.}
{805}{}{Aposta de odds no 5.}
{806}{}{Aposta de odds no 6.}
{807}{}{Aposta de odds no 8.}
{808}{}{Aposta de odds no 9.}
{809}{}{Aposta de odds no 10.}
{810}{}{Apostar em qual número?}
{1100}{}{Você vê uma mulher de olhar afiado e postura de negócios.}
{1102}{}{Ela tem um bastão e muitas fichas. Você poderia tentar a sorte com ela.}
