{100}{}{Você vê um crupiê.}
{101}{}{Você vê uma mesa de dados.}
{110}{}{Você vê uma garota.}
{111}{}{Você vê uma mesa.}
{140}{}{Você vê uma mesa pra jogos de dados.}
{141}{}{Você vê uma mesa com coisas em cima.}
{150}{}{Você vê uma das crupiês do cassino.}
{151}{}{Você vê uma das crupiês do cassino. Ela te faz sinal pra chegar e jogar.}
{152}{}{Você vê uma das crupiês do cassino. O vestido dela mal cobre o corpo.}
{153}{}{Você vê uma das crupiês do cassino. Ela tem umas belas pernas.}
{154}{}{Você vê uma das crupiês do cassino. Ela te dá uma piscadela.}
{155}{}{Você vê uma das crupiês do cassino. Ela cheira reeeealmente bem.}
{160}{}{Você vê uma mulher bonita.}
{161}{}{Ela está te acenando pra chegar mais perto.}
{162}{}{O vestido dela é meio pequeno.}
{163}{}{Ela tem umas belas pernas.}
{164}{}{Ela te dá uma piscadela.}
{165}{}{Ela cheira reeealmente bem.}
{175}{}{SEM DADOS!!!}
{176}{}{DADOS DEMAIS!!!}
{177}{}{As probabilidades parecem certas desde que você trocou os dados.}
{178}{}{As probabilidades não parecem muito certas.}
{179}{}{Você não consegue avaliar as probabilidades com certeza.}
{185}{}{As probabilidades parecem certas.}
{186}{}{Você não consegue avaliar as probabilidades com certeza.}
{187}{}{As probabilidades não parecem muito certas.}
{200}{}{::Comemora::}
{201}{}{::Aplaude::}
{202}{}{::Assobia::}
{203}{}{}
{204}{}{Pensei que você tinha esquecido da gente enquanto estava por aí salvando o mundo.}
{215}{}{Olá, }
{216}{}{Se você estiver procurando uma companhia mais tarde}
{217}{}{Ei, você[pisca]a fim de apostar?}
{218}{}{Ele parece tão[estremece]perigoso.}
{219}{}{Bem-vindo ao cassino, }
{220}{}{Fala bem de mim pro chefe?}
{221}{}{Olá, senhora. Me avise se eu puder ajudar em algo.}
{222}{}{A fim de apostar, senhora?}
{223}{}{Ela parece tão[estremece]perigosa.}
{235}{}{Parece que este aqui já está apostando a própria vida.}
{236}{}{Ãh, acho que ele entrou no cassino errado}
{237}{}{Se ele não sair antes que os rapazes o vejam}
{238}{}{Oh-oh. Encrenca}
{239}{}{Parece que esta aqui já está apostando a própria vida.}
{240}{}{Ãh, acho que ela entrou no cassino errado}
{241}{}{Se ela não sair antes que os rapazes a vejam}
{250}{}{Ei, musculoso. A fim de gastar umas tampinhas?}
{251}{}{Ei, campeão[pisca]a fim de apostar?}
{252}{}{Ei, campeão[sorri]quer arriscar?}
{253}{}{Se você estiver procurando uma companhia mais tarde}
{254}{}{Será que eu devia falar com ele}
{255}{}{Ei, }
{256}{}{Se você está a fim de ganhar umas tampinhas, veio ao lugar certo.}
{257}{}{A Deusa da Sorte está na casa hoje... só vencedores!}
{258}{}{Chega mais, }
{259}{}{Precisa de outra bebida?}
{260}{}{Bem-vindo ao cassino, }
{261}{}{Olá, }
{262}{}{A fim de apostar, }
{263}{}{Bem-vindo ao cassino, }
{270}{}{E aí, astro de cinema. A fim de gastar umas tampinhas?}
{271}{}{Ei, }
{272}{}{Ei, }
{273}{}{Se você está a fim de ganhar umas tampinhas }
{274}{}{A Deusa da Sorte está na casa hoje... só vencedores!}
{275}{}{Chega mais, }
{276}{}{Precisa de outra bebida?}
{277}{}{Bem-vindo ao cassino, }
{278}{}{E aí, Srta. Estrela de Cinema. A fim de gastar um salário?}
{279}{}{Você dança hoje à noite?}
{290}{}{E aí, docinho. A fim de gastar umas tampinhas?}
{291}{}{Ei, docinho[pisca]a fim de apostar?}
{292}{}{Ei, docinho[sorri]quer arriscar?}
{293}{}{Se você está a fim de ganhar umas tampinhas, veio ao lugar certo.}
{294}{}{A Deusa da Sorte está na casa hoje... só vencedores!}
{295}{}{Chega mais, ganhe umas tampinhas.}
{296}{}{Precisa de outra bebida, querido?}
{297}{}{Bem-vindo ao cassino, querido.}
{298}{}{Esta mesa está livre se você quiser apostar}
{299}{}{E aí, querido. A fim de gastar umas tampinhas?}
{300}{}{A fim de apostar, querido?}
{301}{}{Bem-vindo ao cassino, querido.}
{320}{}{[A crupiê te olha nervosa e então morde o lábio.] Hã, façam suas apostas... aposta mínima }
{321}{}{Faça sua aposta, senhor. Aposta mínima }
{322}{}{Faça sua aposta, senhora. Aposta mínima }
{323}{}{Façam suas apostas, aposta mínima }
{324}{}{Eu apostá melhó que ocê}
{325}{}{Eu jogá craps de calça}
{326}{}{Que jogo esse? Pode apostá pele de gecko? Eu tê geckoooo... luzinha bunita! [Sair vagando.]}
{327}{}{[Você tem }
{328}{}{Bet }
{329}{}{Uau, caro demais pro meu bolso.}
{330}{}{Sem apostas hoje, obrigado.}
{331}{}{Ãh, desculpe, não sei jogar esses jogos malucos.}
{340}{}{Hã... ouvi dizer que estão dando cérebros de graça lá atrás. Talvez você devesse ir ver.}
{341}{}{Ãh, muito bem, senhor. Volte logo.}
{342}{}{Ãh, muito bem, senhora. Volte logo.}
{343}{}{Tchauzinhuuu}
{344}{}{Que bom. }
{345}{}{Hã... cérebro... que é isso?! Eu ir vê!}
{350}{}{Muito bem, senhor. Volte logo.}
{351}{}{Muito bem, senhora. Volte logo.}
{352}{}{[A crupiê levanta uma sobrancelha.] }
{354}{}{Vou querer, obrigado.}
{355}{}{Talvez sim.}
{400}{}{Desculpe, mais sorte na próxima.}
{401}{}{Desculpe, senhor. Mais sorte na próxima.}
{402}{}{Desculpe, senhora. Mais sorte na próxima.}
{410}{}{Empate.}
{411}{}{Empate. Tentar de novo, senhor?}
{412}{}{Empate. Tentar de novo, senhora?}
{420}{}{Vencedor! Você dobrou seu dinheiro!}
{421}{}{Vencedor! Você dobrou seu dinheiro! Muito bem, senhor!}
{422}{}{Vencedor! Você dobrou seu dinheiro! Muito bem, senhora!}
{430}{}{Vencedor! Você triplicou seu dinheiro!}
{431}{}{Vencedor! Você triplicou seu dinheiro! A sorte está na casa hoje! Muito bem, senhor!}
{432}{}{Vencedor! Você triplicou seu dinheiro! A sorte está na casa hoje! Muito bem, senhora!}
{440}{}{Encerrar por hoje.}
{441}{}{Encerrar por esta noite.}
{450}{}{Desculpe, esta mesa foi fechada. Alguém andou adulterando os dados.}
{451}{}{Desculpe, senhor, esta mesa foi fechada. Alguém andou adulterando os dados.}
{452}{}{Desculpe, senhora, esta mesa foi fechada. Alguém andou adulterando os dados.}
{453}{}{Ãh, tá bom.}
{454}{}{Que pena ouvir isso. Obrigado.}
{2203}{}{! Bem-vindo ao cassino, herói!}
{2215}{}{. Posso te ajudar com *alguma coisa?*}
{2219}{}{.}
{2255}{}{. A fim de gastar umas tampinhas?}
{2258}{}{, ganhe umas tampinhas.}
{2260}{}{.}
{2261}{}{. Me avise se eu puder ajudar em algo.}
{2262}{}{?}
{2263}{}{.}
{2321}{}{ tampinhas. Façam suas apostas}
{2327}{}{.] }
{2328}{}{.}
{2344}{}{ bem que poderia usar um item de inventário novo [Sair.]}
{2352}{}{ tampinhas? 'Caro demais pro seu bolso?' [Zomba.] Amigão, você está no lugar errado.}
{2353}{}{ tampinhas? 'Caro demais pro seu bolso?' [Zomba.] Garota, você está no lugar errado.}
{5000}{}{ Este é o pagamento final. A casa está encerrando por esta noite!}
{5001}{}{ Este é o pagamento final. A casa está encerrando por hoje!}
{5100}{}{Desculpe, esta mesa foi fechada.}
{5101}{}{Sinto muito, senhor, mas esta mesa foi fechada.}
{5102}{}{Sinto muito, senhora, mas esta mesa foi fechada.}
