{100}{}{Um cartaz de procurado com um esboço grosseiro a carvão de uma pessoa procurada. A pessoa no cartaz parece familiar.}
{101}{}{A legenda diz:}
{102}{}{Procurado Vivo ou Morto por Matar Crianças e por ser um Filho da Mãe Desgraçado. Recompensa: $10.000 Morto ou $5.000 Vivo.}
{103}{}{Procurado Vivo ou Morto por Matar Crianças. Recompensa: $10.000 Morto ou $5.000 Vivo.}
{104}{}{Procurado Vivo ou Morto por ser um Filho da Mãe Desgraçado. Recompensa: $10.000 Morto ou $5.000 Vivo.}
{110}{}{Procurado Vivo ou Morto por Matar Crianças e por ser um Filho da Mãe Desgraçado. Recompensa: }
{111}{}{Procurado Vivo ou Morto por Matar Crianças. Recompensa: }
{112}{}{Procurado Vivo ou Morto por ser um Filho da Mãe Desgraçado. Recompensa: }
{113}{}{ tampinhas Morto ou }
{114}{}{ tampinhas Vivo.}
