{100}{}{Você usa o computador da porta. O computador não reconhece seu codigo de acesso.}
{101}{}{Você usa o computador da porta. Um alto-falante crackles a vida.}
{102}{}{Lamento, mas nós não podemos deixar você voltar agora. Uh,
 problemas tecnicos. Tente de novo mais tarde.}
{103}{}{Você vê o computador da porta de entrada da Vault-13.}
{104}{}{Somos gratos a você por nos salvar, mas não podemos deixar você entrar.}
{105}{}{Sentimos muito, mas você não pode voltar. Desejamos o melhor pra você.}
{106}{}{O Supervisor falou; você deve ir embora.}
{107}{}{Olha, muitos de nós estão indignados com a decisão do Supervisor, mas temos que cumprir os desejos dele.}
{108}{}{Você deve construir sua vida no mundo exterior de agora em diante. Boa sorte, amigo.}
{109}{}{Você é um perigo pro futuro deste vault; vá embora imediatamente.}
{110}{}{Você não é bem-vindo aqui. Vá embora.}
{111}{}{Não vamos permitir assassinos no Vault. Suma!}
{112}{}{Temos medo do que você se tornou e do que pode fazer com a gente. Vá embora.}
{113}{}{Depois do que você fez com o Supervisor, você acha que vamos deixar você voltar?}
{114}{}{Como você pôde nos trair assim?!}
{115}{}{Vá embora, seu maníaco.}
{116}{}{O computador explode numa chuva espetacular de faíscas e fios, causando um curto-circuito em toda a configuração.}
{117}{}{Você vê o computador destruído da entrada do Vault 13.}
{118}{}{É uma bagunça total e completamente irreparável.}
{119}{}{ A porta nunca mais vai fechar.}
{120}{}{ A porta nunca mais vai abrir.}
{121}{}{Acerto em cheio! }
{122}{}{Uh-oh! }
{123}{}{O computador está inutilizável.}
{124}{}{Com a porta selada pra sempre e sem um Chip de Água substituto, os habitantes do Vault 13 logo vão descobrir que o Vault deles virou um túmulo.}
