# Taken from ALLDOGS.msg to make unique strings for Dogmeat.
{100}{}{Você vê uma coisa estranha, metade cão, metade metal. Parece estar te seguindo.}
{101}{}{É o Robodog! O bichinho de estimação favorito de todos!}
{102}{}{Au!}
{103}{}{Grrr!}
{110}{}{Você vê: Dogmeat.}

{117}{}{Au! <clique> Au!}
{118}{}{...bzzzzzz...}
{119}{}{Au! Au-au-au-<clique>au.}
{120}{}{Au?}
{121}{}{Rá! <tique-tique-tique> Rá!}

	{200}{}{Acho que precisamos falar sobre nossa distância.}
	{201}{}{Na verdade, você está a uma boa distância por enquanto.}

# Light
	{300}{}{Ei, Robodog, o que esse botão aqui faz?}
{301}{}{[Você aciona o interruptor e de repente toda a área fica iluminada.]}
	{302}{}{Interessante. Vamos deixar ligado por enquanto.}
	{303}{}{Prefiro não virar um farol de luz no meio do ermo.}

	{304}{}{[Ativar modo-luz]}
	{305}{}{[Desativar modo-luz]}
{306}{}{...bzzzzzz... <clique> Holofote ativado!}
{307}{}{...bzzzzzz... <clique> Holofote desativado!}

	{308}{}{Uhhh... Esse botão? Eu apertar?}
	{309}{}{Oooohhh!}
	{310}{}{Naaaahy!}

{900}{}{O Robodog não pode mais ser consertado neste momento.}
{901}{}{O Robodog foi consertado um pouco.}
{902}{}{O Robodog está totalmente consertado agora.}

# Too many party members
{2500}{}{Grrrrr.}
{2510}{}{O que foi? Você não gosta de tanta companhia, hein?}
{2511}{}{[Feito]}

# Fo1in2
{3500}{}{<clique> ...bzzzzzz... <clique>}
{3501}{}{Auuuuuuuuuuuu! <clique>}
{3502}{}{}