{100}{}{Você vê: Skippy.}
{101}{}{Você vê um membro de gangue.}
{102}{}{Ele está jogando pro alto o que parece ser uma faca exótica.}
{103}{}{[mais]}
{104}{}{[pronto]}
{105}{}{[Jogando um conjunto de Blades perto do seu rosto] Cuidado, seu tapado. Você pode se machucar, e aí eu teria que rir.}
{106}{}{Olha o que faz, essas coisas parecem afiadas.}
{107}{}{Me dê essas coisas antes que você machuque alguém!}
{108}{}{Afinal, o que você fica jogando pro alto?}
{109}{}{São afiadas, de fato mais afiadas que sua sagacidade.}
{110}{}{Você está me desafiando?}
{111}{}{Ai, mas acho que eu mereci essa.}
{112}{}{Eu? Te desafiar? Ah, só o pensamento já me faz rir. Não, nós Tolos não participamos do código do duelo. Não é o nosso estilo. Deixe-nos mostrar como tratamos os de fora.}
{113}{}{De fato, mereceu. O que posso fazer por você?}
{114}{}{O que são essas coisas?}
{115}{}{O que elas são é meu, o que elas não serão é seu. Além disso, estes cortadores são uma herança do meu pobre e falecido pai. Pode-se dizer que ele se enroscou um pouco nelas antes de morrer! [Skippy ri.]}
{116}{}{Você é bobo. Posso pegá-las emprestadas?}
{117}{}{Bom, já que você pediu com educação - tá bom. [Ele te entrega os cortadores.] Agora, suma, pois preciso procurar um novo brinquedo pra passar o tempo.}
{118}{}{Acho que não, pelo menos não pelo cabo. Você vai chorar sangue, ou pelo menos chorar de riso e dor quando eu terminar com você.}
{119}{}{Não gostamos do seu tipo aqui. Vá embora ou você vai levar no fim.}
{120}{}{Bom, se não é o Tolo mais recente. Um bom senso de humor, no mínimo. Talvez uma boa coordenação motora. Vamos ver. Brinque direito.}
{121}{}{Você é um sujeito de sorte, meu amigo. Este dia é o dia em que vou deixar você viver. A não ser, claro, que você me irrite demais. Aí vou ter que usar minhas melhores piadas de defunto.}
{122}{}{Nunca roube de um Tolo, seu tolo.}
{123}{}{Você já pegou os cortadores do Skippy. Pare enquanto está por cima.}
{124}{}{Você consegue roubar os cortadores enquanto ele não está olhando.}
{125}{}{Você nos insulta, e à honra da nossa Rainha. Alguns insultos só podem ser pagos com sangue.}
{126}{}{Você vai morrer, escória!}
{127}{}{Isso é seu rosto, ou seu pescoço vomitou?}
{128}{}{Sua mãe teve que amarrar um bife em você pra o cachorro brincar com você}
{129}{}{A única coisa mais estúpida que você é o Rayze.}
{130}{}{Acho que restos de parto podem viver um tempinho.}
