{100}{}{Você não consegue determinar se está envenenado ou irradiado.}
{101}{}{Você está irradiado e envenenado, mas não tem certeza da extensão.}
{102}{}{Você está irradiado, mas não tem certeza da extensão.}
{103}{}{Você está envenenado, mas não tem certeza da extensão.}
{104}{}{Você esta }
{105}{}{insignificantly}
{106}{}{slightly}
{107}{}{mildly}
{108}{}{moderately}
{109}{}{very}
{110}{}{extremely}
{111}{}{dangerously}
{112}{}{fatally}
{113}{}{ irradiated}
{114}{}{.}
{115}{}{ and }
{116}{}{Nível de irradiação: }
{117}{}{ rads.}
{118}{}{ Você está envenenado no nível }
{119}{}{Você está livre de veneno e radiação.}
{200}{}{}
