{100}{}{Você vê Dumar, um Acólito dos Filhos da Catedral.}
{101}{}{Saudações, viajante. Ouvimos histórias de alguém que percorre o Ermo. Como podemos ser úteis a você hoje?}
{102}{}{Uh? Arrooo?}
{103}{}{O Ermo é um lugar difícil. Fiquei bem ferido. Você pode me ajudar com isso?}
{104}{}{Quero você e os do seu tipo massacrados!}
{105}{}{Me conte uma história.}
{106}{}{Hã? Não consigo te ouvir. Você pode falar mais alto, por favor?}
{107}{}{Quem eu poderia consultar pra me tornar membro deste estabelecimento?}
{108}{}{Desejo compreender a sabedoria na qual você e seus companheiros seguidores basearam este estabelecimento de crenças.}
{109}{}{Sinto muito, mas estou um pouco ocupado demais no momento pra contar a história inteira dos Filhos da Catedral. Estão me fazendo limpar os bancos. Fale com a Laura se você precisar de informação.}
{110}{}{Sinto muito, mas suas palavras estão muito além de mim pra entender o que você disse. Talvez nossos seguidores mais sábios, como a Laura, possam te ajudar melhor que eu.}
{111}{}{Lamento de verdade ouvir sobre a sua enfermidade. Infelizmente, sou apenas um acólito e não posso auxiliar na sua cura. Só os membros plenos recebem treinamento nas artes da cura.}
{112}{}{Ah, criança, parece que você e eu falamos em níveis diferentes. Talvez, se você falar com a Laura, ela possa te ajudar melhor que eu. A paz esteja com você, criança.}
{113}{}{Por favor, fale com a Laura. Ela pode te ajudar melhor que eu.}
{114}{}{Somos realmente um povo pacífico. Por favor, não derrame sangue dentro deste lugar sagrado.}
{115}{}{Era uma vez um pequeno viajante que caminhava pelo mundo. Ele foi até uma jovem chamada Laura e pediu que ela lhe contasse uma história. Fim.}
{116}{}{Dumar implora que você cesse seus ataques cruéis.}
