{100}{}{Você vê Rayze dos Crypts.}
{101}{}{Você é um Tolo por vir aqui.}
{102}{}{Por que você está me incomodando?}
{103}{}{O Rock me mandou.}
{104}{}{Nada, só de passagem.}
{105}{}{Me fale sobre os Tolos.}
{106}{}{Me fale sobre o gerador de energia.}
{107}{}{Ah, é. Por quê?}
{108}{}{Ele disse que eu poderia tomar um copo de água gelada.}
{109}{}{O Rock disse que os Crypts estavam procurando membros.}
{110}{}{Ha-ha! Boa tentativa. Me deixe em paz.}
{111}{}{Pode ser. Parece que você tem algum talento. Você acha que poderia ser um Crypt?}
{112}{}{Sim.}
{113}{}{Não.}
{114}{}{Bom, então. Vamos te testar. Vamos te mandar numa pequena missão. Vá espionar os Tolos ao norte e reporte pra mim.}
{115}{}{Tá.}
{116}{}{Acho que não.}
{117}{}{Então garotinhos deveriam ir embora antes de levar uma palmada.}
{118}{}{Não gostamos de estranhos na nossa cidade. Se você quer ficar, você se junta a nós. Se não, pode se arrepender de ficar em Scrapheap.}
{119}{}{Como eu me junto a vocês?}
{120}{}{Eu pergunto e você diz sim. Você jura um juramento quando entra. Se quebrar esse juramento, mando alguns dos meus rapazes te quebrarem.}
{121}{}{Certo, eu entro.}
{122}{}{Acho que não quero jogar.}
{123}{}{Você não é bem-vindo aqui. Vá embora antes de ser enterrado.}
{124}{}{Os Tolos estão prontos pro nosso ataque?}
{125}{}{Sim.}
{126}{}{Não.}
{127}{}{Preciso espionar mais um pouco.}
{128}{}{Não importa. Nada vai impedi-los de sentir o frio da morte! Eles morrem agora!}
{129}{}{Excelente. Vamos pegá-los despreparados. Eles morrem agora!}
{130}{}{Rápido. Anseio pelo sangue dos Tolos.}
{131}{}{São meus inimigos. Vão morrer. Agora, por que você me incomoda?}
{132}{}{O Rock me mandou.}
{133}{}{Nada, só de passagem.}
{134}{}{Me fale sobre o gerador de energia.}
{135}{}{Você não deveria fazer perguntas sobre coisas que não conhece. O gerador é nosso, e vai continuar nosso. Enquanto o tivermos, estamos no controle. Você faz perguntas demais.}
{136}{}{[pronto]}
{137}{}{[mais]}
{138}{}{Haha! Mais tolos pra matar!!}
{139}{}{A única coisa que vocês Tolos vão governar é uma lápide.}
{140}{}{O esterco de Brahmin cheira melhor que você.}
{141}{}{Até o Lenny tem melhor pontaria que você.}
{142}{}{Você não deveria ter mentido pra mim. Eu percebo. Vá, espione os Tolos e volte. Não me provoque.}
{143}{}{Não dá pra confiar em você. É uma pena. Você vai morrer. Isto é um prazer.}
{144}{}{Nós governamos esta cidade agora!}
{145}{}{Agora não é hora de perguntas. Agora é hora de lutar!}
{146}{}{Então garotinhas deveriam ir embora antes de levar uma palmada.}
