{100}{}{Você vê um Fregues da Caravana.}
{101}{}{Eles nunca tem o que eu quero.}
{102}{}{Eu acho que a selecao esta ficando pior.}
{103}{}{Lamento, eu não devo falar com forasteiros.}
{104}{}{Eu nunca consigo achar o que eu quero.}
{105}{}{Se você ver qualquer Redalek, deixe-me saber.}
{106}{}{Estes preços estão ficando fora de mao.}
{107}{}{Eu estou feliz que aqueles Mercadores das Aguas não vem mais aqui.}
{108}{}{Você deveria ver Cabbot ou Darrell se você tem perguntas.}
{109}{}{Cabbot e nosso Recepcionista. Você deveria falar com ele ou Darrell.}
{110}{}{Eu gosto mais da selecao da Crimson Caravan.}
{111}{}{Os Far Go Traders não são um pessoal agradavel?}
{112}{}{A Crimson Caravan e muito vulgar para mim.}
{113}{}{Ei, você ouviu que Set foi desativado?}
{114}{}{Conjunto está morto. Set está morto. Set está morto. . .}
{115}{}{Eles nunca têm o que eu quero.}
{116}{}{Acho que a variedade está piorando.}
{117}{}{Esses preços estão saindo do controle.}
{118}{}{Lamento, eu não devo falar com forasteiros.}
{119}{}{Eu nunca consigo achar o que eu quero.}
{1100}{}{Você vê um cliente da caravana.}
{1103}{}{Você deveria ver Cabbot ou Darrell se você tem perguntas.}
{1105}{}{Se você vir algum Redalek, me avise.}
{1107}{}{Que bom que aqueles Water Merchants não vêm mais aqui.}
{1109}{}{O Cabbot é nosso Recepcionista. Você deveria falar com ele ou com o Darrell.}
{1110}{}{Eu nunca consigo achar o que eu quero.}
{1111}{}{Os Far Go Traders não são uma turma agradável?}
{1112}{}{A Crimson Caravan é vulgar demais pro meu gosto.}
