{0}{}{SALVAR JOGO}
{1}{}{CARREGAR JOGO}
{2}{}{PREFERENCIAS}
{3}{}{SAIR DO JOGO}
{4}{}{FEITO}
{100}{}{PREFERENCIAS DO JOGO}
{101}{}{DIFIC. DO JOGO}
{102}{}{DIFIC. DO COMBATE}
{103}{}{NIVEL DE VIOLENCIA}
{104}{}{DESTACAR ALVO}
{105}{}{QUEIMANDO CARAS}
{106}{}{MSGS DE COMBATE}
{107}{}{ESCARNIO}
{108}{}{SEM PALAVROES}
{109}{}{CORRER}
{110}{}{LEGENDAS}
{111}{}{DESTACAR ITEM}
{112}{}{VELOCIDADE DO COMBATE}
{113}{}{ATRASO DO TEXTO}
{114}{}{VOLUME DO AUDIO MESTRE}
{115}{}{VOLUME DA MUSICA/FILME}
{116}{}{VOLUME DOS EFEITOS DE SOM}
{117}{}{VOLUME DO DISCURSO}
{118}{}{NVEL DO BRILHO}
{119}{}{SENSITIVIDADE DO MOUSE}
{120}{}{PADRAO}
{121}{}{FECHAR}
{122}{}{Afeta a velocidade do jogador}
{123}{}{Discurso do Pipboy}
{201}{}{Ligado}
{202}{}{Desligado}
{203}{}{Facil}
{204}{}{Normal}
{205}{}{Difícil}
{206}{}{Fracote}
{207}{}{Normal}
{208}{}{Difícil}
{209}{}{Normal}
{210}{}{Mais rapido}
{211}{}{Palavroso}
{212}{}{Breve}
{213}{}{So Mirando}
{214}{}{Nenhum}
{215}{}{Minimo}
{216}{}{Maximo de Sangue}
{217}{}{Lento}
{218}{}{Mais Rapido}
{219}{}{Sempre}
{220}{}{Muito}
{221}{}{Baixo}
{222}{}{Alto}
{223}{}{Mais Brilhante}
{224}{}{Amplo}
{300}{}{FEITO}
{301}{}{PAUSADO}
{1000}{}{Lamento, o menu das preferencias não esta}
{1001}{}{disponivel na versao demo.}
