{100}{}{Você vê: Lex.}
{101}{}{Você vê um perdedor.}
{102}{}{[Mais]}
{103}{}{[Pronto]}
{104}{}{[Lex sussurra.] Melhor tomar cuidado. O Rock nem sempre diz a verdade.}
{105}{}{Por que você diz isso?}
{106}{}{Por que eu deveria confiar em você?}
{107}{}{O Rock é membro dos Crypts, uma gangue. Ele tenta meter estranhos, como você, em encrenca. Se você o ouvir, pode acabar morto e enterrado.}
{108}{}{Quem é você?}
{109}{}{Obrigado pela informação. Tenha um bom dia.}
{110}{}{Sou o Lex. Scrapheap é meu lar, e acho que falo pelo povo dela.}
{111}{}{Mais alguém que eu deva conhecer?}
{112}{}{Bom, também há os Tolos. Eles controlariam Scrapheap, se os Crypts sumissem. As duas gangues brigam por quem controla este lugar. Atualmente, os Crypts estão por cima. Agora que você chegou, as coisas podem mudar.}
{113}{}{O que te faz dizer isso?}
{114}{}{Se você conseguisse se livrar das gangues, ficaríamos gratos. Não temos o número nem a força pra expulsá-los, e poucos se importam com este lugar. Se você se importa, então talvez possamos ajudar você.}
{115}{}{Como assim?}
{116}{}{Já ouvi falar de você. Você quer encontrar a cidade perdida de Necropolis. Um povo grato poderia fornecer informação sobre pra onde ir.}
{117}{}{Vou considerar.}
{118}{}{Não poderíamos pedir mais que isso.}
{119}{}{Tchau.}
{120}{}{Tenho algumas perguntas.}
{121}{}{E por que não deveria? Tenho o bem-estar do meu povo no coração, e gostaria de ver você sair ileso.}
{122}{}{Como assim?}
{123}{}{Há forças agindo aqui em Scrapheap que gostariam de te usar, e, se isso não for possível, de te ver morto e enterrado. Escolha seus amigos com sabedoria, e seus inimigos com ainda mais cuidado. Bom dia.}
{124}{}{É, bom dia.}
{125}{}{Agradecemos por se livrar dos Crypts e dos Tolos. Sem o gerador de energia, meu povo terá uma vida pobre. Você acha que conseguiria consertá-lo?}
{126}{}{Claro.}
{127}{}{Conserte você mesmo. Quero minha recompensa.}
{128}{}{Obrigado.}
{129}{}{Muito bem, você a terá. Você lançou meu povo numa noite fria e então nos abandonou aos lobos - mas entendo que sua missão é mais importante.}
{130}{}{A violência que você começou pode voltar direto pro meu povo. Por favor, termine o que começou.}
{131}{}{Típico de covardes como você jogar a tarefa da morte nos ombros dos outros.}
{132}{}{Estou nisso.}
{133}{}{Se você precisar de ajuda, eu forneço, mas não peça ao meu povo. Estão cansados demais de morte e dor. Vou me juntar a você, se é o que você deseja.}
{134}{}{Sim, me siga e ataque quando eu atacar.}
{135}{}{Não. Só estou fazendo um comentário social.}
{136}{}{Bem como eu suspeitava, você não se importa com nada além das próprias necessidades. Junte-se aos nossos inimigos, traga medo ao meu povo e traia sua própria origem.}
{137}{}{Vou te matar por dizer isso.}
{138}{}{É um plano. Estou me infiltrando nesta gangue.}
{139}{}{Cale a boca.}
{140}{}{Eu sabia que você faria, seu verme.}
{141}{}{Talvez, mas ações falam mais alto que palavras.}
{142}{}{Você vai ver.}
{143}{}{Com o que posso ajudar?}
{144}{}{Me fale sobre o gerador de energia.}
{145}{}{Me fale sobre os Crypts.}
{146}{}{Me fale sobre os Tolos.}
{147}{}{Me fale sobre Scrapheap.}
{148}{}{Nada mais, obrigado.}
{149}{}{Scrapheap é a nossa cidade. Era o nosso lar. E voltará a ser, com sorte.}
{150}{}{O gerador de energia fornece toda a eletricidade da cidade. Sem ele, com certeza morreríamos. É a coisa mais importante da cidade. Quem o controla, controla Scrapheap.}
{151}{}{Os Crypts são uma gangue comandada pelo Rayze. Ele é um animal e tem uma das maiores armas que eu já vi. Ele deixa o Lenny viver porque ele cuida dos brahmin, que fornecem combustível pro gerador. Os Crypts ficam na casa grande.}
{152}{}{A Baka lidera os Tolos. Se ela tivesse mais homens, com certeza atacaria os Crypts e tentaria retomar o gerador de energia. Dá pra diferenciar os Crypts dos Tolos pela armadura. Tolos usam metal, Crypts usam couro.}
