{100}{}{Você vê o Irwin.}
{101}{}{Ah rapaz, você não consegue me deixar em paz? Eu já tenho problemas o bastante na minha mao.}
{102}{}{Problemas? Talvez eu possa ajudar você.}
{103}{}{Como se você fosse o único com problemas.}
{104}{}{Okay, okay. Nenhuma razão pra gritar comigo.}
{105}{}{Hmm... Eu não sei. Exige um calibre diferente de heroi do que você. Escuta, por que você não volta quando você tiver um pouco mais de experiência?}
{106}{}{Isto é uma tragedia, acredite em mim. Nada e do modo como costumava ser. Eu tenho uma pequena fazenda fora da cidade e alguns dias atras um bando de saqueadores apareceu do nada e agora usam minha casa como acampamento deles. Eles mataram o Pugsley, meu burro e eles ameacaram me matar se eu ousasse voltar.}
{107}{}{Apenas me diga aonde e eu tomarei conta do resto.}
{108}{}{Lamento Irwin, mas eu tenho coisas mais importantes pra fazer.}
{109}{}{Realmente, você faria isso? Você sabe, eu não ouso ir lá mais. Por que você não volta e me deixa saber quando e seguro voltar pra casa de novo?}
{110}{}{Escute aberracao, eu disse a você pra me deixar em paz em primeiro lugar. Agora desapareca!}
{111}{}{Eu sabia que você ficaria com medo. Todos ficam quando esta relacionado aos saqueadores.}
{112}{}{Então, você foi capaz de ensinar a aqueles saqueadores uma licao? Meu lar esta seguro de novo?}
{113}{}{Com certeza esta, camarada.}
{114}{}{Eu não tive o tempo ainda de tomar conta disso.}
{115}{}{Ah, muito obrigado. Eu lamento que eu não tenho quaisquer riquezas para dar a você, mas aqui, leve este rifle por salvar minha casa.}
{116}{}{Você esta tentando me enganar, certo? Por favor não brinque comigo. Volte e me deixe saber quando estiver realmente seguro pra voltar pra minha casa, você entendeu?}
{117}{}{Muito obrigado por me ajudar.}
{200}{}{Você ganha }
{201}{}{ de experiência por salvar a fazenda do Irwin.}
{118}{}{Grunk?}
{119}{}{Olha, eu não tenho tempo pra idiotas. Volte quando você tiver smarts.}
{120}{}{Uh Huh, Uh Huh, Uh Huh. Eu fazer.}
{121}{}{Mim não consertar ainda.}
{123}{}{Num acha fazenda. Ocê mostra?}
{403}{}{tAnk-u!}
{300}{}{Encontre seu criador!}
{301}{}{Peguem ele... morto!}
{302}{}{Você acabou de ter seu ultimo pao com queijo!}
{303}{}{Eu perfurarei você igual a um queijo suico!}
{400}{}{Não exatamente. Você poderia me dizer de novo como chegar lá?}
{401}{}{Vou dizer, mas por favor se apresse. Quero voltar pra minha casa.}
{402}{}{Obrigado.}
{2000}{}{Primeiro, logo depois de sair do Hub, você vai seguir a estrada principal pra leste por alguns quilômetros, passando a velha estação ferroviária. Depois faça a volta pro sul, você vai achar a velha fazenda Cooper (é impossível não ver). Passe reto por ela, e então... }
{2001}{}{[Mais]}
{2002}{}{[Irwin explica as direções em grande detalhe. Tanto que você quase adormece. Passam-se minutos até você finalmente marcar as direções no seu Pip-Boy]}
{2500}{}{Obrigado por me devolver minha fazenda.}
{2501}{}{Obrigado de novo.}
{2502}{}{Há muito trabalho a fazer.}
{2503}{}{Esses saqueadores destruíram minha mesa.}
{2504}{}{Ai, meu Deus, você viu isto?}
{2505}{}{Olá.}
{2506}{}{Você ainda está aqui?}
{2507}{}{Espero que você dê um bom uso a essa arma!}
{2508}{}{Colocar minha fazenda pra funcionar de novo vai levar um tempo.}
{2509}{}{Bom te ver.}
{2510}{}{Como vai?}
